juspay/hyperswitch

- crates/router/src/core/payments/transformers.rs
Cancellation reason null in payments response
Fixed cancellation reason being null in payments response
manual
> chore: Add cancellation reason to response

- Cargo.lock
- crates/api_models/Cargo.toml
- crates/common_utils/Cargo.toml
- crates/drainer/Cargo.toml
- crates/masking/Cargo.toml
- crates/redis_interface/Cargo.toml
- crates/router/Cargo.toml
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/cybersource.rs
- crates/router/src/consts.rs
- crates/router/src/services/api/client.rs
- crates/router/src/services/encryption.rs
- crates/router_derive/Cargo.toml
- crates/router_env/Cargo.toml
- crates/storage_models/Cargo.toml
This PR updates all dependencies to their latest versions, except for `tracing` and `tracing-attributes`.
This should also fix a Dependabot security vulnerability reported about the `tokio` crate (GHSA-7rrj-xr53-82p7).
In addition, this PR replaces calls to the deprecated `base64::encode()` and `base64::decode()` methods with their `base64::Engine` alternatives. 
References for the `base64` changes:
- [`base64` crate release notes](https://github.com/marshallpierce/rust-base64/blob/d7fb31c4ada4ca45df5ae80ec691fa3a050d9c3e/RELEASE-NOTES.md).
- [`base64::Engine` trait documentation](https://docs.rs/base64/latest/base64/engine/trait.Engine.html). (`Engine` is a trait, thus needs to be imported everywhere base64 encoding/decoding needs to be done.)
N/A.
> build(deps): update deps

- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_update.rs
Customer ID is mandatory when an address or setup_future_usage is given. This was not being checked properly, leading to some edge cases. This PR fixes that.
None
Customer ID is mandatory when addresses are provided due to GDPR compliance, and is mandatory when setup future usage is given cuz the payment method needs to be saved and associated with the merchant's customer.
Same was #282
> fix(router): better positioning for mandatory customer id conditions

- .github/ISSUE_TEMPLATE/config.yml
- README.md
- docs/CONTRIBUTING.md
This PR fixes the broken Discord invite with a correct one.
N/A
N/A
> docs: fix broken Discord link

- crates/api_models/src/payment_methods.rs
Payment Experience is needed for SDK
N/A
Manual
> fix: Send payment experience on payment method list response

- crates/router/src/db/customers.rs
just something small I found when perusing the code
> perf: avoid making copies of strings

- Cargo.lock
- crates/router/src/services/api.rs
- crates/router/src/services/api/client.rs
Reuse reqwest clients for performance benefits
Have added caching for non-certificate authenticated clients using once cell
Moved request timeout parameters to request builder instead of client
Creating a client has a significant overhead, reusing the clients should increase perf
> feat(router): reuse reqwest clients for requests made to connectors

- crates/router/src/openapi.rs
- openapi/generated.json
- openapi/open_api_spec.yaml
- postman/collection.postman.json
Replaced sandbox base url https://sandbox-router.juspay.io/ with https://sandbox.hyperswitch.io/
tested manually
> chore: update sandbox base url

- README.md
- crates/router/src/openapi.rs
- docs/try_sandbox.md
- openapi/generated.json
- openapi/open_api_spec.yaml
- Make the option to three ( it was not updated in this PR #452 )
- Replace the dashboard link from https://dashboard-hyperswitch.netlify.app/ to https://app.hyperswitch.io/
Preview the file
> docs: fix quick start guide and update dashboard link

- config/Development.toml
- config/config.example.toml
- crates/router/src/configs/settings.rs
- crates/router/src/core/webhooks.rs
- loadtest/config/Development.toml
Allow enabling/disabling of outgoing webhooks based on environment configuration.
- [Development.toml](https://github.com/juspay/hyperswitch/blob/e5fa5655f8196aa125c09305fed4f6e8e5c1fb92/config/Development.toml) - Add a `webhooks` section with an `outgoing_webhooks` boolean key. Defaults to false in code.
Outgoing webhooks can be disabled for testing purposes.
> feat(router): allow enabling/disabling of outgoing webhooks based on env configuration

- crates/router/src/env.rs
First party crate logs were not being logged. This solves that.
Manual
> fix(router): allow console logs for all first-party crates

- crates/router/src/core/configs.rs
- crates/router/src/db/configs.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/configs.rs
- crates/router/src/types/api/configs.rs
- crates/router/src/types/transformers.rs
- crates/router_env/src/logger/types.rs
Added update endpoint for Config table.
Added a cached update on config table.
> feat: Add update endpoint for config

- config/docker_compose.toml
- docker-compose.yml
This change includes the following:
- Renaming producer & consumer to `hyperswitch`
- adding health-check to consumer and adding `depends_on` to prevent parallel compilation of router, consumer & producer
> feat: renaming services in docker-compose and set execution order

- crates/redis_interface/src/commands.rs
- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/core.rs
- crates/router/src/core/configs.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/db/configs.rs
- crates/router/src/lib.rs
- crates/router/src/routes.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/configs.rs
- crates/router/src/types/api.rs
- crates/router/src/types/api/configs.rs
- crates/router/src/types/transformers.rs
- crates/router_env/src/logger/types.rs
- crates/storage_models/src/configs.rs
Added fetch endpoint for config table.
This PR adds cached fetch to config table, for dynamically configuring application.
> feat(config): add fetch endpoint for config table

- crates/api_models/src/admin.rs
- crates/router/src/core/admin.rs
- crates/router/src/routes/admin.rs
- crates/router/src/routes/app.rs
- crates/router/src/types/api/admin.rs
- crates/storage_models/src/merchant_account.rs
This PR will add 2 extra routes providing a way to change the storage schema of a merchant with AdminApiKey
> feat: add a kv switch route for merchants

- docs/try_local_system.md
After dependencies and database are setup on Windows, the next step to be followed is to [configure the application](https://github.com/pixincreate/hyperswitch/blob/main/docs/try_local_system.md#configure-the-application) which is missing in the [docs](https://github.com/pixincreate/hyperswitch/blob/main/docs/try_local_system.md).
https://github.com/pixincreate/hyperswitch/blob/main/docs/try_local_system.md
After dependencies and database are setup on Windows, the next step to be followed is to [configure the application](https://github.com/pixincreate/hyperswitch/blob/main/docs/try_local_system.md#configure-the-application) which is missing in the [docs](https://github.com/pixincreate/hyperswitch/blob/main/docs/try_local_system.md). A windows user, who follow the guide should not get …
> docs(try_local_system): add next steps after installing dependencies on Windows

- crates/router/src/connector/adyen.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/tests/connectors/adyen.rs
- crates/router/tests/connectors/connector_auth.rs
- crates/router/tests/connectors/main.rs
- crates/router/tests/connectors/sample_auth.toml
Fixes #470 , #488 
add payment methods like affirm, klarna, afterpay support for adyen connector
#470
#488
> feat(connector): add afterpay,klarna,affirm support in adyen connector

- docker-compose.yml
…rswitch-server
increase docker health check interval for hyperswitch-server
> build(docker-compose): increase docker health check interval for hyperswitch-server

- add_connector.md
> docs(add_connector): fix typo

- crates/router/src/services/authentication.rs
- crates/router/src/utils.rs
- Making AppState generic in `authenticate_and_fetch`.
- Making functions public.
- Making `authentication_and_fetch` usable for extending projects.
> refactor(router): appstate as trait in authentication

- crates/router/src/routes/api_keys.rs
- crates/router/src/routes/app.rs
- crates/router/src/services/authentication.rs
- Refactored API keys routes to use `/api_keys/{merchant_id}`.
- Refactored authentication errors.
These changes enable extending projects to have merchant based authentication for api routes.
> refactor(router): api-key routes refactoring

- crates/router/src/routes/api_keys.rs
> bugfix(router): api keys path params

- CHANGELOG.md
- crates/router/src/core/payments.rs
- Add Changelog
- Decide connector on payment confirm only
> chore(release): port release bug fixes to main branch

- connector-template/mod.rs
- crates/api_models/src/webhooks.rs
- crates/router/src/connector/aci.rs
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/applepay.rs
- crates/router/src/connector/authorizedotnet.rs
- crates/router/src/connector/braintree.rs
- crates/router/src/connector/checkout.rs
- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/fiserv.rs
- crates/router/src/connector/globalpay.rs
- crates/router/src/connector/klarna.rs
- crates/router/src/connector/payu.rs
- crates/router/src/connector/rapyd.rs
- crates/router/src/connector/shift4.rs
- crates/router/src/connector/stripe.rs
- crates/router/src/connector/worldline.rs
- crates/router/src/connector/worldpay.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/routes/app.rs
- crates/router/src/types/api/webhooks.rs
This PR exposes additional details about the incoming webhooks request (particularly the method) to the various connector webhook functions.
None
Certain connectors like Worldline will peform an initial endpoint check by making a GET request to Hyperswitch. This case needs to be handled in the connector. This PR facilitates this handling.
> enhance(router/webhooks): expose additional incoming request details to webhooks flow

- crates/api_models/src/payments.rs
- openapi/generated.json
> docs(api_models): fix typo

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/routes/payment_methods.rs
This PR adds a field `eligible_connectors` to the list payment methods response which holds all connectors eligible for that payment method.
None
Required for the frontend to select the correct payment method for the correct connector.
Local testing, compiler-guided
> feat(router): include eligible connectors list in list payment methods

- crates/router/src/connector/aci.rs
- crates/router/src/connector/braintree.rs
- crates/router/src/connector/checkout.rs
- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/globalpay.rs
- crates/router/src/connector/klarna.rs
- crates/router/src/connector/payu.rs
- crates/router/src/connector/shift4.rs
- crates/router/src/connector/stripe.rs
- crates/router/src/connector/worldpay.rs
- crates/router/src/services/api.rs
- crates/router/src/services/api/request.rs
Added the debug log for connector request and responses in api.rs file instead of adding log to all connector files
> chore(connectors): log connector request and response at debug level

- crates/api_models/src/enums.rs
- crates/router/src/types/transformers.rs
- crates/storage_models/src/enums.rs
- Add frunk for attempt status
> feat(router): add foreign_into for attempt status

- crates/api_models/src/enums.rs
Update missed config details for bluesnap connector
> fix(connector): update Bluesnap in routable connectors 

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
Support filtering based on card_networks
Manual
> feat(pm_list): support filter based on card_networks and remove unused struct

- crates/router/src/core/payments/transformers.rs
Send metadata in response
Manual
> fix(core): send metadata in payments response

- .github/workflows/CI.yml
- crates/router/src/core/payment_methods/cards.rs
- crates/storage_models/src/api_keys.rs
> chore(workflow): check optional compilation

- config/Development.toml
- config/config.example.toml
- config/docker_compose.toml
- crates/api_models/src/enums.rs
- crates/router/src/configs/settings.rs
- crates/router/src/connector.rs
- crates/router/src/connector/bambora.rs
- crates/router/src/connector/bambora/transformers.rs
- crates/router/src/connector/nuvei/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/connector/worldpay.rs
- crates/router/src/connector/worldpay/requests.rs
- crates/router/src/connector/worldpay/response.rs
- crates/router/src/connector/worldpay/transformers.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/bambora.rs
- crates/router/tests/connectors/connector_auth.rs
- crates/router/tests/connectors/main.rs
- crates/router/tests/connectors/nuvei.rs
- crates/router/tests/connectors/sample_auth.toml
- loadtest/config/Development.toml
Updating support for [Bambora](https://dev.na.bambora.com/docs/references/payment_APIs/v1-0-5/#smooth-scroll-top) payment gateway
Payment Method: card
Supported payment flows
- Authorize
- Capture
- PSync
- Refund
- Cancel
- RSync
> feat(connector): [Bambora] Add support for cards Authorize, psync, capture, void, refund, Rsync

- crates/api_models/src/enums.rs
- crates/storage_models/src/enums.rs
- migrations/2023-02-28-072631_ang-currency/down.sql
- migrations/2023-02-28-072631_ang-currency/up.sql
Adding support for currency `ANG`
> feat: add support for `ANG` currency

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
This PR contains 2 changes
- Fixing deserialization of `card_network`
- Adding wallet filter in the filter_by_card_network to bypass the wallet in the case of that filter
> fix(list): fix card network filtering

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments/helpers.rs
- Check for payment_method_type as eps or ideal and then populate the eligible connectors
- Fix spelling for `MissingRequiredField`.
- Create a connector account and then call pm_list
```
{
"redirect_url": "https://www.example.com/success",
{
{
"payment_method_type": "eps",
"bank_names": [
{
"bank_name": [
"raiffeisen_bankengruppe_osterreich",
"volksbank_gruppe",
"dolomitenbank",
"erste_bank_und_sparkassen",
"volkskreditbank_ag",
"sparda_bank_wien",
"hypo_tirol_bank_ag",
"schoellerbank_ag",
"easybank_ag",
"bawag_psk_ag",
"bank_austria"
],
"stripe",
"adyen"
]
},
{
"bank_name": [
"capital_bank_grawe_gruppe_ag",
"brull_kallmus_bank_ag", …
```
> refactor(pm_list): pm_list for bank redirects

- crates/router/src/connector/nuvei/transformers.rs
- crates/router/src/routes/app.rs
add payment_method list route to payment_methods so that it is compatible with sdk  . Also fixed clippy warnings in nuvei
> refactor(core): add payment method list route to payment_methods

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments/helpers.rs
…method
Save card network in payment_methods table
```json
"customer_payment_methods": [
{
"payment_token": "token_ppk4UnVaoTaHnnLTIWV9",
"customer_id": "ExampleCustomer",
"payment_method_type": null,
"payment_method_issuer": null,
"payment_method_issuer_code": null,
"recurring_enabled": false,
"installment_payment_enabled": false,
"payment_experience": [
"redirect_to_url"
],
"card": {
"scheme": "Visa",
"issuer_country": null,
"last4_digits": "4242",
"expiry_month": "4",
"expiry_year": "24",
"card_token": "ba58f41c-6bc0-4fc8-8193-e67750290fb8",
"card_holder_name": null,
"card_fingerprint": "60270680-f9bd-4576-9246-c47bbcc0c8e0"
},
"metadata": null,
"created": "2023-02-28T11:59:12.831Z"
}
]
```
> feat: store card network for cards

- .typos.toml
fix CI pipeline spell check failure
> chore(typos): fix CI typos issue

- crates/api_models/src/payments.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/nuvei/transformers.rs
- crates/router/src/connector/payu/transformers.rs
- crates/router/src/connector/rapyd/transformers.rs
- crates/router/src/connector/worldpay/transformers.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/openapi.rs
- crates/router/tests/connectors/worldpay.rs
Api contract change for Applepay.
```
"wallet": {
"apple_pay": {
"payment_data": "eyJkYXRhIjoiRmJvdkhBRGJFenFueTNNUFIwR2lBSm5Ld1ltdXhhSTFwTGRMa0x5emNQZHk2Q0pBTElnbjg4eXc5dkY1ZUEwTDV4aGhkNkk0TmZpQTdNRm1qMHFBU0kzc2RjSExFK3V0d1ZwNjVqWEhnendkTnJmNFpkNUhGdDlPM3diTi9wckM2eEhmN3l6aExEL3A4aGx1bktzdHdlZi95eVlXNmJLZGY5dlplaGhKdmRJQ0h6b05UTGRBSlFyeUNWZ3ZCaFJ6cGlQamtJMlVjd3RuS2V4cTA2NFBMNHRXNEs4NzFDMGx0anMvV241NVV6Q3lTNTROUWZUZXBsZ0RiVklpdlphMDFVUzlpNFhwdm4xZzhRa1VhWUh4UEtIU3RqTi9TRlhlOGtYNjkwSGNWZHl1SWRJWmhob2xadzFnbEQ2SzFYcjdmSXBsL3VTY1pYOGFjNTJ4c2o0a3puWkp3WC9lU1ZlUEZUeVJBSy9SaHVWaXZISG5QR0JWZnVBQXdGTXk3aWFkNm43UUQ3RENVU0t4VE53R2ROcz0iLCJzaWduYXR1cmUiOiJNSUFHQ1NxR1NJYjNEUUVIQXFDQU1JQUNBUUV4RFRBTEJnbGdoa2dCWlFNR …
```
> api contract change for applepay

- .typos.toml
- crates/api_models/src/enums.rs
- crates/api_models/src/payments.rs
- crates/router/src/openapi.rs
- crates/router/src/routes/admin.rs
- crates/router/src/routes/api_keys.rs
- crates/router/src/routes/customers.rs
- crates/router/src/routes/mandates.rs
- crates/router/src/routes/payment_methods.rs
- crates/router/src/routes/payments.rs
- crates/router/src/routes/refunds.rs
- openapi/generated.json
This PR documents the OpenAPI security schemes for endpoints already documented on the OpenAPI specification file.
Including security schemes makes it easier for users of our APIs to understand the authentication used by each endpoint.
Verified with the rendered SwaggerUI page for the generated OpenAPI specification file.
> docs(openapi): document security schemes

- CHANGELOG.md
* **connectors:**  log connector request and response at debug level (#624) (6a487b19)
* **workflow:** adding build only sandbox feature to reduce build time (#664) (d1c9305e)
* **workflow:** run cargo hack only for code changes (#663) (f931c427)
* **openapi:**  document security schemes (#676) (c5fda7ac)
* **session_token:**  create session token only if pmt is enabled (#703) (e1afeb64)
* **router:**
*  serve OpenAPI docs at `/docs` (#698) (ed2907e1)
*  added incoming refund webhooks flow (#683) (f12abbce)
* **list:**  global filter mapping for payment methods via card network (#694) (adca6bca)
*  store card network for cards (#687) (bfca26d9)
*  add support for `ANG` currency (#681) (03096eff)
*  Add bank redirect mapping to adyen and stripe (#680) (e6f627d9)
*  api contract change for …
> Changelog for release V0.4.0

- crates/api_models/src/webhooks.rs
- crates/router/src/compatibility/stripe.rs
- crates/router/src/compatibility/stripe/app.rs
- crates/router/src/compatibility/stripe/refunds/types.rs
- crates/router/src/compatibility/stripe/webhooks.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/webhooks.rs
- crates/router/src/types/api/webhooks.rs
Add webhook support for stripe compatibility. There is a generic field added to the webhook core functions. Before the webhook is sent to the merchant it is transformed to the corresponding compatible type.
Manual
> feat(compatibility): add webhook support for stripe compatibility

- crates/router/src/routes/api_keys.rs
This PR documents the path parameters added to the API keys endpoints in #600.
Documenting the path parameters correctly makes it easier for users to try out our APIs via the SwaggerUI preview.
Generated the OpenAPI specification locally, tested the rendered Swagger UI preview.
> docs(openapi): document path parameters for API keys endpoints

- config/config.example.toml
- crates/router/src/services/api/client.rs
This PR simplifies the HTTP client construction code and makes it easier to understand.
N/A
Set up `mitmproxy` locally, verified that both HTTP and HTTPS traffic were proxied through it for connector API calls.
> refactor(client): simplify HTTP client construction

- crates/api_models/src/admin.rs
- crates/router/src/connector/fiserv.rs
- crates/router/src/core/admin.rs
- crates/router/src/db/merchant_account.rs
- crates/router/src/services/api.rs
- crates/router/src/types/api/admin.rs
- crates/router/tests/connectors/globalpay.rs
- crates/router/tests/payments.rs
- crates/router/tests/payments2.rs
- crates/storage_models/src/merchant_account.rs
- crates/storage_models/src/query/merchant_account.rs
- crates/storage_models/src/schema.rs
- migrations/2023-03-04-114058_remove_api_key_column_merchant_account_table/down.sql
- migrations/2023-03-04-114058_remove_api_key_column_merchant_account_table/up.sql
- openapi/generated.json
This PR removes the unused `api_key` field from the merchant account table and request/response schemas.
This PR includes migrations to remove the `api_key` column from the `merchant_account` table. The migrations can be found at [`up.sql`](https://github.com/juspay/hyperswitch/blob/remove-merchant-account-api-key-field/migrations/2023-03-04-114058_remove_api_key_column_merchant_account_table/up.sql) and [`down.sql`](https://github.com/juspay/hyperswitch/blob/remove-merchant-account-api-key-field/migrations/2023-03-04-114058_remove_api_key_column_merchant_account_table/down.sql) files.
N/A
N/A
---
~Marking as this as draft as this is blocked by #712 being merged to `main` branch.~
> chore(merchant_account): remove `api_key` field

- crates/masking/tests/basic.rs
This PR fixes tests in the `masking` crate with appropriate feature gates. When I ran `cargo hack` while including tests (using the command `cargo hack check --workspace --each-feature --all-targets`), I faced a few errors. This fixes that.
N/A
N/A
> test(masking): add suitable feature gates for basic tests

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/vault.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/scheduler/metrics.rs
- crates/router/src/scheduler/types/process_data.rs
- crates/router/src/scheduler/utils.rs
- crates/router/src/scheduler/workflows.rs
- crates/router/src/scheduler/workflows/tokenized_data.rs
- crates/router/src/types/storage/payment_method.rs
- crates/storage_models/src/payment_method.rs
The card stored in basilisk-v3 needs to be deleted after a specified time , in case the temporary card is not deleted session based we add the card to process tracker when the card is stored in vault
Needs to be tested on sbx
> feat: Time based deletion of temp card

- crates/router_env/src/logger/setup.rs
- docker-compose.yml
This PR aims at the following 3 things:
- It removes enter/exit logs generated by `instrument` from the console
- While keeping them present for `tempo`
- It adds authentication-less access to grafana in the local docker-compose setup
Attached in the subsequent comment is a log trail for a simple payment. With this change and without this change
> feat: removing unnecessary logs from console

- add_connector.md
- connector-template/mod.rs
- connector-template/test.rs
- connector-template/transformers.rs
- scripts/add_connector.sh
Update the add_connector script as per current code base
> refactor(connector): update add_connector script

- config/Development.toml
- docs/try_local_system.md
This PR updates the local setup guide to include the API key creation step.
Keeping the local setup documentation up-to-date with our codebase.
N/A
> docs(try_local_system): add API key creation step

- add_connector.md
- docs/try_local_system.md
This PR includes setup instructions for Ubuntu on WSL2.
N/A
I tried setting up our codebase on a relatively new Windows installation without WSL. The instructions included in this PR are the steps I followed in setting it up.
> docs(try_local_system): add Ubuntu on WSL2 setup instructions

- crates/router/src/core/api_keys.rs
- crates/router/src/core/customers.rs
- crates/router/src/core/mandate.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/vault.rs
- crates/router/src/core/payments/access_token.rs
- crates/router/src/core/payments/flows/authorize_flow.rs
- crates/router/src/core/payments/flows/cancel_flow.rs
- crates/router/src/core/payments/flows/session_flow.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/refunds.rs
- crates/router/src/routes/admin.rs
- crates/router/src/routes/api_keys.rs
- crates/router/src/routes/configs.rs
- crates/router/src/routes/customers.rs
- crates/router/src/routes/ephemeral_key.rs
- crates/router/src/routes/mandates.rs
- crates/router/src/routes/metrics.rs
- crates/router/src/routes/metrics/request.rs
- crates/router/src/routes/metrics/utils.rs
- crates/router/src/routes/payment_methods.rs
- crates/router/src/routes/payments.rs
- crates/router/src/routes/payouts.rs
- crates/router/src/routes/refunds.rs
- crates/router/src/routes/webhooks.rs
- crates/router/src/services/api.rs
- crates/router_env/src/logger/types.rs
This PR focuses on adding metrics to the `router` crate. 
> review-note: consider going through the `metrics.rs` file before reviewing the rest of the PR, while will provide more context while reviewing the rest of the code
> feat(router): adding metrics for tracking behavior throughout the `router` crate 

- crates/drainer/Cargo.toml
- crates/drainer/build.rs
- crates/drainer/src/settings.rs
- crates/router/Cargo.toml
- crates/router/src/build.rs
- crates/router/src/configs/settings.rs
- crates/router_env/Cargo.toml
- crates/router_env/src/env.rs
- crates/router_env/src/logger/formatter.rs
- crates/router_env/src/vergen.rs
This PR precisely has 2 changes.
1. It removes unnecessary features from diesel
2. It puts `vergen` under feature gate `(to be reviewed and discussed if necessary)`
The corresponding benchmarks are listed in below mentioned comments.
> generated using `cargo r --timings`
> feat: compile time optimization

- CHANGELOG.md
* **try_local_system:**
*  add Ubuntu on WSL2 setup instructions (#767) (1d2166cf)
*  add API key creation step (#765) (4b268068)
* **pm_list:**  handle client secret check (#759) (82344fc4)
*  add in-memory cache support for config table (#751) (abedaae4)
*  compile time optimization (#775) (5b5557b7)
* **router:**
*  add support for stateful straight through routing (#752) (568bf01a)
*  adding metrics for tracking behavior throughout the `router` crate  (#768) (d302b286)
* **core:**  accept gateway credentials in the request body in payments and refunds (#766) (cb188f92)
* **connector:**
*  Add support to provide connector_payment_meta for capture and void request (#770) (6c008ae6)
*  [Trustpay] add webhooks (payment and refund events) (#746) (853dfa16)
*  process delete response from …
> release: Update CHANGELOG for release v0.5.1

- crates/router/src/consts.rs
- crates/router/src/core/utils.rs
Change MAX_ID_LENGTH to 64. This allows merchants to pass payment_id's of max length 64.
Manual
> enhance(router): change MAX_ID_LENGTH to 64

- .github/workflows/manual-release.yml
- Dockerfile
- crates/router/Cargo.toml
This PR includes the initial changes required for building Docker images with the `production` feature of the `router` crate and using the `Production` run environment. In addition, the manual release workflow now accepts the environment to build the release image for.
Moving to production! :tada::rocket:
Created a new build, verified that the image looks for a `Production.toml` config file.
> chore: prepare for building production Docker images

- .github/workflows/CI.yml
- Dockerfile
This PR updates the `Dockerfile` to use the latest stable Rust toolchain instead of MSRV to build images, since newer versions of the compiler usually receive performance improvements as compared to the older versions. In addition, this PR updates the `Dockerfile` and CI workflow to use the new "sparse" index protocol to fetch crates from the crates.io registry.
Faster build times.
N/A
> docker: build using latest stable Rust toolchain and use sparse index protocol

- CHANGELOG.md
* **rfc:**  add rfc template & first RFC (#806) (01a5e0a0)
*  cards info api (#749) (b15b8f7b)
* **connector:**  [Nuvei] add webhook support (#795) (20b4372b)
* **compatibility:**  add last_payment_error in stripe payment response (#803) (97b95f0e)
* **api_models:**  enhance accepted countries/currencies types (#807) (f9ef3135)
* **services:**   make AppState impl generic using AppStateInfo (#805) (642c3f3a)
> Changelog for release v0.5.3

- crates/common_utils/Cargo.toml
- crates/common_utils/src/crypto.rs
- crates/router/src/types/api/webhooks.rs
- crates/router/src/types/domain.rs
- crates/router/src/types/domain/address.rs
- crates/router/src/types/domain/customer.rs
- crates/router/src/types/domain/merchant_account.rs
- crates/router/src/types/domain/merchant_connector_account.rs
- crates/router/src/types/domain/types.rs
- crates/storage_models/src/encryption.rs
- crates/storage_models/src/lib.rs
-  [x] Enhancement
This PR introduces type and conversions for field data
- `Encryptable<T>`: Domain type for storing encryption
- `Encrypted`: encrypted data to be present in storage_models
> feat(encryption): `Encryptable` domain type

- .github/workflows/CI.yml
Update CI workflows for common_enums crate.
> deps: update ci workflows for common_enums crate

- crates/api_models/src/admin.rs
- crates/api_models/src/enums.rs
- crates/router/src/core/admin.rs
- crates/router/src/core/payments/flows/authorize_flow.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/types/transformers.rs
- crates/storage_models/src/merchant_connector_account.rs
- crates/storage_models/src/schema.rs
- migrations/2023-04-03-082335_update_mca_frm_configs/down.sql
- migrations/2023-04-03-082335_update_mca_frm_configs/up.sql
Reverts juspay/hyperswitch#831
The frm_configs handled as a mandatory field in flows.
> Revert "added field frm_configs to MerchantConnectorAccount"

- crates/router/src/connector/nuvei.rs
- crates/router/src/connector/utils.rs
- crates/router/src/connector/worldpay.rs
- crates/router/src/connector/worldpay/response.rs
- crates/router/src/connector/worldpay/transformers.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/types/api/webhooks.rs
Add support for worldpay webhook
Manually triggered tests for worldpay in local and verified the response in DB
> feat(connector): [Worldpay] add support for webhook

- Cargo.lock
- crates/redis_interface/Cargo.toml
- crates/redis_interface/src/commands.rs
- crates/redis_interface/src/lib.rs
- crates/router/src/services.rs
This PR updates the `fred` dependency of the `redis_interface` crate from version `5.2.0` to `6.0.0`.
N/A
New features and improvements! ✨
Manually, compiler-guided.
> build(deps): bump `fred` from `5.2.0` to `6.0.0`

- crates/api_models/src/admin.rs
- crates/router/src/core/admin.rs
Change the type of `primary_business_details` in update merchant account to vector.
Allow updating primary_business_details
- Create a merchant account
- Update the primary_business_details
> fix(merchant_account): change `primary_business_details` to vec in update

- crates/router/src/compatibility/stripe.rs
- crates/router/src/compatibility/stripe/app.rs
- [ x] Enhancement
Added revoke mandate functionality in compatibility layer
> enhan(compatibility): added mandate revoke

- crates/api_models/src/payments.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
Adding required billing details field for Sofort bank transfer
- Sofort
```json
{
"payment_method_type": "sofort",
"sofort": {
"billing details": {
"billing_name": "Example"
},
"country": "AT",
"preferred_language": "en"
}
}
}
}
```
Billing details in Sofort bank transfer are needed for other connectors like PayPal.
Also discussed this with @bernard-eugine and made the change.
> feat(bank_redirects): modify api contract for sofort

- crates/router/src/connector/coinbase/transformers.rs
- crates/router/src/connector/opennode.rs
Make metadata as option parameter in response
> fix(connector): [coinbase] make metadata as option parameter

- crates/router/src/core/payments.rs
Make tokenization action clonable as it can be used by dependants. 
Compiles
> enhan(payments) : make TokenizationAction clonable

- crates/router/src/core/admin.rs
- crates/router/src/core/api_keys.rs
- crates/router/src/core/configs.rs
- crates/router/src/core/customers.rs
- crates/router/src/core/disputes.rs
- crates/router/src/core/errors/utils.rs
- crates/router/src/core/mandate.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_cancel.rs
- crates/router/src/core/payments/operations/payment_capture.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/operations/payment_start.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payments/operations/payment_update.rs
- crates/router/src/core/refunds.rs
- crates/router/src/types/api/mandates.rs
changing the below pattern code 
```
.map_err(|error| {
error.to_duplicate_response(errors::ApiErrorResponse::DuplicateMerchantAccount)
})?;
```
to 
```
.to_duplicate_response(errors::ApiErrorResponse::DuplicateMerchantAccount)?;
```
Manually, It compiles.
> refactor(storage_models, errors): impl StorageErrorExt for error_stack::Result<T, errors::StorageError>

- CHANGELOG.md
* **connector:**
*  [Shift4] add support for card 3DS payment (#828) (29999fe5)
*  [Nuvei] add support for card mandates (#818) (298a0a49)
* **bank_redirects:**  modify api contract for sofort (#880) (fc2e4514)
*  add template code for connector forte (#854) 
* **connector:**  [coinbase] make metadata as option parameter (#887) (f5728955)
*  Update events table after notifying merchant (#871) (ba013026)
* **stripe:**  remove cancel reason validation for stripe (#876) (fa44c1f6)
* **payments:**  make TokenizationAction clonable (#895) 
*  Frm integration with hyperswitch (#857)
*  use lowercase names for run environment and config files (#801) (ffaa8da0)
*  derive `Serialize` and `Deserialize` to `Country` enum (#882) (456c16fb)
* **storage_models, errors:**  impl StorageErrorExt for …
> doc:Changelog for release v0.5.7

- .github/workflows/manual-release.yml
This PR fixes the `EXTRA_FEATURES` environment variable not being passed correctly in the manual release workflow.
N/A.
N/A.
> ci(manual-release): fix `EXTRA_FEATURES` not being passed correctly

- crates/api_models/src/enums.rs
- crates/router/src/types/transformers.rs
- crates/storage_models/src/enums.rs
- migrations/2023-04-19-091353_add_status_to_events_table/down.sql
- migrations/2023-04-19-091353_add_status_to_events_table/up.sql
This PR adds support for webhooks for the `bank_debits` payment methods. Payment Succeeded case was already supported. Payments Failed was added in this PR.
[down.sql](https://github.com/juspay/orca/blob/999a1e5cfbce787a98fef4d6bb939dcd7797f66e/migrations/2023-04-19-091353_add_status_to_events_table/down.sql)
[up.sql](https://github.com/juspay/orca/blob/999a1e5cfbce787a98fef4d6bb939dcd7797f66e/migrations/2023-04-19-091353_add_status_to_events_table/up.sql)
Since the `bank_debits` payments have delayed notifications, the status will be updated by webhooks.
- ACH bank debits
- Success 
- Failed
- SEPA bank debits
- Succes
s
- Failed: Not possible
- Becs bank debit
-  Success
- Failed
> feat(webhooks): add support for `bank_debits`

- crates/router/src/compatibility/stripe/setup_intents/types.rs
> enhanc(compatibility) added merhcant connector details in setup_intents

- crates/router/src/core/admin.rs
- crates/router/src/core/customers.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/db/merchant_account.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/types/domain/address.rs
- crates/router/src/types/domain/customer.rs
- crates/router/src/types/domain/merchant_account.rs
- crates/router/src/types/domain/merchant_connector_account.rs
- crates/router/src/types/domain/types.rs
- crates/router/src/types/storage/merchant_connector_account.rs
- crates/router/src/types/transformers.rs
- crates/storage_models/src/merchant_connector_account.rs
- crates/storage_models/src/query/merchant_connector_account.rs
- crates/storage_models/src/schema.rs
Encryption for merchant connector account.
Manual
> feat(domain): add domain types for merchant connector account

- crates/router/tests/connectors/adyen.rs
Adyen has changed their response for invalid card expiry month case, because of which our unit test assertion failed. This PR has changes to assert the expected new error message from the Adyen.
> fix(connector): fix adyen unit test

- crates/router/src/core/customers.rs
The error message shown while creating the customer is inconsistent to the behaviour that it stands for.
Manual Testing & compiler guided
> chore: fix error message for deserialization

- .github/PULL_REQUEST_TEMPLATE.md
- docs/CONTRIBUTING.md
This PR updates the PR template with a checklist entry for API contract changes, and the contributing guidelines with recently added labels.
This should help with identifying API contract breaking changes in a better manner.
N/A
> doc(pr-template): add API contract changes and update contributing docs with recent labels

- README.md
Update the link to hyperswitch blog. The link was broken
Update the link to hyperswitch blog. The link was broken
Not applicable
> (docs) replaced stale link of hyperswitch blog

- crates/router/src/connector/nexinets/transformers.rs
- crates/router/src/connector/utils.rs
1) Add support for card mandates for nexinets
2) Add apple pay wallet for nexinets
1)Apple pay testing is pending(Need to generate apple pay token)
2)Manual testing in postman for mandates
**Customer initiated transaction for 3ds card**
**payment retrieval for CIT**
**Successful merchant initiated transaction without challenge**
> feat(connector): [Nexinets] add mandates and applepay support to nexinets

- crates/router/src/types/domain/address.rs
- crates/router/src/types/domain/customer.rs
- crates/router/src/types/domain/merchant_account.rs
- crates/router/src/types/domain/merchant_connector_account.rs
- crates/router/src/types/domain/merchant_key_store.rs
- crates/storage_models/src/address.rs
- crates/storage_models/src/customers.rs
- crates/storage_models/src/merchant_account.rs
- crates/storage_models/src/merchant_connector_account.rs
- crates/storage_models/src/merchant_key_store.rs
- migrations/2023-04-26-090005_remove_default_created_at_modified_at/down.sql
- migrations/2023-04-26-090005_remove_default_created_at_modified_at/up.sql
This closes #984 
#984 
Manual
> fix: remove defaults from `created_at` and `modified_at`

- README.md
Removed duplicate "more" word from the FAQs section in the REDME.md file
There was a typo.
No need for testing
> doc(README): remove redundant "more" in FAQs

- crates/router/Cargo.toml
Make aws dependencies optional
Make aws dependency since it's only used under those features
Manual
> build(deps): make AWS dependencies optional

- CHANGELOG.md
*  fix error message for deserialization ([#885](https://github.com/juspay/orca/pull/885)) ([e4d0dd0a](https://github.com/juspay/orca/commit/e4d0dd0a3885151a8e28a0246e67523f90f53076))
* **connector-sanity-tests:**  run tests on being queued for merge ([#960](https://github.com/juspay/orca/pull/960)) ([067dc709](https://github.com/juspay/orca/commit/067dc709360394b062c217ca3a27e011bfbac215))
* **manual-release:**  fix `EXTRA_FEATURES` not being passed correctly ([#912](https://github.com/juspay/orca/pull/912)) ([9c9c52f9](https://github.com/juspay/orca/commit/9c9c52f9af74ebc7e835a5750dd05967b39a0ade))
* **dashboard:**  add button that links to dashboard ([#934](https://github.com/juspay/orca/pull/934)) ([96f9e806](https://github.com/juspay/orca/commit/96f9e8068bfae0dd8479f69d4add675f1aaad99 …
> Doc:Changelog for release v0.5.8

- Cargo.lock
- crates/api_models/src/admin.rs
- crates/router/src/core/payments.rs
- crates/router/src/types/api/admin.rs
- crates/router/src/types/storage/payment_attempt.rs
- migrations/2023-05-03-121025_nest_straight_through_col_in_payment_attempt/down.sql
- migrations/2023-05-03-121025_nest_straight_through_col_in_payment_attempt/up.sql
This PR updates the `straight_through_algorithm` column in `payment_attempt` by nesting it.
- [up.sql](https://github.com/juspay/hyperswitch/blob/067c58422852f6671bc3d5d8df2e63ec7e11e4ce/migrations/2023-05-03-121025_nest_straight_through_col_in_payment_attempt/up.sql)
- [down.sql](https://github.com/juspay/hyperswitch/blob/067c58422852f6671bc3d5d8df2e63ec7e11e4ce/migrations/2023-05-03-121025_nest_straight_through_col_in_payment_attempt/down.sql)
This change provides us with a way to associate additional internal metadata with the payment attempt through the nested json column.
manual, compiler-guided. local query testing.
> refactor(router): nest the straight through algorithm column in payment attempt

- crates/drainer/src/main.rs
- crates/drainer/src/services.rs
- crates/redis_interface/src/lib.rs
- crates/router/src/bin/router.rs
- crates/router/src/bin/scheduler.rs
- crates/router/src/db.rs
- crates/router/src/lib.rs
- crates/router/tests/utils.rs
This fixes #1035 
#1035 
Manual
> fix: impl `Drop` for `RedisConnectionPool`

- crates/router/tests/connectors/worldline.rs
The test case named `should_throw_not_implemented_for_unsupported_issuer` failed because the `message` field in the `NotSupported` connector error was modified. This PR modifies the `message` field of the code by updating its value from `card` to `Maestro`.
> fix(connector) : [worldline] fix worldline unit test

- Cargo.lock
- crates/common_utils/src/pii.rs
This PR implements `From<Secret<>>` for the Email newtype.
Seamless conversions
> enhancement(common_utils): impl from for email newtype

- CHANGELOG.md
- Cargo.lock
This PR includes the changelog for `v0.5.10` and also adding it for `v0.5.9`
> docs(changelog): add changelog for v0.5.9 & v0.5.10

- .github/CODEOWNERS
This PR updates the CODEOWNERS file to match our current directory structure.
Ensuring the right users get requested for reviews.
N/A
> chore(CODEOWNERS): update CODEOWNERS

- CHANGELOG.md
- Cargo.lock
> docs(changelog): adding changelog for v0.5.10

- Cargo.lock
- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
This PR was not merged to main in #927 because of github not automatically changing the base branch when parent branch is merged to main.
Adds support for bank debits in the payment list, can be checked in #927 
```json
{
"payment_method": "bank_debit",
{
"payment_method_type": "ach",
"bank_names": null,
"bank_debits": {
"stripe"
]
}
}
]
}
```
> feat(pm_list): add pm list support for bank_debits 

- crates/router/src/connector/checkout.rs
- crates/router/src/connector/checkout/transformers.rs
This PR solves an issue with checkout webhooks where deserialization for payment related webhooks was failing.
- Fix the flow by decoupling body fields into separate structs.
- Make the merchant source verification secret optional (since if it's unavailable, we can still process webhooks through another flow)
None
Checkout sends different webhook bodies for payments and disputes webhooks.
Test reception of payment webhooks locally.
> fix(router): fix webhooks flow for checkout connector

- CHANGELOG.md
- crates/api_models/src/payments.rs
> docs(changelog): add changelog for 0.5.12

- .github/workflows/conventional-commit-check.yml
This PR adds a new workflow to verify that PR titles follow conventional commit standards.
This should help us have better changelogs.
N/A
> ci(workflows): add PR title check to verify conformance to conventional commit standards

- crates/common_utils/src/errors.rs
This PR adds two more parsing errors i.e., DateTimeParsingError and EmailParsingError to ParsingError enum
> feat(error): add `DateTimeParsingError` and `EmailParsingError` variants to `ParsingError` enum

- crates/router/src/connector/stripe/transformers.rs
@Narayanbhat166 had added  this accidentally 
```
// This is the case in
Pending,
```
and assured removing it won't break any flows.
```
StripePaymentStatus::RequiresPaymentMethod => Self::Failure,
```
This change done to accommodate manual retries
compiles
> fix(connector): fix Stripe status to attempt status map

- crates/router/src/connector/checkout.rs
Change the error handling condition for empty response from Bitwise OR, to OR over response `status_code`
In case of empty error response, a condition was added for 2 status_code which was in form of Bitwise OR.
> fix(connector): [Checkout] Change error handling condition for empty response

- CHANGELOG.md
Changelog from 0.5.12 to 0.5.13
> docs(CHANGELOG): add changelog for 0.5.13

- crates/router/src/connector/dummyconnector.rs
In the before implementation we are expecting `payment_method_type` in the request data, which is not being sent by the dashboard. So this is a fix for that.
Postman
> fix(connector): change payment method handling in dummy connector

- CHANGELOG.md
Added changelog for 0.5.14 release
> docs: add changelog for v0.5.14

- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/transformers.rs
The `disabled` field in the merchant connector account, was being populated, but it's presence wasn't being validated during a payment. This PR resolves this issue.
> fix(merchant_connector_account): add validation for the `disabled` flag

- crates/api_models/src/enums.rs
Currently, Signifyd is mentioned in connectors enum, but not routable connectors enum...this PR is to add that 
Currently, Signifyd is mentioned in connectors enum, but not routable connectors enum...this PR is to add that
> fix(connector) : Added signifyd to routableconnectors for frm

- crates/router/src/core/payouts.rs
- crates/router/src/core/payouts/helpers.rs
- crates/router/src/core/payouts/validator.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/payouts.rs
> update flows and add helper functions for payouts

- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payouts.rs
- crates/router/src/core/utils.rs
- crates/storage_models/src/payout_create.rs
- crates/storage_models/src/schema.rs
- migrations/2023-05-02-102332_payout_create/up.sql
> feat: payout use mca in payout_data

- crates/router/src/connector/checkout/transformers.rs
Checkout Transaction Type(Event type) - Payment Declined was mapped to incorrect Incoming Webhook Event
> fix(connector): [Checkout] Fix incoming webhook event mapping

- crates/api_models/src/enums.rs
> revert: fix(connector): Added signifyd to routableconnectors for frm

- Cargo.lock
- crates/api_models/src/enums.rs
- crates/storage_models/src/enums.rs
Interac was not available as payment method so I added it
I tested it using postman
> feat(connector):  add Interac as Payment Method Type

- crates/redis_interface/src/commands.rs
Add mget(get values of multiple keys) functionality in redis interface
This is needed for getting multiple values for the given keys at once
Postman
> feat(redis_interface): implement `MGET` command

- .github/git-cliff-changelog.toml
- .github/git-cliff-release.toml
This PR simplifies the `git-cliff` config files, since our commits on the `main` branch now stick to the Angular conventional commit specification.
N/A
N/A
> chore(git-cliff): simplify `git-cliff` config files

- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/core/payouts.rs
- crates/router/src/core/payouts/helpers.rs
- crates/router/src/core/utils.rs
- crates/router/src/types.rs
- add status checks before payout fulfillment and cancellation
- fix default PayoutStatus across flows to RequiresCreation
> refactor: payout flow corrections

- crates/router/src/db.rs
- crates/router/src/db/cards_info.rs
Very simply implement `CardsInfoInterface` for `MockDB`, allowing looking up of card info, the only trait method
Closes #1189.
Code change is simple enough that I didn't find tests necessary, although I am happy to add a unit test if desired.
> feat(router): implement `CardsInfoInterface` for `MockDB`

- connector-template/transformers.rs
- crates/router/src/connector/bitpay/transformers.rs
- crates/router/src/connector/iatapay/transformers.rs
Change amount to refund_amount in iatapay, bitpay and connector template
> fix(refund): change amount to refund_amount

- Cargo.lock
- crates/router/src/configs.rs
- crates/router/src/configs/kms.rs
> refactor(configs): make kms module and KmsDecrypt pub

- Cargo.lock
- crates/common_enums/Cargo.toml
- crates/common_utils/Cargo.toml
- crates/common_utils/src/pii.rs
- crates/drainer/Cargo.toml
- crates/masking/Cargo.toml
- crates/masking/src/diesel.rs
- crates/router/Cargo.toml
- crates/router_derive/Cargo.toml
- crates/storage_models/Cargo.toml
- crates/storage_models/src/api_keys.rs
- crates/storage_models/src/enums.rs
- crates/storage_models/src/lib.rs
- crates/storage_models/src/schema.rs
This PR updates the `diesel` dependency from version `2.0.3` to version `2.1.0`. In addition, this PR includes the schema generated by `diesel_cli v2.1.0` to fix failing CI checks for some PRs since the new release of `diesel_cli`.
Keeping up with new versions of dependencies, and fixing failing CI checks.
Started the server, created a payment successfully via Postman.
> build(deps): bump `diesel` from `2.0.3` to `2.1.0`

- crates/router/src/connector/coinbase/transformers.rs
Remove non-mandatory fields like name and description from request.
> fix(connector): [coinbase] remove non-mandatory fields

- crates/router/src/connector/rapyd/transformers.rs
> fix(connector): [Rapyd] Fix payment response structure

- crates/router/src/services.rs
Fixes subscriber error message on the startup.
NA
Manual
> fix(router): subscriber return type

- CHANGELOG.md
Add changelog to to v0.5.15
NA
Na
> docs: Add changelog to 0.5.15

- crates/router/src/db.rs
- crates/router/src/db/events.rs
>  feat(db): implement `EventInterface` for `MockDb` 

- crates/router/src/compatibility/stripe/payment_intents/types.rs
map connector to routing in payments request for backward compatibility
> refactor(compatibility): map connector to routing in payments request for backward compatibility

- crates/router/src/connector/opennode/transformers.rs
> fix(connector): [opennode] webhook url fix

- crates/router/src/connector/noon/transformers.rs
Add additional field in the Noon Payments Request, so that payment can be identified in the flows like Webhooks
The tunnelling via Euler needs this to recognise Webhooks
> feat(Connector): [Noon] Add reference id in Order Struct

- .github/ISSUE_TEMPLATE/bug_report.yml
Updated the command for getting the app version in `bug_report.yml` as the command was changed 2 months back.
I wasted 10+ mins looking for the command to file the bug report. 
No tests needed.
> fix(docs): Update command for getting app version

- crates/router/src/connector/zen/transformers.rs
Apple Pay payment method config should follow standard structure while storing it in connector merchant account meta data.
> refactor(connector): [Zen] refactor connector_meta_data for zen connector applepay session data

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_cancel.rs
- crates/router/src/core/payments/operations/payment_capture.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/operations/payment_start.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payments/operations/payment_update.rs
This PR adds a `mandate_connector` field to the `PaymentData` struct
None
The mandate connector must be taken into consideration during routingx
> feat(router): add mandate connector to payment data

- crates/router/src/core/payments/helpers.rs
This PR will update the customer details in payment, when sent in the payments request.
Fixes #1325 
- Create a payment with no email and check the new customer created
- Create a payment with email id passed 
- Email id should be updated
> fix: update customer data if passed in payments

- crates/router/src/db/merchant_connector_account.rs
- crates/storage_models/src/merchant_connector_account.rs
The main motivation is to have MockDb stubs, help to void mocking, and invocation of external database api's.
For more information check https://github.com/juspay/hyperswitch/issues/172
Fixes [1123](https://github.com/juspay/hyperswitch/issues/1123)
> feat(db): implement `MerchantConnectorAccountInterface` for `MockDb`

- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/connector/trustpay/transformers.rs
> refactor(compatibility): add holder name and change trustpay merchant_ref id to payment_id

- crates/router/src/connector/aci/transformers.rs
- crates/router/src/connector/zen.rs
- crates/router/src/connector/zen/transformers.rs
- `Zen`: Additional Error Handling is required to map the possible response from the connector
- `ACI`: An optional field was being consumed as a mandatory field so it has been changed to optional
To resolve 500 internal server errors we got on SBX.
> fix(connector): [Zen][ACI] Error handling and Mapping 

- crates/router/src/connector/shift4.rs
Previously , In connector shift4 pretask is executed if auth_type is `threeds` . This breaks bank redirects if auth_type is `threeds` . This pr adds validation for shift4 that pretask is executed only if payment_method is `Card`.
> fix(connector): [Shift4] validate pretask for threeds cards 

- crates/router/src/connector/trustpay.rs
- crates/router/src/connector/trustpay/transformers.rs
TrustPay Transaction Status api throws error in a different structure which should be handled separately from other TrustPay API's.
> fix(connector): fix trustpay error response for transaction status api

- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
Fix amount_capturable field in payments response.
> fix(core): fix amount capturable in payments response

- crates/router/src/core/customers.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/services/authentication.rs
attempt to address unintended 5xx and 4xx in payments
> refactor(payments): attempt to address unintended 5xx and 4xx in payments

- crates/api_models/src/enums.rs
SDK doesn't support bank names with special characters, So from the backend we will return snake case enums without any special characters
> fix(api_models): fix bank namings

- crates/router/src/connector/stripe.rs
Splitting the transformation and encoding part on stripe body construction
> fix(stripe): fix logs on stripe connector integration

- crates/router/src/connector/noon/transformers.rs
Add Support for wallets
- [GooglePay](https://docs.noonpayments.com/payment-method/googlepay/introduction)
- [ApplePay](https://docs.noonpayments.com/payment-method/applepay/introduction)
- [PayPal](https://docs.noonpayments.com/payment-method/paypal/introduction)
> feat(connector): [Noon] Add GooglePay, ApplePay, PayPal Support

- crates/router/src/connector/adyen/transformers.rs
For Adyen connector auto capture payment we can rely on create payment call for Success status
> fix(connector): [Adyen] fix charged status for Auto capture payment

- crates/router/tests/connectors/adyen.rs
The status mapping for auto capture has changed from "Pending" to "Charged," causing our unit test assertion to fail. This PR includes changes to assert the status as "Charged".
> fix(connector): [Adyen] fix unit test

- crates/api_models/src/payments.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_update.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/db/payment_intent.rs
- crates/storage_models/src/payment_intent.rs
- crates/storage_models/src/schema.rs
- migrations/2023-06-18-042123_add_udf_column_in_payments/down.sql
- migrations/2023-06-18-042123_add_udf_column_in_payments/up.sql
In this PR , 
`routing_parameters` and `data`  are removed from metadata.
`udf` field was added in `PaymentsRequest`
Backwards compatibility for order_details in metadata is maintained but will be deprecated in the future.
I tested everything and it worked fine.
> refactor(payments): add udf field and remove refactor metadata

- crates/router/src/connector/airwallex/transformers.rs
> fix(connector): [Airwallex] Fix refunds

- crates/router/src/connector/trustpay/transformers.rs
add missing failure status `800.100.172` for trustpay
> fix(connector): [Trustpay] add missing failure status

- crates/router/src/connector/stripe.rs
> refactor(fix): [Stripe] Fix bug in Stripe

- config/development.toml
```
{
"name": "ROUTER__PM_FILTERS__ADYEN__GOOGLE_PAY__COUNTRY",
"value": "AU,NZ,JP,HK,SG,MY,TH,VN,BH,AE,KW,BR,ES,UK,SE,NO,SK,AT,NL,DE,HU,CY,LU,CH,BE,FR,DK,RO,HR,LI,MT,SI,GR,PT,IE,CZ,EE,LT,LV,IT,PL,TR,IS,CA,US"
},
{
"name": "ROUTER__PM_FILTERS__ADYEN__GOOGLE_PAY__CURRENCY",
"value": "AED,ALL,AMD,ANG,AOA,ARS,AUD,AWG,AZN,BAM,BBD,BDT,BGN,BHD,BMD,BND,BOB,BRL,BSD,BWP,BYN,BZD,CAD,CHF,CLP,CNY,COP,CRC,CUP,CVE,CZK,DJF,DKK,DOP,DZD,EGP,ETB,EUR,FJD,FKP,GBP,GEL,GHS,GIP,GMD,GNF,GTQ,GYD,HKD,HNL,HTG,HUF,IDR,ILS,INR,IQD,ISK,JMD,JOD,JPY,KES,KGS,KHR,KMF,KRW,KWD,KYD,KZT,LAK,LBP,LKR,LYD,MAD,MDL,MKD,MMK,MNT,MOP,MRU,MUR,MVR,MWK,MXN,MYR,MZN,NAD,NGN,NIO,NOK,NPR,NZD,OMR,PAB,PEN,PGK,PHP,PKR,PLN,PYG,QAR,RON,RSD,RUB,RWF,SAR,SBD,SCR,SEK,SGD,SHP,SLE,SOS,SRD,STN,SVC,SZL,THB,TND,TOP,TRY,TTD,TWD,TZS,UAH,UGX,USD,UYU,UZS,VEF, …
```
> fix: update adyen payment method supported countries and currencies in develpment.toml

- crates/api_models/src/payments.rs
- crates/router/src/connector/stripe/transformers.rs
Stripe do not accept sort code in xx-xx-xx format. Therefore removed "-" while passing sort code to stripe
>  fix(connector): [Stripe] Fix bug in Stripe Bacs Bank Debit 

- crates/router/src/connector/mollie/transformers.rs
It can't be tested as, we are unable to enable this payment method from Mollie dashboard.
> feat(connector): [Mollie] Implement Sepa Direct Debit

- crates/router/src/routes/app.rs
Add configs create route back
NA
Manual
> fix: add config create route back

- crates/router/src/core/payment_methods/vault.rs
attached appropriate printable text in the result returned from `delete_tokenized_data()`.
> fix: add appropriate printable text for Result returned from delete_tokenized_data()

- crates/router/src/core/payment_methods/cards.rs
- openapi/openapi_spec.json
This pr will return an empty array when merchant does not have any payment methods configured.
> fix(payment_methods): return an empty array when the merchant does not have any payment methods

- crates/api_models/src/payouts.rs
- crates/router/src/core/errors.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/core/payment_methods/vault.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payouts.rs
- crates/router/src/core/payouts/helpers.rs
- crates/router/src/core/payouts/validator.rs
- crates/router/src/db/locker_mock_up.rs
- crates/storage_models/src/locker_mock_up.rs
- crates/storage_models/src/payouts.rs
- crates/storage_models/src/schema.rs
- migrations/2023-06-23-105727_alter_payouts/down.sql
- migrations/2023-06-23-105727_alter_payouts/up.sql
- migrations/2023-07-03-072633_alter_locker_mock_up/down.sql
- migrations/2023-07-03-072633_alter_locker_mock_up/up.sql
- [x ] This PR modifies the database schema
> feat: add basilisk support for storing generic account details

- .github/cocogitto-changelog-template
- .github/workflows/release-new-version.yml
- .typos.toml
- CHANGELOG.md
- cog.toml
This PR introduces a new workflow to create tags on schedule, with the aid of `cocogitto`. In addition, this adds a `cocogitto` template for updating the changelog file. The changelog file has also been updated with recent changes.
I'll take up generating the release notes and GitHub release in a separate PR.
We aim to have daily releases.
https://github.com/juspay/hyperswitch/actions/runs/5474468598
> ci: add workflow to create tags on schedule

- crates/api_models/src/payments.rs
- crates/router/src/compatibility/stripe/payment_intents.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/setup_intents.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/routes/payments.rs
- crates/router/src/services/authentication.rs
- openapi/openapi_spec.json
add client_secret auth for payments retrieve in core and compatibility layer.
> feat(payments): add client_secret auth for payments retrieve

- .github/workflows/auto-release-tag.yml
- Also push to public docker repositories for all release tags
> ci(docker): update docker push tags for releases

- config/development.toml
- crates/router/src/configs/settings.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/core/utils.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/aci.rs
- crates/router/tests/connectors/utils.rs
Currently connectors are sending payment_intent_id or payment_attempt_id to connectors as merchant reference and being used in webhook flows.
But for retries we need to standardize reference_id based on config set by merchant and send a standard value to connectors which connector flows can pass it to connector without any modification.
1. without config set
2. config set but merchant not enabled
3. config set and merchant enabled
> feat(router): add connector_request_reference_id in router_data based on merchant config

- Cargo.lock
- crates/router/src/core/payments/helpers.rs
- crates/storage_models/src/payment_intent.rs
add client secret in redirect response
Manual
> feat(payments): add client secret in redirect response 

- crates/router/tests/connectors/selenium.rs
- crates/router/tests/connectors/stripe_ui.rs
This pr contains  :
1) support for affirm ui tests in selenium
2) stripe affirm ui tests
ui test for stripe affirm(paylater)
> test(connector): [stripe] Add ui test for affirm

- crates/router/src/core/api_keys.rs
We were providing api key for non existing merchant id also.So, this issue is solved in this PR
Fix the issue for sending Api key for non existing merchant
> fix(api_keys): fix API key being created for non-existent merchant account

- crates/router/src/connector/adyen/transformers.rs
Fix Klarna and other payment method mandates for Adyen
Klarna  & GPAY
IDEAL MIT
> fix(connector): [Adyen] Fix Klarna mandates for Adyen

- crates/common_enums/src/enums.rs
- crates/common_enums/src/transformers.rs
- crates/router/src/types/transformers.rs
- openapi/openapi_spec.json
> fix(connector): [Adyen] Add bizum in common enums

- Cargo.lock
- crates/router/src/connector/powertranz.rs
- crates/router/src/connector/powertranz/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/core/payments/flows.rs
3DS support for cards payment through powertranz connector
To support 3ds cards through powertranz connector
> feat(connector): [PowerTranz] Add cards 3ds support for PowerTranz connector

- crates/router/src/configs/settings.rs
- crates/router/src/core/utils.rs
add parsing for `connector_request_reference_id` env
Env
Config while running application
> fix(router): add parsing for `connector_request_reference_id` env

- crates/router/src/connector/powertranz.rs
- crates/router/src/connector/powertranz/transformers.rs
resolve pr comments and add comments
resolve pr comments and add comments for #1722
> fix(connector): [PowerTranz] resolve pr comments and add comments

- crates/router/src/connector/powertranz.rs
If connector doesn't support Rsync flow then we should return the current refund status without any error.
> fix(connector): [PowerTranz] fix rsync not implemented error

- crates/router/tests/connectors/adyen_uk_ui.rs
Bizum payment method is adyen connector is currently throwing 500 from connector side so ignoring it for now
> fix(adyen_ui): ignore tests failing from connector side

- crates/router/src/connector/adyen/transformers.rs
- crates/router/tests/connectors/adyen_uk_ui.rs
Previously error message is sent "NULL" when there is fraud error message sent from Adyen Connector. Currently, we ll be sending the right error message.
> fix(connector): [Adyen] Fix error message for fraud check from Adyen connector

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
Add configs for PayPal wallet mandates for Adyen Connector
> chore(config): [Paypal] Add configs for PayPal mandates for adyen

- crates/router/src/core/payments/helpers.rs
restrict unknown customer_id to be pass in payment confirm and update call
> fix(router): restricted unknown customer_id to be pass in payment confirm and update call

- .github/workflows/connector-ui-sanity-tests.yml
- .typos.toml
- crates/router/tests/connectors/main.rs
- crates/router/tests/connectors/nexinets_ui.rs
Add ui tests for nexinets 
This ui tests cover bank redirects, 3ds cards and paypal for connector nexinets .
ui tests
> test(connector): [Nexinets] Add UI test for Nexinets Payment methods

- crates/api_models/src/payments.rs
- crates/common_enums/src/enums.rs
- crates/common_enums/src/transformers.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/setup_intents/types.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types/transformers.rs
- openapi/openapi_spec.json
This reverts commit 33a1368e8a0961610d652f5a6834ba37b995582a. (PR #1703)
Revert pix
#1703, was breaking redirection flows
> revert: feat(connector): [Adyen] Add pix support for adyen

- README.md
> docs: add renewed links for readme

- crates/router/src/connector/trustpay/transformers.rs
…s name
update cardholder name with billing address name
> fix(connector): [Trustpay] update cardholder name with billing address name

- crates/router/src/routes/payments.rs
Remove the request from being logged during payments and other API calls for security reasons
The HTTP request can contain the user IP address & other sensitive info,
instead of trying to mask those values we will remove this altogether
locally via json logs
> fix(logs): remove request from logs

- crates/api_models/src/payments.rs
- crates/router/src/connector/dummyconnector/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
- openapi/openapi_spec.json
There was api contract change in #1706 for wechatpay qrcode flow . This pr have corresponding changes for Stripe
There was api contract change in #1706 for wechatpay qrcode flow . This pr have corresponding changes for Stripe
tested using hs tool
> fix(connector): [Stripe] change payment_method name Wechatpay to wechatpayqr

- crates/router/src/connector/trustpay.rs
- crates/router/src/connector/trustpay/transformers.rs
unify error_code, error_message and error_reason in error response
Cards 2xx error response
Cards 4xx error response
Bank redirects error response
> feat(connector): [Trustpay] unify error_code, error_message and error_reason in error response

- crates/api_models/src/payments.rs
- crates/router/src/core/payments/helpers.rs
Make `AdditionalCardInfo` optional to make it compatible with card payment method data which doesn't have those  fields. 
Some times the payments can happen through token and this data is not populated
This was pushed as a hotfix. It was tested on prod.
> fix(payments): all AdditionalCardInfo fields optional

- crates/router/src/connector/adyen.rs
- crates/router/src/connector/bitpay.rs
- crates/router/src/connector/braintree.rs
- crates/router/src/connector/cashtocode.rs
- crates/router/src/connector/coinbase.rs
- crates/router/src/connector/opennode.rs
- crates/router/src/connector/payeezy.rs
- crates/router/src/connector/payme.rs
- crates/router/src/connector/rapyd.rs
> fix(connector): refactor psync and rsync for connectors

- .github/workflows/connector-ui-sanity-tests.yml
- .typos.toml
Adding support to run trigger ui tests with workflow dispatch
NA
NA
> fix(ui-tests): allow ui tests on workflow dispatch

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
- openapi/openapi_spec.json
Hotfix [#1852](https://github.com/juspay/hyperswitch/pull/1852)
> fix(payment_methods): add `requires_cvv` field to customer payment method list api object

- crates/router/src/connector/payme.rs
- crates/router/src/connector/payme/transformers.rs
Add support for PSync, RSync and web hook flow
Postman Testing
> feat(connector): [Payme] Add Sync, RSync & webhook flow support

- crates/router/src/scheduler/workflows/payment_sync.rs
Currently, the `pt_mapping` only supported configuration set directly in the redis which can be in-consistent. This PR stabilizes this by adding support for picking the config directly from the `configs`
Tested the set functionality of config table, and then the parsing of the entry in the function changed here
> feat(config): add config support to pt_mapping along with redis

- crates/router/src/configs/kms.rs
- Mismatched ordering for decryption
> fix(kms): fix kms decryption for jwe keys

- crates/router/src/connector/bluesnap.rs
- crates/router/src/connector/bluesnap/transformers.rs
unified error message & errorCode for blueSnap connector
> feat(connector): unified error message & errorCode for blueSnap connector

- crates/router/src/utils.rs
skip payment intent fetch for single business details merchant in webhook source verification
Multiple MCA
Source verification
Single MCA
Source verification
> feat(router): skip payment_intent fetch for single business details merchant in webhook source verification

- connector-template/mod.rs
Made some changes in the `connector_template` .
No test was required
> refactor(connector): update the `connector_template` 

- crates/common_enums/src/enums.rs
- openapi/openapi_spec.json
Added a variant in `ConnectorType` enum to specify payout processors. This will be used to validate the connectors configured by the merchant for payouts.
> chore: add connector functionality validation based on connector_type

- config/config.example.toml
- config/docker_compose.toml
This PR adds `payout_connector_list` config to docker_compose and config.example toml files
Hyperswitch-server container was not starting because of this missing config
> chore(configs): add `payout_connector_list` config to toml

- crates/router/src/connector/paypal.rs
send valid error_reason in all the error responses
> fix(connector): [Paypal] send valid error_reason in all the error responses

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- crates/api_models/src/payments.rs
- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/connector/payme.rs
- crates/router/src/connector/payme/transformers.rs
- crates/router/src/connector/trustpay/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/flows.rs
- crates/router/src/core/payments/flows/authorize_flow.rs
- crates/router/src/core/payments/flows/session_flow.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
- openapi/openapi_spec.json
payme preprocessing
Addung preprocessing flows
Manual
> feat(connector): [PayMe] Implement preprocessing flow for cards (#1904)

- .github/workflows/postman-collection-runner.yml
- postman/adyen_uk.postman_collection.json
- postman/checkout.postman_collection.json
- Fix Adyen UK and Checkout collections
- Disable Globalpay from running indefinitely given its inconsistencies
- Out of 15 iterations, the connector failed 7 times
Ran the collections
> ci(postman): Fix Adyen_UK, Checkout collections and disable Globalpay from running indefinitely

- crates/router/src/connector/payme/transformers.rs
Add partial capture validation for payme connector
Add partial capture validation for payme connector
Manual Testing
> fix(connector): [Payme] Fix for partial capture validation

- .typos.toml
- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- crates/api_models/src/payments.rs
- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/connector/cashtocode/transformers.rs
- crates/router/src/connector/payme.rs
- crates/router/src/connector/payme/transformers.rs
- crates/router/src/connector/trustpay/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/flows.rs
- crates/router/src/core/payments/flows/authorize_flow.rs
- crates/router/src/core/payments/flows/session_flow.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
- openapi/openapi_spec.json
Add cards non 3ds, Sync &Rsync support for payme connector
Commits from below PR's,
https://github.com/juspay/hyperswitch/pull/1831
https://github.com/juspay/hyperswitch/pull/1862
https://github.com/juspay/hyperswitch/pull/1922
https://github.com/juspay/hyperswitch/pull/1940
Manual Testing
> feat(connector): [Payme] Add cards non 3ds, Sync &Rsync support for connector

- crates/router/src/core/payments/helpers.rs
During the `make_pm_data` we construct a key (`pm_token_{token}_{payment_method}_hyperswitch`) using the token that is received in the request and try to get the value store in redis for that key. If there is no value present for that particular key then we were just returning the token we got thinking it is a locker (V3) token not the parent token. There was a pr (#1929) in which parent token was being generated even while doing a payment using the new card, so now in the `make_pm_data` the code to return the received token if its not parent token was removed thinking we will always receive parent token. The similar change was not done for the payment methods like  BankTransfer, Wallet, BankRedirect because of which it was still returning the locker (V3) token and it was failing during …
> fix(payment_methods): return parent_payment_method_token for other payment methods (BankTransfer, Wallet, BankRedirect)

- .github/workflows/postman-collection-runner.yml
Hope this is the last fix for this. 
Remove red
No tests needed
> ci(postman): remove step skipping tests for PRs

- crates/router/src/core/payments/helpers.rs
During the make_pm_data we construct a key (pm_token_{token}_{payment_method}_hyperswitch) using the token that is received in the request and try to get the value store in redis for that key. If there is no value present for that particular key then we were just returning the token we got thinking it is a locker (V3) token not the parent token. There was a pr (https://github.com/juspay/hyperswitch/pull/1929) in which parent token was being generated even while doing a payment using the new card, so now in the make_pm_data the code to return the received token if its not parent token was removed thinking we will always receive parent token. The similar change was not done for the payment methods like BankTransfer, Wallet, BankRedirect because of which it was still returning the locker …
> fix(payment_methods): return parent_payment_method_token for other payment methods (BankTransfer, Wallet, BankRedirect) 

- crates/router/src/core/payments/helpers.rs
changed MCA decode error from 500 to 422.
> refactor(compatiblity): changed MCA decode 500 error to 422

- .github/workflows/release-new-version.yml
This PR updates the schedule for the "Release a new version" workflow to run it at 8 PM IST instead of 8 AM IST.
N/A
N/A
> ci(release-new-version): update schedule to run workflow at 8 PM IST

- crates/router/src/core/payments/helpers.rs
- crates/router/src/routes/metrics.rs
add relevant metrics and logs for manual retries flow
> feat(router): add relevant metrics and logs for manual retries flow

- migrations/2023-08-23-090712_payment_attempt_perf_idx/down.sql
- migrations/2023-08-23-090712_payment_attempt_perf_idx/up.sql
Adding index for payment attempt table with (attempt_id, merchant_id)
```sql
CREATE INDEX payment_attmpet_attempt_id_merchant_id_index ON payment_attempt (attempt_id, merchant_id);
```
> perf(db): add index for attempt_id merchant_id

- Cargo.lock
- crates/router/src/core/webhooks.rs
This change instead of throwing source verification failed error, return false for `source_verified`
> fix(webhooks): handling errors inside source verification

- crates/router/src/connector/paypal/transformers.rs
fix amount to its currency base unit for Paypal - Bank redirect payment method
For Ideal payment method type -
> fix(connector): [Paypal] fix amount to its currency base unit for Paypal Bank redirects

- crates/router/src/core/payments/helpers.rs
In `make_pm_data` we always expect the incoming token to be parent_payment_method token using which we fetch the corresponding basilisk token. But in case of mandate we were receiving the basilisk token so now in the make_pm_data if it is a mandate payment we return the incoming token as the basilisk token. And the flow remains same for the rest of the payment_methods.
First mandate payment 
Subsequent mandate payment
tested other flows
card payment
bank_transfer
> fix(locker): accept the incoming token as the basilisk token if it is a mandate payment

- crates/router/src/connector/payme/transformers.rs
populate error message in case of 2xx payment failures
Manual Testing
> fix(connector): [Payme] populate error message in case of 2xx payment failures

- crates/router/src/connector/coinbase/transformers.rs
- crates/router/src/connector/iatapay.rs
- crates/router/src/connector/iatapay/transformers.rs
- crates/router/src/connector/utils.rs
> fix(connector): Change 5xx to 4xx for Coinbase and Iatapay

- postman/collection-dir/payme/.event.json
- postman/collection-dir/paypal/.event.json
This PR adds the missing required logs (`x-request-id` and `payment-id`) to PayMe and PayPal connector. 
Logs help us debug the errors on envs.
Run the collection, you'll now see `x-request-id` and `payment-id` being printed in logs.
> ci(postman): Add logs to PayMe and PayPal collection in dir

- crates/router/src/connector/cryptopay/transformers.rs
Fix amount to its currency base unit.
Amount sent in hs request - 2345  currency - USD which should be converted to 23.45 USD
Amount requested to the connector is shown here
Successful payment -
> fix(connector): [Cryptopay] fix amount to its currency base unit 

- config/config.example.toml
- config/docker_compose.toml
- loadtest/config/development.toml
The docker compose -d showed this error in the logs. I am new to hyperswitch, If the intention is to support arrays the data type should be changed but the error says it expects a string, so removed the array operator
Run docker compose and checked for error logs, it is now not present
> fix(configs): fix supported connectors in `multiple_api_version_supported_connectors` table

- crates/router/src/connector/paypal.rs
- crates/router/src/connector/paypal/transformers.rs
- crates/router/tests/connectors/paypal.rs
fix PSync for redirection flow for PayPal
> fix(connector): [Paypal] fix PSync for redirection flow for PayPal

- crates/router/src/connector/paypal.rs
- crates/router/src/connector/paypal/transformers.rs
Add manual capture for paypal wallet for Paypal connector
Payments Create - 
After redirection - 
Sync after redirection - 
Capture - 
Sync after capture -
> feat(connector): [Paypal] Add manual capture for paypal wallet 

- crates/api_models/src/enums.rs
- crates/router/src/configs/defaults.rs
- openapi/openapi_spec.json
Add mandatory fields required for card payment method with payment method type - credit for all existing connectors
for credit - 
for debit -
> feat(pm_list): add card - credit pm type required field info for connectors

- crates/router/src/connector/payme/transformers.rs
Change the name of struct according to the naming convention
> refactor(connector): [Payme] Rename types to follow naming conventions

- crates/router/src/connector/payme/transformers.rs
Preprocessing response was specific to auth_type irrespective of which payment method it was, now it is specific to cards too
> refactor(connector): [Payme] Response Handling for Preprocessing

- .github/workflows/connector-ui-sanity-tests.yml
make ui sanity tests run for pr commit 
make ui sanity tests run for pr commit 
testing pending
> ci(connector-ui-sanity-tests): run UI tests on PRs

- crates/router/src/connector/cryptopay.rs
- crates/router/src/connector/cryptopay/transformers.rs
> feat(connector): [Cryptopay]Add reference id for cryptopay (#2107)

- crates/router/src/core/payments.rs
move connector customer create flow to `call_connector_service`
Create Customer Call to Stripe
Sending create customer id in Payments flow to Stripe
> fix(router): move connector customer create flow to `call_connector_service`

- crates/router/src/types/api/webhooks.rs
- crates/router/src/utils.rs
- crates/storage_impl/src/payments/payment_attempt.rs
Fix some of the bugs that were introduced in the recent PRs
Fix webhooks
- Create and test the webhook locally.
> fix(webhooks): fix database queries in webhook 

- crates/router/src/connector/square.rs
- crates/router/tests/connectors/square.rs
Connector square does not allow partial captures and hence this case needs to be properly handled by throwing a proper error message.
Bugfix for connector square where attempting to do a partial capture for a payment will throw a proper error.
Unit Testing was carried out.
> fix(connector): [SQUARE] Throw Error for Partial Capture of Payments

- crates/router/src/core/payments.rs
move connector customer create flow to call_connector_service
Main PR - https://github.com/juspay/hyperswitch/pull/2137
> fix(router): move connector customer create flow to call_connector_service

- crates/router/src/core/payments/flows/psync_flow.rs
If call_connector_action is anything other than trigger, we need not validate_psync_reference_id.
`validate_psync_reference_id` only if call_connector_action is trigger in psync flow
Main PR - https://github.com/juspay/hyperswitch/pull/2106
> fix(router): `validate_psync_reference_id` only if call_connector_action is trigger in psync flow

- postman/collection-dir/checkout/Flow Testcases/Happy Cases/Scenario10-Multiple Captures/Cancel After Partial Capture/Payments - Cancel/event.test.js
Fixes checkout assertion failure in multiple capture.
Assertion fix
Ran the checkout postman collection
> ci(postman): Change assertion status from cancelled to succeeded for checkout

- crates/api_models/src/payments.rs
- crates/router/src/connector/trustpay/transformers.rs
- openapi/openapi_spec.json
Return `merchant_id` in Gpay `session_response` as per https://developers.google.com/pay/api/web/support/troubleshooting
> fix(core): add merchant_id to gpay merchant info

- crates/router/src/connector/adyen.rs
> refactor(connector): [Adyen] psync validation check for adyen

- crates/router/src/connector/trustpay/transformers.rs
Add missing error_codes, which was causing payments to stay in processing state.
> fix(connector): [trustpay] add missing error_codes

- crates/router/src/db/merchant_account.rs
For fetching merchant account using a publishable key, caching was not enabled. This PR addresses that. 
Manually
> feat(db): enable caching for merchant_account fetch using publishable key

- crates/router/src/connector/trustpay/transformers.rs
Add descriptor for card payment method for trustpay
Since the descriptor reflects as bank statement at bank's end which cannot be tested.
> feat(connector): [Trustpay] Add descriptor for card payment method for trustpay

- crates/router/src/connector/checkout.rs
Needed to use logical `or` operator instead of `and`
Manual
> fix(connector): fix dispute webhook failure bug in checkout during get_webhook_resource_object

- crates/drainer/src/lib.rs
- crates/drainer/src/metrics.rs
Add health metric to drainer
NA
NA
> fix: add health metric to drainer

- crates/router/src/db/merchant_account.rs
merchant_account cache invalidation based on publishable_key , in update and delete functions
Manually
> fix(db): merchant_account cache invalidation based on publishable_key

- crates/router/src/connector/adyen.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/services/api.rs
Made source verification mandatory for adyen. 
If webhook source verification fails for adyen, we will fail webhooks instead of going to PSync.
This is done because, adyen doesn't support `payment sync` flow.
Merchant can later re-trigger the webhook after updating merchant_secret.
Manual
> fix(connector): make webhook source verification mandatory for adyen

- crates/router/src/connector/multisafepay/transformers.rs
Test credentials not available, therefore can't be tested
>  chore(config): [Multisafepay] Add configs for card mandates for Multisafepay

- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_update.rs
allow address updates in payments update flow
Payments Create by sending billing address with country US
DB entry for that address_id
Payments Update by sending billing address with country DE
DB entry updated country for same address_id
> fix(router): allow address updates in payments update flow

- crates/storage_impl/src/payments/payment_intent.rs
append payment_id to secondary key for payment_intent to make it unique in kv flow
Create Payment
KV record
Confirm Payment
KV record
> feat(router): append payment_id to secondary key for payment_intent in kv flow

- crates/router/Cargo.toml
Hotfix PR - [#2358](https://github.com/juspay/hyperswitch/pull/2358)
> refactor: enable `logs` feature flag in router crate (#2358)

- crates/router/src/connector/gocardless/transformers.rs
In create customer api, gocardless connector requires region to be passed if the country is United States. region is [ISO3166](https://en.wikipedia.org/wiki/ISO_3166-2:US) code
In gocardless connector, Create customer endpoints requires region if the country is US. Based on the state passed in the payment request it's 2 letter code has to be passed in the region.
> fix: [Gocardless] add region in customer create request based on country

- crates/router/src/connector/gocardless/transformers.rs
temp support for ach gocardless with existing api contracts
> feat: temp support for ach gocardless with existing api contracts

- config/docker_compose.toml
configure lock settings in `docker_compose.toml`
Ran it locally in docker
> fix(configs): add `lock_settings` in `docker_compose.toml`

- crates/router/src/connector/nuvei/transformers.rs
Nuvei is using just the [order id](https://developer.nuvei.com/chapter-4-payment-page) to track the transaction. 
Closes #2340
I wasn't able to test it on my machine due to ram restrictions.
> feat(connector): [Nuvei] Add order id as the reference id

- crates/router/tests/connectors/authorizedotnet.rs
- crates/router/tests/connectors/cybersource.rs
> fix(CI): fix spell check for CI pull request 

- CHANGELOG.md
> fix(CI): fix spell check for CI pull request

- crates/router/src/db/refund.rs
- crates/storage_impl/src/payments/payment_attempt.rs
remove unnecessary lookups in refund and payment_attempt kv flow
Payments create
Payments confirm
> feat(router): remove unnecessary lookups in refund and payment_attempt kv flow

- crates/router/src/connector/powertranz/transformers.rs
> feat(connector): [PowerTranz] Use connector_response_reference_id as reference to merchant

- crates/router/src/connector/opayo/transformers.rs
opayo uses [transaction_Id ](https://developer-eu.elavon.com/docs/opayo/spec/api-reference#operation/createTransaction)
filled the connector_response_reference_id
Fixes #2341
> feat(connector): [Opayo] Add connector id

- .github/workflows/CI-pr.yml
- crates/router/src/connector/stripe.rs
Include checkout to the pull request base repository for formatting check.
> chore: fix the failing formatting check for external contributors

- crates/router/src/core/mandate.rs
- crates/router/src/core/payments/helpers.rs
connector mandate id field should be updated if present while creating new mandate
Manual testing
> fix: update connector_mandate_id column in generate mandate flow

- crates/router/src/connector/paypal.rs
- crates/router/src/connector/paypal/transformers.rs
If 3D Secure is enabled, challenge url will be provided while doing card payment throught paypal
Closes - [#2496](https://github.com/juspay/hyperswitch-cloud/issues/2496)
`{
"amount": 300,
"currency": "PLN",
"amount_to_capture": 97, …
> feat(connector): [Paypal] Implement 3DS for Cards

- package-lock.json
- package.json
This updates the newman dependency version.  The commit version used no longer exists as the source branch had to be rebased.
PR tests should cover newman test runs and be proof of testing.
> ci(newman): update newman to latest from fork

- crates/drainer/src/main.rs
Add startup config log to drainer
Added startup config in the logs for better debugging.
> fix: add startup config log to drainer

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- loadtest/config/development.toml
Config changes for gocardless mandate
> chore: env changes for gocardless mandate

- crates/router/src/db/refund.rs
- crates/storage_impl/src/payments/payment_intent.rs
Don't  check for storage scheme in OLAP functions.
We don't need KV in OLAP functions, so just fetch things from DB
NA
> fix: fetch data directly from DB in OLAP functions

- crates/drainer/Cargo.toml
Add release feature to drainer which enables KMS
added release feature for deployable images
NA
> fix: add release feature to drianer

- crates/router/src/connector/multisafepay.rs
- crates/router/src/connector/multisafepay/transformers.rs
- Addressing Issue [#2305](https://github.com/juspay/hyperswitch/issues/2305): Use connector_request_reference_id as reference to the connector
- Modified two files in `hyperswitch/crates/router/src/connector/`
- `multisafepay.rs`
- `multisafepay/transformers.rs`
- Rebase with changes from commit [12b5341](https://github.com/juspay/hyperswitch/commit/12b534197276ccc4aa9575e6b518bcc50b597bee)
> feat(connector): [Multisafepay] Use connector_request_reference_id as reference to the connector

- crates/api_models/src/payment_methods.rs
another field was required for bank account creds in payment method data.
> refactor(payment_methods): Added mca_id in bank details

- .github/workflows/hotfix-branch-creation.yml
This PR introduces a new workflow to create hotfix branch.
Automate hotfix branch creation.
> CI: add workflow to create hotfix branch

- crates/router/src/connector/noon/transformers.rs
add missing response status i.e `Expired` and `Rejected` which will be triggered by Noon when the payments redirection is expired or it has been declined due to fraud respectively.
> fix(connector): [noon] add missing response status

- crates/router/src/connector/airwallex/transformers.rs
>  feat(connector): [Airwallex] Use connector_request_reference_id as merchant reference id #2291

- .github/workflows/create-hotfix-tag.yml
> ci(create-hotfix-tag): exit workflow on an error

- crates/router/src/connector/authorizedotnet/transformers.rs
Implement `connector_response_reference_id` as reference for Authorizedotnet
Resolves #2323 
Manually
> feat(connector): [Authorizedotnet] use connector_response_reference_id as reference to merchant

- crates/diesel_models/src/address.rs
- crates/diesel_models/src/kv.rs
- crates/diesel_models/src/query/address.rs
- crates/drainer/src/lib.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/db/address.rs
- crates/router/src/types/domain/address.rs
- crates/router/src/types/storage/kv.rs
add kv implementation for update address in update payments flow
**Tested Manually**
Payments create
Billing Address stored in redis
Payments update
Billing address updated in redis
> feat(router): add kv implementation for update address in update payments flow

- crates/router/src/connector/noon.rs
- crates/router/src/connector/noon/transformers.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/bambora.rs
- crates/router/tests/connectors/forte.rs
- crates/router/tests/connectors/nexinets.rs
- crates/router/tests/connectors/paypal.rs
- crates/router/tests/connectors/utils.rs
- crates/router/tests/connectors/zen.rs
sync payments and refunds with our reference_id
> fix(connector): [noon] sync with reference_id

- crates/router/src/connector/noon.rs
- crates/router/src/connector/noon/transformers.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/bambora.rs
- crates/router/tests/connectors/forte.rs
- crates/router/tests/connectors/nexinets.rs
- crates/router/tests/connectors/paypal.rs
- crates/router/tests/connectors/utils.rs
- crates/router/tests/connectors/zen.rs
Reverts juspay/hyperswitch#2544
> revert: fix(connector): [noon] sync with reference_id

- crates/router/src/connector/noon.rs
- crates/router/src/connector/noon/transformers.rs
sync payments and refunds with our reference_id
> refactor(connector): [noon] use connector_request_reference_id for sync

- crates/router/src/connector/noon.rs
- crates/router/src/connector/noon/transformers.rs
handle sync and response status
> fix(connector): [noon] handle sync and response status

- crates/api_models/src/webhooks.rs
- crates/common_enums/src/enums.rs
- crates/router/src/compatibility/stripe/webhooks.rs
- crates/router/src/connector/stripe.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/core/webhooks/utils.rs
- crates/router/src/types/transformers.rs
- migrations/2023-10-13-100447_add-payment-cancelled-event-type/down.sql
- migrations/2023-10-13-100447_add-payment-cancelled-event-type/up.sql
- openapi/openapi_spec.json
Add new IncomingWebhookEvent which will handle the payment cancel webhooks.
Map the above event in Stripe.
Processing of cancel webhooks from connector will be supported for stripe.
Testing was carried out using Webhooks
> feat(router): Add Cancel Event in Webhooks and Mapping it in Stripe

- crates/router/src/connector/noon.rs
- crates/router/src/connector/noon/transformers.rs
- enhance response status mapping based on https://docs.noonpayments.com/test/evaluating-api
- Populate `error_reason` with noon's error message as it is more informative and will be exposed to the merchant.
> refactor(connector): [noon] enhance response status mapping

- crates/router/src/connector/paypal.rs
- crates/router/src/connector/paypal/transformers.rs
use connector request reference id as reference - invoice id for paypal
webhooks
> feat(connector): [Paypal] use connector request reference id as reference for paypal 

- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/setup_intents/types.rs
Add connector_transaction_id in compatibility layer response
> feat(compatibility): added support to connector txn id

- crates/test_utils/README.md
- postman/README.md
This PR re-writes the outdated postman documentation to help devs test their features and update the collection on the go.
To help devs make product better
When you read the documentation, you should understand on how you can develop the collection for the feature you add.
> docs(postman): Rewrite postman documentation to help devs develop tests for their features

- connector-template/mod.rs
- crates/test_utils/src/connector_auth.rs
- scripts/add_connector.sh
add connector script changes
**Testing Not required**
> chore(scripts): add connector script changes

- crates/router/src/events.rs
- crates/router/src/events/api_logs.rs
- crates/router/src/events/event_logger.rs
- crates/router/src/routes/app.rs
- crates/router/src/services/api.rs
- crates/router/src/services/api/client.rs
- Add basic struct for APIEvent logs
- update `add_request_id` fn of ApiClient to use RequestId type
- Capture incoming api's logs from `server_wrap_util`
- Tested logs for merchant create API
> feat(events): add events for incoming API requests

- crates/router/src/connector/tsys/transformers.rs
The `connector_request_reference_id` parameter has been set for the Tsys Payment Solutions for uniform reference and transaction tracking.
**Location- router/src/connector/tsys/transformers.rs**
This PR was raised so that it Fixes #2319  !
- **I ran the following command, and all the errors were addressed properly, and the build was successful.**
```bash
cargo clippy --all-features
```
- The code changes were formatted with the following command to fix styling issues.
```bash
cargo +nightly fmt
```
> feat(connector): [Tsys] Use connector_request_reference_id as reference to the connector

- .github/CODEOWNERS
Update the codeowners file to account for updated changes.
> ci: update codeowners

- crates/router/src/connector/noon/transformers.rs
remove cancellation_reason from `VOID` call as it is not required as per: https://docs.noonpayments.com/payment-api/reference/reverse
**TEST CASES**
- Try to void payments
- Make Manual Payments, try both capture and void
> refactor(connector): [noon] remove cancellation_reason

- crates/router/src/core/refunds.rs
Fix refunds , fetch refunds if the insert fails. 
CI checks, as CI checks were failing before.
> fix(refunds): fetch refund if insert fails due to duplicate response

- crates/router/src/connector/opayo/transformers.rs
> refactor(connector): added default case for Opayo

- .github/workflows/release-new-version.yml
> ci: fix bash syntax in `release-new-version` workflow

- postman/collection-dir/paypal/Flow Testcases/QuickStart/Merchant Account - Create/request.json
This PR reverts [this](https://github.com/juspay/hyperswitch/pull/2603/files#diff-99375225ff195ba7ed3cf9bc661707e3b9a8e6fb373aaa0042fa7264ef15f601) change that was merged with in this [commit](https://github.com/juspay/hyperswitch/commit/2f9a3557f63150bcd27e27c6510a799669706718).
Paypal Collection is failing because of this change
3 assertion failures because https://github.com/juspay/hyperswitch/pull/2603 is yet to be deployed in the environment.
> ci(paypal): Fix Postman collections of Paypal

- crates/router/src/connector/airwallex/transformers.rs
#2262 
No test cases. As In this PR only error message have been populated for all default cases.
> refactor(connector): [Airwallex] Remove default case handling

- crates/api_models/src/payments.rs
- crates/common_enums/Cargo.toml
- crates/common_enums/src/enums.rs
- crates/router/src/core/payment_link.rs
- crates/router/src/core/payment_link/payment_link.html
refactor: payment link UI
This adds a mapping of currency to their currency symbols. This is needed as part of the payment link UIs.
Payment link UI is modified as per the latest designs.
> feat: add currency symbols

- crates/api_models/src/lib.rs
- crates/api_models/src/organization.rs
- crates/diesel_models/src/lib.rs
- crates/diesel_models/src/organization.rs
- crates/diesel_models/src/query.rs
- crates/diesel_models/src/query/organization.rs
- crates/diesel_models/src/schema.rs
- crates/router/src/core/admin.rs
- crates/router/src/db.rs
- crates/router/src/db/organization.rs
- crates/router/src/types/transformers.rs
- crates/storage_impl/src/mock_db.rs
- migrations/2023-10-23-101023_add_organization_table/down.sql
- migrations/2023-10-23-101023_add_organization_table/up.sql
- postman/collection-dir/stripe/MerchantAccounts/Merchant Account - Create/event.test.js
This feature will add the organization table.
Make Open source repository more usable.
- Create a merchant account without any organization id. -> Ensure that organization id is generated.
> feat(organization): add organization table

- .typos.toml
> fix(typo): add commit id to allowed typos

- postman/collection-json/volt.postman_collection.json
Add Volt's postman collection json file
Fix
Yes.  
https://github.com/juspay/hyperswitch/pull/2582 generated collection files for this.
> ci(postman): Add Volt Postman collection JSON file

- crates/router/src/connector/payme/transformers.rs
This PR removes the default case handling and adds error handling for all the available cases.
Fixes #2282 
No test cases. As In this PR only error message have been populated for all default cases.
> refactor(connector): [Payme] Remove Default Case Handling

- crates/diesel_models/src/query/merchant_connector_account.rs
- crates/router/src/db/merchant_connector_account.rs
implemented a function that will return list of `MerchantConnectorAccount` by merchant_id and connector_name.
Existing definition for `find_merchant_connector_account_by_merchant_id_connector_name` was returning a single `MerchantConnectorAccount`. 
Changed it to return a Vector of `MerchantConnectorAccount`.
Required for dashboard 
Cannot be tested until a different PR by @apoorvdixit88  on dashboard changes gets merged.
> feat: implement list_merchant_connector_accounts_by_merchant_id_connector_name function

- .github/workflows/CI-pr.yml
- .github/workflows/pr-title-check.yml
This PR adds support for spell checking PR title too
PR title was  - CI: spell check environmet
Typo in code - varient
Both are being caught
> CI: add suport for spell checking PR title

- CHANGELOG.md
> fix: response spelling

- README.md
> docs(README): add one-click deployment information using CDK

- config/development.toml
Update the pm_filters of Klarna in Stripe to include some more countries and currencies.
Test case:-
Make a Klarna payment using any one of the these countries and currencies for stripe. Also the admin api key that is being used needs to be of the particular country's.
`klarna = { country = "AU,AT,BE,CA,CZ,DK,FI,FR,DE,GR,IE,IT,NL,NZ,NO,PL,PT,ES,SE,CH,GB,US", currency = "AUD,CAD,CHF,CZK,DKK,EUR,GBP,NOK,NZD,PLN,SEK,USD" }`
```
--header 'api-key: dev_EMia8cy6oceZ3OPX0p5N5Y7wvjLqXfHxCnmO7quEd7oXhyvC8AWLFtLeWf2Nvscq' \
--header 'Cookie: JSESSIONID.130f0e8f=node01ix1y16yw8z3v1m3nwkr4qbiwb6.node0' \
--data-raw '{
"amount": 180000,
"currency": "AUD",
"confirm": …
```
> refactor(config): update payment method filter of Klarna in Stripe

- README.md
Add button to cdk bootstrap the region 
Single click deployment
> docs(README): add bootstrap button for cloudformation deployment

- crates/router/src/connector/zen/transformers.rs
No test cases required. As In this PR only error message have been changed from Not Supported error message to NotImplemented error message.
> refactor(connector): [Zen] change error message from NotSupported to NotImplemented

- crates/common_utils/src/events.rs
- crates/router/src/events/api_logs.rs
- crates/router/src/services/authentication.rs
- use snake case for api events naming
- maintain the naming convention across logs
- Check logs after api calls
> refactor(events): update api events to follow snake case naming

- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario8-Create payment with Manual capture with confirm false and surcharge_data/Payments - Confirm/request.json
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario8-Create payment with Manual capture with confirm false and surcharge_data/Payments - Create/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario8-Create payment with Manual capture with confirm false and surcharge_data/Payments - Create/request.json
Made changes to paypal postman collection to support recent surcharge related change made in this PR https://github.com/juspay/hyperswitch/pull/2696
Manual
> fix: paypal postman collection changes for surcharge feature

- README.md
> docs(README): replace cloudformation deployment template with latest s3 url.

- crates/router/src/services/api/client.rs
add rust locker url in proxy_bypass_urls
No testing required as it is just updating proxy_bypass_urls
> fix(router): add rust locker url in proxy_bypass_urls

- .github/workflows/hotfix-pr-check.yml
> ci(hotfix-pr-check): use env input from GitHub to read PR body

- crates/router/src/configs/defaults.rs
- crates/router/src/connector/powertranz/transformers.rs
- crates/router/src/core/payment_methods/cards.rs
This PR addresses the clippy lints occurring due to new rust version 1.74
> chore: address Rust 1.74 clippy lints

- .github/CODEOWNERS
This PR adds routing related modules under `hyperswitch-routing` in CODEOWNERS
> ci: update CODEOWNERS with hyperswitch-routing modules

- crates/router/src/types.rs
Add `serde::Serialize` impl for `ConnectorAuthType`
Will make it easier to construct a json for `ConnectorAuthType`
Cargo check.
This doesn't effect anything. So no need of test cases.
> refactor(mca): Add Serialization for `ConnectorAuthType`

- crates/router/src/connector/payeezy/transformers.rs
- Fix issue: #2856 
- Changes to be made: update the error message
- File changed: **```transformers.rs```** (crates/router/src/connector/payeezy/transformers.rs)
> refactor(connector): [Payeezy] update error message

- crates/router/src/core/payments/operations/payment_confirm.rs
allow billing and shipping address update in payments confirm flow
1. Create a payment intent by sending billing / shipping address
2. Confirm a payment by sending updated billing / shipping address and see if it updates in the response
3. Check in DB if the address is updated as expected
> feat(router): allow billing and shipping address update in payments confirm flow

- .github/workflows/CI-pr.yml
- .github/workflows/CI-push.yml
- .github/workflows/auto-release-tag.yml
- .github/workflows/connector-sanity-tests.yml
- .github/workflows/connector-ui-sanity-tests.yml
- .github/workflows/conventional-commit-check.yml
- .github/workflows/create-hotfix-branch.yml
- .github/workflows/create-hotfix-tag.yml
- .github/workflows/hotfix-pr-check.yml
- .github/workflows/manual-release.yml
- .github/workflows/migration-check.yaml
- .github/workflows/postman-collection-runner.yml
- .github/workflows/pr-title-spell-check.yml
- .github/workflows/release-new-version.yml
- .github/workflows/validate-openapi-spec.yml
This PR updates the version of dependencies being used in all workflows. Also use bot credentials to generate token
> CI: update actions to latest versions and use bot credentials to generate token

- README.md
Updated mentions for Discord, Slack, and GitHub Discussions
Just want to make platforms specific to the targeted audience.
> docs(README): Updated Community Platform Mentions

- crates/router/src/connector/volt/transformers.rs
Resolves #2864 
No test cases required. As In this PR only error message have been changed from Not Supported error message to NotImplemented error message.
> refactor(connector): [Volt] change error message from NotSupported to NotImplemented

- crates/router/src/connector/dlocal/transformers.rs
- [ x] Bugfix
- Fix: Dlocal Connector Transaction ID Population Issue
- Why is this change required? What problem does it solve?
A.)  The Dlocal connector Transaction ID wasn't correctly populated, causing failures in subsequent operations like capture, refund, and 3DS redirection. This fix ensures the proper population of the Transaction ID, resolving the associated failures.
Executed the following test scenario using the Postman collection:
- Initiated a 3DS-authorized transaction
- Successfully completed the authorization process
- Captured the payment"
> fix(router): [Dlocal] connector transaction id fix

- postman/collection-dir/adyen_uk/Flow Testcases/Variation Cases/Scenario8-Refund for unsuccessful payment/Refunds - Create/event.test.js
Modified error message in assertion as it was failing 
Adyen automation was failing 
Postman
> ci(postman): Fixed adyen assertion failure 

- crates/api_models/src/events/user.rs
- crates/api_models/src/user.rs
- crates/api_models/src/user_role.rs
- crates/diesel_models/src/query/dashboard_metadata.rs
- crates/diesel_models/src/query/user.rs
- crates/diesel_models/src/user/dashboard_metadata.rs
- crates/router/src/core/user.rs
- crates/router/src/db/dashboard_metadata.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/db/user.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/lock_utils.rs
- crates/router/src/routes/user.rs
- crates/router/src/types/domain/user.rs
- crates/router/src/utils/user.rs
- crates/router_env/src/logger/types.rs
- Add list user api
- Add list merchant api
- Add query to update dashboard metadata
Postman.
1. List User
```
curl --location 'http://localhost:8080/user/user/list' \
--header 'Authorization: Bearer JWTToken' \
```
You will get the following response.
```
[
{
"user_id": "user_id",
"email": "email",
"name": "name",
"role_id": "merchant_admin",
"role_name": "Admin",
"status": "Active",
"last_modified_at": "2023-03-29T07:12:47.997Z"
}
]
```
2. List Merchants
```
curl --location 'http://localhost:8080/user/switch/list' \
--header 'Authorization: Bearer JWTToken' \
```
You will get the following response.
```
[
"merchant_1700813754",
"merchant_1701339247",
"merchant_1701345454"
]
```
> feat(user): add user_list and switch_list apis

- Cargo.lock
- crates/common_utils/Cargo.toml
- crates/router/src/core/payments.rs
fix: remove redundant call to populate_payment_data function
> fix: remove redundant call to populate_payment_data function

- crates/router/src/configs/settings.rs
Fix bug.
Build is failing.
IDK
> fix(config): parse kafka brokers from env variable as sequence

- crates/api_models/src/admin.rs
- crates/api_models/src/payment_methods.rs
- crates/router/src/openapi.rs
- openapi/openapi_spec.json
fix payment_methods_enabled in merchant connector account apis
Docs change only
> docs(openapi): fix `payment_methods_enabled` OpenAPI spec in merchant connector account APIs

- crates/router/src/core/errors/user.rs
- crates/router/src/core/errors/user/sample_data.rs
- crates/router/src/core/user.rs
- crates/router/src/utils/user/sample_data.rs
This PR Includes
**Change password changes for user:**
- New password cannot be empty.
- Old and new password cannot be same.
**Sample Data changes**
- Removed unnecessary errors which are not getting used.
For change password use the following curl:
```
curl --location 'http://localhost:8080/user/change_password' \
--data-raw '{
"new_password": "k@12345",
"old_password": "k@12345"
}
'
```
Response
```
{
"error": {
"message": "Old and new password cannot be same",
"code": "UR_29"
}
}
```
When new password is empty:
```
curl --location 'http://localhost:8080/user/change_password' \
--data-raw '{ …
```
> fix(user): add checks for change password

- config/docker_compose.toml
add missing config fields in `docker_compose.toml`
Ran docker compose locally
> fix(config): add missing config fields in `docker_compose.toml`

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- loadtest/config/development.toml
Add configs for mandate payments of Cybersource
VAS PR: https://github.com/juspay/hyperswitch-cloud/pull/3558
https://github.com/juspay/hyperswitch-cloud/issues/3275
Only config changes, hence testing not required.
> chore(configs): [CYBERSOURCE] Add mandate configs

- crates/router/src/connector/cybersource/transformers.rs
Remove field phone number from billing address in payments call because it is not a mandatory field.
https://github.com/juspay/hyperswitch-cloud/issues/3275
Test payments flow in cybersource without passing phone number in billing address.
> fix(connector): [CYBERSOURCE] Remove Phone Number Field From Address

- crates/external_services/src/email/ses.rs
- crates/router/src/routes/app.rs
Create ses client every time when sending the email
This is SES specific change only
> refactor(email): create client every time of sending email

- crates/router/src/connector/wise/transformers.rs
> refactor(connector): [Wise] Error Message For Connector Implementation 

- crates/api_models/src/admin.rs
- crates/api_models/src/gsm.rs
- crates/api_models/src/refunds.rs
- crates/openapi/src/openapi.rs
- crates/openapi/src/routes.rs
- crates/openapi/src/routes/disputes.rs
- crates/openapi/src/routes/gsm.rs
- crates/openapi/src/routes/mandates.rs
- crates/openapi/src/routes/merchant_connector_account.rs
- crates/openapi/src/routes/refunds.rs
- crates/router/src/routes/mandates.rs
- crates/router/src/routes/payments.rs
make relevant openapi changes in mca, disputes, refunds, mandates and gsm apis
> docs: make relevant openapi changes in mca, disputes, refunds, mandates and gsm apis

- crates/router/src/connector/cybersource.rs
fix signature authentication for patch request in incremental_authorization flow for cybersource
1. Do a manual capture_method payment through Cybersource, by sending request_incremental_authorization as true
2. Do a first incremental authorization to see updated amount and authorization records
3. Do a second incremental authorization to see updated amount and authorization records
4. Retrieve the payment to see detailed authorization details
5. Capture the finally incremented authorized amount
> fix(connector): [Cybersource] signature authentication in incremental_authorization flow

- crates/router/src/services/api.rs
- remove deuplicate logs logging payment intent
> chore(events): remove duplicate logs

- migrations/2023-12-14-101348_alter_dashboard_metadata_key_type/up.sql
> fix: change prodintent name in dashboard metadata

- crates/api_models/src/payments.rs
- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/errors/transformers.rs
- crates/router/src/core/payment_link.rs
added amount conversion to base unit based on currency
> fix(payment_link): added amount conversion to base unit based on currency

- crates/router/src/connector/paypal.rs
- crates/router/src/connector/paypal/transformers.rs
remove shipping address as mandatory field for paypal wallet 
test cases - make a payment via PayPal wallet , without shipping address, after redirection, status should be either processing / successful
> fix(connector): [Paypal] remove shipping address as mandatory field for paypal wallet

- crates/router/src/connector/trustpay/transformers.rs
- `connector_reqeust_reference_id` will be used as merchant reference for payment which will help is retrieving status in case of timeout or failure.
- webhook's object reference id uses merchant reference to match against payment_attempt, payment_id was being passed before as merchant reference resulting in failure of mapping webhooks with payments
Tested using connector's dashboard and postman.
- Create a merchant account
```
{
"primary_business_details": [
{
"business": "default"
}
], …
```
> fix(connector): [Trustpay] Use `connector_request_reference_id` for merchant reference instead of `payment_id`

- crates/router/src/core/user.rs
To fix wrong org_id for new invited users.
Postman.
```
curl --location 'http://localhost:8080/user/user/invite' \
--data-raw '{
"email": "new_unregistered_email",
"name": "username",
"role_id": "merchant_view_only"
}'
```
This should be the response.
```
{
"is_email_sent": false
}
```
> fix(users): wrong `user_role` insertion in `invite_user` for new users

- crates/router/src/connector/bankofamerica/transformers.rs
Implement Payment Method Apple Pay(Manual Flow) for connector Bankofamerica
https://github.com/juspay/hyperswitch-cloud/issues/3703
Testing was carried out using postman
> feat(connector): [BOA] Implement apple pay manual flow

- crates/router/src/connector/iatapay/transformers.rs
fix error response handling when payment is failed
test cases - 1. make a successful payment
2. make a payment, after redirection, cancel the payment. When Psync for the payment has made, status should be failed, and error reason and code should be populated.
Success - 
failed case -
> fix(connector): [Iatapay] fix error response handling when payment is failed

- crates/router/src/connector/volt.rs
- crates/router/src/connector/volt/transformers.rs
Error generated during token creation have different body than all the other flows resulting in deserialization error.
Tested through postman
Create a payment through Volt with wrong credentials.
The response should have failed status with error message.
> fix(connector): [Volt] Error handling for auth response

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- crates/router/src/configs/defaults.rs
- crates/router/src/connector/nmi/transformers.rs
- crates/router/src/services/api.rs
Include fields for vaulting the card as well as for payment
Tested through postman.
- Create a card 3DS payment through postman: 
`{
"amount": 15000,
"billing": {
"address": {
"first_name": "Sakil",
"last_name": "Mostak",
}
}, …
> refactor(connector): [NMI] Include mandatory fields for card 3DS

- crates/router/src/connector/iatapay.rs
Refund amount should be equal to amount in the refund request rather than payment intent request
> fix(connector): [iatapay] change refund amount

- crates/diesel_models/src/payment_intent.rs
fix multiple incremental_authorizations with kv enabled
use source data if any value is None in update value in apply_changeset
1. Do a manual capture payment
2. First incremental authorization
3. Second incremental authorization
> fix(router): multiple incremental_authorizations with kv enabled

- postman/collection-dir/adyen_uk/Flow Testcases/Variation Cases/Scenario1-Create payment with Invalid card details/Payments - Create(Invalid Exp month)/event.test.js
Fixed assertion for expired card  test case in the adyen collection
Test was failing 
Postman
> ci(postman): Adyen assertion fix for expired card test case 

- crates/cards/Cargo.toml
- crates/cards/src/validate.rs
This PR fixes failing `wasm-pack build` for the `euclid_wasm` crate. 
Fixes #3260.
> fix(wasm): fix failing `wasm-pack build` for `euclid_wasm`

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
Surcharge with saved card was failing during confirm. Fixed it.
Manual
How to test:
1. Configure surcharge rules for a merchant
2. Create a payment
3. Do customer payment method list
4. Do a payment with payment_token
> fix(core): surcharge with saved card failure

- crates/router/src/connector/volt.rs
- crates/router/src/connector/volt/transformers.rs
Resolves [3835](https://github.com/juspay/hyperswitch-cloud/issues/3835)
Paymnet Request Body
`{
"amount": 1178,
"amount_to_capture": 1178,
"payment_method_type": "open_banking_uk",
"open_banking_uk": {
}
}
},
"billing": {
"address": { …
> feat(connector): [Volt] Add support for refund webhooks 

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
add merchant_secret config for webhooks for  cashtocode and volt
added configs in wasm dashboard for webhook `merchant_secret` for cashtocode and volt
> chore(config): add merchant_secret config for webhooks for  cashtocode and volt in wasm dashboard

- crates/router/src/connector/cryptopay.rs
The encoding for empty string in header generation for PSYNC call is removed. This encoding was previously causing the PSYNC call to fail.
https://github.com/juspay/hyperswitch/issues/3403
- Create a crypto_currency payment for connector cryptopay.
--data-raw '{
"amount": 10,
"customer_id": "custo", …
> fix(connector): [CRYPTOPAY] Fix header generation for PSYNC

- crates/router/src/connector/noon/transformers.rs
Reverts juspay/hyperswitch#3209 
Resolves [#3445](https://github.com/juspay/hyperswitch/issues/3445)
Dependency change not made
>  Refactor(Router): [Noon] revert adding new field max_amount to mandate request 

- connector-template/mod.rs
In Recent changes, `get_request_body` return type was changed and connector template script was not modified .This pr fixes the connector template script.
In Recent changes of `get_request_body` return type was changed and connector template script was not modified .This pr fixes the connector template script.
run `sh scripts/add_connector.sh example [<connector-base-url>](https://www.google.com/)` on oss branch and it should compile with no errors.
> fix(connector): fix connector template script

- crates/router/src/connector/helcim.rs
- crates/router/src/connector/helcim/transformers.rs
Earlier if wrong api_key is passed during Payment Connector - Create for connector Helcim then the server throws 5XX error when you create a payment.
The connector will now handle the error thrown during Payments - Create if wrong api_key is passed during Payment Connector - Create.
https://github.com/juspay/hyperswitch/issues/3457
1. Testing can be done by creating a payment with wrong api credentials. You should get the following error.
--data '{
"amount": 210, …
> fix(connector): [HELCIM] Handle 4XX Errors

- .github/workflows/create-hotfix-branch.yml
- .github/workflows/create-hotfix-tag.yml
- .github/workflows/release-nightly-version-reusable.yml
As we are now using tags in the calendar versioning (CalVer) format, the github workflow to create a hotfix branch and hotfix tag needs to be refactored to handle this format of tags.
Using tags in the calendar versioning (CalVer) format.
> ci: update `create-hotfix-tag` and `create-hotfix-branch` workflows to handle CalVer tags

- crates/router/src/connector/wise.rs
- crates/router/src/core/errors/utils.rs
Cards was not implemented for Wise, but instead of throwing error, it gave a Ok response with status which shouldn't be the actual behaviour.
- Create a merchant account 
- Create a payment connector (Wise)
```
{
"connector_name": "wise",
"api_key": "{{api_key}}",
"key1": "{{key1}}"
},
{
{
"Visa",
"Mastercard"
],
},
{
"Visa",
"Mastercard"
], …
```
> refactor(payouts): Propagate `Not Implemented` error 

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
add wasm dashboard changes for cashtocode to support CAD, CHF currency
test case - in dashboard, for evoucher pm type for cashtocode, fields such as username password mid should be present for CAD, CHF
> chore(configs): [Cashtocode] wasm changes for CAD, CHF currency 

- .github/workflows/create-hotfix-branch.yml
- .github/workflows/create-hotfix-tag.yml
While trying to fetch the latest tags we need to filter for `CalVer` as it also include version tags.
I have tested this change locally.
> ci: fix `create-hot-fix-tag` workflow to filter for `CalVer` tags

- crates/router/src/connector/noon.rs
- crates/router/src/connector/noon/transformers.rs
- crates/router/src/core/payments/flows.rs
Implement revoke mandate flow for Noon
#3494 
- Create Mandate with the Noon
- Test Recurring Payment using mandate_id
- Revoke the mandate and check at connector if it is revoked or not.
> feat(connector): [noon] add revoke mandate

- crates/router/src/connector/trustpay/transformers.rs
add merchant_id in gpay session response for trustpay
test cases - make a gpay payment for trustpay (in gpay session response, merchant_id should be present). testing of this pr can only be done in prod since this issue was only in prod.
Couldn't test in local.
> fix(connector): [Trustpay] add merchant_id in gpay session response for trustpay

- crates/api_models/src/payments.rs
- crates/common_utils/src/custom_serde.rs
- crates/router/src/connector/adyen/transformers.rs
- openapi/openapi_spec.json
Payment request to test Boleto 
```{
"payment_method": "voucher",
"payment_method_type": "boleto",
"voucher": {
"boleto": {
"social_security_number": "56861752509"
}
}
},
"billing": {
"address": {
"country": "BR", …
```
> refactor(connector): [Adyen] change expiresAt time from string to unixtimestamp

- config/deployments/env_specific.toml
This PR adds file storage config in `env_specific.toml`
Cannot be tested as this is just a config addition
> chore: add file storage config in env_specific toml

- config/config.example.toml
- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/docker_compose.toml
##Description
Add Applepay Mandate configs for noon in all environments.
Applepay should appear in the payment method list
> feat(configs): [Noon] Add applepay mandate configs

- crates/api_models/src/health_check.rs
- crates/router/src/bin/scheduler.rs
Closes #3524 . Add an outgoing request check for scheduler.
Added a check in scheduler for checking the outgoing requests
- `curl --location 'http://localhost:3000/health/ready'`
- <img width="1305" alt="Screenshot 2024-02-01 at 6 06 36 PM" src="https://github.com/juspay/hyperswitch/assets/43412619/5d1e1525-a408-484f-9749-6affbad3758c">
**This cannot be tested in sandbox as it's not exposed externally in sandbox**
> fix: add outgoing checks for scheduler

- crates/router/src/lib.rs
- crates/router/src/middleware.rs
handle empty body parse failures in bad request logger middleware
1. 400 Bad request in payments
2. Mandate revokes multiple times
3. Redirection flow for cards through NMI
4. Stripe compatibility layer
> fix(router): handle empty body parse failures in bad request logger middleware

- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
Config was missing for complete auth flow to contain payment_method_data for cards resulting in error during redirection
Steps to Test:
- Create a 3DS payment through Payme: 
```
{
"card": {
"card_number": "4111111111111111",
"card_exp_year": "2024",
"card_holder_name": "joseph …
```
> refactor(configs): [Payme] Development config for 3DS

- crates/router/src/core/admin.rs
This PR changes the error message that is thrown when updating the merchant connector account. 
When updating the merchant connector account, if a duplicate value error is raised, then instead of `InternalServerError`, `DuplicateError` should be thrown.
- Create an mca with connector_label us_stripe.
```bash
curl --location 'http://localhost:8080/account/merchant_1706599788/connectors' \
--data '{
"api_key": "<STRIPE_API_KEY>"
},
"connector_label": "us_stripe"
}'
```
- Create another mca with connector_label us_stripe_second
```bash …
```
> fix(merchant_connector_account): change error to DuplicateMerchantAccount

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
Issue [#3904](https://github.com/juspay/hyperswitch-cloud/issues/3904)
Tested locally using hyperswitch and hyperswitch-card-vault
> fix(payouts): saved payment methods list for bank details

- crates/router/src/services/authorization/info.rs
Change the ordering of the [ThreeDsDecisionManagerWrite , ThreeDsDecisionManagerRead] and [SurchargeDecisionManagerWrite, SurchargeDecisionManagerRead] of permissionInfo API.
```
Previous
{
"module": "ThreeDsDecisionManager",
"description": "View and configure 3DS decision rules configured for a merchant",
"permissions": [
{
"enum_name": "ThreeDsDecisionManagerWrite",
"description": "Create and update 3DS decision rules"
},
{
"enum_name": "ThreeDsDecisionManagerRead",
"description": "View all 3DS decision rules configured for a merchant"
}
]
}
Now
{
"module": "ThreeDsDecisionManager",
"description": "View and configure 3DS decision rules configured for a merchant",
"permissions": [
{
"enum_name": "ThreeDsDecisionManagerRead",
"description": "View all 3DS decision rules configured for a …
```
> feat(permissions): Permsision Info Ordering Change

- crates/connector_configs/toml/production.toml
Add configs for wasm for prodcution for Volt Connector
> chore(configs): [Volt] Add configs for wasm  for production

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- crates/router/src/configs/defaults.rs
- loadtest/config/development.toml
Add required field for Boleto Payment Method
Create a Payment with ` "confirm": false,` of Boleto PM via Adyen Connector
Payment Request:
```
{   "amount": 6540,
"payment_method": "voucher",
"payment_method_type": "boleto",
"voucher": {
"boleto": {
"social_security_number": "56861752509"
}
}
},
"billing": {
"address": {
"line3": "Harrison …
```
> feat(pm_list): Add required field for Boleto Payment Method

- config/deployments/sandbox.toml
This PR updates Iatapay to use Sandbox URL instead of Production URL in Sandbox environment.
Closes #3643
`config/deployment/sandbox.toml`
Everytime, we need to manually do another deployment manually to see whether the connector is working as expected. With this PR, if they want to test, we'll do manual deployment with production URL going forward.
Iataoay payments in Sandbox environments should work now:
```curl
--header 'api-key: snd_oJVcvSxV6aBs3qzsG8en6nVUOMYcczuNBSCaIRToSiHhreVNNOYVmCj9gccgXuhR' \
--data-raw '{ …
```
> chore(env): update Iatapay env to use Sandbox URL instead of Prod

- config/development.toml
- crates/router/src/middleware.rs
- crates/router/src/services/api.rs
- crates/router_env/src/logger/storage.rs
This Pr adds payment_method to golden_log_line
Do paymentCreate -> get the payment_id -> Search golden logs in kibana for loki -> check for payment_method in that line
sample grafana link
https://grafana.staging.eu.juspay.net/explore?orgId=1&left=%7B%22datasource%22:%22x5WTfCG4k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22bach%5C%22%7D%20%7C%3D%20%60pay_1f4aSeP6NpY2fjooT1Uv%60%20%7C%3D%20%60golden_log_line%60%20%7C%20json%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22x5WTfCG4k%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D
Impacted Area -> Application IO level logs
```
{
"message": "[ROOT_SPAN - EVENT] router::middleware",
"hostname": …
```
> refactor(router): added payment_method to golden log line

- config/development.toml
- config/docker_compose.toml
For localhost testing added Dashboard Origin in the Toml files.
Nothing to test.
> fix(env): add dashboard origin in toml file

- migrations/2024-02-15-153757_add_dashboard_metadata_enum_is_change_password_required/down.sql
- migrations/2024-02-15-153757_add_dashboard_metadata_enum_is_change_password_required/up.sql
Add migration for force password enum(`IsChangePasswordRequired`). 
For force password enum `isChangePasswordRequired` migration is not present.
Tested locally, for the invite flow, after migration its working fine and value of enum is getting updated correctly.
```
curl --location 'http://localhost:8080/user/user/invite' \
--data-raw '{
"email": "cdc@gmail.com",
"name": "test3",
"role_id": "merchant_admin"
}
'
```
> fix(user): add migration for force password change

- crates/router/src/configs/defaults.rs
Zip code in billing address is added as mandatory field for 3ds transaction
Through Postman.
Steps: 
```
{
"address": {
}
},
"return_url": …
```
> refactor(connector): [NMI] Add Zip code as mandatory field for 3DS

- crates/router/src/connector/nmi/transformers.rs
Billing details is added as fields for vault it creation
Through Postman.
Steps: 
```
{
"address": {
}
},
"return_url": …
```
> refactor(connector): [NMI] Add billing details for preprocessing

- crates/router/src/connector/noon.rs
Currently in Psync if 4xx or 5xx comes the payment_status is not changed for all the error_codes, for specific error_codes like order does not exist should be failed immediately.
#3675 
- Create a sync with noon for payment that was not registered with noon, it should fail rather than stuck in pending state. Steps to do that: 
1. Create a merchant connector account with Noon with SBX credentials `1`.
```
curl --location 'http://localhost:8080/account/merchant_1708067200/connectors' \
--data '{
"connector_name": "noon", …
```
> fix(connector): [noon] Fail the payment for specific error_response

- crates/router/src/connector/payme/transformers.rs
payme_transaction_id is converted to an optional field since we don't receive it in case of some failures with 2xx status
```
{
"address": {
"zip": …
```
> fix(connector): [Payme] `payme_transaction_id` converted to optional

- postman/collection-dir/cybersource/Flow Testcases/Happy Cases/Scenario1-Create payment with confirm true/Payments - Create/request.json
- postman/collection-dir/cybersource/Flow Testcases/Happy Cases/Scenario12-Zero auth mandates/Payments - Confirm/request.json
- postman/collection-dir/cybersource/Flow Testcases/Happy Cases/Scenario13-Incremental auth/Payments - Create/request.json
- postman/collection-dir/cybersource/Flow Testcases/Happy Cases/Scenario13-Incremental auth/Payments - Retrieve/request.json
- postman/collection-dir/cybersource/Flow Testcases/Happy Cases/Scenario14-Incremental auth for mandates/Payments - Create/request.json
- postman/collection-dir/cybersource/Flow Testcases/Happy Cases/Scenario14-Incremental auth for mandates/Payments - Retrieve/request.json
- postman/collection-dir/cybersource/Flow Testcases/Happy Cases/Scenario15-Incremental auth with partial capture/Payments - Retrieve/request.json
- postman/collection-dir/cybersource/Flow Testcases/Happy Cases/Scenario19-Create 3ds payment/Payments - Create/request.json
- postman/collection-dir/cybersource/Flow Testcases/Happy Cases/Scenario20-Create 3ds mandate/Payments - Create/request.json
- postman/collection-dir/cybersource/Flow Testcases/QuickStart/Merchant Account - Create/request.json
- postman/collection-dir/cybersource/Flow Testcases/Variation Cases/Scenario11-Failure card/Payments - Create/request.json
- postman/collection-dir/cybersource/Health check/New Request/request.json
Removed custom header in the cybersource collection
Cybersource collection was failing 
Postman
> ci(postman): Fix cybersource collection 

- crates/router/src/connector/payme/transformers.rs
payme_transaction_id is converted to an optional field since we don't receive it in case of some failures with 2xx status
Raised corresponding to https://github.com/juspay/hyperswitch/pull/3707
```
{
"address": {
"line3": …
```
> fix(connector): [Payme] payme_transaction_id converted to optional

- crates/router/src/connector/bitpay/transformers.rs
Mask pii information passed and received in the connector request and response for Bitpay
Check if sensitive fields within connector request and response is masked in the click house for Bitpay
Sanity test
1. Payment create - card
```
--header 'api-key: {{api_key}}' \
--data-raw '{ …
```
> refactor(connectors): [Bitpay] PII data masking

- crates/router/src/connector/adyen/transformers.rs
populate connector_transaction_id for Adyen Payment Response - (RedirectionResponse and QrCodeResponseResponse)
PIx via Adyen request  - (it uses QrCodeResponseResponse)
```
{
"profile_id": "pro_sx78reJN0zgRzB5UGicx",
"payment_method_type": "pix",
"bank_transfer": {
"pix": {}
}
},
"billing": {
"address": { …
```
> feat(connector): [Adyen] populate connector_transaction_id for Adyen Payment Response

- crates/router/src/connector/cybersource/transformers.rs
Mask pii information passed and received in the connector request and response for Cybersource.
1.a. create a 3DS payment
```
--header 'api-key: dev_sJlLjo5AQkfrDpPH0IEmB0gKzEgOLRr4CnI0PeHyePVJmCEoww6B9bkUjcVFyIFF' \
--data-raw '{
"amount": 0,
"currency": "PLN",
"customer_id": "abc",
"return_url": "https://hs-payments-test.netlify.app/payments",
"email": "arjun.karthik@juspay.in",
"description": "Its my first …
```
>  refactor(connector): [Cybersource] Mask PII data 

- crates/router/src/compatibility/stripe/payment_intents.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/refunds.rs
- crates/router/src/compatibility/stripe/refunds/types.rs
- crates/router_env/src/logger/types.rs
Added compatibility layer request logs for better debugging
Do payment create using stripe compatibility layer check for CompatibilityLayerRequest .
curl :
payment Create 
```
curl --location 'http://localhost:8080/vs/v1/payment_intents' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'User-Agent: helloMozilla/5.0 (Linux; Android 12; SM-S906N Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.119 Mobile Safari/537.36' \
--header 'api-key: dev_Ibies6buknSjqpSrY4H5ZHreWhFssUebckGhFmrBMHf4xf7uvF0MDnhxf2PVincI' \
--data-urlencode 'amount=2000' \
--data-urlencode 'currency=AED' \
--data-urlencode 'confirm=true' \
--data-urlencode 'payment_method_data%5Btype%5D=card' \
--data-urlencode …
```
> refactor(compatibility): added compatibility layer request logs

- crates/router/src/connector/forte/transformers.rs
Mask pii information passed and received in the connector request and response for Forte.
1.a.1 Card Payment 
```
--header 'api-key: dev_LQJkIZUCjJegIRLaclDqzXFZi5g76kp3AjfZ18bxUroPYL9iTNqSbMTiNkvzTO62' \
--data-raw '{
"billing": {
"address": {
"line2": "Harrison …
```
> refactor(connector): [Forte] Mask PII data

- config/development.toml
- crates/router/src/routes/health.rs
- crates/router/src/routes/lock_utils.rs
- crates/router_env/src/logger/types.rs
Added logs health and deep health
Do Health and deep Health checks and check for flow logs
curl:
Health
```
curl --location 'http://localhost:8080/health' \
--data ''
```
Deep Health
```
curl --location 'http://localhost:8080/health/ready' \
--data ''
```
sample Logs
```
{
"message": "[ROOT_SPAN - END]",
"hostname": "sahkal.poddar-MacBookPro",
"pid": 73552,
"env": "development",
"level": "INFO",
"target": "router::middleware",
"service": "router",
"line": 150,
"file": "crates/router/src/middleware.rs",
"fn": "ROOT_SPAN",
"full_name": "router::middleware::ROOT_SPAN",
"time": "2024-02-22T11:01:23.456202000Z",
"request_id": "018dd07a-297c-7a35-b506-469c75b6e2b2",
"flow": "HealthCheck",
"extra": {
"http.scheme": "http",
"otel.name": "HTTP GET /health",
"http.user_agent": …
```
> refactor(router): added logs health and deep health

- crates/router/src/connector/mollie/transformers.rs
Mask pii information passed and received in the connector request and response for Klarna.
1. Create an Apple pay payment
2. Check if `apple_pay_payment_token`  in the `masked_response` is masked
```
curl --location '{{base_url}}/analytics/v1/connector_event_logs?type=Payment&payment_id={{payment_id}}' \
--header 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'authorization: Bearer JWT_token' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
--header 'Referer: https://integ.hyperswitch.io/' \
--header 'api-key: {{api-key}}' \
--header 'sec-ch-ua-platform: "macOS"'
```
>  refactor(connector): [Mollie] Mask PII data 

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
add wasm dashboard changes for cashtocode to support AUD, INR, JPY, NZD, ZAR currency
test case - in dashboard, for evoucher pm type for cashtocode, fields such as username password mid should be present for AUD, INR, JPY, NZD, ZAR
> chore(configs): [Cashtocode] wasm changes for AUD, INR, JPY, NZD, ZAR currency 

- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_update.rs
This PR removes the validation such that mandate data to be an optional field and not a required param for setup_future_usage: off-session payments
Before removing validation - 
```
--header 'api-key: dev_nDlEYaebMeZFC4W7OzfK7g3ohwAqztjYxNVk58rg755miOXOFdmB3CBGJzRqvMEs' \
--data-raw '{
"amount": 0,
"customer_id": "cus_eTs98Of0QUAoWNfv7Fyt", …
```
> fix(mandates): remove validation for `mandate_data` object in payments create request

- crates/connector_configs/src/common_config.rs
- crates/connector_configs/src/connector.rs
- crates/connector_configs/src/response_modifier.rs
- crates/connector_configs/src/transformer.rs
- crates/diesel_models/src/enums.rs
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/adyen/transformers.rs
- postman/collection-dir/adyen_uk/Flow Testcases/Happy Cases/Scenario5-Void the payment/Payments - Cancel/event.test.js
- postman/collection-dir/adyen_uk/Flow Testcases/Happy Cases/Scenario5-Void the payment/Payments - Retrieve/event.test.js
- postman/collection-dir/adyen_uk/Flow Testcases/QuickStart/Payment Connector - Create/request.json
- Update Connector Account configs for WASM build
- Update Postman Collection test case for Cancelled payments
- Make `endpoint_prefix` as Optional in MCA-create
- Change `connector_refund_id` to `psp_reference`
- Add support to enforce 3DS
#3911 
- Create a manual capture payment and Cancel it, it should go into processing
``` 
curl --location 'http://localhost:8080/payments/pay_7RzGoWYbCpeSHynBpytc/cancel' \
--header 'api-key: dev_LyWBxSXvkIRgcdWNLamgVQul9tMWq2axdKYlmJSwSFbv0nfDsppaJ6UwSbny0PBm' \
--data '{"cancellation_reason":"requested_by_customer"}'
```
RESPONSE:
```
{
"payment_id": "pay_AF6YTcabCeegWRQUWjdZ",
"merchant_id": "postman_merchant_GHAction_b6d214c4-4173-4a86-b4e1-52478efba2ca",
"status": …
```
> fix(wasm): [Adyen] update connector account configs and integration bugs

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments/tokenization.rs
Main PR - https://github.com/juspay/hyperswitch/pull/3919
> fix(payment_methods): insert locker_id as null in case of payment method not getting stored in locker

- crates/router/src/connector/checkout/transformers.rs
Mask pii information passed and received in the connector request and response for Checkout.
1. Create a payment with Apple pay 
2. Create a payment with Google pay
Generate Google pay token from: https://jsfiddle.net/34wxopb2/
    `'gateway': 'checkoutltd'`,
    `'gatewayMerchantId': 'public_key'`
```
--data-raw '{
"amount": 7000, …
```
>  refactor(connectors): [Checkout] PII data masking 

- crates/router/src/connector/fiserv/transformers.rs
Mask pii information passed and received in the connector request and response for Fiserv.
1. Create a card payment with fiserv
```
--data-raw '{
"billing": {
"address": {
"city": …
```
>  refactor(connector): [Fiserv] Mask PII data

- config/config.example.toml
- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
- config/docker_compose.toml
The Bankofamerica connector now includes a currency filter, restricting support exclusively to USD payments.
Following are the paths where you can find config files:
1. `config/development.toml`
2. `config/deployments/integration_test.toml`
3. `config/deployments/sandbox.toml`
4. `config/deployments/production.toml`
https://github.com/juspay/hyperswitch/issues/3960
1. Payment Method List needs to be verified for USD and Non-USD payments via BOA:
Request: `curl --location 'http://localhost:8080/account/payment_methods?client_secret=CLIENT_SECRET_HERE' \
--header 'api-key: API_KEY_HERE'`
> chore(configs): [BOA] Add USD Currency Filter Configuration

- crates/test_utils/src/main.rs
- postman/collection-dir/nmi/Flow Testcases/Happy Cases/Scenario9-Update amount with automatic capture/Payments - Confirm/request.json
- postman/collection-dir/nmi/Flow Testcases/Happy Cases/Scenario9a-Update amount with manual capture/Payments - Confirm/request.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/.meta.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario23- Update Amount/Payments - Confirm/request.json
- postman/collection-json/nmi.postman_collection.json
- postman/collection-json/stripe.postman_collection.json
This PR is a fix for postman CI failing due a bug introduced in https://github.com/juspay/hyperswitch/pull/3807.  
As we can see here in CI's commit, https://github.com/juspay/hyperswitch/commit/cd7040fa8cad2e69a53e3ed609c9eb8a8a17495a, it is clear that NMI and Stripe collection are the ones that are affected which again can be confirmed with https://github.com/juspay/hyperswitch/actions/runs/8148897592/job/22272607599
Closes #3955 
People are shouting that the collections are failing. We've to keep them calm.
NMI
Stripe
> ci(postman): hotfix for stripe and nmi collections failing

- crates/router/src/connector/checkout/transformers.rs
fixes [4426](https://github.com/juspay/hyperswitch-cloud/issues/4426)
Create a payment via checkout connector
`{
"amount": 1040,
"amount_to_capture": 1040,
"card": {
"card_number": "4005519200000004",
"card_exp_year": "2099",
}
},
"billing": {
"address": {
"line3": …
> refactor(connector): [Checkout] handle default cases for dispute status mapping

- crates/router/src/services/authentication/blacklist.rs
Use MGet to check whether role or user is blacklisted in KV. Instead of checking user and role separately, MGet can help to do it in one call.
Enhancement
Singup --> Sigin --> Create a new role --> Invite new user with newly created role --> Sign In new user --> perform some operations  which the user with assigned role can perform --> now update the role  --> try performing same operation for the newly invited user. It won't be valid since role has been blocklist.
Can also check KV for blocklisted role_id and user_id.
Curls for singup/singin
```
--header 'Cookie: token=JWT' \
--data-raw '{
"email": "test121@juspay.in",
"password": "Test@12",
"country": "IN"
}
'
```
``` …
```
> fix(user): use mget to check in blocklist

- crates/openapi/src/openapi.rs
- crates/openapi/src/routes/merchant_account.rs
- openapi/openapi_spec.json
Added API reference for enabling/disabling KV for a merchant
Added doc for KV toggle APi
NA
> chore(doc): add API ref for KV toggle

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments/tokenization.rs
- crates/router/src/routes/payment_methods.rs
Set the initial payment method as default until its explicitly set
- Create an MA and a MCA
- Do a save card payment
- Do a ListPaymentMethodsForCustomers the default flag would be set to true for the initial card
- Do a save card payment, with other card , its default flag would be set to false, until explicitly set to true , using the endpoint `/customers/:customer_id/payment_methods/:payment_method_id/default`
```
curl --location --request POST 'http://localhost:8080/customers/{customer_id}/payment_methods/{payment_method_id}/set' \
--header 'api-key: epk_bf2209db8af14c04b811bce74e0d1202'
```
> feat(payment_method): set the initial payment method as default until its explicitly set

- Cargo.lock
- crates/analytics/Cargo.toml
- crates/analytics/src/lib.rs
- crates/router/src/configs/secrets_transformers.rs
- crates/router/src/configs/settings.rs
- crates/router/src/routes/app.rs
This PR adds support for kms decrypting the analytics config
Locally set up aws kms and decryption of analytics config was successful.
Currently Sandbox uses clickhouse setup, so this PR cannot be tested. Can be deployed in custom pod by using Sqlx there.
> refactor: kms decrypt analytics config

- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/errors/transformers.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/routes/payment_methods.rs
If a payment method is set as a default payment method for a customer and it is tried to be deleted, we throw a invalid request error.
1. Store a card or any other payment method
2. Set that payment method as default
```
curl --location --request POST 'http://localhost:8080/customers/cus_aXfFGQOFT7JFU47GYhZK/payment_methods/pm_37h7qElY2aTWBEPSgovJ/default' \
--data ''
```
3. Now try to delete that default payment method
```
curl --location --request DELETE 'http://localhost:8080/payment_methods/pm_37h7qElY2aTWBEPSgovJ' \
--header 'api-key: abc'
```
> refactor(payment_methods): prevent deletion of default payment method for a customer

- crates/api_models/src/payments.rs
- crates/router/src/core/payments/helpers.rs
Store `ApplepayPaymentMethod` in `payment_method_data` column of `payment_attempt` table.
Payment Create
```
{
"amount": 650,
"billing": {
"address": {
"line3": "Harrison …
```
> refactor(router): store `ApplepayPaymentMethod` in `payment_method_data` column of `payment_attempt` table

- crates/router/src/services/authentication/blacklist.rs
`mget` is not working in the hosted version. So, this PR will revert the #3945 which uses `mget``.
closes #4000 
Authentication and authorization should work as expected.
1. Signin with any user
```
curl --location 'http://localhost:8080/user/signin' \
--data-raw '{
"email": "user email",
}'
```
Response:
```
{
"token": JWT,
"merchant_id": "merchant_id",
"name": "user name"
"email": "user email",
"verification_days_left": null,
"user_role": "org_admin"
}
```
2. Try to hit any api which uses token.
```
curl --location 'http://localhost:8080/user/role/list?groups=true' \
```
Response:
```
[
{
"role_id": "merchant_view_only",
"groups": [
"operations_view",
"connectors_view", …
```
> fix(users): revert using mget in authorization

- .github/workflows/CI-pr.yml
- .github/workflows/CI-push.yml
In the `CI-pr` workflow we had hardcoded  `rust-version` to be installed for the `check-msrv`. This pr adds a step to get rust version from `Cargo.toml`.
> ci: add a step in `check-msrv` get the rust version from `Cargo.toml`

- crates/api_models/src/payments.rs
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/.meta.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario32-Ensure API Contract for Payment Method Data/Payments - Card Payment Method/.event.meta.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario32-Ensure API Contract for Payment Method Data/Payments - Card Payment Method/event.test.js
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario32-Ensure API Contract for Payment Method Data/Payments - Card Payment Method/request.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario32-Ensure API Contract for Payment Method Data/Payments - Reward Payment Method/.event.meta.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario32-Ensure API Contract for Payment Method Data/Payments - Reward Payment Method/event.test.js
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario32-Ensure API Contract for Payment Method Data/Payments - Reward Payment Method/request.json
- postman/collection-json/stripe.postman_collection.json
This PR fixes the deserialization of `payment_method_data` for reward payment method.
postman tests
> fix(deserialization): deserialize reward payment method data

- crates/router/src/connector/trustpay/transformers.rs
Error mapping done to code `100.390.105`
PR merged in main - #3968
\
No testing can be done since it matches error code in production which cant be replicated
> fix(connector): [Trustpay] Add mapping to error code 100.390.105

- crates/router/src/connector/iatapay/transformers.rs
Mask pii information passed and received in the connector request and response for Iatapay.
1. UPI Payment Create
```
--data-raw '{
"customer_id": "IatapayCustomer",
"upi": { …
```
> refactor(connector): [Iatapay] Mask PII data 

- crates/router/src/connector/payeezy/transformers.rs
- crates/router/src/connector/payme/transformers.rs
Mask pii information passed and received in the connector request and response for Payme and Payeezy.
1. Create a 3ds payment with payme
```
curl --location 'https://cee4-219-65-110-2.ngrok-free.app/payments' \
--header 'api-key: {{api_key}}' \
--data-raw '{
"card": { …
```
>  refactor(connector): [Payme][Payeezy] Mask PII data 

- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
added threedsecureio base url in deployment config files
> chore: add threedsecureio base url in deployment config files

- crates/router/src/core/payment_methods/cards.rs
https://github.com/juspay/hyperswitch/pull/3953
Similar to above issue but now the PR refactors to filter out any wallet payment method from mca if it is saved by a customer
1. Create mca
```
curl --location 'http://localhost:8080/account/merchant_1709561576/connectors' \
--data '{
"api_key": "abc"
},
{
{
"Visa",
"Mastercard"
], …
```
> refactor(payment_methods): filter wallet payment method from mca based on customer pm

- crates/api_models/src/payments.rs
- crates/openapi/src/routes/customers.rs
- crates/openapi/src/routes/payments.rs
- openapi/openapi_spec.json
update open-api spec to have payment changes
> refactor(openai): update open-api spec to have payment changes

- crates/router/src/connector/cybersource/transformers.rs
Create mandate with connector if `setup_future_usgae: off_session` and `customer_acceptance` is present.
#4049 
- Create a Mandate Payment
```
--header 'api-key: dev_j23UDZ4X6JcYN6Jz3esn78yIMGYYCEjA3oCBvwogG8vqb8AjGnFGRMezdSkxlJDX' \
--data-raw '{
"amount": 2810,
"customer_id": "shanks5",
"description": "Its my first payment", …
```
> fix(connector): [cybersource] update mandate condition

- config/deployments/production.toml
- config/development.toml
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/adyen/transformers.rs
- Update Psync response handler to consume the incoming webhook response
- Handle Webhook Status Mapping
Adyen Production URL and currency-countries supported for Ideal and soft
#3976 
#4063 
For Adyen all the subsequent payments are confirmed via Webhooks, So test Capture, Cancel, Refunds and Wallets payments.
Payment Methods Need to be tested
- Klarna (Manual Capture)
```
--header 'api-key: dev_ooWwJsn2dIWX2JrPdAbV6SYbxVBF5W0LY2ZvWHV2U3F5UXRQdHDAm9zt5q7Hk0HL' \
--data-raw '{ …
```
> fix(connector): [adyen] handle Webhook reference and object

- crates/router/src/connector/iatapay/transformers.rs
Fixes [4526](https://github.com/juspay/hyperswitch-cloud/issues/4526)
Payment Create 
```
{
"customer_id": "IatapayCustomer",
"upi": {
"vpa_id": "successtest@iata"
}
},
"billing": {
"address": {
"country": …
```
> fix(connector): [Iatapay] remove unused fields from auth response
