- .github/PULL_REQUEST_TEMPLATE.md
Refactor code formatting command in PR template as build pipeline fails with the existing command for some scenario.
Refactor formatting command to avoid unwanted formatting errors during build pipeline
NA
> docs(github): add `--all` flag to rustfmt command in PR template

- crates/api_models/src/payments.rs
- crates/router/src/core/payments/flows/session_flow.rs
This PR will fix missing merchant info when fetching the session token for gpay.
This change is required because without merchant info field in the session token, the google pay sdk cannot be initialized.
Fetch session token for google pay
> fix(gpay): send merchant info field

- crates/router/src/core/errors.rs
- crates/router/src/types/api.rs
This PR removes some variants of the `ApplicationError` enum that are no longer used. Found that there were quite a lot of unused variants when working on #352.
N/A
N/A
> chore(errors): cleanup unused `ApplicationError` variants

- crates/router/src/core/payments/transformers.rs
Fixed error code being null in payments response
Fixed error code being null in payments response
> fix: Fix error code being null in response

- crates/router/src/connector/globalpay.rs
- crates/router/src/core/errors/utils.rs
Required field validation is done in connector side and appropriate error message is also getting printed but this message is not being shown in the response body. this fix will help passing the error message for required field validation 
Pass error message to response body instead of changing the context
> fix(connector): pass error message to response body instead of changing the context for required field validation

- Cargo.lock
- crates/api_models/Cargo.toml
- crates/api_models/src/admin.rs
- crates/router/Cargo.toml
- openapi/generated.json
This PR updates the repository URL for the `utoipa` crate to use the upstream repository URL instead of my fork.
Since juhaku/utoipa#436 was merged, my fork is no longer required. However, since it could take some time for the next release of the crate, we'll be using it as a git dependency.
Regenerated the OpenAPI spec file, there are no changes in property order of the schemas.
> build(deps): use utoipa crate upstream URL as git dependency

- crates/router/src/lib.rs
- crates/router/src/routes/app.rs
> List of payment method api is moved to OLTP instead of OLAP
> Add feature gates to mandate OLAP which was missing
> Add mandate services in OLAP and OLTP while making the server app.
Change in OLAP and OLTP separation
> fix: changes in olap oltp separation

- crates/api_models/src/refunds.rs
- crates/router/src/core/refunds.rs
Add field `created_at` and `updated_at` in refunds response.
The field helps to track when the refund was created and updated, and display them if necessary.
> refactor(api_models): add `created_at` and `updated_at` fields in `RefundResponse`

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- README.md
This PR fixes broken links to the contributing guidelines.
N/A
N/A
> docs: fix broken link to contributing guidelines

- crates/storage_models/src/query/generics.rs
Changed generic DB queries visibility from `pub(super)` to `pub`.
Generic queries need to be used by other repos.
> refactor(storage_models): made generic queries public

- crates/router/src/core/admin.rs
- crates/router/src/core/errors.rs
- crates/router/src/core/errors/utils.rs
- crates/router/src/utils.rs
- crates/router/src/utils/ext_traits.rs
Make `router` utils and error utils public.
None
Usage of router-centric utilities in external crates.
> refactor(router): make utilities public

- crates/api_models/src/enums.rs
- crates/router/src/core/mandate.rs
In case its not a mandate transaction , check for `setup_future_usage` flag to save a card
> fix: Use setup future usage for saving card

- crates/redis_interface/src/types.rs
This PR fixes a mistake in my previous PR #352 where I missed out adding a `#[serde(default)]` annotation to the `RedisSettings` struct.
Bug fix.
Specified a subset of redis settings and started `router`. The application now runs without panicking.
> fix(redis_interface): add missing `#[serde(default)]` annotation to `RedisSettings`

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/types/api/payment_methods.rs
List payment methods needs to have redirect url in it for sdk to fallback incase of any failure.
N/A
Manual
> feat: Add redirect url to pm list

- crates/router/src/core/payments/operations/payment_update.rs
Don't update payment intent in case of requires_capture status.
Merchant shouldn't be able to update the payment intent once the amount is already blocked for the payment method.
> fix: don't update payment on requires_capture

- Cargo.lock
- crates/drainer/Cargo.toml
- crates/drainer/src/main.rs
- crates/drainer/src/settings.rs
- crates/router/Cargo.toml
- crates/router/src/bin/router.rs
- crates/router/src/bin/scheduler.rs
- crates/router/src/configs/settings.rs
This PR migrates from the `structopt` crate to the `clap` crate for parsing CLI arguments.
I was setting up `cargo-deny`. One of the advisory checks failed stating that `ansi_term` (a dependency of `structopt`) is unmaintained ([`RUSTSEC-2021-0139`](https://rustsec.org/advisories/RUSTSEC-2021-0139.html)) and one of the suggested dependency migrations is to migrate to a newer version of `clap`.
Checked the help messages generated by both versions, they are similar.
**Help message generated by `structopt`:**
```text
router 0.2.0-8ad5b37-2023-01-18T11:17:16Z
USAGE:
router [OPTIONS] [SUBCOMMAND]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-f, --config-path <config-path>    Config file. Application will look for "config/config.toml" if …
```
> build(deps): migrate to `clap` from `structopt`

- crates/router/src/connector/shift4.rs
Fixing the refund sync flow. previously it was taking the transaction_id now made it to take connector_refund_id
Ran it in postman
> fix(connector): fix rsync for shift4

- crates/router/src/connector/checkout.rs
- crates/router/src/connector/stripe.rs
This PR will refactor `stripe` and `checkout` request to send the token as `Bearer` instead of asking merchant to add the token type while creating the token.
Instead of requesting the merchant to provide this information for a connector, since we have all information of how to send a request to connector, it is better if this is done in the code.
- Create a connector account with just the api key, without token type ( Bearer or Basic added )
- Create a payment
> refactor(stripe): use bearer explictly when calling connectors

- crates/storage_models/src/merchant_account.rs
- crates/storage_models/src/schema.rs
Running the latest migrations causes the `routing_algorithm` and `metadata` fields to go out of order in `schema.rs` w.r.t the DB models. This PR fixes that.
- [schema.rs](https://github.com/juspay/hyperswitch/blob/d776c0a9f18f29207109dc454918f70f32453607/crates/storage_models/src/schema.rs)
- [merchant_account.rs](https://github.com/juspay/hyperswitch/blob/d776c0a9f18f29207109dc454918f70f32453607/crates/storage_models/src/merchant_account.rs)
The field ordering in `schema.rs` table definition and the actual db type should be identical.
compiler-guided + stripe payments. Earlier it used to error out.
> fix(router): fix incorrect order of routing_algorithm and metadata fields in db models

- crates/router/src/configs/validations.rs
This PR updates the visibility of configs validation functions to be public.
N/A
N/A
> refactor(configs): make visibility of validation functions public

- crates/router/src/connector/aci.rs
- crates/router/src/connector/braintree.rs
- crates/router/src/connector/rapyd.rs
- crates/router/src/connector/stripe.rs
For connector aci, Braintree, rapyd, stripe request encoding should be done using "convert_and_url_encode".
Fix for connector requests url encoding.
No tests available.
> fix(aci,braintree,rapyd,stripe): URL encode request params instead of JSON

- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/payments/operations/payment_response.rs
This is a minor change, which allows individual access to the `error_code` propagated by the connector, which is caught in `ExternalConnectorError`
> feat(errors): seperate code in `ExternalConnectorError`

- crates/router/src/connector/braintree.rs
- crates/router/src/connector/rapyd.rs
For connector Braintree, rapyd request encoding should be done using "convert_and_encode".
Fix for connector requests encoding.
No tests available.
> fix(braintree,rapyd): encode request params instead of JSON

- crates/router/src/connector/checkout.rs
- crates/router/src/connector/checkout/transformers.rs
This fixes checkout getting `requires_capture` error even after an automatic capture payment.
Checkout getting `requires_capture` status even in automatic capture because when you make a payment with automatic capture in checkout it will be authorized first and captured few seconds later. So in balances the `amount_to_capture` will not be 0 when we get the response.
> fix(checkout): status mapping for payment

- crates/router/src/connector/authorizedotnet/transformers.rs
- crates/router/src/connector/checkout.rs
- crates/router/src/connector/shift4.rs
- crates/router/src/connector/stripe.rs
- crates/router/src/connector/worldline.rs
- crates/router/src/core/errors.rs
- crates/router/src/core/refunds.rs
- crates/router/src/core/utils.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/aci.rs
- crates/router/tests/connectors/authorizedotnet.rs
- crates/router/tests/connectors/checkout.rs
- crates/router/tests/connectors/utils.rs
This change will move the `connector_refund_id` into request while also making the updation of router_data for `access_token` step in refund sync optional for connectors that doesn't support it.
This change resolves a bug where the refund sync was failing for every connector which doesn't have access token
This is an sample of refund with connector that needs access_token (i.e. braintree):
This the sample output of refund sync for connector that doesn't need access_token (i.e. stripe):
Here both the calls provide identical result as expected with refund sync
> fix: move `connector_refund_id` to request

- crates/router/src/connector/adyen.rs
Previously when status mapping was not proper for adyen when sync was done. This PR addressed that issue.
Manual
> fix(adyen): fix `capture_method` not considered during payments sync

- crates/storage_models/src/refund.rs
- crates/storage_models/src/schema.rs
With the latest migration adding a `refund_error_code` field, the ordering of the fields in `schema.rs` was not the same as in the storage model. This PR fixes that.
Diesel expects the field ordering of the `schema.rs` table definition and the storage model to be identical.
compiler-guided.
> fix(router): fix refund error code diesel field ordering

- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/operations/payment_start.rs
- crates/router/src/core/payments/operations/payment_update.rs
Payments session did not have a check for creating the session token, which would allow users to create session token for any `succeeded` or `failed` payment.
While adding this check to `payment_session` operation, I found out that the same logic is being used in other operations too. There is a function `helpers::validate_payment_status` which will validate the payment intent status based on the `statuses` which the intent is not allowed to have. It will throw an error if the condition fails.
- Update a payment which has status of `requires_capture`
- Confirm a payment which has already been `confirmed` and `succeeded`
> refactor(core): validate payment status using common function

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/core/payment_methods/vault.rs
After the card detail are fetched from basilisk, payment_method_id is not set, modified DeleteCardResponse from legacy locker getting parsing error
we can test it on sbx only
> fix: payment_method_id not populated

- crates/router/src/connector/cybersource/transformers.rs
- crates/router/src/connector/globalpay/response.rs
- crates/router/src/connector/globalpay/transformers.rs
Globalpay throw error message for failure transaction if it has the message.
Previously for failure transactions only the `failed` status is shown, now adding the reason for failure also to the response
Ran unit tests in local
> fix(connector): fix globalpay error handling

- config/Development.toml
- config/config.example.toml
- crates/router/src/configs/defaults.rs
- crates/router/src/configs/settings.rs
- crates/router/src/configs/validations.rs
- crates/router/src/scheduler/consumer.rs
- crates/router/src/scheduler/utils.rs
This change introduces 2 changes in the configuration in the `[scheduler]` section
```diff
[scheduler]
stream = "SCHEDULER_STREAM"
- consumer_group = "SCHEDULER_GROUP"
+ [scheduler.consumer]
+ consumer_group = "SCHEDULER_GROUP"
+ disabled = false 
```
> fix: add disable env flag for consumer

- connector-template/test.rs
- crates/router/tests/connectors/utils.rs
For card payment method default unit tests should be generated while adding a connector using add_connector script.
Add more test cases in connector-template/test.rs file, So that default test cases will be generated every time while adding a connector. If connector does not support any flow or payment method, then test cases for such scenarios can be removed from the test file.
Closes #467.
Tested by creating a new connector. As expected new test cases were generated in the test file.
> feat(connector-template): add more default tests for card payment method

- crates/storage_models/src/query/refund.rs
Update of refund was happening with the serial `id` primary key field, but in the KV flow we won't know the serial id and thus the update would fail. This PR solves that by updating based on `(merchant_id, refund_id)`.
Manual
> fix(refund): fix failing refund update with KV storage backend

- crates/api_models/src/admin.rs
- crates/router/src/core/admin.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/routes/admin.rs
- crates/storage_models/src/merchant_connector_account.rs
- crates/storage_models/src/query/merchant_connector_account.rs
- crates/storage_models/src/schema.rs
- migrations/2023-02-07-070512_change_merchant_connector_id_data_type/down.sql
- migrations/2023-02-07-070512_change_merchant_connector_id_data_type/up.sql
Change the `merchant_connector_id` data type to use unique id.
Since we want to implement KV for Merchant connector account table we need to have a unique id as key for the table.
> refactor: use unique id for merchant_conenctor_id instead of int

- config/config.example.toml
- crates/drainer/src/lib.rs
- crates/drainer/src/main.rs
- crates/drainer/src/settings.rs
- crates/drainer/src/utils.rs
- crates/router/src/configs/defaults.rs
- crates/router/src/configs/settings.rs
This change will add sleep interval to drainer once a cycle is completed
```
[drainer]
loop_interval: 500, // in milliseconds
```
> feat: add tick interval to drainer

- crates/router/src/services/api.rs
This change fixes the mismatched orientation of the loader on mobile screens
> fix: fix the loader orientation on mobile

- .github/workflows/CI.yml
This PR enables CI checks to run on PRs added to the merge queue.
Reference: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
Merge queues should reduce quite a lot of maintenance effort in merging PRs that have passed all required checks.
I hope it works! :tm:
> ci: run CI checks on merge queue events

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/access_token.rs
- crates/router/src/core/refunds.rs
Klarna redirect payments were failing because of default error that was present in router data, which was populated by access token result.
- Create payment
- Successful redirection
> fix(core): use guard for access token result

- crates/router/Cargo.toml
- crates/router/src/core/payment_methods/vault.rs
- crates/router/src/services.rs
- crates/router/src/services/encryption.rs
- Add feature flag restriction for basilisk features related to encryption
Openssl compiles for a limited set of architectures hence removing it from the default set of dependencies
I tested for the  x86_64 apple architecture
> fix(router): feature gate openssl deps for basilisk feature

- crates/router/src/lib.rs
- crates/router/src/middleware.rs
This PR changes the visibility of the `router::middleware` module to be public.
This should help sharing middleware code across multiple services.
N/A
> refactor(middleware): change visibility to `pub`

- crates/router/src/core/payments/operations/payment_response.rs
Send the full body during a payment sync call when calling connector.
When calling a connector during a psync call, if there is a connector error, then payments sync call would send the shorter version.
> refactor: send full payment object for payment sync

- crates/redis_interface/src/lib.rs
- crates/router/src/core/errors.rs
- crates/router/src/db/cache.rs
- crates/router/src/db/ephemeral_key.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/db/payment_attempt.rs
- crates/router/src/db/payment_intent.rs
- crates/router/src/db/queue.rs
- crates/router/src/db/refund.rs
- crates/router/src/scheduler/producer.rs
- crates/router/src/scheduler/utils.rs
- crates/router/src/services.rs
Created a global flag to check if redis is available or not if it's not available send 500 error to all reamaining requests.
Currently if redis goes down currently after `reconnect_attempts` reached fred will currently close the client and block the whole application. 
Manual
> fix: throw 500 error when redis goes down

- config/Development.toml
- config/config.example.toml
- crates/router/src/configs/defaults.rs
- crates/router/src/configs/settings.rs
- crates/router/src/connection.rs
- crates/router/src/core/errors.rs
- crates/router/src/db/address.rs
- crates/router/src/db/configs.rs
- crates/router/src/db/connector_response.rs
- crates/router/src/db/customers.rs
- crates/router/src/db/events.rs
- crates/router/src/db/locker_mock_up.rs
- crates/router/src/db/mandate.rs
- crates/router/src/db/merchant_account.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/db/payment_attempt.rs
- crates/router/src/db/payment_intent.rs
- crates/router/src/db/payment_method.rs
- crates/router/src/db/process_tracker.rs
- crates/router/src/db/refund.rs
- crates/router/src/db/reverse_lookup.rs
- loadtest/config/Development.toml
Do not panic while getting db connection. Instead of that just throw 500 error. This PR also makes connection timeout in Database configurable.
When database goes down we don't want our application panic and stop actix workers since restarting it has much overhead. So instead just 500 error.
Start the application and bring down the database and try to make a payment. Throws 500 error.
> refactor: Throw 500 error on database connection error instead of panic

- crates/router/src/core/errors/utils.rs
…ntext
This change works on improving the error tracking from the stack trace, currently for some errors tracking the exact error location was difficult because of the wrapper over them. This change adds `#[track_caller]` to such functions allowing the actual call_site to be tracked
> feat: add `track_caller` to functions that perform `change_context`

- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_status.rs
In the case where we do not have the connector transaction id of a connector force_sync should not fail, rather we need it not to call the connector it this case.
> fix: don't call connector if connector transaction id doesn't exist

- crates/router/src/core/payments/operations/payment_response.rs
This will allow connectors with status code 2xx to pass through. While any error with a status code other than 2xx will be converted into router error
> fix: allow errors with status code 200 to pass

- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
Since we are passing the attempt id as reference to few connectors, some might not accept special characters.
Closes #603.
> refactor: use simple uuid instead of hyphens

- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_update.rs
- crates/storage_models/src/payment_intent.rs
Allow the `setup_future_usage` associated with the payment intent to be updated in Payment Update and Confirm APIs.
None
Local, compiler-guided, stripe payments.
> fix(router): allow setup future usage to be updated in payment update and confirm requests

- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/checkout/transformers.rs
- crates/router/src/connector/rapyd/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/services/api.rs
- Avoid code repetition for converting urls to redirection data.
- Refactor rapyd connector to use enums for next action.
Manual Compiler guided, Checked for stripe, checkout and adyen connectors.
> refactor(redirection): `From` impl for redirection data for ease of use

- crates/api_models/src/errors/types.rs
Adding zero-padding for the error codes, ie. `HE_0` → `HE_00`
> fix: add zero-padded formatting for error code

- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
Passing currency in the `VerifyRequestData`, for some connectors they require to send currency even in the case of `0` amount payment.
> fix: add currency in verify request data

- crates/api_models/src/admin.rs
- crates/api_models/src/payment_methods.rs
- crates/router/src/core/admin.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/routes/payment_methods.rs
Supported country and currency , the size exceed the allowed request size, refactoring how these field are passed in the MCA and in the List PM api
Changing the format of the fields
{
"enable_all": false,
"disable_only": ["INR" ],
"enable_only": ["EUR"]
}
Testing with passing filters in list pm
> refactor: Pass country and currency as json format in MCA

- crates/masking/src/secret.rs
- crates/router/src/connector/aci/transformers.rs
- crates/router/src/connector/authorizedotnet/transformers.rs
- crates/router/src/connector/braintree/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
- crates/router/src/connector/globalpay.rs
- crates/router/src/connector/globalpay/requests.rs
- crates/router/src/connector/globalpay/transformers.rs
- crates/router/src/connector/shift4/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/connector/worldpay/requests.rs
- crates/router/src/connector/worldpay/transformers.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/tests/connectors/globalpay.rs
Closes #308 
In connectors when mapping the PII information while building the request we are mapping as plain text(String), it is not recommended as it can be logged. so removing those logs from connector code.
> refactor(connector): remove `peek()` on PII info

- crates/common_utils/src/ext_traits.rs
Provide details on why parsing the struct failed by logging the raw bytes along with the type name which was intended to be converted to.
There were many cases where the response handling was failing because of deserialization problem. This will ease up debugging by providing relevant information.
Create a payment ( or any request where it is sure that it will fail ) and check the logs.
Example of a checkout connector.
> refactor: add better log to parse struct

- config/Development.toml
- config/config.example.toml
- config/docker_compose.toml
- crates/api_models/src/enums.rs
- crates/common_utils/src/lib.rs
- crates/router/src/configs/settings.rs
- crates/router/src/connector.rs
- crates/router/src/connector/dlocal.rs
- crates/router/src/connector/dlocal/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/lib.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/connector_auth.rs
- crates/router/tests/connectors/dlocal.rs
- crates/router/tests/connectors/main.rs
- crates/router/tests/connectors/sample_auth.toml
- loadtest/config/Development.toml
Updating support for [Dlocal](https://docs.dlocal.com) payment gateway
Payment Method: card
Supported payment flows:
1. Authorize
2. Capture
3. PSync
4. Refund
5. Void
6. RSync
New connector integration.
> feat(connector): add authorize, capture, void, refund, psync, rsync support for Dlocal connector

- Cargo.lock
- config/Development.toml
- config/config.example.toml
- config/docker_compose.toml
- crates/api_models/src/enums.rs
- crates/common_utils/Cargo.toml
- crates/common_utils/src/crypto.rs
- crates/router/src/configs/settings.rs
- crates/router/src/connector.rs
- crates/router/src/connector/bluesnap.rs
- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/types.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/bluesnap.rs
- crates/router/tests/connectors/connector_auth.rs
- crates/router/tests/connectors/main.rs
- loadtest/config/Development.toml
Updating support for [Bluesnap](https://developers.bluesnap.com/v8976-JSON/reference/bluesnap-payment-api-json) payment gateway
Payment Method: card
Supported payment flows
- [Authorize](https://developers.bluesnap.com/v8976-JSON/reference/auth-capture)
- [Capture](https://developers.bluesnap.com/v8976-JSON/reference/capture)
- [PSync](https://developers.bluesnap.com/v8976-JSON/reference/retrieve)
- [Refund](https://developers.bluesnap.com/v8976-JSON/reference/refund)
- [Cancel](https://developers.bluesnap.com/v8976-JSON/reference/auth-reversal)
-  [RSync](https://developers.bluesnap.com/v8976-JSON/reference/retrieve)
- [Webhooks](https://support.bluesnap.com/docs/about-ipns)
> feat(connector): [Bluesnap] add authorize, capture, void, refund, psync, rsync and Webhooks support 

- .github/workflows/CI.yml
Adding build only the sandbox feature in CI-CD
Build taking more time in CI-CD, even for small changes.
> chore: adding build only sandbox feature to reduce build time

- crates/router/src/core/payment_methods/cards.rs
Use shipping address country for filtering the payment methods whenever shipping address is available.
Manual, compiler guided
> refactor(pm_list): filter based on shipping country instead of billing country

- crates/router/src/compatibility/stripe/payment_intents/types.rs
The country in billing details of stripe compatibility is  mapped to country_code in address of payments request .
> fix(compatibility): map stripe country_code to payment_request country code

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
The first entry in the hashmap was being populated as empty. This PR fixes it.
PM list failing
Manual
> bugfix: populate empty hashmap and fix card_network filtering logic

- crates/router/src/core/refunds/validator.rs
Check the validate refunds only if payment method is wallet or pay_later. for other payment_methods skip this validation.
Make refunds easy and accessible to all.
> bugfix(refunds): skip validate refunds for card

- crates/api_models/src/enums.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/storage_models/src/enums.rs
- Map all responses with error to failed
- Add bank redirect enum variant
Manual
> bugfix: populate failed status and add bank_redirect

- config/Development.toml
- crates/api_models/src/payment_methods.rs
- crates/api_models/src/payments.rs
- crates/router/src/configs/defaults.rs
- crates/router/src/configs/settings.rs
- crates/router/src/core/payment_methods/cards.rs
- openapi/generated.json
Support sending bank_codes in payment_method list endpoint.
Manual
```json
{
"redirect_url": "https://www.example.com/success",
{
{
"payment_method_type": "eps",
"bank_names": [
{
"bank_name": [
"bks_bank_ag",
"btv_vier_lander_bank",
"brull_kallmus_bank_ag",
"bankhaus_schelhammer_und_schattera_ag",
"arzte_und_apotheker_bank",
"austrian_anadi_bank_ag",
"bawag_psk_ag"
],
"stripe"
]
}
]
}
]
}
]
}
```
> feat(pm_list): support for sending bank names

- config/Development.toml
- crates/router/src/core/payment_methods/cards.rs
Do not send bank_redirect field if there are no bank payment method types configured.
Add additional configuration for banks
Manual, compiler guided
> bugfix: check if bank_pm exists and then send

- crates/router/src/connector/utils.rs
- crates/router/src/connector/worldline/transformers.rs
- crates/router/tests/connectors/worldline.rs
Unit test fix, Visa card issuer support for Worldline
> fix(connector): fix wordline tests and visa card issuer support

- crates/router/src/core/payments/operations/payment_status.rs
Fixed adyen redirects because of failed psync.
Manual, confirmed with 3 colleagues.
> bugfix(adyen): adyen psync fail fix

- crates/router/src/connector/worldline/transformers.rs
- crates/router/tests/connectors/worldline.rs
Worldline connector to support payment for card number with spaces
> fix(connector): fix wordline card number validation issue

- config/config.example.toml
- crates/common_utils/Cargo.toml
- crates/router/src/configs/settings.rs
- crates/router/src/core/payment_methods/cards.rs
In an earlier PR #689, we added a global filter mapping for `<connector>.<payment_method_type>`, but according to the new requirements, the various card networks will also have the similar filters. This PR addes support for `<connector>.<card_network>` in the configuration. @bernard-eugine is compiling the list for this configuration changes
> feat(list): global filter mapping for payment methods via card network

- crates/router/src/connector/airwallex/transformers.rs
- crates/router/src/connector/applepay/transformers.rs
- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/connector/braintree/transformers.rs
- crates/router/src/connector/nuvei/transformers.rs
- crates/router/src/connector/utils.rs
Added few functions in connector utils to convert and parse incoming amount in cents to dollar value before sending it to the connector.
Certain Connectors don't take cents as input, we need to parse the incoming `amount` which is in cents to the dollar value.
Ran the possible cases in postman also verified running unit tests wherever applicable
> fix(connector): convert cents to dollar before sending to connector

- crates/router/src/core/payments/operations/payment_response.rs
Populate amount captured from amount if the status is succeeded.
We are getting amount received as none in because many connectors aren't populating it.
Manual
> fix: Populate amount_captured in case of success

- crates/router/src/core/payments/operations/payment_session.rs
Create session token only if it is enabled by the merchant. This involves parsing the payment methods enabled field for each merchant connector account and checking if `invoke_sdk_client` payment_experience for that particular payment_method_type  is enabled. 
Since the calls to `payment_methods_list` and `session_tokens` will be made in parallel, if the merchant has not enabled particular wallet then it wont be reflected in payment methods list, but this check is not there in session token creation. This PR adds that functionality.
Manual.
- Create a connector account without enabling the wallet, and call session token -> token will not be created.
- Update the connector account and enable the wallet, and call session token -> token will be created.
> feat(session_token): create session token only if pmt is enabled

- crates/api_models/src/customers.rs
- crates/api_models/src/payments.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/setup_intents/types.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/aci.rs
- crates/router/tests/connectors/adyen.rs
- crates/router/tests/connectors/authorizedotnet.rs
- crates/router/tests/connectors/checkout.rs
- crates/router/tests/connectors/utils.rs
- crates/router/tests/connectors/worldline.rs
- crates/router/tests/payments.rs
- crates/router/tests/payments2.rs
- crates/router/tests/utils.rs
- openapi/generated.json
- postman/portman-config.json
- Pass statement descriptor field to stripe.
- Replace Juspay with hyperswitch in docs
Create a payment with both `statement_descriptor` and `statement_descriptor_suffix` and check the same in stripe dashboard.
> enhance(stripe): send statement descriptor to stripe

- crates/router/src/core/api_keys.rs
- crates/router/src/types/transformers.rs
This PR removes the key ID prefix included in the plaintext API keys returned on creating a new API key. The key ID no longer needs to be sent by the user now that #639 makes it easier to identify the API key record in the database table.
This change would also simplify our merchant authentication flow and migration of API keys from the merchant account table to the API keys table.
1. Both the `key_id` and the plaintext `api_key` fields now contain the environment prefix for easier identification of the environment with which the keys can be used:
```shell
$ curl --location 'http://localhost:8080/api_keys/merchant_123' \
--header 'api-key: MyVerySecretAdminApiKey' \
--data '{
"name": "API Key 1", …
```
> refactor(api_keys): remove key ID prefix from plaintext API keys

- Cargo.lock
- crates/api_models/Cargo.toml
- crates/common_utils/Cargo.toml
- crates/drainer/Cargo.toml
- crates/drainer/src/errors.rs
- crates/redis_interface/Cargo.toml
- crates/router/Cargo.toml
- crates/router/src/core/errors.rs
- crates/storage_models/Cargo.toml
This PR uses the `Debug` implementation instead of `Display` implementation for printing error types which wrap around `error_stack::Report`.
Fixes #626.
<details>
<summary>Scenario 1: Column missing from database table</summary>
<pre>
2023-03-05T11:48:49.205284Z ERROR router::services::api: error: {"error":{"type":"api","message":"Something went wrong","code":"HE_00"}}
├╴at crates/router/src/services/api.rs:448:42
│
├─▶ {"error":{"type":"server_not_available","code":"HE_00","message":"Something went wrong"}}
│   ├╴at crates/router/src/core/api_keys.rs:120:10
│   ╰╴Failed to insert new API key
│
╰─▶ DatabaseError: An unknown error occurred
├╴at ~/hyperswitch/crates/storage_models/src/query/generics.rs:50:27
├╴Error while inserting ApiKeyNew { key_id: "dev_3CxVj7hy75r84j6v4HsU", …
> fix(errors): use `Debug` impl instead of `Display` for error types wrapping `error_stack::Report`

- connector-template/test.rs
Rename `paymentMethod` to `paymentMethodData` in `test.rs`
When  `scripts/add_connector.sh` is run, due to name mismatch, compile-time error used to occur. This PR aims to fix by renaming `paymentMethod` to `paymentMethodData` in `test.rs` under connector-template directory. 
By running `sh scripts/add_connector.sh` again after fixing the issue, the test was done that showed no error.
> fix(errors): Replace PaymentMethod with PaymentModethodData in test.rs

- crates/router/src/services/kms.rs
This PR fixes a bug with KMS errors not being logged with detailed information as to what exactly failed. 
This should ease debugging of errors originating from the AWS KMS SDK.
Manually, deployed a test build on sandbox environment.
> fix(kms): log KMS SDK errors using the `Debug` impl

- .github/workflows/auto-release-tag.yml
- .github/workflows/manual-release.yml
This PR fixes an issue with release builds not having the correct values for `VERGEN_GIT_*` environment variables. The fix is to clone the complete git history instead of just the latest commit. Additionally, this also updates the release workflows to use the official Docker GitHub actions for building and pushing Docker images.
This should help us better identify the exact builds running in sandbox and production environments.
Created a manual build, found no `VERGEN_*` related warnings.
> ci(release): specify `fetch-depth` for code checkout and use official Docker GitHub actions

- crates/router/src/db/cache.rs
- crates/router/src/db/payment_attempt.rs
- crates/router/src/db/refund.rs
- crates/router/src/db/reverse_lookup.rs
This adds cached fetches for reverse lookup table.
Since all the calls to reverse lookup table goes to the DB. Moved the fetch calls to redis cache to reduce the latency.
Manual
> feat: cache reverse lookup fetches on redis

- crates/router/src/core/api_keys.rs
- crates/router/src/core/errors.rs
- crates/router/src/db/api_keys.rs
- crates/router/src/routes/metrics.rs
- crates/router/src/scheduler/metrics.rs
- crates/router/src/services/authentication.rs
- crates/storage_models/src/api_keys.rs
- crates/storage_models/src/query/api_keys.rs
This PR updates the API key authentication code to use the API keys from the API keys table instead of the merchant account table. I'll be taking up the deprecation of the `api_key` field from the merchant account table in a separate PR.
This is an extension of PRs #511, #639 and #705, thus completely addressing #501.
Manually. After I made the change, I created a new merchant account and API key, and tested out creating customers and payments. Things worked as expected.
---
~Marking as this as draft as this is blocked by #639 and #705 being merged to `main` branch.~
> refactor(authentication): authenticate merchant by API keys from API keys table

- crates/router/src/scheduler/utils.rs
This PR addresses a clippy lint stabilized in Rust 1.68.
N/A
N/A
> chore: address Rust 1.68 clippy lints

- crates/router/src/services/api/client.rs
This PR removes the dependence on `ROUTER_HTTP_PROXY` and `ROUTER_HTTPS_PROXY` environment variables, as having multiple ways to set a proxy makes it harder to inspect if requests are being proxied or not. The recommended way to set proxy will be to set `ROUTER__PROXY__HTTP_URL` and `ROUTER__PROXY__HTTPS_URL` instead, respectively.
Better debugging of HTTP client behavior.
Manually.
> refactor(client): remove dependence on `ROUTER_HTTP_PROXY` and `ROUTER_HTTPS_PROXY` env vars

- crates/api_models/src/errors/actix.rs
- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/consts.rs
- crates/router/src/core/errors.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/lib.rs
- crates/router/src/services/api.rs
- crates/router/src/utils.rs
Added HSTS header for responses.
This header informs browsers that the site should only be accessed using HTTPS.
For reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
> feat: Add HSTS headers to response

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/vault.rs
service_name is passed as mandatory request in all the api of basilisk-v3
Needs to be tested in sbx/prod
> refactor: Add service_name to get and delete request

- crates/common_utils/src/ext_traits.rs
- crates/router/src/connector/worldline.rs
- crates/router/src/connector/worldline/transformers.rs
- crates/router/src/core/errors.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/core/webhooks/utils.rs
Webhook integration for Worldline connector
Webhook integration for Worldline connector
Manual testing
> feat(connector): add webhook support for worldline connector

- Cargo.lock
- crates/router/Cargo.toml
- crates/router/src/cache.rs
- crates/router/src/lib.rs
Added a struct for Cache which takes any type as value and string as key.
This PR adds support to generic cache struct. Which accepts any type as value and while getting it back from cache downcasts back to concrete type.
Manual
> feat: add generic in-memory cache interface

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types/api/payments.rs
Populate some fields from payment attempt table in Paymentlist response.
Populate necessary fields which we show in the dashboard from payment attempt.
Manual
> feat: populate fields from payment attempt in payment list

- config/config.example.toml
- crates/router/src/configs/settings.rs
- crates/router/src/configs/validations.rs
- crates/router/src/core/api_keys.rs
- crates/router/src/core/errors.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/core/payment_methods/vault.rs
- crates/router/src/routes/api_keys.rs
- crates/router/src/routes/app.rs
- crates/router/src/services.rs
- crates/router/src/services/authentication.rs
- crates/router/src/services/encryption.rs
- crates/router/src/services/kms.rs
This PR refactors the KMS code to use a shared KMS client for all KMS operations within the codebase. In addition, this removes operation specific KMS configuration that was used earlier, and makes use of a single KMS configuration instead.
The `aws_key_id` and `aws_region` config values under the `[api_keys]` and `[jwekey]` tables have been removed, which are instead available as `key_id` and `region` config values under the `[kms]` table. 
In terms of environment variables, the `ROUTER__JWEKEY__AWS_KEY_ID`, `ROUTER__JWEKEY__AWS_REGION`, `ROUTER__API_KEYS__AWS_KEY_ID` and `ROUTER__API_KEYS__AWS_REGION` environment variables have to be removed, and `ROUTER__KMS__KEY_ID` and `ROUTER__KMS__REGION` have to be used instead.
This change would allow us to switch to a different KMS service with …
> refactor(kms): share a KMS client for all KMS operations

- crates/router/src/core/payment_methods/cards.rs
Card Fingerprint is not sent by basilisk_hs , so we made the fingerprints optional, while creating payment method entry fingerprint was fetched as a required field
to be tested on prod/sbx
> bugfix: card_fingerprint not sent by basilisk_hs

- crates/drainer/src/metrics.rs
- crates/router/src/routes/metrics.rs
- crates/router/src/scheduler/metrics.rs
- crates/router_env/src/lib.rs
- crates/router_env/src/metrics.rs
This PR refactors the construction of `Counter` and `Histogram` metrics to use macros. Furthermore, these macros have been added to the `router_env` crate, since it anyway re-exports types from the `opentelemetry` crate.
This would reduce a lot of repetitive code involved with the construction of metrics.
N/A
> refactor(metrics): use macros for constructing counter and histogram metrics

- docker-compose.yml
"hyperswitch-server-init" container doesn't requires port config
"hyperswitch-server-init" and "hyperswitch-server" containers are trying to run in the same port, due to which "hyperswitch-server" is not getting started. However we don't need to provide port for "hyperswitch-server-init" as it is only for build.
Running docker in local machine
> fix(docker-compose): remove port for hyperswitch-server-init in docker-compose.yml

- Cargo.lock
- crates/storage_models/src/connector_response.rs
- crates/storage_models/src/payment_attempt.rs
- crates/storage_models/src/payment_intent.rs
- crates/storage_models/src/process_tracker.rs
- crates/storage_models/src/refund.rs
- Adding serialization for primitive date time in storage models
```
Serialized format without the custom_serde
"created_at": [
2023,
75,
13,
31,
38,
571010000
],
```
- We are serializing these structs throughout the code, the updated serialization format should help us
> fix(storage): add serialization for primitivedatetime for diesel structs

- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/adyen.rs
- crates/router/tests/connectors/airwallex.rs
- crates/router/tests/connectors/utils.rs
- loadtest/config/Development.toml
- scripts/add_connector.sh
1. Adding support to provide meta_data for capture and void request also
2. Bug fixes in add_connector script
Previously when a detail from payment authorize response is needed in any of the payment flow we only add it in the `connector_meta` of payment_attempt table, but it was only used in PaymentSync, now we are enabling the Capture and Void flows to make use of connector_meta from payment_attempt. 
Ran basic sanity cases locally
> feat(connector): Add support to provide connector_payment_meta for capture and void request

- CHANGELOG.md
* **deps:**  update deps (#734) (16bc886c)
* **merchant_account:**  remove `api_key` field (#713) (230fcdd4)
* **config:**  move connector base URLs under the `[connectors]` table (#723) (df8c8b5a)
*  address Rust 1.68 clippy lints (#728) (1ffabb40)
* **release:**  specify `fetch-depth` for code checkout and use official Docker GitHub actions (#722) (c451368f)
*  Update naming conventions and added examples (#709) (98415193)
* **openapi:**  document path parameters for API keys endpoints (#702) (9062dc80)
* **connector:**
*  [Mollie]: add authorize, void, refund, psync, rsync support for mollie connector (#740) (168fa32)
*  [worldline] add webhook support for connector (#721) (13a8ce8e)
*  [Trustpay] add authorize (cards 3ds, no3ds and bank redirects), refund, psync, rsync (#717) …
> release: Update CHANGELOG for release v0.5.0

- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/payments/helpers.rs
If there is no client secret in payment_intent then it has expired, so if we receive a client secret in request and there is no client secret in payment intent then the client secret provided has expired.
Closes #756 
For the client secret to be delete on failed payment #724 PR needs to be merged
- Create a successful payment
- Call payment_method list which fails saying client secret is invalid
> feat(pm_list): handle client secret check

- crates/router/src/core/payment_methods/vault.rs
Response of temp card delete api is sent as a plaintext instead of jwe encrypted payload
Do a confirm call, card from basilisk-v3 should be deleted and response is parsed successfully in router
> fix: process delete response from basilisk-v3 as plaintext instead of JWE

- crates/router/src/connector/airwallex.rs
- crates/router/src/connector/airwallex/transformers.rs
Change the `pretask` in the `Authorize` flow to `InitPayment` which is currently implemented via `SessionToken`.
To initiate a payment in Airwallex's Server we need to first call their `create` API endpoint.
This was implemented using `SessionToken` flow in the code which is not correct as it does not involve any session token, But is a `InitPayment` flow which call the connector and records the basic payment details before authorise call or actual payment call is made to their servers.
All the unit tests for airwallex passed, the `refunds` test were `ignored` as they are not supported by the connector.
Also manual testing for the basic cases is done using postman.
> fix(connector): [Airwallex] Change Session Token to Init Payment

- crates/api_models/src/admin.rs
- crates/api_models/src/enums.rs
- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
This PR makes the `accepted_currencies` and `accepted_countries` field types in `MCA` as enums. Earlier, we had an explicit tagged data structure where the tag itself was a `String` so it could be anything. This change rectifies this issue by converting the types from explicitly tagged structs to serde tagged enums.
None
Using serde tagged enums allows better expression of data types with `variants`.
> refactor(api_models): enhance accepted countries/currencies types

- Cargo.lock
- config/config.example.toml
- crates/drainer/Cargo.toml
- crates/drainer/src/connection.rs
- crates/drainer/src/services.rs
- crates/drainer/src/settings.rs
- crates/router/src/configs/defaults.rs
- crates/router/src/configs/settings.rs
- crates/router/src/configs/validations.rs
- crates/router/src/connection.rs
- crates/router/src/services.rs
This PR enables the use of KMS encrypted database passwords for the `router` and `drainer` crates when the `kms` feature is enabled.
I prefer being explicit that a variable expects a KMS-encryted value, so I use `kms_encrypted_password` and KMS decrypt it to obtain the password when the `kms` feature is enabled, and use the `password` config value directly whenever the `kms` feature is disabled. Let me know if it would be preferable to use the `password` config value in both scenarios.
When `kms` feature is enabled, the `ROUTER__MASTER_DATABASE__PASSWORD`, `ROUTER__REPLICA_DATABASE__PASSWORD` and `DRAINER__MASTER_DATABASE__PASSWORD` environment variables should now be replaced with `ROUTER__MASTER_DATABASE__KMS_ENCRYPTED_PASSWORD`, `ROUTER__REPLICA_DATABASE__KMS_ENCRYPTED_PASSWORD` and …
> refactor(drainer, router): KMS decrypt database password when `kms` feature is enabled

- crates/api_models/Cargo.toml
- crates/api_models/src/lib.rs
- crates/api_models/src/webhooks.rs
- crates/router/Cargo.toml
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/trustpay.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/types/api/webhooks.rs
This PR puts the `errors` module in `api_models` behind a feature flag and makes actix-web and related dependencies optional.
None
Required to make async/tokio related features in `api_models` opt-in.
cargo build
> deps(api_models): put the errors module behind a feature flag

- crates/storage_models/src/cards_info.rs
- crates/storage_models/src/schema.rs
There are some columns in `cards_info` table which will be used and updated by the crawlers. These columns are added in the migration. But when migrations are run, the columns are added to `schema.rs`. Since these fields are not in the `CardInfo` struct in `storage_models` the code will not compile. This PR adds those columns to the struct.
Make the code compile.
> fix(cads_info): add extra columns to cards_info struct

- connector-template/mod.rs
- connector-template/transformers.rs
- crates/router/src/connector/aci.rs
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/airwallex.rs
- crates/router/src/connector/applepay.rs
- crates/router/src/connector/authorizedotnet.rs
- crates/router/src/connector/bambora.rs
- crates/router/src/connector/bluesnap.rs
- crates/router/src/connector/braintree.rs
- crates/router/src/connector/checkout.rs
- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/dlocal.rs
- crates/router/src/connector/fiserv.rs
- crates/router/src/connector/globalpay.rs
- crates/router/src/connector/klarna.rs
- crates/router/src/connector/mollie.rs
- crates/router/src/connector/multisafepay.rs
- crates/router/src/connector/nuvei.rs
- crates/router/src/connector/payu.rs
- crates/router/src/connector/rapyd.rs
- crates/router/src/connector/shift4.rs
- crates/router/src/connector/stripe.rs
- crates/router/src/connector/trustpay.rs
- crates/router/src/connector/worldline.rs
- crates/router/src/connector/worldpay.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/lib.rs
- crates/router/src/services/api/request.rs
This PR adds a `RequestBuilder` method to attach default request headers, for use with connector API requests. 
This should make it easy for us to update default request headers on a later date, should there be such a requirement.
N/A
---
I'll be including the commands I ran for performing the search-replace in connector integration code, for reference:
(This uses [`fd`](https://github.com/sharkdp/fd) and GNU `sed`, available as `gsed` on MacOS when installed through homebrew.)
1. Prepend `.headers()` calls with `attach_default_headers()` calls and run formatter:
```shell
$ fd -t f -e rs . crates/router/src/connector -X gsed -i 's/\.headers(/.attach_default_headers().headers(/g'
$ cargo +nightly fmt
```
2. Remove any duplicate `attach_default_headers()` calls:
```shell
$ fd -t f -e rs . …
```
> feat(request): add `RequestBuilder` method to attach default request headers

- CHANGELOG.md
* **request:**  add `RequestBuilder` method to attach default request headers (#826) (6f61f830)
* **middleware:**  add middleware to attach default response headers (#824) (6d7b11a0)
* **core:**  added multiple payment_attempt support for payment_intent (#439) (35d3e277)
* **router:**  added incoming dispute webhooks flow (#769) (a733eafb)
* **cards_info:**  add extra columns to cards_info struct (#813) (442bed0f)
* **connector:**  [Mollie] remove unsupported implementation of Void flow from mollie connector (#808) (eee8304b)
* **common_utils:**  put the signals module behind a feature flag (#814) (fb4ec431)
* **core:**  replace string with enum for country (#735) (e18bfb2a)
* **api_models:**  put the errors module behind a feature flag (#815) (f14f87a1)
* **storage_models:**  delete …
> Changelog for release v0.5.4

- config/config.example.toml
- crates/router/src/configs/defaults.rs
- crates/router/src/configs/settings.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/core/payment_methods/vault.rs
- crates/router/src/services/encryption.rs
Add locker sign keyid in environment for locker.
Added default value for locker_signing_key_id as 1.
Use `ROUTER__LOCKER__LOCKER_SIGNING_KEY_ID` to change the value.
Previously the locker sign keyid was hard coded in the application. 
This can only be tested in environment.
> fix: Add locker sign keyid in env

- Cargo.lock
- crates/common_utils/Cargo.toml
- crates/common_utils/src/ext_traits.rs
- crates/common_utils/src/lib.rs
- crates/redis_interface/Cargo.toml
- crates/router/Cargo.toml
This PR puts the `AsyncExt` trait and certain async functions in the `common_utils` crate behind a feature flag.
None
Required to make the `api_models` crate free of any async-relate dependencies.
cargo build + cargo hack
> deps(common_utils): put the async ext trait behind a feature

- CHANGELOG.md
* **api_models:**  derive `strum::Display` for `RefundStatus` (#846) (4524d4f5)
*  allow (de)serializing countries to/from alpha-2, alpha-3 and numeric country codes (#836) (899767cf)
* **connector:**  add authorize, capture, void, psync, refund, rsync for PayPal connector (#747) (36049c13)
*  Add locker sign keyid in env (#844) (70dff140)
* **common_utils:**  put the async ext trait behind a feature (#835) (de29eb68)
*  update ci workflows for common_enums crate (#843) (45111337)
* **scheduler:**  remove scheduler options & adding graceful shutdown to producer (#840) (11df8436)
* **router:**  refactor amount in PaymentsCaptureData from Option<i64> to i64 (#821) (b8bcba4e)
> Changelog for release v0.5.5

- Cargo.lock
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/core/refunds.rs
- crates/router/src/db/payment_attempt.rs
- crates/router/src/scheduler/workflows/payment_sync.rs
- crates/router/src/types/storage/payment_attempt.rs
- crates/storage_models/src/payment_attempt.rs
- crates/storage_models/src/schema.rs
- migrations/2023-04-12-075449_separate_payment_attempt_algorithm_col/down.sql
- migrations/2023-04-12-075449_separate_payment_attempt_algorithm_col/up.sql
This PR updates the payment attempt db table and separates out the `straight_through_algorithm` field in `connector` into its own column
[Payment Attempt Table up.sql](https://github.com/juspay/hyperswitch/blob/b91ab3bc05d8f8207820141e3d312291d1c52247/migrations/2023-04-12-075449_separate_payment_attempt_algorithm_col/up.sql)
[Payment Attempt Table down.sql](https://github.com/juspay/hyperswitch/blob/b91ab3bc05d8f8207820141e3d312291d1c52247/migrations/2023-04-12-075449_separate_payment_attempt_algorithm_col/down.sql)
Required for graceful DB updates
Local testing (stripe payment)
> feat(router): separate straight through algorithm in separate column in payment attempt

- crates/router/src/core/payments.rs
Remove connector details which is of type Option of ConnectorCallType from get_connector_tokenization_action function, get connector from payment_attempt instead.
Remove usage of ConnectorCallType from get_connector_tokenization_action function
Manual
> refactor(Tokenization): remove ConnectorCallType from tokenization call

- .github/workflows/manual-release.yml
- Cargo.lock
- Dockerfile
This will add support for choosing whether the `backwards_compatibility` feature when creating the manual release.
To support `backwards_compatibility` feature in CI.
> ci(manual_release): add `multiple_mca` feature in ci

- crates/api_models/Cargo.toml
- crates/api_models/src/admin.rs
- crates/router/Cargo.toml
- crates/router/src/core/admin.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/openapi.rs
- crates/router/src/routes/admin.rs
- crates/router/src/types/api/admin.rs
- crates/router/src/types/transformers.rs
- migrations/2023-04-13-094917_change_primary_business_type/down.sql
- migrations/2023-04-13-094917_change_primary_business_type/up.sql
This will use default values if not passed in the request if feature `backwards_compatibality` is enabled. If not then the additional fields will be mandatory.
To support backwards compatibality
- Run the application with `backwards_compatible` feature
- Create a merchant account without business details -> autopopulated
- Create a merchant connector account without business details -> autopopulated
- Create a payment without business details -> taken from merchant account.
> feat(core): add backwards compatibility for multiple mca

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
Duplicate check is made optional
Duplicate check is made optional
> fix: duplication check fix in basilisk-hs

- crates/router/src/core/errors.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/db/events.rs
- crates/router/src/types/storage/events.rs
- crates/storage_models/src/events.rs
- crates/storage_models/src/query/events.rs
Update the `is_webhook_notified` column in `events` table after an outgoing Webhook notification is successfully triggered.
After triggering Webhook notification, db was not getting updated to record that a successful notification has been delivered to the merchant.
Triggered Webhooks and accordingly based on outgoing Webhook notification, observed the changes in `events` table.
> fix: Update events table after notifying merchant

- crates/router/src/connector/stripe.rs
- crates/router/src/connector/stripe/transformers.rs
For stripe in case of invalid cancellation reason, we should not throw RequestEncodingFailed as it will be returned as InternalServer in our response. Instead validation should happen at connector and connector error should be shown in our response.
> fix(stripe): remove cancel reason validation for stripe

- crates/api_models/src/enums.rs
- crates/api_models/src/payments.rs
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/storage_models/src/enums.rs
Added support for new payment methods for Adyen connector,
**Wallets:** MobilePay, Alipay, WeChat Pay, MB Way
**Bank Redirects:** Bancontact Card, BLIK, Trustly, Online banking Czech Republic, Online banking Finland, Online banking    Poland, Online banking Slovakia
**BNPL:** Paybright, Walley
To provide support for wide variety of payment methods.
Tested manually using hyper switch postman collection.
> Adyen new payment method implementation

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
This PR adds support for `bank_redirects` in payment methods list. The response will be of the form 
```json
{
"payment_method": "bank_debit",
{
"payment_method_type": "sepa",
"bank_names": null,
"bank_debits": {
"stripe",
"adyen"
]
}
},
{
"payment_method_type": "ach",
"bank_names": null,
"bank_debits": {
"adyen"
]
}
}
]
}
```
- Create a payment connector with `sepa` and `ach` enabled.
- Create a payment with confirm set to false
- Call the pm list.
> feat(pm_list): add support for bank debits

- crates/api_models/src/payments.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/transformers.rs
A new field allowed_payment_method_types is introduced in /payments (POST) for limiting a payment intent to specified payment method types. If passed, it will be stored as metadata in payment_intent table and will be used to filter the PaymentMethodTypes during /payment_methods (GET) call.
This feature enables merchant to filter certain payment methods only for a particular payment intent. This helps in cases where the merchants wants to limit the payment methods shown for payment intents based on the requirements.
Eg: limiting PaymentMethods for a particular period / amount
Tested manually.
> feat(router): add support for filtering PaymentMethodTypes at a session

- connector-template/mod.rs
- connector-template/transformers.rs
When `add_connector.sh` is called to generate new connector files `mod.rs` had an unused declaration, removed it. At the time of development, if needed, one can import it directly instead of pre-bloating the stuff.  
`Transformers.rs` straight away failed and threw an error addressing `mismatched types` as it is expecting `bool` while were providing `Result<bool, Error>`.
connector-template/mod.rs
connector-template/transformers.rs
With the changes made, unexpected errors and warnings at the time of generation of connector code is avoided and addressed.
> fix(connector-template): Address unused import and mismatched types in connector-template

- crates/router/src/core/errors/utils.rs
make StorageErrorExt generic on errors so that it can be used on any custom Error.
Compiles
> enhan(errors): make StorageErrorExt generic on errors

- docs/try_local_system.md
This PR updates the links to the Postman collection in the local setup guide with a different Postman collection, to accompany local development. This would ensure that users or developers using the `main` branch to try out HyperSwitch would have a collection in sync with our feature development, while also ensuring that testing of the sandbox environment by the merchants remains unaffected.
This should improve the experience for new users or developers who wish to try out HyperSwitch locally.
N/A
> doc(try_local_system): replace Postman collection links with development collection

- config/prometheus.yaml
- config/tempo.yaml
This PR fixes the Tempo configuration file to match the configuration format expected by Tempo 2.0, and removes a duplicate Prometheus scrape configuration.
Tempo recently released Tempo 2.0 which includes breaking changes in their configuration. Since our Docker Compose file pulled the latest tag of Tempo, the configuration file in our repository would cause the container to exit immediately on startup.
Ran the entire setup with Docker Compose and verified that it works.
> fix(config): fix Tempo config for Tempo 2.0

- .github/workflows/connector-sanity-tests.yml
This PR updates the connector sanity tests workflow to be run on being added to merge queue instead of on PRs being opened/updated.
This would prevent the connector sanity tests from failing on PRs by external contributors because of a missing secret, and hopefully reduce confusion as to why their tests are failing.
This PR _should_ not have the connector sanity tests among the PR checks.
> ci(connector-sanity-tests): run tests on being queued for merge

- Cargo.lock
- config/config.example.toml
- crates/api_models/src/enums.rs
- crates/router/src/connector/applepay.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/types/api.rs
- loadtest/config/development.toml
Rename applepay connector name to apple_pay to support uniformity in dashboard.
Manual
> fix: rename `applepay` connector name to `apple_pay`

- Cargo.lock
- crates/api_models/src/refunds.rs
- crates/router/src/core/refunds.rs
- crates/router/src/routes/refunds.rs
* Changed `refund_list()` function in `crates/router/src/core/refunds.rs`  such that it returns only Ok response with Vec of refunds.
* Added  `size: usize` field to `RefundListResponse` in `crates/api_models/src/refunds.rs` just like in `PaymentListResponse`.
"Get Refund List" would send an error response with status code 400 when no refunds are found.
Fixed it so it returns an empty list with status code 200 like "Get Payment List".
Manual
> fix(refund_list): updated refund list response status code when no refunds found.

- crates/api_models/src/refunds.rs
- crates/router/src/compatibility/stripe/refunds.rs
- crates/router/src/connector/utils.rs
- crates/router/src/core/refunds.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/routes/refunds.rs
This PR performs the following changes:
- Add validation for `connector_refund_id`
- Adds `force_sync` support in `refund_retrieve_core`
This introduces a optional query parameter for refund sync
`?force_sync={bool}`
compiler guided
> fix(refund_sync): add validation for missing `connector_refund_id`

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- crates/drainer/src/env.rs
- crates/drainer/src/errors.rs
- crates/drainer/src/main.rs
- crates/router/src/bin/router.rs
- crates/router/src/bin/scheduler.rs
- crates/router/src/env.rs
- crates/router_env/src/logger/config.rs
- crates/router_env/src/logger/setup.rs
- crates/router_env/tests/logger.rs
- docker-compose.yml
- loadtest/config/development.toml
This PR adds two configuration variables for toggling traces and metrics independently instead of using a single toggle to enable both. In addition, this PR introduces one more configuration variable to ignore errors during traces and metrics setup, if required.
The `log.telemetry.enabled` configuration variable is no longer being used, the `log.telemetry.traces_enabled` and `log.telemetry.metrics_enabled` configuration variables must be used instead for toggling traces and metrics, respectively. In addition, errors during traces or metrics setup can be ignored using the `log.telemetry.ignore_errors` configuration variable.
This would allow us to have metrics and traces independently enabled, as required.
Manually.
> refactor(config): add independent toggles for enabling traces and metrics

- crates/router/src/db/cache.rs
In case of a contract change the old data in redis would cause deserialization error, So remove the old data from redis and insert the new value.
This fixes deserialation error on old data in redis.
Manual
> fix: remove old data while deserialization error from cache

- .github/git-cliff-changelog.toml
- .github/git-cliff-release.toml
- CHANGELOG.md
This PR adds configuration files for [`git-cliff`](https://github.com/orhun/git-cliff) for generating changelogs and release notes. In addition, this PR increases the heading levels for each heading in `CHANGELOG.md` file to align with the changelogs generated by `git-cliff`.
To update the `CHANGELOG.md` file with the unreleased commits, you can run:
```shell
git-cliff --config .github/git-cliff-changelog.toml --unreleased --prepend CHANGELOG.md
```
To generate release notes for a GitHub release with contributor mentions (you'll also need [another tool](https://github.com/SanchithHegde/changelog-gh-usernames) (disclaimer: I built this) to substitute committer emails with their GitHub usernames):
```shell
git-cliff --config .github/git-cliff-release.toml --unreleased | …
```
> chore: add `git-cliff` configs for generating changelogs and release notes

- config/development.toml
- crates/router/src/core/payments.rs
Passing connector_name instead of ConnectorCallType which is only used for routing
> fix: Passing connector_name instead of ConnectorCallType

- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/core/admin.rs
- crates/router/src/core/errors/api_error_response.rs
This PR adds the connector_label to the message of the DuplicateMerchantConnectorAccount variant in the ApiErrorResponse enum
This resolves #899,
The connector_label is created by Hyperswitch internally hence it is necessary to send back the connector_label is the error response so that the user has an idea of what the connector_label is.
> refactor(router): add the `connector_label` field to `DuplicateMerchantConnectorAccount` error message

- crates/common_utils/src/pii.rs
This PR does a manual implementation of the `Queryable` trait on the `Email` pii newtype.
None
The `Row` associated type needs to be set to `Self` for newtypes to be compatible with our current manner of using them. deriving `Queryable` sets the `Row` associated type to the newtype's inner type.
> fix(common_utils): manually implement diesel queryable for email newtype

- crates/router/src/core/payments/transformers.rs
payment_method_data passed empty when mandate_id is not present, it should ideally be emptied only if it is already empty and mandate_id is also not present
Ran sanity tests
> fix(mandate): fix payment_method_data becoming empty when mandate_id is not present

- Cargo.lock
- crates/api_models/src/admin.rs
Usage of an inner enum type for serialization and deserialization of the straight through routing algorithm in the payments request.
None
This PR fixes an infinite recursion bug in deserialization of the straight through routing algorithm in the payments request.
Local testing, test recursion edge case locally.
> fix(router): fix recursion bug in straight through algorithm

- crates/api_models/src/payments.rs
This PR will fix the `camelCase` rename issue that was happening in a nested struct. Involves api contract changes of renaming fields to snake_case
Consistency
> fix(applepay): rename applepay_session_response to lowercase

- .github/workflows/connector-sanity-tests.yml
This PR fixes invalid YAML syntax in the connector sanity tests workflow file.
Fixes CI builds not running due to invalid syntax of the workflow file.
I have the GitHub Actions VS Code extension installed, which previously complained about the invalid syntax when I opened the file. After this change, it no longer complains, so I believe this fixes it.
> ci(connector-sanity-tests): fix invalid YAML syntax

- .github/workflows/connector-sanity-tests.yml
- crates/router/tests/connectors/adyen.rs
- crates/router/tests/connectors/shift4.rs
This PR fixes no tests being run after my derp in #1099.
Ensuring connector integration tests run properly.
Added a temporary trigger for the workflow file to test my changes. The command executed by the runner after this fix is:
`cargo test --package router --test connectors -- aci:: --test-threads=1`
which is the intended behavior.
> ci(connector-sanity-tests): fix no tests being run

- config/development.toml
There was an extra space in config for Connector_customer, so deserialization was not proper and only Bluesnap was in the conneector list
Manual
> fix: connector-customer-id missing bug fix

- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/core/admin.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/payments/helpers.rs
Add `id` field to `MerchantConnectorAccountNotFound`,
Send `connector_label` when possible,
Send `merchant_connector_id` otherwise,
Change `create_payment_connector` function to raise `InternalServerError` instead of `MerchantConnectorAccountNotFound`
Fixes #1053
> refactor(router): add `id` field in `MerchantConnectorAccountNotFound`

- crates/router/src/core/payments/helpers.rs
Previously map error was used, this PR uses change_context.
Compiled
> fix(payments): fix address_insert error propagation in get_address_for_payment_request function

- config/development.toml
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/customers.rs
- crates/router/src/core/payments/flows.rs
- crates/router/src/core/payments/flows/authorize_flow.rs
- crates/router/src/core/payments/flows/verfiy_flow.rs
There was a function called `should_call_connector_create_customer` which was called after constructing the router data. This PR includes the change to move it outside and break if creating the customer is not required.
Remove the space and change this value to
```toml
[connector_customer]
connector_list = "bluesnap,stripe"
```
BUGFIX
Manual, create a payment and customer is also created. Subsequent calls are not made to create customer again
Tested redirect payments too as it was failing previously.
Redirect success url https://www.google.com/?status=requires_capture&payment_intent_client_secret=pay_Rs7BYdDa0XODut0zQwpx&amount=10000
> fix(connector_customer): create connector_customer on requirement basis

- crates/router/src/core/mandate.rs
Consider a scenario where, we are creating a mandate, and there was a failure at the connector side, even in that case the mandate is created.
The bug prominently affects single_use mandate. Where, in the recurring payment, if there was a failure on the connector side, the system still marks the mandate as done
Hackathon
Postman and Manual
> fix(mandate): only trigger mandate procedure on successful connector call

- crates/router/src/connector/checkout/transformers.rs
Error Response had field `type` changed it to `error_type` as checkout sends `error_type` in response.
Manual
Previously it used to be `No error message`, Now error message gets populated.
> fix(connector): fix checkout error response type

- crates/api_models/src/enums.rs
Remove unused attempt status to intent status mapping which is not used.
Compiles
> refactor(api_models): remove unused mapping of attempt status to intent status

- crates/api_models/src/payments.rs
- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/connector/nuvei/transformers.rs
- crates/router/src/connector/utils.rs
Stripe requires 
``` 
"gateway": "stripe"
"stripe:version": "2018-10-31"
"stripe:publishableKey": "YOUR_PUBLIC_STRIPE_KEY"
```
dashboard started sending these fields from front-end but backend is not handling the same, this PR will fix the issue.
Previously it was only
```
"gateway": "assist"
"gatewayMerchantId": "YOUR_GATEWAY_MERCHANT_ID"
```
All connectors requires the googlepay_data in camelcase but we serialize and deserialize it in snake_case, so we initially made serialization in camelcase and deserialization in snake_case previously. Now an issue happened when they stored the gpay token in camelcase in vault and tried retrieving in snake_case, so to avoid this issue we revert back to old mechanism of all snake_case concept. now whatever connector that requires the google token …
> fix(google_pay): allow custom fields in `GpayTokenParameters` for google pay via stripe

- crates/api_models/src/payments.rs
- crates/router/src/connector/bluesnap.rs
- crates/router/src/connector/utils.rs
- crates/router/src/core/payments/flows/session_flow.rs
- Convert the `request.amount` to base denomination based on the currency in GooglePay Session flow `create_gpay_session_token`
- If `auth_type` is give as `three_ds` wallets payments should go through regardless of it.
- GooglePay session token was not converting into base denomination and when an amount is passed in cents it processes in higher denomination like dollars.
- Since Bluesnap 3DS flow has a completely different implementation in Authorize flow, Wallets were getting stuck for payments where `auth_type` is `three_ds`
> fix: Convert GooglePay Session token amount and ignore 3DS for Bluesnap wallets

- .github/workflows/conventional-commit-check.yml
This PR fixes a bug with the commit message check workflow not run on being added to the merge queue. In addition, it specifies the cache key for better caching, and updates the permissions for the token to allow write access to project entries.
Since this is a required check for a PR to be merged to the `main` branch, this is holding off PRs that have been added to the merge queue, from being merged.
N/A.
> ci(conventional-commit-check): run checks on being added to queue

- Cargo.lock
- crates/api_models/Cargo.toml
- crates/api_models/src/errors/types.rs
- crates/router/Cargo.toml
- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/compatibility/wrap.rs
- crates/router/src/core/errors.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/services/api.rs
This change provides a feature-gated functionality for exporting the `stacktrace` in the API response, for easier debugging and faster RCAs
This change only affects the outbound error response, adding a optional field `stacktrace` which is only provided when the specific feature is enabled.
via. postman
> feat(error): add feature-gated stacktrace to error received from API

- Cargo.lock
- crates/router/src/connector/authorizedotnet/transformers.rs
- crates/router/src/core/payments.rs
This change fixes the case where connectors require payment data, when network transaction id is passed. In case of mandate id, no payment data is provided.
Closes #1139.
Tested for `stripe` and `authorizedotnet` via postman (manually)
> fix(mandate): allow card details to be provided in case of network transaction id

- crates/api_models/src/enums.rs
- crates/router/Cargo.toml
- crates/router/src/connector/dummyconnector.rs
- crates/router/src/core/payments/flows.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/dummyconnector.rs
Add multiple dummy connectors and enable dummy connector by default
Closes #726.
> feat(connector): add multiple dummy connectors and enable them

- crates/router/src/connector/authorizedotnet.rs
- crates/router/src/connector/authorizedotnet/transformers.rs
Payments and refund Webhook Flow for Authorizedotnet
Payments and refund webhook flow Authorizedotnet
Outgoing payment webhook 
Payment retrieve for same payment
> feat(connector): [Authorizedotnet] implement payment and refund webhook flow for Authorizedotnet 

- crates/common_utils/src/pii.rs
Fixed the email deserialization.
> fix(utils): fix bug in email validation

- crates/api_models/src/webhooks.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/refunds/types.rs
- crates/router/src/compatibility/stripe/webhooks.rs
- crates/router/src/core/errors.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/services/api.rs
Outgoing webhook api call wasn't using the proxy to call the external endpoint, so was failing on SBX due to outbound proxy whitelisting. Used the generic `send_request` to send outgoing webhook which uses proxy internally.
Outgoing webhook to merchant
> fix(router): outgoing webhook api call

- crates/router/src/core/payment_methods/vault.rs
In case tokenized entry is already present don't throw Unique violation error
> fix: handle unique constraint violation error gracefully

- Cargo.lock
- crates/api_models/src/ephemeral_key.rs
- crates/api_models/src/lib.rs
- crates/api_models/src/payments.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/operations/payment_cancel.rs
- crates/router/src/core/payments/operations/payment_capture.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/operations/payment_start.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payments/operations/payment_update.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/openapi.rs
- crates/router/src/types/api.rs
- crates/router/src/types/api/ephemeral_key.rs
- crates/storage_models/src/ephemeral_key.rs
Added `ephemeral_key` field to `payment_create` response(only payment create).
Through this change, merchant need not do a separate api call for ephemeral key after payment creation.
manual
This is how payment create response would look after this change is merged.
Note `ephemeral_field` at the end.
```
{
"payment_id": "pay_DUrBhwXG03XovxSB6Tra",
"merchant_id": "merchant_1682859385",
"status": "requires_confirmation",
"amount": 6969,
"amount_capturable": null,
"connector": null,
"client_secret": "pay_DUrBhwXG03XovxSB6Tra_secret_4sq0ABEu4FpVvO2pxyc6",
"created": "2023-05-11T14:39:11.331Z",
"customer_id": "cus_7mb0kUzEAzmMPzpkWiFh",
"refunds": null,
"disputes": null,
"mandate_id": null, …
```
> fix(core): add ephemeral key to payment_create response when customer_id is mentioned

- .github/workflows/conventional-commit-check.yml
This PR fixes the PR title check not being run on PRs due to an incorrect event type check.
N/A
N/A
> ci(conventional-commit-check): fix checks being skipped for PRs

- crates/router/src/core/admin.rs
create a hash key if it is not present, which will be used by merchant to verify if the response is coming from hyperswitch
Hash key generated screenshots
> refactor(core): generate response hash key if not specified in create merchant account request

- crates/router/tests/connectors/stripe_ui.rs
For the UI redirection tests, the functions are triggering to the base url containing api-keys.Api-keys in the base url is not required.
Enable UI redirection tests
Requirements:
1. Mozilla firefox browser
2. geckodriver
How to test UI redirection :
1. Export merchant api-key using this :
`export HS_API_KEY={api_key}`
2. For Google Pay payment test and mandate payment test, 
`export GMAIL_EMAIL=hypers.gpaytest GMAIL_PASS={password_for_gpay} PYPL_EMAIL={paypal_email} PYPL_PASS={paypal_password}`
3. Run this :  `function orca-test() {
cargo test --package router --test connectors -- $1 --test-threads=1
}`
4. Start Hyperswitch server
5. Open geckodriver
6.  Run this command for UI redirection tests : `cargo test --package router --test connectors -- stripe_ui --test-threads=1 ` in other …
> test(connector): [Stripe] Fix redirection UI tests

- crates/router/src/core/payments/helpers.rs
If we have hyperswitch_token as well as pmd, we get pmd against that hyperswitch token from basilisk.
We used to update the pmd again against that token w.r.t wallets and bank transfers, as both the data will be same, we get error.
Remove duplicate storage in locker
Manual
> fix: remove multiple call to locker

- Cargo.lock
- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
This builds over #1188 , due to a change of requirement, the customer side mandate information must not only indicate that it's a mandate payment but also the information about the mandate.
compiler guided
> fix(list): add mandate type in payment_method_list

- crates/router/src/core/payments/operations/payment_create.rs
Populate `meta_data` in `PaymentIntent` which in turn populate in `PaymentsAuthorizeRouterData`
The data inside metadata that was sent along with Payments Request was unable to be fetched while building the request for the connector.
Tested the same for Zen and Klarna Via Adyen
> fix: populate meta_data in payment_intent

- Cargo.lock
- crates/router/src/core/payments.rs
In should_add_task_to_process_tracker, if connector is missing then we are raising `MissingRequiredField` error. This will fail in some flows where connector is not available. This PR includes a fix for that. 
This bug was introduced in #905 
Manual
> fix(core): remove `missing_required_field_error` being thrown in `should_add_task_to_process_tracker` function

- crates/api_models/src/payments.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/setup_intents/types.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/openapi.rs
- crates/router/src/types/api/payments.rs
Earlier NextAction was struct and had only redirect_to_url as optional field but after bank transfer, there is next action which is not redirection to url, so NextAction struct is converted to enum with internally tagged with type. Now, this enum can handle both redirection kind of next action as well as just displaying the information kind of next action.
To support both redirection and information display in next action
For redirect to url:
For bank transfer information:
> refactor:  make NextAction as enum 

- crates/api_models/src/enums.rs
- crates/api_models/src/payments.rs
- crates/router/src/core/payments.rs
Made changes in `core/payments.rs` to include a field named `routing_parameters` in Metadata Struct.
This change is necessary for VAS in order to include routing using metadata which can be arbitrary key value pair.
There is no requirement for test moreover it is `Option` so provides for backward compat.
> Refactor(router): router_parameters field inclusion

- crates/router/src/configs.rs
- crates/router/src/configs/kms.rs
- crates/router/src/configs/settings.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/core/payment_methods/vault.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/routes/app.rs
This PR introduces changes to changes to KMS decryption:
- It decrypts and stores the KMS keys for vault and locker in a `AppState`.
- It performs concurrent decryption while startup for those KMS keys
- It also supports, retry mechanism for decryption for failures
Improve the performance
compiler guided
> feat(kms): reduce redundant kms calls

- Cargo.lock
- crates/external_services/src/kms.rs
- crates/external_services/src/lib.rs
This PR adds metrics that support to get KMS decryption time as a metric in Prometheus.
Improving visibility to the overall performance 
Compiler Guided
> fix(kms): add metrics to external_services kms

- Cargo.lock
- crates/router/src/services/api.rs
This PR adds support for logging request payload in `server_wrap`
> feat(logging): logging the request payload during `BeginRequest`

- crates/router/src/cache.rs
- crates/router/src/db/merchant_account.rs
- crates/router/src/services.rs
Fix invalidation of in memory cache for accounts cache.
Fixes accounts cache
Manual
> fix: invalidation of in-memory cache

- crates/api_models/src/payments.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/klarna/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/connector/zen/transformers.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/db/payment_intent.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/zen.rs
- crates/storage_models/src/payment_intent.rs
- crates/storage_models/src/schema.rs
- migrations/2023-05-12-103127_payment_intent.sql/down.sql
- migrations/2023-05-12-103127_payment_intent.sql/up.sql
Order_details was changed from an object to a vector in payment-create....reverting it back to an object .
removing field meta_data from payment_intent table.
This PR reverts #964.
Payment_create request gave error when order_details was an array,success with obejct .
> revert(order_details): revert back `order_details` to be an object, and removing `meta_data` from `PaymentIntent`

- crates/router/src/core/errors.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/lib.rs
Add signature to outgoing webhooks from hyperswitch by hashing it contents, so that the webhook can be verified on the merchants end.
Implementation details: 
-> Key used here is generated from the CSPRNG (generate_cryptographically_secure_random_string())
-> Hashing algorithm used is Sha512
-> The outgoing webhook contents is hashed using this key and the signature is sent in the header
I tested this change manually
Out going webhook to merchant
signature verification
> feat(core): add signature to outgoing webhooks 

- crates/redis_interface/Cargo.toml
- crates/redis_interface/src/lib.rs
- crates/router/src/services.rs
use `SubscriberClient` for subscriber instead of `RedisClient`.
`SubscriberClient` from `fred` has extensive features on top of `RedisClient` which spawns a tokio task which will automatically resubscribe to the channel in case if it closes for any reason.
Manual
> feat: use subscriber client for subscription in pubsub

- Cargo.lock
- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/connector/checkout/transformers.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/core/webhooks/utils.rs
This PR modifies the webhooks core flows to use `ApiErrorResponse` to communicate errors for seamless HTTP Status Code Mapping.
Additionally, we define a mapping between the `ConnectorError` and `ApiErrorResponse` to enable a mapping between these errors as well for the webhooks core flow
None
The Webhooks core flow used to send 5xx status codes even for errors where 4xx was more appropriate due to error consolidation using `error_stack`, with this PR we remove this consolidation and allow the error propagated to be more specific to the issue.
Successful webhook
Unsuccessful webhook (Invalid ID -> Payment Not Found -> 404)
Unsuccessful webhook (Invalid body -> 400)
Unprocessed successful webhook (Unsupported event type -> 200)
> fix(router/webhooks): use api error response for returning errors from webhooks core

- Cargo.lock
- crates/api_models/src/payments.rs
- crates/router/src/connector/airwallex/transformers.rs
- crates/router/src/connector/bambora/transformers.rs
- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/operations/payment_cancel.rs
- crates/router/src/core/payments/operations/payment_capture.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/operations/payment_start.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payments/operations/payment_update.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
add redirect_response field to CompleteAuthorizeData instead of payload 
Previously we were sending only payload in `CompleteAuthorizedData` , for connector `authorizedotnet` query_params are required. In this PR `redirect_response` is added in `CompleteAuthorizedData` which contains both query_params and payload. 
Bluesnap goes through complete authorize flow for 3ds payment ,which uses payload in redirect response .So ,i have tested this connector in postman. 
list
> refactor(core): Add 'redirect_response' field to CompleteAuthorizeData

- Cargo.lock
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/operations/payment_start.rs
- crates/router/src/core/payments/operations/payment_update.rs
This Pr will not check for the `customer_id` present in the confirm request during mandates request.
- Create a mandate payment, with confirm as false
- confirm the mandate payment, without customer id
> fix: customer id is not mandatory during confirm

- crates/masking/tests/basic.rs
- crates/router/src/connector/nexinets.rs
This PR addresses a clippy lint stabilized in Rust 1.70.
N/A
N/A
> chore: address Rust 1.70 clippy lints

- Cargo.lock
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/airwallex.rs
- crates/router/src/connector/authorizedotnet.rs
- crates/router/src/connector/bluesnap.rs
- crates/router/src/connector/braintree.rs
- crates/router/src/connector/checkout.rs
- crates/router/src/connector/coinbase.rs
- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/fiserv.rs
- crates/router/src/connector/globalpay.rs
- crates/router/src/connector/iatapay.rs
- crates/router/src/connector/nuvei.rs
- crates/router/src/connector/opennode.rs
- crates/router/src/connector/rapyd.rs
- crates/router/src/connector/stripe.rs
- crates/router/src/connector/trustpay.rs
- crates/router/src/connector/utils.rs
- crates/router/src/connector/worldline.rs
- crates/router/src/connector/worldpay.rs
- crates/router/src/connector/zen.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/core/webhooks/utils.rs
This PR is intended to perform two bugfixes :-
- Correction in the error mapping from webhook connector errors to API error response. This is done specifically for webhook event type mapping failure cases.
- Making source verification merchant secret retrieval optional for all connectors. This can be optional because some webhook consumption flows can go for a fallback when source verification has failed.
None
This set of bug fixes is aimed at eliminating redundant 5xx API errors, instead making the API errors more sensitive to the actual context in which the error occurred.
> fix(router/webhooks): correct webhook error mapping and make source verification optional for all connectors

- crates/router/src/core/payment_methods/cards.rs
We used to have locker_id as a namespacing identifier for merchants, however this is no more used for BasiliskLocker. This will remove asserting for locker_id in case of BasiliskLocker.
> fix(locker): remove unnecessary assertions for locker_id on BasiliskLocker when saving cards

- Cargo.lock
- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/webhooks/utils.rs
This PR maps the Webhook error for Event Type Not found to HTTP status code `422` which is more appropriate.
None
Ensuring better error mapping
> fix(router/webhooks): map webhook event type not found errors to 422

- crates/router/src/db/refund.rs
- crates/storage_models/src/refund.rs
The main motivation is to have MockDb stubs, help to void mocking, and invocation of external database api's.
For more information check https://github.com/juspay/hyperswitch/issues/172
Fixes #1276
> feat(db): implement `RefundInterface` for `MockDb`

- Cargo.lock
- Cargo.toml
- config/docker_compose.toml
- crates/router_env/Cargo.toml
- crates/router_env/src/logger/setup.rs
- docker-compose.yml
opentelemetry sdk currently isn't exporting traces to otel collector. This now works after changing to batch exporter which is better for performance reasons. Pipeline is now changed to batch exporter with the timeout of 1 second.
Traces are vital to debug failures and to diagnose latency issues. Traces aren't getting exported/reflecting in Grafana/Tempo. This change fixes the issue and traces are available in Grafana.
- set `log.telemetry.traces_enabled = true` in `config/docker_compose.toml`
- start docker compose `docker compose -f docker-compose.yml -p hyperswitch-tempo --profile monitoring up`
- after the hyperswitch server is up, hit the endpoints and verify the traces in Grafana/Tempo
> fix(logging): fix traces export through opentelemetry

- crates/router/src/openapi.rs
- openapi/openapi_spec.json
This PR will add the `ApplepayRedirectionData` struct that was added recently to the api models, to openapi file.
Pass the CI checks
Generate the openapi file and ensure that there are no errors.
> docs: add `ApplePayRedirectionData` to OpenAPI schema

- crates/router/src/connector/bluesnap/transformers.rs
Bluesnap required fraudSessionId to be passed in the payment request for FRMS DDC verification. This can be handled by passing hyper switch payment_id in the blue snap payment request. 
Manual Testing in postman
> feat(router): [Bluesnap] add kount frms session_id support for bluesnap connector

- crates/router/src/connector/bitpay.rs
- crates/router/src/connector/bitpay/transformers.rs
- crates/router/src/connector/coinbase.rs
- crates/router/src/connector/coinbase/transformers.rs
- crates/router/src/connector/opennode.rs
- crates/router/src/connector/opennode/transformers.rs
Handle error response correctly for all crypto connectors.
> fix(connector): [coinbase][opennode][bitpay] handle error response

- crates/router/src/connector/trustpay/transformers.rs
- crates/router/src/connector/utils.rs
Email should be passed as a mandatory field and user-agent should be passed as default value if not passed in TrustPay card payment request 
Manual Testing & verified trustpay card payment request
> fix(router): [Trustpay] fix email & user-agent information as mandatory fields in trustpay card payment request

- crates/router/src/services/api.rs
This PR logs and verifies if the payload and the response is logged in the `server_wrap`.
The payload provided by the api is already logged in the beginning of the request, this PR only adds logging the the response of the core function. As the function is generic the masking information is preserved
compiler guided testing
> feat(response-log): add logging to the response

- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/db/payment_attempt.rs
- crates/router/src/services/api.rs
- crates/storage_models/src/payment_attempt.rs
- crates/storage_models/src/schema.rs
- migrations/2023-06-14-105035_add_reason_in_payment_attempt/down.sql
- migrations/2023-06-14-105035_add_reason_in_payment_attempt/up.sql
Send the 200 response with status as `processing`, populating error_code and error_message when we receive 5xx status codes from connector.
DB payment_attempt for 5xx code from connector
Payments response for 5xx code from connector
> refactor(router): send 200 response for 5xx status codes received from connector

- crates/api_models/src/payments.rs
- crates/router/src/connector/aci/transformers.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
Payment method data enums should follow naming conventions, like if it is Redirect flow then name should be "{Payment_Method_Name}Redirect"
**Updated api contract**
AliPay Redirect:
`"payment_method_data": {
"wallet": {
"ali_pay_redirect": {}
}
}
`
WechatPay Redirect:
`"payment_method_data": {
"wallet": {
"we_chat_pay_redirect": {}
}
}
`
MBWay Redirect:
`"payment_method_data": {
"wallet": {
"mb_way_redirect": {
"telephone_number":"+351213822199"
}
}
}
`
Walley Redirect:
`"payment_method_data": {
"pay_later": {
"walley_redirect": {}
}
}
`
PayBright Redirect:
`"payment_method_data": {
"pay_later": {
"pay_bright_redirect": {}
}
}
`
Postman:
> refactor(api_models): follow naming convention for wallets & paylater payment method data enums

- crates/router/src/connector/trustpay/transformers.rs
Payment id will be passed as reference in trustpay. This is a temporary solution. Ideally attempt id needs to be passed for webhooks to be handled. issue created here - #1443 
Tested
> fix(connector): use reference as payment_id in trustpay

- crates/router/src/core/payments/operations/payment_response.rs
2xx error responses were mapped to processing, fixed it by adding check with 5xx to change status to processing in other cases to failure. 
> fix(router): fix payment status updation for 2xx error responses

- .github/workflows/postman-collection-runner.yml
Added github action to trigger the collection manually
> ci(postman-collection-runner): add `workflow_dispatch` trigger and fix failing CI runs

- crates/api_models/src/payments.rs
- crates/router/src/core/admin.rs
This PR will remove the parsing check for metadata that was added in #1385. 
The reason the parsing check was added ( in addition to certificate validation ), is to ensure that mca cannot be created with malformed data. 
But in https://github.com/juspay/hyperswitch/pull/1390, the connector is expecting the json value to be in specific format. This format is checked only in case the payment is made through that connector and payment method. 
I'm currently removing the type checks ( except for certificate validation ) as its not clear as to where this struct is parsed internally in the connector module to different formats. Ideally the types should be declared in `api_models` and the same type should be used in connector module wherever possible. 
Such type checks can be added later once we …
> refactor(mca): use separate struct for connector metadata

- crates/router/src/connector/zen/transformers.rs
Convert the amount to base denomination in order_details
The amount and price along with lineItemsTotal should be aligned and should be in base denomination according to the currency
- [] I added unit tests for my changes where possible
> fix(connector): [Zen] Convert the amount to base denomination in order_details

- crates/storage_models/src/schema.rs
- migrations/2023-06-19-071300_merchant_key_store_shrink_merchant_id/down.sql
- migrations/2023-06-19-071300_merchant_key_store_shrink_merchant_id/up.sql
This PR updates the `merchant_id` column of the `merchant_key_store` table to use `VARCHAR(64)` instead of `VARCHAR(255)`, since we're using `VARCHAR(64)` for `merchant_id` everywhere else.
The migrations are available at [`up.sql`](https://github.com/juspay/hyperswitch/blob/9e62b6ec85dd9583e27f9e817465c94b9ff5e2ad/migrations/2023-06-19-071300_merchant_key_store_shrink_merchant_id/up.sql) and [`down.sql`](https://github.com/juspay/hyperswitch/blob/9e62b6ec85dd9583e27f9e817465c94b9ff5e2ad/migrations/2023-06-19-071300_merchant_key_store_shrink_merchant_id/down.sql).
We're using `VARCHAR(64)` for `merchant_id` everywhere else, so the `merchant_key_store` table can also use the same size.
N/A
> chore(migrations): shrink `merchant_id` column of `merchant_key_store` to 64 characters

- Dockerfile
This PR updates the `Dockerfile` to use `debian:bookworm-slim` as the base image for both the builder and runner stages.
This fixes an issue where the application panics because it fails to load the OpenSSL library. Turns out, this is caused by `rust:slim` using Debian bullseye (11) in the builder stage, while `debian` pulled Debian bookworm (12) for the runner stage.
Built and ran Docker images locally.
> build(docker): use `debian:bookworm-slim` as base image for builder and runner stages

- crates/router/src/connector/shift4/transformers.rs
Fix webhooks for shift4 . Rename webhooks event type to `SCREAMING_SNAKE_CASE`.
> fix(connector): [Shift4] Fix incorrect deserialization of webhook event type

- crates/router/src/core/payments.rs
This PR will move the update trackers outside the conditional block, this is to ensure that even if there is no call to connector, the database is updated ( this was required in pre processing steps ).
Persist the data in pre processing steps.
- Create a payment with missing required field error, ensure that the payment status is not udpated.
- Create applepay trustpay payment, works as expected.
> refactor(core): update trackers for preprocessing steps

- .github/workflows/postman-collection-runner.yml
This PR aims at fixing the scheduling of `postman-collection-runner.yml`. The action is expected to run at 6AM and 6PM everyday with an additional option to run whenever needed manually. I believe, at the time of merge changes on the local branch have made a duplicate of `workflow_dispatch` command which is unexpected and have been fixed.
This PR aims to fix a bug! Killing bugs are a motivation.
A tester cannot be tested. However, tried running the action on my private repo through workflow_dispatch, it worked until it failed without any secrets and collections given to it.
> ci(postman-collection-runner): remove duplicate `workflow_dispatch` trigger

- crates/api_models/src/payments.rs
- crates/router/src/connector/aci/transformers.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/nexinets/transformers.rs
- crates/router/src/connector/nuvei/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/connector/worldline/transformers.rs
- crates/router/src/core/payments/operations/payment_create.rs
This PR will make the bank names as optional in the payment method data. This is required for trustpay as it does not accept any bank names in the payments request. Previously if bank names are not passed, then it would throw 400 bad request with missing required field of bank names, which will no more be the case.
Allow for bank redirect payment method to work for trustpay.
- Create a payment of bank redirect payment with stripe without bank names - should succeed.
```json
{
"payment_method_type": "eps",
"eps": {
"billing_details": {
}
}
}
}
}
```
> refactor: make bank names optional in payment method data

- crates/router/src/connector/trustpay.rs
- crates/router/src/connector/trustpay/transformers.rs
After #1440, we are sending reason as error_message in payments response. Added valid reason for all the error responses. 
> fix(connector): [Trustpay] add reason to all the error responses

- crates/common_utils/src/crypto.rs
- crates/common_utils/src/pii.rs
- crates/router/src/types/api/webhooks.rs
- crates/router/src/types/domain/types.rs
- crates/storage_models/src/encryption.rs
Add secret to encrypted fields so it wont be logged. It will be logged as `*** Encrypted ***`.
Dont log huge encrypted binary data.
> fix(encryption): do not log encrypted binary data

- crates/router/src/core/payments/operations/payment_confirm.rs
This will not allow the payment to be confirmed if the status is `RequiresCustomerAction`.
- Create a payment which will move to `RequiresCustomerAction`.
- Confirm the payment again
> fix: add requires_customer_action status to payment confirm

- crates/router/src/core/payments.rs
If there is a bad request error during confirm, then the payment status is not changed. This will allow the confirm api to be called again with appropriate data. But when it is confirmed again, we get the process tracker duplicate entry, because a tracker has already been inserted in the previous step.
This will allow the payment to be confirmed if there is a bad request error.
- Confirm a payment to get `MissingRequiredField` Error.
- Confirm the payment again with appropriate data.
> fix(process_tracker): log and ignore the duplicate entry error

- crates/router/src/connector/aci.rs
This bug is introduced here https://github.com/juspay/hyperswitch/pull/1467/files#diff-0bad8e9438400c80070c139bf43a0a406827477908db192e40346e598096d3a5
Change the encoder to `url_encode` for cancel and refund requests in aci connector
Unit tests
> fix(connector): [ACI] fix cancel and refund request encoder

- crates/router/src/connector/trustpay.rs
- crates/router/src/connector/trustpay/transformers.rs
…ayErrorResponse object
TrustpayErrorResponse object has errors as a mandatory field but the connector is returning errors fields as an optional field in error response.
Ref Doc: https://doc.trustpay.eu/aapi#tpgw-s2s-response-failed
> fix(connector): [Trustpay] handle errors fields as optional in TrustpayErrorResponse object

- crates/router/src/core/errors/api_error_response.rs
The error message was previously in the format
```json
{
"error": {
"message": "This refund is not possible through Hyperswitch. Please raise the refund through {connector} dashboard",
"code": "HE_03"
}
}
```
Here the connector should have been replaced by the actual connector name. This has been fixed in this PR.
Display the actual connector name.
- Create a payment by klarna connector.
- Create a refund
> fix(errors): use `format!()` for `RefundNotPossibleError`

- crates/storage_models/src/enums.rs
This PR adds a serde rename_all attribute to refund enums (RefundStatus, RefundType)
> refactor: add serde rename_all for refund enums

- crates/router/src/connector/trustpay.rs
Change the encoding of the request body from string of json to url_encoded.
TrustPay requires url_encoded data, in #1467 it got changed to string of json which is fixed in this PR
> fix(connector): [TrustPay] change the request encoding

- crates/router/src/connector/braintree/transformers.rs
`SubmittedForSettlement` in Braintree is set to `Pending` since it `SubmittedForSettlement` changes is a nightly process and takes time to finish the payment. Docs attached below:
- https://developer.paypal.com/braintree/docs/reference/general/statuses#submitted-for-settlement
- https://developer.paypal.com/braintree/docs/reference/general/testing#settlement-status
Only if the payment is successful (Settled) or failed (Declined), a webhook is sent from Braintree's end.
This change is required as the connector returns the payment as succeeded instead of Processing / Pending. This does not allow the user to initiate a refund. Trying to do the same results in an error that states that the payment is still processing. Also, if the payment fails i.e., the payment status changes from …
> fix(connector): [Braintree] Map `SubmittedForSettlement` status to `Pending` instead of `Charged`

- crates/router/src/cache.rs
- crates/router/src/core/cache.rs
- crates/router/src/db/cache.rs
- crates/router/src/services.rs
Publish the keys to redact cache channel in redis instead of using `.remove` directly. Providing a invalidate key will delete all the kinds of cache associated to that key, which are currently configs and accounts cache. This PR will create a pub-sub message to delete the cache on all pods.
This will fix the inconsistent in memory cache across multiple pods
Manual
> fix: invalidate all cache on invalidate cache route

- crates/router/src/connector/cybersource.rs
- crates/router/src/consts.rs
Send error message if cybersource sends 401 error code
It used to send empty error message in case of authentication error
> fix(connector): [Cybersource] Throw proper unauthorised message

- crates/router/src/connector/bluesnap/transformers.rs
Bluesnap requires card holder information for Apple Pay payment method.
Applepay can't be tested in local machine, Will test in sandbox & integration env.
> fix(connector): [Bluesnap] add cardholder info in bluesnap payment request

- crates/api_models/src/payments.rs
- crates/router/src/core/payments/transformers.rs
add `connector_transaction_id` in payments response
Currently, in order to debug/validate the status at the connector, we require the `connector_transaction_id`, which is obtained from the payment_attempt table. However, on production, this process is not feasible. Moreover, for the sake of easier debugging, it would be beneficial to include the connector_transaction_id as part of the payments response
Payments response
> feat(router): add `connector_transaction_id` in payments response

- crates/router_env/src/logger/formatter.rs
Updated macro invocation from the format! to format_args! 
[1293](https://github.com/juspay/hyperswitch/issues/1293)
> perf(logging): remove redundant heap allocation present in the logging framework

- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/connector/utils.rs
- Add `card_holder_info` in the Bluesnap Connector Request
- Add Conversion Check for 2-Digit Expiry Year in Card Data
> fix: add 3ds card_holder_info and 2 digit expiry year

- crates/api_models/src/enums.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/payme.rs
Disabled payme connector through code
To skip sanity tests in the CI pipeline, newly generated connectors should be disabled in code.
Test not required
> chore(connector): [Payme] disable payme connector in code

- crates/api_models/src/enums.rs
- crates/api_models/src/payments.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations.rs
- crates/router/src/core/payments/operations/payment_cancel.rs
- crates/router/src/core/payments/operations/payment_capture.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/operations/payment_start.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payments/operations/payment_update.rs
- crates/router/src/openapi.rs
- crates/router/src/scheduler/metrics.rs
- crates/router/src/types/storage/process_tracker.rs
add requeue for payments and fix duplicate entry error in process tracker for requeued payments
When a payment is requeued after a 4xx from sdk, we are trying to create a new task in process tracker for same payment attempt which is resulting in duplicate entry error
To handle this, SDK to pass requeue flag to denote a requeued payment and we'll reset the task instead of creating a new one
> feat(router): add requeue support for payments and fix duplicate entry error in process tracker for requeued payments

- crates/router/src/db.rs
- crates/router/src/db/configs.rs
- crates/storage_models/src/configs.rs
The main motivation is to have MockDb stubs, help to void mocking, and invocation of external database api's.
For more information check https://github.com/juspay/hyperswitch/issues/172
Fixes https://github.com/juspay/hyperswitch/issues/997.
> feat(db): implement `ConfigInterface` for `MockDb`

- crates/router/src/core/payments/operations/payment_start.rs
This pull request removes the unnecessary call to fetch payment method data in the payments_start operation of the PaymentStart implementation. The payment method data fetch adds additional latency to the payments flow without being required in this particular flow.
Fixes https://github.com/juspay/hyperswitch/issues/1327
> refactor(payments_start): remove redundant call to fetch payment method data

- crates/router/src/compatibility/stripe/setup_intents/types.rs
added straight through routing and udf field mapping to get txn_id and other details in setup_intents
Euler needs txn_id to verify the txns started at euler's end.
Tested locally through postman
> feat(compatibility): add straight through routing and udf mapping in setup intent

- crates/redis_interface/src/commands.rs
…n as we ourselves are setting the key so don't require the set value to be returned
We don't require to return the value that we ourselves are setting hence replacing the true to false.
> refactor(redis_interface): changed the in the get_options value from true to false

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payments/operations/payment_update.rs
add psync task to process tracker after building connector request in payments flow to prevent duplicate entries error in case of 4xx threw from connector flows
we were adding psync task to process tracker for every payment attempt even though we threw 4xx from our side, in these cases if we do confirm again we were getting duplicate entry error from PT because it's the same attempt. To prevent this have moved psync task addition to process tracker after building connector request
Tested locally
task getting added only after building connector request
> refactor(router): add psync task to process tracker after building connector request in payments flow

- crates/router/src/connector/rapyd/transformers.rs
3DS payment status would always remain in requires_customer_action as there was no return url provided in the 3DS request. This pr adds router_return_url in 3DS request.
> fix(connector): [Rapyd] Add router_return_url in 3DS request

- .github/workflows/release-new-version.yml
This PR updates the schedule for the auto release workflow to run every Tuesday, Wednesday and Thursday.
We mostly won't be making any releases on Mondays and Fridays, so yeah.
N/A
> ci(release-new-version): update schedule to run workflow every Tuesday, Wednesday, Thursday

- crates/router/src/lib.rs
This PR fixes a bug where `x-request-id` was not being included in the `access-control-expose-headers` header. The solution is to register the request ID middleware before the CORS middleware.
Bugfix.
Before:
```shell
$ curl -i http://localhost:8080/health
[...]
access-control-expose-headers: via, strict-transport-security
[...]
```
After:
```shell
$ curl -i http://localhost:8080/health
[...]
access-control-expose-headers: x-request-id, via, strict-transport-security
[...]
```
> fix(middleware): inlcude `x-request-id` header in `access-control-expose-headers` header value

- crates/router/src/core/payments.rs
The function call responsible for deleting card details from payments_operations_core() has been removed in this PR. This modification ensures that the redundant deletion of already deleted card details no longer occurs, preventing the unnecessary error from being triggered.
Previously, there was a function call within payments_operations_core() that deleted card details stored in the Basilisk Locker V3. However, it was discovered that the process tracker was also attempting to delete the same card details, resulting in an unnecessary error when trying to delete an already deleted card.
> fix(locker): remove delete_locker_payment_method_by_lookup_key from payments_operation_core

- crates/router/src/core/errors.rs
Map not found error from StorageError properly in is_db_not_found.
Throws 404 for properly if record not found in DB.
On multiple deletion on API key.
> fix: map not found error properly in db_not found

- crates/router/src/db/api_keys.rs
- crates/router/src/db/dispute.rs
- crates/router/src/db/events.rs
- crates/router/tests/connectors/selenium.rs
This PR addresses a clippy lint stabilized in Rust 1.71.
N/A
N/A
> chore: address Rust 1.71 clippy lints

- .github/workflows/connector-ui-sanity-tests.yml
- crates/router/tests/connectors/trustpay_3ds_ui.rs
Run UI tests only on merge queue so that breaking-PRs will get kicked on failure
To make UI tests mandatory for all PRs
> fix(ui-test): Run UI tests only on merge-queue

- .github/scripts/run_ui_tests.sh
- .github/workflows/connector-ui-sanity-tests.yml
UI tests running forever when build is failing, so making it to run maximum 15mins
> fix(ci): Run UI tests only for 15mins max in case of build failure

- crates/diesel_models/src/payment_intent.rs
While updating the payment_intent's active attempt id in automatic retries we need to update attempt_count too. To support that have added attempt_count field in attempt update record of payment_intent
Compiler guided
> feat(router): add attempt_count field in attempt update record of payment_intent

- crates/router/src/connector/multisafepay/transformers.rs
De-serialization of connector response raised an error as the status void was undefined for Multisafepay 
Declined Payment
>  fix(connector): [Multisafepay] Fix bug in Paypal payment decline and cancel

- config/docker_compose.toml
- docker-compose.yml
- Adding a redis-standalone state to docker compose
- turning off the cluster mode by default
- The application will connect to the right instance based on whether cluster mode was enabled/disabled
- Currently docker runs on redis cluster mode to better test any cluster specific code written
- However the cluster mode is a bit finicky in terms of cluster losing state & being in an unavailable state
- local runs
> fix(build): add a standalone Redis mode in docker-compose installation

- crates/api_models/src/admin.rs
- crates/diesel_models/src/merchant_account.rs
- crates/diesel_models/src/schema.rs
- crates/router/src/configs/defaults.rs
- crates/router/src/configs/settings.rs
- crates/router/src/core/admin.rs
- crates/router/src/types/api/admin.rs
- crates/router/src/types/domain/merchant_account.rs
- migrations/2023-07-11-140347_add_is_recon_enabled_field_in_merchant_account/down.sql
- migrations/2023-07-11-140347_add_is_recon_enabled_field_in_merchant_account/up.sql
- openapi/openapi_spec.json
Added is_recon_enabled field in merchant_account table and sending it in retrive merchant_account api
* This field will be used to know weather the merchant has recon service enabled or not
* check the merchant retrive api
> feat(merchant_account): add `is_recon_enabled` field in merchant_account

- crates/router/src/connector/powertranz.rs
- crates/router/src/connector/powertranz/transformers.rs
PowerTranz doesn't requires shipping address as mandatory field for processing payments.
> fix(connector): [PowerTranz] removing optional field shipping address

- crates/diesel_models/src/payment_intent.rs
dont update client secret on payment intent status update
> refactor(payments): dont update client secret on payment intent status update

- crates/router_env/src/logger/setup.rs
Adding server information in the metrics pipeline.
Adding information specific to the server in the metrics pipeline to support and mitigate issues against counter reset
> feat(metrics): add pod information in metrics pipeline

- crates/router/src/connector/authorizedotnet/transformers.rs
Authorizedotnet don't take cents as input, we need to parse the incoming amount which is in cents to the dollar value.
This pr contains : 
1) Authorizedotnet don't take cents as input, we need to parse the incoming amount which is in cents to the dollar value.
2) Field `Authcode` is not required in void response
> fix(connector): [Authorizedotnet] Convert amount from cents to dollar before sending to connector

- crates/common_utils/src/crypto.rs
- crates/redis_interface/src/lib.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/services/encryption.rs
This PR includes the following changes:
- Updates the AES-GCM-256 tests to use test vectors provided by NIST for the decryption test.
- Refactors the JWE and JWS to accept payload as `impl AsRef<[u8]>` instead of `String`.
- Fixes the JWE and JWS tests by adding sample RSA keys scoped only to the tests module.
- Fixes the doc test in the `redis_interface` crate documentation, and adds a commented line which helps to pass tests.
- Ignores a merchant connector account test since it's blocked on `MockDb` implementation of merchant key store. (#1697)
Being able to run `cargo test` locally and on CI.
Ran `cargo nextest` with the line un-commented in the `redis_interface` crate.
> test: fix failing unit tests

- docs/try_local_system.md
Updated `try_local_system.md` docs to include a note about how Postman now requires you to create a fork to "send" a request. The line number upserted is roughly 478.
Provide links to the files with corresponding changes.
`docs/try_local_system.md`
Why is this change required? What problem does it solve?
To make the documentation clearer.
Not applicable
> docs(postman): added a note about how postman now requires you to fork a collection in order to send a request

- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/configs/settings.rs
- crates/router/src/core/configs.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/errors/transformers.rs
Added support for handling duplicate config creation appropriately instead of throwing `InternalServerError`
- compiler guided testing
- Verified changes with VAS, not bump required
> fix(config): detect duplicate config insert and throw appropriate error

- crates/diesel_models/src/query/merchant_connector_account.rs
- crates/router/src/compatibility/stripe/app.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/webhooks.rs
- crates/router/src/types/api/webhooks.rs
After this PR is merged, even is webhook source verification fails, it will not fail the webhook request. Instead will go to Psync flow
Manual
When only one connector is present 
When multiple connectors are present
When No connectors are present
> revert: connector_label in webhook url is reverted back to connector_name

- crates/router/src/db.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/db/merchant_key_store.rs
- crates/router/src/types/storage.rs
- crates/router/src/types/storage/merchant_key_store.rs
This PR adds the `MockDb` implementation of `MerchantKeyStoreInterface`. In addition, this PR includes a fix for the `test_connector_label_cache` test in the `merchant_connector_account` module.
Fixes #1697.
> feat(db): implement `MerchantKeyStoreInterface` for `MockDb`

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/transformers.rs
currently we are relying only on payment_status to decide if manual_retry_allowed, need to have merchant_id check if a merchant is enabled for retries or not
Merchant is enabled for retries
Payments response for failed payment
Merchant is not enabled for retries
Payments response for failed payment
> feat(router): add merchant_id check for manual_retry_allowed flag sent in payments response

- crates/router/src/connector/mollie/transformers.rs
This PR will work for these following scenarios:
1. If auth_type is BodyKey , all the Mollie payment methods will work fine.
2. If auth_type is HeaderKey, except "Mollie card 3ds" all other payment methods will work fine.
3. If auth_type is HeaderKey, "Mollie card 3ds" will not work and give an "Internal Server Error."
Using Postman.
> refactor(fix): [Mollie] Add support for both HeaderKey and BodyKey AuthType

- crates/redis_interface/src/lib.rs
This PR fixes a bug introduced in #1786 with Redis connection pool connections never being set up on startup.
Fixes a bug introduced in #1786.
Locally, created a payment via Postman.
> fix(redis_interface): add back Redis pool connect step

- crates/router/src/connector/powertranz.rs
Incase of non 200 status code connector is not giving any response body. So the same should be handled in the get_error_response methods
To reduce unnecessary 5xx in the system
> fix(connector): [Powertranz] Fix response handling for https status code other than 200

- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/errors/transformers.rs
add `generic_duplicate_error` in api_error_response
Compiler guided
> feat(errors): add `GenericDuplicateError` in`ApiErrorResponse`

- crates/router/src/connector/klarna.rs
- crates/router/src/connector/klarna/transformers.rs
Incase of error, connector either return error_messages or error_message. Both should be handled in the error scenario
To fix deserialization error in case of error response from connector
> fix(connector): [Klarna] Handle error response with both error_messages and error_message fields

- crates/router/src/connector/trustpay/transformers.rs
currently we are getting empty string as cardholder name from sdk
cardholder name is mandatory for trustpay, send billing address name name as cardholder name
Payments Request
Request sent to connector
> fix(connector): [Trustpay] send billing address name as cardholder name

- crates/common_enums/src/enums.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/operations.rs
- crates/router/src/core/payments/operations/payment_cancel.rs
- crates/router/src/core/payments/operations/payment_capture.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/operations/payment_start.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payments/operations/payment_update.rs
Currently, if FRM pre flow gave a fraud status, we are cancelling the transaction, but its not reflected in the status. The status still comes out to be processing/pending. 
So we added a field, should_cancel_transaction in update trackers function definition, so that this can be supported.
if we get fraud status from frm, we should cancel the transaction and get failed status. following are the request and response curls : 
```
--header 'api-key: dev_QptRM7WYsKPdmsF0RwEQptVv0Rzsl5tYUWj5j8EM5sgBkCofUJTdVWG1PEmO3Uj6' \
--data-raw '{
"amount": 1500000, …
```
> feat(core): added key should_cancel_transaction in update trackers to support Frm Pre flow cancellation

- crates/router/src/connector/trustpay/transformers.rs
For Trustpay Apple Pay, we were sending amount in cents.This PR fixes amount issue by converting to currency base unit.
Fix amount issue
> fix: request amount fix for trustpay apple pay

- crates/api_models/src/payments.rs
- crates/router/src/core/webhooks.rs
- migrations/2023-08-01-165717_make_event_id_unique_for_events_table/down.sql
- migrations/2023-08-01-165717_make_event_id_unique_for_events_table/up.sql
Hyperswitch triggers a webhook only when it receives a webhook. We will need to trigger a webhook for payments too, but in that case, if we receive a webhook from upstream, that will also trigger a webhook to the merchant. To avoid this, event id is generated using `primary_resource_id` and `event_type`. This will prevent the same event type webhook being repeated.
migrations/2023-08-01-165717_make_event_id_unique_for_events_table/down.sql
migrations/2023-08-01-165717_make_event_id_unique_for_events_table/up.sql
- Create a payment and test if webhooks are received in the webhook site.
> fix(webhooks): do not send duplicate webhooks 

- crates/router/src/core/payments/operations/payment_status.rs
Currently, even if frm is not called, frm message is populated with the initial status for psync api
fixing this to only send frm_message, when status is not pending
> fix(core): If frm is not called, send None in frm_message instead of initial values in update tracker

- .github/workflows/CI-pr.yml
- .github/workflows/CI-push.yml
- .github/workflows/connector-sanity-tests.yml
- .github/workflows/connector-ui-sanity-tests.yml
- .github/workflows/postman-collection-runner.yml
- .github/workflows/validate-openapi-spec.yml
This PR reverts juspay/hyperswitch#1857 since `sccache` is causing some problems. We might reconsider using it again on a later date.
> revert: ci: use `sccache-action` for caching compilation artifacts

- .github/workflows/CI-push.yml
- Skip doing build for all features in merge queue for msrv and stable tool-chain's.
- In every pull request in merge queue run only release feature.
- In push to main run cargo hack on each-feature.
After a pull request, for every commit is pushed the cargo hack is running with each-feature which consumes action's resource.  
After this pr gets merge in action for every pr ci-push action logs will hack build logs only for release feature.
> ci: skip all-features check in each pull request

- crates/api_models/src/webhooks.rs
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/bluesnap.rs
- crates/router/src/connector/cashtocode.rs
- crates/router/src/connector/rapyd.rs
- crates/router/src/connector/zen.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/types/api/webhooks.rs
- crates/router/src/utils.rs
handle webhook source verification for multiple mca of the same connector
fetch payment_intent using object reference id, get the connector label using business details and fetch appropriate mca to get merchant secret for webhook source verification
Multiple MCA of adyen
Source verification
Outgoing webhook
> feat(router): handle webhook source verification for multiple mca of the same connector

- crates/router/src/core/payments/flows/authorize_flow.rs
Currently, when a payment succeeds, we save the card details to the locker. If an error occurs during this process, we return an error response, causing an inconsistency between the payment status and the card-saving status. To ensure a more accurate representation of the transaction, we should modify the response behavior in such cases.
Instead if the payment succeeds and saving card to locker fails we should return 200.
In case of mandates payments adding card to locker is a mandatory so we return error if the save card details to the locker fails. During the non mandate payments with setup_future_usage as on_session, if the  payment has succeeded and if save to card to locker fails we just log the error, as it would be inappropriate to return error for a Succeeded payment. 
Made …
> refactor(authorize_flow): suppress error while saving a card to locker after successful payment

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
5xx was being thrown because the struct PaymentMethodMetadata wasn't being deserialized so added a serde transparent as the struct had only one field payment_method_tokenization.
> fix(router): add `serde(transparent)` annotation for `PaymentMethodMetadata`

- .github/workflows/postman-collection-runner.yml
This PR is a hotfix to address postman-collection-runner failing to run since it found a duplicate variable `CONNECTOR` that I believe got duplicated at the time of resolving conflicts.
Now the Runner runs..
> ci(postman): Fix collection runner failing to run

- .github/git-cliff-changelog.toml
- .github/git-cliff-release.toml
This PR updates the `git-cliff` templates to remove spaces at the beginning of the commit message.
Because of the leading spaces in some commit messages, the offending commits were not being included in the release notes. This PR fixes that.
Verified that the changelog generated does include the offending commits. One such PR was #1804, which was included in the `v1.15.0` tag. For verifying my fix, I generated the changelog using the command: `git cliff --config .github/git-cliff-changelog.toml v1.14.1..v1.15.0`.
> chore: remove spaces at beginning of commit messages when generating changelogs

- crates/api_models/src/webhooks.rs
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/bluesnap.rs
- crates/router/src/connector/cashtocode.rs
- crates/router/src/connector/rapyd.rs
- crates/router/src/connector/zen.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/types/api/webhooks.rs
- crates/router/src/utils.rs
add webhook source verification support for multiple mca of the same connector
Previous hotfix - https://github.com/juspay/hyperswitch/pull/1896
> feat(router): add webhook source verification support for multiple mca of the same connector

- crates/router/src/connector/adyen.rs
- crates/router/src/connector/adyen/transformers.rs
In case of Redirection Response in Adyen, it doesn't contain the `payload` field, resulting in deserialization error
>  fix(connector): [Adyen] Response Handling in case of RefusalResponse

- crates/router/src/connector/stax/transformers.rs
Connector Stax only supports payments through the default currency(USD). Added a filter to throw an error if any currency other than USD is used to process a transaction through Stax.
Bugfix: Added a filter to throw an error if any currency other than USD is used to process a transaction through Stax.
Testing was carried out using Unit Tests.
> fix(connector): [STAX] Add currency filter for payments through Stax

- crates/router/src/connector/braintree.rs
- crates/router/src/connector/braintree/transformers.rs
- crates/router/src/connector/rapyd.rs
- crates/router/src/connector/trustpay.rs
- crates/router/src/utils.rs
1) added `Merchant Account id` field in authorize request for braintree. 
2) handle error response in case of wrong merchant account id 
3) cherry pick #1892
1) added `Merchant Account id` field in authorize request for braintree. 
2) handle error response in case of wrong merchant account id 
3) cherry pick #1892
> fix(connector): [Braintree] add merchant_account_id field in authorize request

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/routes/payment_methods.rs
The function call responsible for deleting card details from payments_operations_core() was been removed in this PR https://github.com/juspay/hyperswitch/pull/1636. This modification ensured that the redundant deletion of already deleted card details no longer occurs, preventing the unnecessary error from being triggered.
Now as the delete functionality was removed from the payments_operation_core the token created was valid even after the payment reached the terminal states. So, this pr deletes the internal token that is mapped to the locker token in the redis. Hence the token becomes invalid once a payment reaches terminal state.
#1818
> fix(payment_methods): delete token when a payment reaches terminal state

- crates/router/src/connector/braintree/transformers.rs
Previously status settled is declared in enums but not mapped .So the payment which goes to settled state remains processing even after force sync .This pr contains proper status mapping for connector braintree .
> fix(connector): [Braintree] fix status mapping for braintree

- crates/diesel_models/src/enums.rs
- crates/diesel_models/src/fraud_check.rs
- crates/diesel_models/src/query/fraud_check.rs
- crates/diesel_models/src/schema.rs
- crates/router/src/db/fraud_check.rs
- migrations/2023-08-16-103806_add_last_executed_frm_step/down.sql
- migrations/2023-08-16-103806_add_last_executed_frm_step/up.sql
Currently, frm module dosent work for 3ds flow.
It is because, payments operation core is called multiple times in the same request, and so is pre and post frm.
This creates duplicate entries, and also creates discrepencies.
To fix this, we are adding a field fraud_check_last_step in the fraud check table. This is to indicate the last step executed in  the frm flow, and we will restrict few actions based on the last_step. 
Eg 1: if the last_step is `processing`, then we can do `checkout` or `sale` nothing else
Eg 2: if the last_step is `checkout_or_sale`, then we can do `transaction` or `refund` or `fullfillment`
Eg 3: if the last_step is `transaction_or_record_refund`, then we can either only do `fullfillment`
- is_terminated is added to table fraud_check.
- do a 3ds flow, with frm.
- …
> fix(frm): added fraud_check_last_step field in fraud_check table to support 3DS transaction in frm

- crates/router/src/connector/cashtocode/transformers.rs
> fix(connector): [CashToCode] Transform minor units to major units

- crates/api_models/src/lib.rs
- crates/api_models/src/payouts.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/core/payouts/helpers.rs
Permanent locker requires either card details or encrypted card data to be stored in DB. In case both the fields are present during addition in locker, card details takes preference over the latter. This leads to the locker retrieval API returning null for the required enc_card_data field where generic payment method data is stored.
This is solved by segregating the data types for card addition API request in locker to send only card details or encrypted card data based on the usecase.
Tested in custom integ pod for customer `locker_bank_test`. Bank details for SEPA and BACS are stored for this customer post fulfillment of the payout transaction.
```
curl --location 'https://integ-api.hyperswitch.io/customers/locker_bank_test/payment_methods' \ …
```
> fix: storage of generic payment methods in permanent locker

- crates/test_utils/src/main.rs
Removes `as cmd` and we will be using `Command` going forward. 
Remove bad code practice.
No tests needed.
> fix(test_utils): remove `cmd` alias for `std::process::Command`

- Cargo.lock
- crates/router/src/core/payments/helpers.rs
Made the `authenticate_client_secret `function public for usage
> refactor(core): made authenticate_client_secret function public

- crates/api_models/src/admin.rs
- crates/router/src/compatibility/stripe/customers.rs
- crates/router/src/compatibility/stripe/payment_intents.rs
- crates/router/src/compatibility/stripe/refunds.rs
- crates/router/src/compatibility/stripe/setup_intents.rs
- crates/router/src/core/admin.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/types/domain/merchant_account.rs
Previously Webhooks were triggered when the payment status changes. The outgoing webhook was hyperswitch webhook. 
In this PR , the outgoing webhook is converted to stripe compatible webhook based on metadata of merchant account. 
Slightly modifies the merchant_account api contract by adding the field '{"compatible_connector": "\<Connector\>"}' in metadata. The dashboard can add this field if required.
Tested manually. 
Created a merchant_account and updated the metadata to contain the field `"compatible_connector": "stripe"`
Created a payment and the webhook that was sent was stripe compatible.
> fix(webhooks): send stripe compatible webhooks for stripe compatible merchants

- .github/workflows/CI-pr.yml
- .github/workflows/CI-push.yml
- .github/workflows/connector-sanity-tests.yml
- .github/workflows/conventional-commit-check.yml
- .github/workflows/migration-check.yaml
- .github/workflows/postman-collection-runner.yml
- .github/workflows/release-new-version.yml
- .github/workflows/validate-openapi-spec.yml
- Cargo.lock
- openapi/openapi_spec.json
This would provide us sufficient time to address any clippy lints that would be stabilized.
Using the latest stable Rust toolchain could block PRs whenever new `clippy` lints are introduced. Using the stable toolchain from 2 weeks ago would give us sufficient time to address these lints.
N/A
> ci: use Rust stable from 2 weeks ago

- crates/test_utils/tests/connectors/adyen_uk_wh_ui.rs
- crates/test_utils/tests/connectors/bluesnap_wh_ui.rs
- crates/test_utils/tests/connectors/checkout_wh_ui.rs
- crates/test_utils/tests/connectors/main.rs
- crates/test_utils/tests/connectors/stripe_wh_ui.rs
This PR add support for adyen webhooks and fix checkout webhooks.
> test(connector): add support for adyen webhooks

- crates/api_models/src/payments.rs
- crates/data_models/src/payments/payment_intent.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/setup_intents/types.rs
- crates/storage_impl/src/payments/payment_intent.rs
- openapi/openapi_spec.json
- Add max limit on transforms to common filter
- Add offset for payment intents fetch
- Currently we used a common limit across all api's which shouldn't be the case
> fix(payment): fix max limit on payment intents list

- docs/CONTRIBUTING.md
Fixed the HTTP path for the open a discussion link in the CONTRIBUITING docs.
First, this is a hands-on for me about how to follow the [CONTRIBUTING.md](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md) guidelines. 
Second, the [old link](https://github.com/juspay/hyperswitch/discussions/new) showed a pop-up about not recognizing the category.
Opening the [new link](https://github.com/juspay/hyperswitch/discussions/new/choose) does not show the pop-up.
> docs(CONTRIBUTING): fix open a discussion link

- crates/router/src/connector/bluesnap.rs
- crates/router/src/connector/bluesnap/transformers.rs
Make `error_name` as optional field which is added for GSM, if error_name is not present populate error_code.
For 401 error `error_name` will not be there so make it optional
5xx coming on status_code 401
> fix(connector): [Bluesnap] make error_name as optional field

- Cargo.lock
- crates/router/src/bin/scheduler.rs
- crates/router/src/core/errors.rs
- crates/router/src/lib.rs
- crates/router/src/routes/app.rs
- crates/router/src/services/api.rs
- crates/router/src/services/api/client.rs
- crates/router/src/types/storage/payment_attempt.rs
- crates/router/tests/cache.rs
- crates/router/tests/connectors/aci.rs
- crates/router/tests/connectors/utils.rs
- crates/router/tests/payments.rs
- crates/router/tests/payments2.rs
- crates/router/tests/services.rs
- crates/router/tests/utils.rs
This is a micro PR for introducing `ApiClient` trait in `AppState`. This PR only adds the client but doesn't use it as of now.
It builds over: #1919 
Compiler Guided Testing
> feat(api): use `ApiClient` trait in AppState

- crates/router/src/connector/stax/transformers.rs
This enhancement will only allow Cards & ACH Bank Debit Calls to go through Authorize flow of Stax.
Now only allow Cards & ACH Bank Debit Calls will go through Authorize flow of Stax.
Testing carried out using Postman Calls
> fix(connector): [STAX] Add ACH Payment Filter for Bank Debits

- crates/diesel_models/src/enums.rs
Enum variant mispelled...changed from fullfillment to fulfillment
This is required for the implementation of the fullfillment api 
new api endpoint added... /frm_fulfillment 
no existing endpoint changed...the foll. is the curl for the same :
> feat(frm): enum variant misspelled changed from fullfillment to fulfillment

- crates/drainer/src/env.rs
- crates/drainer/src/lib.rs
- crates/drainer/src/logger.rs
- crates/drainer/src/main.rs
- crates/router/src/bin/router.rs
- crates/router/src/bin/scheduler.rs
- crates/router/src/env.rs
- crates/router_env/src/env.rs
- crates/router_env/src/logger/setup.rs
- crates/router_env/tests/logger.rs
This PR updates the logging setup code to include the binary name in the `service` field in log entries. For the scheduler specifically, the `service` field would contain the name of the scheduler flow, namely, `consumer` or `producer`, since each of them are independent Docker containers (and thus, independent deployments).
After this change, the `service` field in logs can have one of four values: `router`, `consumer`, `producer` and `drainer`.
This would allow us to perform better filtering of logs based on service name. 
Started all services using Docker Compose (command: `docker compose --profile scheduler --profile monitoring up --detach`) and verified that logs are available when filtering by the `service` field for `router`, `consumer` and `producer`. Attaching screenshots of the …
> refactor: include binary name in `service` field in log entries

- config/development.toml
- crates/router/src/configs/settings.rs
- crates/router/src/utils/verification.rs
Previously we had only one route for apple-pay. we were always hitting their prod servers even when we were using our sbx but now while using our sbx we will be hitting their sbx as well
> refactor(router): new separate routes for applepay merchant verification

- .github/workflows/release-new-version.yml
I had used the wrong path to `node_modules` in the previous commit.  Fixing it in this PR.
This is need to update Postman collection files and keep them in sync with the directory representations.
This workflow is a release workflow - which cannot be completely replicated.  Ensured that the code to set the PATH is the same as the one used in the PR workflow.
> ci(release-new-version): correct `node_modules` path

- crates/router/src/consts.rs
- crates/router/src/services/api.rs
send connection_closed errors as 5xx instead of 2xx as connections are not being closed by external entities
> fix(router): send connection_closed errors as 5xx instead of 2xx

- crates/router/src/connector/stax/transformers.rs
- crates/router/tests/connectors/stax.rs
While creating a payment or a refund with connector Stax the incoming amount is being processed in it's higher decimal amount (e.g. Dollars) instead of processing it in it's lower units (e.g. Cents).
Unit testing was completed
> fix(connector): [STAX] Incoming amount will be processed in higher unit

- crates/router/src/connection.rs
- crates/router/src/utils.rs
- crates/storage_impl/src/connection.rs
This PR addresses a clippy lint stabilized in Rust 1.72.
> chore: address Rust 1.72 clippy lints

- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_response.rs
…irm operations
The PR introduces concurrency to the database calls limited only to the payments confirm operation.
compiler guided
> feat(payments): make database calls parallel for `payments_confirm` operation

- crates/router/src/connector/checkout/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
> fix(connector): revert checkout apple pay to tokenization flow

- crates/router/src/connector/cryptopay.rs
- crates/router/src/connector/cryptopay/transformers.rs
Add cutom_id field in which we send reference id to the connector.
Outgoing Webhooks - 
Connector dashboard-
> feat(connector): [Cryptopay]Add reference id for cryptopay

- .github/workflows/CI-pr.yml
- .github/workflows/CI-push.yml
This PR pins the version of `cargo-hack` installed during the MSRV check to `v0.6.5`, since `v0.6.6` has an MSRV of Rust 1.66.
Fixes failing MSRV check due to unsupported Rust version for `cargo-hack v0.6.6`.
N/A
> ci: pin `cargo-hack` version to `v0.6.5` for MSRV check

- crates/diesel_models/src/business_profile.rs
- crates/router/src/db/business_profile.rs
- crates/storage_impl/src/lib.rs
Implement the missing implementation of MockDb for business profiles.
Closes #2039
> feat(db): implement `BusinessProfileInterface` for `MockDb`

- crates/router/src/connector/trustpay/transformers.rs
- crates/router/src/core/payments.rs
1. Fixed session token having null value in next action for third party sdk response
2. change status from pending to `requires_customer_action` for gpay and apple pay in trustpay
Fix session token in next_action null value to session response 
Status changed from pending to requires_customer_action
session_token response in next_action
Trustpay retrieve call getting processing as expected
> fix: null value in session token in next action  

- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
This reduces the database calls done during the confirm call in the `get_tracker` to 2 concurrent stages.
> feat(confirm): reduce the database calls to 2 stages in case of non-retry

- crates/router/src/core/payments/flows/psync_flow.rs
If call_connector_action is anything other than trigger, we need not validate_psync_reference_id. 
`validate_psync_reference_id` only if call_connector_action is trigger in psync flow
> fix(router): `validate_psync_reference_id` only if call_connector_action is trigger in psync flow

- crates/router/src/core/payment_methods/cards.rs
Fixes the bug caused by previous change of fetching card details from pmt. Now defaulting to locker call.
curl - `curl --location --request GET 'http://localhost:8080/customers/StripeCustomer3/payment_methods' \
--header 'api-key: dev_ddu3uvKpn01bZtGOgju0Ihfg2troEdhWaoC79wt6V1tDQesrIU4j8zn1LDgsXl6P'`
> fix(payment_methods): Default card fetch to locker call

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- crates/router/src/configs/settings.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
disable temp locker call for connector-payment_method flow based on env
UI Tests for Stripe
CIT mandate transaction for Stripe
MIT mandate transaction for Stripe
3DS payment for Trustpay
Bank redirect for Trustpay
Non3DS for Trustpay
Payment_token being null for all the above payments as temp locker is disabled
> feat(router): disable temp locker call for connector-payment_method flow based on env

- Cargo.lock
- crates/router/src/routes/dummy_connector/utils.rs
- crates/scheduler/src/consumer.rs
- crates/scheduler/src/errors.rs
- crates/scheduler/src/producer.rs
This is a bugfix for issue [1754](https://github.com/juspay/hyperswitch/issues/1754).
I have replaced the instances of `gen_range()` with `Uniform.sample`.
This should reduce the risk of `gen_range()` throwing a `panic!`.
Provide links to the files with corresponding changes.
Following are the paths where you can find the changed files:
1. crates/router/src/routes/dummy_connector/utils.rs
2. crates/router/src/scheduler/producer.rs
3. crates/router/src/scheduler/consumer.rs
4. crates/scheduler/src/errors.rs
This is a bugfix for issue [1754](https://github.com/juspay/hyperswitch/issues/1754)
Closes #1754.
I did not write any new tests but I ran `cargo test -p router --lib` and all tests passed.
NOTE: I was not able to run all integration tests because my laptop is not setup for running …
> fix(router/scheduler): replace the occurrences of gen_range with a safer alternative

- crates/router/src/db/configs.rs
There is a recursive call which is made in update configs function. We need to remove that and change it to a db call in order for update call to properly function.
> fix: eliminate recursive call while updating config in database

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_session.rs
This change will add support for calling list payment method, and session tokens for payments that were created during the deployment period and those payments which are in non terminal status. This is to support backwards compatibility.
Compile locally
> refactor(pm_list): get profile_id from business_details in list pm

- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/connector/payme.rs
- crates/router/src/connector/payme/transformers.rs
Add dispute webhook support for payme
Dispute webhooks are now supported in payme
> feat(connector): [payme] Add support for dispute webhooks

- crates/masking/src/lib.rs
- crates/masking/src/maskable.rs
- crates/router/src/services/api/request.rs
Currently `Maskable` enum and `Mask` trait resides in router crate. Since this is related to masking we can move this to `masking` crate
> refactor(masking): move masking implementations to masking crate

- crates/data_models/src/payments/payment_attempt.rs
- crates/diesel_models/src/payment_attempt.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/storage_impl/src/payments/payment_attempt.rs
amount_capturable was not updated in update_trackers() of payment_create and confirm.
This was causing unexpected values in amount_capturable field in response during payment create and confirm call.
> fix(core): update amount_capturable in update trackers

- crates/router/src/connector/trustpay/transformers.rs
We don't get payment_status only in case, when the user doesn't complete the authentication step. So, the status should be mapped to Authentication pending
If we receive status, then return the proper status based on the connector response
Payment status fix
> fix: payment status fix in trustpay for 3ds and wallets

- crates/router/src/connector/trustpay/transformers.rs
This PR fixes:
1. Change payment status from pending to requires_customer_action in the confirm call for wallets, as it would invoke sdk.
2. Change the payment status to requires_customer_action from pending when user do not authenticate
Fix the status change
> fix: payment status in trustpay 3ds and wallets

- crates/router/src/connector/stripe.rs
- crates/router/src/connector/stripe/transformers.rs
Add support for some more dispute webhooks events for stripe which is : `Charge Dispute Funds Withdrawn`, `Charge Dispute Funds Reinstated`.
I also removed `Charge Dispute Captured` event as latest stripe documentation does not have this event.
Can not be tested.
> refactor(connector): [Stripe] add support for more incoming woocommerce Stripe disputes webhooks

- connector-template/mod.rs
- connector-template/transformers.rs
- crates/router/src/connector/braintree.rs
- crates/router/src/connector/braintree/braintree_graphql_transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/types/api.rs
Problem : Currently, amount mapping for different connectors are handled by hard coding dollars/cents which has been leading to multiple bugs due to incorrect mapping. Need to handle this better in code by having separate types for dollar vs cents .
Solution : To address this issue and improve code maintainability, this pull request introduces the `get_currecny_unit` from `ConnectorCommon` trait. This function allows connectors to declare their accepted currency unit as either "Base" or "Minor" .
Implement the ConnectorCurrencyCommon trait, where you can declare the accepted currency unit (either Base or Minor) using the get_currency_unit method in `ConnectorCommon` trait .
tested it locally
> refactor(connector): [BraintreeGraphQl] Enhance currency Mapping with ConnectorCurrencyCommon Trait 

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/db/address.rs
- crates/router/src/db/capture.rs
- crates/router/src/db/cards_info.rs
- crates/router/src/db/configs.rs
- crates/router/src/db/connector_response.rs
- crates/router/src/db/customers.rs
- crates/storage_impl/src/payments/payment_attempt.rs
- crates/storage_impl/src/payments/payment_intent.rs
This PR adds `#[instrument(skip_all)]` flag to all db functions in trackers for `payment_confirm.rs`.
Compiles
> refactor: add instrument to trackers for payment_confirm

- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario2-Create payment with confirm false/Payments - Confirm/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario2-Create payment with confirm false/Payments - Retrieve/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario3-Create payment without PMD/Payments - Confirm/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario3-Create payment without PMD/Payments - Retrieve/event.test.js
This PR fixes assertion issue with Paypal. Amount capturable should 0 after it goes to terminal state
Fix it
Ran against integ environment
> ci(postman): Fix Paypal capture assertion failure

- .github/workflows/postman-collection-runner.yml
This PR aims at refactoring the server start logic of `postman-runner.yml` file to address timeout issue that killed the server if the server did not start within 15 minutes.
For context: 
The above failure is because of the timeout that occurred. 
With this PR going in, we'll be building first and then starting the server next in the background in 2 different steps. This way, if the build fails, the check should anyway fail. If the server does not start within the next 2 minutes, fail the check again.
Now that it consumes less than 10 minutes to run, we've reduced the time consumption by 7+ minutes.
> ci(postman): Modify server start logic to address timeouts in actions

- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/types/storage/payment_attempt.rs
amount_capturable must be made `0` when payment status goes to `processing`. Because from `processing` status, the payment can go to either `success` or `failure`. Both are terminal status.
> fix: make amount_capturable zero when payment intent status is processing

- crates/router/src/core/payments.rs
This pr includes the changes to move the `get_connector_tokenization_action_when_confirm_true` above `call_create_connector_customer_if_required`.
This is required because when a payment is created with confirm false, a payment token is returned. Then the token is passed in the confirm call in which we fetch the payment_method_data with the help of the passed token.  This fetch operation happens in the `get_connector_tokenization_action_when_confirm_true` as this function was called after the call_create_connector_customer_if_required payment_method_data was not available for call_create_connector_customer_if_required and hence construct router data in call_create_connector_customer_if_required was failing.
Stripe
Bluesnap
Stripe mandates
> fix(router): move `get_connector_tokenization_action_when_confirm_true` above `call_create_connector_customer_if_required`

- Cargo.lock
- crates/api_models/src/verifications.rs
- crates/router/src/routes/verification.rs
We need to provide camel case keys in applepay request.
> refactor(router): add camel_case for the applepay request

- crates/router/src/core/payment_methods/cards.rs
Apply `Payment Methods List` filters on the billing address as opposed to the shipping address for a payment as it makes more sense in the context of the payment.
None
The payment itself is tied with the billing address as opposed to the shipping address, thus it makes more sense to use it for list payment method filters.
Local, compiler-guided
> refactor(router): use billing address for payment method list filters as opposed to shipping address

- crates/router/src/services/api.rs
Removing x-request-id before connector calls
> fix: remove x-request-id from headers before connector calls

- crates/drainer/src/settings.rs
- crates/router/src/configs/settings.rs
- crates/router_env/src/logger/config.rs
This PR refactors the application configuration deserialization code to make the TOML file as an optional source of application configuration.
The TOML file was made as a required source of application configuration when support for deserializing application configuration from environment variables was absent. Since we have support for environment variables now, we can make the TOML file as an optional source.
Ran it locally without `config/development.toml`, binary does not complain about missing `development.toml` file.
> refactor(configs): make TOML file an optional source of application configuration

- crates/router/src/connector/trustpay/transformers.rs
`800.300.102` error code was missing due to which payment remained in `processing` status
Add the  missing error code
> fix(connector): [Trustpay] Add missing error code

- crates/router/src/routes/app.rs
This PR adds the setter for `flow_name`.
Logs.
> fix: add flow_name setter

- crates/router/src/db/configs.rs
add find_config_by_key_unwrap_or , so that the default value is inserted in DB and cached for faster retrievals.
Compiles
> feat(db): add find_config_by_key_unwrap_or

- crates/router/src/connector/adyen.rs
- crates/router/src/connector/adyen/transformers.rs
This pull request introduces the get_currecny_unit from ConnectorCommon trait for Adyen. This function allows connectors to declare their accepted currency unit as either "Base" or "Minor" .For Adyen it accepts currency as Minor.
> refactor(connector): [Adyen] Enhance currency Mapping with ConnectorCurrencyCommon Trait 

- crates/router/src/core/admin.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payouts.rs
- crates/router/src/core/utils.rs
- crates/router/src/utils.rs
Removing db calls which are unnecessary
> refactor(core): eliminate business profile database queries in payments confirm flow

- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/utils.rs
fix attempt status for techincal failures in psync flow
1. In Psync flow for 4xx / 5xx errors mark the previous attempt status instead of marking it as processing / failure
1. 4xx in payments confirm flow, payment status would be marked as failure
2. 4xx in payments retrieve flow with force_sync = true for processing payment, status is unchanged
> fix(router): fix attempt status for techincal failures in psync flow

- CHANGELOG.md
- postman/collection-dir/aci/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/adyen_uk/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/airwallex/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/authorizedotnet/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/bambora/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/bambora_3ds/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/bluesnap/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/braintree/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/checkout/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/forte/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/globalpay/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/hyperswitch/API Key/Create API Key/request.json
- postman/collection-dir/hyperswitch/Hackathon/QuickStart/API Key - Create/request.json
- postman/collection-dir/hyperswitch/QuickStart/API Key - Create/request.json
- postman/collection-dir/mollie/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/multisafepay/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/nexinets/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/nmi/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/payme/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/paypal/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/powertranz/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/rapyd/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/shift4/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/stripe/API Key/Create API Key/request.json
- postman/collection-dir/stripe/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/stripe/QuickStart/API Key - Create/request.json
- postman/collection-dir/trustpay/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/worldline/Flow Testcases/QuickStart/API Key - Create/request.json
- postman/collection-dir/zen/Flow Testcases/QuickStart/API Key - Create/request.json
ALL COLLECTIONS will fail starting today. In order to avoid that, this PR comes in and updates the HS expiration date.
UPDATE (Was testing @SanchithHegde's feature!)
API Keys now will not throw 401.
> ci(postman): Update API key expiration date

- crates/router/src/connector/stripe/transformers.rs
Need to test the apple pay simplified and manual flow for stripe
Curl
```
"metadata": {
"apple_pay_combined": {
"simplified": {
"session_token_data": {
"initiative_context": "sdk-test-app.netlify.app"
},
"payment_request_data": {
"label": "applepay",
"supported_networks": [
"visa",
"masterCard",
"amex",
"discover"
],
"merchant_capabilities": [
"supports3DS"
]
}
}
}
}
```
> fix(connector): [stripe] use display impl for expiry date 

- crates/router/src/db/cache.rs
- crates/router/src/db/reverse_lookup.rs
- crates/storage_impl/src/lookup.rs
- crates/storage_impl/src/payments/payment_attempt.rs
- crates/storage_impl/src/redis/cache.rs
Add KV for last successful payment attempt
Add it in KV for better latency
This function is being used in `refunds_create_core`. So refund should succeed.
> feat(payment_attempt): add kv for find last successful attempt

- crates/router/src/db/merchant_connector_account.rs
The key used to redact and fetch the cached value were different. It has been fixed in this PR.
After updating the merchant connector account, it was not being redacted because of invalid redact key.
- Create a connector with invalid connector credentials.
- Create a payment. - fails
- Update the mca with correct connector credentials.
- Create a payment. - succeeds
> fix(merchant_connector_account): use appropriate key when redacting

- crates/router/src/connector/zen.rs
- crates/router/src/connector/zen/transformers.rs
This pull request introduces the get_currecny_unit from ConnectorCommon trait for `Zen`. This function allows connectors to declare their accepted currency unit as either "Base" or "Minor" .For zen it accepts currency as Base.
> refactor(connector): [Zen] Enhance currency Mapping with ConnectorCurrencyCommon Trait

- crates/router/src/connector/stripe/transformers.rs
Bank Transfer Payment sync was failing due to stripe contract changes , stripe now expecting the payment_method_type as customer_balance.So, this PR supports customer_balance in StripePaymentMethodDetailsResponse
Bank Transfer Payment sync was failing due to stripe contract changes, so fixed in this PR
Steps:
1. Bank transfer payment
2. Retrieve the payment. (Earlier it was failing here because of stripe changes, so now we should get proper response), attaching the screen shot of the tested repsonse
> fix: [stripe] Add customer balance in StripePaymentMethodDetailsResponse

- crates/data_models/src/payments/payment_attempt.rs
- crates/diesel_models/src/payment_attempt.rs
- crates/diesel_models/src/schema.rs
- crates/router/src/core/payments/helpers.rs
- crates/storage_impl/src/mock_db/payment_attempt.rs
- crates/storage_impl/src/payments/payment_attempt.rs
- migrations/2023-09-25-125007_add_surcharge_metadata_payment_attempt/down.sql
- migrations/2023-09-25-125007_add_surcharge_metadata_payment_attempt/up.sql
`surcharge_metadata` Field will be used to store the surcharges for each payment_method during list payment method call.
During confirm call, this data can be used to arrive at final amount to send to connector.
> feat(core): create surcharge_metadata field in payment attempt

- crates/router/src/connector/payme.rs
- crates/router/src/connector/payme/transformers.rs
This pull request introduces the get_currecny_unit from ConnectorCommon trait for `Payme`. This function allows connectors to declare their accepted currency unit as either "Base" or "Minor" .For Payme it accepts currency as Minor.
> refactor(connector): [Payme]Enhance currency Mapping with ConnectorCurrencyCommon Trait 

- crates/router/src/connector/gocardless/transformers.rs
temp support for ach gocardless with existing api contracts
Local testing with postman
> fix: temp support for ach gocardless with existing api contracts

- crates/cards/src/lib.rs
Allow card cvc 000
Card CVC can be 000
The CVV code on my credit card is 000. : r/mildlyinteresting
Reddit
[https://www.reddit.com › mildlyinteresting › comments](https://www.reddit.com/r/mildlyinteresting/comments/2g1nz2/the_cvv_code_on_my_credit_card_is_000/)
"Invalid Card CVC" (thrown only when cvc is 000)
> fix(cards): Allow card cvc 000

- crates/router/src/connector/klarna.rs
Match arms using the wildcard patten (`_`) can be dangereous when extending enums since developers may miss locations where new variants should be handled. This patch expands all wildcard patterns in the Klarna connector to avoid this problem.
Fixes #2273 
`cargo check`, `cargo clippy`, and `cargo test` all pass without errors in modified files.
> refactor(connector): [Klarna] Expand wildcard match arms

- crates/router/src/connector/klarna.rs
- crates/router/src/connector/klarna/transformers.rs
This pull request implements the `get_currency_unit` from the `ConnectorCommon` trait for the Klarna connector. This function allows connectors to declare their accepted currency unit as either `Base` or `Minor`. For Klarna it accepts currency as `Minor` units.
Fixes #2230 
`cargo check`, `cargo clippy`, and `cargo test` all pass without any new errors.
> refactor(connector): [Klarna] Enhance currency Mapping with ConnectorCurrencyCommon Trait

- crates/diesel_models/src/query/merchant_key_store.rs
- crates/router/src/core/admin.rs
- crates/router/src/db/merchant_key_store.rs
Closes #2154 by calling `delete_merchant_key_store_by_merchant_id` at `merchant_account_delete`
> fix(router): merchant account delete does not delete the merchant_key_store

- crates/router/src/connector/stax/transformers.rs
This pull request fixes #2348 issue in STAX and uses connector_response_reference_id as reference to merchant.
Fixes https://github.com/juspay/hyperswitch/issues/2348
> feat(connector): [Stax] Use connector_response_reference_id as reference to merchant

- Cargo.lock
- crates/scheduler/Cargo.toml
- crates/scheduler/src/utils.rs
This PR addresses `undeclared crate or module` errors arising from the `scheduler` crate on Windows, due to some crates being excluded on Windows. In addition, some of the unused dependencies of the `scheduler` crate have also been removed.
Fix failing builds on Windows.
I was able to build the `scheduler` crate successfully, thus confirming that the removed crates were indeed unused. For the Windows-specific changes, I haven't tested it out on a Windows machine, but I believe the codebase should build successfully.
> build(deps): address `undeclared crate or module` errors on Windows for `scheduler` crate

- crates/router/src/connector/payeezy/transformers.rs
Add `connector_response_reference_id` support for Payeezy
- Used `transaction_id` as the reference id, while implementing this!  
Resolves #2343 and resolves #2312.
Need help testing!
> feat(connector): [Payeezy] Use connector_response_reference_id as reference to merchant

- crates/api_models/src/webhooks.rs
This PR will add a function to retrieve the `payment_id` which can be populated in the webhooks response which can be used by other crates.
> refactor(webhook): add a function to retrieve payment_id

- crates/router/src/connector/noon/transformers.rs
I have added `reference` that's sent to noon payments order to the `TransactionResponse` in `transformer.rs` of noon that's present in the `connector` directory.
https://github.com/juspay/hyperswitch/blob/main/crates/router/src/connector/noon/transformers.rs
Closes  #2339
> feat(connector): [Noon] Use connector_response_reference_id as reference

- crates/router/src/compatibility/stripe/errors.rs
- crates/router/src/connector/adyen.rs
- crates/router/src/core/errors.rs
- crates/router/src/core/errors/api_error_response.rs
- crates/router/src/core/errors/transformers.rs
Currently adyen returns `bad request body` error during webhook call if merchant_secret set by the merchant for webhook source verification is invalid.
In this PR, appropriate error message will be returned when merchant_secret is an invalid value.
```
{"error":{"type":"invalid_request","message":"Merchant Secret set for webhook source verificartion is invalid","code":"WE_02"}}
```
`hex::decode(string)` function is used to decode the `merchant_secret` to a `Vec<u8>` in adyen.
This `hex::decode(string)` function will return Err() if the `string` value passed to it either has odd number of characters or if it has an invalid character.
Manual
> fix: return appropriate error message during webhook call for invalid merchant_secret adyen

- crates/api_models/src/payment_methods.rs
- crates/api_models/src/payments.rs
- crates/common_enums/src/enums.rs
- crates/data_models/src/payments/payment_intent.rs
- crates/diesel_models/src/enums.rs
- crates/diesel_models/src/payment_intent.rs
- crates/diesel_models/src/schema.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/openapi.rs
- crates/storage_impl/src/mock_db/payment_intent.rs
- crates/storage_impl/src/payments/payment_intent.rs
- migrations/2023-10-04-120026_add_payment_type_column_in_payment_intent/down.sql
- migrations/2023-10-04-120026_add_payment_type_column_in_payment_intent/up.sql
- openapi/openapi_spec.json
This PR adds a new `payment_type` column in the `payment_intent` table, the value of which is inferred during payment creation, and is also included in the response of the list payment methods call.
The `payment_type` field will be detrimental in deciding the right mandate flow. Certain merchants may want to just set up the mandate without debiting any amount, whereas some merchants may want to debit some amount as part of the setup. This distinction is done based on the `payment_type`.
> feat(router): add support for payment_type field in payment intent

- crates/api_models/src/mandates.rs
- crates/api_models/src/webhooks.rs
- crates/common_enums/src/enums.rs
- crates/diesel_models/src/enums.rs
- crates/diesel_models/src/mandate.rs
- crates/diesel_models/src/query/mandate.rs
- crates/diesel_models/src/schema.rs
- crates/router/src/compatibility/stripe/webhooks.rs
- crates/router/src/core/mandate.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/db/mandate.rs
- crates/router/src/types/transformers.rs
- crates/router/src/utils.rs
- migrations/2023-10-05-114138_add_payment_id_in_mandate/down.sql
- migrations/2023-10-05-114138_add_payment_id_in_mandate/up.sql
- migrations/2023-10-05-130917_add_mandate_webhook_types/down.sql
- migrations/2023-10-05-130917_add_mandate_webhook_types/up.sql
- openapi/openapi_spec.json
add mandates incoming webhooks flow
Original payment id being stored in mandate record
Mandates webhook flow
Compiler guided
> feat(router): add mandates incoming webhooks flow

- crates/router/src/connector/gocardless.rs
- crates/router/src/connector/gocardless/transformers.rs
Add mandate webhooks in connector gocardless.
Add mandate webhooks in connector gocardless.
> feat(connector): [Gocardless] Add mandate webhoooks

- crates/router/src/connector/noon/transformers.rs
Closes #2308
Use `connector_request_reference_id` instead of `payment_id` as Order reference
> feat(connector): [Noon] Use connector_request_reference_id as Order reference

- .github/workflows/CI-pr.yml
It use to auto formate the code even for external contributors and push a commit. This is not the expected behavior hence rem removing the auto formatting.
> CI: Remove auto format code when formatting step fails

- crates/router/src/connector/coinbase/transformers.rs
Relevant documentation [here](https://docs.cloud.coinbase.com/commerce/docs/webhooks-events). I'm not 100% sure what `code` is in the documentation but they haven't provided more clarity, the only other identifier for the transaction is id, so I've used that.
Fixes #2326
> feat(connector): [Coinbase] Add order id as the reference id 

- crates/router/src/connector/fiserv/transformers.rs
Update connector_response_reference_id to use gateway_resp.transaction_processing_details.order_id in fiserv transformers.
Fixes #2329
- [x New feature
> feat(connector): [Fiserv] update connector_response_reference_id in transformers

- crates/router/src/connector/nuvei/transformers.rs
`connector_request_reference_id` is being passed as "attempt_id" or "payment_id" to improve consistency in transmitting payment information to the Nuvei payment gateway.
> feat(connector): [Nuvei] Use "connector_request_reference_id" for as "attempt_id" to improve consistency in transmitting payment information

- Cargo.lock
- crates/router_env/Cargo.toml
- crates/router_env/src/logger/setup.rs
This PR includes changes for removing the ansi escape characters from logs when the logs format is set to json
This will help in making the logs much cleaner as opposed to having ansi escape characters in json format
Current log - 
Log due to current PR changes -
> refactor: disable color in reports in json format

- crates/drainer/src/lib.rs
Gracefully shutdown drainer if redis goes down.
If redis goes down drainer won't be able to automatically reconnect to redis after it exhausts max reconnection attempts. So gracefully shutdown drainer and let it reconnect while restart
> feat: gracefully shutdown drainer if redis goes down

- .github/workflows/release-new-version.yml
This PR updates the schedule for the release new version workflow to run at 8 PM IST on Sunday to Thursday, instead of Monday to Friday.
This would allow us to deploy builds in the morning on all weekdays.
`crontab.guru` for the cron expression.
> ci(release-new-version): update schedule to create releases at 8 PM UTC+05:30 every Sunday to Thursday

- crates/router/src/connector/airwallex/transformers.rs
convert expiry year to four digit
> fix(connector): [Airwallex] convert expiry year to four digit

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- crates/router/src/connector/gocardless/transformers.rs
- loadtest/config/development.toml
Config changes for gocardless mandates for becs and sepa
> chore: [GOCARDLESS] env changes for becs and sepa mandates

- crates/router/src/connector/nexinets/transformers.rs
The `connector_response_reference_id` parameter has been set for the Nexi Nets Payment Solutions for uniform reference and transaction tracking.
**Location- router/src/connector/nexinets/transformers.rs**
This PR was raised so that it Fixes #2337 
- **I ran the following command, and all the errors were addressed properly, and the build was successful.**
```bash
cargo clippy --all-features
```
- The code changes were formatted with the following command to fix styling issues.
```bash
cargo +nightly fmt
```
> feat(connector): [NexiNets] Update connector_response_reference_id as reference to merchant

- crates/api_models/src/payouts.rs
- crates/router/src/core/payouts.rs
- crates/router/src/core/utils.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/utils.rs
- openapi/openapi_spec.json
This PR modifies logic used for fetching connector and storing customer's details using a profile_id. This had already been done for the core functionalities, including payments, refunds, etc.
Core PR - https://github.com/juspay/hyperswitch/pull/2020
Move towards using `profile_id` as opposed to `business_label`.
Tested locally
#1 Current State [payouts flow is broken]
#2 Updated State [using profile_id]
> fix: consume profile_id throughout payouts flow

- crates/router/src/connector/nexinets/transformers.rs
For all payment methods, Hyperswitch should transmit a reference to the connector, enabling merchants to subsequently locate the payment within the connector dashboard.
In this PR, such reference is obtained by calling `connector_request_reference_id()` in `RouterData`. The result is then passed as the "merchantOrderId" parameter to the NexiNets API, as per the [official documentation](https://developer.nexigroup.com/payengine/en-EU/api/payengine-api-v1/#orders-post-body-merchantorderid).
Fixes #2307
> feat(nexinets): Use connector_request_reference_id as reference to the connector - Work In Progress 

- crates/router/src/connector/worldline.rs
- crates/router/src/connector/worldline/transformers.rs
This pull request implements the get_currency_unit from the ConnectorCommon trait for the Worldline connector. This function allows connectors to declare their accepted currency unit as either Base or Minor. For Worldline  it accepts currency as Minor units.
1. crates/router/src/connector/worldline.rs
2. crates/router/src/connector/worldline/transformers.rs
Closes #2249
> refactor(connector): [Worldline] Currency Unit Conversion

- crates/api_models/src/webhooks.rs
- crates/common_enums/src/enums.rs
- crates/router/src/compatibility/stripe/webhooks.rs
- crates/router/src/connector/stripe.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/core/webhooks/utils.rs
- crates/router/src/types/transformers.rs
- migrations/2023-10-13-100447_add-payment-cancelled-event-type/down.sql
- migrations/2023-10-13-100447_add-payment-cancelled-event-type/up.sql
- openapi/openapi_spec.json
Add new IncomingWebhookEvent which will handle the payment cancel webhooks.
Map the above event in Stripe.
Processing of cancel webhooks from connector will be supported for stripe.
Testing was carried out using Webhooks
> feat(router): Add Cancel Event in Webhooks and Mapping it in Stripe

- crates/router/src/connector/paypal.rs
- crates/router/src/connector/paypal/transformers.rs
use connector request reference id as reference - invoice id for paypal
webhooks
> feat(connector): [Paypal] use connector request reference id as reference for paypal

- crates/router/src/connector/dlocal/transformers.rs
- [x ] New feature
I have populated the 'id' which is provided as a payment-specific ID in their response to then be populated as 'connector_reference_id'. As per the docs  they don't require a payment reference ID in their payment requests. So populated the existing id.
If it fixes an open issue, please link to the issue here.
It fixes an open issue . Closes #2328 
- [x ] I formatted the code `cargo +nightly fmt --all`
- [x ] I reviewed the submitted code
> feat(connector): [Dlocal] Use connector_response_reference_id as reference to merchant

- crates/router/src/core/payments/transformers.rs
- crates/router/src/core/verification.rs
Earlier we were throwing 2xx even when applepay verification was failing refactored it to throw 4xx
> refactor(router): throw bad request error on applepay verification failure

- crates/storage_impl/src/payments/payment_intent.rs
- updated the kv payment insert to use payment intent instead of payment update enum...
- updated the variable name to provide more context
- Currently we are inserting the payment update enum in kv instead of the updated intent
- This causes bugs down the line when trying to read the values from kv store...
> fix(payments): fix payment update enum being inserted into kv

- crates/router/src/connector/bambora/transformers.rs
The `connector_response_reference_id` parameter has been set for the Bambora Payment Solutions for uniform reference and transaction tracking.
**Location- router/src/connector/bambora/transformers.rs**
This PR was raised so that it Fixes #2324  !
- **I ran the following command, and all the errors were addressed properly, and the build was successful.**
```bash
cargo clippy --all-features
```
- The code changes were formatted with the following command to fix styling issues.
```bash
cargo +nightly fmt
```
> feat(connector): [Bambora] Use connector_response_reference_id as reference to the connector

- crates/router/src/connector/dlocal/transformers.rs
removed all the default case in dlocal and handle all the missing cases
closes #2269
> refactor(connector): [Dlocal] remove default case handling

- crates/router/src/connector/nexinets/transformers.rs
> refactor(router): [Nexi nets] Remove Default Case Handling

- crates/common_utils/src/errors.rs
- crates/common_utils/src/types.rs
- crates/common_utils/tests/percentage.rs
- crates/data_models/src/payments/payment_intent.rs
- crates/diesel_models/src/payment_intent.rs
- crates/storage_impl/src/payments/payment_intent.rs
-> Enabled updating surcharge_applicable in payment_intent.
-> Implemented apply_and_ceil_result() function in Percentage struct
> feat: add support for updating surcharge_applicable field intent

- crates/external_services/src/kms.rs
- crates/router/src/configs/kms.rs
- crates/router/src/configs/settings.rs
- crates/router/src/core/payment_methods/vault.rs
- crates/router/src/routes/app.rs
Add kms decryption for redis_temp_locker_encryption_key . hex decode after kms decrypt.
Kms changes can be tested on integ.
> fix: kms decryption of redis_temp_locker_encryption_key

- crates/router/src/events.rs
- crates/router/src/events/api_logs.rs
- crates/router/src/services/api.rs
- crates/storage_impl/src/payments/payment_attempt.rs
- Add a debug representation of request & response to api event
Adding the request & response to API events would help provide more info about the type of query
> feat(events): Add request body to api events logger

- crates/router/src/connector/shift4/transformers.rs
> refactor(connector): Use connector_response_reference_id  for Shift4

- crates/router/src/routes/payments.rs
- openapi/openapi_spec.json
disable openapi examples to support api reference documentation
> fix(router): disable openapi examples

- crates/api_models/src/refunds.rs
- crates/router/src/core/refunds.rs
- openapi/openapi_spec.json
- postman/collection-dir/stripe/QuickStart/Refunds - Create/event.test.js
We're not passing `profile_id` in Refunds response and it is not being populated in the database as well. This PR aims to fix that.
Fixes a bug.
- Make a Payment through any connector
- Do a refund
- You should be able to see `profile_id` being populated in response and the same should be updated in `refunds` table in database as well
Did a payment through Stripe connector:
```json
{
"payment_id": "pay_aw1wK7Rvpb8iwjvgLKlb",
"merchant_id": "postman_merchant_GHAction_1f531e91-324f-4d43-b18e-c7b981c591be",
"status": "succeeded",
"amount_received": 6540,
"connector": "stripe",
"client_secret": "pay_aw1wK7Rvpb8iwjvgLKlb_secret_kX76Zixn3YVuu7J6c6yp",
"created": "2023-10-20T10:36:07.609Z",
"description": …
```
> fix(refunds): Add `profile_id` in refunds response

- crates/router/src/connector/cryptopay.rs
`connector_request_reference_id` is being pass as reference id which will help in payment retrieval in case of connector timeout. This will not make connector transaction id as mandatory. It will force sync even though connector transaction id is not present.
Test cases - make a payment, update connector_transaction_id with NULL and do a force sync.
> refactor(connector): [Cryptopay] add psync reference id validation for Cryptopay

- .github/workflows/release-new-version.yml
Use `cog bump --patch --dry-run` to get next bump version if `cog bump --auto --dry-run` fails. Also remove prefix 'v' from 'NEW_TAG' as cog bump --version expects only the version number to be passed.
> ci: perform patch bump to get next bump version if auto bump fails

- crates/router/src/connector/tsys/transformers.rs
> refactor(router): tsys default case handling

- crates/router/src/connector/opennode/transformers.rs
Use connector_request_reference_id as reference to the connector #2311
Following are the paths where you can find config files:
1. hyperswitch/crates/router/src/connector/opennode/transformers.rs
To solve inconsistency in RouterData and it solves the Issue #2311 
Need help in doing  test?
> feat(connector): [OpenNode] Use connector_request_reference_id as referemce to connector

- crates/router/src/connector/paypal.rs
Error reason mapping in paypal fails when `description` for error reason is empty string .Because current implementation uses `then_some` , which returns Some(t) if the bool is [true], or None otherwise. So `error_reason` always set to `None` .This pr fixes this issue and set the error reason to paypal's error message if error reason is empty string.
Can't test this if paypal sends empty string in 
`PaypalPaymentErrorResponse -> details -> description `then this will be mapped to `PaypalPaymentErrorResponse-> message` . Although it have same test case as this pr https://github.com/juspay/hyperswitch/pull/2611 to test the previous error mapping .
> fix(connector): [Paypal]fix paypal error reason mapping when it is empty string.

- crates/router/src/connector/dlocal/transformers.rs
…cal connector #2297
Use connector_request_reference_id as reference to the connector #2297 
Provide links to the files with corresponding changes.
Following are the paths where you can find config files:
1. hyperswitch/crates/router/src/connector/Dlocal/transformers.rs
To solve inconsistency in RouterData and it solves the Issue #2297 
Make any Payment for connector Dlocal and see that you are getting "reference_id" field in the logs of payment request.
> feat(connector): [Dlocal] Implement feature to use connector_request_reference_id as reference to the connector

- CHANGELOG.md
This PR fixes the typo in the CHANGELOG.md file by replacing `referemce` with `reference`.
Fix typo
With this PR getting merged, spell checks should pass.
> docs(changelog): Fix typo in changelog

- CHANGELOG.md
- crates/router/src/connector/iatapay/transformers.rs
fixes #2302 
Make any Payment for connector Iatapay and see that you are getting "reference_id" field in the logs of payment request.
> refactor(connector): Use connector_request_reference_id for Iatapay

- crates/router/src/connector/nmi/transformers.rs
Add orderid with value of connector_request_reference_id in NMI transformers.
Fixes #2306
Make any Payment for connector NMI and see that you are getting "reference_id" field in the logs of payment request.
> feat(connector): [NMI] add orderid to PaymentRequest

- crates/router/src/connector/worldline/transformers.rs
https://github.com/juspay/hyperswitch/issues/2351
Make any Payment for connector Worldline and see that you are getting "reference_id" field in the payments response of hyperswitch. It should not be null.
> feat(connector):  Worldline Use `connector_response_reference_id` as reference to merchant

- crates/data_models/src/payments/payment_intent.rs
- crates/storage_impl/src/mock_db/payment_intent.rs
- crates/storage_impl/src/payments/payment_intent.rs
Remove redundant implementation of apply_changeset for payment intent.
This fixes fields like description,statement_descriptor being null in PaymentsConfirm response. Issue was caused by some fields not being populated inside apply_changeset while creating the object.
- Create Payment with confirm=false
```
--header 'api-key: dev_e03Q912SkJBWBG0LCkkaqcjluJD0DZGiLc1UjrLVuCCsqca0FjI2PZ9cKWwzlcDO' \
--data-raw '{
"amount": 600,
"customer_id": "HScustomer1234",
"email": "p143@example.com",
"amount_to_capture": 600,
"capture_on": …
```
> fix: null fields in payments respose

- postman/collection-dir/stripe/MerchantAccounts/.meta.json
Since `Merchant Account - List` is not in `meta.json`, it had a different behavior of moving to the top and resulting in it throwing 404.
Fix unintended behavior
> ci(postman): Fix collection throwing 404

- crates/router/src/connector/aci.rs
- crates/router/src/connector/aci/transformers.rs
> feat(connector): [ACI] Currency Unit Conversion

- .github/workflows/pr-title-check.yml
This pr uses env input form GitHub to prevent the command injection vulnerability.
> ci: use `env` input to fix the command injection vulnerability

- crates/diesel_models/src/schema.rs
- crates/router/src/core/payments/operations/payment_response.rs
…ment_intent
- [ x] Refactoring
group connector_response, payment_attempt db update calls with payment_intent
make db calls concurrent to improve api latency
compare values of updated objects with db update returned object if they match
print connector_response in payment intent and connector_response returned from awaiting db update and compare
in payment confirm api
`curl --location --request POST 'http://localhost:8080/payments/pay_xNnINZf39jNKoFPoHJ0B/confirm' \
--header 'api-key: ***' \
--data-raw ' {}'`
> refactor: #3059 group db update calls

- config/development.toml
Update the pm_filters of Klarna in Stripe to include some more countries and currencies.
https://github.com/juspay/hyperswitch/pull/2807
> refactor(config): update payment method filter of Klarna in Stripe

- crates/test_utils/src/newman_runner.rs
I previously used debug which messed up the whole thing that forced custom headers to not work. Now that, it should work as expected by not "stringifying" the commands.
Previously, custom headers were in string format since debug was used to display.
Before: `"pm.request.headers.add({{key: \"{key}\", value: \"{value}\"}});"`
After (with this PR): `pm.request.headers.add({{key: "{key}", value: "{value}"}});`
Fixes custom headers.
Ran the collection with added custom-headers and verified that to be working.
> ci(rustman): Fix Rustman custom headers

- crates/router/src/connector/noon.rs
add `validate_psync_reference_id` implementation for Noon as we can make a Psync using `connector_request_reference_id` and currently core is defaulting if `connector_transaction_id` is not present it fails the Psync.
Can't be reproduced in envs as either a timeout is required or would need to delete the connector_transaction_id in the DB.
Check for regular proper working of Psyncs in all the cases.
> fix(connector): [noon] add validate psync reference

- crates/router/src/core/payment_link/payment_link.html
- Fix bug for not allowing the SDK to render for PaymentIntent status `requires_payment_method`
- Remove modern JS features (ES6 and ES6+) to support older browsers
Test Case
use the curl below to generate payment_link and check whether the payment link is opening test few transactions aswell
`curl --location 'https://sandbox.hyperswitch.io/payments' \
--header 'api-key: snd_RrnVYK6c3puJkhYm3seCFACIpJuKjG5ZkydUP9fbPFAqVYiYCaSgQXqYQLsTwMUM' \
--data '{
"amount": 3423,
"customer_id": "sahkal",
"return_url":"https://google.com",
"description": "For selling Tea",
"order_details":[{
"product_name":"Tea",
"quantity":1,
"amount":10, …
> fix(payment_link): render SDK for status requires_payment_method

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
Can be tested on sandbox by seeing we the Payment method create request to basilisk is returning 200 response.
> fix(router): add choice to use the appropriate key for jws verification

- crates/router/src/connector/bankofamerica/transformers.rs
When doing a psync call on connector bankofamerica, connector response deserialization is failing
https://github.com/juspay/hyperswitch-cloud/issues/3264
PSYNC flow needs to be tested for Cards Non-3DS flow in connector BankOfAmerica.
> feat(connector): [BANKOFAMERICA] PSYNC Bugfix

- crates/router/src/core/admin.rs
Previously the check for `disabled` in `mca_create` and `mca_update` is matching on false instead of true. This PR fixes it.
Postman.
Same test cases as #2883.
> fix(mca): Change the check for `disabled` field in mca create and update

- crates/router/src/core/locker_migration.rs
- crates/router/src/core/payment_methods/cards.rs
This pr is to have a change that will migrate payment_method_data to rust locker only is the payment_method is crad. This change is required because only cards were added to Basilisk HS.
Also this includes changes to just log error instead of propagating it if add card to rust locker fails, this is done as part of fallback where we will be adding the card to Basilisk HS also.
https://github.com/juspay/hyperswitch/pull/2929
VAS compiling for `v1.74.0`
Make a request with the below curl for a merchant_id which has saved card and also some other payment method saved. After the migration it should just migrate payment method data for only cards this can be verified by api response which gives the number of cards moved.
```
curl --location --request POST …
```
> feat(router): migrate `payment_method_data` to rust locker only if `payment_method` is card

- crates/data_models/src/payments/payment_attempt.rs
- crates/diesel_models/src/payment_attempt.rs
- crates/router/src/connector/utils.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_capture.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/payments/retry.rs
- crates/router/src/types.rs
- crates/router/src/workflows/payment_sync.rs
- crates/storage_impl/src/payments/payment_attempt.rs
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario1-Create payment with confirm true/Payments - Create/request.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario11-Refund recurring payment/Recurring Payments - Create/request.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario27-Create a failure card payment with confirm true/Payments - Create/request.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario27-Create payment without customer_id and with billing address and shipping address/Payments - Create/request.json
Original PR: https://github.com/juspay/hyperswitch/pull/2802
Hotfix branch PR for this Main branch PR https://github.com/juspay/hyperswitch/pull/2915
Currently, for a connector that returns `processing` status for full manual capture, if Psync is done later, status would always go from `processing` to `partially_captured` instead of `succeeded`.
1. Create a merchant
2. Create a connector that returns `processing` status for single full capture. Then later gives `succeeded` after some time.
3. Create a payment with confirm = true and capture_method = manual.
4. Capture the payment fully. (status should be `processing`)
5. later do force sync. (status should be `succeeded`)
> fix: status goes from pending to partially captured in psync

- crates/api_models/src/payments.rs
- crates/router/src/connector/utils.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/refunds.rs
- crates/router/src/types.rs
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario12-BNPL-klarna/Payments - Create/request.json
Amount captured would go to 0 for 3ds payments( payments that require redirection ).
Manual
> fix: amount_captured goes to 0 for 3ds payments

- config/docker_compose.toml
- crates/drainer/src/lib.rs
- crates/drainer/src/utils.rs
Increment jobs picked only when stream is not empty
Currently we are incrementing `jobs_picked` whenever we try to read a stream which gives the wrong notion that drainer is picking the job in every stream read. So only increment `jobs_picked` when stream is not empty.
- Do a payment with KV Merchant.
- Run on data source VM-Single
```
router_CYCLES_COMPLETED_SUCCESSFULLY_total
router_CYCLES_COMPLETED_UNSUCCESSFULLY_total
```
- Check if `router_CYCLES_COMPLETED_SUCCESSFULLY_total` and `router_CYCLES_COMPLETED_UNSUCCESSFULLY_total` both are increasing
> fix(drainer): increase jobs picked only when stream is not empty

- crates/router/src/connector/prophetpay/transformers.rs
- Replaced connector_request_reference_id with refund_id for refund.
- Removed response_code since we are not receiving it in case of failure
- Made tranSeqNumber optional
Closes [#3353](https://github.com/juspay/hyperswitch-cloud/issues/3353)
- Craete a payment through Prophetpay Card Redirect
- If it is successful, go the refund
- The refund must be successful
> fix(connector): [Prophetpay] Use refund_id as reference_id for Refund

- crates/router/src/core/payment_methods/cards.rs
This PR includes changes for returning None instead of Err when payment method data itself is empty in case of bank debit during list customer payment method api
This PR cannot be tested unless we have plaid feature
> fix: return none instead of err when payment method data is not found for bank debit during listing

- crates/router/src/connector/prophetpay/transformers.rs
- crates/router/src/core/errors/utils.rs
In case of refund, error was not being propagated specially for "not implemented error"
- Create a payment through Prophetpay
- Create a refund partial to the amount of the payment
- Should throw the given error
> fix(core): Error propagation for not supporting partial refund

- crates/router/src/core/refunds.rs
mark refund status as failure for not_implemented error from connector flows
1. Do a payment with connector prophetpay
2. Perform a partial amount refund to see a 4xx error
3. Check the refund status, it should be failure
> fix(router): mark refund status as failure for not_implemented error from connector flows

- crates/router/src/analytics/routes.rs
- crates/router/src/consts.rs
- crates/router/src/consts/user.rs
- crates/router/src/core/user.rs
- crates/router/src/routes/admin.rs
- crates/router/src/routes/api_keys.rs
- crates/router/src/routes/disputes.rs
- crates/router/src/routes/files.rs
- crates/router/src/routes/mandates.rs
- crates/router/src/routes/payment_link.rs
- crates/router/src/routes/payments.rs
- crates/router/src/routes/refunds.rs
- crates/router/src/routes/routing.rs
- crates/router/src/routes/verification.rs
- crates/router/src/services.rs
- crates/router/src/services/authentication.rs
- crates/router/src/services/authorization.rs
- crates/router/src/services/authorization/info.rs
- crates/router/src/services/authorization/permissions.rs
- crates/router/src/services/authorization/predefined_permissions.rs
This PR adds required permissions for all APIs using JWT related auth types and a permission module which can be used to control the permissions.
To support user roles and permissions.
Postman.
The following APIs now use authorization (These routes cannot be called without having required permissions in the JWT Token).
1. Analytics
a. Get Payment Metrics: `/analytics/v1/metrics/payments`
b. Get Refund Metrics: `/analytics/v1/metrics/refunds`
c. Get Payment Filters: `/analytics/v1/filters/payments`
d. Get Refund Filters: `/analytics/v1/filters/payments`
2. Admin
a. Merchant Account - Retrieve: `/accounts/{id}`
b. Merchant Account - Update: `/accounts/{id}`
c. Payment Connector - Create: `/account/{merchant_id}/connectors`
d. Payment Connector - Retrieve: …
> feat(auth): Add Authorization for JWT Authentication types

- crates/storage_impl/src/payments/payment_attempt.rs
This adds prefix to `connector_transaction_id` and `preprocessing_id` while inserting to reverse lookup.
For some connectors like `cashtocode` the `connector_transaction_id` is same as `payment_attempt_id` it causes duplication in reverse lookup. So add a prefix to the `connector_transaction_id` to fix it.
- Payments with CashtoCode
```
--header 'api-key: dev_RBXd1eGsgx19XwbcRPyr3xxHlnhrIBfPBE9VhsZrbvmQhfVWgNzER0Kp2gl4NhBW' \
--data-raw '{
"payment_id":"pay_1700832163",
"customer_id": "e064f3fe-a027-458a-a373-09eb38122b67", …
```
> fix: add prefix to connector_transaction_id

- .github/workflows/release-new-version.yml
This PR updates the credentials used for generating token in release new version workflow
> CI: update the credentails for generating token in release new version workflow

- crates/cards/src/validate.rs
- crates/common_utils/src/pii.rs
- crates/masking/src/secret.rs
- crates/masking/src/strategy.rs
as per #1973
Use empty enums as strategy type parameter, instead of unit structs, to prevent instantiation. 
no
#1973
`cargo clippy --all-features`
Assuming existing tests should catch side effects if any.
> refactor(masking): use empty enums as masking:Strategy<T> types

- crates/data_models/src/payments/payment_attempt.rs
- crates/diesel_models/src/query/payment_attempt.rs
- crates/router/src/core/refunds.rs
- crates/storage_impl/src/mock_db/payment_attempt.rs
- crates/storage_impl/src/payments/payment_attempt.rs
Currently, payment refund would only happen when intent status is `succeeded`(full capture).
With this change, it would be possible to refund the payment even when if is `partially captured`
Manual
1. Create merchant with stripe connector.
2. Create a payment with confirm = true, capture = manual
3. Later, partially capture the payment ("amount_to_capture < amount"). (status changes to `partially_captured`)
4. Then do a refund on the above payment for the captured amount.
> feat(core): enable payment refund when payment is partially captured

- crates/api_models/Cargo.toml
- crates/common_enums/Cargo.toml
dummy connector is enabled by default in common enums . This pr disables the dummy connector in common enums .
by running `make hack` and `cargo check --no-default-features ` succesfully .
> fix: remove `dummy_connector` from `default` features in `common_enums`

- crates/router/src/core/payments/helpers.rs
This PR removes the error propagation if card name not found in locker in case of temporary token. Instead asks during confirm flow
1. Make a payment with saving the card. pass card_holder_name empty while saving
```
--header 'api-key: dev_u67d5zdpJVfHQ5jRhWXNg5F0Wy8MhzG2STAeHBhIKJowJJxAuVtvwhB2lsL427C8' \
--data-raw '{ …
```
> fix: remove error propagation if card name not found in locker in case of temporary token

- crates/diesel_models/src/business_profile.rs
- crates/diesel_models/src/capture.rs
- crates/diesel_models/src/payment_attempt.rs
- crates/diesel_models/src/payment_intent.rs
- crates/diesel_models/src/refund.rs
In `fn apply_changeset()` function, which is being used in KV for applying the changed fields was not updating all the fields.
Fixed it.
Cannot be tested in local
> fix: few fields were not getting updated in apply_changeset function

- crates/router/src/core/refunds.rs
Only the message body was being saved on refund update but now the whole error will be stored.
Create a payment through Prophet pay:
`{
"payment_method": "card_redirect",
"payment_method_type": "card_redirect",
"card_redirect": {
"card_redirect": {}
}
},
"routing": {
"type": "single",
"data": "prophetpay"
}
}`
If the transaction is successful, create a partial refund (amount must be less than the total amount of transaction).
The response of the refund request should be: 
```
{
"error": {
"message": "Partial Refund is not implemented",
"code": "IR_00"
}
}
```
Do a …
> fix(core): Error message on Refund update for `Not Implemented` Case

- crates/router/src/connector/stax/transformers.rs
Resolves #2862
No test cases required. As In this PR only error message have been changed from Not Supported error message to NotImplemented error message.
> refactor(connector): [Stax] change error message from NotSupported to NotImplemented

- crates/router/src/routes/app.rs
- Allow kms decryption for Analytics SQLX password when the kms feature flag is enabled
- run it with the KMS feature flag & provide kms encrypted values
> fix(config): add kms decryption support for sqlx password

- crates/api_models/src/payment_methods.rs
- crates/api_models/src/payments.rs
- crates/api_models/src/surcharge_decision_configs.rs
- crates/common_utils/src/types.rs
- crates/diesel_models/src/payment_intent.rs
- crates/router/src/core/payment_methods/surcharge_decision_configs.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_update.rs
- crates/router/src/core/payments/types.rs
- crates/router/src/core/utils.rs
- crates/router/src/types.rs
- crates/router/src/types/api.rs
Changes in this PR:
1. Renamed and restructured a few existing enums and structs
2. Introduced new `SurchargeDetails` struct for use in core and `SurchargeDetailsResponse` struct for api response.
3. Surcharge details validation during payment_confirm shall only be made if surcharge_details is sent during confirm call. Not otherwise.
4. Added amount validation is payment create and payment update flow, to cover surcharge.
Steps to test:
1. Create a merchant with paypal connector
2. Configure some surcharge rules for the merchant
3. Create a payment
4. Do merchant payment_method list. (should get below body in `surcharge_details` field)
```
"surcharge_details": {
"surcharge": {
"type": "fixed",
"value": 123
},
"tax_on_surcharge": {
"percentage": 5.09
},
"display_surcharge_amount": 1.23, …
```
> refactor: create separate struct for surcharge details response

- scripts/add_connector.sh
transform connector name to lowercase in the add_connector script.
created a new connector and discarded it works. Need not to be tested by QA
> fix: transform connector name to lowercase in connector integration script

- crates/test_utils/README.md
Update postman documentation since we had previously made some changes w.r.t how the postman commands are passed.
I don't want to make people scream if it does not work.
This command should fail to run postman tests
```sh
cargo run --package test_utils --bin test_utils -- --connector_name=<connector_name> --base_url=<base_url> --admin_api_key=<admin_api_key>
```
This command should run postman tests as expected.
```sh
cargo run --package test_utils --bin test_utils -- --connector-name=<connector_name> --base-url=<base_url> --admin-api-key=<admin_api_key>
```
> docs(test_utils): Update postman docs

- crates/router/src/core/payments/helpers.rs
This PR removes the error propagation if card name not found in locker. Instead asks during confirm flow
Original PR - https://github.com/juspay/hyperswitch/pull/2998
> fix: remove error propagation if card name not found in locker

- crates/router/src/core/payment_methods/cards.rs
This PR updates the List Payment Method core filters to allow payment intents with zero amount
Payment intents with zero amount are created for setting up a mandate with the connector and thus are a valid form of connector call.
1. Create a Merchant Account, 1 Merchant Connector Account
2. Create a payment with amount = 0, confirm = false & no payment method given
3. Do a list payment methods call. The returned list should include all the eligible payment methods despite the amount being 0.
> fix(router): allow zero amount for payment intent in list payment methods

- crates/api_models/src/events/user.rs
- crates/api_models/src/user.rs
- crates/router/src/core/errors/user.rs
- crates/router/src/core/user.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/lock_utils.rs
- crates/router/src/routes/user.rs
- crates/router_env/src/logger/types.rs
This PR adds a new route `/verify_email_request` which will send verify email to the new user.
To support the user verification process.
Postman with SES.
```
curl --location 'http://localhost:8080/user/verify_email_request' \
--data-raw '{
"email": "email"
}'
```
> feat(users): Add resend verification email API

- crates/data_models/src/payments.rs
- crates/data_models/src/payments/payment_intent.rs
- crates/diesel_models/src/payment_intent.rs
- crates/diesel_models/src/schema.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/core/utils.rs
- migrations/2023-12-07-075240_make-request-incremental-auth-optional-intent/down.sql
- migrations/2023-12-07-075240_make-request-incremental-auth-optional-intent/up.sql
make `request_incremental_authorization` optional in payment_intent for backward compatibility
1. make request_incremental_authorization false in payments request, to see incremental_authorization allowed as false in payments response. when incremental authorization is tried for this payment, it fails with not allowed error
2. make request_incremental_authorization true, to see incremental_authorization_allowed in the response. Then try to attempt incremental_authorization api to see successfully calling the connector
> fix(router): make `request_incremental_authorization` optional in payment_intent

- crates/router/src/connector/trustpay.rs
- crates/router/src/connector/trustpay/transformers.rs
make paymentId optional field as it is not always sent by the connector in the request body, so it is causing deserialization errors.
Test Webhooks for Trustpay end to end from receiving to triggering outgoing webhook
> fix(connector): [trustpay] make paymentId optional field

- crates/router/src/configs/settings.rs
> fix(api_locking): fix the seconds and millis mismatch while fetching configuration

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- crates/router/src/configs/defaults.rs
- crates/router/src/connector/helcim/transformers.rs
The payments in Helcim will contain an invoice number which will be equal to the connector_request_reference_id.
https://github.com/juspay/hyperswitch-cloud/issues/3553
Test Cards-Non3DS Payments(Manual & Automatic) for Helcim.
```
{
"amount": 211,
"card": {
"card_number": "5413330089099130",
"card_exp_year": "27",
"card_cvc": "123",
"card_holder_name": "John Doe"
}
},
"user_agen": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36",
"accept_header": …
```
> feat(connector): [HELCIM] Add connector_request_reference_id in invoice_number 

- crates/router/src/core/payment_methods/transformers.rs
- remove double serialization for locker requests
- fixes invalid request bodies for locker calls
> fix(locker): fix double serialization for json request

- crates/router/src/core/payments.rs
Add outgoing webhook when payment suceedes or fails.
To inform the merchant / upstream about payment status asynchronously
- Create a payment -> succeedes -> check whether a webhook was received on webhook site.
> feat(payments): add outgoing payments webhooks

- crates/router/src/configs/defaults.rs
- crates/router/src/connector/cybersource/transformers.rs
Implement Payment Method Google Pay for connector Cybersource
https://github.com/juspay/hyperswitch-cloud/issues/3672
Authorize(Manual+Automatic), Capture and PSYNC flow needs to be tested for Payment Method Google Pay for connector Cybersource
```
--data-raw '{
"amount": 900, …
```
> feat(connector): [CYBERSOURCE] Implement Google Pay

- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/cybersource/transformers.rs
Cybersource status mapping requires update.
Separate the handle_response try_from's for different flows.
https://github.com/juspay/hyperswitch-cloud/issues/3226
Authorize(Manual+Automatic), Capture, PSYNC, Refunds and RSYNC flow needs to be tested for Payment Method Cards for connector Cybersource
1. Authorize: 
`{
"amount": 100,
"email": "bernard.eugine@juspay.in",
"return_url": "https://google.com/",
"card": {
"card_number": "4111111111111111",
"card_exp_month": "12",
"card_exp_year": "30",
}
},
"billing": {
"address": {
"line1": …
> fix: [CYBERSOURCE] Fix Status Mapping

- crates/router/src/configs/defaults.rs
- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/cybersource/transformers.rs
Implement Payment Method Apple Pay for connector Cybersource
https://github.com/juspay/hyperswitch-cloud/issues/3673
This is an apple pay pr and proper testing will be carried out directly on sandbox.
> feat(connector): [CYBERSOURCE] Implement Apple Pay

- crates/router/src/connector/bankofamerica.rs
- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/cybersource/transformers.rs
The field reason in struct BankOfAmericaErrorResponse/ ErrorResponse(in cybersource) will be handled as a string instead of handling it as an enum. The reason for this is the absence of proper documentation for error reason at the connector's end.
Authentication error will also be handled properly now.
https://github.com/juspay/hyperswitch-cloud/issues/3682
1. Try to create a payment by passing `billing.last_name` as an empty string. You should be then able to successfully generate an error.
```
--data-raw '{
"amount": 100,
"email": …
```
> fix(connector): [BOA/CYBERSOURCE] Update error handling

- crates/euclid_wasm/src/lib.rs
Add the wasm function to retrieve keys for the 3DS and surcharge decision manager.
The 3DS decision manager uses a restricted set of keys that's supported by the Euclid framework, which needs a function in the wasm for usage in the dashboard. This PR adds that function.
Local testing, compiler-guided
> fix(euclid_wasm): add function to retrieve keys for 3ds and surcharge decision manager

- crates/router/src/connector/nmi/transformers.rs
customer_vault_id was a mandatory field during deserialization but on error, the connector would through 2xx with failed response which couldn't be deserialized because of this.
Tested it through postman:
- Create connector(NMI) using wrong credentials
`{
"connector_name": "nmi",
"api_key": "X5e7Y5ArqrQm2WSm2pBdS3r2ZEmWNfQ",
"key1": "checkout_public_Pd6pb49339et5JNyh67ctctS2FS7XtBt"
},
{
{
"Visa",
"Mastercard"
],
},
{ …
> fix(connector): [NMI] Fix response deserialization for vault id creation

- crates/router/src/core/user.rs
- crates/router/src/utils/user.rs
This PR changes switch merchant api so that it sends correct merchant_id, org_id and role_id in the response.
curl --location 'http://localhost:8080/user/switch_merchant' \
--data '{
"merchant_id": "merchant_1702984450"
}'
Response should be like this
```
{
"token": "JWT",
"merchant_id": "merchant_1702984450",
"name": "name",
"email": "email",
"verification_days_left": null,
"user_role": "org_admin"
}
```
This token and response should have same values in the attributes.
> fix(users): send correct `user_role` values in `switch_merchant` response

- crates/router/src/connector/nmi.rs
- crates/router/src/connector/nmi/transformers.rs
- Includes webhook for payment as well as refund
- Includes refactoring of sync using reference id
`{
"address": {
}
},
"return_url": …
> feat(connector): [NMI] Implement webhook for Payments and Refunds

- crates/router/src/routes/webhooks.rs
add logger for incoming webhook payload. Now, the Webhook payload will be logged in Loki along with its complete body inserted in the api events table.
test case - make a test payment, its webhook should be logged in Loki, and in api events table, both complete payload as well as the parsed body should be there.
> fix(events): add logger for incoming webhook payload

- crates/router/src/connector/aci/transformers.rs
- crates/router/src/connector/bambora/transformers.rs
- crates/router/src/connector/braintree/braintree_graphql_transformers.rs
- crates/router/src/connector/dlocal/transformers.rs
- crates/router/src/connector/dummyconnector/transformers.rs
- crates/router/src/connector/forte/transformers.rs
- crates/router/src/connector/mollie/transformers.rs
- crates/router/src/connector/noon/transformers.rs
- crates/router/src/connector/opayo/transformers.rs
- crates/router/src/connector/payeezy/transformers.rs
- crates/router/src/connector/paypal/transformers.rs
- crates/router/src/connector/powertranz/transformers.rs
- crates/router/src/connector/rapyd/transformers.rs
- crates/router/src/connector/shift4/transformers.rs
- crates/router/src/connector/stax/transformers.rs
- crates/router/src/connector/worldline/transformers.rs
This PR includes changes for sending the `card_holder_name` as an empty string if not sent during confirm or not present in locker
1. Create a noon merchant connector account
2. Create a payment without `card_holder_name`
```
--header 'api-key: dev_ZBWUNGf7TfqeTnt5VsSYyonTiN3Ohdw4JoEba8frZPmKYaHu9tLLBbMPqmhJcIJl' \
--data-raw '{ …
```
> refactor(payment_methods): make the card_holder_name as an empty string if not sent

- crates/router/src/core/payments/helpers.rs
fix payment status for 4xx
Through Postman and checked the Status in DB
1. With confirm call true
2. With confirm call False
> refactor(core): fix payment status for 4xx

- crates/router/src/connector/bankofamerica.rs
- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/core/payments/operations/payment_response.rs
A 5xx error from connector BOA will lead to payment status failing instantaneously.
https://github.com/juspay/hyperswitch-cloud/issues/3699
Generate a 5XX payment using BOA (card no: 3566111111111113) and you should get payment status as failed.
> feat(connector): [BOA] Handle BOA 5XX errors

- .github/workflows/CI-pr.yml
- .github/workflows/CI-push.yml
- .github/workflows/auto-release-tag.yml
- .github/workflows/connector-sanity-tests.yml
- .github/workflows/connector-ui-sanity-tests.yml
- .github/workflows/conventional-commit-check.yml
- .github/workflows/create-hotfix-branch.yml
- .github/workflows/create-hotfix-tag.yml
- .github/workflows/hotfix-pr-check.yml
- .github/workflows/manual-release.yml
- .github/workflows/migration-check.yaml
- .github/workflows/postman-collection-runner.yml
- .github/workflows/pr-title-spell-check.yml
- .github/workflows/release-new-version.yml
- .github/workflows/validate-openapi-spec.yml
- crates/api_models/src/enums.rs
- crates/router/src/configs/defaults.rs
- crates/router/src/connector/bankofamerica.rs
- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/checkout/transformers.rs
- crates/router/src/connector/powertranz/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments/operations/payment_method_validate.rs
- crates/router/src/core/payments/operations/payment_response.rs
- openapi/openapi_spec.json
I have cherry-picked the following commits for production deployment:
1. https://github.com/juspay/hyperswitch/pull/2934
2. https://github.com/juspay/hyperswitch/pull/2940
3. https://github.com/juspay/hyperswitch/pull/2969
4. https://github.com/juspay/hyperswitch/pull/3014
5. https://github.com/juspay/hyperswitch/pull/3061
6. https://github.com/juspay/hyperswitch/pull/3156 (Only BOA changes from this PR 3156)
Production hotfix
The following payment methods need to be tested for Bank of America
1. Cards-NON-3DS
2. Google Pay
3. Apple Pay
The following flows need to be tested for each of the above payment method.
- Authorize
- Capture
- PSYNC
- VOID
- Refunds
- RSYNC
> feat(connector): [BOA] Add GPAY, ApplePay and other fixes

- crates/router/src/connector/aci.rs
- crates/router/src/connector/airwallex.rs
- crates/router/src/connector/bambora.rs
- crates/router/src/connector/bankofamerica.rs
- crates/router/src/connector/checkout.rs
- crates/router/src/connector/dummyconnector.rs
- crates/router/src/connector/globalpay.rs
- crates/router/src/connector/helcim.rs
- crates/router/src/connector/iatapay.rs
- crates/router/src/connector/multisafepay.rs
- crates/router/src/connector/noon.rs
- crates/router/src/connector/opayo.rs
- crates/router/src/connector/paypal.rs
- crates/router/src/connector/shift4.rs
- crates/router/src/connector/stripe.rs
- crates/router/src/connector/worldpay.rs
- crates/router/src/connector/zen.rs
Remove set_body method for connectors implementing default get_request_body
> fix(connector): Remove set_body method for connectors implementing default get_request_body

- crates/api_models/src/payments.rs
- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/connector/payme/transformers.rs
- crates/router/src/connector/trustpay/transformers.rs
- crates/router/src/core/payments/flows/session_flow.rs
This pr contains the changes to make the billing country for apple pay as optional field. In this case if a billing country is not passed in the payments create call the session call would still be done and the billing country would be collected form sdk during the payments confirm.
Test Case :-
This flow needs to be tested for stripe (Manual and simplified flow), trustpay, bluesanp, payme and any important connectors for which apple pay is implemented.
1) Create a apple pay payment with confirm false without apple the country in billing address
2) Make a Session token call. Expected behaviour is response should contain session token for apple pay with the country_code as null.
> feat(router): make the billing country for apple pay as optional field

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
BOA and cybersource only accept maximum administrative_area length of 20 which is handled by truncating the input state length.
https://github.com/juspay/hyperswitch-cloud/issues/3708
Testing can be done by creating a payment by passing states as 'Andaman and Nicobar Islands'
> fix(connector): [BOA/Cyb] Truncate state length to <20

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
Handle 2XX Failures by showing proper error response in payments response.
https://github.com/juspay/hyperswitch-cloud/issues/3709
Testing can be done by creating a failure payment using following card `412345678912345678914`. You should get the following error_message in payments response.
> fix(connector): [BOA] Display 2XX Failure Errors

- crates/router/src/connector/cybersource/transformers.rs
Handle 2XX Failures by showing proper error response in payments response.
https://github.com/juspay/hyperswitch-cloud/issues/3709
Testing can be done by creating a failure payment using following card `412345678912345678914`. You should get the following error_message in payments response.
> fix(connector): [CYBERSOURCE] Display 2XX Failure Errors

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
For connectors BOA and Cybersource the connector_transaction_id should be populated for error response payments.
Also new introduced payment status' from https://developer.cybersource.com/content/dam/cybsdeveloper2021/responsecode.json.
https://github.com/juspay/hyperswitch-cloud/issues/3710
Testing can be done by creating a failure payment by using card `412345678912345678914` and you should see the `connector_transaction_id` in payments response of the failed payment.
> feat(connector): [BOA/CYBERSOURCE] Populate connector_transaction_id

- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/cybersource/transformers.rs
The following features have been implemented for the connector Cybersource:
- Apple Pay - Manual Flow
- Explicit handling of connector 5XX response
- Using Authorization Reversal endpoint to Void a transaction
- Passing payment metadata from merchant to connector using `merchant_defined_information` field
https://github.com/juspay/hyperswitch-cloud/issues/3719
https://github.com/juspay/hyperswitch-cloud/issues/3721
https://github.com/juspay/hyperswitch-cloud/issues/3722
https://github.com/juspay/hyperswitch-cloud/issues/3723
1. Apple pay testing was carried out using postman
2. Generate a 5XX payment using BOA (card no: 3566111111111113) and you should get payment status as failed.
3. Check void flow for manual authorized payment for cybersource:
``` …
```
> feat(connector): [CYBERSOURCE] Refactor cybersource

- crates/router/src/middleware.rs
This adds a log line in the middleware tracking and logging any received request-id in the process. Allow the logs to be linked when multiple services are composed and request id is sent between them
> fix(middleware): add support for logging request-id sent in request

- config/development.toml
- crates/router/src/connector/cybersource/transformers.rs
- crates/router/src/core/payments.rs
- [fix]: Recurring Payments via Wallets
- [feat]: Implement zero dollar mandates and recurring payments via wallets
- [refactor]: Update the mandate token created with cybersource from `instrumentIdentifier` to `PaymentInstrument`
- Create a Merchant and an Mca for cyberource
- Make a setup mandate payment for card and also for wallet
- Make a recurring mandate payment for card and also google_pay 
- The payment should succeed
- Test both zero and non-zero mandate creation
> fix(core): fix recurring mandates flow for cyber source

- crates/router/src/utils/user/dashboard_metadata.rs
- migrations/2024-01-04-121733_add_dashboard_metadata_key_integration_completed/down.sql
- migrations/2024-01-04-121733_add_dashboard_metadata_key_integration_completed/up.sql
- Bug Fix: Add support for integration_completed enum in DB side
- Throw 500 for the enums which are not present in dashboard metadata key type in db
To get integration_completed
```
curl --location --request GET 'http://localhost:8080/user/data?keys=IntegrationCompleted' \
--data '
'
```
Response:
```
[
{
"IntegrationCompleted": false
}
]
```
To set integration_completed, response will be 200 
```
curl --location 'http://localhost:8080/user/data' \
--data '
"IntegrationCompleted"
'
```
And if we again call Get, response will be
```
[
{
"IntegrationCompleted": true
}
]
```
> fix(user): add integration_completed enum in metadata type

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
- crates/router/src/types/api/verify_connector.rs
- crates/router/tests/connectors/aci.rs
- crates/router/tests/connectors/adyen.rs
- crates/router/tests/connectors/bitpay.rs
- crates/router/tests/connectors/cashtocode.rs
- crates/router/tests/connectors/coinbase.rs
- crates/router/tests/connectors/cryptopay.rs
- crates/router/tests/connectors/opennode.rs
- crates/router/tests/connectors/utils.rs
- crates/router/tests/connectors/worldline.rs
We need to populate the merchant_defined_information for each payment with data coming from merchant in payment requests metadata.
Testing can be done by creating a card/gpay/applepay payment and by passing the following metadata in PAYMENTS-CREATE:
"metadata": { "count_tickets": 1, "transaction_number": "5590043" }
You should then be able to see the metadata on BOA dashboard for that payment:
Screenshot 2023-12-26 at 8 34 14 PM
> feat(connector): [BOA] Populate merchant_defined_information with metadata

- crates/common_utils/src/request.rs
- crates/kgraph_utils/src/mca.rs
- crates/masking/src/diesel.rs
- crates/masking/src/serde.rs
- crates/redis_interface/src/lib.rs
- crates/router/src/configs/settings.rs
- crates/router/src/connector/braintree/braintree_graphql_transformers.rs
- crates/router/src/connector/checkout/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/connector/wise.rs
- crates/router/src/core/fraud_check.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/db/dispute.rs
- crates/router/src/macros.rs
- crates/router/src/middleware.rs
- crates/router/src/services/api.rs
- crates/router/src/types/api/connector_onboarding/paypal.rs
- crates/router/src/types/storage.rs
- crates/router/src/types/storage/query.rs
- crates/router/src/utils.rs
- crates/router/src/utils/user/sample_data.rs
- crates/router/tests/connectors/utils.rs
- crates/scheduler/src/consumer.rs
- crates/scheduler/src/producer.rs
- postman/collection-dir/checkout/Flow Testcases/QuickStart/Payment Connector - Create/request.json
This PR addresses the clippy lints occurring due to new rust version 1.75
> chore: address Rust 1.75 clippy lints

- crates/router/src/connector/nmi.rs
- crates/router/src/connector/nmi/transformers.rs
- In ErrorResponse, the reason and connector_transaction_id were not being populated even though we were receiving transaction_id from the connector for failed response.
- connector_response_reference_id were not being populated to reference transaction in merchant dashboard
For testing if connector_response_reference_id being filled, make a payment through NMI in postman:
`{
"amount_to_capture": 2000, …
> fix(connector): [NMI] Populating `ErrorResponse` with required fields and Mapping `connector_response_reference_id`

- crates/router/src/routes/payments.rs
This change will make changes to the psync api locking to hold the lock only when force_sync = true. In other cases, no locking is necessary.
This change is to avoid unnecessary api locks when doing psync with force sync as false. This is only reading the payment and will not change the status, so lock is not needed.
- Fire 10 concurrent requests to psync, with force_sync as false
- Old application with locking
The timings are cumulative because next request is processed only after previous request is completed, adding to the time.
- New application without locking
All the requests take the same amount of time, as there is no locking.
> refactor(api_lock): allow api lock on psync only when force sync is true

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
Some payments fail when merchant_defined_information is passed for the payment with data coming from merchant in payment requests metadata.
This was happening because hashmaps were being used to populate key,value pairs in merchantDefinedInformation due to which the order in which the (key,value) pairs gets inserted into merchantDefinedInformation was not fixed. Due to this for some payments there was a mismatch between the body used in generation of signature(for payments headers) and the body which was being passed in the actual request. This mismatch caused the connector to throw authentication error for those payments.
https://github.com/juspay/hyperswitch/issues/3282
Testing can be done by creating a card/gpay/applepay payment and by passing the following metadata in PAYMENTS-CREATE: …
> fix(connector): [BOA/CYB] Fix Metadata Error

- .github/workflows/release-stable-version.yml
This PR adds a new workflow to attach a SemVer tag to a selected CalVer tag, thus creating a "stable" release intended for end users and deploying on production environments. The workflow also attaches the changelog since the previous SemVer tag as a build artifact, so that the maintainer can base the GitHub release notes off of the changelog.
This PR allows maintainers to promote a nightly release to a stable one after it has undergone sufficient testing. The workflow to create nightly releases was added in #3247, for additional context.
I've added this workflow and tested it out on a private repository and verified that it works as intended.
> ci: add workflow to create stable SemVer tag for a given CalVer tag

- crates/router/src/services/kafka.rs
Throw an error when outgoing webhook events env var not found
> fix(outgoingwebhookevents): Throw an error when outgoing webhook events env var not found

- crates/api_models/src/user.rs
- crates/diesel_models/src/query/merchant_account.rs
- crates/diesel_models/src/query/merchant_key_store.rs
- crates/router/src/core/user.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/db/merchant_account.rs
- crates/router/src/db/merchant_key_store.rs
- crates/router/src/utils/user_role.rs
Added Merchant name in list merchant api.
PR to main: https://github.com/juspay/hyperswitch/pull/3289
Dashboard needs to show merchant name is available.
```
curl --location --request GET '<URL>/user/switch/list' \
--header 'Authorization: Bearer <JWT>'
```
Above api should return list of merchant accounts the user (whos jwt is being used) has access to.
```
[
{
"merchant_id": "merchant_1704706726",
"merchant_name": null
},
{
"merchant_id": "merchant_1704706837",
"merchant_name": "some merchant name"
}
]
```
> fix(users): Added merchant name is list merchants

- crates/router/src/connector/utils.rs
- crates/router/src/connector/worldline/transformers.rs
- crates/router/src/core/fraud_check.rs
- crates/router/src/core/payment_methods/vault.rs
While addressing [PR#3168](https://github.com/juspay/hyperswitch/pull/3168), I came across several minor issues and made some small code improvements. These changes were unrelated to the main issue and were requested to be undone. Consequently, I've created this separate pull request.
```
cargo check --all-features -p router
cargo clippy --all-features -p router
```
> chore: nits and small code improvements found during investigation of PR#3168

- crates/router/src/connector/bluesnap.rs
add connector_txn_id fallback for webhook
#3316 
Trigger webhooks from Bluesnap with and without `merchant_transaction_id` and receive outgoing webhooks from Hyperswitch
> refactor(connector): [bluesnap] add connector_txn_id fallback for webhook

- .github/workflows/release-nightly-version-reusable.yml
- .github/workflows/release-nightly-version.yml
- CHANGELOG.md
This PR updates the nightly release workflows to make use of git commands to push commits and tags, since GitHub's branch protection rules prevent a bot from pushing commits when the merge queue has been enabled.
This PR fixes failures with using a GitHub app to push to a protected branch when the merge queue has also been enabled. One such failure happened this morning: https://github.com/juspay/hyperswitch/actions/runs/7468465920/job/20323959428
Temporarily enabled the workflow to run on branch pushes:
https://github.com/juspay/hyperswitch/actions/runs/7475549987/job/20343942382
Screenshot of the tag pushed (that I had to then delete):
> ci: use git commands for pushing commits and tags in nightly release workflows

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
Include merchant metadata in capture and void requests for connectors BOA and Cybersource.
https://github.com/juspay/hyperswitch/issues/3307
Testing can be done by creating 2 manual authorized payments for each BOA and Cybersource. While creating these payments you should pass metadata in the requests.
```
"metadata": {
"count_tickets": 1,
"transaction_number": "5590043"
},
```
Then you should void one payment and capture the other. You should then be able to see this metadata in merchantDefinedInformation in BOA/Cybersource Dashboard.
> feat(connector): [BOA/Cyb] Include merchant metadata in capture and void requests

- crates/api_models/src/refunds.rs
- crates/router/src/core/refunds.rs
- openapi/openapi_spec.json
Merchant connector id was not being populated in `refunds`. This PR will fix it.
This will fix refunds sync
- Create a refund and check whether `merchant_connector_id` is populated in the refund.
> fix(refund): add merchant_connector_id in refund

- .dockerignore
- .gitignore
- crates/router/tests/connectors/sample_auth.toml
- crates/test_utils/tests/sample_auth.toml
This PR fixes the `-dirty` suffix appearing in the `x-hyperswitch-version` header, only with Docker image builds but not when running locally.
As of today, on the `2024.01.11.0` Docker image running on our sandbox environment, we see a `-dirty` suffix in the `x-hyperswitch-version` header:
```shell
$ curl --silent --include https://sandbox.hyperswitch.io/health | grep 'x-hyperswitch-version:'
x-hyperswitch-version: 2024.01.11.0-dirty
```
This PR fixes the working directory being dirty in Docker builds, and thus the `-dirty` suffix appearing in the header.
Built a Docker image locally and ran the built image using the following commands: 
```shell
$ docker build --progress=plain --build-arg BINARY=router --tag router:latest .
$ docker run --rm --publish 8080:8080 --volume …
```
> chore: remove connector auth TOML files from `.gitignore` and `.dockerignore`

- crates/api_models/src/payments.rs
- crates/cards/src/validate.rs
- crates/router/src/core/payments/helpers.rs
Card extended bin is the initial 8 digits of card number. we need this field to be sent in payment attempt so that merchant can block payments based on this field too.
This PR adds a new field `card_extended_bin` in `AdditionalCardInfo` struct which is mapped to `payment_method_data` in `payment_attempt` table. Also this field is added in payments retrieve response too.
1. Do a payment with card. You should be getting the `card_extended_bin` field in response
2. Do a payment retrieve call using the `payment_id` from above call. You should get `card_extended_bin` field in response
> feat: add support for card extended bin in payment attempt

- crates/router/src/connector/utils.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/types.rs
wrote logic to update amount_capturable based intent_status and payment flow.
This was necessary because connector may send processing status in the authorization response (amount_capturable will be set to 0). This will later change to requires_capture when force sync is done. At this point, with the existing implementation, amount_capturable will remain 0 and will not be updated to authorized_amount. This prevents the capture of the payment. (NMI connector).
Manual
Create a payment with manual capture
Force sync
Capture the payment
Force sync
> fix: update amount_capturable based on intent_status and payment flow

- crates/api_models/Cargo.toml
- crates/router/Cargo.toml
This PR disables the default `recon` feature and moves it to be a part of `release` instead.
`recon` feature is dependent on `email` feature which requires AWS SES credentials. This leads to application throwing an error / panic at application startup.
Tested locally using cargo hack - `cargo hack check --each-feature --no-dev-deps`
> chore(router): remove recon from default features

- crates/router/src/connector/volt.rs
- crates/router/src/connector/volt/transformers.rs
Make a payment and do refund , Check for webhooks in Volt dashboard under transactions.  
Then for Notifications check for all webhooks, In All the 4 notifications `PENDING ` , `COMPLETED`, `RECEIVED` and `REFUND_CONFIRMED ` should have status `Delivered` and http code `200 OK`. 
Paymnet Request Body
`{
"amount": 1178,
"amount_to_capture": 1178,
"payment_method_type": "open_banking_uk", …
> refactor(connector): [Volt] Refactor Payments and Refunds Webhooks

- crates/router/src/utils/user/sample_data.rs
Currently for user with multiple business profiles. We are getting 500 if the profile id is not passed in the payload. Therefore, need to fetch the profile_id (the first one) from list of business profiles, for the sample data generation. 
Getting 500, for users with multiple business profiles for sample data generation.
Singup
```
--header 'Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMWZjNzgyOTUtM2JiMy00OGJjLThlZDgtNzFjMzVjMzMxYWU2IiwibWVyY2hhbnRfaWQiOiJtZXJjaGFudF8xNjk3NzE2ODcwIiwicm9sZV9pZCI6Im1lcmNoYW50X2FkbWluIiwiZXhwIjoxNjk3ODg5NjcxLCJvcmdfaWQiOiJvcmdfejQ5ZExMeTdmbllUODN5TDY3clEifQ.CJzEQ2qbhn-qUiiVBSdvCJiLvWp-5wCF9R54gth6QbQ' \
--data-raw '{
"email": …
```
> fix(user): fetch profile_id for sample data

- crates/api_models/src/events/user.rs
- crates/api_models/src/user.rs
- crates/diesel_models/src/query/user_role.rs
- crates/diesel_models/src/schema.rs
- crates/diesel_models/src/user.rs
- crates/router/src/core/user.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/db/user.rs
- crates/router/src/db/user_role.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/lock_utils.rs
- crates/router/src/routes/user.rs
- crates/router_env/src/logger/types.rs
- migrations/2024-01-02-111223_users_preferred_merchant_column/down.sql
- migrations/2024-01-02-111223_users_preferred_merchant_column/up.sql
- This PR adds a new column in users table called `preferred_merchant_id`. `preferred_merchant_id` will be used at the time of signin to directly use that `merchant_id` when user has access to multiple merchant accounts.
- This PR adds a new API which enables users to update their name and preferred merchant id.
To support the highlighted flow in the following diagram.
Note: This PR doesn't have the actual changes of the flow, but has few required changes to make the highlighted flow possible.
```mermaid
flowchart TD
A["Connect Account"] -- Email --> B{"User Exists"}
B -- No --> C["Create new \n Org \n Merchant \n User \n User Role"]
C --> D["Send Verify Email"]
D --> E["Verify Email Token"]
B -- Yes --> D
E --> H{"Is there\n any perferred \nmerchant"}
F -- ==0 --> I{{"Send list of …
```
> feat(users): Add `preferred_merchant_id` column and update user details API

- crates/api_models/src/user_role.rs
- crates/router/src/core/user_role.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/lock_utils.rs
- crates/router/src/routes/user_role.rs
- crates/router/src/services/authorization/info.rs
- crates/router/src/services/authorization/permissions.rs
- crates/router/src/types/domain/user.rs
- crates/router/src/utils/user_role.rs
- crates/router_env/src/logger/types.rs
Added API to get list of permission user has.
Required for hyperswitch control centre
```
curl --location --request GET '<URL>/user/role' \
--header 'Authorization: Bearer <JWT>'
```
Above API should give an array of permission.
All roles and their permission can be found [here](https://github.com/juspay/hyperswitch/blob/main/crates/router/src/services/authorization/predefined_permissions.rs#L28).
Example response,
```
[
"PaymentRead",
"RefundRead",
"ApiKeyRead",
"MerchantAccountRead",
"MerchantConnectorAccountRead",
"RoutingRead",
"ForexRead",
"ThreeDsDecisionManagerRead",
"SurchargeDecisionManagerRead",
"Analytics",
"DisputeRead",
"MandateRead",
"CustomerRead",
"FileRead",
"UsersRead"
]
```
> feat(users): Added get role from jwt api

- crates/router/src/routes/recon.rs
- crates/router/src/services/email/types.rs
This PR corrects the recipient mail which notifies the HS team for any recon activation requests.
**How to test**
Once deployed, request for recon activation using /recon/request API. Check the mail body sent to the recipient (biz@hyperswitch.io)
> refactor(recon): update recipient email and mail body for ProFeatureRequest

- README.md
Add Api Documentation link to the README.md
Making Api docs accessible to the users.
> docs: add link to api docs

- crates/router/src/compatibility/stripe/payment_intents/types.rs
Populate Mandate data for multi-use mandates
Resolves [#[3908]](https://github.com/juspay/hyperswitch-cloud/issues/3908)
1.Create a mandate payment with noon through stripe compatibility layer
2.Do a mandate payment with the same
> feat(compatibility): add multiuse mandates support in stripe compatibility

- crates/router/src/compatibility/stripe/payment_intents/types.rs
Reverts juspay/hyperswitch#3425
resolves [#3445](https://github.com/juspay/hyperswitch/issues/3445)
Dependency changes not made
> Refactor(compatibility): revert add multiuse mandates support in stripe compatibility

- crates/router/src/utils.rs
Outgoing webhooks were not being triggered for Partial Capture status for Payment Sync and Process Tracker.
Steps to test:
- Create a merchant account and update the webhook endpoint where you want to send the webhooks with it
```
{
"address": { …
```
> feat(core): Add outgoing webhook for manual `partial_capture` events

- crates/router/src/core/payments/operations/payment_confirm.rs
This will allow us to enable and disable the blocklist feature based on each merchant's requirements.
The steps to test out this feature can be found in the mentioned issue.
> refactor(core): Add killswitch for blocklist feature

- crates/connector_configs/toml/production.toml
add wasm changes for prod dashboard
test case - in prod dashboard, for nmi, pm types - credit and debit should be present
> chore(configs): [NMI] add wasm changes for prod dashboard

- config/deployments/sandbox.toml
- config/development.toml
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/sandbox.toml
Add configs for PIX for ADYEN in wasm dashboard
Not tested, as this PR only has config changes
> chore(config): [ADYEN] Add configs for PIX in WASM

- crates/router/src/connector/bankofamerica.rs
- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/cybersource/transformers.rs
Server was throwing 5XX Error if wrong api_secret was passed during Payment Connector - Create.
This is now handled by throwing `InvalidConnectorConfig` error.
https://github.com/juspay/hyperswitch-cloud/issues/3255
Testing can be done by adding wrong api_secret/api_key/key1 during Payment Connector - Create.
- If wrong api_secret is added you should get the following error:
- If wrong api_key/key1 is added you should get the following error:
> fix(connector): [BOA/Cybersource] Handle Invalid Api Secret

- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario1-Create payment with confirm true/Payments - Create/request.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario27-Create payment without customer_id and with billing address and shipping address/Payments - Create/request.json
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario8-Create a failure card payment with confirm true/Payments - Create/request.json
Extended card expiry month for stripe collection in some of the scenarios 
Collection was failing because card was expired as of today 
Postman
> ci(postman): Stripe collection card expired fix

- crates/router/src/middleware.rs
- crates/router/src/routes/customers.rs
- crates/router/src/routes/mandates.rs
- Add an end request log line for logging keys
- Since we no longer log enter & exit spans we need an explicit log line to mark end of request
make a health API call & check for the following log line
```json
{
"message": "[ROOT_SPAN - EVENT] router::middleware",
"hostname": "sampraslopes-SERIAL.local",
"pid": 78236,
"env": "development",
"level": "INFO",
"target": "router::middleware",
"service": "router",
"line": 146,
"file": "crates/router/src/middleware.rs",
"fn": "ROOT_SPAN",
"full_name": "router::middleware::ROOT_SPAN",
"time": "2024-02-01T11:54:29.607859000Z",
"flow": "UNKNOWN",
"request_id": "018d6485-3b65-7902-8983-fc57988d7e7a",
"extra": {
"golden_log_line": true,
"otel.kind": "server",
"http.scheme": "http",
"trace_id": "00000000000000000000000000000000",
"http.method": "GET", …
```
> fix(logging): add an end log line for `LogSpanInitializer`

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments/operations/payment_create.rs
ListPaymentMethodsForMerchant was unable to list the payment methods enabled as it was always taking mandate to have Some value even though its respective fields were None. So added a check that, if there's mandate_data present then only any data should be stored in the database
- Create MA and MCA 
- Do a payment with confirm as false and then ListPaymentMethodsForMerchnats
> Earlier
> After fix
> fix(core): fix mandate_details to store some value only if mandate_data struct is present

- crates/router/src/connector/trustpay/transformers.rs
add merchant_id in gpay session response for trustpay
PR merged in main - #3471
test cases - make a gpay payment for trustpay (in gpay session response, merchant_id should be present). testing of this pr can only be done in prod since this issue was only in prod.
Couldn't test in local.
tested in sbx - we received merchant_id
> fix(connector): [Trustpay] add merchant_id in gpay session response for trustpay

- crates/api_models/src/events/user.rs
- crates/api_models/src/user.rs
- crates/router/src/core/user.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/lock_utils.rs
- crates/router/src/routes/user.rs
- crates/router_env/src/logger/types.rs
The new endpoint `/resend_invite`, add supports to send invitation to user again. 
To invite user:
```
curl --location 'http://localhost:8080/user/user/invite' \
--data-raw '{
"email": "test_2@juspay.in",
"name": "test2",
"role_id": "merchant_admin"
}
'
```
For resend invite:
```
curl --location 'http://localhost:8080/user/user/resend_invite' \
--data-raw '{
"email": "test_2@juspay.in"
}'
```
> feat(user): add support for resend invite

- crates/router/src/lib.rs
- crates/router/src/middleware.rs
handle empty body parse failures in bad request logger middleware
Main PR - https://github.com/juspay/hyperswitch/pull/3541
> fix(router): handle empty body parse failures in bad request logger middleware

- crates/router/src/connector/nmi/transformers.rs
- crates/router/src/services/api.rs
Handle empty response in psync and error response in complete authorize 
test cases - Make payment, when status is in authentication_pending, make a psync, status should remain same
make a payment, after redirection , status should be succeeded.
successful payment - 
payment having error code and message when the fields such as cavv, eci, xid
> fix(connector): [NMI] Handle empty response in psync and error response in complete authorize

- crates/router/src/core/user.rs
- crates/router/src/utils/user_role.rs
Changed switch list api to also send inactive merchants in the response.
To use this in this api to get all the merchant details
```
curl --location 'http://localhost:8080/user/switch/list' \
```
This api will send merchants with `is_active`: `false` in the response from now on.
```
[
{
"merchant_id": "merchant_1",
"merchant_name": null,
"is_active": false
},
{
"merchant_id": "merchant_2",
"merchant_name": null,
"is_active": true
}
]
```
> refactor(users): change list roles api to also send inactive merchants

- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/connector/noon/transformers.rs
Resolves #3445
Original PR:  #3481
_Note
1.While connector create ensure `test_mode` is set to true
2.Ensure the currency passed is `AED` and country is `AE`_
1.Create a CIT with noon
with 
```
"connector_metadata": {
"noon": {
"order_category": "pay"
}
}
```
</n>
without order_category it should throw an error
2. Make a MIT
3.Test through stripe compatibility layer
CIT
MIT 
MIT with greater amount
4.Test Applepay mandates
> refactor: [Noon] add new field max_amount to mandate request

- crates/diesel_models/src/events.rs
- crates/router/src/core/webhooks.rs
- crates/router/src/events/outgoing_webhook_logs.rs
This PR includes minor refactors and improvements to the webhooks code. The PR can easily be reviewed one commit at a time, to understand the changes involved.
The webhooks flows contains a few redundant clones, unnecessary lazy evaluation (using `attach_printable_lazy()` instead of `attach_printable()`), spawning of a future on the `tokio` runtime without the current `tracing` span information, etc. This PR addresses those concerns.
Most of the changes are such that the code should work if it compiles.
However, I performed a sanity test of incoming and outgoing webhooks for a successful payment and refund.
- Screenshot of Postman folder run containing payments create and retrieve, followed by refunds create and retrieve API calls:
- Screenshot of captured outgoing webhooks for a …
> refactor(webhooks): remove unnecessary clones and lazy evaluations

- crates/router/src/compatibility/wrap.rs
- crates/router/src/db/address.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/db/payment_method.rs
- crates/router/src/services/api.rs
- crates/scheduler/src/utils.rs
- crates/test_utils/src/newman_runner.rs
This PR addresses the clippy lints occurring due to new rust version 1.76
Rust updation clippy lints are addressed here. So basic sanity test should suffice
> chore: address Rust 1.76 clippy lints

- crates/router/src/core/payment_methods/cards.rs
When metadata of a saved card is updated and customer payment methods are listed, the updated card's last 4 digit is getting masked in the response. This PR unmasks it and returns the raw digits.
Bug: `last4_digits` is masked -
Fix: unmasked - 
1. Save a card in locker
2. Change the metadata of the saved card and try to save it again in locker
3. Now when `list_customer_payment_method` is called, the `last4_digits` field of the updated card has to be unmasked
> fix(payment_methods): unmask last4 digits of card when listing payment methods for customer

- crates/api_models/src/disputes.rs
- crates/api_models/src/events/dispute.rs
- crates/router/src/core/disputes.rs
- crates/router/src/core/disputes/transformers.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/disputes.rs
- crates/router/src/routes/lock_utils.rs
- crates/router_env/src/logger/types.rs
add `delete_evidence` api for disputes
1. Create a dispute through checkout connector with dispute_opened status ([docs](https://www.checkout.com/docs/developer-resources/testing/disputes-testing))
2. Add multiple evidences to the dispute using attach_evidence API
3. Check dispute record in DB for entries (Alternatively can call retrieve_evidence API)
4. Call the delete_evidence API to delete a particular evidence type for a dispute
5. Check in DB if that evidence type is deleted and others are not changed (Alternatively can call retrieve_evidence API)
> feat(router): add `delete_evidence` api for disputes

- crates/router/src/connector/stripe/transformers.rs
Pass billing details to stripe in case of card payment.
This PR will pass the `billing_address` to stripe for card payment
- Create a payment using billing address and customer email.
```bash
--header 'api-key:<API-KEY>' \
--data-raw '{
"amount": 6969,
"name": "John Dough",
"customer_id": "cus_PAxm0MeCGM5TowgDKPc9",
"email": "example@juspay.in",
"description": "Its my third payment request",
"card": {
"card_number": …
```
> feat(stripe): send billing address to stripe for card payment

- crates/router/src/core/payments/tokenization.rs
When a metadata is changed during /payments and list customer payment method is called, last4 digits is getting masked. This PR unmasks it
1. Save a card in locker using /payments
2. Change the metadata of the saved card and try to save it again in locker using /payments
3. Now when list_customer_payment_method is called, the last4_digits field of the updated card has to be unmasked
> fix(payment_methods): unmask last4 when metadata changed during /payments

- crates/test_utils/README.md
- postman/README.md
This PR updates the `Rustman` documentation easing the collection development process along with the things to look for before running the collection.
Closes #3616
The documentation misses some key points which is why some of the developers and contributors are finding it difficult to test their work.
Below 2 files look cleaner and clearer:
- https://github.com/juspay/hyperswitch/blob/af7e39e57fd079bad60d8afed97c74fe633e4645/crates/test_utils/README.md
- https://github.com/juspay/hyperswitch/blob/af7e39e57fd079bad60d8afed97c74fe633e4645/postman/README.md
> docs(postman): update rustman and collection generation docs

- add_connector.md
This PR adds documentation to add_connector.md explaining how to add connectors to the Control Center via Wasm configs.
Testing not required
> docs(connector): Add wasm docs in connector integration docs 

- Cargo.lock
- config/deployments/drainer.toml
- crates/drainer/Cargo.toml
- crates/drainer/src/connection.rs
- crates/drainer/src/health_check.rs
- crates/drainer/src/lib.rs
- crates/drainer/src/main.rs
- crates/drainer/src/secrets_decryption.rs
- crates/drainer/src/secrets_transformers.rs
- crates/drainer/src/services.rs
- crates/drainer/src/settings.rs
- crates/hyperswitch_interfaces/src/secrets_interface/secret_state.rs
Added `AppState` in drainer which now contains `encryption_client` for runtime encryption and decryption of values. This PR also incorporates the newly added `hyperswitch_interface` crate for decrypting the secrets during application startup.
This PR refactors the way decryption of secrets work in drainer. So this cannot be tested
> refactor: incorporate `hyperswitch_interface` into drainer

- config/config.example.toml
- config/deployments/env_specific.toml
- config/development.toml
- config/docker_compose.toml
- crates/router/src/configs/defaults.rs
- crates/router/src/configs/settings.rs
- crates/router/src/configs/validations.rs
- crates/router/src/cors.rs
- crates/router/src/lib.rs
- loadtest/config/development.toml
Adds cors rules to actix
- Added `CorsSettings` config
NA
- Configure allowed origins in `ROUTER__CORS__ORIGINS`.
- Add `Origin` header to that configured to your config and the request should return 200
```bash
curl --location 'http://localhost:8080/health' \
--header 'Origin: http://localhost:8080'
```
- And configure origin header to something else like `google.com`. It should return `Bad Request` with Response
`Origin is not allowed to make this request`
```bash
curl --location 'http://localhost:8080/health' \
--header 'Origin: https://google.com'
```
> feat: add cors rules to actix

- crates/router/src/cors.rs
Allow all headers on CORS
This fixes CORS error on headers not being allowed
- Do a preflight request to `/user/role`
```bash
curl --location --request OPTIONS 'http://localhost:8080/user/role' \
--header 'authority: sandbox.hyperswitch.io' \
--header 'accept: */*' \
--header 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
--header 'access-control-request-headers: api-key,authorization,content-type' \
--header 'access-control-request-method: GET' \
--header 'cache-control: no-cache' \
--header 'origin: https://app.hyperswitch.io' \
--header 'pragma: no-cache' \
--header 'referer: https://app.hyperswitch.io/' \
--header 'sec-fetch-dest: empty' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-site: same-site' \
--header 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) …
```
> fix: allow all headers on cors

- crates/api_models/src/enums.rs
- crates/router/src/core/locker_migration.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
- crates/router/src/core/payments/tokenization.rs
- crates/router/src/core/payouts/helpers.rs
- crates/router/src/lib.rs
- crates/router/src/routes.rs
- crates/router/src/routes/app.rs
Fallback was added for card and retrieve card from rust locker (`hyperswitch card vault`).  This changes was to add card to both the locker (Basilisk HS and Rust Locker) and during the retrieve call try to fetch card details from the rust locker first, if it fails it tries to fetch it form Basilisk HS. https://github.com/juspay/hyperswitch/pull/2888
Now as we are no more using `Basilisk` this code is being removed.
This PR also removes the locker_migration route since the card migration is completed. However, the code for it remains as we may require the migration API in the future.
Payment create with `"setup_future_usage": "on_session"`
```
{
"amount_to_capture": …
```
> refactor(router): remove fallback feature for `/add` and `/get` for locker

- crates/storage_impl/src/errors.rs
This PR fixes a bug with the update API key and delete API key endpoints throwing an internal server error when a non-existent API key was provided.
Fixes #3761.
Locally. Trying to either update a non-existent API key returns a 404 status code, with an error message stating that the API key does not exist.
1. Update API key (request body may contain data or could just be an empty object): 
```shell
curl --location 'http://localhost:8080/api_keys/<merchant_id>/invalid-api-key-id' \
--header 'api-key: <ADMIN_API_KEY>' \
--data '{}' 
```
2. Delete API key:
```shell
curl --location --request DELETE 'http://localhost:8080/<merchant_id>/merchant_1708546282/invalid-api-key-id' \ …
```
> fix(api_keys): fix internal server error being thrown when trying to update or delete non-existent API key

- crates/router/src/connector/nmi/transformers.rs
- crates/router/src/services/api.rs
NMI card 3DS was failing in production. This is because `customer_vault_id` was not being provided in the transaction requeset. 
Create a 3ds card payment via NMI connector
```
{
"amount": 250,
"amount_to_capture": 250,
"accept_header": …
```
> refactor(connector): [NMI] Include customer_vault_id for card 3ds transaction request

- crates/router/src/services/api.rs
Corresponding [hotfix PR](https://github.com/juspay/hyperswitch/pull/3755)
Create a 3ds card payment via NMI connector
```
{
"amount": 250,
"amount_to_capture": 250,
"accept_header": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image …
```
> refactor(connector): [NMI] add hyperswitch loader to card 3ds 

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/checkout/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/core/payments.rs
- crates/router/src/types.rs
Apple pay transactions via BOA and Cybersource require a specific field `commerce_indicator` which is based on the card network type used during apple pay transactions.
https://docs.cybersource.com/content/dam/documentation/en/apple-pay/fdiglobal/so/applepay-so-fdiglobal.pdf
This data is now being passed using the card network data being shared from SDK during apple pay payments.
https://github.com/juspay/hyperswitch/issues/3783
Apple pay payments need to be tested using simplified and manual flow for connectors BOA and Cybersource.
> feat(connector): [BOA/Cybersource] Pass commerce indicator using card network for apple pay

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
- openapi/openapi_spec.json
Bug Description
CustomerPaymentMethodsListResponse returns 404 when there is no customer tied to a payment
Proposed Behavior
Return a 200 response somehow indicating that a customer is not associated with the payment
Current Behavior
A 404 response with "Customer does not exist in our records" is being returned, although the customer_id is null
Fixes https://github.com/juspay/hyperswitch/issues/3767
> fix(cards): Return a 200 response indicating that a customer is none

- crates/router/src/connector/payme.rs
- crates/router/src/connector/payme/transformers.rs
Add void to payme for cancelling transaction
Cannot be tested since cards are failing for Payme
> feat(connector): [Payme] Add Void flow to Payme

- crates/router/src/services/api.rs
This PR fixes the duplicate request that was being constructed even if the connector_request already exists.
The `or()` function does eager evaluation. This means that even if there is Some(val) the part of code in the or part is evaluated. This is causing the request to be constructed twice.
Fixes #3799 
- Manual, compiler guided.
- Create a payment and check if `connector_request` is logged only once.
> fix(core): do not construct request if it is already available

- crates/router/src/connector/braintree/braintree_graphql_transformers.rs
- crates/router/src/connector/braintree/transformers.rs
Mask pii information passed and received in the connector request and response for Braintree.
Check if sensitive fields within connector request and response is masked in the click house for Braintree
Test for both graphQL and the normal version
Sanity test
1. Payment create - 3ds card
```
--header 'api-key: {{api_key}}' \
--data-raw '{
"authentication_type": …
```
> refactor(connector): [Braintree] Mask PII data

- crates/router/src/core/payments/helpers.rs
- postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario23- Update Amount/Payments - Update/request.json
If capture method is automatic then `amount` must be equal to `amount_to_capture`, if `amount_to_capture` is sent in payment_create request.
This validation works in payments_create call but doesn't work as expected in payments_update call.
Manual
Payment create with confirm false
Update payment amount (fails with validation error)
Send correct `amount_to_capture` field and update is successful
> fix(core): validate amount_to_capture in payment update

- crates/api_models/src/events/user_role.rs
- crates/api_models/src/user_role.rs
- crates/api_models/src/user_role/role.rs
- crates/common_enums/src/enums.rs
- crates/router/src/core/user.rs
- crates/router/src/core/user_role.rs
- crates/router/src/core/user_role/role.rs
- crates/router/src/routes/user_role.rs
- crates/router/src/services/authorization.rs
- crates/router/src/services/authorization/info.rs
- crates/router/src/services/authorization/roles.rs
- crates/router/src/types/domain/user.rs
- crates/router/src/utils/user.rs
Change `list_roles`, `get_role` and `get_authorization_info` api to respond with groups if asked.
closes #3836 
All the following APIs have a query param called groups, setting it to true will return the following response.
1. Get role list
```
curl --location 'http://localhost:8080/user/role/list?groups=true' \
```
Response
```
[
{
"role_id": "merchant_iam_admin",
"groups": [
"operations_view",
"analytics_view",
"users_view",
"users_manage",
"merchant_details_view"
],
"role_name": "IAM",
"role_scope": "organization"
},
{
"role_id": "merchant_customer_support",
"groups": [
"operations_view",
"analytics_view",
"users_view",
"merchant_details_view"
],
"role_name": "Customer Support",
"role_scope": "organization"
},
{
"role_id": "merchant_admin", …
```
> feat(roles): Change list roles, get role and authorization info api to respond with groups
