crates/router/src/connector/gocardless/transformers.rs
Mask pii information passed and received in the connector request and response for Gocardless.
1. Create a payment intent with Gocardless
```
--header 'api-key: {{}}' \
--data-raw '{
"amount": 0,
"order_details": null,
"customer_id": "arjun",
"email": "hyperswitch_sdk_demo_id@gmail.com",
"description": "Hello this is description",
"shipping": {
"address": {
"state": "zsaasdas",
"city": "Banglore",
"line1": "sdsdfsdf",
"line2": "hsgdbhd",
"line3": "alsksoe",
"zip": "571201",
"last_name": "doe"
},
"phone": {
"number": …
```
=>  refactor(connector): [Gocardless] Mask PII data

crates/api_models/src/events/user_role.rs, crates/api_models/src/user_role/role.rs, crates/router/src/core/user_role/role.rs, crates/router/src/routes/user_role.rs
Get role from token will respond with groups if asked.
Closes #3871 
The following api will take a query param called `groups` and if it is set to `true` it will respond with array of groups.
This api was already present previously but was responding with permissions. The default behaviour without the `groups` query param is still the same (permissions will be returned). Groups will only be returned when `groups` param is set to true.
```
curl --location 'http://localhost:8080/user/role?groups=true' \
```
```
[
"users_view"
]
```
=> feat(roles): Add groups for `get_from_token` api

crates/router/src/connector/payme.rs, crates/router/src/core/payments/operations/payment_response.rs
Status should remain same to previous status in case of 429 http code
This error cannot be tested in sandbox so not included
=> refactor(core): Status mapping for Capture for 429 http code

crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/cybersource/transformers.rs
`ucaf_collection_indicator` is now being passed for apple pay payments via BOA/Cybersource for Mastercard users.
https://github.com/juspay/hyperswitch/issues/3898
Apple pay payments need to be tested using simplified and manual flow for connectors BOA and Cybersource using a mastercard network card.
=> fix(connector): [BOA/CYB] Pass ucaf for apple pay mastercard users

crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments/tokenization.rs
If the payment is made with payment methods other than card and bank_transfer and is asked to save the payment method, we should store `locker_id` column as `NULL` in payment_methods table. 
1. Create an MCA
```
curl --location 'http://localhost:8080/account/merchant_1709304245/connectors' \
--data '{
"api_key": "abc"
},
{
{ …
```
=> fix(payment_methods): insert `locker_id` as null in case of payment method not getting stored in locker

crates/router/src/connector/volt/transformers.rs
Fixes [4406](https://github.com/juspay/hyperswitch-cloud/issues/4406)
Configure Webhooks before creating a payment.
Create a open_banking_uk payment
Payment create request
`{
"return_url": "https://www.google.com/",
"payment_method_type": "open_banking_uk",
"open_banking_uk": {
}
}
},
"billing": {
"address": {
"line2": "Harrison …
=> fix(connector): [Volt] Fix status mapping for Volt

.deepsource.toml, .github/workflows/CI-pr.yml, .github/workflows/CI-push.yml, Cargo.toml, INSTALL_dependencies.sh, crates/router/src/routes/lock_utils.rs, crates/router/src/routes/user.rs, crates/router_env/src/logger/types.rs, crates/test_utils/tests/connectors/selenium.rs, loadtest/Dockerfile, monitoring/docker-compose-ckh.yaml
upgraded msrv to 1.70
opensearch crate depends on aws-smithy-types which requires msrv >= 1.67
upgrading msrv to 1.70
opensearch is used in dashboard global search - https://github.com/juspay/hyperswitch/issues/3866
CI checks passed locally
=> chore: upgrade msrv to 1.70

crates/diesel_models/src/api_keys.rs, crates/router/src/connector/square/transformers.rs, crates/router/src/core/api_keys.rs, crates/router/src/services/email/assets/api_key_expiry_reminder.html, crates/router/src/services/email/types.rs, crates/router/src/workflows/api_key_expiry.rs
Refactored the api key expiry reminder workflow to include the name and prefix of the expiring API key in the email
It fixes #3801 
1. Create a merchant account
2. Create an api key with expiry somewhat closer to 7 days from current time in UTC format.
3. You should get an email something like below once api key expiry is exactly 7 days from current time
=> refactor(api_keys): provide identifier for api key in the expiry reminder email

crates/diesel_models/src/payment_attempt.rs, crates/diesel_models/src/payment_intent.rs, crates/diesel_models/src/refund.rs
Add Unit tests for testing backwards compatibility
This tests if the type is backwards compatible or not
- Run `cargo tests --all-features -p diesel_models` it should pass all tests
- Cannot be tested in sandbox
=> chore(tests): add unit tests for backwards compatibility

crates/router/src/connector/checkout.rs, crates/router/src/connector/checkout/transformers.rs
fixes [4423](https://github.com/juspay/hyperswitch-cloud/issues/4423)
Create a Payment Request for Checkout Connector
`{
"return_url": "https://duck.com/",
"card": {
"card_number": "4724117215951699",
}
},
"billing": {
"address": { …
=> feat(connector): [Checkout] accept connector_transaction_id in 2xx and 4xx error_response of connector flows

crates/common_enums/src/enums.rs, crates/router/src/utils/user_role.rs
Enforce uniqueness of groups while role create or update.
Currently duplicate groups are allowed while role create/update.
Try to create/update role with duplicate groups:
Create
```
curl --location 'http://localhost:8080/user/role' \
--data '{
"role_name": "test007",
"groups": ["operations_view", "operations_manage", "operations_manage"],
"role_scope": "organization"
}'
```
Response:
```
{
"error": {
"message": "User Role Operation Not Supported",
"code": "UR_23"
}
}
```
Update
```
curl --location --request PUT 'http://localhost:8080/user/role/role_DGLY2gKDdS48cFoY573Y' \
--data '{
"groups": …
```
=> fix(user): improve role validation to prevent duplicate groups

crates/router/src/core/payment_methods/cards.rs
Since we are currently not getting any differentiators for multiple mandates set via a single wallet, we will be restricting setting up recurring payment for wallet only once.
- In Merchant Payment Method list, wallet types which are already saved and in active state for a customer should not be listed 
1. Create mca
```
curl --location 'http://localhost:8080/account/merchant_1709561576/connectors' \
--data '{
"api_key": "abc"
},
{
{ …
```
=> refactor(payment_methods): filter applepay payment method from mca based on customer pm

crates/router/src/connector/authorizedotnet/transformers.rs
- If the billing address is included in the payments request, it will be transmitted to the connector.
- Additionally, the `connector_request_reference_id` is now transmitted within the order description, making it visible in the transaction details on the connector dashboard.
https://github.com/juspay/hyperswitch/issues/3980
Test payments (manual and automatic) for authorizedotnet.
1. Automatic: 
- Request: `curl --location 'http://localhost:8080/payments' \
--data '{
"amount": 1234,
"card": …
=> feat(connector): [AUTHORIZEDOTNET] Add billing address in payments request

crates/api_models/src/events/user.rs, crates/api_models/src/user.rs, crates/router/src/core/user.rs, crates/router/src/routes/app.rs, crates/router/src/routes/lock_utils.rs, crates/router/src/routes/user.rs, crates/router_env/src/logger/types.rs
Currently there is no way to get the details of user and their role directly. This API solves it by taking the email of the user and returns the details.
closes [#3987](https://github.com/juspay/hyperswitch/issues/3987)
Postman.
```
curl --location 'http://localhost:8080/user/user?email=user@hyperswitch.io' \
```
```
{
"email": "user email",
"name": "user name",
"role_id": "merchant_view_only",
"role_name": "View Only",
"status": "Active",
"last_modified_at": "2024-03-01T06:23:44.250Z",
"groups": [
"operations_view",
"connectors_view",
"workflows_view",
"analytics_view",
"users_view",
"merchant_details_view"
],
"role_scope": "organization"
}
```
=> feat(users): Add new API get the user and role details of specific user

crates/router/src/core/errors.rs, crates/router/src/core/webhooks.rs
This PR fixes a bug in the outgoing webhook retry workflow where process tracker tasks remained in pending state if merchant webhook URL was not configured in the business profile. For more information, see: #3995.
In addition, this PR includes these changes:
1. Updates the process tracker task ID format to include the event ID instead of the primary resource ID.
2. Removes unused enum variants from the `WebhooksFlowError` error enum.
The PR can easily be reviewed one commit at a time.
Fixes #3995.
Locally, by running `router`, `producer` and `consumer`, and testing for these three cases:
1. For a business profile with webhook URL configured, the behavior should remain as before: webhooks should either be delivered successfully in the first attempt, or scheduled for later retries.
1. …
=> fix(webhooks): abort outgoing webhook retry task if webhook URL is not available in business profile

crates/router/src/core/payment_link/payment_link_initiate/payment_link.css, crates/router/src/core/payment_link/payment_link_initiate/payment_link.html, crates/router/src/core/payment_link/payment_link_initiate/payment_link.js
add shimmer page before payment_link loads starts
closes https://github.com/juspay/hyperswitch-cloud/issues/4483
Do payment link create and look for shimmer before the script start downloading
```shell
--header 'api-key: dev_vuC3wt9p8qUzB9co6ve1J04rUoxZvrFaaHi2cJ4BDIJCIwnltnZLPQMSJGCyIdHJ' \
--data-raw '{
"amount": 250,
"amount_to_capture": 250,
"authentication_type": …
```
=> feat(payment_link): add shimmer page before payment_link loads starts

crates/masking/src/serde.rs, crates/router/src/connector/multisafepay/transformers.rs
Mask pii information passed and received in the connector request and response for Mulisafepay.
1. Create a card payment
```
--data-raw '{
"billing": {
"address": {
"city": "San …
```
=>  refactor(connector): [Multisafepay] Mask PII data 

crates/router/src/connector/noon/transformers.rs
Mask pii information passed and received in the connector request and response for Noon.
1. Create a mandate payment with Noon
```
--header 'api-key: dev_DSA7zgwLkTw5bHT6khsixyQNDlvsM6HDvyhxwMulGlRk8gnjJwejcmvOCniHFWT6' \
--data-raw '{
"currency": "AED",
"customer_id": "c1",
"billing": {
"address": {
"line2": "Harrison …
```
=> refactor(connector): [Noon] Mask PII data

crates/diesel_models/src/customers.rs, crates/diesel_models/src/query/generics.rs, crates/diesel_models/src/query/payment_method.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/payment_method.rs, crates/router/src/types/domain/customer.rs
Currently, we don't delete the default payment method of a customer. But if only one payment method exists for a customer which is also set to default, then we should allow to delete that payment method
1. Store a new card or any other payment method for a customer. (Ensure only one payment method exists for a customer)
2. Set that payment method as default
```
curl --location --request POST 'http://localhost:8080/customers/cus_aXfFGQOFT7JFU47GYhZK/payment_methods/pm_37h7qElY2aTWBEPSgovJ/default' \
--data ''
```
3. Now try to delete that default payment method
```
curl --location --request DELETE 'http://localhost:8080/payment_methods/pm_37h7qElY2aTWBEPSgovJ' \ …
```
=> refactor(payment_methods): allow deletion of default payment method for a customer if only one pm exists

crates/router/src/core/errors/utils.rs, crates/router/src/core/refunds.rs
- The handling of the `ConnectorError` with the type `NotSupported` has been implemented for refunds. In cases where the connector raises a `NotSupported` error, the refund status will now be set to failure.
- Additionally, in this scenario, the error message will be presented as `{message} is not supported by {connector}`.
https://github.com/juspay/hyperswitch-cloud/issues/4439
Create a partial refund for connector placetopay which should result in connector throwing `NotSupported` error.
Request:
```
--data '{
"amount": 100,
"payment_id": "pay_yv0as66Wx6FRR5okC840",
"refund_type": "instant"
}'
```
Response:
```
{
"error": …
```
=> fix(core): [REFUNDS] Fix Not Supported Connector Error

config/deployments/production.toml, crates/router/src/connector/adyen.rs, crates/router/src/connector/adyen/transformers.rs
- Update Prod URL endpoint
- Handle refunds webhooks using hyperswitch internal refund id
- Add card holder name
Updated Prod URL endpoint
#4047 
- Trigger a refunds transaction
```
--header 'api-key: dev_gwfA0IT4jpKdcUSmJlWMJ0jawjc5ziP6lA91du0gpc9ydEzI5HajDN18Wr72NkS7' \
--data '{
"payment_id": "pay_ow2YSNvgVDZlGTv3o8wc",
"reason": "RETURN",
"refund_type": "instant",
"metadata": {
"login_date": "2019-09-10T10:11:12Z"
}
}'
```
- Check for outgoing webhook and also retrieve the refund to confirm the Status change
- Send card holder name in the cards request it should be visible in Adyen Dashboard for the payment
``` …
```
=> fix(connector): [Adyen] update config and add required fields

crates/router/src/core/payments/operations/payment_complete_authorize.rs
This PR fixes the issue where token data fetch from Redis was failing for 3DS payments going through the complete authorize flow. The issue being that the payment method was being taken from the request, where it may not be present. The solution was to add the payment method stored in the payment attempt as a fallback.
Certain connectors confirm their payments through the Complete Authorize flow when it comes to 3DS. To ensure that the token data fetch for this flow doesn't fail, we should be using the payment attempt as the fallback ground of truth for any missing data. This PR adds this fallback.
3DS Payments with Cybersource (failing before, passing now)
Payment Confirmation:
Payment Redirection (Succeeding):
=> fix(router): fix token fetch logic in complete authorize flow for three ds payments

crates/router/src/core/payment_methods/cards.rs
This PR updates the logic to decide the `requires_cvv` parameter in the customer payment methods list api to also depend on whether the payment is an off-session payment.
For off-session payments, the cvv is not required, so it should not be mandatory for off-session payments.
List Customer Payment Methods for normal payment (requires_cvv = true):
List Customer Payment Methods for off-session payment (requires_cvv = false):
=> fix(payment_methods): set requires-cvv to false for cards in customer payment methods list if making an off-session payment

crates/cards/src/validate.rs
Fixed `FromStr` implementation on `CardNumber` to work with wasm related feature configs.
Run `make euclid-wasm` to verify if Wasm build was successful.
=> fix: get valid test cards list based on wasm feature config

crates/router/src/connector/cybersource/transformers.rs, crates/router/src/core/payments/operations/payment_create.rs
Currently in the core, for a recurring mandate payment, if the mandate has both a network transaction ID and a connector mandate ID associated with it, the core picks the network transaction ID for making the recurring payment. This causes mandate payments to fail since we don't yet have support for making recurring mandate payments using a network transaction ID.
Recurring Mandate payment with Adyen
Initial Mandate Payment:
Recurring Mandate payment (Succeeding):
=> fix(mandates): give higher precedence to connector mandate id over network txn id in mandates

crates/router/src/configs/defaults.rs
add card holder name as a required field in dynamic fields for cyber source
#4083
- Create a payment for Cybersource with confirm false
```
--header 'api-key: dev_NEqxtA08zn0qi3szJqYNmFXpQQt41BfwDpOE1sVucX37yJUN7jpR6QkmrlJCuWf5' \
--data-raw '{
"amount": 9040,
"customer_id": "shanks5",
"email": "abc-ext.kylta@flowbird.group",
"description": "Its my first payment", …
```
=> feat(connector): [cybersource] add card holder name in dynamic fields

crates/router/src/core/payment_methods/cards.rs
This PR enables country, currency filter for cards in list payment methods for merchants
Payment Method List needs to be verified for USD and Non-USD payments via BOA:
1. Payments Request(with confirm false): 
```
--data-raw '{
"amount": 1404,
"billing": {
"address": { …
```
=> refactor(payment_methods): enable country currency filter for cards

crates/router/src/core/payments.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/types/transformers.rs, postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario29-Create payment with payment method billing/Payments - Create/event.test.js, postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario29-Create payment with payment method billing/Payments - Create/request.json, postman/collection-dir/stripe/QuickStart/Payments - Create/event.test.js, postman/collection-json/stripe.postman_collection.json
This PR fixes the inconsistency in payments response. More details can be found in the linked issue.
- Added postman test cases
=> fix(api_response): ghost payment_method_billing being populated in the response

crates/router/src/connector/prophetpay/transformers.rs, crates/router/src/connector/rapyd/transformers.rs, crates/router/src/connector/shift4/transformers.rs, crates/router/src/connector/square/transformers.rs
Mask pii information passed and received in the connector request and response for Prophetpay, rapyd, shift4 and square.
1. Create a card redirect payment with Prophetpay
```
--data '{
"payment_method": "card_redirect",
"payment_method_type": "card_redirect",
"card_redirect": {
"card_redirect": {}
}
},
"routing": {
"type": "single",
"data": "prophetpay"
}
}'
```
2.Rapyd Applepay 
3.Create a 3DS payment with Shift4
_Note: …
=>  refactor(connector): [Prophetpay][Rapyd][Shift4][Square] Mask PII data 

crates/router/src/core/payments/transformers.rs
`Profile_id` and `merchant_connector_id` is to be populated for payments list response.
closes #4103 
Use the curl to get payments list:
```
--header 'Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMWZjNzgyOTUtM2JiMy00OGJjLThlZDgtNzFjMzVjMzMxYWU2IiwibWVyY2hhbnRfaWQiOiJtZXJjaGFudF8xNjk3NzE2ODcwIiwicm9sZV9pZCI6Im1lcmNoYW50X2FkbWluIiwiZXhwIjoxNjk3ODg5NjcxLCJvcmdfaWQiOiJvcmdfejQ5ZExMeTdmbllUODN5TDY3clEifQ.CJzEQ2qbhn-qUiiVBSdvCJiLvWp-5wCF9R54gth6QbQ' \
--data '{ 
}'
```
In Response fields `profile_id` and `merchant_connector_id` fields properly populated.
```
{
"count": 5,
"total_count": 100,
"data": [
{
"payment_id": …
```
=> fix(payments): populate merchant connector id and profile id in list

crates/router/src/connector/stripe/transformers.rs
Should close #2863 by changing `NotSupported` to `NotImplemented` error for Stripe
Test a Payment Method which is not implemented It should give 
Not implemented error
This is an Crypto payment request. 
```
{
"crypto": {}
},
"routing": {
"type": "single",
"data": "adyen"
},
"billing": {
"address": { …
```
=> refactor(stripe): change NotSupported to NotImplemented error for Stripe

Cargo.lock, crates/router_env/Cargo.toml, crates/router_env/src/cargo_workspace.rs
This PR updates the build script code to obtain cargo workspace member package names to use a better and more deterministic way to do so. 
Previously, we used to perform string manipulation on the package ID format (obtained from the `workspace_members` field in `cargo metadata --format-version=1`), and the package ID format was not stabilized (until recently). The package ID format has been [stabilized](https://github.com/rust-lang/cargo/pull/12914) in Rust 1.77, and the stabilized format breaks our existing build scripts. This PR updates the build script code to instead obtain the workspace member package names using the [`Metadata::workspace_packages()`](https://docs.rs/cargo_metadata/0.18.1/cargo_metadata/struct.Metadata.html#method.workspace_packages) method that the `cargo_metadata` …
=> build(router_env): obtain workspace member package names from `cargo_metadata` more deterministically

crates/api_models/src/payments.rs
This PR adds a trait to extract billing detials from payment method data. No logical changes that affect payment flows are present in this PR. 
This change will be used in further PRs to consume payment method data billing and unify it and send it to the connector module.
Only code changes, no flows are affected
- I have added unit tests
=> refactor(payment_method_data): add a trait to retrieve billing from payment method data

crates/router/src/core/payments/operations/payment_response.rs
Currently we update the payment method status if the existing status doesn't match the attempt status. Update the status only if the existing status is not active.
1. Create Stripe mca
2. Create normal payment and save the card (payment fails as below used is a failure test card)
```
--data-raw '{
"customer_id": "customer1", …
```
=> fix(payment_methods): update payment method status only if existing status is not active

crates/api_models/src/payments.rs, crates/router/src/core/payments/helpers.rs
make ApplepayPaymentMethod in payment_method_data column of payment_attempt table as json because retrieve payment fails for the old payments for which the payment_method_data in the payment_attempt table was stored as {"wallet": {}}
Closes #4153.
Checkout to old commit where we were storing the `{"wallet": {}}` for apple pay in the `payment_attempt`  table
Make a payment create call for apple pay
```
{
"amount": 650, …
```
=> fix(payment_methods): make `ApplepayPaymentMethod` in payment_method_data column of `payment_attempt` table as json

crates/api_models/src/payments.rs, crates/router/src/core/payments/helpers.rs
make ApplepayPaymentMethod in payment_method_data column of payment_attempt table as json because retrieve payment fails for the old payments for which the payment_method_data in the payment_attempt table was stored as {"wallet": {}}
https://github.com/juspay/hyperswitch/pull/4154
Make a payment create call for apple pay
```
{
"amount": 650, …
```
=> fix(payment_methods): make ApplepayPaymentMethod in payment_method_data column of payment_attempt table as json

crates/router/src/core/payments.rs
handle redirection to return_url from nested iframe in separate 3ds flow
Currently, we are opening bank page in nested iframe in SDK. So, the redirection post message should be sent to top level instead of immediate parent. 
1. Sanity Separate 3ds flow testing, redirecting properly to return_url of merchant
=> fix(router): handle redirection to return_url from nested iframe in separate 3ds flow

add_connector.md, crates/common_utils/src/lib.rs, crates/common_utils/src/request.rs, crates/diesel_models/src/process_tracker.rs, crates/router/src/connector/bankofamerica.rs, crates/router/src/connector/checkout/transformers.rs, crates/router/src/connector/cryptopay.rs, crates/router/src/connector/cybersource.rs, crates/router/src/connector/dlocal.rs, crates/router/src/connector/fiserv.rs, crates/router/src/connector/payeezy.rs, crates/router/src/connector/rapyd.rs, crates/router/src/connector/riskified.rs, crates/router/src/core/mandate.rs, crates/router/src/core/payment_methods.rs, crates/router/src/types.rs, openapi/openapi_spec.json
This PR addresses the clippy lints occurring due to new rust version 1.77
=> chore: address Rust 1.77 clippy lints

crates/router/src/connector/checkout/transformers.rs, crates/router/src/core/payments/types.rs
After authentication is successful, authorization call must be made to the payment connector with authentication results to complete the transaction.
`eci`(e commerce indicator) is one of authentication result values. This `eci` is only returned during challenge flow and not in frictionless flow So had to make it an optional field.
Manual
Tested the external authenticaiton flow.
1. Create a merchant with checkout payment connector and threedsecure.io 3ds connector.
Create merchant
```
--data-raw '{
"merchant_id": "postman_merchant_GHAction_4e597812-7532-4497-b9c2-327975aab5fb",
"merchant_name": "NewAge …
```
=> fix(core): make eci in AuthenticationData optional

crates/router/src/connector/cryptopay/transformers.rs
Serialization of the metadata field in the payments request for cryptopay is skipped if the metadata is set to none.
https://github.com/juspay/hyperswitch/issues/4206
Testing can be done by creating a payment on cryptopay without passing metadata.
Request:
```
--data-raw '{
"amount": 120,
"customer_id": "custo", …
```
=> fix(connector): [CRYPTOPAY] Skip metadata serialization if none

Cargo.lock, crates/router_env/Cargo.toml, crates/router_env/src/cargo_workspace.rs
ORIGINAL PR: https://github.com/juspay/hyperswitch/pull/4139
This PR updates the build script code to obtain cargo workspace member package names to use a better and more deterministic way to do so. 
Previously, we used to perform string manipulation on the package ID format (obtained from the `workspace_members` field in `cargo metadata --format-version=1`), and the package ID format was not stabilized (until recently). The package ID format has been [stabilized](https://github.com/rust-lang/cargo/pull/12914) in Rust 1.77, and the stabilized format breaks our existing build scripts. This PR updates the build script code to instead obtain the workspace member package names using the [`Metadata::workspace_packages()`](https://docs.rs/cargo_metadata/0.18.1/cargo_metadata/struct.Metadata.html …
=> build(router_env): obtain workspace member package names from cargo_metadata more deterministically

crates/common_utils/src/macros.rs, crates/diesel_models/src/lib.rs, crates/diesel_models/src/macros.rs, crates/drainer/src/handler.rs, crates/drainer/src/lib.rs, crates/router/src/bin/scheduler.rs, crates/router/src/core/payments/flows/authorize_flow.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/lib.rs, crates/router/tests/utils.rs, crates/scheduler/src/consumer.rs, crates/scheduler/src/producer.rs, crates/storage_impl/src/redis.rs
Add span metadata to `tokio` spawned futures, as logs do not have parent span context. Also removed unused marco.
Logs of save payment method. Initially the `request_id` was not available for this logs.
=> fix(log): adding span metadata to `tokio` spawned futures

crates/router/src/compatibility/stripe/errors.rs, crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/bluesnap/transformers.rs, crates/router/src/connector/braintree/braintree_graphql_transformers.rs, crates/router/src/connector/checkout/transformers.rs, crates/router/src/connector/cybersource/transformers.rs, crates/router/src/connector/globalpay/transformers.rs, crates/router/src/connector/mollie/transformers.rs, crates/router/src/connector/nexinets/transformers.rs, crates/router/src/connector/noon/transformers.rs, crates/router/src/connector/payme/transformers.rs, crates/router/src/connector/square/transformers.rs, crates/router/src/connector/stax/transformers.rs, crates/router/src/connector/stripe/transformers.rs, crates/router/src/connector/utils.rs, crates/router/src/connector/zen/transformers.rs, crates/router/src/core/errors.rs, crates/router/src/core/errors/api_error_response.rs, crates/router/src/core/errors/transformers.rs, crates/router/src/core/errors/utils.rs, crates/router/src/core/payments/helpers.rs, crates/storage_impl/src/errors.rs
If deserialization fails for Google pay, Apple Pay and any other wallets token - Hyperswitch should respond with 4xx and proper error message
1. Successful payment with Stripe Googlepay 
```
--header 'api-key: {{}}' \
--data-raw '{
"amount": 1800,
"payment_method_type": "google_pay", …
```
=> fix(connectors): fix wallet token deserialization error 

crates/router/src/connector/trustpay.rs, crates/router/src/connector/trustpay/transformers.rs
- fix deserialization error for incoming webhook response for trustpay 
made `Code` as optional field
- add error code mapping '800.100.203'
PR raised against main - #4199
No testing can be done since it matches error code in production which cant be replicated
=> fix(connector): [Trustpay] fix deserialization error for incoming webhook response for trustpay and add error code mapping '800.100.203'

crates/router/src/types.rs
Amount capturable should remain same in case of processing status in manual capture
Create a manual capture through NMI:
```
{
"amount": 254,
"amount_to_capture": 254,
"accept_header": …
```
=> fix(core): Amount capturable remain same for `processing` status in capture

config/development.toml, config/docker_compose.toml
This updation will allow any origin to make request.
wildcard_origin = false                 # If true, allows any origin to make requests
=> refactor(config): allow wildcard origin for development and Docker Compose setups

crates/common_enums/src/enums.rs
This will remove the `processing` status from `payment_method_status` and by default makes everything active or failure.
This is a patch to ensure that no payment_method goes to non-terminal.
Sample curl:
```
curl --location 'http://127.0.0.1:8080/payments' \
--header 'api-key: dev_eZdRVkfE8sbYE7JSzm2Tu0HAca0PHRY6u3JoSFBukHuxoYeXw7bgwr7Gy2DJn1kS' \
--data-raw '{
"customer_id": "cus_v6LovN3Zs9k8QQ2UYcbi", …
```
=> refactor(core): removed the processing status for payment_method_status

crates/router/src/connector/cryptopay/transformers.rs, crates/router/src/connector/utils.rs
add validation for metadata for cryptopay. This method will return None if metadata is not of type Object. Since connector accepts only Object.
OSS PR - #4272
Test cases - Make a payment with metadata - null, bool, and object
expected behavior - Payment should be successful
payment request - 
```
{
"amount": 100,
"crypto": {
"pay_currency": …
```
=> fix(connector): [Cryptopay]fix redirection for cryptopay

crates/router/src/connector/stripe/transformers.rs
Earlier the connector_mandate_id was not being populated as expected, instead it was being populated in a separate field as `payment_method_id` in mandate_reference data. And earlier if we try to do MIT payment using `payment_method_id` it was not working.  In this PR the flow has been refactored and fixed to send the  Response from connector such that it is mapped to the `connector_mandate_id` in the core.
1. Create a CIT Card payment via Stripe Connector. 
```{
"customer_id": "SWANGI123", …
```
=> refactor(connector): [Stripe] fix mandate flow 

crates/api_models/src/payment_methods.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_complete_authorize.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_update.rs
When a setup mandate is done with customer, when doing recurring payment using `payment_method_id`, this PR adds following validation
- to match on customer_id such that they match on setup mandate as well as recurring.
- to match on merchant_id such that they match on setup mandate as well as recurring.
- not to pass both `mandate_id` and `recurring_details` 
This PR also stores `payment_method_id` and `payment_method_data` in payment_attempt table when doing recurring payment with `payment_method_id`
1. Setup mandate with a customer
```
--data-raw '{
"amount": 0, …
```
=> refactor(mandates): add validations for recurring mandates using payment_method_id

crates/router/src/core/payments/flows/authorize_flow.rs
log the appropriate error message if the card fails to get saved in locker
Cannot be tested , just a log addition
=> refactor(core): log the appropriate error message if the card fails to get saved in locker

crates/router/src/compatibility/stripe/errors.rs, crates/router/src/core/errors/api_error_response.rs, crates/router/src/core/errors/transformers.rs, crates/router/src/services/authentication.rs, crates/router/src/services/authentication/cookies.rs
This is the second PR for cookie implementation.
In this PR, cookie header is parsed to retrieve JWT that was set during dashboard entry.
This PR does not remove old auth flow where `Authorization` header was used to retrieve JWT from request. Instead, it compares  the JWT retrieved from `Authorization` header and `Cookie` header and logs the result. 
Storing JWT in cookies instead of local storage.
No testing required, feature is not complete and hence is not enabled.
=> feat(users): Implemented cookie parsing for auth

crates/redis_interface/src/commands.rs
Getting multiple values from Redis at one time was working fine in local environment but was failing when deployed because  of mutiple clusters at infra level.
closes #4302
#3945 when deployed, caused sandbox to fail.
=> fix(redis_interface): remove mget function from redis interface

crates/router/src/connector/stripe/transformers.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/flows.rs, crates/router/src/core/payments/flows/approve_flow.rs, crates/router/src/core/payments/flows/authorize_flow.rs, crates/router/src/core/payments/flows/cancel_flow.rs, crates/router/src/core/payments/flows/capture_flow.rs, crates/router/src/core/payments/flows/complete_authorize_flow.rs, crates/router/src/core/payments/flows/incremental_authorization_flow.rs, crates/router/src/core/payments/flows/psync_flow.rs, crates/router/src/core/payments/flows/reject_flow.rs, crates/router/src/core/payments/flows/session_flow.rs, crates/router/src/core/payments/flows/setup_mandate_flow.rs, crates/router/src/core/payments/operations/payment_response.rs, crates/router/src/core/payments/tokenization.rs
`payment_method` table where `network_transaction_id` is null as `pg_agnotic` flag is not enabled.
enabled `pg_agnotic` flag
```
curl --location 'https://sandbox.hyperswitch.io/routing/business_profile/:business_profile_id/configs/pg_agnostic_mit' \
--header 'Authorization: Bearer JWT_Token' \
--data '{
"enabled": true
}'
```
Preform a setup_mandate
```
{
"customer_id": "ajjj",
"return_url": …
```
=> fix(mandates): store network transaction id only when `pg_agnostic` config is enabled in the `authorize_flow`

crates/router/src/core/payments/operations/payment_status.rs
-> When a payment is created with save card we store the card in the locker and also a payment method entry is created in the payment method table. And the corresponding payment_method_id will be stored in the payment_attempt table.
-> And later when that payment method is deleted, psycn is failing as we are trying to fetch the payment method data from the payment_method table in the psync flow.
-> The error occurred because of the recent change that was trying to fetch the payment method in the psync flow using the payment_method_id in the payment attempt.
This is fixed by adding a validation for the error that occurs during fetching the payment method data from the db. If it is not found in db error then just log the error (do not propagate it), any other error needs to be returned as …
=> fix(psync): log the error if payment method retrieve fails in the `psync flow`

crates/diesel_models/src/configs.rs, crates/router/src/db/configs.rs
- [ x] Refactoring
Existing behavior is to insert configs in db with default if not found, this introduces interaction with master db which can be avoided.
This pr  has changes that avoids the db insert in case of configs entry not found in inmem, cache or db, the default will be cached in in mem and redis to avoid freq reads to db (as previously) and a redis publish to channel is done for inserts now
Existing behavior is to insert configs in db with default if not found, this introduces interaction with master db which can be avoided.
This pr  has changes that avoids the db insert in case of configs entry not found in inmem, cache or db, the default will be cached in in mem and redis to avoid freq reads to db (as previously) and a redis publish to channel is done for inserts now
test …
=> refactor(configs): Config default write defer

crates/router/src/core/payments.rs, crates/router/src/core/payments/operations/payment_create.rs
When a setup_mandate is done with currency say `USD`, When a recurring payment is being made using `payment_method_id` with another currency, the payment should fail saying `cross currency mandates not supported`.
This PR also handles error which could occur during payment_method_data decryption 
1. Setup mandate with a customer
```
--data-raw '{
"amount": 0,
"customer_id": "test_cus4",
}, …
```
=> fix(mandate): add validation for currency in MIT recurring payments

crates/router/src/core/payouts.rs, crates/router/src/core/payouts/helpers.rs
This PR ensures PayoutData's state is being updated after DB operations. It is important for the app's state to be updated as these objects are later used when updating entries in Redis KV.
Any asynchronous payout operation is likely to fail as KV will not be updated with latest data. This PR ensures the fix for the same!
- Enable KV for a merchant
- Perform payout txns in stages (Create + Confirm + Fulfill)
- Postman collection - https://galactic-capsule-229427.postman.co/workspace/My-Workspace~2b563e0d-bad3-420f-8c0b-0fd5b278a4fe/collection/9906252-8f51a4d2-86d6-4f72-8198-3fff5a4e71af?action=share&creator=9906252
=> fix(payouts): update payout's state in app after DB operations

crates/router/src/connector/zsl/transformers.rs, crates/router/src/types/transformers.rs
This PR address the issue where billing.address is None despite billing.address.country being passed in the /payments call. 
1. Make a zsl local bank transfer payment as follows 
```
--header 'api-key: "" ' \
--data-raw '{
"amount": 120,
"currency": "CNY",
"customer_id": "111111234567890",
"billing": {
"address": {
"country": "CN"
}
}, …
```
=> fix(router): capture billing country in payments request

crates/api_models/src/payments.rs, crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/bluesnap/transformers.rs, crates/router/src/connector/cybersource/transformers.rs, crates/router/src/connector/forte/transformers.rs, crates/router/src/connector/multisafepay/transformers.rs, crates/router/src/connector/nmi/transformers.rs, crates/router/src/connector/nuvei/transformers.rs, crates/router/src/connector/utils.rs, crates/router/src/connector/volt/transformers.rs
This PR fixes the issue which arises when creating a payement with cybersource and bank of america connectors where billing first name and last name are mandatory.
- Create a payment by passing billing address in payment create request, with confirm set to false.
```bash
--header 'api-key: dev_uHrHd27n2djqmWLoWqhpHPf1NmU2dsIbEguhDIB9ji7bQmzf9rLqw9TqrsRybqwm' \
--data-raw '{
"customer": {
"id": "cus_abc",
"email": "example@juspay.in"
},
"billing": {
"address": {
"first_name": "Narayan",
"last_name": "Bhat"
}
}
}'
```
- …
=> fix(address): use first_name if last_name is not passed

crates/router/src/core/payment_methods/cards.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/payment_method.rs, crates/router/src/utils/db_utils.rs
- [ x] Bugfix
Issue scenario faced:
1. create payment method (in /payments)
2. list payment method by customer (find all query that always went to db)
above api returns empty list
to handle cases where payment method entry present in kv but not drained to db yet, we have added a lookup in kv as well and combining data for findall from both kv and db
list payment method by customer and merchant was eventually consistent when payment method followed kv path,
change here is to combine values from db and redis
1. create payment method and drain data to db (can skip this step if payment method entries are already present in db but not kv for the customer <> merchant)
2. create another payment method through kv
3. list payment methods should reflect pm created through kv as well
`curl …
=> fix: added find all support for pm kv

crates/api_models/src/admin.rs, crates/api_models/src/payments.rs, crates/common_utils/src/consts.rs, crates/router/src/core/payment_link.rs, crates/router/src/core/payment_link/payment_link_initiate/payment_link.html, crates/router/src/core/payment_link/payment_link_initiate/payment_link.js, openapi/openapi_spec.json
Currently we show payment link with payment details, where
left side of the payment link contains payment details and the right side contains the sdk.
This is a merchant requirement where they want only the sdk to be displayed in payment link and it should be centered with custom color background.
Added `"display_sdk_only"` to `payment_link_config`
TestCase :
Do payment Create with the following curl and test all transaction mobile view etc for payment link.
```shell 
--header 'api-key: snd_oaidL49hiU3HmQRKSBsASyb1yANBmLJQJoDsulQbkSuZQiO7xQTj6ks0Alhtr3fD' \
--data '{
"amount": 1130,
"return_url": "https://hyperswitch.io", …
```
=> feat(payment_link): added display_sdk_only option for displaying only sdk without payment details

crates/api_models/src/lib.rs, crates/api_models/src/poll.rs, crates/common_utils/src/events.rs, crates/openapi/src/openapi.rs, crates/openapi/src/routes.rs, crates/openapi/src/routes/poll.rs, crates/router/src/compatibility/stripe/errors.rs, crates/router/src/core.rs, crates/router/src/core/errors/api_error_response.rs, crates/router/src/core/errors/transformers.rs, crates/router/src/core/poll.rs, crates/router/src/events/api_logs.rs, crates/router/src/lib.rs, crates/router/src/routes.rs, crates/router/src/routes/app.rs, crates/router/src/routes/lock_utils.rs, crates/router/src/routes/poll.rs, crates/router/src/types/api.rs, crates/router/src/types/api/poll.rs, crates/router_env/src/logger/types.rs, openapi/openapi_spec.json
add retrieve poll status api
This is a generic poll status retrieve API, which can be used in any polling flows. application will set a poll_id in backend as pending, and sends back a poll_id to client to keep polling until the status is completed. once it turns to completed, client will do the required action. This is a light weight alternative to actually polling with the payment status or similar heavy apis.
1. Currently we can't test the entire flow, but to check the API we can use the below CURL to check the poll status of some random poll_id, which is expected to give status as 404 Not Found (because it's not a valid one)
```
curl --location --request GET '{{BASE_URL}}/poll/status/poll_id' \ …
```
=> feat(router): add retrieve poll status api

crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/cybersource/transformers.rs
Fix simplified Applepay deserialization error
Hotfix for https://github.com/juspay/hyperswitch/pull/4389
1.Applepay non mandate simplified payment
=> fix(router): make payment_instrument optional

crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/cybersource/transformers.rs
Capture the Avs result and Cvv validation result from the connector response and populate it in hyperswitch payment response.
Earlier Response 
```
"card": {
"last4": "8914",
"card_type": null,
"card_network": null,
"card_issuer": null,
"card_issuing_country": null,
"card_isin": "412345",
"card_extended_bin": "41234567",
"payment_checks": null,
"authentication_data": null
},
"billing": null
}
```
With this PR
```
"card": {
"last4": "0101",
"card_type": null,
"card_network": null,
"card_issuer": null,
"card_issuing_country": null,
"card_isin": "400000",
"card_extended_bin": "40000000", …
```
=> feat(router): [BOA/CYBS] add avs_response and cvv validation result in the response

crates/diesel_models/src/kv.rs, crates/diesel_models/src/mandate.rs, crates/diesel_models/src/query/mandate.rs, crates/router/src/core/mandate.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments/flows/authorize_flow.rs, crates/router/src/core/payments/flows/setup_mandate_flow.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_response.rs, crates/router/src/core/payments/operations/payment_update.rs, crates/router/src/core/webhooks.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/mandate.rs, crates/router/src/db/payment_method.rs, crates/router/src/utils.rs, crates/router/src/utils/db_utils.rs, crates/storage_impl/src/lib.rs, crates/storage_impl/src/mandate.rs, crates/storage_impl/src/redis/kv_store.rs
- [ x] Enhancement
kv tables : payment_method, customer, mandate 
https://github.com/juspay/hyperswitch/pull/4275
https://github.com/juspay/hyperswitch/pull/4357
=> feat(mandate_kv): add kv support for mandate

crates/api_models/src/user/dashboard_metadata.rs, crates/diesel_models/src/enums.rs, crates/diesel_models/src/schema.rs, crates/router/src/core/user/dashboard_metadata.rs, crates/router/src/types/domain/user/dashboard_metadata.rs, crates/router/src/utils/user/dashboard_metadata.rs, migrations/2024-04-12-100908_add_dashboard_metadata_key_onboarding_survey/down.sql, migrations/2024-04-12-100908_add_dashboard_metadata_key_onboarding_survey/up.sql
Bug Fix: Add support for onboarding_survey enum 
Until now, we've been utilising Calendly to gather comprehensive information regarding both merchants and users. 
After this PR we will capture all the data from the dashboard and store it in dashboard_metadata for better insights.
1. Post OnboardingSurvey enum details  
Request 
``` 
curl --location 'http://localhost:8080/user/data?keys=OnboardingSurvey' \
--header 'Authorization: JWT token' \
--data '{
"OnboardingSurvey": {
"designation": "some designation",
"business_website": "some business website",
"about_business": "about business ",
"major_markets": [
"Europe"
],
"business_size": "business size",
"hyperswitch_req": "hyperswitch requirement",
"required_features": [
"FRM",
"Recon"
], …
```
=> fix(user): add onboarding_survey enum in dashboard metadata type

crates/router/src/connector/checkout.rs, crates/router/src/connector/checkout/transformers.rs, crates/router/src/connector/stripe.rs, crates/router/src/connector/stripe/transformers.rs, crates/router/src/core/webhooks.rs, crates/router/src/routes/webhooks.rs, crates/router/src/services/api.rs
Serde json value was being passed which doesn't support masking which exposed sensitive fields in the log. Rather than sending serde json value, the object struct should be passed to mask the sensitive fields
Corresponding main [PR](https://github.com/juspay/hyperswitch/pull/4400)
- Create a Merchant Account:
```
{
"about_business": "Online Retail with a wide selection of organic …
```
=> fix(connectors): Mask fields for webhook_resource_object

crates/diesel_models/src/query/user_role.rs, crates/router/src/core/user_role.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/user_role.rs
The PR add support to blocklist JWT token of the deleted user/user role. After delete signined user won't be able to perform any operation as token is blocklisted.
closes #4427 
SignIn/Signup
```
--data-raw '{
"email": "test1@gmail.com",
"password": "t"
}'
```
Invite another user
```
curl --location 'http://localhost:8080/user/user/invite' \
--data-raw '{
"email": "test3@gmail.com",
"name": "test3",
"role_id": "merchant_view_only"
}'
```
Sign in to this new user account and perform some operations JWT based, like listing payments etc.
Sing in  again into account from which this …
=> fix(user): blacklist token after delete user role

crates/diesel_models/src/query/user.rs, crates/router/src/core/user.rs, crates/router/src/core/user_role.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/user.rs, crates/router/src/services/email/types.rs, crates/router/src/types/domain/user.rs, crates/router/src/utils/user.rs
Pass the masked email in the SQL query function.
This fixes plaintext logging of email during find and update users by email. In this change instead of passing the plain-text email into the function, changed it to masked email which will mask the email while logging.
- Signup a new user
```bash
--data-raw '{
"email": "mani@test.in",
}'
```
- Signin the user
```bash
curl --location 'http://localhost:8080/user/v2/signin' \
--header 'Cookie: login_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOTg4N2YzNzQtNDYyZC00MDU1LWE4NGEtZDY5MzU3NTNmZjY2IiwibWVyY2hhbnRfaWQiOiJtZXJjaGFudF8xNzEzODYyNzU2Iiwicm9sZV9pZCI6Im9yZ19hZG1pbiI …
```
=> fix(masking): mask email while logging SQL query

crates/router/src/core/authentication.rs, crates/router/src/core/payments.rs
handle authorize redirection after webhook processing for external 3ds flow
In authorize flow, check if pull mechanism is enabled. Based on that call either payments confirm / payments sync. Check if, it's in requires_customer_action then set the poll_id in redis for client polling
Sanity of external 3ds payments
=> feat(router): handle authorize redirection after webhook processing for external 3ds flow

crates/router/src/connector/cybersource.rs, crates/router/src/connector/cybersource/transformers.rs
Following connector audit changes are done for wallets for connector Cybersource: 
- `paymentInformation.fluidData.descriptor` is passed in apple pay payments request
- HTML Error Response from connector is handled
https://github.com/juspay/hyperswitch/issues/4450
Manual flow apple payments need to be tested via cybersource.
Request:
```
--data-raw '{
"amount": 1900,
"business_label": "food", …
```
=> fix(connector): [CYBERSOURCE] Handle HTML Error Response and add Descriptor field in ApplePay payments request

crates/api_models/src/enums.rs, crates/connector_configs/src/connector.rs, crates/router/src/core/payments/access_token.rs, crates/router/src/core/payouts.rs, crates/router/src/core/payouts/access_token.rs, crates/router/src/core/payouts/retry.rs, openapi/openapi_spec.json
Access token flow is added for payout create and payout fulfill flow.
Note: Should not break current sanity
Only adds access token flow for Paypal Payouts(for now)
=> feat(core): [Payouts] Add access_token flow for Payout Create and Fulfill flow

crates/router/src/connector/stripe/transformers.rs
This PR adds optional `browser_info` where we pass the `user_agent` and `ip_address` in the name of added security for increasing trust as recommended [here](https://docs.stripe.com/radar/integration) in their docs.
This changes helps increase trust in the transactions done and reduce fraudulent transactions.
Tested locally.
For a Payment made that has `browser_info` passed, we're passing `ip_address` and `user_agent` info to the connector
Normal Payments
```curl
curl --location 'http://Localhost:8080/payments' \
--header 'api-key: dev_Ccavmev3Psp3EH7rvFLf0qrgsHbXwEFQKtBFq7Fbx9u2gOtbUXuLdVfhKiQ5Arls' \
--data-raw '{
"amount": 4545, …
```
=> refactor(connector): pass optional browser_info to stripe for increased trust

postman/collection-dir/adyen_uk/Flow Testcases/Happy Cases/Scenario14-Refund recurring payment/Payments - Create/request.json
Added billing address in the request for one of the scenarios which was failing in the automation setup
Adyen collection was failing 
Postman
=> ci(postman): Fix Adyen postman collection

.github/PULL_REQUEST_TEMPLATE.md, docs/building_docker_images.md
This PR adds a documentation page with information on building Docker images for the application server and other components. This includes:
1. The commands that can be used to build Docker images
2. How to select specific features (like AWS KMS, AWS SES integration, etc.)
3. Some FAQs such as the minimum system requirements and expected build times, etc.
This should aid interested users in building Docker images on their own hardware, or for a different architecture, etc.
N/A
=> docs: add documentation page for building Docker images

config/deployments/integration_test.toml, config/deployments/production.toml, config/deployments/sandbox.toml
add comments to configs for deployments to environments - sandbox.toml, production.toml
no testing needed
=> refactor(configs): add comments to configs for deployments to environments

crates/common_utils/src/access_token.rs, crates/common_utils/src/lib.rs, crates/router/src/core/payments/access_token.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/merchant_connector_account.rs
This PR modifies the way in which access tokens are stored in the redis. The key format is changed to 
`access_token_{merchant_id}_{merchant_connector_id}` More information can be found in the linked issue.
In order to support multiple connector accounts
- Run the Trustpay postman collection locally and check whether the access token is stored in redis
- All connectors using access token auth.
- Trustpay BankRedirect, Volt and Iatapay
=> refactor(access_token): use `merchant_connector_id` for storing access token

crates/router/src/services/authentication.rs
Use cookie if present otherwise use `authorization` header for authentication.
Use of cookie for authentication for better security.
Use any JWT auth API with cookies.
If cookie is present with `login_token` then app will use it for auth otherwise it will fallback to use `Authorization` header.
Example curl,
```curl
curl --location '<URL>/user/permission_info?groups=true' \
--header 'Cookie: login_token=<JWT>'
```
Above should give `200` when valid JWT is used.
```curl
curl --location 'localhost:8080/user/permission_info?groups=true' \
--header 'Authorization: Bearer <JWT>' \
```
Above should also give `200` when valid JWT is used.
=> feat(users): use cookie for auth

crates/api_models/src/payments.rs, crates/openapi/src/openapi.rs, crates/router/src/core/authentication.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/operations/payment_approve.rs, crates/router/src/core/payments/operations/payment_cancel.rs, crates/router/src/core/payments/operations/payment_capture.rs, crates/router/src/core/payments/operations/payment_complete_authorize.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_reject.rs, crates/router/src/core/payments/operations/payment_session.rs, crates/router/src/core/payments/operations/payment_start.rs, crates/router/src/core/payments/operations/payment_status.rs, crates/router/src/core/payments/operations/payment_update.rs, crates/router/src/core/payments/operations/payments_incremental_authorization.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/types.rs, openapi/openapi_spec.json
send poll_config in next_action of confirm response for external 3ds flow
1. Next action block of confirm response for external 3ds flow would contain poll_config (default poll_config is given if it's not set for a connector)
2. Update the poll_config for a connector
3. Next action block of confirm response for external 3ds flow would contain updated poll_config
=> feat(router): send poll_config in next_action of confirm response for external 3ds flow

crates/router/src/consts.rs, crates/router/src/services/authentication.rs, crates/router/src/services/authentication/blacklist.rs
Add single purpose token and authentication for single purpose token. This token will serves as a intermediate token and used to perform a certain action only.
Closes #4478 
This can be tested with upcoming PRs for reset password, TOTP, accept invite etc. Single purpose token and auth will be used for that. 
I also tested this locally, by changing auth type of  change passwor and it was working as expected.
=> feat(user): add single purpose token and auth

crates/api_models/src/events/payment.rs, crates/api_models/src/payments.rs, crates/openapi/src/openapi.rs, crates/router/src/compatibility/stripe/errors.rs, crates/router/src/core/errors/api_error_response.rs, crates/router/src/core/errors/transformers.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/routes/app.rs, crates/router/src/routes/lock_utils.rs, crates/router/src/routes/payments.rs, crates/router_env/src/logger/types.rs, openapi/openapi_spec.json
This PR adds a new endpoint to retrieve the extended card info (encrypted) stored in redis under a given merchant and payment. 
This PR cannot be tested until https://github.com/juspay/hyperswitch/issues/4482 goes in.
For local testing I manually set redis entry and tried to hit this newly added endpoint.
1. Create merchant account and api key
2. Create a payment
3. Got the payment id and merchant id and set the redis entry 
```
set merchant_1713971568_pay_1nrIoi2hRnzsy1V2cEv6_extended_card_info "eyJlbmMiOiJBMjU2R0NNIiwidHlwIjoiSldUIiwiYWxnIjoiUlNBLU9BRVAtMjU2In0.sTmCdgRVEz4hZKZ5VxQxq4Dt_V6v9O_96dIXy5F6lzdePOVQ2CwYJQeMhrsFjfk8kZrdOsfeOfFV1FVmxhWjREUvVBZKld5p47HDi4GAEDCX10HH9hIE3SD-IfU4D9riyE2MpIiWoB6xMVNxOvZSWAh2r_-UBgMzAoTAvz7ecmFJopRa8691up8H-Bc7DsVUxfAnEPef9bUIXd2Ej8vWR_XNyx9giPPwhYqYwt …
```
=> feat: add an api for retrieving the extended card info from redis

crates/diesel_models/src/schema.rs, crates/router/src/connector/netcetera/netcetera_types.rs, crates/router/src/connector/netcetera/transformers.rs, crates/router/src/connector/utils.rs, migrations/2024-04-28-095920_make_error_message_field_text/down.sql, migrations/2024-04-28-095920_make_error_message_field_text/up.sql
Two required params in SDK information were not serde renamed properly. This was causing SDK based authentication call to fail. Fixed it.
Other changes:
* Changed the type of `error_message` column in `authentication` table to `TEXT` from `VARCHAR(64)`. Because when length of error_message was greater than 64 chars, update operation was failing.
* Pass Device render options in authentication request because it is also required for SDK based authentication.
* Pass address-state as two character state code.
* pass country code in phone number after trimming `+` prefix
Manual
=> fix(connector): send valid sdk information in authentication flow netcetera

crates/api_models/src/payments.rs, crates/common_utils/src/request.rs, crates/masking/src/secret.rs, crates/router/src/connector/netcetera.rs, crates/router/src/core/payments/flows/session_flow.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/verification.rs, crates/router/src/services/api/client.rs
Made client Certificates and private keys secret across codebase. Because They are merchant secrets and should not be logged.
Certificate and private key was getting logged every time a request is made. This would leak the certificate and private key.
Manual
1. Integrate a connector that uses Client certificate and private key for api authentication and checked the logs. 
Netcetera can be used.
=> chore: make client certificate and private key secret across codebase

crates/common_utils/src/access_token.rs, crates/router/src/core/payments/access_token.rs, crates/router/src/db/merchant_connector_account.rs
This PR adds a fallback to use `connector_name` in cases where `merhant_connector_id` is not available.
- Run the postman tests for paypal and trustpay connectors
=> fix(access_token): use fallback to `connector_name` if `merchant_connector_id` is not present

crates/router/src/core/user_role.rs, crates/router/src/routes/user_role.rs, crates/router/src/services/authentication.rs, crates/router/src/services/authentication/blacklist.rs, crates/router/src/types/domain/user.rs
- Use single purpose JWT auth and single purpose token for accept invite
- Remove user without merchant JWT auth and user auth token
closes [#4497](https://github.com/juspay/hyperswitch/issues/4497)
- Enable email feature flag
- Signup/ singin 
- Invite a new user from multiple accounts
- Sign in to newly created user
- The response should be merchant select, then do accept invite, it will give dashboard entry response.
Current and expected behaviour of accept invite should remain same!
```curl
curl --location 'http://localhost:8080/user/user/invite/accept' \
--data '{
"merchant_ids": [
"merchant_id1",
"merchant_id2",
"merchant_id3"
],
"need_dashboard_entry_response": true
}'
```
If any of the `merchant_id` …
=> refactor(user): use single purpose token and auth to accept invite

config/deployments/integration_test.toml, config/deployments/production.toml, config/deployments/sandbox.toml
Updating env variables which were missed in this - https://github.com/juspay/hyperswitch/pull/2041
=> chore(payouts): update deployment configs for connector_customer

crates/api_models/src/payments.rs, crates/router/src/compatibility/stripe/payment_intents/types.rs, crates/router/src/compatibility/stripe/setup_intents/types.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_complete_authorize.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_update.rs, crates/router/src/types/api/payments.rs, crates/router/tests/payments.rs, crates/router/tests/payments2.rs, openapi/openapi_spec.json
Currently payment_method_data.billing cannot be passed without passing the payment method details. This causes problem for saved card payments which require `payment_method_data.billing`
`PaymentMethodData` is made optional. This means that the below data in `PaymentsRequest` does not throw any deserialization error.
```json
{
"billing": {
"address": {
"first_name": "Narayan",
"last_name": "Bhat"
}
}
}
}
```
To be able to pass only `payment_method_data.billing`.
- Create a payment and save the card.
```bash …
```
=> fix(api_request): make `payment_method_data` as optional

.github/workflows/release-stable-version.yml
This PR fixes a bug in the release stable version workflow where SemVer tags in the entire repository are not considered when obtaining previous and next tags. The bug is addressed by using `cocogitto` to obtain the previous and next tags, which considers all SemVer tags.
Fixes a bug in the release stable version workflow.
Locally, by ensuring the commands added here return the expected outputs.
=> ci(release-stable-version): use `cocogitto` to obtain previous and next tags

crates/diesel_models/src/authentication.rs, crates/diesel_models/src/schema.rs, crates/router/src/core/authentication/utils.rs, crates/router/src/db/authentication.rs, crates/router/src/types/api/authentication.rs, migrations/2024-05-08-111348_delete_unused_column_from_authentication/down.sql, migrations/2024-05-08-111348_delete_unused_column_from_authentication/up.sql
there are two fields in `authentication`(`three_ds_server_trans_id` and `threeds_server_transaction_id`) table that hold the same data. Removed `three_ds_server_trans_id` column which is not being populated at all. 
This caused confusion and as a result we were returning `three_ds_server_trans_id`. Which resulted in null being returned in `AuthenticationResponse` all the time.
Fixed that as well.
Manual.
Create a merchant with netcetera authentication connector and checkout payment connector
1. create a payment with "request_external_three_ds_authentication": true,
```
--header 'api-key: dev_yWDRHoFLgGtQRwkccTm9nMENIESjKEgkxratJOAjLRUHDFp71Mzhy0OJguhBk47h' \ …
```
=> fix(core): drop three_dsserver_trans_id from authentication table

crates/api_models/src/events/user.rs, crates/api_models/src/user.rs, crates/router/src/core/errors/user.rs, crates/router/src/core/user.rs, crates/router/src/routes/app.rs, crates/router/src/routes/lock_utils.rs, crates/router/src/routes/user.rs, crates/router/src/types/domain/user.rs, crates/router_env/src/logger/types.rs
This PR allows users to complete the TOTP flow.
It adds a new api `/user/totp/verify`, which will verify the totp entered by the user and mark the user totp status as set if it is in `InProgress`.
Closes #4596.
```
curl --location 'http://localhost:8080/user/totp/verify' \
--header 'Authorization: Bearer SPT with Purpose as TOTP' \
--data '{
"totp": "189646"
}'
```
If the TOTP is correct, the the API should return the next token that is in the current flow.
```
{
"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiZjYwOWFiMDAtNzg5Ny00NTU2LWFlMGMtNGQ4MDZmZGFkZTkxIiwicHVycG9zZSI6ImZvcmNlX3NldF9wYXNzd29yZCIsIm9yaWdpbiI6InNpZ25fdXAiLCJleHAiOjE3MTUyNjQ0NTF9.jkhMT8x1o5WhzNxqBbBwX4jS0TQuSpemlg9_5K5Kgk8",
"token_type": "force_set_password"
} …
```
=> feat(users): Create API to Verify TOTP

crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/cybersource/transformers.rs
BOA's Rsync response may or may not contain status.  But status is a mandatory field in the connector response, hence when the connector response do not contain status, it results in a de serialization error. 
This PR fixes the de-serialization error, by marking refund status as pending if connector do not send us the status. 
Hotfix for https://github.com/juspay/hyperswitch/pull/4570
1.Create a card payment with BOA
```
--header 'api-key:""' \
--data-raw '{
"amount": 100,
"customer_id": "A",
"phone": …
```
=>  Fix(connector): [BOA/CYBS] make rsync status optional

cypress-tests/cypress/e2e/ConnectorTest/00003-NoThreeDSAutoCapture.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00004-ThreeDSAutoCapture.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00005-NoThreeDSManualCapture.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00006-VoidPayment.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00007-SyncPayment.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00008-RefundPayment.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00009-SyncRefund.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00010-CreateSingleuseMandate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00011-CreateMultiuseMandate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00012-ListAndRevokeMandate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00013-SaveCardFlow.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00014-ZeroAuthMandate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00015-ThreeDSManualCapture.cy.js, cypress-tests/cypress/e2e/ConnectorUtils/Adyen.js, cypress-tests/cypress/e2e/ConnectorUtils/BankOfAmerica.js, cypress-tests/cypress/e2e/ConnectorUtils/Bluesnap.js, cypress-tests/cypress/e2e/ConnectorUtils/Cybersource.js, cypress-tests/cypress/e2e/ConnectorUtils/Nmi.js, cypress-tests/cypress/e2e/ConnectorUtils/Paypal.js, cypress-tests/cypress/e2e/ConnectorUtils/Stripe.js, cypress-tests/cypress/e2e/ConnectorUtils/Trustpay.js, cypress-tests/cypress/support/commands.js
-Resolved an issue in the savecard flow where card expiry was incorrectly sourced from the confirmBody.json, resulting in failures. Now, only the payment_token is utilized, ensuring successful payment transactions.
-This pull request includes refactoring of the card_pm details to accommodate the addition of banks and wallet flows.
To enhance test coverage for wallet and bank redirect flows.
Ran the test manually
=> ci(cypress): Fix card expiry for savecard flows

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml, crates/router/src/connector/bambora.rs, crates/router/src/connector/bambora/transformers.rs
ORIGINAL PR: https://github.com/juspay/hyperswitch/pull/4604
Following code improvements are done for connector Bambora:
- Optional fields that are being passed for payments request are removed
- 2XX and 4XX Error response are now handled properly
- Separate try_from are now used for all the flows
- Unwanted configs are removed
- Default case handling is removed
Following are the paths where you can find config files which have been updated:
1. `crates/connector_configs/toml/development.toml`
2. `crates/connector_configs/toml/sandbox.toml`
3. `crates/connector_configs/toml/production.toml`
https://github.com/juspay/hyperswitch/issues/4605
All the payment flows need to be tested(except void) for cards(Non-3DS) via Bambora.
1. Payments (Automatic):
Request -
``` …
```
=> fix(connector): [BAMBORA] Audit Fixes for Bambora

crates/router/src/connector/netcetera/transformers.rs
skip sending browser_information in authentication request for app device_channel
1. External 3DS with app device_channel for netcetera <> checkout
2. External 3DS with browser device_channel for netcetera <> checkout
=> fix(router): [NETCETERA] skip sending browser_information in authentication request for app device_channel

crates/router/src/utils.rs
The QR code generation function, 'new_from_data', is not working as expected. It is returning an empty string instead of the encoded image URL , leading to the failure of PIX QR code generation.
Earlier 
1. Create a PIX payment with Adyen. In response we must get a valid base64 encoded QR Code data
```
--header 'api-key: dev_Q1XJ407yuiyLeM1BwpMrGJos9JzwwHHztSVIypS3zsMkIYQqf1W7HA2NZhFpZyL4' \
--data-raw '{ …
```
=> Fix(router): fix QR data into image conversion

crates/api_models/src/payments.rs, crates/router/src/compatibility/stripe/payment_intents/types.rs, crates/router/src/core/payments/transformers.rs
Since the payment_method_billing has been made optional, If passed in the request, it will be present in the response too.
- Create a payment with confirm as false and with payment method billing.
```bash
--header 'api-key: dev_cgBkVO7LcoXTqBEqqBRZQGfz9utfGqUFm7wBLhU5hm3oD7HHjXteBtzXVxIgpChw' \
--data '{
"customer_id": "cus_PAxm0MeCGM5TowgDKPc9",
"billing": {
"address": {
"line3": null,
"first_name": "Narayan",
"last_name": "Hegde"
},
"phone": null,
"email": …
```
=> refactor(payment_method_data): send optional billing details in response

crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/cybersource/transformers.rs
We faced wrong de-serialization of Rsync response struct due to missing `cancelled` status
Hotfix for https://github.com/juspay/hyperswitch/pull/4620
Sanity test
1. Create a payment with BOA
```
--header 'api-key: ""' \
--data-raw '{
"amount": 100,
"customer_id": "A",
"billing": {
"address": {
"line2": "Harrison …
```
=> Fix(connector): [BOA/CYBS] add cancelled status to refund response 

cypress-tests/cypress/e2e/ConnectorTest/00013-SaveCardFlow.cy.js, cypress-tests/cypress/fixtures/create-payment-body.json, cypress-tests/cypress/fixtures/save-card-confirm-body.json, cypress-tests/cypress/support/commands.js
SaveCard flow is failing in the pipeline for BOA,Cybersource,Adyen.It requires billing country,city. So Added the billing details in the confirmBody
Tested in cypress
BOA:
Adyen
=> Ci(Cypress): Fix SaveCard Flow Test

crates/router/src/db/kafka_store.rs, crates/router/src/services/kafka.rs
#4595 
- Add TenantID to the KafkaEvent struct and add the extra param to the KafkaEvent constructor
- Made changes to the required placed 
- Supporting multi-tenancy
=> refactor(db): Add TenantID field to KafkaEvent struct

crates/router/src/consts.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_update.rs
add `max_amount` validation in payment flows
add max amount validation in payments create, confirm and update flow to throw an error if amount sent it more than 999999999
1. Pass amount greater than 999999999 in payments create with confirm = false
2. Pass amount greater than 999999999 in payments create with confirm = true
3. Pass amount greater than 999999999 in payments update
4. Pass amount greater than 999999999 in payments confirm
5. Any amount less than or equal to 999999999 should work without any error
=> fix(router): add `max_amount` validation in payment flows

crates/router/src/connector/adyen.rs, crates/router/src/connector/bambora/transformers.rs, crates/router/src/connector/mifinity/transformers.rs, crates/router/src/connector/multisafepay.rs, crates/router/src/connector/nexinets.rs, crates/router/src/connector/nuvei.rs, crates/router/src/connector/payme.rs, crates/router/src/connector/payone/transformers.rs, crates/router/src/connector/stripe.rs, crates/router/src/connector/utils.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/lib.rs, crates/router/src/middleware.rs, crates/router/src/routes/user.rs, crates/router/src/types/domain/address.rs, crates/router/tests/connectors/gpayments.rs, crates/router/tests/connectors/mifinity.rs, crates/router/tests/connectors/payone.rs
In case of 4xx, we need to log the content length of the request from the `content-length` header. This PR adds that enhancement.
To provide better support for debugging issues related to missing fields.
- Create a 4xx error and check for the content length log.
=> feat(middleware): log content_length for 4xx

crates/router/src/routes/payments/helpers.rs
Previously we were relying on the `X_FORWARDED_FOR` header value for extracting the ip address. This value would be available if there were proxies that populate this value. But if this has been done from the localhost or if there were no reverse proxies behind the application, then this header value would not be present. This has been fixed in this PR. 
We are using the `realip_remote_addr` function to extract the ip address from the request. This will look for the `X_FORWARDED_FOR` header, if not found, fallback to the socket ip address.
- Confirm a payment and then check for the log line
=> fix(core): use `realip_remote_addr` function to extract ip address

docker-compose-development.yml, docker-compose.yml
This PR adds a `pull_policy` field for hyperswitch services in the Docker Compose setup, so that the latest images are pulled from Docker Hub. In addition, this PR renames the `analytics` profile in the Docker Compose to `olap`, and moves the `fluentd`, `opensearch` and `opensearch-dashboards` services under the `olap` profile.
This would ensure that the latest images from Docker Hub are pulled and run, even if the user has old images cached on their local system.
Running the Docker Compose setup locally with `docker compose up -d` and `docker compose --profile olap up -d` and verified that the intended containers come up.
=> chore(docker-compose): specify `pull_policy` for hyperswitch services

.github/workflows/release-stable-version.yml, README.md, docs/try_local_system.md
This PR updates the release stable version workflow with a new step to update the `latest` tag to the newly created SemVer tag, and updates the Docker Compose setup guide to checkout the `latest` tag when cloning the repository.
This would help prevent failures with starting the app server when running off of the `main` branch, specifically when a new enum variant has been introduced in the `main` branch, but is not available in the latest stable release. Checking out the latest stable release when running the Docker Compose setup would ensure that a compatible configuration file would be used, and thus reduce server startup failures.
I've tested out the new step added in the stable release workflow by running the command locally, first by creating the `latest` tag manually to point to an …
=> docs: update Docker Compose setup guide to checkout `latest` tag

crates/router/src/core/payments.rs
handle connector authentication technical failures and skip confirm in authorize flow only when authentication_type is not challenge
=> fix(router): handle connector authentication technical failures and skip confirm in authorize flow only when authentication_type is not challenge

crates/router/src/db/cache.rs, crates/router/tests/cache.rs, crates/storage_impl/src/redis/cache.rs, crates/storage_impl/src/redis/pub_sub.rs
Currently `Cache` is a type having inner value as `MokaCache`.
```
pub struct Cache {
inner: MokaCache<String, Arc<dyn Cacheable>>,
}
```
There's a deref impl on this type which returns the inner `MokaCache`. We should instead have custom methods on `Cache` which calls the `MokaCache` methods instead of deref doing the job. There's already custom methods available on `Cache`. This PR refactors it to invoke these methods instead of calling it on the deref of `Cache`.
Basic sanity tests should suffice
=> refactor(cache): remove `deref` impl on `Cache` type

crates/router/src/core/payments/operations/payment_confirm.rs
add support to enable pm_data and pm_id in payments response
- Create a MA and a MCA 
- Create a Off session payment with Customer Acceptance
> 
```
Create
--header 'api-key: dev_Mg6I2ovVxNBp6ZJmf84J2CPS3aDBtKeara9bYS08ep8h8PknW2S8yiprQGwmc4lQ' \
--data-raw '{
"amount": 6777,
"customer_id": "new-c777", …
```
=> refactor(core): add support to enable pm_data and pm_id in payments response

Cargo.lock, Cargo.toml, crates/redis_interface/Cargo.toml, crates/redis_interface/src/commands.rs, crates/redis_interface/src/lib.rs, crates/router_env/Cargo.toml
…ndency for redis_interface
This PR removes `router_env` as a dependency of `redis_interface` crate. To accomplish this we declare `tracing` as a workspace dependency and use that individually in `redis_interface` and `router_env`.
This is done to make `redis_interface` more self-sufficient and improve its usage as a autonomous dependency.
This is dependency relocation, no domain logic or framework code was changed
=> chore: move tracing to workspace deps and remove router_env as a dependency of redis_interface

crates/api_models/src/payments.rs, crates/diesel_models/src/authentication.rs, crates/diesel_models/src/schema.rs, crates/router/src/connector/netcetera/transformers.rs, crates/router/src/connector/threedsecureio/transformers.rs, crates/router/src/core/authentication/utils.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/db/authentication.rs, crates/router/src/types/authentication.rs, migrations/2024-05-21-075556_add_directory_server_id_in_authentication/down.sql, migrations/2024-05-21-075556_add_directory_server_id_in_authentication/up.sql, openapi/openapi_spec.json
send message_version and directory_server_id in next_action block of three_ds_data for external 3ds flow
message_version and directory_server_id are required for mobile sdk to initiate the netcetera sdk
**Tested Manually**
1. Initiate 3DS Authentication with Netcetera and can see the newly added fields in next_action block for external 3DS
=> feat(router): send message_version and directory_server_id in next_action block of three_ds_data for external 3ds flow

crates/euclid/src/frontend/dir.rs, crates/kgraph_utils/src/mca.rs
This PR fixes a couple of failing unit tests in the `euclid` and `kgraph_utils` crates.
Running unit tests locally. API Tests not required
=> ci: fix unit tests for routing

crates/analytics/src/auth_events/accumulator.rs, crates/analytics/src/auth_events/core.rs, crates/analytics/src/auth_events/metrics.rs, crates/analytics/src/auth_events/metrics/challenge_attempt_count.rs, crates/analytics/src/auth_events/metrics/frictionless_success_count.rs, crates/analytics/src/clickhouse.rs, crates/analytics/src/sqlx.rs, crates/analytics/src/types.rs, crates/api_models/src/analytics/auth_events.rs
Modified authentication analytics queries to query api_events
```
curl --location 'localhost:8080/analytics/v1/metrics/auth_events' \
--header 'Authorization: Bearer {token}' \
--data '[
{
"timeSeries": {
"granularity": "G_ONEDAY"
},
"timeRange": {
"startTime": "2024-01-13T18:30:00Z",
"endTime": "2024-04-30T18:30:00Z"
},
"metrics": [
"three_ds_sdk_count",
"authentication_attempt_count",
"authentication_success_count",
"challenge_flow_count",
"frictionless_flow_count",
"challenge_attempt_count",
"challenge_success_count",
"frictionless_success_count",
]
}
]'
```
```
{
"queryData": [
{
"three_ds_sdk_count": 3,
"authentication_attempt_count": 3,
"authentication_success_count": 3,
"challenge_flow_count": 2, …
```
=> feat: authentication analytics 

crates/api_models/src/payment_methods.rs, crates/router/src/core/payment_methods/cards.rs
This pr is to mask the email address being logged in the payment method list response.
-> Create a merchant account and mca
-> Create a payment with confirm false
```
curl --location 'http://localhost:8080/account/payment_methods?client_secret=pay_jviyQiUsX9uHI99VXUlF_secret_lHrA6q5GKvNvd5a0blUQ' \
--header 'api-key: pk_dev_df002da8beb74682ac3e8677a4b82217'
```
in the below log we can see the email address being logged (this is without the changes in this pr)
after the changes the email is being masked
=> fix(payment_methods): mask the email address being logged in the `payment_method_list` response logs

crates/router/src/core/payments.rs, crates/router/src/core/payments/helpers.rs
For a merchant account there are be n number of connectors and its not mandatory that apple pay needs to be enabled for all of them. So while fetching apple pay retry connectors log the error if the apple pay metadata parsing fails. This is required as this will create unnecessary errors for the connectors that does not have the apple pay metadata enabled as for them apple pay metadata will be not there.
-> Create a merchant account
-> Enable gcm for the `merchant_id`
```
curl --location 'localhost:8080/configs/' \
--data '{
"key": "should_call_gsm_{merchant_id}",
"value": "true"
}'
```
-> Set the maximum retries count
```
curl --location 'localhost:8080/configs/' \
--header …
```
=> fix(payment_methods): log and ignore the apple pay metadata parsing error while fetching apple pay retry connectors

crates/api_models/src/payments.rs, crates/router/src/types/transformers.rs, openapi/openapi_spec.json
This pull request introduces a modification to the **PaymentAttemptResponse** struct by adding two new fields: **client_source** and **client_version**. These fields are intended to provide additional context about the client making the payment attempt, which can be valuable for analytics, debugging, and improving overall user experience.
**client_source**: A string representing the source of the client making the payment attempt (e.g., "mobile_app", "web_app", "api_client").
**client_version**: A string indicating the version of the client making the payment attempt (e.g., "1.0.0", "2.3.1").
Added descriptions for **client_source** and **client_version** to ensure developers understand their purpose and usage.
**Backward Compatibility:**
This change is backward compatible as it only adds …
=> fix: include client columns in payment attempts response struct

crates/hyperswitch_domain_models/src/lib.rs, crates/hyperswitch_domain_models/src/router_request_types.rs, crates/hyperswitch_domain_models/src/router_request_types/authentication.rs, crates/hyperswitch_domain_models/src/router_response_types.rs, crates/hyperswitch_domain_models/src/router_response_types/disputes.rs, crates/hyperswitch_domain_models/src/router_response_types/fraud_check.rs, crates/router/src/connector/adyen.rs, crates/router/src/connector/nuvei.rs, crates/router/src/connector/stripe/transformers.rs, crates/router/src/core/authentication/types.rs, crates/router/src/core/payments/flows/authorize_flow.rs, crates/router/src/core/payments/flows/complete_authorize_flow.rs, crates/router/src/core/payments/flows/setup_mandate_flow.rs, crates/router/src/core/payments/operations/payment_response.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/core/payments/types.rs, crates/router/src/routes/fraud_check.rs, crates/router/src/services/api.rs, crates/router/src/types.rs, crates/router/src/types/authentication.rs, crates/router/src/types/fraud_check.rs
Moved all router_data response models and a few request models to hyperswitch domain models crate.
Checked if the code compiles successfully.
=> refactor(core): move router data response and request models to hyperswitch domain models crate

crates/masking/src/strong_secret.rs
Implement `StrongEq` for `Vec<u8>`
Implement `StrongEq` for deriving `Eq` for `StrongSecret<Vec<u8>>`.
NA. Testing is not needed, compiler guided.
=> fix: implement StrongEq for Vec<u8>

crates/api_models/src/user.rs, crates/router/src/consts/user.rs, crates/router/src/core/errors/user.rs, crates/router/src/core/user.rs, crates/router/src/routes/app.rs, crates/router/src/routes/lock_utils.rs, crates/router/src/routes/user.rs, crates/router/src/utils/user.rs, crates/router/src/utils/user/two_factor_auth.rs, crates/router_env/src/logger/types.rs
- Begin TOTP will now insert the TOTP secret in redis instead of DB directly, which allows the old secret to stay if it exists and recovery codes are also removed from Begin TOTP.
- Verify TOTP will now send 200 OK and puts the timestamp in the redis when the TOTP is verified.
- Update TOTP is a new API which will take the TOTP and verifies the TOTP against the redis secret instead of db secret. If the TOTP is correct, it will replace the redis secret in the db.
Closes #4764.
Closes #4707.
1. TOTP Routes
1. Begin TOTP
```curl
curl --location 'http://localhost:8080/user/2fa/totp/begin' \
--header 'Authorization: Bearer SPT with Purpose as TOTP'
```
```
{
"secret": {
"secret": "Q54GEKFSVTP4FU3YHDFMEN5KMGD2P3IN",
"totp_url": "otpauth://totp/Hyperswitch:mani.dchandra%40juspay.in?secret=Q54GEKF …
```
=> feat(users): Add redis in Begin and Verify TOTP and create a new API that updates TOTP

cypress-tests/cypress.config.js, cypress-tests/cypress/e2e/ConnectorTest/00008-RefundPayment.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00015-ThreeDSManualCapture.cy.js, cypress-tests/cypress/support/commands.js
3DS payments were failing in the refund test in Cypress headless mode. I added the timeout and properly configured the hooks to fetch the redirection URL correctly.
To ensure the test runs successfully without any failures in the CI/CD pipeline.
Tested locally in the headless mode
Stripe
Cybersource
NMI
Adyen
=> Fix(Cypress): Fixing 3DS payment failure in headless mode

crates/router/src/core/user.rs, crates/router/src/routes/app.rs, crates/router/src/routes/lock_utils.rs, crates/router/src/routes/user.rs, crates/router/src/utils/user/two_factor_auth.rs, crates/router_env/src/logger/types.rs
Add support to reset TOTP
Closes [#4820](https://github.com/juspay/hyperswitch/issues/4820)
Use the curl to reset TOTP when it is already setup (from inside dashboard):
```
curl --location 'http://localhost:8080/user/2fa/totp/reset' \
--header 'Cookie: Cookie_1=value'
```
Response:
```
{
"secret": {
"secret": "VERUDBNHLYZDGFTKNXY2VVP4EQ5GOBUB",
"totp_url": "otpauth://totp/Hyperswitch:ver%40gmail.com?secret=VERUDBNHLYZDGFTKNXY2VVP4EQ5GOBUB&issuer=Hyperswitch"
}
}
```
The Response can be used to generate new QR and reset TOTP.
=> feat(users): add support to reset totp

.cargo/config.toml, crates/router/src/core/disputes.rs, crates/router/src/core/fraud_check.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments/tokenization.rs, crates/router/src/core/refunds.rs, crates/router/src/core/webhooks.rs, crates/router/src/core/webhooks/webhook_events.rs, crates/router/src/routes/cards_info.rs, crates/router/src/routes/customers.rs, crates/router/src/routes/disputes.rs, crates/router/src/routes/mandates.rs, crates/router/src/routes/payment_link.rs, crates/router/src/routes/payments.rs, crates/router/src/routes/poll.rs, crates/router/src/routes/refunds.rs, crates/router/src/routes/routing.rs, crates/router/src/routes/webhook_events.rs, crates/router/src/workflows/outgoing_webhook_retry.rs
This PR enables the `clippy::large_futures` lint and addresses warnings that arise due to the lint.
Hopefully helps keep async functions which use a lot of stack space in check.
N/A
=> chore: enable `clippy::large_futures` lint

cypress-tests/cypress/e2e/ConnectorTest/00000-AccountCreate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00001-CustomerCreate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00002-ConnectorCreate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00003-NoThreeDSAutoCapture.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00004-ThreeDSAutoCapture.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00005-NoThreeDSManualCapture.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00006-VoidPayment.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00007-SyncPayment.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00008-RefundPayment.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00009-SyncRefund.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00010-CreateSingleuseMandate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00011-CreateMultiuseMandate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00012-ListAndRevokeMandate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00013-SaveCardFlow.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00014-ZeroAuthMandate.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00015-ThreeDSManualCapture.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00016-BankTransfers.cy.js, cypress-tests/cypress/e2e/ConnectorTest/00017-BankRedirect.cy.js
This PR removes all the `console.log()`, `cy.task()` that exposes the `globalState`
NIL
To avoid possible exposure of admin api keys and other sensitive info.
print statements should not affect flow of a test. it should just work as before.
=> chore(cypress): remove logs that expose `globalState`

crates/router/src/connector/netcetera.rs, crates/router/src/connector/netcetera/transformers.rs
Few fields in netcetera error object that were marked required in the official api documentation were missing in api response body. This caused deserialization failure at hyperswitch. 
So made those fields optional.
Manual.
Tested sanity of Netcetera Authentication Connector.
=> fix(connector): make few fields optional in struct NetceteraErrorDetails

crates/router/src/connector/klarna.rs, crates/router/src/connector/klarna/transformers.rs, crates/router/src/connector/utils.rs
Add shipping Address in Klarna Session and Payment Request
1. Create a Merchant 
```
{
"address": {
}
},
"return_url": "https://google.com/success", …
```
=> refactor(connector): [Klarna] Add shipping Address in Klarna Session and Payment Request

crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/retry.rs
This pull request addresses a bug where the client_source and client_version fields were not populated for payment attempts created via retry cases. This issue resulted in these fields being correctly displayed for the first payment attempt but missing in subsequent retry attempts.
**Issue:**
Problem: For the first payment attempt, the client_source and client_version fields were populated correctly. However, for subsequent payments made through retry mechanisms, these fields were not populated, leading to incomplete data in the PaymentAttemptResponse struct.
**Impact**: This caused inconsistencies in tracking the source and version of clients across different payment attempts, impacting analytics, debugging, and support.
**Backward Compatibility:**
This fix is backward compatible as it …
=> fix: include client_version and client_source in retried payments

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/sandbox.toml, crates/router/src/configs/defaults.rs
This pr fixes afterpay clearpay required fields for adyen. This also removes przelewy payment method for adyen from dashboard configs since adyen doesn't support that payment method.
1) configure the afterpay clearpay while create merchant connector account.
2) curl --location --request GET 'http://localhost:8080/account/payment_methods?client_secret={{client_secret}}' \
--header 'api-key:{{publishable_key}}'
response should contain billing address information & billing email.
response: 
```
{
"redirect_url": "https://google.com/success",
{
{
"payment_method_type": "paypal",
"payment_experience": [
{
"payment_experience_type": "redirect_to_url", …
```
=> fix(connector): [Adyen]add required fields for afterpay clearpay

crates/router/src/connector/adyen/transformers.rs
1. Make refusal_reason optional as, we don't get it every time 
2. Capture `connector_response_reference_id` in error response.
1. Create a Wechat Pay Payment via Adyen
```
{
"return_url": "https://webhook.site/6fed9c8b-2a57-43cc-9eb1-9629ff4d2f80",
"payment_method_type": "we_chat_pay",
"wallet": {
"we_chat_pay_redirect": {}
}
}
}
```
Response
```
{
"payment_id": …
```
=> refactor(connector): [Adyen] handle redirection error response

crates/router/src/core/user.rs, crates/router/src/types/domain/user.rs
Internal signup will now use the `org_id` of `juspay000` and insert it in `user_roles`.
Closes #4887.
```
curl --location 'http://localhost:8080/user/internal_signup' \
--header 'api-key: admin-api-key' \
--data-raw '{
"name" : "name",
"email" : "email",
}'
```
In `user_roles` table, the `org_id` is the correct one as the `juspay000` merchant account. These are the queries I've used to verify.
```sql
select organization_id from merchant_account where merchant_id = 'juspay000'
```
```sql
select org_id from user_roles where merchant_id = 'juspay000'
```
In both cases, `org_id` should be same for newly created user.
=> fix(users): Populate correct `org_id` for Internal Signup

crates/router/src/core/webhooks/outgoing.rs
This PR refactors the outgoing webhooks logic to raise errors to the analytics pipeline (involving Kafka and ClickHouse) in case the webhook was not at all sent due to API client errors, or if the merchant server returns a non-2xx HTTP response.
This was done in two steps:
1. First, the success and error handling closures were moved out as functions within the outgoing webhooks module.
2. Then, the error handling functions were updated to return errors.
Since it's easier to follow along when reviewing one commit at a time, I'd suggest the reviewers to do the same.
This fixes a bug where failed webhook deliveries were falsely displayed as successful on the control center, since the analytics pipeline had no information that an error had occurred.
With a local Kafka and ClickHouse setup:
1. …
=> refactor(outgoing_webhooks): raise errors in the analytics pipeline in case of API client errors or non-2xx responses

crates/router/src/connector/bankofamerica/transformers.rs
Refund Status in Bankofamerica refund response is returning a new value 201 along with errorInformation.reason as PROCESSOR_DECLINED which is being handled now.
https://github.com/juspay/hyperswitch/issues/4906
We are unable to recreate the status "201" on BOA sandbox and hence only normal refund flow should be tested.
Refund Request:
```
--data '{
"payment_id": "pay_O9ziXsg3MNqO3z40T5G7",
"amount": 1404,
"reason": "Coumer returned product",
"refund_type": "instant",
"metadata": {
"login_date": "2019-09-10T10:11:12Z"
}
}'
```
Refund Response:
```
{
"refund_id": …
```
=> feat(connector): [BOA] Handle refund status 201

crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/cybersource/transformers.rs
State and Zip is made optional for BOA and Cybersource transactions for countries other than USA and Canada.
https://github.com/juspay/hyperswitch/issues/4917
We need to test apple pay, google pay and cards payments for BOA and Cybersource. For each payment method we need to test using at least 3 countries which should include US, Canada and Israel. 
billing.address.state and billing.address.zip have been made optional only for countries other than USA and Canada.
Request:
```
--data-raw '{
"amount": 101,
"customer_id": …
```
=> feat(connector): [BOA/CYB] Make state,zip optional for Non US CA Txns

crates/common_utils/src/types.rs, crates/router/src/connector/cryptopay.rs, crates/router/src/connector/cryptopay/transformers.rs, crates/router/src/types/api.rs, crates/router/tests/connectors/cryptopay.rs
The conversion of a f64 base amount to i64 minor amount is causing parsing error in cryptopay. This needs to be fixed by using decimal type instead of f64.
Also this Pr adds amount conversion framework to Cryptopay
Note: Cryptopay uses String Major Unit
https://github.com/juspay/hyperswitch/issues/4929
We need to test Cryptopay payments for various different amounts.
Request: 
```
--data-raw '{
"amount": 115, …
```
=> refactor(connector): [CRYPTOPAY] amount conversion framework added

crates/router/src/db/kafka_store.rs
As part of multitenancy feature, we added tenant prefix in the redisinterface directly. so this specific handling of tenant id in append_stream function is not required anymore
#4475 
Remove tenant id from redis stream key of kafkaStore
1. Make a payment and see if the entries are added in process tracker
2. Check if the analytics for the payment is visible from the dashboard
=> fix(multitenancy): remove tenant id from redis stream key of kafkaStore

crates/drainer/src/settings.rs, crates/external_services/src/file_storage.rs, crates/external_services/src/managers/encryption_management.rs, crates/router/src/routes/app.rs
Currently, the encryption interface and file storage interface client is wrapped with `Box`. These clients live in `AppState`. Since state is cloned for each api handler, wrapping the clients in Arc will help in not cloning the actual internal data rather maintaining a counter on the single client instance.
Basic sanity testing should suffice
=> refactor: wrap the encryption and file storage interface client in appstate with `Arc` as opposed to `Box`

crates/router/src/core/admin.rs
Wrote a validation function to validate ConnectorAuthType being passed during MCA create and update.
Manual.
1. SignatureKey
```
curl --location 'http://localhost:8080/account/postman_merchant_GHAction_3589e3c3-2b53-4627-b0f9-8449b37a9c07/connectors' \
--data '{
"api_key": "",
"key1": "",
"api_secret": ""
},
"metadata": {
"acquirer_bin": "438309",
"acquirer_merchant_id": "00002000000"
}
}'
```
2. BodyKey
``` …
```
=> fix: add validation for connector authentication type during mca create and update operation

config/deployments/integration_test.toml
This PR reverts typo introduced in https://github.com/juspay/hyperswitch/pull/4398 in `integration_test.toml` that resulted in deployments to fail.
Resolves #4957
config/deployments/integration_test.toml
NIL
Deployments should succeed.
=> chore(env): revert typo in integ env

crates/router/src/core/payment_methods/cards.rs
Previously we did not support the deletion of the Default Payment Method, if it's the only PM for the particular customer. In this PR we enable deletion of default Payment Methods
- Create a MA and a MCA
- Do a payment , with `setup_future_usag:off_session`; the card would be saved
- Do a List PM for Customers, you'll have only one card , which has been set as default
```
Response
{
"customer_payment_methods": [
{
"payment_token": "token_FC8TupTKMEmhtM69dmYS",
"payment_method_id": "pm_Syvbg2Nb8mGdZC9oi4Sv",
"payment_method_issuer": null,
"payment_method_issuer_code": null,
"installment_payment_enabled": false,
"payment_experience": [
"redirect_to_url"
],
"card": {
"scheme": …
```
=> refactor(payment_methods): Enable deletion of default Payment Methods

api-reference/openapi_spec.json, crates/api_models/src/payments.rs, crates/connector_configs/src/common_config.rs, crates/connector_configs/src/connector.rs, crates/connector_configs/src/response_modifier.rs, crates/connector_configs/src/transformer.rs, crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml, crates/hyperswitch_domain_models/src/payment_method_data.rs, crates/router/src/connector/mifinity/transformers.rs
1. Move destination_account_number from Mifinity payment method data to Mifinity metadata
2. Wasm changes for adding destination_account_number in MCA for Mifinity in dashboard
1. create mca for Mifinity 
```
{
"connector_name": "mifinity",
"api_key": "7KU1tRYnjar-AnkFGJZdUa244czauGxOCuOZq9HYOUciSOZY5Oj5Q5IsvJRSZkZNM2IPJI5MKpo_jVJ_2Ay1HavSdGwkplc0z7zZE9OAJ0Djxbvo-ae-1_Ui6jTjQdDx"
},
{
{
"payment_method_type": "mifinity",
"recurring_enabled": false,
"installment_payment_enabled": false, …
```
=> refactor(connector): [Mifinity]Move destination_account_number from pmd to Mifinity Metadata

crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/cybersource/transformers.rs
Make billTo fields optional in connector BOA and Cybersource. This change is required for prod testing.
https://github.com/juspay/hyperswitch/issues/4950
Testing should be done for BOA and Cybersource. Payments should work if billing address is passed and payments should be failed at connector if billing address is not passed.
Failure Request:
```
--header 'api-key: dev_mF5ApaF7qylFyewcvRbsOVw9bhOUy2ufhC8MutbWQvLwNWWqX7CZGDPf5SnZ6KRE' \
--data-raw '{
"amount": 101,
"customer_id": "mearX",
"email": "guest@deepanshu.com", …
```
=> feat(connector): [BOA/CYB] Make billTo fields optional

crates/router/src/core/payment_methods/utils.rs
This change will make the country nodes as weak so that for the cases we don't have billing address in mca. It will ignore the nodes and move with other checks.
```
curl --location 'http://127.0.0.1:8080/account/merchant_1718275101/connectors' \
--data '
{
"api_secret": "xx+xx=",
"api_key": "xxxxx",
"key1": "xxxxx"
},
{
{
"Visa",
"Mastercard"
], …
```
=> refactor(core): make country aggregator nodes weak for list payment methods

crates/analytics/src/query.rs, crates/router/src/connector/globalpay/response.rs, crates/router/tests/connectors/adyen.rs, crates/router/tests/connectors/payme.rs, crates/router/tests/connectors/square.rs, crates/router/tests/connectors/stax.rs, crates/router/tests/connectors/utils.rs, crates/router/tests/connectors/wise.rs
This PR addresses the clippy lints occurring due to new rust version 1.79
Basic sanity testing should suffice
=> chore: address Rust 1.79 clippy lints

crates/router/src/core/user.rs, crates/router/src/types/domain/user.rs, crates/router/src/types/domain/user/decision_manager.rs
Currently verify email API will be picked by the decision manager only if the user is not verified.
But this API should be called always in case of verify email and magic link flow. This PR fixes it.
Closes #4970.
```
curl --location 'http://localhost:8080/user/connect_account' \
--data-raw '{
"email": "user email"
}'
```
You will receive a magic link to the email provided.
Once the link in the email is used to login to dashboard, the link should not work anymore.
=> fix(users): Magic link is not expiring after one usage

crates/diesel_models/src/process_tracker.rs, crates/router/src/bin/scheduler.rs, crates/router/src/core/api_keys.rs, crates/router/src/core/payment_methods/vault.rs, crates/router/src/core/refunds.rs, crates/router/src/core/webhooks/outgoing.rs, crates/router/src/db/kafka_store.rs, crates/router/src/types/storage.rs, crates/router/src/workflows/api_key_expiry.rs, crates/router/src/workflows/outgoing_webhook_retry.rs, crates/router/src/workflows/payment_sync.rs, crates/scheduler/src/consumer.rs, crates/scheduler/src/consumer/workflows.rs, crates/scheduler/src/db/process_tracker.rs
When below command is executed in sandbox DB, we get a set of "distinct" `business_status`es that is specified for process tracker:
```sql
SELECT DISTINCT(business_status) FROM process_tracker;
```
For debugging and fun, execute to learn more about process tracker and its behavior:
```sql
SELECT DISTINCT(name, retry_count, business_status, status), created_at FROM process_tracker order by created_at desc LIMIT 10000;
```
The main goal for us here is to keep all the `business_status`es in a single place, confined for ease of access and increased readability. This also helps us keep track of the statuses we use.
We need to keep a track of the statuses that we use in `process_tracker`
This should not require any testing as the change done is here just a mere replacement of hardcoded string …
=> chore(process_tracker): use `const` instead of `String` for `business_status`

docker-compose-development.yml, docker-compose.yml
This PR includes the following changes to the Docker Compose setup:
- Adds health checks for PostgreSQL and Redis containers.
- Specifies the dependencies among services.
- Specifies the correct environment variables for the `hyperswitch-web` service so that the SDK demo app works correctly.
More robust Docker Compose setup, and enabling the SDK demo app.
Locally, with the Docker Compose setup:
=> chore(docker-compose): pass correct configuration values for running SDK demo app 

crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payment_methods/transformers.rs, crates/router/src/core/payments/tokenization.rs
When the same card is being saved with metadata changes, the other fields of card like `card_network`, `card_issuer`, `scheme`, `card_type`, `card_isin`, `card_issuing_country` were getting saved with hardcoded value as `None` instead of getting its value from the existing saved card. This PR fixes the issue
1. Save a card 
```
--header 'api-key: dev_bS3Uz99HdVusSOy9rHtZqcevmpHt9L4N6WvNt5d16SwBgz53crKKEd6pCMrvVVbH' \
--data-raw '{
"amount": 499,
"customer_id": "cus_6Syv31iU1EeDKyfN1U7O",
}, …
```
=> fix(payment_methods): populate card fields while saving card again during metadata change condition

crates/router/src/core/payments.rs, crates/router/src/services/api.rs
Add a logger for failure of sessions call when the call fails at connector's end.
https://github.com/juspay/hyperswitch/issues/5037
The following logs should be checked:
1. Session call fails without calling connector:
- Payments Create(Klarna): 
Request:
```
--header 'api-key: dev_jOiTovkpGinwxAIGAlEyC9SiVkJCfK3Tc1NNOntnkLMaeaM7U7xtde8a88LhPVlm' \
--data-raw '{
"amount": 6500,
"client_secret": "pay_QWcuxERT26fPFELkA1d6_secret_m9LRWGDRVRckiKvfnNUZ",
"customer_id": "cdsdcwmn",
"customer": {
"id": "cdsdcwmn",
"email": "user@gmail.com"
},
"description": "Hello this is description", …
```
=> feat(core): Add logger for sessions call failure

crates/router/src/core/payments/tokenization.rs
Currently there is no duplication check for google pay and we will create a new payment method entry for every google pay payment CIT with `"setup_future_usage": "on_session"`. This is not the case in cards as locker handles the card duplication. Since we do not have a parameter handle duplication check for a google pay, we have to go with a approach of a customer can have only one saved google pay payment method.
In this approach we list all the saved payment method for a customer during every google pay CIT and check if any of them have the `payment_method_type` is `google_pay` if it is then we just return already saved `payment_method_id`.
-> Create a merchant connector account with google pay enabled
-> Do a CIT with `setup_future_usage`
``` …
```
=> feat(router): add payment method type duplication check for `google_pay`

crates/router/src/configs/defaults.rs
Refactor path for dynamic field name - `first_name` , `last_name` and `country`
1. create mca for Mifinity 
```
{
"connector_name": "mifinity",
"api_key": "7KU1tRYnjar-AnkFGJZdUa244czauGxOCuOZq9HYOUciSOZY5Oj5Q5IsvJRSZkZNM2IPJI5MKpo_jVJ_2Ay1HavSdGwkplc0z7zZE9OAJ0Djxbvo-ae-1_Ui6jTjQdDx"
},
{
{
"payment_method_type": "mifinity",
"recurring_enabled": false,
"installment_payment_enabled": false,
"accepted_countries": {
"type": "enable_only",
"list": [
"DE"
]
}
}
]
}
],
"metadata": {
"city": …
```
=> refactor(connector): [Mifinity]dynamic fields for mifinity

crates/redis_interface/src/lib.rs, crates/router/src/db/configs.rs, crates/router/src/services.rs, crates/storage_impl/src/redis/cache.rs, crates/storage_impl/src/redis/pub_sub.rs
In the current Redis pub-sub implementation, a subscriber spawns a thread to handle all messages published to a channel. As a result, if a subscriber is invoked multiple times (even for subscribing to the same channel), it creates multiple threads for handling messages, which is not the desired behaviour. Ideally, we want to have only one subscriber thread handling all messages published to different channels. To achieve this, we maintain an atomic boolean variable, initially set to `false`, indicating whether the subscriber handler thread has been spawned. This variable will be set to `true` during the first subscriber invocation, thus preventing the creation of multiple threads during subsequent subscriber invocations. 
In the current implementation, the subscriber has been invoked 2 …
=> refactor(redis): spawn one subscriber thread for handling all the published messages to different channel

crates/router/src/core/payments.rs
avoid considering pre-routing results during `perform_session_token_routing`
As there is a logic to filter out the apple pay payment method if apple pay is already saved. But this should not be the save when performing the session token (`perform_session_token_routing`). 
-> Create mca with apple pay configured
-> Create payment with apple pay
```
{
"amount": 650,
"description": "Its my first payment …
```
=> fix(router): avoid considering pre-routing results during `perform_session_token_routing`

cypress-tests/cypress/e2e/PaymentTest/00018-MandatesUsingPMID.cy.js, cypress-tests/cypress/e2e/PaymentUtils/Paypal.js, cypress-tests/cypress/e2e/PaymentUtils/Trustpay.js, cypress-tests/cypress/support/redirectionHandler.js
- Added hooks for payment method id mandates test cases as it was missed 
- Added bank redirect cases for Paypal 
- Fixed ideal bank redirect as UI has been changed
Test cases were failing for non supported connectors
Cypress:
- Trustpay 
- Stripe
- Cybersource
- Bankofamerica
- nmi
[2 failures are because of issue in sandbox , needs to be fixed ]
- adyen
- paypal
=> ci(cypress): Fix payment method id for non supported connectors

crates/router/src/core/refunds.rs
In case of refund sync, the `merchant_connector_id` was being populated as `connector_id`. This has been fixed in this PR to use `merchant_connector_id`.
- Run the postman collection locally
=> fix(access_token): use `merchant_connector_id` in access token

crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments/tokenization.rs
When a card is saved with nick_name during 1st time, if the same card is being saved next time with no nick_name, the nick_name field is being null. This is because we are only relying on request's nick_name field. We should first infer the value from the request. If not present/sent in request, we fallback to the existing field value in db.
1. Make a payment and save a card. Pass the `nick_name` field in request while saving for the 1st time.
```
--header 'api-key: dev_5sLv9sGxz1Dd0t45aORnPOpJ66ir3zsqKHrPTFBixrtgHeH7sqjsEcYPH2RCHK7u' \
--data-raw '{
"capture_on": …
```
=> fix(payment_methods): use existing field value of `nick_name` in db if not sent during request

crates/router/src/core/mandate/helpers.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/tokenization.rs
updated `last_used_at` field for apple pay and google pay for CITs
Currently, the `last_used_at` field for Apple Pay and Google Pay is not updated when an Apple Pay CIT (Cardholder Initiated Transaction) is made after Apple Pay has been saved.
This needs to be update whenever the payment are made.
-> Create mca for cybersource
-> Save apple pay for a customer
```
{
"amount": 800,
"amount_to_capture": 800,
"customer_id": "testing_123456",
"statement_descriptor_name": …
```
=> feat(router): updated `last_used_at` field for apple pay and google pay for CITs

crates/api_models/src/payments.rs
assurance_details_required being null in googlepay session response was causing issues in SDK, skip serialize if none for assurance_details_required in googlepay session response
parent pr - https://github.com/juspay/hyperswitch/pull/2744
1. There's no assurance_details_required field in metadata for googlepay, field is not shown in the response
2. If there's assurance_details_required in metadata for googlepay, then the value is returned
=> fix(router): skip serialize if none for assurance_details_required in googlepay session response

crates/euclid/src/dssa/analyzer.rs, crates/euclid/src/dssa/graph.rs, crates/euclid/src/dssa/truth.rs, crates/euclid_wasm/src/lib.rs, crates/hyperswitch_constraint_graph/src/builder.rs, crates/hyperswitch_constraint_graph/src/graph.rs, crates/hyperswitch_constraint_graph/src/types.rs, crates/kgraph_utils/benches/evaluation.rs, crates/kgraph_utils/src/mca.rs, crates/router/src/core/payments/routing.rs
Removes the lifetime parameter from Constraint Graph. Which was previously introduced due to Domains.
Ran all the Unit test of Euclid crate as the Graph testcases are written there.
```
cargo test -p euclid --all-features -- --show-output
```
=> refactor(hyperswitch_constraint_graph): Removal of lifetime from the Constraint Graph framework

crates/router/src/configs/defaults.rs, crates/router/src/configs/settings.rs, crates/router/src/core/blocklist/transformers.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payment_methods/transformers.rs
…e used by the locker
Add support for `RSA-OAEP-256` while decrypting the locker response as a configuration
Optional configuration, no tests needed
=> chore(cards): add configuration option to change the decryption scheme locker

postman/collection-dir/users/Flow Testcases/Sign In/Signin Token Only Wrong/event.test.js, postman/collection-dir/users/Flow Testcases/Sign In/Signin Token Only/event.test.js, postman/collection-dir/users/Flow Testcases/Sign In/Signin Wrong/event.test.js, postman/collection-dir/users/Flow Testcases/Sign In/Signin/event.test.js, postman/collection-dir/users/Flow Testcases/Sign Up/Connect Account/event.test.js, postman/collection-json/users.postman_collection.json
For user postman tests log x request id for every request.
Closes #5158 
Use command 
```
cargo run --bin test_utils -- --module-name="users" --base-url="http://localhost:8080" --admin-api-key="admin_api_key"
```
Results will contain x request id for every request:
Local Response in Postman Collection:
=> ci(postman): log request id for user tests

crates/router/src/lib.rs
Rename the browser name header from `browsername` to `x-browser-name`
Our web sdk is currently passing  `browsername` also, but this will be removed going forward
-> Create merchant connector account with apple pay manual flow. Below is the metadata for the manual flow.
```
"session_token_data": {
"initiative": "web",
"certificate": "==",
"display_name": "applepay",
"certificate_keys": "",
"payment_processing_details_at": "Hyperswitch",
"payment_processing_certificate": "",
"payment_processing_certificate_key": "",
"initiative_context": "sdk-test-app.netlify.app",
"merchant_identifier": "",
"merchant_business_country": "US"
}
```
-> Session response when only `x-client-platform` is passed
```
curl --location 'http://localhost:8080/payments/session_tokens' \ …
```
=> fix(router): rename the browser name header to `x-browser-name`

cypress-tests/cypress/e2e/PaymentUtils/Adyen.js, cypress-tests/cypress/e2e/PaymentUtils/Paypal.js, cypress-tests/cypress/e2e/PaymentUtils/Stripe.js
1. Update no_three_ds card number for adyen as previously it was 3D-secure-2 card which was resulting in no_three_ds payment to fail
2. Update the status for PayPal payments: previously, they would go to a 'processing' state, and refunds were not handled. Now, every PayPal payments goes to a 'succeeded' state
[Note: Refunds are bit flaky due to issues on the connector's end]
3. `Giropay` is Deprecated from `PayPal` and `Stripe` and hence added the appropriate error message
Adyen and Paypal test cases were failing
- Previously PayPal
- Currently PayPal
- ADYEN
- STRIPE
=> ci(cypress): Update card number for adyen and status for paypal

crates/router/src/core/payments.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_complete_authorize.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_update.rs
This is the use case where in which we need if the setup_future_usage is set to off_session in the payment method needs to be just saved at hyperswitch and not at connector. This is fix to override it during the pre-routing as well.
`skip_saving_wallet_at_connector_<merchant_id>` is the config which takes vector of payment method type as the value. When this config is set, the `setup_future_usage` is overridden to `on_session` by which mandates won't be created at the connector's end.
```
curl --location 'localhost:8080/configs/' \
--data '{
"key": "skip_saving_wallet_at_connector_merchant_1718351667",
"value": "[\"apple_pay\"]"
}'
```
-> Create merchant connector account
-> Make a CIT with off_session and …
=> fix(router): `override setup_future_usage` filed to on_session based on merchant config

crates/common_enums/src/enums.rs
RefundStatus Enum does not support snake_case, so serde directive were added.
Run a Query :
```
{topic="hyperswitch-refund-events", source!="vector"} |= `ref_XPgVve1i7ISdDXfnxNy0` | json | line_format `{{.refund_status}}`
```
the Output should be :
2024-07-04 15:37:41.486	failure
2024-07-04 15:37:41.486	pending
2024-07-04 15:37:40.998	pending
=> feat(analytics): Refund status serialization issue for ckh analytics

crates/api_models/src/user.rs, crates/router/src/core/user.rs
Make id option in auth select. If no id is passed the response should give totp token
Closes [#5212](https://github.com/juspay/hyperswitch/issues/5212)
request:
```
curl --location 'http://localhost:8080/user/auth/select' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYjJkNjMxZDUtMGQzMi00Y2IxLTg2MTQtNWVlNWI2MDczYTVkIiwicHVycG9zZSI6ImF1dGhfc2VsZWN0Iiwib3JpZ2luIjoiYWNjZXB0X2ludml0YXRpb25fZnJvbV9lbWFpbCIsInBhdGgiOltdLCJleHAiOjE4MTk1ODQ1NDN9._vo2f5SpbKFcpNipvLqbJTsEJ5YwSdL__3Igg7yU4-4' \
--data '{
}
'
```
Response:
```
{
"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYjJkNjMxZDUtMGQzMi00Y2IxLTg2MTQtNWVlNWI2MDczYTVkIiwicHVycG9zZSI6InRvdHAiLCJvcmlnaW4iOiJhY2NlcHRfaW52aXRhdGlvbl9mcm9tX2VtYWlsIiwicG …
```
=> fix(user_auth_method): make id option in auth select

crates/common_enums/src/enums.rs
- Add backwards compatibility aliases on refund status
Currently drainer relies on the serde json representation to parse these results and hence needs a backwards compatible way to parse older & newer formats.
- make refunds with kv mode and check the operations tab for their presence
=> fix(refunds): Add aliases on refund status for backwards compatibility

api-reference/openapi_spec.json, crates/api_models/src/payment_methods.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments/flows/session_flow.rs
Currently there are two fields which indicate if the customer address needs to be collected form the wallets like apple pay or google pay. And those fields are `collect_shipping_details_from_wallet_connector` and `collect_billing_details_from_wallet_connector`, and the same fields needs to be sent to sdk so that they can make the required decisions based on it.
-> Create stripe mca
-> For the specific business profile set the below fields as ture
```
curl --location 'http://localhost:8080/account/merchant_1720165673/business_profile/pro_6Rcn7QpBhEJ1M76tiD4w' \
--header 'api-key: admin' \
--data '{
"collect_shipping_details_from_wallet_connector": false,
"collect_billing_details_from_wallet_connector": false …
```
=> feat(router): pass fields to indicate if the customer address details to be connector from wallets

.github/nextest.toml, .github/workflows/CI-pr.yml, .github/workflows/CI-push.yml, Cargo.lock, crates/euclid/src/dssa/analyzer.rs, crates/external_services/src/hashicorp_vault/core.rs, crates/hyperswitch_domain_models/src/router_request_types.rs, crates/masking/README.md, crates/router/src/configs/settings.rs, crates/router/src/connector/netcetera/netcetera_types.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/db/events.rs, crates/router/src/types/storage/payment_attempt.rs, crates/router_derive/Cargo.toml, crates/router_derive/src/lib.rs, crates/router_env/README.md, crates/router_env/src/logger/formatter.rs
This PR enables the usage of `sccache` for caching compilation artifacts in the CI-pr workflow, and fixes the existing unit and documentation tests. I'll be taking up running the unit and documentation on pull requests in a separate PR, with some more CI workflow improvments.
Fixing unit tests so that they can be run as part of pull request checks.
I've run unit tests locally with the following command (with locally running Postgres and Redis servers), and they pass:
```shell
FEATURES=$(cargo metadata --all-features --format-version 1 | \
jq -r '
[ ( .workspace_members | sort ) as $package_ids # Store workspace crate package IDs in `package_ids` array
| .packages[] | select( IN(.id; $package_ids[]) ) | .features | keys[] ] | unique # Select all unique features from all workspace crates
| …
```
=> refactor: fix unit and documentation tests

cypress-tests/cypress/e2e/PayoutTest/00003-CardTest.cy.js, cypress-tests/cypress/e2e/PayoutTest/00004-BankTransfer.cy.js
This PR fixes bug introduced in https://github.com/juspay/hyperswitch/pull/5223
Payouts for other connectors started to fail they did not skip
Tests have been added here: https://github.com/juspay/hyperswitch/pull/5180
=> fix(cypress): Fix payouts failing

crates/api_models/src/payments.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_complete_authorize.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_update.rs
In case we receive a 4xx when creating the payment before calling the connector, we do not save the `customer_id` in payment intent. This PR fixes it
This PR also includes changes to ensure that `customer_id` is always taken from both the places in the PaymentsRequest. The root `customer_id` and `customer.id` field.
- Create a merchant account
```bash
--data '{
"merchant_id": "merchant_1720593206"
}'
```
- Create an api key
```bash
curl --location 'http://localhost:8080/api_keys/merchant_1720593134' \
--data '{ …
```
=> fix(payments_create): save the `customer_id` in payments create

crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/cybersource/transformers.rs
Pass billing details, in MIT  request 
1. Create a CIT with BOA/CYBS
```
--header 'api-key: dev_ABuIePR7mHSsEj9vq0efN00DpFcwUQ7KPkqRLv8luwtgl9jOfBzHNgapj6uNTxZn' \
--data-raw '{
"customer_id": "ffff",
"billing": {
"address": {
"state": …
```
=> refactor(connectors): [boa/cybs] add billing address to MIT request

crates/connector_configs/src/transformer.rs
send assurance_details required as false in googlepay metadata during merchant_connector_account creation from dashboard
Compiler guided
Once this change is deployed, when we try to create an mca with googlepay enabled from dashboard. assurance_details_required would be false in googlepay metadata, and same would be sent in session call response for googlepay
=> fix(router): send assurance_details required as false in googlepay metadata during merchant_connector_account creation from dashboard

crates/router/src/core/refunds.rs
fail refund with bad request error for duplicate refund_id in refunds create flow
Create a refund with duplicate refund_id, it should fail with Bad request error
=> fix(router): fail refund with bad request error for duplicate refund_id in refunds create flow

crates/hyperswitch_domain_models/src/router_request_types.rs, crates/hyperswitch_interfaces/src/integrity.rs, crates/router/src/connector/stripe.rs, crates/router/src/connector/utils.rs, crates/router/src/core/payments/flows/psync_flow.rs, crates/router/src/core/payments/transformers.rs, crates/router/tests/connectors/bambora.rs, crates/router/tests/connectors/forte.rs, crates/router/tests/connectors/nexinets.rs, crates/router/tests/connectors/paypal.rs, crates/router/tests/connectors/utils.rs, crates/router/tests/connectors/zen.rs
we have implemented integrity checks for stripe, we have implemented integrity in authorise, sync, capture and refund, refund sync
but, where in sync flow we check amount, currency and amount_captured.
the bug is in 3ds flow, where after the transaction is completed we do a sync with the connector, but our trackers are not updated at this point.
In 3ds transaction we rely on connector sync to update our trackers, since integrity checks happens with data before post update trackers we were comparing MinorUnit(0) our amount captured to Some(MinorUnit(x)) amount received by the connector.
due, to this there was a data mismatch issue, which led to integrity check failure.
``` …
```
=> fix(router): fixed integrity check failures in case of 3ds flow in sync flow

crates/router/src/core/payouts.rs, crates/router/src/core/payouts/helpers.rs
This PR fixes below bugs
- default status (based on different conditions) does not update in `payouts` table
- payout status updation during confirmation happens prior to validating the request
- helper functions for deciding whether or not to execute different payout flows does not have the updated status list 
Tested locally using payout's test suite.
1. Create a payout using confirm: false, auto_fulfill: false
```
curl --location 'https://heard-directly-trademarks-diana.trycloudflare.com/payouts/create' \
--header 'x-feature: integ-custom' \
--header 'api-key: dev_N4b6S09H8f5CHy1vvGEEyvyJcUqcs64R84eVkCtdBr3iTYFOGhCHieJlkoJUSs7w' \
--data-raw '{
"amount": 1,
"customer_id": "cus_ZcGmeCSo9O0YMHx8S9KT",
"email": …
```
=> refactor(payouts): update helper functions for deciding whether or not to consume flows based on current status

crates/common_utils/src/macros.rs, crates/drainer/src/handler.rs, crates/router/src/bin/scheduler.rs, crates/router/src/core/blocklist/utils.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/retry.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/core/payouts/retry.rs, crates/router/src/core/pm_auth.rs, crates/router/src/core/refunds.rs, crates/router/src/core/user.rs, crates/router/src/core/user_role.rs, crates/router/src/db/merchant_connector_account.rs, crates/router/src/lib.rs, crates/router/src/routes/payments.rs, crates/router/src/routes/payments/helpers.rs, crates/router/src/services/api.rs, crates/router/src/services/authentication.rs, crates/router/src/services/authorization.rs, crates/router/src/utils/currency.rs, crates/router/src/workflows/api_key_expiry.rs, crates/scheduler/src/db/queue.rs, crates/scheduler/src/errors.rs, crates/scheduler/src/producer.rs, crates/scheduler/src/utils.rs
This PR updates the error logs to use the `Debug` implementation instead of the `Display` implementation to log errors. This would print the entire error reports (in case of `error_stack::Report`) instead of just the latest error raised in the report.
This would help developers debug failures better.
Sanity testing done via Postman.
=> refactor: use `Debug` impl instead of `Display` impl for logging errors

crates/router/src/core/payments/transformers.rs
Populate merchant order reference id in payments list response
Closes [#5309](https://github.com/juspay/hyperswitch/issues/5309)
For a particular payment merchant_order_ref_id_should be pouplated:
Use list api:
```
--data '{
"payment_id": "test_XBmXZFG8IcR9CCAvFgxG"    
}'
```
Response:
```
{
"count": 1,
"total_count": 1,
"data": [
{
"payment_id": "test_XBmXZFG8IcR9CCAvFgxG",
"merchant_id": "merchant_1720779856",
"status": "succeeded",
"amount": 20000,
"net_amount": 0,
"amount_capturable": 20000,
"connector": "paypal_test",
"client_secret": "test_XBmXZFG8IcR9CCAvFgxG_secret_61VMg0zl0IqpGhSJviK9",
"created": …
```
=> fix(payments): populate merchant order ref id in list

crates/router/src/connector/authorizedotnet/transformers.rs
Error reason is now being populated for failure transactions for connector authorizedotnet.
https://github.com/juspay/hyperswitch/issues/5318
Zip code should be passed as 46282 to generate failure scenario for connector authorizedotnet.
Request:
```
--header 'api-key: dev_Rjm1odUMbdX57oOLZNQzZtoYOEAo8ZAi1QHZzV79JIkJPnM8ffypLayUJW9rGX7a' \
--data '{
"amount": 1232,
"customer_id": "Strustomewwr",
"card": {
"card_number": "4111111111111111",
"card_exp_month": "02",
"card_exp_year": "35",
"card_holder_name": "John Doe",
}
}, …
```
=> fix(connector): [AUTHORIZEDOTNET] Populate error reason for failure transactions

config/config.example.toml, config/deployments/env_specific.toml, crates/router/src/bin/scheduler.rs, crates/router/src/configs/defaults.rs, crates/router/src/configs/settings.rs, crates/router/src/lib.rs, crates/router/src/services/api.rs, crates/router/src/services/api/client.rs
Add support to set custom urls in the proxy list via configuration
FIx for https://github.com/juspay/hyperswitch/pull/5168
The configuration changes are mentioned in `config.example.toml`.
=> feat(proxy): add support to pass proxy bypass urls from configs

crates/router/src/services/api.rs
Skip incoming_request_header getting logged during instrumentation
Request headers added for multi-tenancy is not skipped from instrumentation, which is resulting in logging request headers for all server_wrap calls.
=> fix(logs): ignore request headers while logging

crates/router/src/core/payouts.rs
the payout retrieve fails when payout_token expires for payout_method_data. It should not fail for such cases so removed the dependency on payout_method_data
- Create a payout through Paypal: 
```
{
"amount": 1,
"customer_id": "payout_customer",
"payout_type": "wallet",
"wallet": {
"paypal": {
"email": "sk.sakil@juspay.in"
}
}
},
"billing": {
"address": {
"state": "NY",
},
"phone": {
"number": …
```
=> fix(core): [payouts] failure of payout retrieve when token is expired

crates/diesel_models/src/schema.rs, crates/diesel_models/src/schema_v2.rs, migrations/2024-07-19-044034_change_primary_key_for_refund/down.sql, migrations/2024-07-19-044034_change_primary_key_for_refund/up.sql
Previously our Refund table had id as PKey.
Which needs to be changed to a composite Primary key as (merchant_id, refund_id).
Tested it by compiling the code and checking the file `query/refund.rs`, where id is nowhere being used.
=> refactor(core): change primary key of refund table

crates/router/src/connector/cybersource/transformers.rs
During the MITs with the `connector_mandate_details`  the `original_authorized_amount` is made optional.
-> Create cybersource merchant connector account
-> Create mandate
```
--header 'api-key: dev_FZ5RdQNZ944E16z8uT6DrqlkCa2TsEnGBFxdFu6uuNgbwi68PJlvfpYGXmqLFlJa' \
--data-raw '{
"customer_id": "cu_1720965634", …
```
=> refactor(connector): make the `original_authorized_amount` optional for MITs with `connector_mandate_details`

crates/hyperswitch_domain_models/src/merchant_account.rs, crates/hyperswitch_domain_models/src/merchant_key_store.rs, crates/hyperswitch_domain_models/src/payments/payment_attempt.rs, crates/hyperswitch_domain_models/src/type_encryption.rs, crates/router/src/core/admin.rs, crates/router/src/core/customers.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/pm_auth.rs, crates/router/src/core/webhooks/outgoing.rs, crates/router/src/types/api/admin.rs, crates/router/src/types/domain/merchant_connector_account.rs, crates/router/src/types/domain/types.rs, crates/router/src/types/domain/user.rs, crates/router/src/types/domain/user_key_store.rs, crates/router/src/utils/user.rs
encrypt/decrypt should happen only via encryption service and DEK should be same in application and encryption service
encrypt/decrypt should happen only via encryption service and DEK should be same in application and encryption service
Changes can be verified only through logs. Look for "Fall back to Application Encryption" or "Fall back to Application Decryption" in the logs post deployment after running below tests. If logs are present encryption/decryption failed with encryption service and fall back to the application encryption which has to be investigated.
Test with merchant created before the changes deployed
1. Create Payment
2. Retrieve Payment
3. Create Refund
4. Retrieve Payment
Test with merchant created after the changes deployed
1. Create Merchant
2. Create API Key
3. …
=> fix: use encrypt api for all encryption and decryption

crates/router/src/configs/defaults.rs
Add billing country in klarna dynamic fields
1. Create a Klarna Payment Request via Klarna with with `confirm=fasle`
```
{
"amount": 1800,
"customer_id": "cus_NwicjmCJbgafjhjfhHr6",
"phone": "9123456789",
"payment_method_type": "klarna",
"pay_later": {
"klarna_sdk": {
"token": "65bfb654-ef2c-6b39-942e-ffdc9a105d3cf"
} …
```
=> refactor(connector): Add billing_country in klarna dynamic fields

crates/diesel_models/src/query/dashboard_metadata.rs, crates/router/src/db/dashboard_metadata.rs
Alter query in `find_merchant_scoped_dashboard_metadata`
For merchant scoped metadata it need not to be considered whether user_id column is `null` or not
Closes #5396
To get the metadata use curl:
```
curl --location 'http://localhost:8080/user/data?keys=ProductionAgreement%2CSetupProcessor%2CConfigureEndpoint%2CSetupComplete%2CFirstProcessorConnected%2CSecondProcessorConnected%2CConfiguredRouting%2CTestPayment%2CIntegrationMethod%2CConfigurationType%2CIntegrationCompleted%2CStripeConnected%2CPaypalConnected%2CSPRoutingConfigured%2CFeedback%2CProdIntent%2CSPTestPayment%2CDownloadWoocom%2CConfigureWoocom%2CSetupWoocomWebhook%2CIsMultipleConfiguration%2CIsChangePasswordRequired' \
```
In response we will get the metadata both that set or unset:
```
[
{ …
```
=> refactor(dashboard_metadata): alter query for merchant scoped metadata

crates/api_models/src/payments.rs, crates/router/src/core/payments/transformers.rs
This pr adds the decrypted customer_details, shipping and billling address in Payment list response.
https://github.com/juspay/hyperswitch/pull/5401
Required for our Dashboard
We need to make a payment with shipping, billing and customer details and then hit the Payment list api:
```
curl --location --request GET 'http://127.0.0.1:8080/payments/list' \
--header 'api-key:xxxxxxx' \
--data '{
}'
```
The response should contain the below fields:
```
"customer_id": "uiuiuiui",
"customer": {
"id": "uiuiuiui",
"name": null,
"email": "guest@ehjhjxample.com",
"phone": null,
"phone_country_code": null
},
"shipping": {
"address": { …
```
=> chore: add customer, shipping and billing details to payment_response for payment list api

crates/router/src/connector/datatrans/transformers.rs
1)Datatrans accepts expiry year in YY format only . Fixed that.
2) Removed the Check for 3ds flow (Earlier Not Implemented error was thrown)
https://github.com/juspay/hyperswitch-cloud/issues/6000#issuecomment-2238555051
**for 3DS**
Request
```
--header 'api-key:' \
--data '{
"amount": 800,
"amount_to_capture":800,
"card": {
"card_number": "4444090101010103",
"card_exp_month": "06",
"card_exp_year": "2025",
"card_cvc":"232"
}
}
}'
``` …
=> fix(connector): [Datatrans] Handling for 4-Digit YYYY input and Correct 3DS Routing to no_3ds

api-reference/openapi_spec.json, crates/api_models/src/enums.rs, crates/router/src/configs/defaults.rs
Added mandatory fields for pix in dynamic field 
Through postman:
- Do a payment method list call:
- The response should contain the following value
```
"required_fields": {
"payment_method_data.bank_transfer.pix.cpf": {
"required_field": "payment_method_data.bank_transfer.pix.cpf",
"display_name": "cpf",
"field_type": "user_cpf",
"value": null
},
"payment_method_data.bank_transfer.pix.pix_key": {
"required_field": "payment_method_data.bank_transfer.pix.pix_key",
"display_name": "pix_key",
"field_type": "user_pix_key",
"value": null
},
"payment_method_data.bank_transfer.pix.cnpj": {
"required_field": "payment_method_data.bank_transfer.pix.cnpj",
"display_name": "cnpj",
"field_type": "user_cnpj",
"value": null
}
},
```
=> refactor(connector): [Itaubank] add dynamic fields for pix

.github/workflows/CI-pr.yml, scripts/ci-checks.sh
This PR updates the CI check script to obtain the modified files from the PR instead of via `git diff`, since obtaining it from the PR would give us more accurate results.
Using `git diff` to obtain the diff of files modified can result in incorrect diffs, specifically if the base branch has had recent commits which modify Rust code, while the PR itself does not modify any Rust code. In such situations, taking a `git diff` would report that the PR involves Rust code changes, since `origin/main` (for example) reflects the latest state of the `main` branch, but not when the PR was last synced with the `main` branch.
Test commits on this PR branch.
1. When no code files were modified ([commit `0c973de`](https://github.com/juspay/hyperswitch/pull/5436/commits/0c973de8018dfc52da787fb7a7c47a1c1d …
=>  ci: obtain files modified from PR instead of git diff

crates/analytics/src/opensearch.rs, crates/analytics/src/search.rs, crates/api_models/src/analytics/search.rs
> Implement a validation check that ensures the `query` field is not empty or consisting only of whitespace, and that the `filters` field is not entirely `None` or containing only `None` values for all its fields. If both conditions are true, an error should be returned.
```bash
curl 'http://localhost:8080/analytics/v1/search' \
-H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"' \
-H 'sec-ch-ua-mobile: ?0' \
-H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNTEzYWUyODItN2I1NS00MGMwLWFiZGMtYjdiMGYzNDNkMTQ2IiwibWVyY2hhbnRfaWQiOiJtZXJjaGFudF8xNzIxNjQyOTczIiwicm9sZV9pZCI6Im9yZ19hZG1pbiIsImV4cCI6MTcyMjE1NzQ0Miwib3JnX2lkIjoib3JnX2drZHNlNDBIdGx6RkNob2NpU0NzIn0.Fmrxsp-emKQ-67EpcJolMf7EyeDdjl4DcwbmnVSprMU' \
-H 'User-Agent: Mozilla/5.0 …
```
=> refactor(opensearch): Add Error Handling for Empty Query and Filters in Request

api-reference/openapi_spec.json, crates/api_models/src/admin.rs, crates/openapi/src/openapi.rs, crates/openapi/src/routes/merchant_connector_account.rs, crates/router/src/core/admin.rs, crates/router/src/types/transformers.rs
remove `connector_account_details` and `connector_webhook_details` in merchant_connector_account list response
1. Create a MCA
2. Do MCA List and observe connector_account_details, connector_webhook_details being not present in the response
3. Do MCA retrieve and observe connector_account_details, connector_webhook_details being present in the response
=> refactor(router): remove `connector_account_details` and `connector_webhook_details` in merchant_connector_account list response

config/deployments/integration_test.toml
This will add the config for cybersource in Integ.
Due to configs not present the Cypress tests(blocklist) are failing.
This is an env change, hence wouldn't require testing as such.
=> refactor(configs): include env for cybersource in integration_test

cypress-tests/cypress/e2e/PaymentMethodListTest/00000-PaymentMethodListTests.cy.js, cypress-tests/cypress/e2e/PaymentMethodListUtils/Commons.js
Added shipping address test cases for payment method list in cypress automation
Shipping address test cases wasn't present in the cypress automation 
Cypress
- PML alone
- Stripe
- Cybersource
=> ci(cypress): Added shipping address test cases for PML

crates/router/src/core/payment_link/payment_link_initiate/payment_link_initiator.js
Described in https://github.com/juspay/hyperswitch/issues/5495
<details>
<summary>1. Create non 3DS open payment link</summary>
--header 'api-key: API_KEY' \
--data-raw '{
"customer_id": "cus_05845u0qSuOENDnHLqTl",
"amount": 100,
"connector": [
"stripe"
],
"billing": {
"address": {
"state": "CA",
},
"phone": {
"number": "8056594427",
"country_code": "+91"
}
},
"email": "john.doe@example.com", …
=> fix(payment_link): move redirection fn to global scope for open links

crates/router/src/core/payment_link/payment_link_initiate/payment_link_initiator.js
This PR adds an argument to be sent to the SDK for open payment links. This field controls the listing of SPMs for a given customer. Default value is `true` in SDK, needs to be sent as `false` explicitly during SDK integration
Bug fixes; open link is not behaving as expected
<details>
<summary>1. Create non 3DS open payment link with an existing customer</summary>
--header 'api-key: API_KEY' \
--data-raw '{
"customer_id": "cus_05845u0qSuOENDnHLqTl",
"amount": 100,
"connector": [
"stripe"
],
"billing": {
"address": {
"line3": …
=> fix(open_payment_links): send displaySavedPaymentMethods as false explicitly for open payment links

config/deployments/integration_test.toml, config/deployments/production.toml, config/deployments/sandbox.toml, config/development.toml, config/docker_compose.toml, crates/router/Cargo.toml, crates/router/src/lib.rs, crates/router/src/middleware.rs, loadtest/config/development.toml
add accept language header middleware .
Case 1 : when query parameter locale is present it should overwrite the Accept-Language headers in the middleware for api request.
Case 2: If query parameter is not present then if request have Accept-Language headers, do nothing.
Case 3 : Incase if both query param & header is not present we should add new header Accept-Language header with default value "en".
This feature is meant to be used by internal api's, We will not suggest merchant to send query parameter . SDK will pass this headers to backend to perform backend loaclization. Will consume this header input and perform backend localization in future.
create any api request to hyperswitch with query params locale this should add accept-language header in the request. you can check this in …
=> feat(router): add accept language header middleware 

crates/router/src/connector/cybersource/transformers.rs
The status mapping for AuthorizedPendingReview status from Cybersource is updated. These payments will now be marked as pending.
https://github.com/juspay/hyperswitch/issues/5535
For testing this PR, we need to generate a AVS mismatch error at Cybersource which should mark the payment as failure. For triggering this one needs to enable strong fraud checks on cybersource dashboard before starting testing.
Request:
```
--header 'api-key: dev_yvZV0B0RAfH0T1djPkbJicPaQJ34DgMFFpLJiHLs7z4qaC2jZoYx0HPGKSyHRUhh' \
--data-raw '{
"amount": 1404,
"customer_id": …
```
=> fix: [CYBERSOURCE] Update status handling for AuthorizedPendingReview

crates/router/src/connector/boku.rs, crates/router/src/connector/boku/transformers.rs, crates/router/src/types/api.rs, crates/router/tests/connectors/boku.rs
This PR do changes to Boku connector for framework amount conversions and Boku accepts the amount in MinorUnit
https://github.com/juspay/hyperswitch-cloud/issues/6128
We do not have sandbox credential for this connector
=> refactor(connector): added amount conversion framework for Boku

crates/router/src/connector/mifinity.rs, crates/router/src/connector/mifinity/transformers.rs, crates/router/src/types/api.rs, crates/router/tests/connectors/mifinity.rs
This PR do amount conversion changes for Mifinity Connector and it accepts the amount in StringMajorUnit
https://github.com/juspay/hyperswitch-cloud/issues/6148
Payment Request: 
```
--header 'api-key: dev_WRjhnbKDoMkMK2LlnwS2EDjEP0wMGhJPgOOk1lPrQybpvCVcLVOLcNpATsbIzruw' \
--data-raw '{
"amount_to_capture": 1000, …
```
=> refactor(connector): added amount conversion framework for Mifinity

cypress-tests/cypress.config.js, cypress-tests/cypress/support/e2e.js, cypress-tests/cypress/support/screenshotConfigs.js
Currently, we do not have the privilege for properly taking screenshots when a test fails. We have to manually run the test and see what went wrong, why it went wrong. That is because upcoming test would override previous / existing screenshot. This is a loss for us.
- screenshots that are taken will **not** be overwritten and will **not** be trashed between runs
- To mask sensitive info, elements with the class .secret-info or any element with the attribute data-hide=true will be blacked out to prevent sensitive information from being visible in the screenshot
- Cypress will take screenshot of entire `runner` window and not just specific `viewport`
- Hooks:
- `onBeforeScreenshot`:
- Runs before taking the screenshot
- It looks for elements with the class `.clock` within the `$el` (the …
=> feat(cypress): add configs for not overriding screenshots

cypress-tests/cypress/e2e/PaymentTest/00021-CoreFlows.cy.js, cypress-tests/cypress/fixtures/imports.js, cypress-tests/cypress/fixtures/merchant-update-body.json, cypress-tests/cypress/fixtures/update-api-key-body.json, cypress-tests/cypress/fixtures/update-connector-body.json, cypress-tests/cypress/fixtures/update-customer-body.json, cypress-tests/cypress/support/commands.js
- This PR adds following core flow validations
- Merchant Accounts
- Create
- Retrieve
- List
- Update
- Delete
- API Keys
- Create
- Retrieve
- Update
- List
- Delete
- MCA
- Create (Same connector, multiple labels)
- Create (label x)
- Create (label y)
- Create
- Retrieve
- Update
- List
- Delete
- Customers
- Create
- list
- Retrieve
- Update
- Ephemeral Generate
- Delete
- Added 4 additional `fixtures` for `update` bodies
**NOTE:** This PR is highly dependent on https://github.com/juspay/hyperswitch/pull/5547 without which some validations **will** fail. Also, lints have been validated in the same PR
NIL
=> feat(cypress): add core flow tests

crates/common_enums/src/enums.rs, crates/router/src/core/payments/operations/payment_response.rs, crates/router/src/core/payments/tokenization.rs
Update pm_status accordingly for the respective attempt status. Earlier we were mapping the AttemptStatus to Active in all the cases other than Failure. In this PR we must update the pm_status as Active only if it's charged / Authorised by the connector. 
https://github.com/juspay/hyperswitch/pull/5557
- Create a 3ds payment
>  
```
Create
--header 'api-key: dev_uaSNBro089ifFDTOyfoTqV6fEZOIkjtEUCDeHMDbwolILfq885p0xt0Nu9pwGLW9' \
--data-raw '{
"customer_id": "CustomerX7777",
"return_url": …
```
=> fix(core): Update pm_status accordingly for the respective attempt status

config/docker_compose.toml
This PR fixes the following bug 
```
2024-08-08 21:08:07 thread 'main' panicked at crates/router/src/bin/router.rs:16:10:
2024-08-08 21:08:07 Unable to construct application configuration: Application configuration error
2024-08-08 21:08:07 ├╴at crates/router/src/configs/settings.rs:759:14
2024-08-08 21:08:07 │
2024-08-08 21:08:07 ╰─▶ payout_method_filters.adyenplatform.sepa.currency: Some errors occurred:
2024-08-08 21:08:07     Unable to deserialize `NOR` as `common_enums::enums::Currency`: Matching variant not found
2024-08-08 21:08:07     ├╴at crates/router/src/configs/settings.rs:758:14
2024-08-08 21:08:07     ╰╴Unable to deserialize application configuration
2024-08-08 21:08:07 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> fix(docker): currency enum fix for docker config

cypress-tests/cypress/e2e/PaymentTest/00013-SaveCardFlow.cy.js, cypress-tests/cypress/e2e/PaymentUtils/Adyen.js, cypress-tests/cypress/e2e/PaymentUtils/BankOfAmerica.js, cypress-tests/cypress/e2e/PaymentUtils/Commons.js, cypress-tests/cypress/e2e/PaymentUtils/Cybersource.js, cypress-tests/cypress/e2e/PaymentUtils/Stripe.js, cypress-tests/cypress/fixtures/save-card-confirm-body.json, cypress-tests/cypress/support/commands.js
This PR adds up some more test cases for save card flows i.e., recurring payment using payment token 
NIL
Cypress:
- STRIPE
- cybersource
=> ci(cypress): Add off-session save card flows

crates/router/src/core/payment_link/payment_link_initiate/payment_link.js
Put an check to remove dynamic section if no fields are present in it or it is of invalid format
Create a payment link with no transaction_details:
```
{
"amount": 1100,
"logo": "https://hyperswitch.io/logos/hyperswitch.svg",
"display_sdk_only": false
},
"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) …
```
=> fix(payment_link): remove dynamic section if no fields are present

cypress-tests/cypress/support/commands.js, cypress-tests/package.json
This PR enables running PML independently.
Needed.
Execute:
```
export CYPRESS_CONNECTOR="wellsfargo" && npm run cypress:payment-method-list
```
=> chore: run pml independently

crates/router/src/core/payments/operations/payment_update.rs
currently payments update is allowed for requires_customer_action and other non allowed statuses also, to fix that
allow payments update for requires_payment_method and requires_confirmation intent status only
Try to Update payment after status is in requires_customer_action
Payment Update when status is in requires_payment_method
=> fix(router): allow payments update for requires_payment_method and requires_confirmation intent status only

crates/redis_interface/src/commands.rs, crates/redis_interface/src/errors.rs
This PR adds the required redis commands for success rate based routing. Below are the added redis commands - 
*  ​​RPUSH (Push current block to aggregates list): Pushing an item to LIST
*  LRANGE (Get a list of buckets in aggregates): Access an item from LIST in a given range
*  LLEN (Check length of aggregates list): Get the length of LIST
*  LPOP (Remove first bucket in aggregates list): Remove first n elements from LIST
*  HINCRBY (Increment current_block's fields): Increment key of map
As this PR only adds the new redis commands and doesn't involve any existing code changes, basic sanity tests should suffice
=> refactor(redis): add redis commands required for success rate based routing

crates/hyperswitch_domain_models/src/payment_address.rs, crates/router/src/core/payments/transformers.rs
Currently when a payment method is the billing details will also get saved in the payment method table.
But when a recurring payment is performed with the saved payment method, it is expected that the billing details to be passed in the current payment as well instead of using already saved billing details.
This pr contains the changes to use the saved payment method billing details during the recurring payment.
-> Create mca for cybersource
-> Create a payment to save a card
```
{
"amount": 100,
"customer_id": "cu_{{$timestamp}}",
"description": "Its my first …
```
=> refactor(router): use the saved billing details in the recurring payments

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/payments.rs
make `billing_details` optional for payment method przelewy24 BankRedirectData. 
1. Create a przelewy24 payment request via Mollie connector, without passing billing_details in payment_method_data
```
{
"payment_method_type": "przelewy24",
"przelewy24": { }
}
},
"billing": {
"address": {
"line2": …
```
=> refactor(core): make p24 billing_details optional

crates/common_utils/src/consts.rs, crates/common_utils/src/id_type.rs, crates/common_utils/src/id_type/global_id.rs
This PR adds a global id type that can be used to create global ids for other entities.
All the entities henceforth will be identified by a universal identifier, i.e the global id. 
unit test cases are added
No testing required as only the types are added
=> feat(global_id): create a `GlobalId` domain type

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml, crates/router/src/connector/cybersource/transformers.rs, crates/router/src/core/admin.rs
When `disable_avs` is enabled, avs result will be ignored by Cybersource. 
When `disable_cvn` is enabled, cvn result will be ignored by Cybersource.
```
"metadata": {
"disable_avs": true,
"disable_cvn": true,
}
```
> Note:  These flags are not effective in sandbox
Can't be tested as avs check is only done in production env
Sanity 
1. Create a payment with cards
```
--header 'api-key: dev_aQxPOtk3HOI1YMCSh71XowkHSKeKmfYLoakbfXuAMxlEIX93sCOenDWzBySirGhl' \
--data-raw '{
"customer_id": "testCus_15",
"name": "John …
```
=> feat(router): [cybersource] add disable_avs and disable_cvn flag in connector metadata 

api-reference-v2/api-reference/organization/organization--create.mdx, api-reference-v2/api-reference/organization/organization--retrieve.mdx, api-reference-v2/api-reference/organization/organization--update.mdx, api-reference-v2/mint.json, api-reference-v2/openapi_spec.json, crates/openapi/src/routes/organization.rs, crates/router/src/routes/app.rs
Added new v2 routes for organization endpoint. And generated open api spec and mintlify docs.
Ran `mintlify dev` to render the newly added routes.
Postman screenshots.
1. Create.
2. Retrieve
3. Update
=> chore: create v2 route for organization

.deepsource.toml, Cargo.lock, Cargo.toml, INSTALL_dependencies.sh, api-reference-v2/openapi_spec.json, crates/analytics/Cargo.toml, crates/analytics/src/sqlx.rs, crates/common_enums/Cargo.toml, crates/common_utils/Cargo.toml, crates/diesel_models/Cargo.toml, crates/drainer/Cargo.toml, crates/hsdev/Cargo.toml, crates/masking/Cargo.toml, crates/router/Cargo.toml, crates/router/src/connector/signifyd/transformers/api.rs, crates/router/src/services/kafka.rs, crates/router_derive/Cargo.toml, crates/storage_impl/Cargo.toml
This PR updates `diesel` to `2.2.3`, `sqlx` to `0.8.1` and `bigdecimal` to `0.4.5`. `diesel 2.2.3` requires an MSRV of 1.78, and `sqlx 0.8.1` requires an MSRV of 1.80 (at least until https://github.com/launchbadge/sqlx/pull/3459 is merged and a new version is released), so the MSRV had to be bumped to 1.80.
In addition, this PR removes the dependency on the `bigdecimal` crate in `router` and replaces it with `num-traits`, since we were only using a trait from `num-traits` re-exported by `bigdecimal`.
The updated versions of the dependencies address security vulnerabilities https://github.com/advisories/GHSA-xmrp-424f-vfpx and https://github.com/advisories/GHSA-wq9x-qwcq-mmgf.
N/A
=> build(deps): bump `diesel` to `2.2.3` and `sqlx` to `0.8.1`

cypress-tests/cypress/e2e/PaymentUtils/Paybox.js
This PR fixes main issues with Paybox Cypress tests.
For payments with `AutoCapture` that accepts only specific currencies say, `EUR`. We should pass currency in config.
And for corner cases. Just for sake of changing `currency`, all the cases have been cloned to `paybox.js`
I've to fix this.
Refer there as well.
=> ci(cypress): update paybox configs

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/admin.rs, crates/diesel_models/src/merchant_connector_account.rs, crates/hyperswitch_domain_models/src/merchant_connector_account.rs, crates/router/src/core/admin.rs, crates/router/src/core/connector_onboarding/paypal.rs, crates/router/src/core/verification/utils.rs
This PR does - 
- In the PIS flow,  in merchant connector update, we didn't collect `additional_merchant_data` in the update req, have fixed that. Have also added relevant logic in MCA update core to process the data collected.
1. MCA create for Plaid - 
```
curl --location --request POST 'http://localhost:8080/account/merchant_1724231900/connectors' \
--data-raw '{
"connector_name": "plaid",
"api_key": "something",
"key1": "something"
},
{
"payment_method": "open_banking",
{
"payment_method_type": "open_banking_pis", …
```
=> refactor(open_banking): Added merchant data update in mca update

api-reference-v2/openapi_spec.json, crates/router/src/core/payment_methods/utils.rs
This Pr will change the node relation of the `Disabled_only` field passed in mca for any connector to be Negative.
https://github.com/juspay/hyperswitch/pull/5701
The flow for testing this is as follows:
1. Mca create for crypto_pay
```
curl --location 'http://127.0.0.1:8080/account/merchant_1724687132/connectors' \
--data '{
"connector_name": "cryptopay",
"api_key": "xxxxx",
"key1": "xxxxxxx"
},
{
{
"payment_experience": …
```
=> refactor(euclid): make the disabled node's relation as negative

crates/router/src/connector/itaubank.rs, crates/router/src/connector/itaubank/transformers.rs
Previously error code is mapped to status code and error reason was not populated with complete Itau error message .This PR fixes this issue.
create a failed payment with itau bank as connector.
```
--header 'Accept-Language: pt' \
--header 'api-key: dev_YIuwtNJjD1B53fObhypkm3QhyIK0YrBOfNv7q3Kk3vEYC4d14puZckhktJYxzVFS' \
--data-raw '{
"amount": 1001,
"amount_to_capture": 1001,
"description": "Its my …
```
=> refactor(connector): [itau] refactor error reason and code mapping for itau

crates/diesel_models/src/kv.rs, crates/hyperswitch_domain_models/src/customer.rs, crates/router/src/core/fraud_check/flows/checkout_flow.rs, crates/router/src/core/fraud_check/flows/record_return.rs, crates/router/src/core/fraud_check/flows/sale_flow.rs, crates/router/src/core/fraud_check/flows/transaction_flow.rs, crates/router/src/core/fraud_check/operation/fraud_check_pre.rs, crates/router/src/core/payment_methods.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments/flows.rs, crates/router/src/core/payments/operations/payment_complete_authorize.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_update.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/core/payout_link.rs, crates/router/src/core/payouts.rs, crates/router/src/core/payouts/helpers.rs, crates/router/src/core/payouts/transformers.rs, crates/router/src/core/payouts/validator.rs, crates/router/src/core/utils.rs, crates/router/src/db/customers.rs, crates/router/src/types/api/customers.rs, crates/router/src/types/transformers.rs
Currently we are not able to create customer for customer_v2 since it panics in todo!()  functions, with this pr we will be able to create customer for v2.
Postman test cases
=> refactor(customer_v2): fixed customer_v2 create panic issue

crates/api_models/src/customers.rs, crates/api_models/src/events.rs, crates/diesel_models/src/query/customers.rs, crates/router/src/consts.rs, crates/router/src/core/customers.rs, crates/router/src/core/locker_migration.rs, crates/router/src/db/customers.rs, crates/router/src/db/kafka_store.rs, crates/router/src/routes/customers.rs, crates/router/src/types/api/customers.rs
This PR adds the limit and offset to the customers list endpoint
- Create three customers
```bash
curl --location 'http://localhost:8080/customers' \
--header 'api-key: dev_Grr8XdZ1hcbKc6QtLtAdAq1FP8G5lKNwO3W1DmIUoUCCb9jO88olEX4dzHHTuKan' \
--data-raw '{
"description": "First customer",
"metadata": {
"login_date": "2019-09-10T10:11:12Z"
}
}'
```
- Use the list customer endpoint to list the customer
```bash
curl --location 'http://localhost:8080/customers/list?limit=2&offset=1' \ …
```
=> refactor(customers): add offset and limit to customers list

cypress-tests/cypress/e2e/RoutingTest/00000-PriorityRouting.cy.js, cypress-tests/cypress/e2e/RoutingTest/00001-VolumeBasedRouting.cy.js, cypress-tests/cypress/e2e/RoutingTest/00002-RuleBasedRouting.cy.js
Fixed compilation errors due to filename mismatch.
Updated the hooks in testcases.
Routing testcases are failing in the CI pipeline
This won't fail locally since it won't detect the filename mismatch.Have to run in jenkins.
There are 3testcases are failing due to the hooks. I will fix it in the upcoming PR
=> fix(cypress): fix compilation errors due to filename mismatch

cypress-tests/cypress/e2e/PaymentUtils/Trustpay.js, cypress-tests/cypress/support/redirectionHandler.js
- Giropay is deprecated from trustpay hence added error message
- Fixed elements changes for ideal redirection flow
Test cases were failing
Cypress
Note : Failed test cases are not related to these changes , this will be picked up by @Gnanasundari24
=> ci(cypress): Handle failures for trustpay bank-redirects

crates/router/src/configs/secrets_transformers.rs, crates/router/src/configs/settings.rs
=> chore: fix typos

cypress-tests/cypress.config.js, cypress-tests/cypress/e2e/PaymentUtils/Commons.js, cypress-tests/cypress/e2e/PaymentUtils/Fiservemea.js, cypress-tests/cypress/e2e/RoutingTest/00002-RuleBasedRouting.cy.js, cypress-tests/cypress/support/commands.js, cypress-tests/package-lock.json, cypress-tests/package.json
- This PR aims to fix Cypress throwing error when the `connectorId` is `undefined`. This would occur when `routing` and `payment method list` tests were being run directly without passing the `connectorId` which is in fact redundant
- As for `reports`, we now pass `service` as prefix without which it takes `undefined` as connector name which is not intended and for CI, reportName is considered from `env`
- This PR also addresses one of the issue with `routing` test by removing `should_continue` flag  where Cypress would throw an error stating  it to be not defined
- In addition to that, we now set the `connectorId` in `globalState` during connector create call to address occasional unintended issues where it would not get updated properly
- Bumped Cypress version to `v13.14.0` from …
=> fix(cypress): fix cypress throwing error when `connectorId` is not passed and miscellaneous fixes

crates/router/src/core/utils.rs
send post message to window.parent instead of window.top in external 3ds flow
SDK is making a change of adding an event listener at the parent, this approach is more fault tolerant and SDK would be handling the redirection from post message even when during an architecture / design change in SDK
Sanity External 3DS payment using Netcetera <> Cybersource
=> fix(router): send post message to window.parent instead of window.top in external 3ds flow

crates/storage_impl/src/payouts/payouts.rs
This PR fixes the DB query for fetching a list of active payout IDs, which is later used for getting a total count of available payout objects.
Fixes the payout list API response in #5538  
Fixes the bug for listing payouts on dashboard.
Locally.
Test cases - as mentioned in https://github.com/juspay/hyperswitch/pull/5538
=> fix(payout): query for getting a list of active payout IDs

docker/wasm-build.Dockerfile
It is now required to either enable v1 or v2 feature while building wasm
This PR adds `version_feature_set` build arg with default as `v1` in wasm build dockerfile
Built locally
=> fix(docker): add `version_feature_set` build arg with default as `v1` in wasm build dockerfile

crates/router/src/core/payouts.rs, crates/router/src/routes/app.rs, crates/router/src/routes/payouts.rs
- This PR adds a profile level get filters api for payouts.
Closes #5805.
```
curl --location 'http://localhost:8080/payouts/profile/filter' \
--header 'authorization: Bearer JWT with profile_id' \
--data '{"start_time":"2024-08-05T18:30:00Z","end_time":"2024-09-05T08:19:00Z"}'
```
Response will look like this
```json
{
"connector": [],
"currency": [],
"status": [],
"payout_method": []
}
```
This API should only give filters for payouts which have profile_id as the one in JWT.
This cannot be tested in integ/sandbox as the JWT currently doesn't have profile_id.
=> feat(payouts): Add profile level payout filter API

crates/diesel_models/src/query/payment_attempt.rs, crates/hyperswitch_domain_models/src/lib.rs, crates/hyperswitch_domain_models/src/payments/payment_attempt.rs, crates/hyperswitch_domain_models/src/payments/payment_intent.rs, crates/hyperswitch_domain_models/src/refunds.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/refunds.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/refund.rs, crates/router/src/types/storage/refund.rs, crates/storage_impl/src/mock_db/payment_attempt.rs, crates/storage_impl/src/payments/payment_attempt.rs, crates/storage_impl/src/payments/payment_intent.rs
This is the hotfix PR for https://github.com/juspay/hyperswitch/pull/5827
Currently payment and refund profile_id filter is applied at application level instead if DB level. This change implements filter at DB level instead of Application level.
=> feat: enable payment and refund filter at DB query level

crates/drainer/src/health_check.rs, crates/router/src/connector/globalpay.rs, crates/router/src/core/health_check.rs, crates/router/src/core/payment_methods/surcharge_decision_configs.rs, crates/router/src/core/payments.rs, crates/router_env/tests/env.rs, crates/storage_impl/src/redis/kv_store.rs, crates/storage_impl/src/redis/pub_sub.rs
This PR addresses the clippy lints occurring due to new rust version 1.81.0
This PR addresses clippy lint due to new rust version. So basic sanity testing should suffice.
=> chore: address Rust 1.81.0 clippy lints

crates/router/src/configs/secrets_transformers.rs
Putting the checksum kms decryption under the runtime feature flag
it was a fix for an issue that happened on integ deployment the other day. No testing is required
=> chore: make kms decryption optional if partial auth not enabled

crates/analytics/src/api_event/core.rs, crates/analytics/src/api_event/filters.rs, crates/analytics/src/api_event/metrics.rs, crates/analytics/src/api_event/metrics/api_count.rs, crates/analytics/src/api_event/metrics/latency.rs, crates/analytics/src/api_event/metrics/status_code_count.rs, crates/analytics/src/lib.rs, crates/router/src/analytics.rs
Previously modified api_event_metrics and api_event_filters to authenticate through AuthInfo where there are MerchantLevel, ProfileLevel and OrgLevel authentication. ([https://github.com/juspay/hyperswitch/pull/5729](https://github.com/juspay/hyperswitch/pull/5729))
But ApiEvents table is not populated with `organization_id` and `profile_id`, hence reverting back.
Fix the issues on sandbox analytics related to api_events.
Spoke with dashboard team and removed the following api endpoints:
- /analytics/v1/profile/metrics/api_events
- /analytics/v1/profile/filters/api_events
- /analytics/v1/org/metrics/api_events
- /analytics/v1/org/filters/api_events
=> feat(analytics): Revert api_event metrics and filters back to merchant_id authentication

crates/router/src/core/webhooks/outgoing.rs, crates/router/src/services/api.rs
This PR fixes a bug with the `status_code` field being logged as a string instead of a number in JSON logs. This was primarily happening in two functions: `router::services::api::call_connector_api()` and `router::core::webhooks::outgoing::error_response_handler()`. 
The bug occurred due to the `Debug` implementation of the field being used to log the values (with the `?` sigil). Using the `%` sigil to use the `Display` implementation to log the status code also caused the same problem. The fix was to not provide any sigil (`?` or `%`) and let `tracing` automatically format the status code.
This PR fixes a bug with status codes being sometimes logged as strings, which also caused issues with Elasticsearch being unable to index the field correctly.
1. Create a successful payment using …
=> fix: fix `status_code` being logged as string instead of number in logs

.deepsource.toml, Cargo.lock, Cargo.toml, INSTALL_dependencies.sh, crates/analytics/Cargo.toml
This PR bumps the `sqlx` crate to `0.8.2`. This also allows us to drop our MSRV from 1.80.0 to 1.78.0.
PR #5688 bumped the MSRV to 1.80.0 since `sqlx 0.8.1` required an MSRV of 1.80.0. Now that `0.8.2` is released, we can drop the MSRV to 1.78.0.
N/A.
=> build(deps): bump `sqlx` to `0.8.2`

crates/hyperswitch_interfaces/src/connector_integration_v2.rs, crates/router/src/services/connector_integration_interface.rs
Main branch PR https://github.com/juspay/hyperswitch/pull/5840
Currently few functions in ConnectorIntegrationV2 trait accepts enum Connectors as argument. This prevents the trait from being used outside the repository (through connector_integration module).
Checked if the code compiled successfully.
=> chore: remove Connectors enum dependency from ConnectorIntegrationV2 trait

crates/router/src/connector/zsl/transformers.rs
ZSL implements bank transfer payment, so the payment status is updated through webhooks.
Their webhook body has two fields for indicating the paid amount - `paid_amt` and `consr_paid_amt` we compared 
`paid_amt` with total amount to identify the partial/over payments. But the field for what user paid is given in `consr_paid_amt` and what they will pay the merchant after fee is given in `paid_amt`. 
In this Pr we are fixing this issue.
As we cannot trigger the webhooks, we cannot test it in sandbox
=> fix(connector): [ZSL] compare consr_paid_amt with the total amount for identifying partial payments

crates/common_utils/src/request.rs, crates/hyperswitch_interfaces/src/connector_integration_v2.rs
Currenlty `fn get_request_body` in `ConnectorIntegrationV2` trait returns `RequestContent` type. Modified it to return `Option<RequestContent>`.
This needs to be done since most flows with http get call don't need any RequestBody.
Checked if code compiled successfully.
=> refactor: return optional request body from build_request_v2 in ConnectorIntegrationV2 trait

crates/hyperswitch_domain_models/src/router_data.rs, crates/router/src/types/transformers.rs
revert mask keys in connector_account_details for merchant_connector_response in mca retrieve flow - https://github.com/juspay/hyperswitch/pull/5848
This reverts commit 71b52024c296548156cd80950010a2f1266906fb.
MCA create & retrieve to see api keys are not masked
Sanity payments, captures & refunds
=> revert: feat(router): mask keys in connector_account_details for merchant_connector_response in mca retrieve flow

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/payments.rs, crates/openapi/src/openapi.rs, crates/openapi/src/openapi_v2.rs, crates/router/src/core/payments/transformers.rs
A new field `display_amount` has been added to the `PaymentsDynamicTaxCalculationResponse`. This field holds amounts in the `StringMajorUnit` format, converted from their respective `MinorUnit` values. It includes the `net_amount`, `order_tax_amount`, and `shipping_cost` fields, all intended for display in the SDK.
Hotfix of https://github.com/juspay/hyperswitch/pull/5909
1. Create a Merchant Account 
```
--data-raw '{
"merchant_id": "merchant_1725535996", …
```
=> refactor(core): update response for PaymentsDynamicTaxCalculationResponse

crates/router/src/core/user_role.rs
Currently, profile level user_roles are not being updated. This PR fixes it.
Closes #5906.
```
curl 'http://localhost:8080/user/user/update_role' \
-H 'authorization: Bearer JWT' \
--data-raw '{"email":"email","role_id":"profile_iam_admin"}'
```
Response: 200 OK.
=> fix(user_roles): Populate `profile_id` from token in update user role API

crates/router/src/connector/stripe/transformers.rs
Remove passing customer_acceptance from mandate payment request as, this mandates collecting `ip_address` within the `customer_acceptance` filed. Causing issue in backwards compatibility. For mandate payment, where customer_acceptance passed inside mandate_data - `browser_info.ip_address` is made mandatory. This change will not break the current setup
Hotfix for https://github.com/juspay/hyperswitch/pull/5920
Do a mandate payment with customer_acceptance, passed inside the 
```
--header 'api-key: dev_Q5lDnJyyZPJQBTu6xnMQ3l6TevlS8H6hreld9Fc2MhHG2qYLwfK8NKxv0fd9z0Ib' \
--data-raw '{
"capture_method": …
```
=> fix(router): [stripe] remove passing of customer_acceptance from Mandate Payment Request

cypress-tests/cypress/e2e/PaymentUtils/Commons.js, cypress-tests/cypress/e2e/PaymentUtils/Novalnet.js, cypress-tests/cypress/e2e/PayoutUtils/Commons.js, cypress-tests/cypress/e2e/RoutingTest/00000-PriorityRouting.cy.js, cypress-tests/cypress/e2e/RoutingTest/00001-VolumeBasedRouting.cy.js, cypress-tests/cypress/e2e/RoutingTest/00002-RuleBasedRouting.cy.js, cypress-tests/cypress/e2e/RoutingTest/00003-Retries.cy.js, cypress-tests/cypress/support/commands.js
This PR fixes user logins in routing Cypress framework.
In addition to that, we now also handle a rare case where the spec name will be a single word (`__all`) that resulted in Cypress to stop working.
Its been quite a while since the user login flow was changed and went unhandled in Cypress and no one was bothered to fix given that other tasks were given the priority.
As a matter of fact, this PR **does not** fix the hooks issue that exist in volume and rule based routing.
=> fix(cypress): fix user login in routing cypress framework

crates/router/src/configs/defaults.rs, crates/router/src/core/payment_methods/cards.rs
This is to extend the feature of [collecting address details](https://github.com/juspay/hyperswitch/pull/5418) from wallets to paylater.
Additionally also include phone and country_code in the dynamic fields.
-> Create a merchant connector of Klarna with klarna payment method enabled.
-> Set the below business profile config
```
curl --location 'http://localhost:8080/account/merchant_1726764490/business_profile/pro_XOWZOwYWMAmTV4wEyGgh' \
--header 'api-key: ]' \
--data '{
"collect_billing_details_from_wallet_connector": false,
"collect_shipping_details_from_wallet_connector": false,
"always_collect_shipping_details_from_wallet_connector": true,
"always_collect_billing_details_from_wallet_connector": true
}' …
```
=> refactor(router): add `phone` and `country_code` in dynamic fields

crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
Trim the spaces in IBAN before sending it in SEPA Mandate Post and Direct Debit requests for Deutsche Bank.
https://github.com/juspay/hyperswitch/issues/5976
Request:
```
--header 'api-key: dev_2QpEeK0ByPRkb2DPBxHfad4i1WxQO3hZSuVzlFcg9mTrLFUHRpGfE0SCuQwZjGEb' \
--data '{
"amount": 9000,
"profile_id": "pro_EuXuxP2KVO0m1tlDWSau",
"customer_id": "customer123",
"payment_method": "bank_debit",
"payment_method_type": "sepa",
"bank_debit": {
"sepa_bank_debit": {
"iban": "DE87 1234 5678 1234 5678 90"
}
}
},
"billing": {
"address": {
"last_name": "doe"
}
}, …
```
=> fix(connector): [DEUTSCHE] Trim spaces in IBAN

config/docker_compose.toml, crates/drainer/src/health_check.rs, crates/router/src/bin/scheduler.rs, crates/router/src/routes/health.rs
This PR updates the deep health check error propagation code to build the error reports instead of constructing new errors. As a result of this change, we should now have detailed error reports being logged when there are deep health check failures (which were absent previously).
In addition, this PR fixes the sqlx analytics host name in the Docker Compose config file.
This PR fixes the sqlx analytics host name in the `config/docker_compose.toml` file.
Having detailed error reports during deep health check failures should help debug issues better.
1. I intentionally typo'd the sqlx analytics host name in the `config/development.toml` file, which causes a deep health check failure when the endpoint is accessed.
2. Next, hit the deep health check endpoint:
```shell
curl --include …
```
=> fix: log detailed error reports during deep health check failures

crates/router/src/core/payments/transformers.rs
pr on oss main - [#6003](https://github.com/juspay/hyperswitch/pull/6003)
Currently, in Psync response, payment_method_data is being none. Updated the Psync response with pm data.
For network token pm data will be none, since we are not storing additional pm data in attempt.
For other payment methods,  it will continue to function as it did previously.
payment curl - 
```{
"return_url": "https://duck.com/", …
```
=> fix(core): Update pm details in Psync response

crates/router/src/connector/adyen.rs, crates/router/src/connector/cybersource/transformers.rs
The token received form Samsung Pay will be int the JWT format. The header of that will contain the `kid` which is the `public_key_hash`. This is needs to be passed to Cybersource in the confirm call.
Test Samsung Pay flow
-> Enable Samsung Pay payment method for the connector (Cybersource)
```
{
"api_secret": "api_secret",
"key1": "key1",
"api_key": "api_key"
},
{
{
"installment_payment_enabled": true, …
```
=> fix(connector): pass Samsung Pay `public_key_hash` in the confirm call

docker-compose.yml
In docker for hyperswitch-web we were facing that it's always pointing to beta.hyperswitch.io as `ENV_BACKEND_URL` was not getting passed.
Via checking HyperLoader.js file at 9050 port.
=> fix: env added for hyperswitch-web

crates/router/src/configs/defaults.rs
When we provide address in both billing and payment_method_data.billing, only one will be taken. Hence the details provided in one of the path will discarded. 
eg/- if we provide payment_method_data.billing.phone.number and billing.phone.country_code, we will still throw a `required_field phone_number not found` error. 
PR fixes, this bug for the following payment methods 
1. Ach Bank Transfer
2.Sepa Bank Transfer
3.Bacs Bank Transfer
4.Klarna
5.Affirm 
6.Boleto
7.OnlineBankingPoland
This PR will not affect the current behavior of SDK as SDK has not enabled required_fields for these payment methods
1. Test all the payment methods through SDK, after enabling required fields.
> List PML
```
curl --location 'http://localhost:8080/account/payment_methods?client_secret=pay_4Q5gYsCHR8NzW5aOJQ6A_ …
```
=> fix(router): fix billing details path in required field

config/development.toml, crates/common_utils/src/types/keymanager.rs, crates/hyperswitch_domain_models/src/type_encryption.rs, crates/router/src/configs/defaults.rs, crates/router/src/configs/secrets_transformers.rs, crates/router/src/configs/settings.rs, crates/router/src/configs/validations.rs
This fixes unnecessary failure when url and cert for the keymanager is not provided in the config but keymanager is disabled.
If the keymanager is disabled in the config, there's no reason to provide `url` and `cert` for keymanager since they won't be used. This PR adds a check which checks if keymanager is enabled and only fail for these configs missing if keymanager is enabled
This cannot be tested on any environment
=> fix(config): dont read cert and url if keymanager is disabled

Cargo.lock, crates/api_models/src/payments.rs, crates/cards/Cargo.toml, crates/cards/src/validate.rs, crates/router/src/connector/adyen/transformers.rs, crates/router/src/connector/bankofamerica/transformers.rs, crates/router/src/connector/cybersource/transformers.rs, crates/router/src/connector/stripe/transformers.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_update.rs
Reverts https://github.com/juspay/hyperswitch/pull/5801
Hotfix for https://github.com/juspay/hyperswitch/pull/6142
=> feat(router): revert support for co-badged cards

crates/router/src/core/user_role.rs, crates/router/src/utils/user_role.rs
- Send only same and below Entity Level Users in List Users API.
Closes [#6146](https://github.com/juspay/hyperswitch/issues/6146).
```
curl 'http://localhost:8080/user/user/v2/list' \
-H 'authorization: Bearer JWT' \
```
This API when called with merchant level users, should send org level users in response. Can be tested via control center.
=> fix(user_roles): Send only same and below Entity Level Users in List Users API

.github/workflows/cypress-tests-runner.yml
This PR makes Cypress tests to run against PRs.
At present, it runs against Stripe.
|Jobs|Time taken to build router|Time taken to run Cypress|Overall time consumption|
|-|-|-|-|
|4|18m 02s|07m 18s|26m 53s|
|6|16m 08s|07m 12s|26m 21s|
|6|16m 11s|07m 26s|26m 16s|
|8|15m 47s|07m 13s|24m 44s|
|8|24m 36s|07m 09s|36m 10s|
6 core should be fine for now. Will be monitoring this over a week.
NIL
CI should run against PRs successfully: https://github.com/juspay/hyperswitch/actions/runs/11089890539/job/30811578393?pr=5183
=> feat(ci): add cypress tests to github ci

crates/diesel_models/src/query/payment_attempt.rs, crates/hyperswitch_domain_models/src/payments/payment_attempt.rs, crates/router/src/core/payments.rs, crates/router/src/db/kafka_store.rs, crates/storage_impl/src/mock_db/payment_attempt.rs, crates/storage_impl/src/payments/payment_attempt.rs
Currently `created_at` is not indexed in payment attempt table, when applying filtering with active attempt ids. We are adding extra overhead of checking time_range, though we need not to as we will be already getting filtered attempt ids from intent table.
Closes [#6160](https://github.com/juspay/hyperswitch/issues/6160)
We can hit test api
```
--data '{
"limit": 50,
}'
```
=> fix(payments_list): remove time range to filter payments attempts

crates/hyperswitch_domain_models/src/payments/payment_intent.rs, crates/router/Cargo.toml, crates/router/src/core/admin.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/services/api.rs
Batch Encrypt/Decrypt fields in Payment Intent table
Currently all the encryption/Decryption operation is happening serially. Which adds additional latency, So this PR fixes it by using the Batch encryption/decryption API of Keymanager
Basic sanity testing of `PaymentsCreate` and `PaymentsList`.
1. Call /payments from postman
```bash
--header 'api-key: dev_BPQpf0oItObooOxXtmyACTUJD9TpwU3jjs3YCkStXbCDwMKYCauROqOqqRBQpJLi' \
--data-raw '{
"amount": 600,
"customer_id": "HScustomer1234",
"email": "p143@example.com",
"amount_to_capture": 600,
"description": …
```
=> fix(payment_intent): batch encrypt and decrypt payment intent

.github/workflows/cypress-tests-runner.yml
this pr reduces the jobs required by cargo to build the router for cypress tests from 6 to 4 as a measure to reduce memory consumption that lead to abrupt failures like this one: https://github.com/juspay/hyperswitch/actions/runs/11107215802?pr=6159 (memory usage hit 15.9 gb at one point)
reduce failures in ci
it should not fail in ci abruptly.
=> ci(cypress): reduce cargo build jobs to 4

crates/diesel_models/src/query/user_role.rs, crates/router/src/core/user.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/user_role.rs, crates/router/src/services/authorization/roles/predefined_roles.rs, crates/router/src/types/domain/user.rs
Currently we are inserting user_roles in v1 version and v2 version. Since we have completely moved the APIs to support v2, we don't have to insert v1 anymore.
Allow inviting, updating and deleting org_admins.
Closes #6184
Closes #6186 
All the following APIs will insert only v2 user_roles from now on.
```curl
curl --location 'https://integ-api.hyperswitch.io/user/signup' \
--data-raw '{
"email": "new email",
}'
```
```curl
curl --location 'https://integ-api.hyperswitch.io/user/signup?token_only=true' \
--data '{
"email": "new email",
}'
```
```
curl --location 'https://integ-api.hyperswitch.io/user/connect_account' \ …
```
=> refactor(user_role): Remove V1 insertion for `user_roles` and allow Invites for `org_admins`

api-reference-v2/api-reference/organization/organization--merchant-account--list.mdx, api-reference-v2/api-reference/organization/organization--retrieve.mdx, api-reference-v2/api-reference/organization/organization--update.mdx, api-reference-v2/openapi_spec.json, api-reference/api-reference/organization/organization--retrieve.mdx, api-reference/api-reference/organization/organization--update.mdx, api-reference/openapi_spec.json, crates/openapi/src/routes/organization.rs
changed {organization_id} to {id} in organization endpoints and generated mintlify docs.
=> docs: change organization_id to id in organization endpoints

crates/router/src/core/user_role.rs
- Currently update user role API allows updating a merchant level user role to profile level, which should not be possible.
Closes #6222.
```curl
curl --location 'http://localhost:8080/user/user/update_role' \
--header 'Authorization: JWT' \
--data-raw '{
"email": "merchant level user email",
"role_id": "profile_admin"
}'
```
This call should throw the following error.
```json
{
"error": {
"message": "User Role Operation Not Supported",
"code": "UR_23"
}
}
```
=> fix(user_role): Restrict updating user role to the same `EntityType`

docker-compose-development.yml
Fixes: https://github.com/juspay/hyperswitch/issues/6216
Builds a docker image with protobuf for hyperswitch-server.
Refer here for the issue Fixes: https://github.com/juspay/hyperswitch/issues/6216
docker compose --file docker-compose-development.yml up -d
=> build(docker-compose-development): address build failure of `hyperswitch-server` service

crates/diesel_models/src/query/user_role.rs, crates/router/src/core/user.rs, crates/router/src/core/user_role.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/user_role.rs, crates/router/src/utils/user_role.rs
Currently accepting invites for org_admin will not work. This PR fixes it.
Closes [#6254](https://github.com/juspay/hyperswitch/issues/6254)
```
curl 'http://localhost:8080/user/accept_invite_from_email' \
-H 'authorization: Bearer SPT with accept_invite_from_email' \
--data-raw '{"token":"email token"}'
```
Response:
```json
{
"token": "JWT",
"token_type": "user_info"
}
```
=> fix(users): Allow accepting invites for `org_admin`s

crates/router/src/core/webhooks/outgoing.rs
This PR introduces user agent as a new header in outgoing webhooks. 
This will prevent our webhooks getting blocked from security firewalls.
Test outgoing webhooks.
=> refactor: add user agent header in outgoing webhooks

api-reference-v2/openapi_spec.json, crates/openapi/src/routes/profile.rs
Add X-Merchant-Id to headers in Profile endpoints for v2
=> docs(v2): Added 'X-Merchant-Id' to headers in Profile API docs

cypress-tests/cypress/e2e/RoutingTest/00003-Retries.cy.js, cypress-tests/cypress/support/commands.js
This pull request resolves issue #5913 
This PR refactors the existing Cypress commands used for configuration updates (autoRetryConfig, setMaxAutoRetries, and stepUp) into a single unified command cy.updateConfig. The refactor helps reduce redundancy in the codebase by consolidating multiple similar implementations into one versatile command that can handle configuration changes for auto retries, max retries, and step-up flows.
-Combined autoRetryConfig, setMaxAutoRetries, and stepUp into the cy.updateConfig command.
-Updated the Retries.cy.js test cases to use the new unified command for disabling/enabling auto retries and step-up configurations.
The refactor was necessary to reduce code duplication and improve maintainability. By creating a unified command, we ensure that future …
=> refactor(cypress): reuse config update command

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml, crates/hyperswitch_connectors/src/connectors/fiuu.rs, crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
Add support for payment and refund webhooks
note: Needs dashboard wasm deployment to test in sandbox.
Test cases : 
**Payment Webhooks**
<details>
<summary>Create payment(curl ) </summary>
```
--header 'api-key: dev_b8UHhFyzeGg5ftn9f6oGstBF6gWmxtrCpvWaj6KL7dj9NSBeSmHS9q9Mg5UU7d7O' \
--data-raw '{
"amount":100,
"currency": "MYR",
"payment_link" : false, …
```
=> feat(connector): [fiuu] Add support for payment and refund webhooks

.github/CODEOWNERS, crates/api_models/src/pm_auth.rs, crates/pm_auth/src/connector/plaid/transformers.rs, crates/pm_auth/src/types.rs, crates/router/src/connector/plaid/transformers.rs, crates/router/src/core/pm_auth.rs, crates/router/src/routes/pm_auth.rs
Make header data to consume in open banking flows as optional.
Test all open banking flows (PM auth and Payment initiation)
Refer to this PR - https://github.com/juspay/hyperswitch/pull/3952
=> fix: Set headers as optional in ob flows

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/payments.rs, crates/common_enums/src/enums.rs, crates/hyperswitch_domain_models/src/router_request_types.rs, crates/hyperswitch_domain_models/src/router_response_types.rs, crates/hyperswitch_interfaces/src/types.rs, crates/router/src/connector/paypal.rs, crates/router/src/connector/paypal/transformers.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/flows.rs, crates/router/src/core/payments/operations/payment_approve.rs, crates/router/src/core/payments/operations/payment_cancel.rs, crates/router/src/core/payments/operations/payment_capture.rs, crates/router/src/core/payments/operations/payment_complete_authorize.rs, crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/operations/payment_post_session_tokens.rs, crates/router/src/core/payments/operations/payment_reject.rs, crates/router/src/core/payments/operations/payment_response.rs, crates/router/src/core/payments/operations/payment_session.rs, crates/router/src/core/payments/operations/payment_start.rs, crates/router/src/core/payments/operations/payment_status.rs, crates/router/src/core/payments/operations/payment_update.rs, crates/router/src/core/payments/operations/payments_incremental_authorization.rs, crates/router/src/core/payments/operations/tax_calculation.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/types.rs, crates/router/tests/connectors/utils.rs
- implement session update flow for Paypal
- implement post_update_tracker for SessionUpdate Flow 
hotfix for [PR](https://github.com/juspay/hyperswitch/pull/6299)
1. Create Merchant Account
```
--data-raw '{
"merchant_id": "merchant_1728546485",
"about_business": "Online Retail …
```
=> feat(router): implement post_update_tracker for SessionUpdate Flow and add support for session_update_flow for Paypal

crates/api_models/src/payments.rs, crates/diesel_models/src/query/payment_attempt.rs, crates/hyperswitch_domain_models/src/payments/payment_attempt.rs, crates/router/src/core/payments.rs, crates/router/src/db/kafka_store.rs, crates/router/src/routes/metrics.rs, crates/router/src/routes/payments.rs, crates/storage_impl/src/mock_db/payment_attempt.rs, crates/storage_impl/src/payments/payment_attempt.rs
- Skip count query if no filters are applied for attempts, in this we don't need to filter attempts as count of active attempt ids will be the total count.
- Profile id filter is already getting applied in intents, so removing it from last active attempts.
- Add logging around count query.
Closes [#6330](https://github.com/juspay/hyperswitch/issues/6330)
For Tests Lists working is same, same request and response:
```
--header 'x-api-key: dev_VWtyXkyK1Ath1vBNRMM4dqm18J0PVW8SiML4IsKtuzpsR5ojI0FCDBIY0ZRggpFf' \
--data '{
}'
``` 
Response will be something like
```
{
"count": 0,
"total_count": 0,
"data": []
}
```
Log …
=> fix(payments_list): skip count query if no filters and add logging

crates/router/src/core/payments.rs
In the MIT flow when the recurring details is of type "type": "network_transaction_id_and_card_details" the eligible connector needs to be set in the payment attempt.
Create merchant connector account for cybersource
-> Make a MIT payment with `"type": "network_transaction_id_and_card_details"`
```
--header 'api-key: dev_OJYRaFClX8PIIwCNrPWUMttJWZrAXUNbBiyA1GvyYyaxRK5EsqODd2ON8KTOlTMa' \
--data-raw '{
"amount": 499,
"off_session": true,
"recurring_details": {
"type": …
```
=> fix(router): set the eligible connector in the payment attempt for nti based mit flow

config/config.example.toml, config/deployments/env_specific.toml, config/development.toml, config/docker_compose.toml, config/vector.yaml, crates/analytics/src/opensearch.rs, crates/analytics/src/search.rs, crates/api_models/src/analytics/search.rs, crates/router/src/consts/opensearch.rs
Global search has two components:
- Free flow search, wherein search takes place across all fields available to search upon
- Search on a specific field based on the field filter
In this PR, additional filters have been added for global search to search on a specific field.
A list of values can be provided for every filter field which will be added to the query in order to extract responses from opensearch / elasticsearch.
Existing filters (fields):
- payment_method
- currency
- status
- customer_email
- search_tags
New filters added (fields):
- connector
- payment_method_type
- card_network
- card_last_4
- payment_id
Enhance search experience on global search using filters
The following filters can be used to be searched upon:
- connector
- payment_method_type
- card_network
- …
=> feat(opensearch): add additional global search filters and create sessionizer indexes for local

crates/router/src/core/payments/operations/payment_response.rs
Earlier we used to store the connector mandate id only in case of charged payments, Ideally we should store for both authorized and charged
Earlier 
**CIT 3DS Auth**
```
--header 'api-key: dev_l2PIg8yKpNpJYfXwnSgY8IppXOrB0Nz9OAfD36Y6Xtar5h5nyO5AgVhulydeirKW' \
--data-raw '{
"currency":"USD",
"amount": 300,
"amount_to_capture": 300,
"customer_id": "malay12345",
"description": "Its my first payment …
```
=> fix(mandates): Allow connector_mandate_detail updation in case of  'Authorized' Payments

.github/workflows/cypress-tests-runner.yml, cypress-tests/cypress.config.js, cypress-tests/readme.md, scripts/execute_cypress.sh
This PR makes it possible for us to run Cypress tests in parallel by leveraging `gnu-parallel`.
At present, we'll only be running against 5 connectors namely,
- payments: bluesnap, cybersource, stripe
- payouts: adyen and wise
w.r.t pml and other connectors, there are some failures within the tests that needs to be addressed.
>[!IMPORTANT]
> Cypress in parallel is resource heavy and running it in batch of 3+ will result in unintended consequences like abrupt failures due to resource limitation.
Running Cypress tests in parallel also puts up a challenge where when a specific test fails for 2 connectors at the same time, test against both the connectors stops abruptly. This is because of the file name conflict as we not have the privilege to change the names of the screenshots while …
=> feat(cypress): execute cypress tests in parallel

crates/router/src/connector/worldpay.rs, crates/router/src/connector/worldpay/response.rs, crates/router/src/connector/worldpay/transformers.rs
Described in #6316 (point # 2)
Helps in error code unification for understanding the errors better.
Tested locally using test cards and magic values for intentionally returning a refused response - https://developer.worldpay.com/products/access/card-payments/testing#test-card-numbers
Things to test
1. Non 3DS payments
2. 3DS payments
<details>
<summary>1. Non 3DS payments</summary>
Use magic values for cardHolderName - https://developer.worldpay.com/products/access/card-payments/testing#issuer-response-test-values
cURL
--header 'api-key: dev_sMl3D9efytjSoXznSOKCv5PHyql50M1BMhU8e7qsa5m6mXxHvyROVg7cER7AWue9' \
--data-raw …
=> refactor(connector): [WorldPay] propagate refusal codes as error code and messages

crates/router/src/connector/shift4.rs, crates/router/src/connector/shift4/transformers.rs, crates/router/src/types/api.rs, crates/router/tests/connectors/shift4.rs
This PR adds amount conversion framework to Shift4, for sending to connector.
Resolves #6122
=> refactor(connector): add amount conversion framework to Shift4

api-reference-v2/rust_locker_open_api_spec.yml, api-reference/rust_locker_open_api_spec.yml
Improved wording in the edit files.
Fixes #6321.
Manually inspected the changed files.
=> docs(openapi): improve `rust_locker_open_api_spec`

crates/api_models/src/payment_methods.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments.rs
Earlier a connector was occurring twice while doing a session token call for wallets. This PR fixes merchant payment method list to retain a mca based on connector_name and mca_id. So that with every distinct mca_id the connector is listed just once for wallets.
- Create a MA and an MCA(with wallets enabled)
- Create an payment_intent 
```
Intent Response
{
"payment_id": "pay_NHWegNguTfDH9hxuVj1m",
"merchant_id": "merchant_1729514766",
"status": "requires_payment_method",
"amount": 8500,
"net_amount": 8500,
"shipping_cost": null,
"connector": null,
"client_secret": "pay_NHWegNguTfDH9hxuVj1m_secret_YgCdjC1ZMbdqGBmOOoTP",
"created": "2024-10-21T13:11:49.384Z",
"customer_id": "CustomerX777",
"customer": {
"id": …
```
=> fix(payment_methods): fix merchant payment method list to retain a mca based on connector_name and mca_id

crates/api_models/src/analytics/refunds.rs
- Whenever `Refund Status` filter is applied on the analytics section on dashboard, errors are being generated.
- The wrong `RefundStatus` enum has been imported for the `RefundStatus` filter in `RefundFilters` struct in this PR: [https://github.com/juspay/hyperswitch/pull/2988](https://github.com/juspay/hyperswitch/pull/2988).
- Updated the code to use the correct `RefundStatus` import.
To fix the issue on dashboard whenever refund status filter is applied.
- Apply the refund status filter on the dashboard
- Hit the curl:
```bash
curl --location 'http://localhost:8080/analytics/v1/org/metrics/refunds' \
--header 'Origin: …
```
=> fix(analytics): fix refund status filter on dashboard

crates/router/src/core/payments/operations/payment_response.rs
This is hot fix for the [PR](https://github.com/juspay/hyperswitch/pull/6446)
Earlier, for setup mandate flows we were not populating  the Payment Method Info field, due to which for the Setup Mandate Payments the connector_mandate_details where not getting populated in the payment methods table.  This PR fixes setup mandate payments to store connector mandate details, in the payment methods table. 
- Create a Off -session payment , with 0 dollar
```
Create
--header 'api-key: dev_x0Y92cBUtNSQwvW9B6xfQRtg8NxoURcyMbGh9kiqxO5EfMidDo31Ji6McelAQv9M' \
--data-raw '{
"amount": 0, …
```
=> fix(core): fix setup mandate payments to store connector mandate details

cypress-tests/cypress/e2e/PaymentTest/00006-VoidPayment.cy.js, cypress-tests/cypress/e2e/PaymentTest/00013-SaveCardFlow.cy.js, cypress-tests/cypress/e2e/PaymentTest/00020-Variations.cy.js, cypress-tests/cypress/e2e/PaymentUtils/Commons.js, cypress-tests/cypress/e2e/PaymentUtils/Paybox.js, cypress-tests/cypress/e2e/PaymentUtils/Utils.js, cypress-tests/cypress/e2e/PaymentUtils/WorldPay.js, cypress-tests/cypress/fixtures/create-connector-body.json, cypress-tests/cypress/support/commands.js, cypress-tests/cypress/support/redirectionHandler.js
Described in #6316 point # 4 (read comments)
Helps in sanity testing of Worldpay connector.
Locally using `npm run cypress:payments`
=> feat(cypress-test): include worldpay's request / response structure for test suite

crates/analytics/src/payments/metrics/sessionized_metrics/failure_reasons.rs
- Currently, the `limit by` clause in query_builder of `failure_reasons` metric has only `connector` hardcoded.
- Changed this behaviour to enable dynamic addition of `group` by fields to the `limit by` clause as well.
Prevent errors when connector is not passed as a group by and also provide dynamic combination of error_reason with other filters like connector, payment_method, payment_method_type, etc.
Hit the curl:
```bash
curl --location 'http://localhost:8080/analytics/v1/org/metrics/payments' \
--header …
```
=> fix(analytics): add dynamic limit by clause in failure reasons metric query

INSTALL_dependencies.sh, aws/hyperswitch_aws_setup.sh, aws/hyperswitch_cleanup_setup.sh, scripts/add_connector.sh
Use $(...) notation instead of legacy `...` in the shell files.
Removes the use of deprecated backticks notation (cf. [SC2006](https://www.shellcheck.net/wiki/SC2006)).
Fixes https://github.com/juspay/hyperswitch/issues/6271
=> fix: replace deprecated backticks with $(...) for command substitution

crates/router/src/connector/cybersource/transformers.rs
Newline in billing address failing the payment in production (speculated). This pr removes the newline (if present) in billing address with space.
Corresponding hotfix PR to #6478 
- Create a MCA for cybersource:
- Create a Payment with Cybersource:
```
{
"amount": 499,
"request_external_three_ds_authentication": true,
},
"card": {
"card_exp_year": "2030",
"card_holder_name": "Test Holder",
"card_cvc": "737"
}
},
"billing": {
"address": {
"city": …
```
=> fix(connector): [Cybersource] remove newline in billing address with space

.gitignore, docs/try_local_system.md, flake.lock, flake.nix
Described in #57 
Removes dependency on brew for installing and managing external services - redis and Postgres.
Locally.
- Make sure nix is installed
- `nix run .#ext-services`
=> feat(nix): add support for running external services through services-flake

crates/router/src/connector/paybox/transformers.rs, crates/router/src/core/payments/operations/payment_confirm.rs
1)Payment Method Data was not getting populated in db in case of Payment via the saved card (off/On session ). 
2) Connector_mandate_request_refernce_id  was not correctly passed in Paybox Connector in case of 3DS flow 
Test: Create +Confirm
```
Request
--header 'api-key: dev_jVzJl283ZzMdgIrFQY2jqFaI1GyU7hiLariAvovvHPLh1S7jfWNKxIbofZJNkodO' \
--data-raw '{
"customer_id": "test123",
"description": "Its my first …
```
=> fix(core): PMD Not Getting Populated for Saved Card Transactions 

crates/router/src/core/payments/flows/session_flow.rs, crates/router/src/core/payments/helpers.rs
Currently we have apple pay certificates being stored in the `metadata` as well as `connector_wallet_details` when a merchant connector account is created. During the session call we try to get the certificates from the `connector_wallet_details` if it fails we try to get it from `metadata`. 
Currently when apple pay certificates are being updated with the merchant connector update call only the metadata is being updated. Because of this `connector_wallet_details` will still have the old data using which we make the session call.
In order to fix it, this pr contains the changes to get the `apple pay certificates` from the `metadata` only as it will have the latest updated data. In subsequent pr mca update inconsistency will be handled.
-> Create merchant connector account with apple pay …
=> fix(router): get apple pay certificates only from metadata during the session call

crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs
Novalnet expects decoded wallet token for applepay. Previously encoded wallet token was being sent.
Not able to test applepay locally. Can be tested in sbx.
=> fix(connector): [Novalnet] Send decoded wallet token to applepay

crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payment_methods/migration.rs
Added support to migrate expired cards 
req for migration api - 
```
curl --location 'http://localhost:8080/payment_methods/migrate' \
--header 'api-key: api-key' \
--data '{
"merchant_id": "merchant_id",
"card": {
"card_number": "<card_number>",
"card_exp_month": "12",
"card_exp_year": "21",
"card_holder_name": "joseph Doe"
},
"customer_id": "cust-1731038739",
"network_transaction_id": "ntid-test-2",
"payment_method":"card"
}'
```
=> refactor(router): Remove card exp validation for migration api

crates/router/src/configs/defaults/payment_connector_required_fields.rs
1.  Added mandatory fields for googlepay, paypal and applepay  needed for Novalnet  in config
2. Added mandatory fields for card mandates needed for Novalnet  in config
Fix to this issue https://github.com/juspay/hyperswitch-cloud/issues/7291
Manually tested with postman
Payment Methods Response
`{
"redirect_url": "https://google.com/success",
{
{
"payment_experience": [
{
"payment_experience_type": "redirect_to_url",
"novalnet"
]
}
],
"bank_names": null,
"bank_debits": null,
"bank_transfers": null,
"required_fields": {
"billing.address.zip": {
"required_field": "payment_method_data.billing.address.zip", …
=> fix(connector): [Novalnet] Add mandatory fields for wallets and card in config

crates/router/src/core/generic_link/payout_link/initiate/script.js, crates/router/src/core/payment_link/payment_link_initiate/secure_payment_link_initiator.js
Described in https://github.com/juspay/hyperswitch-web/issues/773
Helps secure links handle redirections for 3ds txns for payments and end return URLs for payouts.
Locally, using iframed links.
<details>
<summary>1. Enable secure links by setting up allowed domains</summary>
cURL
curl --location 'http://localhost:8080/account/merchant_1730884662/business_profile/pro_4eqlNAJWOPckKqn59OBB' \
--data '{"payment_link_config":{"allowed_domains":["*"],"enabled_saved_payment_method":false,"theme":"#1A1A1A","logo":"https://hyperswitch.io/favicon.ico"}}'
</details>
<details>
<summary>2. Create a payment link</summary>
cURL …
=> refactor: explicitly specify top redirections for secure payment and payout links

cypress-tests/cypress/support/redirectionHandler.js
Fix EPS Bank Redirect redirection in Cypress.
Closes #6528
NIL
=> fix: trustpay `eps` redirection in cypress

crates/router/src/core/payments/operations/payment_reject.rs, crates/router/src/events/audit_events.rs
Pass along request_state to payment_core
Modify the UpdateTracker trait to accept request state
Modify the PaymentReject implementation of UpdateTracker to generate an event
Files changed
1. `crates/router/src/core/payments/operations/payment_reject.rs`
2. `crates/router/src/events/audit_events.rs`
Resolves #4669 
This requires FRM related flows to be tested, and may not be tested locally.
=> feat(events): Add payment reject audit events

crates/router/src/core/routing/helpers.rs
This will remove payment_id from being pushed to dynamic_routing metrics
This can be tested on SBX in the dynamic_routing Dashboard present on grafana dashboard,
There shouldn't be payment_id and the merchant_id should be merged with profile_id
=> refactor(routing): remove payment_id from dynamic_routing metrics

crates/analytics/docs/README.md
Now that `analytics` depends on `currency_conversion` crate after this [PR](#6418), we need to include instructions in `analytics` documentation to set up this service.
This is related to the PR #6418 and documents the necessary prerequisite setup info.
=> docs(analytics): add setup instructions for currency_conversion service

crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/transformers.rs
hotfix PR for https://github.com/juspay/hyperswitch/pull/6519
=> fix(payments): populate payment_method_type in payment_attempt for cards

cypress-tests/cypress/e2e/PaymentUtils/Iatapay.js
Handled zero auth mandates for Iatapay connector in cypress automation
Zero auth payments test cases were failing for Iatapay
- Iatapay
=> ci(cypress): Fix Iatapay Zero Auth Mandates Flow

cypress-tests/cypress/e2e/PaymentTest/00014-SaveCardFlow.cy.js, cypress-tests/cypress/e2e/PaymentTest/00016-ThreeDSManualCapture.cy.js, cypress-tests/cypress/e2e/PaymentUtils/Checkout.js, cypress-tests/cypress/e2e/PaymentUtils/Utils.js, cypress-tests/cypress/support/redirectionHandler.js
Add Checkout Connector for Cypress Automation 
Checkout connector was not available in the cypress automation 
Cypress Tests 
- Checkout 
- NMI
=> ci(cypress): Add Checkout Connector

crates/router/src/core/routing.rs, crates/router/src/routes/app.rs, crates/router/src/routes/routing.rs
This will refactor the route `routing/default/profile`
Previously the output for this route was the default fallback connectors from all the profiles, 
After this refactor it will have the fallback connectors only for the mentioned profile. If the `profile_id` is provided by the authentication layer, if not it will behave as previous by taking the `merchant_id` from auth layer.
Moreover we have removed 2 routes from backed as these were not being used(Dahboard as well as internal apis), hence were redundant.
GET `routing/default`
POST `routing/default`
Required by our Dashboard to move the api's under profile level
```
curl --location 'http://127.0.0.1:8080/routing/default/profile' \
--header 'Authorization: Bearer token
```
This should have the connectors from the mentioned profile only. …
=> refactor(core): add profile_id for default_fallback api

crates/hyperswitch_connectors/src/connectors/novalnet.rs, crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs
Added dispute support for novalnet.  Novalnet supports 2 webhook events for disputes
1. Chargeback 
2. Representment (dispute won)
Novalnet does not support emails/webhooks for Arbitration and Pre-Arbitration stages. 
https://github.com/juspay/hyperswitch-cloud
Tested locally with dispute webhook simulators given in novalnet documentation
**Chargeback webhook simulator:** https://developer.novalnet.com/asynchronousnotification/parameterspassed?payment=chargeback_creditcard_chargeback#parameter-list
**Representment webhook simulator:** https://developer.novalnet.com/asynchronousnotification/parameterspassed?payment=credit_creditcard_representment#parameter-list
**Chargeback webhook output**
**Representment webhook output**
=> feat(connector): [Novalnet] Add support for disputes 

crates/router/src/connector/adyen/transformers.rs
For adyen incase of reponse update with webhooks,  we are hardcoding error code and message to none and while propagating checking whether error code & message is some, This pr fixes this bug .
Make 3ds payment via adyen and cancel it in adyen simulator. block the redirect response in the browser so that payment is updated via webhook. Do a retrieve call error code & error message should be updated as per below response 
```
{
"payment_id": "pay_xaWbqtvgCc8CuBKaMXmp",
"merchant_id": "merchant_1731937042",
"status": "failed",
"amount": 2957000,
"net_amount": 2957000,
"shipping_cost": null,
"connector": "adyen",
"client_secret": "pay_xaWbqtvgCc8CuBKaMXmp_secret_WZ701MiltGrC0FjAoOEB",
"created": "2024-11-18T19:11:13.043Z",
"currency": "AUD", …
```
=> fix(connector): [Adyen]fix error code and message for webhooks response

crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs, crates/router/src/configs/defaults/payment_connector_required_fields.rs
Added minimal customer data feature. To use this the payments request body should have `"no_nc":  1`. 
With this enabled, `billing`, `customer_ip` wont be needed in request body anymore 
Details: https://developer.novalnet.com/onlinepayments/aboutminimalcustomerdata
Tested locally for cards
`curl --location --request POST 'http://localhost:8080/payments' \
--header 'api-key: dev_uMzYVQ13nwcIGJPBPuAUYOoH7EpGhb48w3cYLMn1Y34u6fxzUqmACEhkWrK3SrSq' \
--data-raw '{
"amount_to_capture": 10000,
"name": "John …
=> feat(connector): [Novalnet] Add minimal customer data feature 

crates/api_models/src/analytics/payment_intents.rs
There is a serialization issue for `card_last_4` and `authentication_type` fields when filters are getting applied for `PaymentIntentFilters`.
`card_last_4` was being processed as `card_last4` .
`auth_type` is being used to add the filters and not serialized into `Authentication_type`.
Made the changes to properly serialize `card_last_4` and `authentication_type` filters for `PaymentIntentFilters` now.
Fix the filters issue for some fields for Payment Intents.
`authentication_type`:
Hit the curl for any metric of payment_intents (sessionized metrics):
```bash
curl --location 'http://localhost:8080/analytics/v2/org/metrics/payments' \ …
```
=> fix(analytics): fix `authentication_type` and `card_last_4` fields serialization for payment_intent_filters

crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs
1. Fetching email from customer email if billing.email is not present ,  so in HS payment request body we wont need billing.email anymore 
2. Removed `customer_ip` from payments request since it is not a mandatory field for novalnet, so in HS payment request body we wont need browser_info anymore 
Checked locally without passing billing.email and browser_info 
`{
"amount_to_capture": 10000, …
=> fix(connector): [Novalnet]  Get email from customer email if billing.email is not present 

crates/analytics/src/payment_intents/metrics/payment_processed_amount.rs, crates/analytics/src/payment_intents/metrics/payments_success_rate.rs, crates/analytics/src/payment_intents/metrics/sessionized_metrics/payment_processed_amount.rs, crates/analytics/src/payment_intents/metrics/sessionized_metrics/payments_distribution.rs, crates/analytics/src/payment_intents/metrics/sessionized_metrics/payments_success_rate.rs, crates/analytics/src/payment_intents/metrics/sessionized_metrics/smart_retried_amount.rs, crates/analytics/src/payment_intents/metrics/smart_retried_amount.rs
`first_attempt` as a group by is getting added internally in the queries as it is required by the new PaymentIntent based metrics for Analytics V2 Dashboard.
The logic was added for the existing older metrics as well for PaymentIntents on the older dashboard, and is failing when using sqlx as the Pool.
Need to remove the logic for adding `first_attempt` as a group_by in the older metrics, and also tweak the manner in which this is getting added as a group_by in the new metrics.
Fix the error when using older metrics on the old dashboard (PaymentIntent based metrics)
Hit the curls to test the various metrics.
Sessionized_metrics should be tested only on clickhouse.
Older metricss can be tested on both sqlx and clickhouse.
```bash …
```
=> fix(analytics): remove first_attempt group by in Payment Intent old metrics

cypress-tests/cypress/e2e/PaymentUtils/Commons.js, cypress-tests/cypress/e2e/PaymentUtils/Noon.js, cypress-tests/cypress/e2e/PaymentUtils/Utils.js
Add Noon Connector for Cypress Automation
Note : Noon supports only 3ds payments , so all the no_three_ds payments are skipped  
Noon connector was not available in the cypress automation
=> ci(cypress): Add Noon Connector

crates/router/src/connector/cybersource/transformers.rs
Change the commerce indicator for cybersource applepay payment which was failing payment in production
Hotfix correspond to PR - [#6634](https://github.com/juspay/hyperswitch/pull/6634)
Note: This pr is crucial for flowbird
- Create an MCA for Cybersource:
- Create a Payment with Applepay: 
```
{
"amount": 650, …
```
=> fix(connector): [Cybersource] change commerce indicator for applepay

crates/analytics/src/payments/filters.rs, crates/analytics/src/payments/types.rs, crates/analytics/src/query.rs, crates/analytics/src/sqlx.rs, crates/api_models/src/analytics/payments.rs
Added `first_attempt` as a filter in `PaymentFilters`.
This is required for the new Analytics v2 `Smart Retries` Metrics, specifically `Smart Retries Successful Distribution` and `Smart Retries Failure Distribution`, for calculations only involving smart retries (ignoring first attempts).
Helps in calculating certain metrics seamlessly.
=> feat(analytics): add `first_attempt` as a filter for PaymentFilters

crates/router/src/core/refunds.rs, crates/router/src/types/transformers.rs, crates/router/src/utils.rs
Trigger refund outgoing webhooks in create and retrieve refund flows. 
Test cases : 
1) Create a refund without configuring incoming webhooks, this should trigger outgoing webhook to merchant
2) If possible create a refund with processing and update the status by force sync, Upon status update it should trigger outgoing webhook to merchant.
Refund created with webhooks configured with immediate status = 'success' 
outgoing webhook triggered for the same event.
=> feat(refunds): Trigger refund outgoing webhooks in create and retrieve refund flows

cypress-tests-v2/package-lock.json, cypress-tests-v2/package.json, cypress-tests/package-lock.json, cypress-tests/package.json
This PR update Cypress packages to address [CVE-2024-21538](https://vulert.com/vuln-db/CVE-2024-21538).
Closes https://github.com/juspay/hyperswitch/issues/6623
CVE.
No tests needed as it is just a dependency update. CI passing should be enough.
=> chore(deps): update cypress packages to address CVE

crates/api_models/src/payments.rs, crates/hyperswitch_domain_models/src/payments/payment_intent.rs, crates/router/src/types/storage/dispute.rs, crates/router/src/types/storage/refund.rs, crates/storage_impl/src/payments/payment_intent.rs
The PR
- Add merchant order reference id filter for payments list
- Fix bug for search by refund id (or payment_id), using `or` instead of `or_filter`. Earlier we were searching in whole list, ignoring the filter previously applied in the query.
However this was the only case for when we were searching dynamically for ids, it can be payment or refund id. It was producing correct result when searching for only payment id or only refund id. 
Closes [#6629](https://github.com/juspay/hyperswitch/issues/6629)
Merchant Order filter is working as expected
Request
```
--data '{
"merchant_order_reference_id": "test"
}'
``` …
=> feat(payments): add merchant order ref id filter

.github/workflows/cypress-tests-runner.yml
Use ubuntu runners instead.
closes https://github.com/juspay/hyperswitch/issues/6656
NA
See if CI checks pass.
=> ci(cypress): use ubuntu runner

cypress-tests/cypress/e2e/PaymentTest/00013-ListAndRevokeMandate.cy.js, cypress-tests/cypress/support/commands.js
Added the list mandate and revoke mandates for zero auth mandate payment
Removed the fiuu hardcoded checks which is invalid for few connectors
To cover the scenarios for cypress
=> ci(cypress): Add list and revoke for zero auth mandate payments

crates/api_models/src/payment_methods.rs, crates/hyperswitch_domain_models/src/payment_method_data.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/core/payments/tokenization.rs
Described in #5858 # 2 point
Helps the requestor identify the cards used for GooglePay MIT
Using Adyen's GPay CIT and MIT transactions
<details>
<summary>1. Create a payment link (CIT for future uses)</summary>
cURL
--header 'api-key: dev_y1KsGsLkn9B3ZruidtCYZVHA5sGL6u9vlIwTMhLD1QsVp04x766uWdrvc7st37At' \
--data-raw '{"authentication_type":"no_three_ds","customer_id":"cus_DYMtbNUqf3wErjOjcZXy","profile_id":"pro_sM6tKJWMBFyr4lsWTpcI","amount":100,"currency":"USD","payment_link":true,"setup_future_usage":"off_session","connector":["adyen"],"capture_method":"automatic","email":"john.doe@example.com","session_expiry":10000,"return_url":"https://exa …
=> feat(payments): propagate additional payment method data for google pay during MIT

crates/router/src/core/user.rs
Currently in invites we don't check if user exists across entities.
This will be a problem when inviting a user with higher entity from different lineage.
This PR fixes it.
Closes #6679.
1. Invite a user in a specific (org, merchant, profile) combination.
2. Create a new profile in the same merchant account and switch to it.
3. Invite the same user as merchant level user. This should be stopped by API.
=> fix(users): Check lineage across entities in invite

crates/api_models/src/connector_enums.rs, crates/hyperswitch_connectors/src/connectors/cashtocode.rs, crates/hyperswitch_connectors/src/connectors/worldline.rs, crates/hyperswitch_connectors/src/connectors/zen.rs, crates/hyperswitch_connectors/src/connectors/zsl.rs, crates/hyperswitch_interfaces/src/webhooks.rs, crates/router/src/connector/adyen.rs, crates/router/src/connector/adyenplatform.rs, crates/router/src/connector/braintree.rs, crates/router/src/core/webhooks/incoming.rs, crates/router/src/core/webhooks/incoming_v2.rs, crates/router/src/services/connector_integration_interface.rs
In webhook, for specific connectors, we want to consume every webhook that arrives even if a error occurs while processing. This is done to keep the webhook channel open with the connector. 
In this pr, a error wrapper is introduced to handle this logic where based on connector, we choose whether to send error or not.
- Create a MCA (Adyenplatform):
- Setup webhook endpoint in dashboard (Adyenplatform):
- Create a payout:
```
{
"amount": 100,
"customer_id": "sakilcust",
"priority": "instant",
"bank": {
"iban": "DE89370400440532013000"
}
},
"billing": {
"address": { …
```
=> refactor(core): add error handling wrapper to wehbook

crates/analytics/src/query.rs
Fixes this issue: [https://github.com/juspay/hyperswitch-cloud/issues/7580](https://github.com/juspay/hyperswitch-cloud/issues/7580)
- `first_attempt` filter takes in `true` or `false` as variants.
- But while it is getting applied in the query, it is being converted into a string:
`'true'` or `'false'`
This works on latest clickhouse versions, but fails on the older clickhouse versions, with the error:
```error
DB::Exception: Cannot convert string false to type Bool: While processing (first_attempt IN ('false'))
```
Now, internally converting `'true'` to `'1'` and `'false'` to `'0'` to fix the issue, and this gets accepted in both the versions.
The query which was previously running was:
```bash
SELECT connector, status, sum(sign_flag) as count, first_attempt, min(created_at) as …
```
=> fix(analytics): fix first_attempt filter value parsing for Payments

crates/analytics/src/opensearch.rs
Previously, there was no support to add filters in global-search, hence only free-text search queries were supported.
Because of this, the following query object was being mandatorily added.
```bash
{
"multi_match": {
"type": "phrase",
"query": "merchant_1726046328",
"lenient": true
}
},
``` 
Now, since adding filters is provided as a feature, it is no longer compulsary to have a free-text search query in addition to the filters applied.
So if no free-text search query is being applied, the query object will have the following:
```bash
{
"multi_match": {
"type": "phrase",
"query": "",
"lenient": true
}
},
```
This empty string in the query is resulting in wrong data being fetched when we hit opensearch/elasticsearch using the `/search` API.
Made changes to incorporate free-text search …
=> fix(opensearch): handle empty free-text query search in global search

crates/hyperswitch_connectors/src/connectors/zsl/transformers.rs
Currently, in case of underpayment we are mapping the payment status as `partially captured` with the changes of this PR. We will map the underpayment status as `succeeded` and provide information about the amount actually captured 
Webhooks cannot be tested in ZSL sandbox.
=> refactor(router): [ZSL] remove partially capture status

crates/router/src/utils/currency.rs
Refactors for currency conversion which invlolves:
-> Better error propagation
-> Redis lock realease, if data isn't fetched from api, so that the other subsequent calls donot fail.
Reqired for analytics
Scenarios tested:
1. No api_keys provided: call returned error and redis key was deleted after being set.
2. fallback api_key provided: call returned forex rates and lock was also released.
3. primary api_key provided: call returned forex rates and lock was also released.
=> refactor(currency_conversion): release redis lock if api call fails

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/admin.rs, crates/api_models/src/payments.rs, crates/diesel_models/src/business_profile.rs, crates/diesel_models/src/payment_intent.rs, crates/hyperswitch_domain_models/src/lib.rs, crates/router/src/consts.rs, crates/router/src/core/payment_link.rs, crates/router/src/core/payment_link/payment_link_initiate/payment_link_initiator.js, crates/router/src/core/payment_link/payment_link_initiate/secure_payment_link_initiator.js, crates/router/src/core/payments/transformers.rs, crates/router/src/types/transformers.rs
Add showCardFormByDefault config for payment links. 
https://docs.hyperswitch.io/explore-hyperswitch/merchant-controls/integration-guide/web/customization#show-card-form-by-default 
Functionality:
(By default showCardFormByDefault is true.)
When in PML card is not present + showCardFormByDefault=false, then card form is hidden from the UI. In all other cases card form is shown in UI.
<details>
<summary>1. Create a connector with only wallets in `payment_methods_enabled` (Expand to see details) </summary>
```
{
{
"payment_method_type": "paypal",
"installment_payment_enabled": false
},
{ …
```
=> feat(payments): [Payment links] add showCardFormByDefault config for payment links

crates/hyperswitch_domain_models/src/errors/api_error_response.rs, crates/router/src/compatibility/stripe/errors.rs, crates/router/src/core/user.rs, crates/router/src/core/user_role.rs, crates/router/src/db/kafka_store.rs, crates/router/src/db/user.rs, crates/router/src/services/authentication.rs, crates/router/src/services/authentication/cookies.rs, crates/router/src/services/authorization.rs, crates/router/src/services/email/types.rs, crates/router/src/types/domain/user.rs, crates/router/src/utils/user.rs
This PR does 3 things.
1. Throw 401 if cookies are not found in request or if JWT is not found in cookies.
2. Cache role info only if the ttl is greater than or equal to 0.
3. Use `UserEmail` type in DB functions.
Closes #6696.
Closes #6697.
Closes #6698.
todo!()
=> refactor(users): Use domain email type in user DB functions

crates/router/src/routes/app.rs
Reverts part of juspay/hyperswitch#6510
This PR also changed the dashboard related APIs, which doesn't come under the V2 changes that team is doing. As this is not a backwards compatible change, dashboard is breaking. Revert the dashboard API related changes.
=> fix(openapi): Revert Standardise API naming scheme for V2 Dashboard Changes

crates/analytics/src/opensearch.rs
The opensearch query should be built manually in the code, based on the request body.
There is a component called `filter_array` which comprises of the free-text search query, addition of case sensitive filters and also the time_range (if provided).
When all the three sub parts are empty (empty query string, no case-sensitive filters and missing time_range) in the request, the filter_array will not be created, and the logic for integrating the rest of the filters is affected.
Making minor fixes to the query builder to update the opensearch query even if all the above mentioned components are empty.
Give out correct results by building the opensearch query through the request body.
Should test the case when free-text query is empty, case-sensitive filters are not provided, and time-range …
=> fix(opensearch): fix empty filter array query addition in globalsearch query

crates/router/src/connector/adyen.rs, crates/router/src/connector/adyen/transformers.rs
Described in the linked #6719 
Ensures mandate details are stored for Adyen.
Since this is an intermittent scenario, webhooks flow was tested locally by disabling propagation of mandate details during PSync flow for Adyen.
`connector_mandate_details` is populate post receiving the webhooks
=> fix(connector): adyen - propagate connector mandate details in incoming webhooks

crates/router/src/connector/cybersource/transformers.rs
commerce indicator for discover card in applepay is changed since the payments are failing in production for cybersource
Note: This is hotifx against [#6690](https://github.com/juspay/hyperswitch/pull/6690)
- Create an MCA for Cybersource:
- Create a Payment with Applepay: 
```
{
"amount": 650, …
```
=> fix(connector): [Cybersource] change commerce indicator for discover cards in apple pay

crates/router/src/configs/defaults/payment_connector_required_fields.rs
ach, becs and bacs in payment method data is renamed to ach_bank_debit, becs_bank_debit, bacs_bank_debit
Tested it through Postman.
- Create Connector (Stripe):
```
{
"api_key": "some key here"
},
{
{
"installment_payment_enabled": true,
"payment_method_type": "affirm"
}
]
},
{
{
"maximum_amount": …
```
=> refactor(dynamic_fields): rename fields like ach, bacs and becs for bank debit payment method

crates/hyperswitch_connectors/src/connectors/nexixpay.rs, crates/hyperswitch_connectors/src/connectors/nexixpay/transformers.rs, crates/hyperswitch_connectors/src/utils.rs, crates/router/src/configs/defaults/payment_connector_required_fields.rs, cypress-tests/cypress/e2e/PaymentUtils/Nexixpay.js
Integrate mandates flow for card payments.
https://developer.nexi.it/en/funzionalita-/pagamenti-ricorrenti
**1) Multiuse mandates**
**2) Singleuse mandates**
**3) Test cases in the headless mode**
**Note:**  
1. Skipping no3ds test cases as it is not supported by nexixpay
2. Remaining few test cases in headless mode is failing due to inconsistency in test environment from the connector - cc: @likhinbopanna @Gnanasundari24 **
```
--header 'api-key: dev_VyjzlxA4qJnZUAalRRpB8MGDRzw6moojPrhbHThoGwxrZiyCvNnuIdVKoWvumalE' \
--data '{
"amount": 3545,
"customer_id": "tester799",
"setup_future_usage": "off_session"
}'
```
```
curl …
```
=> feat(connector): [Nexixpay] add mandates flow for cards

crates/api_models/Cargo.toml, crates/api_models/src/events/user.rs, crates/api_models/src/user.rs, crates/router/Cargo.toml
Wasm build is failing because of adding `actix-multipart` dependency in `api-models`.
Closes #6748.
Checked by building `wasm` locally. It worked.
No need to run any other tests as this is an internal change.
=> fix(api_models): Fix `wasm` build problems caused by `actix-multipart`

crates/diesel_models/src/payment_method.rs, crates/hyperswitch_domain_models/src/router_flow_types/webhooks.rs, crates/hyperswitch_interfaces/src/webhooks.rs, crates/router/src/connector/adyen.rs, crates/router/src/connector/adyen/transformers.rs, crates/router/src/core/webhooks/incoming.rs, crates/router/src/services/connector_integration_interface.rs
Described in #6719 
This PR introduces below changes
- `get_network_txn_id` fn in IncomingWebhook trait
- implement this new fn for Adyen for retrieving the network txn ID
- consume this fn in core flows for updating `network_transaction_id` in `payment_methods` table
Helps persist network transaction IDs for connectors in case it was not present in Authorize or Capture responses but instead sent in the webhook!
- Ensure Adyen is configured in HS, along with webhooks!
- Ensure `network_tx_reference` (field in Adyen) is not returned in Authorize or Capture response
- This field should be populated in DB once webhooks are received (provided this field was also returned)
`network_transaction_id` is populated after receiving webhooks
=> feat(webhooks): adyen - consume and update connector's network_transaction_id in payment_methods

crates/router/src/core/payments/operations/payment_confirm.rs, crates/router/src/core/payments/operations/payment_create.rs
Added a check to update payment_attempt.payment_method_data only when additional_payment_method is present; otherwise, the existing payment_method_data will remain unchanged.
**Request**
Create
```
--header 'api-key: dev_LjRfdy51O1zg0ToyQvxKdxvyIIlqkA8Wdle3E5IKgnmx6MOge4eTO0wwlFuMuJVk' \
--data-raw '{
"amount": 7940,
"amount_to_capture": 7940,
"customer_id": "StripeCustomer1",
"authentication_type": …
```
=> fix(core): card_network  details Missing in Customer Payment Methods List for External 3DS Authentication Payments

cypress-tests/cypress/e2e/PaymentUtils/Cybersource.js
There is a bug fix for cybersource where the billing address contains new line then the payments are getting failed. To address that in automation have added billling address with newlinw in confirm call and expecting succeeded in the response.
To enhance the testcase
=> ci(Cypress): Add testcase for newline in address

crates/common_enums/src/enums.rs, crates/router/src/services/authorization/info.rs, crates/router/src/services/authorization/permission_groups.rs
This PR introduces a new variant - `ReconOps` in the `PermissionGroup` enum for deserializing the custom recon related roles in the existing DB.
**Why?**
In `PermissionGroup` enum, `ReconOps` was recently renamed to `ReconOpsManage`. These values are serialized and stored in DB in case custom roles are created. For existing custom recon related roles, this would be stored as `recon_ops` in the DB. Application would expect this to be `recon_ops_manage` leading to deserialization failures.
This cannot be solved using serde's alias or strum's serialize attributes. **Why?** using strum's serialize attribute will expect the DB to always have `recon_ops` - application will always store this as `recon_ops_manage` in the new builds. Serde's alias attribute is not taken into account for DB enums …
=> refactor(enums): recon - include ReconOps variant in PermissionsGroup for backwards compatibility with data in DB

crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payment_methods/utils.rs
Previously the `mandate_details` were enough to identify the payment as mandate payment but now it is optional so a payment can be mandate even if there is no `mandate_details` but the payment's `setup_future_usage` is `off-session`.
This can be tested in the following way:
1. Connector create (Fiuu)
```
curl --location 'http://127.0.0.1:8080/account/merchant_1733312955/connectors' \
--data '{
"connector_name": "fiuu",
"api_key": ".....",
"key1": "......",
"api_secret": "......"
},
{ …
```
=> refactor(constraint_graph): add setup_future_usage for mandate check in payments

cypress-tests/cypress/e2e/PaymentTest/00004-NoThreeDSAutoCapture.cy.js, cypress-tests/cypress/e2e/PaymentUtils/Adyen.js, cypress-tests/cypress/e2e/PaymentUtils/BankOfAmerica.js, cypress-tests/cypress/e2e/PaymentUtils/Bluesnap.js, cypress-tests/cypress/e2e/PaymentUtils/Checkout.js, cypress-tests/cypress/e2e/PaymentUtils/Commons.js, cypress-tests/cypress/e2e/PaymentUtils/Cybersource.js, cypress-tests/cypress/e2e/PaymentUtils/Nmi.js, cypress-tests/cypress/e2e/PaymentUtils/Noon.js, cypress-tests/cypress/e2e/PaymentUtils/Paypal.js, cypress-tests/cypress/e2e/PaymentUtils/Stripe.js, cypress-tests/cypress/e2e/PaymentUtils/Trustpay.js, cypress-tests/cypress/support/commands.js
Add Shipping Cost test case for cypress automation
Currently Test case was not present 
Cypress
=> ci(cypress): Add shipping cost test case

crates/router/src/core/payment_link/locale.js
Changed locale case to snakecase for  `const locale`  object for payment_link. Currently the object has keys in snake case but since Accept-Language is not passed in snakecase, payment_link is not able to render the translated data but shows data in english (fallback language).
(Need to run both hyperswitch-web and hyperswitch locally to test)
<details>
<summary>1. Update `allowed_domains` in business profile (Expand to see details)</summary>
``` 
curl --location 'http://localhost:8080/account/merchant_1733317126/business_profile/pro_I5CYJ8tVS6OHA1GMcXaW' \
--data '{
"*"
],
"enabled_saved_payment_method": true,
"hide_card_nickname_field" : true
}
}'
```
</details> …
=> feat(payments): [Payment links] Add locale case fix

crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payment_methods/utils.rs
This will make the `mandate_payments` acceptable even when `setup_future_usage` is null in payments.
=> refactor(constraint_graph): revert handle for cases where setup_future_usage is null in payments is null in payments

crates/router/src/services/kafka/dispute_event.rs, crates/router/src/services/kafka/payment_attempt_event.rs, crates/router/src/services/kafka/payment_intent_event.rs, crates/router/src/services/kafka/refund_event.rs
Adding nanosecond level precision to kafka messages for sessionizer
So due to millisecond level precision earlier , sessionizer was getting updates in same millisecond due to which updates we not getting picked up
Via Kafka UI
=> refactor(kafka_message): NanoSecond precision for consolidated logs

cypress-tests/cypress/e2e/PaymentTest/00022-Variations.cy.js, cypress-tests/cypress/e2e/PaymentUtils/Adyen.js, cypress-tests/cypress/e2e/PaymentUtils/Commons.js, cypress-tests/cypress/e2e/PaymentUtils/Stripe.js
Added the testcases for unified error code and error message for stripe and adyen connector. And added failure payments testcases.
Stripe
Adyen
=> ci(cypress): Add testcases for unified error code and message

crates/hyperswitch_connectors/src/connectors/airwallex/transformers.rs
Add referrer data in Airwallex's Create Payment Intent request in order to whitelist Hyperswitch for processing raw card details.
https://github.com/juspay/hyperswitch/issues/6807
Testing can be done by verifying payment logs for Airwallex payments
Payments Request:
```
--header 'api-key: dev_cEY8PgIkrpv1Y8pe0oVj6izFmGmxSlhrtV78ead9czZGWd5vp4h2GK8iLtenibs7' \
--data '{
"amount": 8059,
"card": {
"card_number": "4035 5010 0000 0008",
"card_exp_year": …
```
=> feat(connector): [AIRWALLEX] Add refferer data to whitelist hyperswitch

migrations/2024-12-02-110129_update-user-role-entity-type/down.sql, migrations/2024-12-02-110129_update-user-role-entity-type/up.sql, migrations/2024-12-13-080558_entity-id-backfill-for-user-roles/down.sql, migrations/2024-12-13-080558_entity-id-backfill-for-user-roles/up.sql
This PR ensures that the entity_id is backfilled in the user_roles table, preventing issues for V1 users when switching organizations and logging in.
Through dashboard 
- login to v1 user 
- invite the same user to another org 
- Switch organization
=> fix(user_roles): migrations for backfilling user_roles entity_id

crates/router/src/core/payments/helpers.rs
- Handle default case where card network is null because in case of co-badged cards, we will always get the card network from frontend
- Create an MCA (Checkout)
- Create a payment with co-badged card
```
{
"amount": 1043,
"card": {
"card_number": "4010061700000021",
"card_exp_year": "99",
"card_cvc": …
```
=> fix(router): handle default case for card_network for co-badged cards

crates/hyperswitch_connectors/src/connectors/volt/transformers.rs
- 5xx error for Volt Payment Sync, for PaymentStatus. We received a new status `UNKNOWN`. 
- Adding `UNKNOWN` status to Psync Payment Status and mapping it with previous status to avoid deserialization error.
- Create a Payment using Volt connector
```
--header 'api-key: ___' \
--data-raw '{ …
```
=> fix(connector): 5xx error for Volt Payment Sync

crates/router/src/connector/adyen/transformers.rs
This PR fixes MIT payments failing especially during NTID flow.
We previously used to get below error message during MIT Confirm call:
```log
"The provided Expiry Date is not valid.: Expiry year should be a 4 digit number greater than 2000: 30"
```
closes https://github.com/juspay/hyperswitch/issues/6850
xecuted below commands:
```sh
git cherry-pick -n ..cypress-delete-pm
just migrate
cargo r
```
ran the cypress NTID tests for Adyen:
full test (based on #6735) -- no regressions found with adyen:
=> fix(connector): add expiry year conversion for adyen mit transactions

crates/diesel_models/src/payment_method.rs, crates/router/src/core/payment_methods/cards.rs, crates/router/src/core/payments/tokenization.rs
In customer payment method list api, card scheme and card network are showing different value for co-branded card it they are saved with both the network, to fix this issue, both these fields are now fetching the data from the card locker
Note: This PR is hotfix against [#6849](https://github.com/juspay/hyperswitch/pull/6849)
Tested through Postam:
- Create a MCA(Checkout):
- Create a payment with co-branded card with network at Visa:
```
{
"amount": 1043,
"return_url": …
```
=> fix(payment_methods): card_network and card_scheme should be consistent

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/admin.rs, crates/api_models/src/payments.rs, crates/diesel_models/src/business_profile.rs, crates/diesel_models/src/payment_intent.rs, crates/hyperswitch_domain_models/src/lib.rs, crates/router/src/core/payment_link.rs, crates/router/src/core/payment_link/payment_link_initiate/payment_link.js, crates/router/src/core/payments/transformers.rs, crates/router/src/types/transformers.rs
Added config for changing text of confirm button for payment links
<details>
<summary>1. Update `allowed_domains` in business profile (Expand to see details)</summary>
``` 
curl --location --request POST 'http://localhost:8080/account/merchant_1734440294/business_profile/pro_DD9djS7uH6B6uB9A8Nl4' \
--data-raw '{
"*"
],
"enabled_saved_payment_method": true,
"hide_card_nickname_field": true
}
}'
```
</details>
<details>
<summary>2. Create a payment link with `payment_button_text` (Expand to see details)</summary>
``` …
```
=> feat(payments): [Payment links] Add config for changing button text for payment links

crates/router/src/core/user/theme.rs, crates/router/src/core/user_role/role.rs, crates/router/src/db.rs, crates/router/src/services/authorization.rs, crates/router/src/services/authorization/roles.rs, crates/router/src/utils/user/theme.rs, crates/router/src/utils/user_role.rs
Refactor:
- move roles to global schema
- remove themes from global schema
Closes [#6861](https://github.com/juspay/hyperswitch/issues/6861)
Refactoring changes, currently in config global schema points to public, so no change in behaviour.
Changes will be reflected after we turn on feature flag for multi-tenancy and update the configs. Global interface will point to global (shared resources) schema.
When interacting with roles and themes storeage fucntions/queries we are getting expected response as we were getting before.
```
curl --location 'http://localhost:8080/user/role' \
--header 'Cookie: Cookier' \
--data '{
"role_name": "custom_role_1",
"groups": ["users_view"],
"role_scope": "merchant"
}'
``` …
=> refactor(users): move roles schema to global interface

crates/router/src/connector/paypal/transformers.rs
PayPal added some extra parameters in the response, which caused the bank redirects to fail.
=> fix(connector): Paypal BankRedirects (Ideal/EPS) 

api-reference-v2/openapi_spec.json, crates/api_models/src/events/customer.rs, crates/api_models/src/payments.rs, crates/router/src/core/customers.rs, crates/router/src/core/payments/transformers.rs
This PR includes minor fixes suggested in my previous PR #6836. This PR includes the following changes:
- Import `CustomerUpdateRequestInternal` instead of fully qualifying it.
- Renames the `fetch_domain_model_and_update_and_generate_delete_customer_response()` method to `redact_customer_details_and_generate_response()`.
- Includes the `customer_id` field in `PaymentsConfirmIntentResponse` and `PaymentsRetrieveResponse` API models.
This PR adds the `customer_id` field in the `PaymentsConfirmIntentResponse` and `PaymentsRetrieveResponse` API models. This does not affect any API contract for v1 APIs.
Addresses minor fixes in customers v2 APIs.
For the `customer_id` field in being included in `PaymentsConfirmIntentResponse` and `PaymentsRetrieveResponse` API models, I tried out the payment …
=> refactor(customers_v2): include minor fixes for customer v2 flows

crates/router/src/connector/stripe/transformers.rs, crates/router/src/core/payments/transformers.rs
- Revert this [PR](https://github.com/juspay/hyperswitch/pull/6855)
- Pass `setup_future_usage = None` for ConnectorMandateId and NetworkMandateId.
1. Create Merchant
2. Create API KEY
3. Create Stripe connector
```
curl --location 'http://localhost:8080/account/postman_merchant_GHAction_1734681965/connectors' \
--data '{
"profile_id": "pro_iprJnfcIANK2ws8xnWhI",
"api_key": "__"
},
{
{
"maximum_amount": …
```
=> fix(connector): [STRIPE] fix stripe mandate

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/payments.rs, crates/common_utils/src/types.rs, crates/hyperswitch_connectors/src/connectors/airwallex/transformers.rs, crates/hyperswitch_connectors/src/utils.rs, crates/hyperswitch_domain_models/src/router_request_types.rs, crates/router/src/connector/trustpay/transformers.rs, crates/router/src/routes/payments/helpers.rs, crates/router/tests/connectors/trustpay.rs, crates/router/tests/connectors/utils.rs
- add a extra object `device_data` in payment request for both 3ds and no 3ds Cards for connector Airwallex
1. Create Merchant Account
2. Create API KEY
3. Create Airwallex connector 
```
curl --location 'http://localhost:8080/account/merchant_1734509905/connectors' \
--data '{
"connector_name": "airwallex",
"api_key": "_",
"key1": "_"
},
{
{
"AmericanExpress",
"Discover",
"Interac",
"JCB",
"Mastercard",
"Visa", …
```
=> refactor(connector): [Airwallex] add device_data in payment request

crates/common_utils/src/consts.rs, crates/external_services/src/grpc_client.rs, crates/external_services/src/grpc_client/dynamic_routing/elimination_rate_client.rs, crates/external_services/src/grpc_client/dynamic_routing/success_rate_client.rs, crates/router/src/core/payments/routing.rs, crates/router/src/core/routing.rs, crates/router/src/core/routing/helpers.rs, crates/router/src/routes/app.rs
This PR adds support for sending the `x-tenant-id` and `x-request-id` in the grpc headers
1. Create merchant_account, api_key and mca (any connector)
2. Toggle dynamic routing
```
curl --location --request POST 'http://localhost:8080/account/merchant_1734609410/business_profile/pro_gPTjn9jLm0CxI8ZD1omL/dynamic_routing/success_based/toggle?enable=metrics' \
--header 'api-key: dev_K70Wr6zqJLbPECg8eEXrnZ43TW41JNUuXYHzRB50geiG0lViLExjxNUld6sgdNd0' \
--data ''
```
3. Create a payment
```
--header 'api-key: dev_K70Wr6zqJLbPECg8eEXrnZ43TW41JNUuXYHzRB50geiG0lViLExjxNUld6sgdNd0' \ …
```
=> refactor(grpc): send `x-tenant-id` and `x-request-id` in grpc headers

crates/router/src/configs/defaults/payment_connector_required_fields.rs
Fix required fileds for wallet mandate payments for cybersource and bank of america.
create payment with cybersource
request : 
```
{
"amount":1001,
"amount_to_capture": 1001,
"card": {
"card_exp_year": "2030",
"card_cvc": …
```
=> fix(connector): [Cybersource] fix the required fields for wallet mandate payments

crates/api_models/src/relay.rs, crates/diesel_models/src/query/relay.rs, crates/diesel_models/src/relay.rs, crates/router/src/core/relay.rs, crates/router/src/db/relay.rs, crates/router/src/routes/app.rs, crates/router/src/routes/lock_utils.rs, crates/router/src/routes/relay.rs, crates/router_env/src/logger/types.rs
/relay is a api that will be used to just forward the request sent by merchant without performing any application logic on it. This is particular to support the refunds for the payments that was directly performed with the connector (example stripe) with out hyperswitch involved during the payment flow. 
This PR introduces changes to add a retrieve API for relay refunds.
The retrieve API will:
1. Return the relay status from our database when a retrieve call is made.
2. If force_sync = true is passed and the relay status is not in a terminal state in our system, the API will call the connector to fetch the latest status.
Flow
1. Merchant performs payment directly with processor and stores the payment reference id associated with it.
2. Merchant tiggers the refund through hyperswitch using …
=> feat(router): add /retrieve api for relay

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml
remove extra space from wasm for payment_method_type of JPMorgan
No test required as only wasm changes are done in this PR
=> fix(wasm): remove extra space from wasm for payment_method_type of JPMorgan

crates/router/src/cors.rs
This PR exposes all headers set by the application in the `access-control-expose-headers` header value. This should thus allow our headers like `x-request-id` to be accessed by the browser.
This should allow headers set by our application like the `x-request-id` header to be accessed by the browser.
This was fixed once before in #1673, but I suspect the behavior changed again when #3646 was merged.
Locally.
```shell
$ curl -i http://localhost:8080/health
[...]
access-control-expose-headers: x-request-id, via, strict-transport-security
[...]
```
The `access-control-expose-headers` header is included in the response headers, and `x-request-id` is included in the header value.
=> fix(cors): expose all headers set by application in `access-control-expose-headers` header value

crates/connector_configs/src/connector.rs, crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml
remove chasenet from jpmorgan wasm as ChaseNet doesn’t exist in PMT
No test required as only wasm changes are done in this PR
=> fix(wasm): remove chasenet from jpmorgan wasm as ChaseNet doesn’t exist in PMT

config/docker_compose.toml
Users not able to login using local setup. 
This PR removes force cookie option for docker setup.
Closes [#6931](https://github.com/juspay/hyperswitch/issues/6931)
Tested locally with updated docker configs, and re run the container.
=> fix(users): remove force cookie for docker setup

api-reference/openapi_spec.json, crates/openapi/src/routes/relay.rs
Update open-api spec of /relay request to make the data untagged enum.
=> docs(openapi): update /relay request example

crates/router/src/core/payments/operations/payment_response.rs, crates/router/src/core/payments/tokenization.rs
Allow update of `connector_mandate_details` for card in case of metadata changes(in case of expiry changes). First the  value is set as inactive and if a successful payment has been made then set it back to active
- Nothreeds
> - Create a MA and a MCA
> - Make a off_Session save card payment
> - Make a off_Session payment again with the same card just and changes expiry 
> - After a successful payment the Connector Mandate Details would be overriden
- Follow the same step for 3threeds
> - Create a MA and a MCA
> - Make a off_Session save card payment
> - Make a off_Session payment again with the same card just and changed expiry 
> -Before a successful redirection ( the connector mandate is inactive)
> - After a successful redirection ( the connector mandate is active)
=> refactor(payment_methods): update `connector_mandate_details` for card metadata changes

migrations/2024-12-18-124527_add_new_value_in_success_based_routing_conclusive_state/down.sql, migrations/2024-12-18-124527_add_new_value_in_success_based_routing_conclusive_state/up.sql
This will add a value `non_deterministic` in `SuccessBasedRoutingConclusiveState` type.
1. Toggle Success Based routing for the merchant.
```
curl --location --request POST 'http://localhost:8080/account/xxxxxx/business_profile/xxxxxxx/dynamic_routing/success_based/toggle?enable=metrics' \
--header 'api-key: xxxxxxx'
```
2. Create a payment that goes in processing state or any non terminal state.
3. Check the `dynamic_routing_stats` table for the `payment_id` for the `non_determinisctic`.
=> refactor(dynamic_routing): add non_deterministic value in SuccessBasedRoutingConclusiveState type

crates/router/src/core/payments/routing.rs, crates/router/src/core/routing.rs, crates/router/src/core/routing/helpers.rs
Since hyperswitch started sending tenant-id in headers of dynamic routing grpc requests, we can safely remove the tenant-id prefixed in `id` field
1. Create merchant_account, api_key and mca (any connector)
2. Toggle dynamic routing
```
curl --location --request POST 'http://localhost:8080/account/merchant_1734609410/business_profile/pro_gPTjn9jLm0CxI8ZD1omL/dynamic_routing/success_based/toggle?enable=metrics' \
--header 'api-key: dev_K70Wr6zqJLbPECg8eEXrnZ43TW41JNUuXYHzRB50geiG0lViLExjxNUld6sgdNd0' \
--data ''
```
3. Create a payment
``` …
```
=> refactor(dynamic_routing): remove `tenant-id` prefixed in `id` field of dynamic routing grpc requests

crates/redis_interface/src/commands.rs, crates/router/src/core/admin.rs, crates/router/src/core/cache.rs, crates/router/src/core/routing.rs, crates/router/src/core/routing/helpers.rs, crates/router/src/db/configs.rs, crates/router/src/db/merchant_account.rs, crates/storage_impl/src/redis/cache.rs, crates/storage_impl/src/redis/pub_sub.rs
This PR fixes an inconsistency in the redis `key_prefix` that was used when invalidating the cache entries which affected all the cache types (configs, accounts, routing, etc).
The `delete_key` redis call during cache invalidation was using `global` as the `key_prefix` (key like `global:test_key` was being deleted in redis) while each of the tenants were reading using their corresponding `key_prefix` (key like `public:test_key` was being set/read in redis).
PUT/GET/UPDATE/DELETE on configs table as configs has cache usage
1. PUT
```
curl --location 'http://localhost:8080/configs/' \
--header 'x-tenant-id: public' \
--data '{
"key": "test_key_1",
"value": "test_val_1"
}'
``` …
=> fix(cache): address in-memory cache invalidation using global tenant as `key_prefix`

cypress-tests/cypress/e2e/PaymentUtils/Adyen.js, cypress-tests/cypress/e2e/PaymentUtils/Commons.js, cypress-tests/cypress/e2e/PaymentUtils/Iatapay.js
- Adyen sofort was failing in cypress automation as sofort payment method is deprecated from adyen, hence handled the error message 
- Fixed Variation case for iatapay
Adyen cypress tests were failing
- Adyen
- Iatapay
=> ci(cypress): fix adyen sofort in cypress

config/config.example.toml, config/deployments/env_specific.toml, config/development.toml, config/docker_compose.toml, crates/common_utils/src/consts.rs, crates/common_utils/src/id_type/tenant.rs, crates/common_utils/src/keymanager.rs, crates/common_utils/src/types/keymanager.rs, crates/router/src/configs/defaults.rs, crates/router/src/configs/settings.rs, crates/router/src/types/domain/types.rs, loadtest/config/development.toml
Adds tenant-id for every requests to keymanager
Added tenant id header for the keymanager service to classify key ids based on tenants.
- Create Merchant Account with x-tenant-id as `public`
```bash
--header 'x-feature: integ-custom' \
--header 'x-tenant-id: public' \
--data-raw '{
"merchant_id": "1735815159", …
```
=> chore(keymanager): add tenant-id to keymanager requests

crates/router/src/core/payment_methods/cards.rs
https://github.com/juspay/hyperswitch/pull/3953
We were not considering the status of payment method in above filtering logic
1. Create merchant_account, api_key, mca (with any wallet)
2. Create a payment with wallet as payment method with authentication_type as three_ds. Retain the status of payment as processing
```
--header 'api-key: dev_qVglrYUpCaoLCvnixZd3hX0ls7du5ZmaVMhZJNGt8ezEN4Axn8oU22i2gRz0OTqx' \
--data '{
},
"customer_id": "cus_kWEMsP0NufHyhHsBB1Ol",
"profile_id": "pro_mjcaEelE0mjdp8ODpfkc", …
```
=> fix: consider status of payment method before filtering wallets in list pm

crates/router/src/configs/defaults/payment_connector_required_fields.rs
This PR adds below dynamic required fields for processing Worldpay payments -
- address.line1
- address.city
- address.country
The txn will fail in case a few details are missing from address while processing a payment. To fix this, required fields are updated in `RequiredFields` struct which is requested by SDK at runtime for dynamically rendering the inputs for the required fields.
Tested by rendering a payment link locally.
=> chore(dynamic-fields): [Worldpay] update dynamic fields for payments

cypress-tests/cypress/e2e/RoutingTest/00000-PriorityRouting.cy.js, cypress-tests/cypress/e2e/RoutingTest/00001-VolumeBasedRouting.cy.js, cypress-tests/cypress/e2e/RoutingTest/00002-RuleBasedRouting.cy.js, cypress-tests/cypress/e2e/RoutingTest/00003-Retries.cy.js, cypress-tests/cypress/support/commands.js
this pr fixes the issue where cookies are not being set when hitting user apis.
- we need to set cookies. but cypress does not directly support that 
- `cy.setCookie()` method does not persist outside of the `it()` block
- in order to make it persist, we need to set session using `cy.session()` method in the `beforeEach()` hook
closes #6977
this pr, of course, does not fix the hooks (caching) issue. 
NA
every failure here is related to assertion and `globalState` where `connectorId` and `mcaId` not getting updated. This can be picked up a separate PR since the fix done in this PR is `P0`
=> fix(cypress): backup and restore sessions when using user apis

crates/hyperswitch_connectors/src/connectors/novalnet.rs, crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs, crates/hyperswitch_connectors/src/utils.rs, crates/hyperswitch_domain_models/src/router_request_types.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/core/relay/utils.rs, crates/router/src/core/utils.rs, cypress-tests/cypress/e2e/PaymentUtils/Novalnet.js
1. Added zero auth mandates for Novalnet
2. Made changes so that `create_webhook_url` fn can accept `merchant_connector_account_id` instead of `connector_name`
1. Zero auth mandate for novalnet
Note:
Skipping no3ds test cases as it is not supported by novalnet  cc: [@Likhin Bopanna](https://github.com/likhinbopanna)
Tested manually 
https://docs.google.com/document/d/1i4SSX837Dh9ipfOz24bDwJF8osR_UPmfPLWUbLP3bh0/edit?usp=sharing
2. Webhooks 
Webhooks working as expected for /payments. Tested locally.
=> feat(connector): [Novalnet] Add zero auth mandate

cypress-tests/README.md, cypress-tests/cypress/support/e2e.js
This PR updates Cypress documentation to deal with recent file structure change.
- `cypress-tests` folder structure to reduce confusion and chaos in within `e2e` directory
- previous:
```sh
.
└── cypress
├── e2e
│   ├── PaymentMethodListTest
│   ├── PaymentMethodListUtils
│   ├── PaymentTest
│   ├── PaymentUtils
│   ├── PayoutTest
│   ├── PayoutUtils
│   ├── RoutingTest
│   └── RoutingUtils
├── fixtures
├── support
└── utils
```
- present:
```sh
.
└── cypress
├── e2e
│   ├── configs
│   │   ├── Payment
│   │   ├── PaymentMethodList
│   │   ├── Payout
│   │   └── Routing
│   └── spec
│       ├── Misc
│       ├── Payment
│       ├── PaymentMethodList
│       ├── Payout
│       └── Routing
├── fixtures
├── support
└── utils
```
closes #6955
Just trying to be up-to-date with the latest …
=> docs(cypress): update file structure

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/common_enums/src/connector_enums.rs, crates/connector_configs/src/connector.rs, crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml, crates/hyperswitch_connectors/src/connectors/xendit.rs, crates/hyperswitch_connectors/src/connectors/xendit/transformers.rs, crates/hyperswitch_connectors/src/default_implementations.rs, crates/hyperswitch_connectors/src/utils.rs, crates/router/src/configs/defaults/payment_connector_required_fields.rs, crates/router/src/core/admin.rs, crates/router/src/core/payments/connector_integration_v2_impls.rs, crates/router/src/core/payments/flows.rs, crates/router/src/types/api.rs, crates/router/src/types/transformers.rs, cypress-tests/cypress/e2e/PaymentTest/00007-VoidPayment.cy.js, cypress-tests/cypress/e2e/PaymentUtils/Utils.js, cypress-tests/cypress/e2e/PaymentUtils/Xendit.js, cypress-tests/cypress/support/redirectionHandler.js
Added Xendit Cards & Mandates Flow 
https://github.com/juspay/hyperswitch-cloud/issues/7964
**Three-DS ** 
```
--header 'api-key: dev_tq4ULEe1sBlAVdBP2vInkkBCLMBBPimfl5cfsGZKq19Apf2XxUxxJYfYQ0iDTvkb' \
--data-raw '{
"amount": 651200,
"currency": "IDR",
"customer_id": "First_Customer",
"card": {
"card_number": "4000000000001091",
"card_exp_month": "12",
"card_exp_year": "27",
"card_holder_name": "joseph …
```
=> feat(connector): [Xendit] ADD Cards & Mandates Flow 

crates/router/src/connector/netcetera/netcetera_types.rs
Missing BrowserInformation.AcceptLanguage in Authentication request for Netcetera
- add accept-language in browser_information for netcetera authentication request
External 3DS authentication request through Netcetera
CURL
```
curl --location '{{baseURL}}/payments/{{PAYMENT_ID}}/3ds/authentication' \
--header 'api-key: {{PUBLISHABLE_KEY}}' \
--data '{
"client_secret": "pay_YgaqwRsJ2D609GavM4R7_secret_dyidRAo6cvSM5Wfbc4Se",
"device_channel": "BRW",
"threeds_method_comp_ind": "Y"
}'
```
Response
```
{
"trans_status": "Y",
"acs_url": null,
"challenge_request": null,
"acs_reference_number": null,
"acs_trans_id": null,
"three_dsserver_trans_id": "0fa5cf1b-dd17-4314-8fb0-6ef51367a32b", …
```
=> fix(connector): [NETCETERA] add accept-language in browser_information for netcetera authentication request

crates/router/src/core/payment_link/payment_link_initiate/payment_link_initiator.js, crates/router/src/core/payment_link/payment_link_initiate/secure_payment_link_initiator.js
This PR enables a flag which enables HyperSwitch SDK to handle removal of `beforeunload` events based on it's consumption by the integrating merchants.
This PR enables handling of removal of `beforeunload` events once checkout form is submitted by the user. Helps keep a clean user experience.
Tested locally using payment links.
=> refactor(payment-link): use shouldRemoveBeforeUnloadEvents flag for handling removal of beforeunload events through SDK

crates/hyperswitch_domain_models/src/router_request_types.rs, crates/router/src/core/payments/transformers.rs
Refactored customer email and browser information in router data
This refactoring provides data to the connector integrations, so that it can be used in connector calls. 
- Confirm Intent API Call for trustpay connector.
```
curl --location 'http://localhost:8080/v2/payments/12345_pay_01945e865f697553bbf0eb847611cfcd/confirm-intent' \
--header 'x-client-secret: 1secret-client-secret' \
--header 'x-profile-id: pro_id' \
--header 'api-key: api-key' \
--data '{
"card": {
"card_holder_name": "John Doe",
"card_cvc": "100"
}
},
"payment_method_type": "card",
"payment_method_subtype": "credit",
"user_agent": "Mozilla/5.0 (Windows …
```
=> Refactor: Customer email and browser Information

crates/router/src/connector/adyen.rs
To consume transaction id for some error cases , where currently its not consumed for Adyen, Worldpay. This PR addresses this issue.
Could not manually trigger error
=> feat(connector): [ADYEN ] Consume transaction id for PaymentsPreProcessing error

cypress-tests/cypress/support/e2e.js, cypress-tests/cypress/support/redirectionHandler.js, cypress-tests/package-lock.json, cypress-tests/package.json
the return url i.e., `hyperswitch.io` is throwing uncaught exceptions. the issue has been escalated to the team managing the website. and for now, we're ignoring any uncaught exceptions thrown by it.
additionally, have bumped the package versions except for cypress since it is a major upgrade and breaks redirection tests left right and center.
this pr also removes redundant code from redirection handler
closes https://github.com/juspay/hyperswitch/issues/7093
ci
ci checks should pass, but works in local:
payouts: wise
payments: adyen
payments: bankofamerica
payments: bluesnap
payments: cybersource
payments: nmi
payments: paypal
payments: stripe
payments: trustpay
payment method list
routing
=> fix(cypress): uncaught exceptions thrown by `hyperswitch.io`

config/deployments/production.toml
adding `stripe` in connector list for network transaction id.
=> chore: add stripe to network transaction id support

.github/workflows/CI-pr.yml, .github/workflows/CI-push.yml, .github/workflows/connector-sanity-tests.yml, .github/workflows/connector-ui-sanity-tests.yml, .github/workflows/postman-collection-runner.yml
changed cargo clippy command in workflow files to use default number of jobs instead of 2.
Github CI checks has passed.
=> chore: run clippy with default number of jobs in github workflows

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/payments.rs, crates/openapi/src/openapi.rs, crates/openapi/src/openapi_v2.rs, crates/router/src/connector/netcetera/netcetera_types.rs
add `sdk-type` and `default-sdk-type` in netcetera authentication request
add `sdk-type` in SDK Information of PaymentsExternalAuthenticationRequest
1. Sanity External Authentication Request through Mobile SDK
CURL
```
curl --location 'localhost:8080/payments/pay_OxGBWwRs9qH0nJP1CI99/3ds/authentication' \
--header 'api-key: pk_dev_74ab7c8aac7c49d793f9c980c544a09f' \
--data '{
"client_secret": "pay_OxGBWwRs9qH0nJP1CI99_secret_Vw1ItPPePtpz32zI2V9d",
"device_channel": "APP",
"threeds_method_comp_ind": "Y",
"sdk_information": {
"sdk_app_id": "92deb809-a452-47af-ac3b-301978a9e9e0",
"sdk_enc_data": "eyJraWQiOiIzYzVlZDMxOTBhOWFlNGI2OTI1NjZiYmZkZTc0ODNiZTI4MDAyMzg4IiwiZW5jIjoiQTEyOEdDTSIsImFsZyI6IlJTQ …
```
=> fix(connector): [NETCETERA] add `sdk-type` and `default-sdk-type` in netcetera authentication request

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/payment_methods.rs, crates/api_models/src/payments.rs, crates/api_models/src/payments/additional_info.rs, crates/hyperswitch_domain_models/src/payment_method_data.rs, crates/router/src/core/fraud_check/operation/fraud_check_pre.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_create.rs, crates/router/src/types/fraud_check.rs
This pr contains the changes to populate `payment_method_data` in the samsung pay payment response. As part of this card_type is made a optional for wallet  payment_method_data as samsung pay does not send credit or debit in the samsung pay token.
Having `payment_method_data` for Samsung Pay would be helpful in identifying the customer's card, as it contains the last four digits during a wallet payment.
-> Create a connector with samsung pay enabled
-> Make a samsung pay payment, payment_method_data would be populated in the resposne.
```
--header 'api-key: <api-key>' \
--data-raw '{
"amount": 1, …
```
=> fix(samsung_pay): populate `payment_method_data` in the payment response

crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs, crates/hyperswitch_connectors/src/utils.rs, crates/router/src/configs/defaults/payment_connector_required_fields.rs
For Novalnet  Connector, for Applepay, Googlepay, Paypal the following fields are not required
```
payment_method_data.billing.address.first_name
payment_method_data.billing.address.last_name
```
This PR removes these required fields for Applepay, Googlepay, Paypal for Novalnet
Applepay can't be tested locally
Tested Googlepay and Paypal locally without passing 
```
payment_method_data.billing.address.first_name
payment_method_data.billing.address.last_name
```
```
--header 'api-key: dev_tAW8Ub52irOZ4OGMRHftVI2amltitI5Y8SvnWg9rAgz6tkKEVwbrQsVEgHFrPDOM' \
--data-raw '{
"amount": 100,
"capture_method": …
```
=> fix(connector): [novalnet] Remove first name, last name as required fields for Applepay, Googlepay, Paypal 

Cargo.lock, crates/router/Cargo.toml
Update openssl dependency from `version = "0.10.66"` to `version = "0.10.70"`
This pr also updates openssl-sys transitive dependency from `version = "0.9.103"` to `version = "0.9.105"`
openssl patch version `0.10.70` release
We've had to update the `openssl` crate due to the advisory GHSA-rpmj-rpgj-qmpm that was recently published against the crate.
Verified by code compilation
=> build(deps): bump `openssl` from 0.10.66 to 0.10.70

crates/router/src/connector/authorizedotnet/transformers.rs
fix deserialization error for Paypal while canceling payment for Authorizedotnet
1. connector create for authorizedot net
```
curl --location 'http://localhost:8080/account/postman_merchant_GHAction_39c48f8b-cc20-4438-aeb0-c55318bdaf57/connectors' \
--data '{
"connector_name": "authorizedotnet",
"api_key": "___",
"key1": "_____"
},
{
{
"Visa",
"Mastercard"
], …
```
=> fix(connector): [Authorizedotnet] fix deserialization error for Paypal while canceling payment 

crates/router/src/consts.rs, crates/router/src/core/refunds.rs
…ated errors
Some connectors  like Novalnet do not have a separate list of refund errors, they only have a single list for all the possible connector error codes.
In such cases, the error codes and messages are stored under "Authorize" flow in GSM table.
During refund related error when we fetch GSM in code, we will have to fetch the GSM using Authorize flow in case GSM is not found using "refund_flow".
[ Enhancement for [this](https://github.com/juspay/hyperswitch/pull/6933 ) PR ]
1) Make a  card payment for 1000 MYR, and capture.
2) Update DB to alter the captured amount to a greater amount say 3000 MYR.
3) Make refunds call with 3000 MYR, connector will throw error since the real captured amount is lesser than this new amount.
**cURL**
`curl --location --request POST …
=> feat(core): Add Authorize flow as fallback flow while fetching GSM for refund errors

crates/router/src/core/customers.rs
Return redacted customer response instead of error when querying deleted customers.
Upon merging this PR, the API will return deleted Customer with redacted values instead of error.
https://github.com/juspay/hyperswitch/issues/7126 
- Create Customer API Call
```
curl --location 'http://localhost:8080/customers' \
--data-raw '{
"description": "First customer",
"address": {
},
"metadata": { …
```
=> refactor(customer): return redacted customer instead of error

crates/hyperswitch_connectors/src/connectors/fiuu.rs, crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
Hotfix for https://github.com/juspay/hyperswitch/pull/7211
Helps fix Fiuu connector specifically for DuitNow.
DuitNow cannot be tested. Updated based on API documentation.
=> fix(connector): [fiuu] update PSync and webhooks response

crates/hyperswitch_connectors/src/connectors/fiuu.rs
(cherry picked from commit c044ffff0c47ee5d3ef5f905c3f590fae4ac9a24)
Hotfix for https://github.com/juspay/hyperswitch/pull/7189
This helps in debugging PSync deserialization errors for Fiuu for DuitNow payment method.
As mentioned in https://github.com/juspay/hyperswitch/pull/7189
=> chore(connector): [Fiuu] log keys in the PSync response

api-reference/openapi_spec.json, crates/api_models/src/payments.rs, crates/common_enums/src/enums.rs, crates/diesel_models/src/query/payment_attempt.rs, crates/hyperswitch_domain_models/src/payments/payment_attempt.rs, crates/hyperswitch_domain_models/src/payments/payment_intent.rs, crates/openapi/src/openapi.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/db/kafka_store.rs, crates/router/src/services/kafka/payment_attempt.rs, crates/router/src/services/kafka/payment_attempt_event.rs, crates/router/tests/payments.rs, crates/router/tests/payments2.rs, crates/storage_impl/src/mock_db/payment_attempt.rs, crates/storage_impl/src/payments/payment_attempt.rs, crates/storage_impl/src/payments/payment_intent.rs
add card_discovery filter to payment list and payments Response
Enable `Click To Pay` and try to do a payment, after that do list payment list with constraint `card_discovery`
to enable `Click To Pay` you can refer this PR (https://github.com/juspay/hyperswitch/pull/6982)
```shell
--header 'x-api-key: dev_lqs6topblZKyE7pXWRRtzmWkZcAZNxSzkXDCsNTfsgsaJXoGPN6JmR0Pwey4Aknz' \
--header 'api-key: dev_lqs6topblZKyE7pXWRRtzmWkZcAZNxSzkXDCsNTfsgsaJXoGPN6JmR0Pwey4Aknz' \
--data '{
"card_discovery": ["click_to_pay"]
}'
```
Response :
```shell
{
"count": 2,
"total_count": 1,
"data": [
{
"payment_id": "pay_JI24u3IxBDkutHtxqxVK",
"merchant_id": "sahkal",
"status": …
```
=> feat(core): add card_discovery filter to payment list and payments Response

crates/diesel_models/src/customers.rs, crates/hyperswitch_domain_models/src/business_profile.rs, crates/hyperswitch_domain_models/src/customer.rs, crates/router/src/core/customers.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/customers.rs, crates/router/src/core/payments/operations/payment_confirm_intent.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/core/payouts.rs, crates/router/src/core/payouts/helpers.rs, crates/router/src/types/storage/customers.rs
This PR updates the payments v2 flows to create a customer at connector's end, where applicable, and populate the connector's customer ID in `RouterData`, so that the connector integrations which need the connector customer ID can access the field and pass it along.
Additionally, this PR includes some refactors done around relevant code:
- Introduces a newtype instead of `serde_json::Value` for the `connector_customer` field in the customer v2 diesel and domain models.
- Addresses a `clippy::large_enum_variant` warning arising with the `CustomerUpdate` v2 enum.
- Addresses an unused variable warning for `is_click_to_pay_enabled` field in the business profile v2 code. (I just opened the file and my IDE displayed only this warning in the entire file, so I ended up fixing it.)
As of opening …
=> refactor(payments_v2): create customer at connector end and populate connector customer ID

.typos.toml, crates/api_models/src/payments.rs, crates/common_enums/src/enums.rs, crates/hyperswitch_connectors/src/utils.rs, crates/hyperswitch_domain_models/src/mandates.rs, crates/router/src/core/payments.rs
For each countries present in Europe, their states are converted to ISO Standard 
[Source for standard](https://github.com/juspay/hyperswitch-web/blob/main/src/States.json)
Note: A bugfix is present as well for address_id used to fetch billing_address for external authentication
Sanity External 3DS payment, by sending billing_address in payment_method_data for Poland country address
CURL
```
curl --location 'localhost:8080/payments/pay_MRVy1jlxGGGZafdE7xsJ/3ds/authentication' \
--header 'api-key: pk_dev_d3a60dc7950549aa954219ca29746442' \
--data '{
"client_secret": "pay_MRVy1jlxGGGZafdE7xsJ_secret_at05FqOzGfMCtJ3bRw4Y",
"device_channel": "BRW",
"threeds_method_comp_ind": "Y"
}'
```
=> feat(utils): add iso representation for each state for european countries

.typos.toml, crates/common_enums/src/enums.rs, crates/hyperswitch_connectors/src/utils.rs, crates/router/src/connector/netcetera/netcetera_types.rs, crates/router/src/connector/threedsecureio/transformers.rs, crates/router/src/connector/utils.rs
to_state_code method of router is not updated so the implementation from hyperswitch_connectors needs to be used and the one from router is depreciated.
Note: Contains remaning European countries for ISO conversion
Sanity External 3DS payment, by sending billing_address in payment_method_data for Poland country address
CURL
```
curl --location 'localhost:8080/payments/pay_MRVy1jlxGGGZafdE7xsJ/3ds/authentication' \
--header 'api-key: pk_dev_d3a60dc7950549aa954219ca29746442' \
--data '{
"client_secret": "pay_MRVy1jlxGGGZafdE7xsJ_secret_at05FqOzGfMCtJ3bRw4Y",
"device_channel": "BRW",
"threeds_method_comp_ind": "Y"
}'
```
=> refactor(utils): use to_state_code of hyperswitch_connectors in router

crates/router/src/connector/utils.rs
klarna in router crate uses to_state_code in branch hotfix-2025.02.05, thus, to_state_code implementation needs to be present in router as well
=> fix(utils): add to_state_code to router crate

cypress-tests/cypress/support/commands.js
Add assertions to verify the requires_cvv field in the customer payment method list.
Test cases enhancement
- Cybersource
=> ci(cypress): add assertions for `requires_cvv`

crates/router/src/core/routing/helpers.rs
A 5xx error log in DR metrics was spamming in alerts.
Have removed the log
make a payment with dynamic routing enabled
5xx error log now converted to 4xx
=> fix(routing): Fixed 5xx error logs in dynamic routing metrics

crates/connector_configs/src/common_config.rs, crates/connector_configs/src/connector.rs, crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml, crates/router/src/connector/netcetera/transformers.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_confirm.rs
add `merchant_configuration_id` in netcetera metadata and make other merchant configurations optional
This would allow merchant to do the required configuration on netcetera dashboard, and just provide us the merchant_configuration_id to process the payment authentications
1. Configure netcetera with merchant_configuration_id and don't send other configuration details except live endpoint prefix and test the sanity 3DS authentication
Authentication request CURL
```
curl --location '{{BASE_URL}}/payments/{{PAYMENT_ID}}/3ds/authentication' \
--header 'api-key: {{PUBLISHABLE_API_KEY}}' \
--data '{
"client_secret": "pay_5CJ7ExVzDnwBiAw4Gtku_secret_InmW7DASEWY2eZy1xBOb",
"device_channel": "BRW", …
```
=> feat(router): add `merchant_configuration_id` in netcetera metadata and make other merchant configurations optional

crates/masking/src/abs.rs, crates/masking/src/bytes.rs, crates/masking/src/secret.rs, crates/masking/src/strong_secret.rs
Add `peek_mut` function to PeekInterface to get mutable reference for the inner data.
To get the mutable reference for inner data in StrongSecret.
** THIS CANNOT BE TESTED IN ENVIRONMENTS **
=> chore(masking): add peek_mut to PeekInterface

.github/workflows/CI-pr.yml
This PR disables the `cargo-hack` step for PRs opened against hotfix branches, and in such cases `cargo check --features release` would be run instead. This is done to (hopefully) reduce the time required to get the hotfixes merged, and thus, deployed to our hosted environments.
Additionally, I've completely disabled the MSRV check for hotfix PRs, since the workflow only runs a `cargo-hack` step. And I didn't modify the v2 check, since it only runs `just clippy_v2` and a command like `cargo check --features release,v2`.
This would hopefully reduce the time required to get the hotfixes merged, and thus, deployed to our hosted environments.
N/A
=> ci(CI-pr): disable `cargo-hack` step for hotfix PRs

crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs, crates/scheduler/src/utils.rs
Cybersource throws error if state length exceeds 20 characters, to fix this this PR addes truncation of state  at Hyperswitch end
```
--header 'api-key: dev_eM1Lq0Ebo27JrIBD9t71RWadvwqQzRuDLoLNSYsYYJkFE6SfIpHzGbxFF3MVedWL' \
--data-raw '{
"amount": 700,
"amount_to_capture": 700,
"email": "dg@example.com",
"card": {
"card_number": "4917610000000000", …
```
=> fix(cybersource): Add truncation logic for administrative area

.github/workflows/hotfix-pr-check.yml
This PR updates the hotfix PR check workflow to conditionally enforce the requirement of the `main` branch PR being merged, based on the value of a repository variable.
This change would allow us to enforce the requirement by changing the repository variable, without having to make workflow file changes across multiple branches.
Temporarily removed the branch filter from the workflow to run on all pull requests, and then checked the errors reported with different values for the repository variable.
| Repository Variable | Workflow Output | Remarks |
|--------|--------|--------|
| ![Screenshot of repository variable set to true](https://github.com/user-attachments/assets/ffdb0073-67cd-4a1f-8022-9b1cb1ae7966) true | ![Screenshot of workflow …
=> ci(hotfix-pr-check): conditionally enforce requirement of main branch PR being merged

crates/router/src/core/payments/flows/session_flow.rs
For generating session token for google pay, error was thrown if connector_wallet_details was not present and google pay related data won't be  present in session token response thus parsing connector_wallet_details is made optional
Tested through Postaman:
- Create an MCA (Trustpay) with connector_wallet_details as null:
```
{
"connector_name": "trustpay",
"connector_label": "trustpay_US_default",
"merchant_connector_id": "mca_aIkTJWJcd2m5COTrHbF2",
"api_key": "{{api_key}}",
"key1": "{{key1}}",
"api_secret": "{{api_secret}}"
},
{
{ …
```
=> fix(core): make parsing optional for connector_wallet_details in session token flow

api-reference/api-reference/payments/Introduction--to--payments.mdx, api-reference/api-reference/payments/payments--create.mdx, api-reference/introduction.mdx, api-reference/mint.json
We have changes the Intro page of the API-ref to make it more informative and navigable.
Also, The API sidebar is now re-organised basis of different use-cases to improve the dev experience.
Added an introduction page to payments API explaining all the scenarios an user can explore payment API. 
Closes #7323
=> docs: changes for api ref

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/admin.rs, crates/api_models/src/payments.rs, crates/diesel_models/src/business_profile.rs, crates/diesel_models/src/payment_intent.rs, crates/hyperswitch_domain_models/src/lib.rs, crates/router/src/core/payment_link.rs, crates/router/src/core/payment_link/payment_link_initiate/payment_link.js, crates/router/src/core/payments/transformers.rs, crates/router/src/types/transformers.rs
1. Added config `skip_status_screen` in payment links to decide whether to skip status screen after payment completion
- If config is true user will be redirected to return url directly 
- If config is false,or not passed redirect user to status screen and then to return url `(default flow)`
2. Added config `background_color` to customize background color for payment links
3. Added config `payment_button_text_color` to customize text color for payment button in payment link
Tested locally 
```
curl --location --request POST 'http://localhost:8080/account/merchant_1740126811/business_profile/pro_FirWioMrQWWbdkcvq1V5' \
--data-raw '{
"*"
],
"payment_button_text": "PAY …
```
=> feat(payments): [Payment links] add configs for payment link

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml, crates/hyperswitch_connectors/src/connectors/paystack.rs, crates/hyperswitch_connectors/src/connectors/paystack/transformers.rs
Paystack EFT flow (Payments, PSync, Refunds, RSync, Webhooks).
1. Merchant Account Create:
```
--data-raw '{
"merchant_id": "merchant_1739960795",
"address": {
"line2": …
```
=> feat(connector): [PAYSTACK] EFT Payment Flows

aws/hyperswitch_aws_setup.sh, config/deployments/README.md, docker-compose-development.yml, docker-compose.yml
This PR updates Hyperswitch Docker images to be prefixed by `docker.juspay.io`. I've just done a global search-replace to be honest.
N/A
Tried the Docker Compose setup locally, didn't "test" out any of the other changes though.
=> chore(docker): prefix Hyperswitch Docker image URIs with `docker.juspay.io`

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/payments.rs, crates/diesel_models/src/payment_attempt.rs, crates/hyperswitch_connectors/src/connectors/braintree/transformers.rs, crates/hyperswitch_domain_models/src/router_request_types.rs, crates/hyperswitch_domain_models/src/router_response_types.rs, crates/openapi/src/openapi.rs, crates/openapi/src/openapi_v2.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/core/relay/utils.rs, crates/router/src/core/utils.rs, crates/router/src/services/api.rs, crates/router/src/types.rs, crates/router/src/types/api/verify_connector.rs, crates/router/tests/connectors/utils.rs
Consume merchant_account_id and merchant_config_currency from payment requests for braintree.
=> fix(connector): [Braintree] Consume merchant_account_id and merchant_config_currency in payment requests

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/admin.rs, crates/api_models/src/payments.rs, crates/diesel_models/src/business_profile.rs, crates/diesel_models/src/payment_intent.rs, crates/hyperswitch_domain_models/src/lib.rs, crates/router/src/core/payment_link.rs, crates/router/src/core/payment_link/payment_link_initiate/payment_link.js, crates/router/src/core/payment_link/payment_link_initiate/payment_link_initiator.js, crates/router/src/core/payment_link/payment_link_initiate/secure_payment_link_initiator.js, crates/router/src/core/payments/transformers.rs, crates/router/src/routes/admin.rs, crates/router/src/routes/ephemeral_key.rs, crates/router/src/routes/verification.rs, crates/router/src/types/transformers.rs
This PR exposes customizations for payment links. Below configs are added -
- SDK UI rules - https://docs.hyperswitch.io/explore-hyperswitch/merchant-controls/integration-guide/web/customization#id-4.-rules
- Payment Link UI rules - similar to SDK UI rules, but for payment link template*
Gives granular control to the payment link consumer for designing their UI.
Tested locally.
<details>
<summary>1. Add a payment link style ID</summary>
cURL
curl --location --request POST 'http://localhost:8080/account/merchant_1741095653/business_profile/pro_dgzCAaE0KhqCTj6cY5a7' \
--data '{"payment_link_config":{"allowed_domains":["*"],"business_specific_configs":{"style1":{"enabled_saved_payment_method":true,"theme":"#E71D36"," …
=> feat(payment_link): expose payment link configs for SDK UI rules and payment button

cypress-tests/cypress/e2e/configs/Payment/Adyen.js, cypress-tests/cypress/e2e/configs/Payment/BankOfAmerica.js, cypress-tests/cypress/e2e/configs/Payment/Bluesnap.js, cypress-tests/cypress/e2e/configs/Payment/Commons.js, cypress-tests/cypress/e2e/configs/Payment/Cybersource.js, cypress-tests/cypress/e2e/configs/Payment/Elavon.js, cypress-tests/cypress/e2e/configs/Payment/Fiservemea.js, cypress-tests/cypress/e2e/configs/Payment/Fiuu.js, cypress-tests/cypress/e2e/configs/Payment/Moneris.js, cypress-tests/cypress/e2e/configs/Payment/Noon.js, cypress-tests/cypress/e2e/configs/Payment/Stripe.js, cypress-tests/cypress/e2e/configs/Payment/Trustpay.js, cypress-tests/cypress/e2e/configs/Payment/WellsFargo.js
This PR is just a minor refactor of removing duplicate / redundant `customer_acceptance` object by re-using it. 
Moved the object to `Commons` and imported the object where ever the duplicate code exist.
Reduce code duplication
closes https://github.com/juspay/hyperswitch/issues/7436
CI should pass
=> ci(cypress): move customer acceptance in configs to a const within commons

crates/router/src/core/authentication.rs, crates/router/src/core/authentication/transformers.rs, crates/router/src/core/authentication/utils.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/operations/payment_confirm.rs
Add payment id in authentication router data
This change is done to populate payment id in clickhouse authentication table and kafka to get authentication analytics since analytics is dependent on payment_id.
logs screenshots
kafka UI :
Clickhouse table:
=> refactor(core): Added payment id in authentication router data

crates/analytics/src/auth_events/accumulator.rs, crates/analytics/src/auth_events/core.rs, crates/analytics/src/auth_events/metrics.rs, crates/analytics/src/auth_events/metrics/authentication_attempt_count.rs, crates/analytics/src/auth_events/metrics/authentication_count.rs, crates/analytics/src/auth_events/metrics/authentication_success_count.rs, crates/analytics/src/auth_events/metrics/challenge_attempt_count.rs, crates/analytics/src/auth_events/metrics/challenge_flow_count.rs, crates/analytics/src/auth_events/metrics/challenge_success_count.rs, crates/analytics/src/auth_events/metrics/frictionless_flow_count.rs, crates/analytics/src/auth_events/metrics/frictionless_success_count.rs, crates/analytics/src/clickhouse.rs, crates/analytics/src/lib.rs, crates/analytics/src/query.rs, crates/analytics/src/sqlx.rs, crates/analytics/src/types.rs, crates/api_models/src/analytics/auth_events.rs, crates/router/src/analytics.rs
Refactored and re-wrote the authentication related analytics.
The table being queried is now `authentications`.
The following metrics were modified:
- Authentication Attempt Count
- Authentication Count
- Authentication Success Count
- Challenge Attempt Count
- Challenge Flow Count
- Challenge Success Count
- Frictionless Flow Count
- Frictionless Success Count
Get better insights into authentications related data through analytics
Hit the following curls:
```bash
curl --location 'http://localhost:8080/analytics/v1/metrics/auth_events' \
--header …
```
=> feat(analytics): refactor and rewrite authentication related analytics

crates/api_models/src/admin.rs, crates/common_utils/src/types.rs, crates/diesel_models/src/business_profile.rs, crates/diesel_models/src/schema.rs, crates/diesel_models/src/schema_v2.rs, crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs, crates/hyperswitch_domain_models/src/business_profile.rs, crates/hyperswitch_domain_models/src/router_request_types/authentication.rs, crates/router/src/connector/netcetera/netcetera_types.rs, crates/router/src/connector/netcetera/transformers.rs, crates/router/src/core/admin.rs, crates/router/src/core/authentication.rs, crates/router/src/core/authentication/transformers.rs, crates/router/src/core/payments.rs, crates/router/src/types/api/admin.rs, migrations/2025-03-04-105454_add_force_3ds_challenge_column_to_business_profile/down.sql, migrations/2025-03-04-105454_add_force_3ds_challenge_column_to_business_profile/up.sql
add capability to force challenge for 3DS Payments through Netcetera and send few optional fields
1. Profile level enablement `force_3ds_challenge` which would request netcetera for challenge flow
2. Send few optional fields like trans_type, which can potentially be required on PROD (Because docs says, it maybe required in some markets)
Note: hotfix pr against https://github.com/juspay/hyperswitch/pull/7429
Perform a External 3DS payment by enabling force_3ds_challenge at profile level, and observe ThreeDSRequestorChallengeInd being sent "04" to netcetera connector
CURL
```
curl --location '{{BASE_URL}}/payments/{{PAYMENT_ID}}/3ds/authentication' \
--header 'api-key: {{PUBLISHABLE_KEY}}' \ …
```
=> feat(router): add capability to force challenge for 3DS Payments through Netcetera and send few optional fields 

crates/analytics/src/auth_events.rs, crates/analytics/src/auth_events/accumulator.rs, crates/analytics/src/auth_events/core.rs, crates/analytics/src/auth_events/filters.rs, crates/analytics/src/auth_events/metrics.rs, crates/analytics/src/auth_events/metrics/authentication_attempt_count.rs, crates/analytics/src/auth_events/metrics/authentication_count.rs, crates/analytics/src/auth_events/metrics/authentication_error_message.rs, crates/analytics/src/auth_events/metrics/authentication_funnel.rs, crates/analytics/src/auth_events/metrics/challenge_attempt_count.rs, crates/analytics/src/auth_events/metrics/challenge_flow_count.rs, crates/analytics/src/auth_events/metrics/challenge_success_count.rs, crates/analytics/src/auth_events/metrics/frictionless_flow_count.rs, crates/analytics/src/auth_events/metrics/frictionless_success_count.rs, crates/analytics/src/auth_events/types.rs, crates/analytics/src/clickhouse.rs, crates/analytics/src/core.rs, crates/analytics/src/lib.rs, crates/analytics/src/query.rs, crates/analytics/src/sqlx.rs, crates/analytics/src/utils.rs, crates/api_models/src/analytics.rs, crates/api_models/src/analytics/auth_events.rs, crates/api_models/src/events.rs, crates/common_enums/src/enums.rs, crates/router/src/analytics.rs
Added support for filters and dimensions for authentication analytics.
Filters added: 
- AuthenticationConnector
- MessageVersion
Dimensions added:
- AuthenticationStatus,
- TransactionStatus,
- ErrorMessage,
- AuthenticationConnector,
- MessageVersion,
New metrics added:
- AuthenticationErrorMessage
- AuthenticationFunnel
Get better insights into authentication data.
Hit the curls:
```bash
curl --location 'http://localhost:8080/analytics/v1/metrics/auth_events' \
--header 'Sec-Fetch-Mode: cors' \
--header …
```
=> feat(analytics): add new filters, dimensions and metrics for authentication analytics

crates/hyperswitch_connectors/src/connectors/rapyd.rs, crates/hyperswitch_connectors/src/connectors/rapyd/transformers.rs
fix amount conversion framework for Rapyd 
According to doc - https://docs.rapyd.net/en/create-payment.html , amount should be of FloatType (BaseUnit).
We can not test it, as we dont have credentials for Rapyd connector
=> refactor(connector): [Rapyd] fix amount conversion framework

crates/hyperswitch_connectors/src/connectors/braintree/transformers.rs
Changed the Attempt Status Mapping of `SubmittedForSettlement` and `SettlementPending` to `Charged`
Issue Link: https://github.com/juspay/hyperswitch/issues/7472
**Postman Tests**
**1. Create Payment (AutoCapture)**
-Request
```
--header 'api-key: dev_ekPGg1GI2tBzBI98TAEWKy1FHsIxlwJVA7L9mNtIZPs3UpODWkCzDpUDE2dFM46T' \
--data-raw '{
"amount": 2500,
"amount_to_capture": 2500,
"customer_id": "abcdef", …
```
=> fix(connector): [BRAINTREE] Changed Attempt Status Mapping for Braintree

crates/router/src/core/payment_methods.rs
This PR fixes the `payment_method_type` and `payment_method_subtype` not being populated when the payment method is added via the payment methods session endpoint.
Previously, whenever a payment method was added via the payment methods session confirm endpoint, on listing the payment method for the customer, we get an error because the `payment_method_type` and `payment_method_subtype` not being populated.
- Add a payment method using the payment methods session endpoint.
```bash
curl --location 'https://integ-api.hyperswitch.io/v2/payment-methods-session/12345_pms_019560e38b7a7e6389e1495f1ffa8521/confirm' \
--header 'x-profile-id: pro_VSm7frQcpOKQxveHtg8Q' \
--header 'Authorization: publishable-key=pk_snd_6e6f84710fa849a08b6fe739b7492ca0,client-secret=cs_019560e38b7c7783a4ed501baa0eca17' …
```
=> fix(payment_methods): payment method type not being stored in payment method

cypress-tests/cypress/e2e/configs/Payment/Paypal.js
connector throws above error when using VISA card. Replacing that with MasterCard fixes it:
paypal ci is failing.
`CYPRESS_CONNECTOR=paypal npm run cypress:payments`
=> ci(cypress): fix paypal failures

crates/hyperswitch_connectors/src/connectors/braintree.rs, crates/hyperswitch_connectors/src/connectors/braintree/transformers.rs, crates/hyperswitch_connectors/src/default_implementations.rs
Add mandate revoke flow to Braintree
https://developer.paypal.com/braintree/graphql/guides/payment_methods/#delete
https://github.com/juspay/hyperswitch/issues/7526
Revoking an existing mandate using tunnel needs to be tested:
Request:
```
curl --location 'http://localhost:8080/vs/v1/payment_methods/man_OVY39ecmn6QDAxh18qIe/detach' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'User-Agent: helloMozilla/5.0 (Linux; Android 12; SM-S906N Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.119 Mobile Safari/537.36' \
--header 'api-key: HIDDEN' \
--data-urlencode 'merchant_connector_details%5Bencoded_data%5D=HIDDEN'
```
Response:
```
{
"mandate_id": "man_OVY39ecmn6QDAxh18qIe",
"status": "revoked",
"error_code": null, …
```
=> feat(connector): [BRAINTREE] Add revoke mandate flow

crates/hyperswitch_connectors/src/connectors/authorizedotnet/transformers.rs
Closes this [issue](https://github.com/juspay/hyperswitch/issues/7522)
Changed the attempt status mapping of `CapturedPendingSettlement` given by AuthorizeDotNet from `ChargeInitiated` to `Charged`
When the capture_method is automatic, AuthorizeDotNet connector first sends a `CapturedPendingSettlement` status which is mapped to `ChargeInitiated` in our codebase. That results in `processing` transaction status in the Hyperswitch's response (in production environment).
Postman tests are not valid since AuthorizeDotNet directly sends `SettledSuccessfully` status in local/sandbox environment.
=> fix(connector): fix incorrect mapping of attempt status in AuthorizeDotNet connector

crates/common_enums/src/connector_enums.rs, crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs, crates/hyperswitch_connectors/src/utils.rs, crates/hyperswitch_domain_models/src/business_profile.rs, crates/router/src/core/admin.rs, crates/router/src/core/payments/transformers.rs
- card network fetch from db was not being populated in payment call resulting in sending the default value which failed the payment
- util function have been added to collect the card network from additional_payment_method_data
- ucaf_indicator is being populated for mastercard 
- profile generic update is made optional to not update the force_3ds_challenge if it is passed as null
- External authentication is disabled for Datatrans
Note: hotfix raised against https://github.com/juspay/hyperswitch/pull/7473
- Create MCA(Cybersource):
- Create MCA(Netcetera):
- Create a payment call (enable external 3ds):
```
{
"amount": 499, …
```
=> fix(router): pass card network for external 3DS from additional_payment_method_data

crates/hyperswitch_connectors/src/connectors/paybox/transformers.rs
Handle Missing Sequential Automatic case for Paybox MIT 
**CIT Payments**
```
Request
--header 'api-key: dev_kHPzYM5Uswd1YML6yqjBYuZgFJaRFnAeTv40MYW8WQMZ9gxAeCEBkSnHYpV3sdcv' \
--data-raw '{
"amount":4501,
"capture_method": "sequential_automatic",
"email":"malay.awasthi@gmail.com",
"billing": {
"address": {
},
"phone": {
"number": "8056594427",
"country_code": "+91"
}
},
"acceptance_type": "online", …
```
=> fix(connector): Handle Sequential Automatic case in MIT payments

crates/router/src/core/routing.rs
Reverts juspay/hyperswitch#7199
We are reverting the filtering of response for payment and payout processors.
So this works as follows:
If Payment's route is hit all the PaymentProcessors will be listed like PayoutConnectors etc.
Tested after creating JWT locally and adding 1 payment and 1 payout connector.
Payment :
```
curl --location 'http://localhost:8080/routing/default/profile' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMWMyMTJhODgtOGFmYy00YjJjLWIwYWQtODY3MmQ2NTI3MzdlIiwibWVyY2hhbnRfaWQiOiJtZXJjaGFudF8xNzQxMDAzMjgwIiwicm9sZV9pZCI6Im9yZ19hZG1pbiIsImV4cCI6MTc0MTE3NjE1Miwib3JnX2lkIjoib3JnX1c4MkFMNTZ6VVE1dXFHcEEyYzFkIiwicHJvZmlsZV9pZCI6InByb19NcUlMcDAwdUFJeW5JZDdtUTNUTyIsInRlbmFudF9pZCI6InB1YmxpYyJ9.RoPyIG-JGrH6QmM6Gqd9gh03hOqy6MuC9Our9EHYGNk' …
```
=> refactor(core): Revert "filter default routing config response based on connector type"

crates/api_models/src/payments.rs, crates/router/src/core/payment_link.rs, crates/router/src/core/payment_link/payment_link_initiate/payment_link.js, crates/router/src/core/payment_link/payment_link_status/status.css, crates/router/src/core/payment_link/payment_link_status/status.html, crates/router/src/core/payment_link/payment_link_status/status.js
Hotfix for https://github.com/juspay/hyperswitch/pull/7531
Helps merchants take action for requires_customer_action state in case user re-renders the link for the mentioned intent status.
=> feat(payment-link): emit intent status to parent before rendering payment link UI

crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs
send xid as none for external 3ds payments
Main PR - https://github.com/juspay/hyperswitch/pull/7577
Test cases in main PR
=> fix(connector): [CYBERSOURCE] send xid as none for external 3ds payments

crates/hyperswitch_connectors/src/connectors/braintree/transformers.rs
ORIGINAL PR: https://github.com/juspay/hyperswitch/pull/7591
Pass email in payment request body of Braintree as  it is mandatory field for sending receipts in braintree
https://github.com/juspay/hyperswitch/issues/7590
Payment Request:
```
{
"amount": 1233,
"customer_id": "abcdef",
"billing": {
"email": "guest@example.com"
}
"card": {
"card_number": "5200000000001096",
}
}
}
```
Payment Response:
```
{
"payment_id": "pay_o6SLsqlZ6J049AiPkHwW",
"merchant_id": …
```
=> refactor(connector): [BRAINTREE] Pass email in payment requests

crates/hyperswitch_connectors/src/connectors/authorizedotnet/transformers.rs
Closes this [issue](https://github.com/juspay/hyperswitch/issues/7565)
Mapped status `voided` coming from AuthorizeDotNet to `Failure` in Hyperswitch.
AuthorizeDotNet has started sending status voided in RSync Response which is not mapped in Hyperswitch. As a result, deserialization failed.
Can't be tested as AuthorizeDotNet takes 5-6 business days to send any other status than `RefundPendingSettlement`.
=> fix(connector): RSync voided status mapping in AuthorizeDotNet

crates/hyperswitch_connectors/src/connectors/globalpay/transformers.rs, crates/router/src/core/admin.rs
This PR address the 5xx that occurs with GlobalPay connector when the required field `account_name` is not passed during MCA creation.
Below migration needs to be run on hosted environments:
```sql
UPDATE merchant_connector_account
SET metadata = jsonb_set(
metadata,
'{account_name}',
'""',
true
)
WHERE connector_name = 'globalpay'
AND NOT metadata ? 'account_name';
```
Getting the connector production ready.
<details>
<summary>0. try creating mca without passing `metadata` field</summary>
```curl
curl --location 'http://Localhost:8080/account/postman_merchant_GHAction_b7e0e1f4-ca0a-495e-8a6f-915769911e30/connectors' \
--data '{ …
```
=> fix(connector): [globalpay] address 5xx due to deserialization issue when `account_name` is not passed

crates/hyperswitch_connectors/src/connectors/bankofamerica/transformers.rs
Implemented Payment Method Samsung Pay for connector Bankofamerica
https://github.com/juspay/hyperswitch-cloud/issues/7903
1. Connector configuration with merhcant account
```
curl --location 'http://localhost:8080/account/merchant_1734596148/connectors' \
--data '{
"connector_name": "bankofamerica",
"api_secret": API_SECRET_HERE,
"key1": KEY_1 here,
"api_key": API_KEY here
},
{
{
"payment_method_type": "samsung_pay", …
```
=> feat(connector): [BANKOFAMERICA] Implement Samsung Pay

crates/hyperswitch_connectors/src/connectors/adyen/transformers.rs
Added `FRM` data in payment request for connector `Adyen`
```
--header 'api-key: dev_1tUvTWvHj4yX8wc3kkROOR01P8ikqRzDkcj3ZUdcpLmTjhkuW6f7LPj1s7RhO3Nc' \
--data-raw '{
"amount": 100,
"card": {
"card_number": "4917610000000000",
"card_exp_year": "30",
"card_cvc": "737",
"card_network": "Visa"
}, …
```
=> refactor(request_body): Added FRM data in payment request

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml
Added wasm changes to collect metadata for visa_ctp
Once this PR is merged check for `ctp_visa` connector addition and look for input field in metadata in dashboard. Should look similar toh ctp_mastercard metadata input fields 
```shell
"metadata": {
"dpa_id": "DPA-ID",
"dpa_name": "TestMerchant",
"locale": "en_AU",
"card_brands": [
"mastercard",
"visa"
],
"acquirer_bin": "BIN",
"acquirer_merchant_id": "MERCHANT-ID",
"merchant_category_code": "0001",
"merchant_country_code": "US"
}
```
=> feat(dashboard): Added wasm changes to collect metadata for visa_ctp

cypress-tests/cypress/support/redirectionHandler.js
This PR adds a check in Cypress `redirectionHandler` to verify that `payment_id` exists after the redirection completes without which it throws an error!
We need to check if we get `payment_id` in return url after the redirection completes.
tested by inverting the check:
since i asked cypress to throw an error if `payment_id` exist, it threw me an error:
so, the check works as expected.
=> ci(cypress): verify existence of `payment_id` after redirection

docker-compose.yml
Docker pull from latest stable tag
Web Docker Image was not working properly 
Now with this fix its working
Via locally running Docker Image
=> fix: web-docker pull from docker hub

cypress-tests/cypress/e2e/configs/Payment/Iatapay.js, cypress-tests/cypress/e2e/spec/Payment/00022-Variations.cy.js
Fixed the IataPay Cypress test cases as UPI_Collect payments were failing due to an invalid billing.address.country.
Cypress test cases were failing 
Cypress 
Before
After
Adyen 
Bluesnap
=> ci(cypress): fix iatapay upi payments

api-reference/openapi_spec.json, crates/openapi/src/routes/profile.rs
Need to update the API doc to display Admin API Key instead of API key for Profile - Delete.
Correct Information to be displayed in the API docs.
Cannot be tested.
=> refactor(openapi): modify profile-delete auth to AdminAPIKey in API doc

crates/analytics/src/lib.rs
Currently, if the `forex_enabled` feature flag is not present as an ENV, it is leading to deserialization errors.
Modified it in such a way to assume the default value (false) if the ENV is not present.
Fix deserialization errors for analytics
Removed the `forex_enabled` feature flag from local envs, and replicated the error
Need to remove the env `forex_enabled` during deployment, and then test out the analytics section..
Tested on local, by removing the `forex_enabled` env and checking the analytics API calls, worked as expected
Curl: 
```bash
curl --location 'http://localhost:8080/analytics/v1/org/metrics/payments' \
--header 'Origin: …
```
=> refactor(analytics): default config for forex_enabled

crates/connector_configs/src/common_config.rs, crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml
The metadata fields should have currency_id and platform_id as numbers, not strings for coingate 
No testing required.
=> fix(connector): [Coingate] Fix Wasm Changes 

crates/hyperswitch_connectors/src/connectors/nexixpay/transformers.rs
Nexixpay does not send error_code and error_message in case of failure responses. We will store NO_ERROR_CODE and nexixpay operation result as error_message in this case in our DB. This is sent in outgoing webhooks to the merchants.
Possible values of error messages:
1. Declined
2. DeniedByRisk
3. ThreedsFailed
4. Failed
Currently error_code and error_message goes null in case of webhooks to merchants for nexixpay. We need to pass NO_ERROR_CODE and nexixpay operation result as error_message as connector doesn't sends us any message or code.
Curls to test:
```
--header 'api-key: dev_nRAnqXGtbt60CdOO7rfovzh4MdEAIiaqnWc78AdQIx4yWnDXIKetpkjGFOvwFPcb' \ …
```
=> fix(connector): [Nexixpay] handle error code and message in failure response

.github/workflows/cypress-tests-runner.yml
this pr updates the `adyen` payouts credentials and it also replaces wise from running in github ci
ci checks are failing across all prs. closes #7755
ci checks should pass.
=> ci(cypress-ci): remove wise payout from running in github ci

postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario16-Bank Redirect-sofort/Payments - Confirm/event.test.js, postman/collection-dir/stripe/Flow Testcases/Happy Cases/Scenario16-Bank Redirect-sofort/Payments - Retrieve/event.test.js
Mapping `status`, `error_code`, and `error_message` for `Stripe` Payment Processor `Sofort` Bank Transfer Payment Method as `Sofort` has been deprecated by `Stripe`.
`Stripe` Payment Processor has deprecated `Sofort` Bank Transfer Payment Method.
_Before_
_After_
=> chore(postman): update `Stripe` response `status`, `error_code`, and `error_message` for deprecated `Sofort`

docker-compose.yml, scripts/poststart_hook.sh, scripts/prestart_hook.sh
Added a webhook notifier for pre- and post-installation of `hyperswitch` using docker compose. This webhook sends the following API call to `https://hyperswitch.gateway.scarf.sh`:
- **initiated** (when a user tries to install hyperswitch)
- **success** (when all the components are successfully up and running)
- **error** (when any of the component fails or the server is unreachable)
The API calls include information about the platform(docker/helm/cdk), version and additional information about success/failure.
This change enables tracking of installation attempts, providing valuable insights into user adoption and setup experience. By monitoring success and failure rates, we can identify and resolve potential setup issues, ultimately improving user experience.
1. Create a mock server and …
=> feat(docker): add webhook notifiers for installation tracking

config/config.example.toml, config/deployments/integration_test.toml, config/deployments/production.toml, config/deployments/sandbox.toml, config/development.toml, config/docker_compose.toml, crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml, crates/router/src/connector/stripe/transformers.rs, cypress-tests/cypress/e2e/configs/Payment/Stripe.js, cypress-tests/cypress/e2e/configs/Routing/Stripe.js, loadtest/config/development.toml
Removed sofort bank redirect from Stripe, as Stripe has deprecated sofort.
Also added configs for Stripe Ach and Multibanco.
Nothing to test with sofort.
Test currencies in Ach and Multibanco for stripe to test the configs.
=> refactor(connector): [STRIPE] Remove sofort bank redirect from stripe

crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_create.rs
This PR adds a validation for `return_url` when creating payment links. Return URL must be a required parameter as payment links is client side facing and needs to be redirected to an end URL post payment completion.
This PR fixes a bug in the payment links flow which allowed creating payment links without validating presence of `return_url`. This allows merchants to be careful of payment link integration.
<details>
<summary>1. Create a payment link without return_url in the payments create request</summary>
cURL
--header 'api-key: dev_ddmeaxUlgRPHkcqtmZZm5nGMRhejMxXijYCnsp070Oqn2y4lrfUNBCb9UmedwgMt' \
--data-raw …
=> fix(payment_link): add validation for return_url during payment link creation

crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs
Hotfix for https://github.com/juspay/hyperswitch/pull/7828
Authentication with Netcetera was successful, but authorization with Cybersource failed with the below error:
Declined - The request is missing one or more fields, detailed_error_information: paymentInformation.card.typeSelectionIndicator : MISSING_FIELD
Need to send card.typeSelectionIndicator as 1, for all co-badged cards txns with Cybersource (authorization).
This can be tested with below payments call:
```
--header 'api-key: dev_4KJPCRL8DJ8dAo0l8hF7TnL7j8TKkbreziz4Zebyv23PtZJOptiK5vpAZjh7eESn' \
--data-raw '{
"amount": 499, …
```
=> fix(connector): [Cybersource] send type selection indicator for co-batch cards

api-reference-v2/openapi_spec.json, api-reference/openapi_spec.json, crates/api_models/src/payments.rs, crates/hyperswitch_connectors/src/connectors/adyen/transformers.rs, crates/hyperswitch_connectors/src/utils.rs, crates/hyperswitch_domain_models/src/router_request_types.rs, crates/openapi/src/openapi.rs, crates/openapi/src/openapi_v2.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/types.rs, crates/router/src/types/api/verify_connector.rs, crates/router/tests/connectors/utils.rs
This PR adds support for connector testing data in payment requests, specifically for Adyen connector. It allows merchants to send testing values via `connector_metadata` to simulate different scenarios in the sandbox environment.
The implementation includes:
1. Added a new structure `AdyenConnectorMetadata` and `AdyenTestingData` in the API models
2. Modified the Adyen connector payment flows (both CIT and MIT) across different payment methods to accept and process the testing data
The holder_name in testing data will override card_holder_name in the connector's payment request, allowing merchants to test specific scenarios without affecting their production implementation.
Connectors like Adyen provide special values for certain fields that can be used to simulate different error …
=> feat(payments): add support for connector testing (Adyen)

config/docker_compose.toml
This PR removes the open-router configuration from docker_compose.toml
Since this is just a docker config change and cypress was failing due to this, ensuring CI check pass for cypress should suffice
=> fix(config): remove open-router configuration from docker compose toml

crates/hyperswitch_connectors/src/connectors/worldpay.rs, crates/hyperswitch_connectors/src/connectors/worldpay/transformers.rs, crates/payment_methods/src/configs/payment_connector_required_fields.rs
Hotfix for https://github.com/juspay/hyperswitch/pull/7897
Card holder name is a mandatory field which is required by WP during card transactions.
Fixing the 3DS SetupMandate flow for Worldpay allows merchants to consume the functionality.
Same as in https://github.com/juspay/hyperswitch/pull/7897
=> chore: add cardholder name as mandatory field for Worldpay card transactions

crates/api_models/src/analytics/refunds.rs, crates/api_models/src/refunds.rs, crates/diesel_models/src/enums.rs
- set Instant as the default RefundType
1. Create a Merchant
2. Create a API Key
3. Create Stripe MCA
4. Create a Stripe Payment
```
{
"card": {
}
},
"billing": {
"address": { …
```
=> refactor(refunds): set Instant as the default RefundType

config/config.example.toml, config/deployments/env_specific.toml, config/deployments/integration_test.toml, config/deployments/production.toml, config/deployments/sandbox.toml, config/development.toml, config/docker_compose.toml, crates/router/src/configs/settings.rs, crates/router/src/configs/validations.rs, crates/router/src/core/webhooks/outgoing.rs, crates/router/src/core/webhooks/utils.rs, loadtest/config/development.toml
The current implementation of insertion of an event in `event` table does not handle the case where multiple requests with the same idempotent_event_id might be processed concurrently, leading to multiple unique constraint violation errors in the database.
This was reported by a merchant who was facing high volumes of unique constraint violation errors.
NOTE: this unique constraint log error issue is only applicable for the`initial` attempt of outgoing webhook delivery, not for retry attempts
**Why does this happen?**
1. Multiple requests with the same `idempotent_event_id` might reach the database at the same time.
2. Each request checks for the event, finds nothing (since it’s not committed yet), and proceeds to insert.
3. The first request succeeds, while the others fail due to the …
=> feat(core): add redis lock during insertion of event in event table during initial attempt of outgoing webhook delivery

crates/hyperswitch_connectors/src/connectors/stripebilling.rs, crates/hyperswitch_connectors/src/connectors/stripebilling/transformers.rs
This PR changes the url of billing connector payment sync flow from using stripe charge api to stripe payment intents api. Because in Recovery Flow there is a chance to call stripe's psync flow to update the error codes and other details for an attempt. And psync flow accepts payment intent id rather than the charge id. To reuse the existing flow we need payment_intent id to propogate.
To test this You can follow the steps of this PR: #7461
Tested it locally. And the logs are as following.
=> refactor(connector): [Stripebilling] change Billing Connector Payment Sync url from charges to payment intents api

crates/diesel_models/src/query/generics.rs
This PR changes the way we raise error if something goes wrong with generic filter. Currently we throw not found error which is wrong.
This feature is hard to test on hosted environments, as this requires to make some db changes so that we can get error in generic filter.
We will able able to log correct error messages
Tested it with dropping `organization_id` column in refund table while trying to create refund.
According to current implementation, we are raising not found error which is incorrect because it is not displaying the right cause.
Implementation in this PR fixes this bug.
=> fix(diesel_models): Fix error message while using generic filter

crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs
Hotfix for https://github.com/juspay/hyperswitch/pull/7956
Fixes the bug which allows debit card mandate creation, but does not allow MITs for the same payment method entry.
Same as described in https://github.com/juspay/hyperswitch/pull/7956
=> fix(connector): [Novalnet] allow debit card MITs

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml
Added wasm changes for the coinbase
=> feat(connector): Fix Wasm Changes for Coinbase

crates/router/src/db/kafka_store.rs
Fixed stack over flow for session call in authentication connectors
Currently when we are doing session call for authentication connectors stack is overflowing since the function
`list_enabled_connector_accounts_by_profile_id` is calling itself recursively in implementation of kafka store.
Setup Click to Pay and do session call should provide proper response than 503
=> fix(router): Fixed stack over flow for session call in authentication connectors

cypress-tests/cypress/support/redirectionHandler.js
Stripe introduced changes in how bank redirects are handled within iframes, so the corresponding Cypress test has been updated to reflect this.
The previous test setup was failing due to changes in Stripe’s redirect behavior. This update ensures compatibility with the new flow and resolves the failing checks.
Ran locally
=> ci(cypress): Fix Bank Redirects for stripe test

crates/api_models/src/routing.rs, crates/router/src/core/errors.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/operations/payment_response.rs, crates/router/src/core/payments/routing.rs, crates/router/src/core/routing/helpers.rs
This pull request introduces significant updates to the dynamic routing logic, focusing on enhancing the success-based routing mechanism and improving the integration with the "open router" service. Key changes include the addition of a new helper method, refactoring of existing methods for better clarity, and updates to the routing logic to streamline decision-making.
* Added a new method `is_success_rate_routing_enabled` in `DynamicRoutingAlgorithmRef` to determine if success-based routing is enabled, improving readability and encapsulation. (`crates/api_models/src/routing.rs`)
* Modified the `perform_open_routing` function to consolidate success-based and elimination routing into a single API call, simplifying the logic for deciding gateways. …
=> refactor(open_router): call elimination routing of open router if enabled instead of dynamo

crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs
We're passing base64 encoded data in SetupMandate flow for apple pay token, but Novalnet expects apple pay token as decoded raw string. This PR fixes this.
Cannot be tested locally.
=> fix(connector): [Novalnet] send decoded token for apple pay payment

crates/hyperswitch_connectors/src/connectors/noon.rs
Noon has updated there Authentication api
- The mode selector has been deprecated because there is no more segregation of authentication for TEST/LIVE environment via the authorization header,
the endpoint used will take care of routing the request to the relevant environment.
Current
Mode selector is mandatory in the authorization header to authenticate credentials:
• Key_test Base64(BusinessIdentifier.ApplicationIdentifier:ApplicationKey)
• Key_live Base64(BusinessIdentifier.ApplicationIdentifier:ApplicationKey)
New
Mode selector no more required, for both environments the new format is:
• Key Base64(BusinessIdentifier.ApplicationIdentifier:ApplicationKey
1. Create a Noon Payment 
```
--header …
```
=> refactor(connector): [Noon] auth header

crates/router/src/core/authentication.rs
Currently if we cancel the transaction after initiating with netcetera we are trying hard fetch cavv stored in temp locker, which is causing 5xx.
with this PR we will be ignoring the cavv fetch error since it will be fetched in authorisation flow if authorisation need to be done!
Tested via sdk 
forward flow ( friction)
https://github.com/user-attachments/assets/0c1e56c1-b849-47b9-9a3a-734ba7675a33
forward flow ( friction less)
https://github.com/user-attachments/assets/b3daf207-3942-486d-b4eb-b351adf5c81e
backward flow 
https://github.com/user-attachments/assets/4e53d72b-584d-488b-b67b-8b1c3e1ca469
table screenshot
=> fix(router): fixed netcetera flow for backward flow cavv fetching

crates/hyperswitch_connectors/src/connectors/adyen/transformers.rs, crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs, crates/hyperswitch_connectors/src/connectors/multisafepay/transformers.rs, crates/hyperswitch_connectors/src/connectors/payeezy/transformers.rs, crates/hyperswitch_connectors/src/connectors/payone/transformers.rs, crates/hyperswitch_connectors/src/utils.rs
Payment via CartesBancaires were failing via Cybersource, since the card_type passed was wrong. It was previously "006" ,but should be "036" - this PR introduces this fix.
source
https://developer.cybersource.com/library/documentation/dev_guides/Retail_SO_API/html/Topics/app_card_types.htm
**/payments curl via Cybersource**
--header 'api-key: dev_NPIG8WP70mW0jR7lCFARlP4ca4QlG1h99wGNpagFQsVdID90RONd5m7DDChGTzBk' \
--data-raw '{
"amount": 700,
"amount_to_capture": 700,
"email": "dg@example.com", …
=> fix(connector): [CYBERSOURCE] fix CartesBancaires card_type for Cybersource

crates/api_models/src/admin.rs, crates/diesel_models/src/business_profile.rs, crates/diesel_models/src/schema.rs, crates/hyperswitch_domain_models/src/business_profile.rs, crates/hyperswitch_domain_models/src/payment_method_data.rs, crates/hyperswitch_domain_models/src/payments.rs, crates/router/src/core/admin.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/helpers.rs, crates/router/src/core/payments/operations/payment_response.rs, crates/router/src/core/payments/tokenization.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/types/api/admin.rs, cypress-tests/cypress/e2e/configs/Payment/Noon.js, cypress-tests/cypress/support/commands.js, migrations/2025-05-16-064616_add_is_pre_network_tokenization_enabled_in_business_profile/down.sql, migrations/2025-05-16-064616_add_is_pre_network_tokenization_enabled_in_business_profile/up.sql, v2_migrations/2025-05-05-073505_remove_is_pre_network_tokenization_enabled_from_business_profile/down.sql, v2_migrations/2025-05-05-073505_remove_is_pre_network_tokenization_enabled_from_business_profile/up.sql
Introduced a new field in business_profile (is_pre_network_tokenization_enabled).
Based on that field the card will be tokenized before first payment.
If the payment get succeeded the card and network token data will be stored in the locker afterwards.
1. Enable is_network_tokenization_enabled and is_pre_network_tokenization_enabled in business_profile
2. Create a card payment with a network tokenization supported connector. (Customer acceptance should be there)
Connector Create(Cybersource):
```
curl --location 'http://localhost:8080/account/merchant_1747299015/connectors' \
--header 'api-key: dev_6YZ1hGvUYrgBzKrKO25WteTts6KvLVXCodhEmuqaogJZvLhGIEVSVNftVcZytpdE' \
--data '{
"connector_type": …
```
=> feat(core): [Network Tokenization] pre network tokenization

config/config.example.toml, config/deployments/integration_test.toml, config/deployments/production.toml, config/deployments/sandbox.toml, config/development.toml, config/docker_compose.toml
This PR adds SEK currency for cybersource
**/payment curl**
`
--header 'api-key: dev_T2i3ahN91KOsWsk7hGjfY7qN35q2bE2xPIyL0kd8bNDk2rmvMSb4rsrOx4HJoGSE' \
--data-raw '{
"amount": 700,
"currency": "SEK",
"amount_to_capture": 700,
"email": "dg@example.com",
"card": {
"card_number": "4111 1111 1111 1111",
"card_exp_month": "12",
"card_exp_year": "30",
}, …
=> feat(connector): [CYBERSOURCE] add SEK currency for cybersource

crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs, crates/hyperswitch_connectors/src/connectors/redsys/transformers.rs
This PR contains changes for two connector integrations
1. Fiuu - omit `bank_code` from the refund request for enabling ORF feature from Fiuu's side
2. RedSys - fix the field for sending `browserJavascriptEnabled` field properly
This change fixes the issues for Fiuu and RedSys integrations. Fiuu for refunds flow, and RedSys for 3ds card transactions.
Can only be tested in production.
=> refactor(connector): [Fiuu] enable refund ORF feature [RedSys] fix the request structure

crates/api_models/src/routing.rs, crates/router/src/core/payments/routing.rs
This pull request modifies the default configuration for `SuccessBasedRoutingConfig` in the `crates/api_models/src/routing.rs` file. The changes adjust the values for aggregate sizes, success rate thresholds, and block duration to better align with updated routing requirements.
Key changes to default routing configuration:
* Updated `min_aggregates_size` from `2` to `5` and `max_aggregates_size` from `3` to `8` to allow for larger aggregate sizes.
* Changed `current_block_threshold` to set `duration_in_mins` to `None` (previously `5`) and increased `max_total_count` from `2` to `5`, providing more flexibility in block thresholds.
1. Toggle success based routing for a profile, Check the business profile table in DB, get the routing_algorithm_id active for that profile and check in …
=> refactor(success_rate): update the default configs

crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
Fixed Fiuu connector to properly handle and return `error_code` and `error_message` for failed FPX transactions. The connector was previously receiving error information during redirection back to Hyperswitch but was not populating these fields in API responses after redirection back to Hyperswitch during Payment Sync (PSync) operations.
**Changes made:**
- Updated Fiuu connector's FPX transaction handling to capture and store error_code and error_message from redirection responses
- Modified PSync logic to properly propagate error information to payment API response
This change addresses a critical gap in error handling for FPX transactions through the Fiuu connector. Currently, when FPX transactions fail, the error details provided during redirection are not being captured and made …
=> fix(connector): [Fiuu] populate error_code and error_desc for redirection flows if they're not present in PSync

api-reference-v2/openapi_spec.json, api-reference/hyperswitch_intelligent_router_open_api_spec.yml, api-reference/openapi_spec.json, crates/api_models/src/open_router.rs, crates/api_models/src/routing.rs, crates/external_services/src/grpc_client/dynamic_routing/success_rate_client.rs, crates/router/src/core/payments/routing.rs, cypress-tests/cypress/e2e/configs/Payment/Worldpayxml.js, proto/success_rate.proto
This pull request introduces a new feature to support an "exploration percentage" parameter in success-based routing configurations and adds a "RoutingApproach" enum to define routing strategies. These changes span multiple files, including API specifications, Rust models, and protocol buffer definitions, ensuring end-to-end support for the new functionality.
* Added `exploration_percent` parameter to the `SuccessBasedRoutingConfig` struct in Rust models (`crates/api_models/src/routing.rs`) and updated its default implementation. [[1]](diffhunk://#diff-6eb6e93a94555e904f304999acc96ab6125769971da9ec3dcbb30d5912b4fc45R963) [[2]](diffhunk://#diff-6eb6e93a94555e904f304999acc96ab6125769971da9ec3dcbb30d5912b4fc45R992)
* Modified the `update` method in `SuccessBasedRoutingConfigBody` to handle …
=> refactor(success_based): add support for exploration

crates/hyperswitch_domain_models/src/payments.rs, crates/hyperswitch_domain_models/src/router_data.rs, crates/router/src/core/payments.rs, crates/router/src/core/payments/operations/payment_get.rs, crates/router/src/core/payments/operations/payment_response.rs, crates/router/src/core/payments/transformers.rs, crates/router/src/core/revenue_recovery.rs, crates/router/src/core/revenue_recovery/types.rs, crates/router/src/core/webhooks/incoming_v2.rs
Currently, we have two endpoints for retrieving payment information in v2:
- GET  /payments/:id
- GET /payments/:id:/get-intent
The endpoint /payments/{payment_id} is called after confirmation, at which point a payment attempt always exists. Currently, payment_attempt in PaymentStatusData is stored as an optional field requiring implementation for get_payment_attempt().
This PR refactors the PaymentStatusData struct to make payment_attempt a required field
1. Payments Create
2. Payments Confirm
3. Payments Retrieve
```
curl --location 'http://localhost:8080/v2/payments/12345_pay_0196fd5c3d7a7502a39002fd8ce86a03?force_sync=true' \
--header 'x-profile-id: pro_zpak30UxH06EvzDWoXsW' \
--header 'Authorization: api-key=dev_Qi7ZsoVS4uccUf9Zy3pbS3eqvHjledzayfBn3i74bic6JHGMXNGpuY4wwN1xEMoQ' \ …
```
=> refactor: Payment Attempt as mandatory field in PaymentStatusData

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml, crates/hyperswitch_connectors/src/connectors/worldpay.rs, crates/hyperswitch_connectors/src/connectors/worldpay/transformers.rs
This PR adds below changes for the Worldpay connector
1. Add a root CA certificate for Worldpay's request client
2. Add a new AuthType for Worldpay - MultiAuthType
3. Use `MultiAuthType` in wasm crate for Worldpay
This fixes the self signed certificate not trusted errors for Worldpay in production.
Cannot be tested in non prod env.
=> fix(connector): [Worldpay] add root CA certificate

crates/connector_configs/src/connector.rs
This change adds support for capturing the reportGroup in the dashboard.
Currently, the dashboard does not extract the reportGroup from the metadata. With this update, it will start collecting and displaying the reportGroup field correctly.
=> fix(wasm): [Worldpayvantiv] add support for metadata.report_group

crates/payment_methods/src/configs/payment_connector_required_fields.rs
This PR fixes the required fields error in SDK.
SDK throws `Missing Required Param: cpf`.
Closes https://github.com/juspay/hyperswitch/issues/8275
CPF now gets populated:
```curl
curl --location 'http://localhost:8080/account/payment_methods?client_secret=pay_1iYxKKzKMLFXthlD6iAO_secret_i2gpOEtZadPHnlUpKR1Z' \
--header 'api-key: pk_dev_9caa65826ff740e78fcf292b7d96f31f'
```
```json
{
"redirect_url": "https://duck.com/",
{
{
{
"card_network": "Interac",
"surcharge_details": null,
"facilitapay"
]
},
{
"card_network": "Discover",
"surcharge_details": null, …
```
=> fix(connector): [facilitapay] cpf is a required field

api-reference-v2/openapi_spec.json, crates/api_models/src/customers.rs
We are removing `merchant_reference_id` from all API updates, due to possible bugs on merchant side db and HS db as there might be mismatch in their's and our's db records. This exists only in customers and refunds v2 apis, a separate PR has been implemented for refunds update, and this PR is for customers v2 update api.
It was noticed that in the current implementation of customers v2 update flow, the `merchant_reference_id` field is being accepted by the API but it was never updated in the db. In this PR we are removing `merchant_reference_id` from being accepted in the customers v2 update request.
Upon merging this PR, we will be removing `merchant_reference_id` from being updated in customer v2 update api.
- Create Customer API Call
``` …
```
=> refactor(customers_v2): Remove merchant reference id from v2 customer update

api-reference/openapi_spec.json, crates/api_models/src/payments.rs, crates/diesel_models/src/payment_intent.rs, crates/diesel_models/src/schema.rs, crates/hyperswitch_domain_models/src/payments/payment_intent.rs, cypress-tests/cypress/e2e/configs/Payment/Commons.js, cypress-tests/cypress/e2e/spec/Payment/00022-Variations.cy.js, migrations/2025-05-25-185220_add-merchant_return_url-column-to-payment_intent/down.sql, migrations/2025-05-25-185220_add-merchant_return_url-column-to-payment_intent/up.sql, v2_migrations/2025-01-13-081847_drop_v1_columns/up.sql
- A new field in introduced in payment_intent table called extended_return_url
- This deprecate the existing return_url field since it can take string only upto length 255
- extended_return_url can now take length upto 2048 size
- write is done into the new field (extended_return_url)
- read is backward compatible (return_url as fallback)
Note: hotfix raised against https://github.com/juspay/hyperswitch/pull/8135
- Create a Payment with return url length smaller than 2048
```
curl --location '{{baseUrl}}/payments' \
--data-raw '{
"amount": 499,
"email": …
```
=> refactor(core): introduce new field in payment_intent to handle longer return_url

api-reference-v2/openapi_spec.json, crates/openapi/src/routes/refunds.rs, crates/router/src/routes/app.rs
Currently to list refunds in v2, we are using GET verb, but we are passing filters through body which is not correct. Since listing requests are generally GET requests, we pass filters through query params.
In the current scenario, passing filters through query params may result in url length violation. Hence we are changing the route verb from GET to POST request.
Follow correct and semantic approach to list refunds in v2 apis.
Create some payments and refunds before hand.
- List all refunds API call
```
curl --location 'http://localhost:8080/v2/refunds/list' \
--header 'x-profile-id: pro_hB6oV5vfIHyqUVw1aetw' \
--header 'Authorization: api-key=dev_iNC2eYPgqnHNYoFG44nlmpp3ofzZqQ4wPOcx9r7IONCidqNmbVRLwXZwgctSQn4m' \
--data '{
}'
```
- Response …
=> refactor(refunds_v2): Change refunds v2 list request verb from GET to POST

crates/hyperswitch_connectors/src/connectors/archipel/transformers.rs
… implemented as required in the code to optional
Change connector fields that are currently implemented as required in the code to optional - billing address and card holder name are optional fields
make /payments without optional field billing.address
--header 'api-key: dev_T1HKwjm5U0WlfjAgmTAcoE2ejpTsm5J02qCBBqYTNVkHZ7KY5ZKkz2HLfR26Mz5r' \
--data '{
"amount": 600,
"amount_to_capture": 600,
"card": {
"card_cvc": "123",
"card_exp_year": "50", …
=> fix(connector): [ARCHIPEL] Change connector fields that are currently implemented as required in the code to optional

crates/hyperswitch_connectors/src/connectors/archipel/transformers.rs
Archipel does not accept `card.card_holder_name` field without `cardholder` field.
So if `card_holder` is None, `card.card_holder_name` must also be None.
However, the reverse is allowed — the `cardholder` field can exist without `card.card_holder_name`.
This PR adds changes to make sure if `card_holder` is None, `card.card_holder_name` will also be None
NOTE - As an alternate solution we cannot mark `card.card_holder_name`,`cardholder`  fields as required, since these are not mandatory fields.
call /payments without billing fields but with card_holder_name
call /payments without billing fields but with card_holder_name
``` …
```
=> fix(connector): [ARCHIPEL] Make card_holder_name as none if cardholder field is none

cypress-tests/cypress/e2e/configs/Payment/Globalpay.js, cypress-tests/cypress/e2e/configs/Payment/Utils.js, cypress-tests/cypress/fixtures/create-connector-body.json
Enhanced Globalpay Connector in cypress for Comprehensive Testing.
**Globalpay**
Note: 1. 3ds payments silently falling back to no-3ds(Should throw validation)
2. All MIT payments are failing with error("Payment methods is not implemented") but in feature matrix globalpay supports mandates
=> ci(cypress): Add Globalpay connector test in cypress

crates/hyperswitch_connectors/src/connectors/jpmorgan.rs, crates/hyperswitch_connectors/src/connectors/jpmorgan/transformers.rs, cypress-tests/cypress/e2e/configs/Payment/Jpmorgan.js
This PR implements refund flow for JPMorgan connector. Connector returns `Authorized` state (`Pending`). Post RSync call, the status gets updated to `Success`.
The connector lacked this basic feature until now. Closes #8435 
Updated Cypress tests:
There exist an issue from the connector where it returns same `transaction_id` (`connector_transaction_id`) every single time which we have no control. Because of this, refunds tend to exceed the maximum refundable amount resulting in 4xx as shown below:
=> feat(connector): [jpmorgan] implement refund flow

crates/hyperswitch_domain_models/src/payments/payment_attempt.rs, crates/router/Cargo.toml, crates/router/src/core/payments.rs, crates/router/src/core/payments/operations/proxy_payments_intent.rs, crates/router/src/routes/payments.rs, crates/router/src/services/authentication.rs
Previously there was no restriction in confirmData to connector request reference id to be mandatory. Recovery internally uses proxy flow, which internally uses confirmData where connector request reference id was hardcoded to none. This Pr adds supports to generate connector request reference to merchant reference id. 
This Pr also has changes of adding support for jwt auth to payment get for dashboard use case. Previously payment sync was used in dashboard to retrieve payment details, but this would fail now in v2 because if there are no attempts created payment get would return 4xx since active attempt is mandotory. To solve this now dashboard is relying on payment get and payment get attempt list api's .
Test case 1 : 
**step 1 :** create a profile in hyperswitch and wait for 8 mins …
=> fix(recovery): Populate connector request reference id in revenue recovery record attempt flow.

crates/api_models/src/payment_methods.rs, crates/diesel_models/src/payment_methods_session.rs, crates/hyperswitch_domain_models/src/payment_methods.rs, crates/router/src/core/payment_methods.rs, crates/router/src/core/payment_methods/vault.rs, crates/router/src/core/payments/operations/payment_confirm_intent.rs
- Save the context of payment_method_id in the session
- Create temporary token for payment_method_id to pass to payment confirm
- Save the cvc as a temporary data against the payment_token to be accessed by payment
- Evict the cvc after first use
- Encrypt/Decrypt the payload for cvc to store in redis
- do confirm with payment_token in payment confirm call
- the relative data are stored temporarily (15 mins) or till the first use
- payment_method_data and cvc are fetch against the payment_token for the payment
payment token are present in payment method session response
```
"associated_payment_methods": [
"token_Dafmj9an9QORtSR2ZUlt"
],
```
Tested through Postman (Hyperswitch v2):
Create a customer:
- curl for customer create
```
curl --location '{{baseUrl}}/v2/customers' \
--header …
```
=> feat(payment-methods): create payment_token in vault confirm / do payment-confirm with temp token from session

crates/router/src/core/payment_methods.rs, crates/router/src/core/payment_methods/vault.rs, crates/router/src/core/proxy.rs, crates/router/src/core/proxy/utils.rs, crates/router/src/core/tokenization.rs, crates/router/src/types/domain.rs, crates/router/src/types/payment_methods.rs
Currently, if payment method data is inserted in vault for customer c1, merchant id is being sent as entity id, this will not allow us to store same payment method data for customer c2.
Payment Method data is always tied to customer, not to merchant.
Hence updated entity id to Global customer id
test case - 
- create a payment method with 4242 card for a customer c1
- create new payment method with 4242 card for a customer c2
Both api should return 200
Initially for a diff customer under same merchant, api is returning duplication error.
with this fix, the api should return 2xx
```
curl --location 'http://localhost:8080/v2/payment-methods' \
--header 'X-Profile-Id: profile id' \
--header 'Authorization: …
```
=> fix(payment_method): update entity id used for Vault to global customer id

crates/router/src/types/domain/user/decision_manager.rs
This PR fixes an issue where a stale `role_id` from the cached `lineage_context` was being used to generate the JWT token during sign-in, even if the actual user role was modified (e.g., role deleted and recreated with a different `role_id` but same lineage).
Previously, we only validated if a user role existed for the lineage (`user_id`, `tenant_id`, `org_id`, `merchant_id`, `profile_id`), but **did not verify that the `role_id` matched** the current assigned role. This led to JWTs being issued with outdated `role_id` values.
- During sign-in, added a strict match check for `role_id` in the fetched user role.
- If the `role_id` from cached `lineage_context` does not match the current role fetched from DB (v2 fallback to v1), we now **resolve the lineage afresh from the current …
=> fix(users): fallback to fresh lineage context if cached role_id no longer matches

crates/external_services/src/grpc_client.rs, crates/external_services/src/grpc_client/dynamic_routing.rs, crates/external_services/src/grpc_client/health_check_client.rs, crates/router/src/core/payments/routing.rs, crates/router/src/core/routing.rs, crates/router/src/core/routing/helpers.rs, crates/router/src/core/unified_connector_service.rs
This pull request introduces changes to improve the handling of optional configurations for dynamic routing in the gRPC client module. The updates include modifying the `GrpcClientSettings` structure to use `Option` types, enhancing error handling, and simplifying connection establishment logic. Additionally, default implementations are added to certain structs to streamline initialization.
* [`crates/external_services/src/grpc_client.rs`](diffhunk://#diff-0129f28e4a26fac6ce00609c3a3542c380baabb72d04d977daa28f364ab319beL50-R51): Changed `dynamic_routing_client` in `GrpcClientSettings` to use `Option<DynamicRoutingClientConfig>` instead of a direct type, allowing for better handling of cases where the configuration might be absent.
* …
=> refactor(dynamic_routing): make the dynamo configs optional

crates/router/src/core/payments/routing.rs, crates/router/src/core/payments/routing/utils.rs
Decision engine does not have the concept of fallback connectors, so we recently added support to handle the default connectors by allowing them to be passed in the evaluate request. As part of this PR we are making the necessary changes to pass fallback connectors to decision engine
On making a payment from hyperswitch, with the routing rules defined and activated already. We will be passing the fallback_output to the decision engine
=> feat(routing): add support to pass fallback connectors to decision engine

crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs, crates/hyperswitch_domain_models/src/router_request_types.rs, crates/router/src/core/payments/types.rs
1. Added   **created_at** (time at which authentication completed) in Authentication Flow
2. Reused **created_at** field from AuthenticationStore, since all 3ds connectors do not send this field in authentication response
3. Used this field  **created_at**  for 3ds external authentication payments for Cybersource.( See ref Pg 460
https://docs.cybersource.com/content/dam/new-documentation/documentation/en/reference/api-fields/api-fields-so.pdf ). Reason for this change - Without this field Visa card payments are currently failing for a france-based merchant acquirer CMCIC in prod for cybersource.
Tested this for both Mastercard card and Visa card, for 3ds external authentication
--header …
=> feat(core): add authentication date in Authentication Flow

cypress-tests/cypress/e2e/configs/Payment/Authorizedotnet.js, cypress-tests/cypress/e2e/configs/Payment/Commons.js, cypress-tests/cypress/e2e/configs/Payment/Utils.js
Add Authorize.net connector to cypress test suite 
Connector tests enhancement
Failure Reason: 
1.3ds payments silently falling back to no-3ds(Should throw validation)
2.Mandates using NTID are working
3.Zero mandates throwing error from the connector
=> ci(cypress): add authorizedotnet connector

crates/hyperswitch_connectors/src/connectors/worldpay.rs, crates/hyperswitch_connectors/src/connectors/worldpay/transformers.rs, crates/router/src/services/api.rs, cypress-tests/cypress/e2e/configs/Payment/Commons.js, cypress-tests/cypress/e2e/configs/Payment/Utils.js, cypress-tests/cypress/e2e/configs/Payment/WorldPay.js, cypress-tests/cypress/e2e/spec/Payment/00030-DDCRaceCondition.cy.js, cypress-tests/cypress/support/commands.js
Fixes race condition in Worldpay 3DS Device Data Collection (DDC) flow causing `bodyDoesNotMatchSchema` errors.
**Changes made:**
- Extended DDC timeout from 8s to 10s in client-side JavaScript
- Added `ddcProcessed` flag to prevent duplicate submissions on client-side
- Reject `collectionReference` submissions when payment is in `AuthenticationPending` state
- Fixed CSS media query syntax (`@media (max-width: 600px)`)
- Added Cypress test case for both client and server-side race conditions for DDC submissions
Race condition caused intermittent 3DS payment failures when DDC took > 8 seconds.
<details>
<summary>1. DDC race case in isolation </summary>
</details>
<details>
<summary>2. All test cases for Worldpay</summary>
Note
- PSync for WP fails due to 404 and WP sending back a HTML …
=> fix(connector): [Worldpay] handle multiple ddc submission for CompleteAuthorize

CHANGELOG.md, crates/router/src/configs/secrets_transformers.rs, crates/router/src/configs/settings.rs, crates/router/src/routes/app.rs, crates/router/src/services/api.rs
This feature allows based on deployment config , it is able to query Request Body and add as a top level fields in the Kafka events
We wanted a feature where we could add fields from Request Body to top level fields in kafka events irrespective of the flow
Test 1
In ```development.toml```
```bash
[enhancement]
"merchant_reference_id" = "txn_uuid"
```
```json
{
"tenant_id": "public",
"merchant_id": "cloth_seller_kGLq5ZsmKL6hISw8HI9A",
"api_flow": "PaymentsCreateIntent",
"created_at_timestamp": 1753767564159,
"request_id": "019854b1-52c2-7080-ab7f-114e169fc92b",
"latency": 170,
"status_code": 200,
"api_auth_type": "api_key",
"authentication_data": {
"merchant_id": "cloth_seller_kGLq5ZsmKL6hISw8HI9A",
"key_id": "dev_ekHYWGqV5It7fLj62AOa"
},
"request": …
```
=> chore(router): events enhancement for kafka

crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs, crates/hyperswitch_domain_models/src/router_request_types.rs, crates/router/src/core/payments/types.rs
Context - Cybersource payments via Netcetera are failing for a France based acquirer in prod, the PR provides fix for the same by introducing field **_consumerAuthenticationInformation. effectiveAuthenticationType_** and making sure **_consumerAuthenticationInformation.specificationVersion** is sent.
**Testing for field effective_authentication_type and specification_version** 
**Curl**
--header 'x-feature: integ-custom' \
--header 'api-key: dev_TSUxfiSwiAelCPTr9xN2ValUdd1fvmeYg0AtMUwdJukRkTlCpHL9p2IWxn6fouYl' \
--data-raw '{
"amount": 2540,
"profile_id": "pro_aKVBsBqyTIq2T1UIaapY",
"amount_to_capture": 2540, …
=> feat(connector): [cybersource] add changes for field CybersourceConsumerAuthInformation

crates/router/src/core/api_keys.rs, crates/router/src/routes/api_keys.rs
- Removed merchant ID from path in `API Keys - Revoke`
- Changed auth to read merchant ID from headers
Closes #8807 
- V1:
Request:
```
curl --location --request DELETE 'http://localhost:8080/api_keys/merchant_1753949938/dev_8Xwp8SIyp0R4ItROu0tR' \
--header 'api-key: test_admin'
```
Response:
```json
{
"merchant_id": "merchant_1753949938",
"key_id": "dev_8Xwp8SIyp0R4ItROu0tR",
"revoked": true
}
```
- V2:
Request:
```
curl --location --request DELETE 'http://localhost:8080/v2/api-keys/dev_DULXUEOAUgYKxuxE7PQN' \
--header 'x-merchant-id: cloth_seller_v2_hFIzh6a4wFsbtEkKYLxD' \
--header 'Authorization: admin-api-key=test_admin' \
--header 'api-key: test_admin'
```
Response:
```json
{
"merchant_id": …
```
=> fix(router): Take merchant ID from headers in API Key - Revoke (v2)

crates/hyperswitch_connectors/src/connectors/netcetera/transformers.rs
Currently we are not recieving field **_three_ds_requestor_challenge_ind_** in Netcetera's authentication response since the struct is incorrectly declared in the transformers file.
1. **_three_ds_requestor_challenge_ind_** is currently a part of _**NetceteraAuthenticationSuccessResponse**_ enum, but it should be a field inside **_authenitcation_request_**
2. **_three_ds_requestor_challenge_ind_** has type optional string currently, but it should be a vector of string (ref documentation - https://3dss.netcetera.com/3dsserver/doc/2.5.2.1/3ds-authentication) 
**Current structure**
```
NetceteraAuthenticationSuccessResponse{
....
three_ds_requestor_challenge_ind: Option<String>
...}
```
**Correct structure**
```
NetceteraAuthenticationSuccessResponse{
....
authentication_request: { …
```
=> fix(connector): [CYBERSOURCE] fix response field for netcetera authentication response

crates/connector_configs/toml/production.toml, crates/hyperswitch_connectors/src/connectors/adyen/transformers.rs
Closes this [issue](https://github.com/juspay/hyperswitch/issues/8845)
This PR updates the reason field in AdyenRefundRequest from Option<String> to Option<AdyenRefundRequestReason>, a strongly typed enum. This change ensures only supported values (FRAUD, CUSTOMER REQUEST, RETURN, DUPLICATE, OTHER) are used.
Postman Test
A. Refund(with valid reason):
Request:
```
--header 'api-key: dev_Emxcc7NEApdtpDZyA54Hc0hN43a4wvBTlJ0wIGGeGquavEbsE4lhVWQcyPV8jMFu' \
--data '{
"payment_id": "pay_aUwRQFUMFVSuIsfGRRiq",
"amount": 100,
"reason": "CUSTOMER REQUEST",
"refund_type": "instant",
"metadata": {
"login_date": …
```
=> fix(connector): Change Refund Reason Type in Adyen

crates/redis_interface/src/commands.rs, crates/redis_interface/src/lib.rs, crates/redis_interface/src/types.rs, crates/router/src/core/api_locking.rs, crates/router/src/routes/payments.rs
added support for api locking with multiple keys for a single api.
* introduced a couple of redis interface commands to support this feature.
Redis commands unit test result:
Parallel payments-create script output:
before this change:
after this change:
<details>
This script will make n number of parallel payment create calls with same customer id.
<summary>Click to expand script</summary>
```shell
#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
print_color() {
local color=$1
local message=$2
echo -e "${color}${message}${NC}"
}
show_usage() {
echo "Usage: $0 <num_requests> <api_key> <profile_id> [endpoint_url]"
echo ""
echo "Arguments:"
echo "  num_requests  - Number of parallel requests to make (positive integer)"
echo " …
```
=> feat(core): add support for api locking with multiple keys for a single api

crates/router/src/core/payment_link/locale.js
We need to update traditional chinese locale for payment link expired.
Raised by the merchant to update the locale to the correct one as shared by them.
use below curl for payment link create and wait for 60 secs for payment link to get expired:
```
--header 'api-key: ***' \
--header 'Accept-Language: zh-Hant' \
--data '{
"amount": 10,
"session_expiry": 60,
"theme": "#14356f",
"logo": "https://logo.com/wp-content/uploads/2020/08/zurich.svg",
"seller_name": "Zurich Inc."
}
}'
```
=> feat(payment-link): update traditional chinese local

crates/router/src/core/payments/routing/utils.rs
This PR refactors the Euclid routing parameter transformation logic to **include sub-variants of payment method types** in the Decision Engine evaluation request.  
Key updates:
- Added logic to **convert `(payment_method_type, payment_method)` pairs** into a `DirValue` representation.
- Introduced `insert_dirvalue_param()` to map each `DirValue` variant into a corresponding routing parameter key.
- Enhanced `convert_backend_input_to_routing_eval` to insert these sub-variant parameters alongside existing routing parameters.
- This ensures richer context is sent to Euclid for more granular routing decisions.
- Enables **finer-grained routing rules** based on payment method sub-types (e.g., `WalletType`, `CryptoType`, `GiftCardType`).
- Improves compatibility with dashboard-configured …
=> refactor(euclid): transform enum types to include sub-variants of payment method types

crates/hyperswitch_connectors/src/connectors/nmi.rs
the problem is that we previously extracted `nonce` instead of `signature` and entire regex match instead of `nonce`. this pr fixes webhook source verification for nmi connector by properly extracting `signature` (`2`) and `nonce` (`1`) values.
check attached issue for detailed explanation.
webhook source verification must not be `false` unless connector does not support it. in this case, it was a mistake from our end where we parsed wrong values.
closes https://github.com/juspay/hyperswitch/issues/8945
<details>
<summary>Setup webhooks for NMI connector and also the signature verification</summary>
</details>
<details>
<summary>Make a Payment</summary>
```curl
curl --location 'https://pix-mbp.orthrus-monster.ts.net/payments' \ …
```
=> fix(connector): [nmi] webhook source verification

crates/redis_interface/src/commands.rs, crates/redis_interface/src/lib.rs, crates/redis_interface/src/types.rs, crates/router/src/core/api_locking.rs, crates/router/src/routes/payments.rs
This reverts commit 2f7cd4f752d98e23910c37502d8748e9842682ef.
reverted this commit: 2f7cd4f752d98e23910c37502d8748e9842682ef
=> revert: feat(core): add support for api locking with multiple keys for a single api

crates/api_models/src/events/user_role.rs, crates/api_models/src/user_role/role.rs, crates/common_enums/src/enums.rs, crates/router/src/core/user_role.rs, crates/router/src/core/user_role/role.rs, crates/router/src/routes/app.rs, crates/router/src/routes/lock_utils.rs, crates/router/src/routes/user_role.rs, crates/router/src/services/authorization/permission_groups.rs, crates/router/src/utils/user_role.rs, crates/router_env/src/logger/types.rs
- Creates a role using `parent_groups` (with `name` + `scopes`) instead of granular `groups`.
- Internally maps `parent_groups` + `scopes` to existing granular permissions for DB storage.
- Replicates existing `/user/role/list` functionality but replaces the `groups` field with a `parent_groups` array containing:
- `name`
- `description`
- `scopes`
- Added entity_type filter for current parent/list which used to take user role entity_type.
We are standardizing all role-related APIs (/role/list, /role/v2) to use parent group + scopes rather than granular permissions like we use in the Invite api.
Improves readability for FE consumers and ensures consistency across role creation and retrieval.
1. Create Custom Role
Request:
```
curl --location 'http://localhost:8080/user/role/v2' \
--header …
```
=> refactor(user_roles): implement parent group info based role APIs

crates/redis_interface/src/commands.rs, crates/redis_interface/src/lib.rs
added support for fetching multiple keys for redis cluster.
Earlier, we were using `mget` to fetch multiple keys. While this works fine for standalone redis, it would fail for redis cluster(it won't work if redis keys are stored in multiple hash slots).
So, introduced a new redis interface function to use `mget` for standalone redis and parallel `get` calls for cluster redis.
test cases same as this PR: https://github.com/juspay/hyperswitch/pull/8887
Tested in an internal environment with redis cluster setup enabled.
=> fix(redis): add support for fetching multiple keys for redis cluster

api-reference/v2/openapi_spec_v2.json, crates/api_models/src/payments.rs, crates/router/src/core/payments/transformers.rs
- Add `payment_type` to Payments Get Intent response
Closes #9065 
Request:
```
curl --location 'http://localhost:8080/v2/payments/create-intent' \
--header 'api-key: dev_5DkqRwXafcKhIFXyzwGtSjrnqsQuFWELuWJsepMgoRrjY1AxF7lhtNGeeja9BEHt' \
--header 'x-profile-id: pro_RAH6QGkLhuQfmi97QhPZ' \
--header 'Authorization: api-key=dev_5DkqRwXafcKhIFXyzwGtSjrnqsQuFWELuWJsepMgoRrjY1AxF7lhtNGeeja9BEHt' \
--data-raw '{
"amount_details": {
"order_amount": 1000,
"currency": "USD"
},
"order_details": [
{
"product_name": "Apple iphone 15",
"quantity": 1,
"amount": 1000
}
],
"billing": {
"address": { …
```
=> feat(router): Add payment_type to Get Intent response (v2)

crates/hyperswitch_connectors/src/connectors/stripe/transformers.rs, crates/hyperswitch_connectors/src/utils.rs, crates/hyperswitch_domain_models/src/router_data.rs
Extend stripe integration to support extended authorization
We cannot test this feature  until it is enabled by stripe
Sanity Test - cypress ran on the PR
=> feat(connectors): [Stripe] add extended authorization for cards

crates/router/src/services/openidconnect.rs
Added a BadRequest response for SSO login when an invalid authorization code is provided.
Currently, when users provide an invalid or expired code during SSO login, the system returns a 500 response. This is misleading, as the issue is with the client input rather than a server error. This change introduces a proper 400 BadRequest response to better reflect the actual problem and improve error handling.
```sh
curl --location '<BASE URL>/user/oidc' \
--data '{
"state": "<correct state>",
"code": "<wrong code>"
}'
```
This should give `400` instead of 500.
=> fix(users): add bad request for openidconnect

crates/hyperswitch_connectors/src/connectors/chargebee.rs, crates/hyperswitch_connectors/src/connectors/chargebee/transformers.rs, crates/hyperswitch_connectors/src/connectors/recurly.rs, crates/hyperswitch_connectors/src/connectors/recurly/transformers.rs, crates/hyperswitch_connectors/src/connectors/stripebilling.rs, crates/hyperswitch_connectors/src/connectors/stripebilling/transformers.rs, crates/hyperswitch_connectors/src/default_implementations.rs, crates/hyperswitch_connectors/src/default_implementations_v2.rs, crates/hyperswitch_domain_models/src/router_data_v2/flow_common_types.rs, crates/hyperswitch_domain_models/src/router_flow_types/revenue_recovery.rs, crates/hyperswitch_domain_models/src/router_request_types/revenue_recovery.rs, crates/hyperswitch_domain_models/src/router_response_types/revenue_recovery.rs, crates/hyperswitch_domain_models/src/types.rs, crates/hyperswitch_interfaces/src/api/revenue_recovery.rs, crates/hyperswitch_interfaces/src/api/revenue_recovery_v2.rs, crates/hyperswitch_interfaces/src/conversion_impls.rs, crates/hyperswitch_interfaces/src/types.rs, crates/router/src/core/payments/flows.rs, crates/router/src/core/revenue_recovery/types.rs, crates/router/src/services/api.rs, crates/router/src/types.rs
Make the RevenueRecoveryRecordBack functionality generic to make it usable by subscription after making a successful payment.
This pull request refactors the "record back" functionality in the revenue recovery flow by renaming types and data structures from RevenueRecoveryRecordBack* and RecoveryRecordBack to InvoiceRecordBack* and InvoiceRecordBack. This change is applied consistently across domain models, connector implementations, interfaces, and transformers, improving clarity and aligning naming with their purpose (handling invoice record backs).
Only removing the feature flag and renamed it. compilation and PR checks should be sufficient
=> refactor(connector): rename RevenueRecoveryRecordBack as InvoiceRecordBack

.github/workflows/migration-check.yaml
- `diesel_cli` version `2.3.0` expects to call `rustfmt` to format its output. If `rustfmt` is not installed on the system it will give an error.
- Added a step to install `rustfmt` to fix the workflow
Closes #9385 
Verified CI checks
=> ci(migration-check): install rustfmt to address migration run failures

.github/CODEOWNERS
This PR assigns the code owner to relevant modules for `hyperswitch-payouts`.
- Helps offload PR review tasks for payout related modules to the respective team.
Not needed
=> chore(git): add code owner for payout modules

cypress-tests/cypress/e2e/configs/Payment/Braintree.js
Fix save card flow for braintree , earlier we were passing on_session for off_session flow 
Test cases were failing
=> ci(cypress): fix braintree connector

crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs
This PR introduces the following fix:
HS should pass `paymentInformation.tokenizedCard.transactionType`  for only wallet MITs. Presently `paymentInformation.tokenizedCard.transactionType` is being passed for card MITs as well, which is incorrect according to cybersource docs.
1. Test MIT for connector mandate flow via Cybersource for cards, and check router logs. 
`paymentInformation.tokenizedCard.transactionType` should not be present.
Logs from localhost:
2. Test MIT for setup mandate flow via Cybersource for cards, and check router logs. `paymentInformation.tokenizedCard.transactionType` should not be present. 
Logs from localhost:
=> fix(connector): [CYBERSOURCE] Pass transaction type for only wallet MITs

crates/common_utils/src/consts.rs, crates/injector/src/vault_metadata.rs, crates/router/src/core/errors.rs, crates/router/src/core/webhooks/outgoing.rs, crates/router/src/core/webhooks/outgoing_v2.rs, crates/router/src/core/webhooks/utils.rs, crates/router/src/core/webhooks/webhook_events.rs, crates/router/src/workflows/outgoing_webhook_retry.rs
This change updates the idempotent_event_id generation to first hash the base string with SHA256 and then encode it using URL-safe Base64 without padding. By doing this, the generated IDs are guaranteed to be short and deterministic, ensuring they always fit within the 64-character database column limit. This fix addresses the issue where long payment_ids combined with event types were exceeding the DB constraint and breaking the outgoing webhooks flow.
The idempotent_event_id column is a combination of payment_id and event_type. The DB column length is limited to 64 characters. Since payment_id itself can be up to 64 characters long, appending event_type causes the field to exceed the limit, leading to database constraint violations.
Currently, this breaks the outgoing webhooks flow. …
=> fix(webhooks): add idempotent_event_id generation using URL-safe Base64 (no padding) and SHA256 digest

crates/connector_configs/toml/development.toml, crates/connector_configs/toml/production.toml, crates/connector_configs/toml/sandbox.toml
This PR updates the payout MCA creation to use `sepa_bank_transfer` instead of `sepa`.
Fixes issue #8168 during payout creation
Needs to be tested from dashboard
=> chore(wasm): update sepa to sepa_bank_transfer for payout MCAs

config/deployments/integration_test.toml
Enable L2l3 config for integ
NO test needed. Just enabling config
=> fix(l2l3): enable l2l3 for integ

api-reference/v2/openapi_spec_v2.json, crates/api_models/src/payments.rs, crates/openapi/src/openapi_v2.rs
- Added `split_payment_method_data` field to `confirm-intent` call to accept a `Vec` of payment methods
Closes #9467 
Note: Currently the `split_payment_method_data` field is not used. This PR just adds it to the API contract. There are no behaviour changes. The field will be used in a future PR.
Request:
```
curl --location 'http://localhost:8080/v2/payments/12345_pay_019975b06d2d77b0beff1a83df9a3377/confirm-intent' \
--header 'x-profile-id: pro_JSAAWLeyardnZ5iQDB4o' \
--header 'x-client-secret: cs_019975b06d407b738bb37971ce338246' \
--header 'Authorization: publishable-key=pk_dev_e098d9545be8466a9e52bfd7db41ec77,client-secret=cs_019975b06d407b738bb37971ce338246' \
--header 'api-key: pk_dev_e098d9545be8466a9e52bfd7db41ec77' \
--data '{ …
```
=> feat(router): Add Confirm-Intent API contract changes for split payments (v2)

crates/hyperswitch_connectors/src/connectors/authorizedotnet/transformers.rs
- RELATED PR : https://github.com/juspay/hyperswitch/pull/9581
- Refunds via authorizedot net are getting into `pending` state where no connector call is made
- This happens when `connector_metadata` is empty in attempt table
- In usual cases `connector_metadata` is not empty but this happened via ucs.
- `connector_metadata` contains last4 digits which can be fetched form payment_method_data
- make payment from old code , delete connector metadata in attempt table and make refund
1.  make payment
```json
{
"amount": 689,
"customer_id": "hello_world", …
```
=> fix(authorizedotnet): refund via ucs missing connector_metadata
