juspay/hyperswitch

- crates/router/src/connector/wise/transformers.rs
Fields that are deserialized are made optional based on whether Wise sends it or if it is needed to be stored
```
{
"address": {
//   "line1": "1467",
//   "line2": "Harrison Street",
//   "line3": "Harrison Street",
//   "city": "San Fransico",
//   "state": …
```
> refactor(connector): [Wise] Response Fields made Optional 

- crates/router/src/connector/stripe.rs
- crates/router/src/connector/stripe/transformers.rs
Fixes https://github.com/juspay/hyperswitch/issues/4090
Create a stripe Card Payment Request
```
{
"card": {
}
},
"billing": {
"address": { …
```
> refactor(connector): [Stripe] add stripe-api-version in API-headers

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
The payment response will also address the `ACCEPTED` and `CANCELLED` payment status from connectors Bankofamerica and Cybersource.
https://github.com/juspay/hyperswitch/issues/4106
Testing can be done by creating a recurring payment of 2USD using a Zero Auth Mandate in Cybersource.
1. Payments Intent Create:
Request: 
```
--data-raw '{
"amount": 0,
"order_details": null,
"customer_id": "cut2",
"email": "johndoe@gmail.com",
"description": "Hello this is description",
"billing": {
"address": {
"line2": …
```
> feat(connector): [BOA/CYB] Add support for payment status ACCEPTED and CANCELLED

- crates/router/src/connector/stripe/transformers.rs
Field called `name` in stripe Shipping address is not optional at the stripe's end. This PR makes it a mandatory field.
```
--header 'api-key:{{}}' \
--data-raw '{
"amount": 7000,
"billing": {
"address": { …
```
> refactor(connector): [Stripe] make name field of StripeShippingAddress mandatory

- crates/router/src/connector/stripe/transformers.rs
Fixes https://github.com/juspay/hyperswitch/issues/4121
Stripe supports multiple api versions and each stripe merchant account has its own default api version based on the time the account has created. So whenever Hyperswitch calls stripe API, stripe will respond based on merchant's default version which might differ from the version which Hyperswitch has implemented. The current API version is not the compatible with our implementation. So we need to update the version according to current implementation.
1. Run whole Stripe Postman collection
2. Create a stripe Card Payment Request
```
{
"email": …
```
> refactor(connector): [Stripe] update stripe-api-version in API-headers

- crates/router/src/core/payments/operations/payment_response.rs
Original PR - https://github.com/juspay/hyperswitch/pull/4149
> fix(payment_methods): update payment method status only if existing status is not active

- .github/ISSUE_TEMPLATE/config.yml
- README.md
- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
- config/docker_compose.toml
- docs/CONTRIBUTING.md
- loadtest/config/development.toml
This PR updates the Slack workspace URL across the entire repository.
The previous link no longer works.
N/A
> chore: update Slack workspace URL

- .github/workflows/hotfix-pr-check.yml
- .github/workflows/pr-convention-checks.yml
Currently backticks in hotfix pr title is not being parsed resulting in hotfix-pr-check workflow failing. This PR updates the workflow to store pr title in env and make use of it. 
Failing CI check (example) - https://github.com/juspay/hyperswitch/actions/runs/8359058549/job/22884641822
This PR also updates conventional check workflow to store commit message in env
> CI: update hotfix pr check workflow to parse backticks in pr title

- crates/router/src/connector/trustpay.rs
- crates/router/src/connector/trustpay/transformers.rs
- fix deserialization error for incoming webhook response for trustpay 
made `Code` as optional field
- add error code mapping '800.100.203'
PR raised against main - #4199
No testing can be done since it matches error code in production which cant be replicated
> fix(connector): [Trustpay] fix deserialization error for incoming webhook response for trustpay and add error code mapping '800.100.203'

- crates/router/src/connector/cryptopay/transformers.rs
ORIGINAL PR: https://github.com/juspay/hyperswitch/pull/4205
Serialization of the metadata field in the payments request for cryptopay is skipped if the metadata is set to none.
https://github.com/juspay/hyperswitch/issues/4206
Testing can be done by creating a payment on cryptopay without passing metadata.
Request:
```
--data-raw '{
"amount": 120,
"customer_id": "custo", …
```
> fix(connector): [CRYPTOPAY] Skip metadata serialization if none

- crates/router/src/connector/trustpay/transformers.rs
Error mapping done to code `800.100.100`
No testing can be done since it matches error code in production which cant be replicated
> fix(trustpay): [Trustpay] Add error code mapping '800.100.100' 

- crates/api_models/src/payments.rs
- crates/router/src/core/payment_link.rs
- crates/router/src/core/payment_link/payment_link_initiate/payment_link.html
- crates/router/src/services/api.rs
Add payment info metadata to payment link for customer 
we are adding seller_name from payment_link_config and description from payment description
```
"seller_name": "bernard",
},
"description": "Please Pay for your XYZ"
```
Created payment-link ->  copy pasted the payment-link in slack to check metadata popup.
```shell
curl --location 'https://54d0-2409-40f2-31-6a41-1194-fe61-26bc-f98a.ngrok-free.app/payments' \
--header 'api-key: dev_5XCNlDivDdjrMhW66UNB4MYGIuDaeweOfOdaHmBupTBUEFIv7Pll0HGoIaEQTGB0' \
--data-raw '{
"amount": 250,
"amount_to_capture": 250, …
```
> feat(payment_link): Add payment info metadata to payment link

- crates/router/src/core/payment_methods/vault.rs
Instead of converting payout_method_data to payment_method_data to save in temp locker, we extract the required fields to save.
Create MCA (Adyen):
```
{
"connector_type": "payout_processor",
"connector_name": "adyen",
"api_key": "{{api_key}}",
"key1": "{{key1}}",
"api_secret": "{{api_secret}}"
},
{
{
"Visa",
"Mastercard"
],
},
{
"Visa",
"Mastercard"
], …
```
> refactor(payout): Handle saving wallet in temp locker

- crates/router/src/connector/stripe/transformers.rs
This PR fixes typos caught from the new version of typos-cli 
Local sanity testing
> refactor: fix typos in stripe transformers

- crates/router/src/connector/stripe/transformers.rs
Add Support for Google Pay recurring Payments for Stripe Connector
TESTING WITH `PAYMENT_METHOD_ID`
1. Create a CIT Gpay Payment vai Stripe
```
{
"payment_method_type": "google_pay",
"wallet": {
"google_pay": {
"type": "CARD",
"description": "Visa •••• 1111",
"info": {
"card_network": "VISA",
"card_details": "1111"
},
"tokenization_data": { …
```
> refactor(connector): add support for GooglePay recurring payments 

- crates/api_models/src/payouts.rs
- crates/data_models/src/payouts/payouts.rs
- crates/diesel_models/src/payouts.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/core/payouts.rs
- crates/router/src/core/payouts/helpers.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/routes/payouts.rs
- crates/storage_impl/src/mock_db/payouts.rs
- crates/storage_impl/src/payouts/payouts.rs
- openapi/openapi_spec.json
refactor(payouts): populate customer fields in list response
This PR fixes below payout related **BUGS**
- Customer related fields are not populated
- Status is not persisted in `payouts` table
This is to be used for listing payouts, and it needs to work as expected!
Tested locally using postman.
<details>
<summary>View request</summary>
curl --location 'http://localhost:8080/payouts/list?limit=4' \
--header 'api-key: dev_wmZ4BwC6pXMpBZs3kHlEHAbAxQevfCfJvEESnNmpm7eGlRlNH3yqWCjH58Q87Vfm'
</details>
<details>
<summary>View response</summary>
{
"size": 4,
"data": [
{
"payout_id": "c353a893-a0a6-4be4-849e-a328264b8509",
"merchant_id": "merchant_1712111780",
"connector": "wise",
"billing": null,
"customer_id": …
> fix(payouts): persist status updates in payouts table

- crates/router/src/routes/routing.rs
Add support for api-key auth for `pg_agnotic` config api enpoint.
```
curl --location 'http://localhost:8080/routing/business_profile/{{business_profile_id}}/configs/pg_agnostic_mit' \
--header 'api-key: api-key' \
--data '{
"enabled": true
}'
```
> feat(router): add  `ApiKeyAuth` support for `upsert_connector_agnostic_mandate_config`

- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
Base url was missing for Zsl connector for prod, sandbox and integ env
No testing required
> fix(connector): [ZSL] Add base_url to Environments

- crates/router/src/db/payment_method.rs
- [ x] Bugfix
revert payment method kv changes due to entity not found issue
> fix: revert payment method kv changes

- crates/router/build.rs
Refactor Stack Size
- No test required
> refactor(router): change stack size

- crates/router_env/src/logger/setup.rs
> fix(logger): use specified log level only for first-party crates

- config/config.example.toml
- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
- config/docker_compose.toml
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
1. Create a merchant 
```
--header 'api-key: "" ' \
--data-raw '{
"merchant_id": "merchant_1712909275",
"return_url": "https://chrome.google.com/",
"enable_payment_response_hash": false,
"payment_response_hash_key": null,
"redirect_to_merchant_with_http_post": false,
"primary_contact_person": "joseph Test",
"primary_phone": "veniam aute officia ullamco esse",
"primary_email": "josephTest@test.com",
"secondary_contact_person": "joseph Test2",
"secondary_phone": "proident adipisicing officia nulla",
"secondary_email": "josephTest2@test.com",
"about_business": …
```
>  chore(configs): [Zsl] Add configs for wasm 

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/bluesnap/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
- crates/router/src/connector/forte/transformers.rs
- crates/router/src/connector/multisafepay/transformers.rs
- crates/router/src/connector/nmi/transformers.rs
- crates/router/src/connector/nuvei/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/connector/volt/transformers.rs
More details can be found in #4360 
Same set of test cases as found on #4360
> fix(address): use first_name if last_name is not passed

- crates/router/src/configs/defaults.rs
1. Create a merchant
```
--header 'api-key: "" ' \
--data-raw '{
"merchant_id": "merchant_1712920458",
"return_url": "https://chrome.google.com/",
"enable_payment_response_hash": false,
"payment_response_hash_key": null,
"redirect_to_merchant_with_http_post": false,
"primary_contact_person": "joseph Test",
"primary_phone": "veniam aute officia ullamco esse",
"primary_email": "josephTest@test.com",
"secondary_contact_person": "joseph Test2",
"secondary_phone": "proident adipisicing officia nulla",
"secondary_email": "josephTest2@test.com",
"about_business": "Online …
```
>  feat(pm_list): add dynamic fields for local bank transfer

- cypress-tests/cypress/e2e/ConnectorTest/00003-NoThreeDSAutoCapture.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00004-ThreeDSAutoCapture.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00005-NoThreeDSManualCapture.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00006-VoidPayment.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00007-SyncPayment.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00008-RefundPayment.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00009-SyncRefund.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00010-CreateSingleuseMandate.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00011-CreateMultiuseMandate.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00012-ListAndRevokeMandate.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00013-SaveCardFlow.cy.js
- cypress-tests/cypress/e2e/ConnectorTest/00014-ZeroAuthMandate.cy.js
- cypress-tests/cypress/e2e/ConnectorUtils/Adyen.js
- cypress-tests/cypress/e2e/ConnectorUtils/BankOfAmerica.js
- cypress-tests/cypress/e2e/ConnectorUtils/Bluesnap.js
- cypress-tests/cypress/e2e/ConnectorUtils/Cybersource.js
- cypress-tests/cypress/e2e/ConnectorUtils/Nmi.js
- cypress-tests/cypress/e2e/ConnectorUtils/Paypal.js
- cypress-tests/cypress/e2e/ConnectorUtils/Stripe.js
- cypress-tests/cypress/e2e/ConnectorUtils/Trustpay.js
- cypress-tests/cypress/fixtures/confirm-body.json
- cypress-tests/cypress/fixtures/create-confirm-body.json
- cypress-tests/cypress/fixtures/create-connector-body.json
- cypress-tests/cypress/fixtures/create-mandate-cit.json
- cypress-tests/cypress/fixtures/create-payment-body.json
- cypress-tests/cypress/fixtures/save-card-confirm-body.json
- cypress-tests/cypress/support/commands.js
Added the save card flow scenario and Zero auth mandate  flow in cypress for Stripe, Adyen, BankofAmerica, Cybersource, Bluesnap, Paypal, Nmi, Trustpay.
To run the testcases in cypress use below command:
`CYPRESS_CONNECTOR="stripe" npm run cypress:ci `
To run particular folder use the below command
`npm run cypress:ci -- --spec "cypress/e2e/ConnectorTest/00000-AccountCreate.cy.js"`
> ci(cypress): Add save card flow

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/sandbox.toml
Add feature for extended 3DS
No testing required
> feat(euclied_wasm): [NMI] Add configs for extended 3DS

- crates/connector_configs/src/connector.rs
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/sandbox.toml
added wasm toml configs for netcetera authnetication connector
Wasm build was successful.
> chore: add wasm toml configs for netcetera authnetication connector

- crates/connector_configs/src/connector.rs
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/sandbox.toml
add wasm changes for pull_mechanism_enabled config for 3dsecureio connector
> chore(configs): add wasm changes for pull_mechanism_enabled config for 3dsecureio connector

- crates/router/src/core/payment_link/payment_link_initiate/payment_link.js
- crates/router/src/core/payment_methods/cards.rs
list saved payment method customer is not working for payment link. 
#1 : with enabled_saved_payment_method as false
```shell
--header 'api-key: snd_oaidL49hiU3HmQRKSBsASyb1yANBmLJQJoDsulQbkSuZQiO7xQTj6ks0Alhtr3fD' \
--data '{
"amount": 1130,
"customer_id": "sahkal123",
"return_url": "https://hyperswitch.io",
"seller_name":"Jiverson OU",
"display_sdk_only":true,
"enabled_saved_payment_method":false
}
}'
```
#2. With enabled_saved_payment_method as true
```shell …
```
> refactor(router): enable saved payment method for payment link bug fix

- crates/euclid/src/dssa/analyzer.rs
- crates/euclid/src/frontend/dir.rs
- crates/kgraph_utils/src/mca.rs
This PR fixes failing unit tests for routing, either by updating outdated tests, or resolving code discrepancies. See #4437 for more info on failing tests.
All unit tests pass locally. Does not require any API tests.
> fix(routing/tests): fix unit tests for routing

- crates/api_models/src/payments.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/utils.rs
- crates/router/src/types/domain/payments.rs
- openapi/openapi_spec.json
This PR includes changes to use  `payment_method_data.billing.first_name` ,`payment_method_data.billing.last_name` ,`payment_method_data.billing.phone.number` and `payment_method_data.billing.email` instead of `payment_method_data.[Voucher->AlfamartVoucherData].{first_name,last_name_email}` , `payment_method_data.[Voucher->IndomaretVoucherData].{first_name,last_name_email}` and `payment_method_data.[Voucher->JCSVoucherData].{first_name,last_name_email,phone_number}`at the connector level. The backwards compatibility is provided.
1. Create a Boleto Payment Request via Adyen
```
{
"profile_id": "{{payment_profile_id}}",
"amount_to_capture": 2000,
"customer_id": …
```
> refactor(voucher): remove billing details from voucher pmd

- cypress-tests/readme.md
In this PR, I have updated the README file to include detailed information about Cypress test scenarios and the folder structure . 
Added detailed instructions for adding new test scenarios to the ConnectorTest directory.
Included a clear explanation of the folder structure, guiding contributors on where to find specific files and directories related to Cypress tests.
Emphasized the importance of writing clear test scenarios using Cypress commands for effective testing.
By providing a descriptive title and detailed description, reviewers can quickly understand the purpose of the changes and ensure that the README file enhancements align with the project's goals and standards.
This update aims to improve the documentation for contributors and provide a clearer understanding of the testing …
> docs(cypress): Update Cypress README Documentation

- crates/router/src/connector/cryptopay.rs
- crates/router/src/connector/cryptopay/transformers.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/bambora.rs
- crates/router/tests/connectors/forte.rs
- crates/router/tests/connectors/nexinets.rs
- crates/router/tests/connectors/paypal.rs
- crates/router/tests/connectors/utils.rs
- crates/router/tests/connectors/zen.rs
During settlement, payments processed through the Cryptopay connector may experience underpayment or overpayment, leading to fluctuations in the payment amount. The revised amount must be communicated through outgoing webhooks for the respective payment.
The new `price_amount` should be populated in `amount_captured` field.
https://github.com/juspay/hyperswitch/issues/4467
We need to check for the `amount_received` in outgoing webhook for underpaid/overpaid payments via cryptopay. The `amount_received` should be equal to the `invoice amount` on cryptopay dashboard for that payment.
In order to generate an underpaid/overpaid one must let the 10 min timer runout (on the redirection screen) and then only complete the payment.
Request:
``` …
```
> feat(connector): [CRYPTOPAY]  Report underpaid/overpaid amount in outgoing webhooks

- crates/router/src/connector/riskified/transformers/api.rs
- crates/router/src/connector/signifyd/transformers/api.rs
- crates/router/src/core/fraud_check/flows/transaction_flow.rs
- crates/router/src/core/fraud_check/operation/fraud_check_pre.rs
- crates/router/src/core/fraud_check/types.rs
- crates/router/src/types/fraud_check.rs
Signifyd has three types of request fields : Required, Needed and optional. Initial integration has been done only passing required fields. This PR adds needed fields, which helps Signifyd to improve its data model for fraud detection.
Test case 1 : Process a signifyd preAuth legit payment. It should trigger transaction call by itself. Transaction `raw_connector_request` in logs should contain `gateway` field.
Test Case 2 : Process signifyd  PostAuth and then fulfillment the payment. Fulfillment logs should contain below all fields that are being passed in request. 
fulfillment request : 
```
{
"payment_id": "{{payment_id}}",
"order_id": "{{payment_id}}_1",
"fulfillments": [
{
"shipment_id": "{{$randomUUID}}",
"destination": {
"full_name": "Bob Smith",
"organization": "Initrode plc", …
```
> feat(FRM): add shipping details for signifyd

- cypress-tests/readme.md
Updates the documentation for the changes done in https://github.com/juspay/hyperswitch/pull/4430.
To address security concerns, the file i.e., `example.creds.json` has been made `read_only`.
https://github.com/juspay/hyperswitch/pull/4430
Tested in https://github.com/juspay/hyperswitch/pull/4430
> docs(cypress): update cypress docs

- crates/connector_configs/src/connector.rs
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/sandbox.toml
Added configs for the following payouts connector: Cybersource, Ebanx and Paypal
Must be tested through dashboard.
Following things should be available in the dashboard with given connectors:
- Cybersource: Cards
- Ebanx: Pix
- Paypal: Paypal & Venmo
> feat(euclid_wasm): Add configs for new payout connectors

- crates/router/src/consts/user.rs
- crates/router/src/types/domain/user.rs
Reverts juspay/hyperswitch#4489
> fix(users): Revert add password validations

- config/config.example.toml
- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
- config/docker_compose.toml
- crates/router/src/configs/settings.rs
> fix(payment_methods): fix deserialization errors for `sdk_eligible_payment_methods`

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
Add support for CNY currency for Evoucher Payment Method for Cashtocode connector
> feat(connector-configs): [Cashtocode] add CNY currency for evoucher 

- crates/router/src/db.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/routes/app.rs
Add TenantId field to the KafkaStore struct
#4496 
- Add TenantId field to the KafkaStore struct
- Add the tenant_id parameter to the constructor of Kafkastore 
- no testable changes except CI checks
> refactor(db): Add TenantId field to the KafkaStore struct

- crates/router/src/consts.rs
- crates/router/src/core/user.rs
- crates/router/src/types/domain/user.rs
This PR fixes the following bugs:
- Password without special characters is not throwing parsing failed error.
- Signup is not populating the `last_password_modified_at`.
- Verify email is blacklisting all email tokens.
- If the SPT token time is less than JWT time, some SPTs issued after that blacklist are not working.
Closes #4606.
- To check the password validation
```
--data-raw '{
"email": "unregistered email",
}'
```
- If the password is valid, then you will get the following response
```
{
"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiM2MwOTBiMDYtYWY2ZS00MDk0LTgwYzktMWEzOTlkOTQ2MjBjIiwicHVycG9zZSI6InRvdHAiLCJvcmlnaW4iOiJzaWduX2luIiwiZXhwIjoxNzE1MzM …
```
> fix(users): Fix bugs caused by the new token only flows

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
We faced wrong de-serialization of Rsync response struct due to missing `cancelled` status
Sanity test
1. Create a payment with BOA
```
--header 'api-key: ""' \
--data-raw '{
"amount": 100,
"customer_id": "A",
"billing": {
"address": { …
```
> Fix(connector): [BOA/CYBS] add cancelled status to refund response 

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
- crates/router/src/consts.rs
- crates/router/src/core/refunds.rs
Populate adequate error_message and error_reason for refunds, whenever connector response contains this information.
This PR also marks refund as failure when encountered with rsync 2xx  error 
A) BOA Void Refund
1. Create a BOA payment with cards
```
--header 'api-key: ""' \
--data-raw '{
"amount": 100,
"customer_id": "A",
"billing": …
```
> refactor(connector): [BOA/CYBS] refund error handling

- crates/api_models/src/payment_methods.rs
- crates/openapi/src/routes/payment_method.rs
- crates/router/src/core/payment_methods/cards.rs
- openapi/openapi_spec.json
This PR updates the api contract for payment methods update endpoint and removes few unused fields. This PR adds the missing client secret validation for update endpoint
`/payment_methods/:id/update` endpoint have to be tested 
1. Create a customer
```
curl --location 'http://localhost:8080/customers' \
--header 'api-key: dev_kxFm2YwE2I8srj4W96v9C5XkZl8VputfqADhqdumTgJFLpuXpgU5I2NlTHOM3ply' \
--data-raw '{
"name": "new_cus",
"description": "First customer",
"address": { …
```
> refactor(payment_methods): update api contract for update payment method endpoint

- .github/CODEOWNERS
> ci(CODEOWNERS): add hyperswitch-qa as code owners of cypress-tests directory

- crates/api_models/src/payments.rs
remove the shipping and billing parameter fields if null for apple pay and google pay.
-> Apple pay payment create with confirm false
```
{
"amount": 650,
"billing": {
"address": {
"line2": …
```
> refactor(session_flow): remove the shipping and billing parameter fields if null for apple pay and google pay

- crates/storage_impl/src/redis/kv_store.rs
there are some entries created with updated_by as '' for payment_attempt, which is causing decide storage scheme to select the configured scheme which is an issue during soft kill with configured scheme as redis_kv as we want db entities to be processed in db
there are some entries created with updated_by as '' for payment_attempt, which is causing decide storage scheme to select the configured scheme which is an issue during soft kill with configured scheme as redis_kv as we want db entities to be processed in db
`select created_at , updated_by from payment_attempt where updated_by = '' order by created_at desc limit 100`
> fix: added hget lookup for all updated_by existing cases

- crates/router/src/core/payments/operations/payment_confirm.rs
The token based MIT payments were throwing a 5xx , as this [PR](https://github.com/juspay/hyperswitch/pull/4711) called locker every time as a fallback while trying to decrypt the card . This PR fixes the failing token based MIT payments
-Create a MA and a MCA
- Create a off_session payment , with google pay token
- Create another recurring payment via google pay
>
```
--header 'api-key: dev_QEGuyQGnDNOXysqCH4yETBv5kLrF9Nk0cktqhVcnxEutsoJQZkAlmeQ4rITJHTI5' \
--data-raw '{
"amount": 6777,
"customer_id": "new-c777", …
```
> fix(core): fix failing token based MIT payments

- crates/diesel_models/src/query/merchant_connector_account.rs
- crates/router/src/core/payment_methods/cards.rs
use recurring enabled flag in the lIst Customer Payment Method to decide which payment method supports MIT.
- Create a MA and a MCA with 2 connectors , cybersource and stripe
- Create a mandate payment with one card , lets say using stripe
- create a mandate payment with some pm, let's say wallet with the connector cybersource
- list the payment methods for the customer, the card which has mandate enabled will have the recurring field as true else false
> So in the below case have not disabled any mca and then you do a list the recurring enabled field will come as true
```
Response
{
"customer_payment_methods": [
{
"payment_token": "token_HeBYwsQiiuwKosGloeAF",
"payment_method_id": "pm_N1PKc4pShnNg3zCCKFrY",
"payment_method_type": …
```
> refactor(payment_methods): use recurring enabled flag to decide which payment method supports MIT

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
https://github.com/juspay/hyperswitch/pull/4749
This pr is to mask the email address being logged in the payment method list response.
-> Create a merchant account and mca
-> Create a payment with confirm false
```
curl --location 'http://localhost:8080/account/payment_methods?client_secret=pay_jviyQiUsX9uHI99VXUlF_secret_lHrA6q5GKvNvd5a0blUQ' \
--header 'api-key: pk_dev_df002da8beb74682ac3e8677a4b82217'
```
in the below log we can see the email address being logged (this is without the changes in this pr)
after the changes the email is being masked
> fix(payment_methods): mask the email address being logged in the `payment_method_list` response logs

- crates/diesel_models/src/query/merchant_connector_account.rs
- crates/router/src/core/payment_methods/cards.rs
revert the filter for getting the mcas which are disabled, and explicitly get the Mca that are disabled
- All the MCA's either disabled/enabled will show in the LIST MCAs
```
Response
[
{
"connector_label": "cybersource_US_default_2",
"merchant_connector_id": "mca_JfI8xFhxTnL5q2bFhpUW",
"profile_id": "pro_NMDohQHyrqzAkUjBjDmB",
{
{
"Visa",
"Mastercard"
],
"accepted_currencies": null,
"accepted_countries": null,
},
{ …
```
> fix(payment_methods): revert the filter for getting the mcas which are disabled

- crates/router/src/core/payments/operations/payment_response.rs
asynchronous payment attempt update causing stale data to be updated in redis during kv mode, made a temporary 
change to wait for call to locker
https://github.com/juspay/hyperswitch/pull/4582 (to make CI happy)
> feat: Soft kill kv

- crates/api_models/src/payments.rs
When the name is sent as "" ( empty string ), it is being considered as Some(""), this might cause some problems when we accept the name from api and send it directly to the processor. Instead, this should be handled as None value in the code.
- Create a payment intent
```bash
--header 'api-key: dev_6Rvpw8dhQv925raOOXlnZJ439sIRA085PbFyDJqK395MLmZAOm24NISOwpUlBK1i' \
--data '{
"currency": "EUR"
}'
```
- Make a payment through ideal using the below api contract which is how it is being sent by the sdk
```bash
curl --location 'http://localhost:8080/payments/pay_eU2sZbBujtZvJq8mRjAg/confirm' \
--header …
```
> refactor(first_name): check if first_name is sent as empty string

- crates/api_models/src/payouts.rs
- crates/openapi/src/openapi.rs
- crates/router/src/connector/utils.rs
- crates/router/src/types/api/payouts.rs
- openapi/openapi_spec.json
Fixes https://github.com/juspay/hyperswitch/issues/4860
> refactor(api_models): rename Card struct for payouts to avoid overrides in auto generated open API spec

- CHANGELOG.md
- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
add `request_external_three_ds_authentication` flag in payment_method_list_response
This is required for mobile SDK before confirm call to initiate the Netcetera SDK beforehand
1. Payments Create
2. List Payment Methods
> feat(router): add `request_external_three_ds_authentication` flag in payment_method_list_response

- crates/api_models/src/enums.rs
- crates/router/src/configs/defaults.rs
- openapi/openapi_spec.json
Field Type of `payment_method_data.crypto.network` is made an enum called UserCryptoCurrencyNetwork
https://github.com/juspay/hyperswitch/issues/4852
- Payments Create (Confirm False):
Request:
```
--header 'api-key: dev_pjVrtRQmn0UDgtRtnzq6irFdNrbGHTgMvHFhX2RI15o84A5UFWvtlstAyB14V349' \
--data-raw '{
"amount": 120,
"return_url": "https://google.com"
}'
```
Response:
```
{
"payment_id": "pay_ovcPYk9E32vh4YYhxpsw",
"merchant_id": "merchant_1713942708",
"status": "requires_payment_method",
"amount": 120,
"net_amount": 120,
"connector": null, …
```
> feat(connector): [CRYPTOPAY] Make payment_method_data.crypto.network as enum

- crates/router/src/connector/klarna/transformers.rs
- crates/router/src/connector/utils.rs
1. Create a Merchant 
```
{
"address": {
}
},
"return_url": "https://google.com/success",
"webhook_details": {
"webhook_version": "1.0.1",
"webhook_username": …
```
> refactor(connector): [Klarna] Add support for Klarna Optional Shipping Address

- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
- crates/router/src/configs/defaults.rs
Supported currency and countries are added for [afterpay clearpay](https://docs.adyen.com/payment-methods/clearpay/)(Adyen).
Test case 1: curl --location --request GET '[http://localhost:8080/account/payment_methods?client_secret={{client_secret}}](http://localhost:8080/account/payment_methods?client_secret=%7B%7Bclient_secret%7D%7D)'
--header 'Accept: application/json'
--header 'api-key:{{publishable_key}}'
response should contain billing address country : [GB,AU,NZ,CA,US]
TestCase 2: Payment method list should contain after pay if we provided country currency as `[GB,AU,NZ,CA,US]` & `[GBP,AUD,NZD,CAD,USD]`
> fix(connector): [Adyen]add configs for afterpay adyen

- crates/api_models/src/admin.rs
- crates/router/src/types/api/admin.rs
- openapi/openapi_spec.json
add `collect_shipping_details_from_wallet_connector` in the business profile
-> Create merchant account
-> update the business profile with the below curl
```
curl --location 'http://localhost:8080/account/merchant_1717593917/business_profile/pro_eqCDCAfX7AA2WudlMDYP' \
--data '{
"collect_shipping_details_from_wallet_connector": true
}'
```
> refactor(business_profile): add `collect_shipping_details_from_wallet_connector` in the business profile response

- crates/api_models/src/enums.rs
- crates/router/src/configs/defaults.rs
- openapi/openapi_spec.json
Add dynamic fields for klarna payment method
1. Create a Klarna Payment Request via Klarna with with `confirm=fasle`
```
{
"amount": 1800,
"customer_id": "cus_NwicjmCJbgafjhjfhHr6",
"phone": "9123456789",
"payment_method_type": "klarna",
"pay_later": {
"klarna_sdk": {
"token": "65bfb654-ef2c-6b39-942e-ffdc9a105d3cf"
} …
```
> refactor(connector): [KLARNA] Add dynamic fields for klarna payment method

- cypress-tests/cypress/e2e/PaymentTest/00017-BankRedirect.cy.js
- cypress-tests/cypress/e2e/PaymentUtils/Adyen.js
- cypress-tests/cypress/e2e/PaymentUtils/Commons.js
- cypress-tests/cypress/e2e/PaymentUtils/Stripe.js
- cypress-tests/cypress/e2e/PaymentUtils/Trustpay.js
- cypress-tests/cypress/fixtures/create-connector-body.json
- cypress-tests/cypress/support/redirectionHandler.js
Add Bank redirects payment methods for stripe in cypress automation
Bank redirects  test cases was present in the automation setup
Cypress 
- Stripe
- Adyen
- Trustpay
- Nmi
- Cybersource
- Bankofamerica
- Bluesnap
> ci(cypress): Add bank redirects for stripe

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
Make AVS code optional
1. Do a non 3ds payment - Sanity
```
--header 'api-key: dev_K5SsEmIckmis20oeONswdh8Cu58ZuXrNLCLIzyXNhhJLiHeeo600vhMovaKi81F0' \
--data-raw '{
"amount": 10000000,
"billing": {
"address": { …
```
> fix(connectors): [BOA/CYBS] make avs code optional

- crates/router/src/connector/bankofamerica/transformers.rs
[ORIGINAL PR: https://github.com/juspay/hyperswitch/pull/4908 ]
Refund Status in Bankofamerica refund response is returning a new value 201 along with errorInformation.reason as PROCESSOR_DECLINED which is being handled now.
https://github.com/juspay/hyperswitch/issues/4906
We are unable to recreate the status "201" on BOA sandbox and hence only normal refund flow should be tested.
Refund Request:
```
--data '{
"payment_id": "pay_O9ziXsg3MNqO3z40T5G7",
"amount": 1404,
"reason": "Coumer returned product",
"refund_type": "instant",
"metadata": {
"login_date": "2019-09-10T10:11:12Z"
} …
```
> feat(connector): [BOA] Handle refund status 201

- crates/router/src/core/payments/transformers.rs
Populate payment method data in payments list to get card network details.
Closes [#4914](https://github.com/juspay/hyperswitch/issues/4914)
Tested with curl for payments list
```
--header 'Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMWZjNzgyOTUtM2JiMy00OGJjLThlZDgtNzFjMzVjMzMxYWU2IiwibWVyY2hhbnRfaWQiOiJtZXJjaGFudF8xNjk3NzE2ODcwIiwicm9sZV9pZCI6Im1lcmNoYW50X2FkbWluIiwiZXhwIjoxNjk3ODg5NjcxLCJvcmdfaWQiOiJvcmdfejQ5ZExMeTdmbllUODN5TDY3clEifQ.CJzEQ2qbhn-qUiiVBSdvCJiLvWp-5wCF9R54gth6QbQ; Cookie_1=value' \
--header 'Authorization: Bearer HWT' \
--data '{
"amount_filter": {
"start_amount": 12600,
"end_amount": 12600
}
}'
```
Response
```
{
"count": 1,
"total_count": 1,
"data": …
```
> fix(payments): populate payment method data in payments list

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
ORIGINAL PR: https://github.com/juspay/hyperswitch/pull/4915
State and Zip is made optional for BOA and Cybersource transactions for countries other than USA and Canada.
https://github.com/juspay/hyperswitch/issues/4917
We need to test apple pay, google pay and cards payments for BOA and Cybersource. For each payment method we need to test using at least 3 countries which should include US, Canada and Israel. 
billing.address.state and billing.address.zip have been made optional only for countries other than USA and Canada.
Request:
```
--data-raw '{
"amount": 101,
"capture_method": …
```
> feat(connector): [BOA/CYB] Make state,zip optional for Non US CA Txns

- .github/CODEOWNERS
- api-reference/openapi_spec.json
- crates/api_models/src/admin.rs
- crates/diesel_models/src/business_profile.rs
- crates/router/src/core/admin.rs
- crates/router/src/core/routing/helpers.rs
- crates/router/src/types/api/admin.rs
`is_connector_agnostic_mit_enabled` this field is used to make connector agnostic MIT payments. If set to `true` the recurring payments (MIT) can be routed to any other connector which supports network transaction id flow. If it `false` the subsequent MITs needs to be routed trough the same connector as CIT.
Hence adding support create and update the filed in business profile create, update and in business profile response.
-> Create a merchant account
-> Create a business profile under the above merchant account
```
curl --location 'http://localhost:8080/account/merchant_1718004259/business_profile' \
--data '{
"profile_name": "Pg_agnostic_mit",
"collect_shipping_details_from_wallet_connector": true, …
```
> refactor(business_profile): add `is_connector_agnostic_mit_enabled` in the business profile APIs

- CHANGELOG.md
- crates/router/src/core/payment_methods/utils.rs
- crates/router/src/core/payments/routing.rs
- crates/router/src/routes/app.rs
fix the multitenancy prefix  in routing cache, graph cache and pm_filter cache. 
- To test the routing cache you can create two rules
- Lets say the first is volume 100 to stripe
- Do a list PM for Merchant you'll get stripe as the connector for google pay
-The second rule would be, Lets say the first is volume 100 to cybersource
- Now do a list PM for Merchant you'll get cybersource  as the connector for google pay
> fix(core): fix the multitenancy prefix  in routing cache

- crates/hyperswitch_domain_models/src/lib.rs
- crates/hyperswitch_domain_models/src/router_data_new.rs
- crates/hyperswitch_domain_models/src/router_data_new/flow_common_types.rs
Introduced `struct RouterDataNew` in hyperswitch_domain_models crate.
This is a flow agnostic RouterData. This RouterDataNew will replace existing RouterData in all flows.
Also created Flow specific common data types for each flow.
Checked if compiles successfully since This PR only introduces the new types and doesn't alter the existing code.
> chore: introduce RouterDataNew and FlowSpecificData models

- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/routing.rs
- crates/router/src/types/storage.rs
Currently for apple pay pre-routing is done before the session call and only one connector is decided based on the routing logic. Now since we want to enable auto retries for apple pay we need to consider all the connectors form the routing rule and construct a list of it. After which this connectors should be filtered out with the connectors that supports apple pay simplified flow.
Once this is done there will be a list of connectors with which apple pay retries can we performed.
Corresponding pr on the main branch https://github.com/juspay/hyperswitch/pull/4952
-> Create merchant account
-> Enable auto retries for the specific `merchant_id`
```
curl --location 'localhost:8080/configs/' \
--data '{
"key": …
```
> feat(router): include the pre-routing connectors in Apple Pay retries

- crates/api_models/src/events/user.rs
- crates/common_utils/src/events.rs
- docker-compose.yml
fix(events): Correct parsing of API events with user event_type for ClickHouse (#4987)
- Removed redundant `merchant_id` to handle user events correctly in ClickHouse.
- Updated Docker Compose to display times in IST timezone for ClickHouse.
By switching the merchant from localhost dashboard itself.
> fix(events): Correct parsing of API events with user event_type for Clickhouse

- crates/euclid/src/enums.rs
- crates/router/src/core/payment_methods.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/utils.rs
- crates/router/src/db/merchant_connector_account.rs
- crates/router/src/routes/metrics/bg_metrics_collector.rs
- crates/storage_impl/src/redis/cache.rs
- crates/storage_impl/src/redis/pub_sub.rs
Reverts the feature payment method list filter using constraint graph.
the main PR is
https://github.com/juspay/hyperswitch/pull/5044
> Refactor(core): reverts the payment method list filtering using constraint graph

- crates/router/src/core/payments.rs
avoid considering pre-routing results during `perform_session_token_routing`
As there is a logic to filter out the apple pay payment method if apple pay is already saved. But this should not be the save when performing the session token (`perform_session_token_routing`). 
https://github.com/juspay/hyperswitch/pull/5076
-> Create mca with apple pay configured
-> Create payment with apple pay
```
{
"amount": 650,
"phone_country_code": …
```
> fix(router): avoid considering pre-routing results during `perform_session_token_routing`

- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
make risk information message optional
Sanity
1. Create a card payment 
```
--header 'api-key: dev_rqLTjP6lYoYBlUxgTo4vgFpLqh9FaLiOb2XKtRCgVEmowE8JneOTgkA5kYRrq197' \
--data-raw '{
"amount": 100,
"email": "example@juspay.in",
"card": {
"card_number":  "4456530000001104",
}
},
"billing": {
"address": {
"line3": "Harrisoff Street",
"state": …
```
> fix(connector): [BOA/CYBS] make risk information message optional

- crates/router/src/connector/adyenplatform/transformers/payouts.rs
- crates/router/src/core/errors/utils.rs
Throw 4xx instead of 5xx in case of missing `source_balance_id `
- Create MCA for AdyenPlatform without passing source_balance_account
```
{
"connector_type": "payout_processor",
"connector_name": "adyenplatform",
"api_key": "{{adyen_platform_api_key}}"
},
"metadata": {
"city": "NY",
"unit": "245"
}
}
```
- Do a payout request:
```
{
"amount": 100,
"customer_id": "sakilcust",
"priority": "regular",
"bank": {
"iban": "NL91ABNA0417164300"
}
},
"billing": {    
"address": { …
```
> refactor(connector): [AdyenPlatform]Throw 4xx instead of 5xx for source_balance_account

- crates/api_models/src/events/user.rs
- crates/api_models/src/user.rs
- crates/router/src/core/user.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/lock_utils.rs
- crates/router/src/routes/user.rs
- crates/router/src/types/domain/user/decision_manager.rs
- crates/router_env/src/logger/types.rs
- Add endpoint `/auth/select` to terminate auth select
- The api will take Auth Select SPT and will give SSO SPT or TOTP SPT based on the choice selected
- SSO SPT if user selects continue with SSO
- TOTP SPT if user selects continue with TOTP
Closes #5127 
If request from id that has auth type as `open_id_connect`:
```
curl --location 'http://localhost:8080/user/auth/select' \
--header 'Authorization: Bearer SPT' \
--header 'Cookie: Cookie_1=value' \
--data '{
"id":"f20742d2-f1b8-4dad-8b2d-cf8fe6d457eb"
}'
```
response will contain token type as `sso`
```
{
"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYjJkNjMxZDUtMGQzMi00Y2IxLTg2MTQtNWVlNWI2MDczYTVkIiwicHVycG9zZSI6InNzbyIsIm9yaWdpbiI6ImFjY2VwdF9pbnZpdGF0aW9uX2Zyb21fZW1haWwiLCJw …
```
> feat(users): add endpoint for terminate auth select

- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/connector_configs/src/transformer.rs
- crates/diesel_models/src/payment_attempt.rs
- crates/hyperswitch_domain_models/src/payment_method_data.rs
- crates/hyperswitch_domain_models/src/payments/payment_attempt.rs
- crates/openapi/src/openapi.rs
- crates/router/src/connector/trustpay/transformers.rs
- crates/router/src/core/payments/flows/authorize_flow.rs
- crates/router/src/core/payments/flows/setup_mandate_flow.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/payments/retry.rs
- crates/router/src/workflows/payment_sync.rs
- crates/router/tests/connectors/payme.rs
- crates/router/tests/connectors/payu.rs
- crates/router/tests/connectors/square.rs
- crates/router/tests/connectors/stax.rs
- crates/router/tests/connectors/utils.rs
- crates/router/tests/connectors/worldpay.rs
- crates/storage_impl/src/payments/payment_attempt.rs
Main PRs
https://github.com/juspay/hyperswitch/pull/5118
Tested Manually, test cases can be seen on main PRs
> fix(router): skip serialize if none for assurance_details_required in googlepay session response

- crates/router/src/configs/defaults.rs
- crates/router/src/configs/settings.rs
- crates/router/src/core/blocklist/transformers.rs
- crates/router/src/core/payment_methods/cards.rs
- crates/router/src/core/payment_methods/transformers.rs
https://github.com/juspay/hyperswitch/pull/5140
> chore(cards): add configuration option to change the decryption scheme locker

- crates/router/src/core/user.rs
- crates/router/src/utils/user.rs
The PR
- removes cookie after rotate password and reset password
- refactor parsing for sso config, now it uses `serde json from value` instead of `parse value`
- refactors terminate auth select
- send bad request instead of internal server error if invalid id is passed to auth/select 
closes #5146 
For bad request id for in auth select:
```
curl --location 'http://localhost:8080/user/auth/select' \
--header 'Authorization: Bearer SPT' \
--data '{
"id":"wrong id"
}'
```
Response
```
{
"error": {
"message": "Invalid user auth method operation",
"code": "UR_44"
}
}
```
For valid id Response token type can be `sso` or `totp`, (tested for both valid ids from db to get correct token type)
```
{
"token": …
```
> fix(users): clear cookie and alter parsing for sso

- crates/router/src/connector/adyen/transformers.rs
send `browser_info` for all the card and googlepay payments
Main PR https://github.com/juspay/hyperswitch/pull/5153
Main PR has the test cases
> fix(connector): [ADYEN] send `browser_info` for all the card and googlepay payments

- crates/router/src/core/payment_methods/cards.rs
This PR adds missing logs for payment methods flow (both merchant and customer).
This PR only adds logs so basic sanity tests should suffice
> refactor(payment_methods): add appropriate missing logs

- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/common_enums/src/enums.rs
- crates/openapi/src/routes/payments.rs
- crates/router/src/lib.rs
> Docs: Updated API - ref for payments

- crates/router/src/services/kafka.rs
Adds millisecond timestamp to the kafka timestamp, would help in solving the re-ordering of events in kafka while pushing
> refactor: Adding millisecond to Kafka timestamp

- crates/router/src/connector/iatapay/transformers.rs
> fix(router): [Iatapay] add CLEARED refund status

- .github/workflows/CI-pr.yml
- .github/workflows/CI-push.yml
This PR updates the `CI-pr` and `CI-push` workflows to use a matrix strategy to specify runners.
This is being done to debug issues with some of the runners.
N/A
> ci: use matrix strategy for specifying runners

- crates/router/src/connector/adyen/transformers.rs
remove mandatory payment_method_type check in MIT, as we won't necessarily have this in CIT
https://github.com/juspay/hyperswitch/issues/5245
```
--header 'api-key: dev_FdbwTgkrJgCahVeugTVGJ3KWbS0UiIADoLlJoMfP2gzxicfOqbJ3HXcjoP8fjr8I' \
--data-raw '{
"amount": 1212,
"customer_id": "adyen_test",
"email": "abc-ext.kylta@flowbird.group",
"description": "Its my first payment",
"statement_descriptor_suffix": …
```
> fix(connector): remove mandatory payment_method_type check in MIT

- .github/workflows/CI-pr.yml
Set `fail_fast` to false in the Ci
> ci: set fail fast to false in CI workflow

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
> refactor(connector): wasm changes for razorpay

- crates/router/src/connector/razorpay.rs
Make source verification false
1.Create a payment 
```
curl --location '/payments' \
--header 'api-key: dev_apY4Z0olECTOs9jaEXdLerWGTjFwlPexZBWUQn9t1Cd09ebyn8yGS2nT6JPFTZj8' \
--data-raw '{
"customer_id": "IatapayCustomer",
"payment_method_data": …
```
> fix(router): [razorpay] make source verification false

- .github/CODEOWNERS
update CODEOWNERS for connector_configs crate
Nothing to test in this PR
> ci: update CODEOWNERS for connector_configs crate

- crates/router/src/connector/razorpay/transformers.rs
1. Update connector_refund_id in Refund and Rsync
2. 
3. Refactor Webhook Status
1. MCA 
```
{
"connector_name": "razorpay",
"auth_type": "MultiAuthKey",
"api_key": "",
"key1": "",
"api_secret": "",
"key2": ""
},
{
{
"accepted_currencies": {
"type" : "enable_only",
"list": ["INR"]
},
"accepted_countries": {
"type" : "enable_only",
"list": ["IN"]
},
}
]
}
],
"metadata": {
"city": "NY",
"unit": "245"
}, …
```
> refactor(connector): Update connector_refund_id and Refactor Webhook Status

- crates/analytics/docs/clickhouse/scripts/fraud_check.sql
- crates/analytics/docs/clickhouse/scripts/sdk_events.sql
Fixed the issue, a comma was missed in the syntax
Fix the bug
Script ran fine, and the fraud check tables were created in clickhouse
> fix(analytics): Updated frm clickhouse script for creating table

- config/deployments/production.toml
Update ZSL base url for production
No testing required
> feat(config): [ZSL] Update ZSL base url for production

- crates/api_models/src/analytics/payment_intents.rs
Fixed issues for Payment Intent v2 Analytics
https://github.com/juspay/hyperswitch-cloud/issues/5798
- currency filter was compulsary previously, but changed it to optional by adding `#[serde(default)]` tag to take the default value if this field is not present
Fixed bugs in analytics
```bash
curl --location 'http://localhost:8080/analytics/v2/metrics/payments' \
--header 'QueryType: SingleStat' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-site' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel …
```
> fix(analytics): Resolve issues for payment-intent v2 analytics

- crates/router/src/connector/razorpay.rs
Currently we are passing a wrong refund webhook reference id, hence refund webhooks are failing while received by hyperswitch.
After this PR
Hyperswitch should identify refund webhook and trigger a Rsync to update the status
1. Create a payment with Razorpay UPI Collect
```
--header 'api-key: dev_UlJFXb4LACytmSXSI3i9J9N6aFzJELAUCypIwcylOhr5nhhGr6wOioIxQ52KGuDb' \
--data-raw '{
"customer_id": "IatapayCustomer", …
```
> Fix(router): [razorpay] update refund webhook reference id

- cypress-tests/cypress/e2e/PaymentMethodListTest/00000-PaymentMethodListTests.cy.js
- cypress-tests/cypress/e2e/PaymentUtils/Utils.js
- cypress-tests/cypress/support/commands.js
- cypress-tests/package-lock.json
- cypress-tests/package.json
TL:Dr: This PR fixes the false positives by adding a check and also fixes PML tests from throwing `422`.
When we get a 4xx response but in configs, we are expecting a 2xx, the tests would pass which is unexpected and a false positive.   
Also, PML connector have been failing due to changed creds contract. This PR also fixes that.
@Sakilmostak 
PML Tests run without any issues:
This fails at PML for connectors other than `Stripe` and `Cybersource` and is outside the scope of this PR. 
CC: @prajjwalkumar17
> fix(cypress): validate false positives and fix PML tests

- crates/router/src/services/email/assets/api_key_expiry_reminder.html
- crates/router/src/services/email/assets/bizemailprod.html
- crates/router/src/services/email/assets/invite.html
- crates/router/src/services/email/assets/magic_link.html
- crates/router/src/services/email/assets/recon_activation.html
- crates/router/src/services/email/assets/reset.html
- crates/router/src/services/email/assets/verify.html
Minor bugfix in Email templates footer icon, an extra character. was appearing that is now removed
Current
New
> fix: email template minor fix

- config/config.example.toml
- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
- config/docker_compose.toml
- crates/router/src/connector/adyen/transformers.rs
- loadtest/config/development.toml
Sepa Debit mandates CIT requires `shopperReference` & `storePaymentMethod`  to send but we are hardcoding them to none in backend. This is fixed in the PR.
Test Case 1: 
create ach payment and validate whether mandate is stored for payment method id in db.
```
--header 'api-key: dev_qkj7jazEjBPCyX8BcqI7Ykp2MsIPZsvjtZCdn1PpVevqo1AIFxlljhiVkjbHH0K2' \
--data-raw '{
"description": "Its …
```
> fix(connector): [Adyen] fix bank debit mandates for adyen

- crates/router/src/core/payments/routing.rs
While performing the session token routing we create an empty vec that will contain the Routing choices for that particular session. In case if there is no connectors that requires session call then the `perform_session_flow_routing` will return the empty vec. Instead if there is no connectors that requires session call, then we should just return empty hashmap.
-> Create mca for stripe with apple pay, google pay and klarna
```
{
"api_key": ""
},
{
{
"Visa",
"Mastercard"
], …
```
> fix(routing): do not update `perform_session_flow_routing` output if the `SessionRoutingChoice` is none

- crates/router/src/core/payments/operations.rs
- crates/router/src/core/payments/operations/payment_status.rs
There is a locker call that is happening the psync flow. This pr is to remove that call as it is not required.
-> Create a merchant connector account
-> Make payment with setup future usage as on_session
```
{
"amount": 100,
"customer_id": "cu_{{$timestamp}}",
"return_url": "http://127.0.0.1:4040",
"acceptance_type": "offline",
"accepted_at": "1963-05-03T04:07:52.723Z",
"online": {
"ip_address": "in sit", …
```
> refactor(router): Remove the locker call in the psync flow

- crates/api_models/src/payments.rs
- crates/router/src/core/payments/transformers.rs
This pr adds the decrypted customer_details, shipping and billling address in Payment list response.
Required for our Dashboard
We need to make a payment with shipping, billing and customer details and then hit the Payment list api:
```
curl --location --request GET 'http://127.0.0.1:8080/payments/list' \
--header 'api-key:xxxxxxx' \
--data '{
}'
```
The response should contain the below fields:
```
"customer_id": "uiuiuiui",
"customer": {
"id": "uiuiuiui",
"name": null,
"email": "guest@ehjhjxample.com",
"phone": null,
"phone_country_code": null
},
"shipping": {
"address": { …
```
> chore: add customer, shipping and billing details to payment_response for payment list api

- scripts/ci-checks.sh
handle packages to run are being empty
> ci: handle packages to run are being empty

- crates/router/src/connector/volt.rs
- crates/router/src/connector/volt/transformers.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/volt.rs
This PR adds amount conversion framework to Volt
Note: Volt works in MinorUnit
Flows to test in Volt
- Payment
```shell
curl --location 'http://127.0.0.1:8080/payments' \
--header 'api-key: dev_lQ8tJ8zDfuL9j1qjIJ9w1KUkWg9PmDA5PtjspO3R3CZHPkRMLUFVRmai5FM33hCZ' \
--data-raw '{ …
```
> refactor(connector):  add amount conversion framework to volt

- crates/router/src/core/payment_methods/cards.rs
Removes the redundant `business_profile_routing` feature flag from Payment method list.
We can run Cypress test cases for this.
> fix(euclid): remove business_profile routing feature flag

- cypress-tests/cypress/support/commands.js
This PR adds the support for https://github.com/juspay/hyperswitch/pull/5303
nullify the positive cases for mit payments and add some validations
Cypress
- Stripe
- Cybersource
- Bluesnap
(test cases failing due to error code update) this will be fixed by @prajjwalkumar17 
- Bankofamerica 
(failures due to 3ds change)
- nmi 
(error codes failures)
- Trustpay 
(error code failures)
> ci(cypress): Nullify positive cases for MIT payments

- crates/router/src/connector/bitpay.rs
- crates/router/src/connector/bitpay/transformers.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/bitpay.rs
This PR adds amount conversion framework to bitpay
Note: bitpay works in MinorUnit
Flows to test in Bitpay
- Authorize - Capture-automatic
```shell
curl --location 'http://127.0.0.1:8080/payments' \
--header 'api-key: dev_ZsGuKbTiVdiXvPKgq5a2vS8QTWJL7IiQJZPDeVR878m8RqP0fmpbze89umvUn2N3' \
--data-raw '{ …
```
> refactor(connector): added amount conversion framework for bitpay

- cypress-tests/cypress/e2e/PaymentUtils/Commons.js
Changing of error codes to match cypress mappings
To fix failing Cypress-tests
Tested locally for the following connectors:
PS: The failing tests are not due to error codes they are due to expected status 200 but instead receiving error in routing.
stripe
blluesnap
> fix(cypress): fix cypress tests, failing due to error codes being recently changed

- docs/try_local_system.md
Before 
`export DATABASE_URL=$DB_USER:$DB_PASS@localhost:5432/$DB_NAME`
After
`export DATABASE_URL=postgres://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME`
> docs: update postgreSQL database url 

- cypress-tests/cypress/e2e/PaymentMethodListTest/00000-PaymentMethodListTests.cy.js
- cypress-tests/cypress/e2e/PaymentTest/00002-ConnectorCreate.cy.js
- cypress-tests/cypress/e2e/PayoutTest/00002-ConnectorCreate.cy.js
- cypress-tests/cypress/fixtures/create-connector-body.json
- cypress-tests/cypress/support/commands.js
https://github.com/juspay/hyperswitch/pull/4909 will break Cypress tests.  
We need to replace `fiz_operations` during merchant connector account create call with respective `connector_type`(s) -- `payment_processor` for payments and `payout_processor` for payouts, for now.
NIL
PML
Payment Merchant Connector Create Call
Payout Merchant Connector Create Call
Routing is unaffected as usual
> refactor(cypress): pass `connector_type` externally

- config/vector.yaml
- crates/analytics/src/opensearch.rs
Added the `@timestamp` field to OpenSearch locally while creating index-patterns, as it is present in Elasticsearch and is causing mismatched results while using the /search api on SBX
To prevent mismatched data while using `/search` api
- Hit the `/search` API
```bash
curl --location 'http://localhost:8080/analytics/v1/search' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-site' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) …
```
> fix(opensearch): Added @timestamp field for opensearch localhost

- config/docker_compose.toml
This PR fixes the following bug 
```
2024-08-08 21:08:07 thread 'main' panicked at crates/router/src/bin/router.rs:16:10:
2024-08-08 21:08:07 Unable to construct application configuration: Application configuration error
2024-08-08 21:08:07 ├╴at crates/router/src/configs/settings.rs:759:14
2024-08-08 21:08:07 │
2024-08-08 21:08:07 ╰─▶ payout_method_filters.adyenplatform.sepa.currency: Some errors occurred:
2024-08-08 21:08:07     Unable to deserialize `NOR` as `common_enums::enums::Currency`: Matching variant not found
2024-08-08 21:08:07     ├╴at crates/router/src/configs/settings.rs:758:14
2024-08-08 21:08:07     ╰╴Unable to deserialize application configuration
2024-08-08 21:08:07 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Hotfix PR for #5577
> fix(docker): currency enum fix for docker config

- crates/router/src/core/payment_methods/cards.rs
List cards on the basis of profiles, if it has a mandate details.The precedence order for off_session payments should be if network_txn_id is present , then show the pm irrespective of  the profile, but if its not there then check for mandate_details for that profile and list it on that basis.
- Create a MA and 2 Profiles
- Create a MCA for Profile 1
- Create a `off_session` payment 
```
Create
--header 'api-key: dev_jsssWAg0XyxGK0ycPunkFjlItYNs30X1IVOr1MIF7lwrDQgBBk7npwdkZB4t7EQd' \
--data-raw '{
"customer_id": "CustomerX7777", …
```
> fix(payment_methods): List cards on the basis of profiles

- README.md
Adding SM links in the readme header section
> docs(README): add social media links

- crates/router/src/connector/ebanx.rs
- crates/router/src/connector/ebanx/transformers.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/ebanx.rs
This PR adds amount conversion framework to Ebanx and It will work in FloatMajorUnit
We can not test it as we have not sandbox credentials for this connector
> refactor(connector): added amount conversion framework for Ebanx

- cypress-tests/cypress/e2e/PaymentUtils/Iatapay.js
This PR fixes the naming convention with Ideal payment method in Iatapay.
NA
> fix(cypress): fix naming convention in iatapay ideal

- cypress-tests/cypress/e2e/PaymentTest/00020-Variations.cy.js
This PR fixes corner cases in tests failing occasionally.
NA
Ran against `Stripe`:
﻿<img width="417" alt="image" src="https://github.com/user-attachments/assets/5a134aa9-7608-49ba-9ffa-bb33fb8e529e">
> fix(cypress): fix hooks in cypress for 3ds

- crates/analytics/src/opensearch.rs
When searching using global search, the results are not sorted. Sorted the results now in newest to oldest order.
Enhance search experience by listing the results in newest to oldest order.
Raised by this issue: [https://github.com/juspay/hyperswitch-control-center/issues/1131](https://github.com/juspay/hyperswitch-control-center/issues/1131)
- Hit the `/search` API
```bash
curl --location 'http://localhost:8080/analytics/v1/search' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-site' \
--header …
```
> fix(opensearch): Sorted the global search results in descending order

- crates/connector_configs/src/response_modifier.rs
plaid payment processor configuring was breaking
plaid connector configuring was breaking
updated the wasm, and tested with frontend changes locally it is working fine
> chore: wasm changes required for plaid

- crates/router/src/core/payouts.rs
- crates/router/src/core/utils.rs
Described in #5621 
<details>
<summary>1. Create a merchant account</summary>
curl --location 'https://sandbox.hyperswitch.io/accounts' \
--data-raw '{
"merchant_id": "merchant_1723634705",
"address": {
"line2": …
> fix(payout): use mca_connector_id from ConnectorData to fetch mca_account

- api-reference-v2/api-reference/merchant-connector-account/delete-connector_accounts.mdx
- api-reference-v2/api-reference/merchant-connector-account/get-connector_accounts.mdx
- api-reference-v2/api-reference/merchant-connector-account/merchant-connector--create.mdx
- api-reference-v2/api-reference/merchant-connector-account/merchant-connector--delete.mdx
- api-reference-v2/api-reference/merchant-connector-account/merchant-connector--retrieve.mdx
- api-reference-v2/api-reference/merchant-connector-account/merchant-connector--update.mdx
- api-reference-v2/api-reference/merchant-connector-account/post-connector_accounts-1.mdx
- api-reference-v2/api-reference/merchant-connector-account/post-connector_accounts.mdx
fix api paths for `merchant_connector_account` in api-reference-v2
Run `mintlify dev` locally in api-reference-v2
> fix(api-reference): fix api paths for `merchant_connector_account` in api-reference-v2

- crates/api_models/src/events/payment.rs
- crates/api_models/src/payments.rs
- crates/hyperswitch_domain_models/src/payments/payment_intent.rs
- crates/router/src/core/payments.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/lock_utils.rs
- crates/router/src/routes/payments.rs
- crates/router/src/types/api/payments.rs
- crates/router_env/src/logger/types.rs
- crates/storage_impl/src/mock_db/payment_intent.rs
- crates/storage_impl/src/payments/payment_intent.rs
- The endpoint `/aggregate` to support views
- Add support for aggregates in payments.
- For now it will have list of intent status along with the their count for a given time range.
( Profile level support will be covered in separate PR, with new route but same core function having profile_id as option)
- [] This PR modifies the database schema
Closes [#5627](https://github.com/juspay/hyperswitch/issues/5627)
Request:
```
curl --location 'http://localhost:8080/payments/aggregate?start_time=2022-08-20T11%3A33%3A39.000Z' \
```
Response:
```
{
"status_with_count": {
"requires_capture": 0,
"requires_customer_action": 0,
"requires_payment_method": 0,
"processing": 0,
"cancelled": 0,
"requires_confirmation": 0, …
```
> feat(payments): add support for aggregates in payments

- crates/diesel_models/src/query/user_role.rs
- crates/diesel_models/src/user_role.rs
- crates/router/src/core/user.rs
- crates/router/src/core/user_role.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/db/user_role.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/user_role.rs
- crates/router/src/utils/user_role.rs
- This PR adds a new db function which can update a user_role by it's lineage.
Closes [#5650](https://github.com/juspay/hyperswitch/issues/5650).
All the following APIs should not break and work as before.
```
curl --location 'https://integ-api.hyperswitch.io/user/accept_invite_from_email' \
--data '{
"token": "email token"
}'
```
```
curl --location 'https://integ-api.hyperswitch.io/user/accept_invite_from_email?token_only=true' \
--data '{
"token": "email token"
}'
```
```
curl --location 'https://integ-api.hyperswitch.io/user/user/update_role' \
--header 'Authorization: ••••••' \
--data '{
"email": "user email",
"role_id": "merchant_iam_admin"
}'
```
The …
> feat(user_role): Add update by lineage DB function

- crates/router/src/configs/defaults.rs
- crates/router/src/connector/adyen/transformers.rs
Prevent partial submission of billing address to Adyen
1. Create a payment connector accounts with adyen, stripe , bambora and cybersource with following payment methods enabled. 
```
"payment_methods_enabled":[
{
"payment_method": "voucher",
{
"payment_method_type": "boleto",
"accepted_currencies": null,
"accepted_countries": null,
"minimum_amount": 0,
"installment_payment_enabled": false
}
]
},
{
{
"payment_method_type": "paypal",
"accepted_currencies": null,
"accepted_countries": null,
"minimum_amount": 0,
"maximum_amount": …
```
> fix(router): [Adyen]  prevent partial submission of billing address and add required fields for all payment methods

- crates/router/src/core/payment_methods/utils.rs
This Pr will change the node relation of the `Disabled_only` field passed in mca for any connector to be Negative.
The flow for testing this is as follows:
1. Mca create for crypto_pay
```
curl --location 'http://127.0.0.1:8080/account/merchant_1724687132/connectors' \
--data '{
"connector_name": "cryptopay",
"api_key": "xxxxx",
"key1": "xxxxxxx"
},
{
{ …
```
> refactor(euclid): make the disabled node's relation as negative

- crates/connector_configs/toml/production.toml
add production connector-configs for netcetera external 3ds flow
Config changes only
> chore(config): add production connector-configs for netcetera external 3ds flow

- crates/router/src/core/routing.rs
- crates/router/src/routes/routing.rs
fix routing routes for activating and retrieving the routing algorithms where not able to deserialise correctly due to the following [PR](https://github.com/juspay/hyperswitch/pull/5686)
- Create a MA and a MCa 
-  Create a Routing Rule
```
curl --location 'http://localhost:8080/routing' \
--header 'api-key: dev_HIL1XwQlvsJtPbfaOoWrYPznXmFoKE2F0Sg2Kq58Rjnj8PsV5k51g33I6a8chvLN' \
--data '{
"profile_id": "pro_2ScZ3GfSL10mn5BMMuFH",
"name": "Brand based",
"description": "This is a rule based routing created at Wed, 21 Aug 2024 08:28:31 GMT",
"algorithm": {
"type": "advanced",
"data": {
"defaultSelection": {
"type": "priority",
"data": []
},
"rules": [
{
"name": "rule_1",
"connectorSelection": {
"type": "priority",
"data": [
{
"connector": "adyen", …
```
> fix(routing): fix routing routes to deserialise correctly

- crates/api_models/src/payments.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
bug - when request_external_three_ds_authentication is sent as true in payments request of recurring payments, it's trying to attempt 3ds flow which is not expected. 
This PR adds the check to skip external three_ds flow for recurring payments
Recurring payment by sending request_external_three_ds_authentication as true shouldn't trigger 3ds and get succeeded
CURL
```
curl --location '{{BASE_URL}}/payments' \
--header 'api-key: {{API_KEY}}' \
--data-raw '{
"request_external_three_ds_authentication": true,
"customer_id": "stripecustomer1",
"email": …
```
> fix(router): skip external three_ds flow for recurring payments

- crates/api_models/src/customers.rs
- crates/api_models/src/events.rs
- crates/diesel_models/src/query/customers.rs
- crates/router/src/consts.rs
- crates/router/src/core/customers.rs
- crates/router/src/core/locker_migration.rs
- crates/router/src/db/customers.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/routes/customers.rs
- crates/router/src/types/api/customers.rs
Main branch PR can be found here https://github.com/juspay/hyperswitch/pull/5735
Check the same test cases that are run on the main PR
> refactor(customers): add offset and limit to customers list

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
Wellsfargo doest supports wallets (applepay and googlepay). Removing Config.
Just config Changes ,Can't test it
> Feat(connector): [WELLSFARGO] Remove Wallet Configs

- cypress-tests/cypress/e2e/RoutingTest/00003-Retries.cy.js
Changes introduced in https://github.com/juspay/hyperswitch/commit/150094fd92d67391f412055abf6eb78d2286963e#diff-50079ba51c9e78787cf466488b71d898170d56c08782a82e7cd14f8bd1fcde16 went unaddressed in https://github.com/juspay/hyperswitch/commit/b66f91034beab4078f360ecbb3607b55df556eae resulting in Auto Retry tests to fail. This PR aims to fix that.
NIL
> fix(cypress): fix undefined errors in auto-retries

- crates/router/src/connector/cybersource.rs
- crates/router/src/connector/cybersource/transformers.rs
- crates/router/src/connector/utils.rs
During the MIT with cybersource connector we check if the connector mandate details are present. If is present then we make a no_three_ds api request. Same check needs to be added in case of network transaction id flow as MIT can be done using card details and network transaction id as well.
As this check is not present threeds is triggered even during MITs with card details and network transaction id.
-> Create mca of cybersource  
-> enable the `is_connector_agnostic_mit_enabled` config
```
curl --location 'http://localhost:8080/account/merchant_1725355756/business_profile/pro_jQJ4qqk9cMEsOfzx4jjP' \
--header 'api-key:' \
--data '{
"is_connector_agnostic_mit_enabled": true
}'
```
```
{
"merchant_id": …
```
> fix(connector): skip 3DS in `network_transaction_id` flow for cybersource

- crates/router/Cargo.toml
Build was failing so Fixed errors on payment_methods_v2 for the build to succeed.
> fix: Fix errors on payment_methods_v2

- crates/analytics/docs/clickhouse/scripts/payment_attempts.sql
Added card_network as a field in payment_attempts clickhouse table
Made sample payments on sandbox dashboard and confirmed the data for card_network on clickhouse sandbox
> feat(analytics): add card_network as a field in payment_attempts clickhouse table

- crates/hyperswitch_domain_models/src/router_data.rs
- crates/router/src/types/transformers.rs
mask keys in connector_account_details for merchant_connector_response in merchant_connector_account retrieve flow
1. if key length > 4 -> show first and last two characters, mask others with *
2. if key length <= 4 -> mask the entire key with *
MCA Create CURL
```
curl --location 'localhost:8080/account/merchant_1725618480/connectors' \
--data '{
"api_key": "key",
"api_secret": "secret",
"key1": "key1"
},
{
"payment_method": "card_redirect", …
```
> feat(router): mask keys in `connector_account_details` for merchant_connector_response in mca retrieve flow

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
> docs: Correction for JPY in API Ref

- crates/router/src/core/payments.rs
Type of Change
Remove unwanted commented lines
Remove unnecessary code
No code changes done
> refactor: Remove unwanted commented lines

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/admin.rs
- crates/api_models/src/payments.rs
- crates/common_utils/src/consts.rs
- crates/openapi/src/openapi.rs
- crates/openapi/src/openapi_v2.rs
- crates/router/src/core/payment_link.rs
- crates/router/src/core/payment_link/payment_link_initiate/payment_link.css
- crates/router/src/core/payment_link/payment_link_initiate/payment_link.js
the api contract is changed for payment link to specifically take position of the fields and how to render them on UI. 
Tested through Postman: 
- Create a MCA(Bamboraapac):
```
{
"connector_name": "bamboraapac",
"api_key": "{{api_key}}",
"key1": "{{key1}}",
"api_secret": "{{api_secret}}"
},
{
{
"Visa",
"Mastercard"
],
},
{
"Visa",
"Mastercard"
], …
```
> refactor(payment_links): Update API contract for dynamic transaction details and upgrade UI

- crates/connector_configs/src/connector.rs
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
Added Wasm Configs
Not Applicable
> feat(connector): [Fiuu] ADD Wasm Configs

- crates/connector_configs/src/connector.rs
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
- crates/euclid_wasm/src/lib.rs
- wasm changes for Taxjar connector 
- wasm changes for new ConnectorType TaxConnectors
No testing required
> feat(connector): wasm changes for Taxjar

- crates/common_utils/src/lib.rs
- crates/router/src/connector/paybox/transformers.rs
1)Fixed Datatime format
2) Paybox returns 0000 for successful operations and any other code for unsuccessful ones, but we were previously marking the response status(0000) as "Pending" for Capture/Auth/Auth+Capture. We would then perform a sync after each operation. Now, the status is updated to "Authorized," "Settled," or "Charged" where necessary, instead of "Pending."
**Auth+Capture**
Request 
```
--header 'api-key: dev_EAjowXCNHti7TNLRlRjuBOiorCgOYn3XJ9K9kdioIORXVr1vwZu792BhvwnBdf3d' \
--data '{
"amount": 1500,
"customer_id": "BamboraCustomer", …
```
> refactor(connector): [Paybox] Fix Error Handling/Datetime format

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/openapi/src/openapi.rs
- crates/openapi/src/openapi_v2.rs
- crates/router/src/core/payments/transformers.rs
A new field `display_amount` has been added to the `PaymentsDynamicTaxCalculationResponse`. This field holds amounts in the `StringMajorUnit` format, converted from their respective `MinorUnit` values. It includes the `net_amount`, `order_tax_amount`, and `shipping_cost` fields, all intended for display in the SDK.
1. Create a Merchant Account 
```
--data-raw '{
"merchant_id": "merchant_1725535996",
"secondary_contact_person": "John …
```
> refactor(core): update response for PaymentsDynamicTaxCalculationResponse

- crates/router/src/core/payments/operations/payment_approve.rs
- crates/router/src/core/payments/operations/payment_reject.rs
- crates/router/src/core/payments/operations/payment_status.rs
Described in #5888 
Ensures FRM DB queries are not executed if `frm` feature flag is not enabled. There are a couple of features disabled in HS production, and the DB migrations for such features have not been executed. This leads to unnecessary missing column logs in production - `ERROR: column fraud_check.last_step does not exist at character 443`
Moving such DB queries behind the feature flag ensures they are not executed in the flow.
<details>
<summary>1. Create a txn</summary>
cURL
--header 'api-key: dev_4cUeectovRvg0seB0AhDXZ04342m045JeKncgz5XfwkkhJujY4gy7TzfTS9uvdiP' \
--data-raw '{ …
> fix(frm): add feature flag for querying FRM data

- crates/router/src/db/merchant_connector_account.rs
After MCA Update v2, retrieve wasn't giving the updated values as cahce wasn't invalidated. 
fix cache invalidation in merchant_connector_update flow for v2
1. MCA Update
CURL
`curl --location --request PUT '{{BASE_URL}}/v2/connector_accounts/{{MCA_ID}}' \
--header 'api-key: {{ADMIN_API_KEY}}' \
--data '{
"connector_webhook_details": {
"merchant_secret": "secret1"
},
"merchant_id": "{{MERCHANT_ID}}"
}'`
Response
`{
"connector_name": "adyen",
"connector_label": "adyen_abcdef",
"id": "mca_GG4rKGG8Eg185d8dsPJj",
"profile_id": "pro_iB39KVkXPAkJAILOZaUp", …
> fix(router): cache invalidation in merchant_connector_update flow for v2

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/enums.rs
- crates/router/src/configs/defaults.rs
Add `user_iban` & `user_bank_account_number`as field type for required fields for SDK to add validation on iban & bank account number place holders
. This PR also fixes 
- required field path and display name for sepa payment method. 
- remove duplicate required field for adyen mbway
- rename bank_account_number to iban for sepa bank debits.
Step 1: Create an mca with adyen as processor
```
curl --location 'http://localhost:8080/account/merchant_1726493260/connectors?locale=en' \
--data '{
"connector_name": "adyen",
"key1": "KEY1",
"api_key": "API_KEY"
}, …
```
> fix(connector): add field types for bank debits

- api-reference-v2/openapi_spec.json
- crates/openapi/src/openapi_v2.rs
- crates/openapi/src/routes/customers.rs
add openapi docs for customers v2
openapi changes only
> docs: add openapi docs for customers v2

- api-reference-v2/api-reference/business-profile/merchant-connector--list.mdx
- api-reference-v2/api-reference/customers/customers--create.mdx
- api-reference-v2/api-reference/customers/customers--delete.mdx
- api-reference-v2/api-reference/customers/customers--list.mdx
- api-reference-v2/api-reference/customers/customers--retrieve.mdx
- api-reference-v2/api-reference/customers/customers--update.mdx
- api-reference-v2/api-reference/merchant-account/business-profile--list.mdx
- api-reference-v2/api-reference/merchant-account/merchant-account--create.mdx
- api-reference-v2/api-reference/merchant-account/merchant-account--retrieve.mdx
- api-reference-v2/api-reference/merchant-account/merchant-account--update.mdx
- api-reference-v2/api-reference/organization/merchant-account--list.mdx
- api-reference-v2/mint.json
- api-reference-v2/openapi_spec.json
- api-reference/api-reference/customers/customers--list.mdx
- api-reference/openapi_spec.json
- crates/openapi/src/routes/customers.rs
make api-reference docs changes for customers and admin list apis for v2
Tested api docs locally using `mintlify dev`
> docs: api-reference changes for customers and admin list apis for v2

- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario1-Create payment with confirm true/Payments - Create/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario1-Create payment with confirm true/Payments - Retrieve/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario11-Create Partial Capture payment/Payments - Capture/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario11-Create Partial Capture payment/Payments - Retrieve/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario2-Create payment with confirm false/Payments - Confirm/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario2-Create payment with confirm false/Payments - Retrieve/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario3-Create payment without PMD/Payments - Confirm/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario3-Create payment without PMD/Payments - Retrieve/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario4-Create payment with Manual capture with confirm false/Payments - Capture/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario4-Create payment with Manual capture with confirm false/Payments - Retrieve/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario4-Create payment with Manual capture/Payments - Capture/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario4-Create payment with Manual capture/Payments - Retrieve/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario8-Create payment with Manual capture with confirm false and surcharge_data/Payments - Capture/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Happy Cases/Scenario8-Create payment with Manual capture with confirm false and surcharge_data/Payments - Retrieve/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Variation Cases/Scenario4-Capture the succeeded payment/Payments - Create/event.test.js
- postman/collection-dir/paypal/Flow Testcases/Variation Cases/Scenario5-Void the success_slash_failure payment/Payments - Create/event.test.js
Update status from processing to succeeded in paypal postman collection
Test cases were failing
> ci(postman): Update status for paypal postman collection

- crates/hyperswitch_connectors/src/connectors/taxjar.rs
- crates/hyperswitch_connectors/src/connectors/taxjar/transformers.rs
- crates/router/src/core/payments/operations/tax_calculation.rs
- handle connector errors for tax calculation flow to avoid 5xx
1. Create a Merchant Account 
```
--data-raw '{
"merchant_id": "merchant_1725535996",
"address": { …
```
> refactor(router): handle connector errors for tax calculation flow

- crates/router/src/types/transformers.rs
This PR refactors the way in which `billing.email` is populated in the dynamic fields. In case `billing.email` is not present, then use the `customer.email` to populate this value.
This PR is used to fix merchant integrations where instead of `billing.email` they are passing `customer.email`
- Create a cybersource connector, enable cards payment method
- Create a payment with customer email at the root level
```bash
--header 'api-key: dev_FiFhMeCc1lJOZXPLYSlMd77dzN6ozGzvdfjJS5ul33J6UEJFRVDUi6mYBc6uPN7m' \
--data-raw '{
"payment_id": "pay_1726747163",
"customer_id": "cus_123",
"email": "example@gmail.com" …
```
> refactor(dynamic_fields): populate `billing.email` with customer email if not present

- crates/router/src/configs/defaults.rs
This is to extend the feature of [collect address details](https://github.com/juspay/hyperswitch/pull/5418) to collect `billing.email` and `shipping.email`.
-> Create a merchant account
-> Set the below config in the business profile
```
curl --location 'http://localhost:8080/account/merchant_1726839405/business_profile/pro_TwNiv0vtGBct5t1SLyhm' \
--header 'api-key: *' \
--data '{
"collect_billing_details_from_wallet_connector": false,
"collect_shipping_details_from_wallet_connector": false,
"always_collect_shipping_details_from_wallet_connector": true,
"always_collect_billing_details_from_wallet_connector": true
}'
```
```
{
"merchant_id": "merchant_1726839405",
"profile_id": "pro_TwNiv0vtGBct5t1SLyhm", …
```
> refactor(router): add `email` in `billing` and `shipping` address of merchant payment method list

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/common_enums/src/enums.rs
- docs/TERMS_OF_CONTEST.md
> docs: add terms and conditions

- cypress-tests-v2/cypress/e2e/spec/Payment/0000-CoreFlows.cy.js
- cypress-tests-v2/cypress/e2e/spec/Routing/0000-Coreflows.cy.js
- cypress-tests-v2/cypress/support/commands.js
coming from https://github.com/juspay/hyperswitch/pull/5883
In this pr:
- update merchant account endpoints
- fix error messages
- make cypress throw error an error if connector name is missing during mca create call
- introduce list apis
be up-to-date with hyperswitch v2
|CI|UI|
|-|-|
|<img width="877" alt="image" src="https://github.com/user-attachments/assets/3a9e718c-0bc9-48e2-899a-78d28a41fe25">|<img width="481" alt="image" src="https://github.com/user-attachments/assets/469d6445-bc2c-4373-b031-4dd5c3eaf11d">|
failures are genuine (404):
- update api key endpoint
- list api key endpoint
These failures should be fixed in https://github.com/juspay/hyperswitch/pull/5980
> feat(cypress-v2): introduce list apis to cypress v2

- crates/api_models/src/events/user_role.rs
- crates/api_models/src/user_role.rs
- crates/api_models/src/user_role/role.rs
- crates/router/src/core/user_role.rs
- crates/router/src/core/user_role/role.rs
- crates/router/src/routes/user_role.rs
- crates/router/src/utils/user_role.rs
- Adds entity_type filter in list users and list roles API.
Closes #5996.
1. List Users
```
curl 'http://localhost:8080/user/user/v2/list' \
-H 'authorization: Bearer JWT' \
```
This should respond with all the users who are at the same level and lower.
```
curl 'http://localhost:8080/user/user/v2/list?entity_type=organization' \
-H 'authorization: Bearer JWT' \
```
This can only be hit by org level users and only responds with org level users.
```
curl 'http://localhost:8080/user/user/v2/list?entity_type=merchant' \
-H 'authorization: Bearer JWT' \
```
This can only be hit by merchant and org level users and only responds with merchant level users.
```
curl 'http://localhost:8080/user/user/v2/list?entity_type=profile' \
-H 'authorization: Bearer JWT' \
```
This can only be hit by …
> feat(users): Add entity type filter in list users and list roles API

- api-reference-v2/api-reference/api-key/api-key--list.mdx
- api-reference-v2/mint.json
- api-reference-v2/openapi_spec.json
- api-reference/api-reference/api-key/api-key--list.mdx
- api-reference/mint.json
- api-reference/openapi_spec.json
- crates/api_models/src/api_keys.rs
- crates/api_models/src/events.rs
- crates/common_utils/src/events.rs
- crates/openapi/src/openapi.rs
- crates/openapi/src/openapi_v2.rs
- crates/openapi/src/routes/api_keys.rs
- crates/router/src/routes/api_keys.rs
This PR fixes `404` errors thrown by API Key List and Update endpoints.
Previously:
Update end point:
```curl
curl --location --request PUT '{{baseUrl}}/v2/api_keys/{{api_key_id}}' \
--header 'x-merchant-id: {{mechant_id}}' \
--header 'api-key: {{admin_api_key}}' \
--data '{
"name": "My new Api Key"
}'
```
```json
wrong number of parameters: 1 expected 2
```
List end point:
```curl
curl --location '{{baseUrl}}/v2/api_keys/list' \
--header 'x-merchant-id: {{mechant_id}}' \
--header 'api-key: {{admin_api_key}}'
```
```json
wrong number of parameters: 0 expected 1
```
endpoints under `v2` flags were not properly handled in `api_keys.rs` file and this PR fixes that.
closes #5979
tested it by running locally. …
> fix(api_key): fix api key `list` and `update` endpoints for v2

- crates/router/src/core/payments/operations/payment_response.rs
Add support for setup mandate payments to show connector_mandate_id
- Create a MA and MCA
- Create a 0 dollar payment , the connector_mandate_details should be populated in the response
```
{
"payment_id": "pay_u9daXin9p77AD1e4OudT",
"merchant_id": "merchant_1727343268",
"status": "succeeded",
"amount": 0,
"net_amount": 0,
"connector": "stripe",
"client_secret": "pay_u9daXin9p77AD1e4OudT_secret_BwUFsGfYpSRg8xjosR4e",
"created": "2024-09-26T09:40:24.193Z",
"customer_id": "CustomerX7777",
"customer": {
"id": "CustomerX7777",
"phone_country_code": "+65"
},
"refunds": null,
"disputes": null,
"mandate_id": …
```
> fix(core): Fix connector mandate details for setup mandate

- crates/api_models/src/payments.rs
- crates/router/src/core/payments/flows/session_flow.rs
We need to restructure the Samsung Pay session token data stored in the connector wallet details as going forward we will add support for samsung pay payments with hyperswitch credentials. Then the samsung pay payment can be done using either merchant's credentials or hyperswitch's credentials. If it is  merchant's credentials, it needs to be provided in the time of the merchant connector account creation. 
But when it comes to hyperswitch's credentials flow, merchant will provide only merchant specific business information (like merchant name that should be displayed to customer during the payment and merchant's business country). Whereas the private key or the required Samsung Pay certificates for the decryption will reside in the application env.
```
"connector_wallets_details": { …
```
> refactor(router): restructure `Samsung Pay` connector wallet details

- Cargo.lock
- crates/api_models/src/payments.rs
- crates/cards/Cargo.toml
- crates/cards/src/validate.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/connector/bankofamerica/transformers.rs
- crates/router/src/connector/cybersource/transformers.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_update.rs
Reverts juspay/hyperswitch#5801
> feat(router): revert support for co-badged cards

- crates/router/src/routes/admin.rs
- crates/router/src/services/authentication.rs
Previously, updating and retrieving organization details required authentication using the admin API key. With the recent change, the dashboard JWT can now be used to update the org_name directly through the dashboard.
Closes #6141
Request : 
```
curl --location --request PUT 'http://localhost:8080/organization/${org_id}' \
--data '{
"organization_name":"RiddhiTest3"
}'
```
Response:
```
{
"organization_id": "org_id",
"organization_name": "RiddhiTest3",
"organization_details": null,
"metadata": null,
"modified_at": "2024-09-27 07:13:13.074956",
"created_at": "2024-09-19 12:46:25.990045"
}
```
Request :
```
curl --location 'http://localhost:8080/organization/${org_id}' \ …
```
> fix(admin): Add JWT Auth for Org Read and Update APIs

- crates/router/src/connector/signifyd.rs
Described in #5956 
Fixes 5xx thrown by payments API when FRM flows are consumed.
Locally - using an increased stack size.
> fix(connector): update API endpoints for signifyd

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
- crates/router/src/connector/adyenplatform/transformers/payouts.rs
This add wasm configs for adyen platform and fix the deserialization issue due to wrong status mapping
- Configure webhook in adyen platform dashboard
- Create a payout through adyen platform:
```
{
"amount": 100,
"customer_id": "sakilcust",
"priority": "regular",
"bank": {
"iban": "NL91ABNA0417164300"
}
},
"billing": {    
"address": {
"line1": "Raadhuisplein",
"line2": "92",
"city": "Hoogeveen",
"state": "FL",
"zip": "7901 BW",
"country": "NL",
},
"phone": {
"number": "0650242319",
"country_code": "+31"
}
},
"entity_type": …
```
> fix(connector): [Adyen Platform] wasm configs and webhook status mapping

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/retry.rs
add profile level auto retries config support
Auto retries can now be configured at profile level, by providing `is_auto_retries_enabled` and `max_auto_retries_enabled` values in profile
is_auto_retries_enabled - denoted whether auto retries is enabled
max_auto_retries_enabled - maximum number of auto retries allowed for a payment
CURL to add GSM rule
```
curl --location '{{BASE_URL}}/gsm' \
--header 'api-key: {{ADMIN_API_KEY}}' \
--data '{
"connector": "cybersource",
"flow": "Authorize",
"sub_flow": "sub_flow",
"code": "SERVER_ERROR",
"message": "Error - General system failure.",
"status": "Failure",
"router_error": null,
"decision": "retry",
"step_up_possible": true
}'
```
1. Enable Merchant configs and test auto retries flow …
> feat(router): add profile level auto retries config support

- crates/router/src/connector/iatapay/transformers.rs
`preferredCheckoutMethod` should not be passed for `upi_collect` payments via `iatapay`.
https://github.com/juspay/hyperswitch/issues/6208
UPI Collect payments need to be tested via Iatapay
Request:
```
--header 'api-key: dev_r4eLn371GGyhV4kCH3lk3JyBhcYNSVnAn78qel2Gkaea5l8p7rCjNvwQGDnKof3s' \
--data-raw '{
"amount": 8765,
"upi": {
"upi_collect": [
"successtest@iata"
]
}
}
}'
```
Response:
```
{
"payment_id": "pay_19AjvjO4zAf7Mi11nmr7",
"merchant_id": "merchant_1727943265",
"status": …
```
> fix(bug): [IATAPAY] Fix PCM value for UPI_COLLECT

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/router/src/connector/stripe/transformers.rs
'reference' added in sepa_bank_instructions, for Stripe Sepa Bank Transfer 
https://github.com/juspay/hyperswitch/issues/6014
Request
~~~
--header 'api-key: <apiKey>' \
--data-raw '{
"amount": 60,
"customer_id": "StripeCustomer", 
"payment_method_type": "sepa",
"bank_transfer": {
"sepa_bank_transfer" : {
"billing_details" : {
"email" : "gmail@rajanikanth.com",
"name" : "Rajanikanth"
},
"country" : "DE"
}
}
}
}'
~~~
The successful output :
~~~
{
"payment_id": "pay_bLamnDrh3V3GefetEL3Tm",
"merchant_id": "merchant_1727948661", …
> fix: add `reference` in `sepa_bank_instructions`

- README.md
- docs/try_local_system.md
Changed the links to point to:
https://github.com/juspay/hyperswitch/blob/main/docs/try_local_system.md#running-additional-services
Fixes #6242.
Manually checked the links.
> docs: fix broken links to Running Additional Services

- crates/router/src/configs/defaults.rs
sepa in payment method data is renamed to sepa_bank_debit
- Create a payment intent(confirm should be false):
```
{
"amount": 100,
"payment_method": "bank_debit",
"payment_method_type": "sepa",
"bank_debit": {
"sepa_bank_debit": {
"billing_details": {
"houseNumberOrName": "50",
"street": "Test Street",
"city": "Amsterdam",
"stateOrProvince": "NY",
"postalCode": …
```
> refactor(dynamic_fields): rename sepa in dynamic fields

- crates/router/src/connector/trustpay.rs
Payments - Create request
~~~
--header 'api-key: dev_7aPO2c5oIxjntPGv0r45rDbGYgc1Z6LKTglgEQw10yEuFcGC4Zq3pyZ5BO80RiLS' \
--data-raw '{
"amount": 20,
"amount_to_capture": 20,
"profile_id": null,
"setup_future_usage": "on_session", 
"customer": {
"id": "customer123",
"email": "customer@gmail.com",
"phone": "9999999999",
},
"customer_id": "customer123", …
> fix(users): Trustpay refund url update

- crates/hyperswitch_connectors/src/connectors/deutschebank/transformers.rs
SEPA only supports mandate payments, and Deutsche Bank also supports this. To facilitate one-off payments via SEPA with Deutsche Bank, we are considering not storing the connector mandate ID in our system if future usage is on-session. We will only check for customer acceptance to make a one-off payment. we will be storing the connector mandate details only when setup future usage is off-session.
<details>
<summary>Sepa one off payments create </summary>
```
--header 'api-key: ••••••' \
--data '{
"amount": 1650,
"customer_id": "customer123"
}'
```
</details>
<details>
<summary> Sepa one off payments confirm </summary> …
> fix(connector): [deutsche bank] add support for sepa one-off payments

- Cargo.lock
- Makefile
- crates/cards/Cargo.toml
- crates/cards/src/validate.rs
Due to dependency issue, wasm build was failing but this fixes the issue
> fix(euclid_wasm): update dependency for wasm in validate.rs

- cypress-tests/cypress/e2e/PaymentUtils/Paypal.js
Updated error codes for deprecated payment methods (Giropay and Sofort) to reflect recent changes for Paypal connector
Tests were failing for paypal
Cypress
> ci(cypress): Update error message for deprecated payment methods

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
remove placeholder from novalnet webhooks secret
> fix(connector): remove placeholder from novalnet webhooks secret

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
- crates/hyperswitch_connectors/src/connectors/fiuu.rs
- crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
> feat(connector): add dynamic duitnow qr code, google pay and applpepay for fiuu 

- crates/router/src/connector/adyenplatform/transformers/payouts.rs
dyen platform removed the priority field from the webhook object put into the categoryData object inside webhook object. This in an api contract change which was causing deserialization error.
- Create an mca with merchant_secret of adyenplatform (hmac key): 
```
{
"connector_type": "payout_processor",
"connector_name": "adyenplatform",
"api_key": "{{adyen_platform_api_key}}"
},
"metadata": {
"city": "NY",
"unit": "245",
"source_balance_account": "{{adyen_platform_balance_account_id}}"
},
"connector_webhook_details": {
"merchant_secret": "{{merchant_secret}}"
}
}
```
- Setup webhook endpoint at adyenplatform dasbhoard
- Create a payment through adyenplatform
```
{
"amount": 100,
"currency": …
```
> refactor(connector): [Adyen platform] api contract change for webhook

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/sandbox.toml
Enable Paze Wallet for Cubersource on Dashboard
https://github.com/juspay/hyperswitch/issues/6303
Only config changes hence no testing required.
> feat(connector): [CYBERSOURCE] Add paze dashboard configs

- crates/router/src/core/payments/flows/session_flow.rs
-> Create a connector with samsung pay enabled
-> Create a payment
```
--header 'api-key:' \
--data '{
"amount": 100000,
"customer_id": "cu_1728548597"
}'
```
```
{
"payment_id": "pay_mJFt25nBNl0ZKeW122Eu",
"merchant_id": "merchant_1728917453",
"status": "requires_payment_method",
"amount": 100000,
"net_amount": 100000,
"connector": null,
"client_secret": "pay_mJFt25nBNl0ZKeW122Eu_secret_ssXacvSHe4w7Q6smAWOQ",
"created": "2024-10-14T14:51:05.156Z",
"customer_id": "cu_1728548597", …
```
> fix(router): replace underscore by hyphen in Samsung pay session call

- README.md
Fixes #6294.
Manual check of the README.md file.
> docs(README): remove FAQs section

- api-reference/essentials/error_codes.mdx
> docs(error_codes): add unified error codes

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/common_enums/src/enums.rs
- crates/hyperswitch_domain_models/src/router_request_types.rs
- crates/hyperswitch_domain_models/src/router_response_types.rs
- crates/hyperswitch_interfaces/src/types.rs
- crates/router/src/connector/paypal.rs
- crates/router/src/connector/paypal/transformers.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/flows.rs
- crates/router/src/core/payments/operations/payment_approve.rs
- crates/router/src/core/payments/operations/payment_cancel.rs
- crates/router/src/core/payments/operations/payment_capture.rs
- crates/router/src/core/payments/operations/payment_complete_authorize.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_post_session_tokens.rs
- crates/router/src/core/payments/operations/payment_reject.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/payments/operations/payment_session.rs
- crates/router/src/core/payments/operations/payment_start.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payments/operations/payment_update.rs
- crates/router/src/core/payments/operations/payments_incremental_authorization.rs
- crates/router/src/core/payments/operations/tax_calculation.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types.rs
- crates/router/tests/connectors/utils.rs
- implement session update flow for Paypal
- implement post_update_tracker for SessionUpdate Flow 
hotfix for [PR](https://github.com/juspay/hyperswitch/pull/6299)
1. Create Merchant Account
```
--data-raw '{
"merchant_id": "merchant_1728546485",
"about_business": "Online Retail …
```
> feat(router): implement post_update_tracker for SessionUpdate Flow and add support for session_update_flow for Paypal

- crates/hyperswitch_connectors/src/connectors/mollie.rs
- crates/hyperswitch_connectors/src/connectors/mollie/transformers.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/mollie.rs
This PR do amount conversion changes for Mollie Connector and it accepts the amount in StringMajorUnit
Fixes https://github.com/juspay/hyperswitch/issues/6092
1. Create Merchant Account
```
--data-raw '{
"merchant_id": "merchant_1729161609",
"primary_business_details": [
{
"business": "default"
},
{
"country": "GB",
"business": "payouts"
}
],
"secondary_email": …
```
> refactor(connector): added amount conversion framework for Mollie

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/router/src/core/payments/flows/session_flow.rs
The merchant domain url is only required in case of samsung pay payments on web. While processing payments on app the merchant domain is not required. Hence mandate the merchant domain only if the `x-client-platform` is `web`
-> Create a connector with samsung pay enabled
-> Create a payment
```
--header 'api-key: dev_GhK0bBcXMIVjqoKmEip0XbSEvPXOuaEOLlMdBQWL4gdD51LsgHsjj2vzyuxMahw1' \
--data '{
"amount": 100000,
"customer_id": "cu_1728548597"
}'
```
```
{
"payment_id": "pay_rXRkcJK4eiTFnb29Meks",
"merchant_id": "merchant_1729239061",
"status": …
```
> fix(router): make `x_merchant_domain` as required value only for session call done on web

- .github/workflows/cypress-tests-runner.yml
- cypress-tests/README.md
- scripts/execute_cypress.sh
This PR updates Cypress documentation as it was outdated that resulted in confusion among users of Cypress, we'll be stop sourcing the script.
Me. Myself.
See if Cypress Ci runs without any errors.
> docs(cypress): refactor cypress documentation for more clarity

- crates/common_utils/src/types.rs
- crates/router/src/connector/wellsfargo.rs
- crates/router/src/connector/wellsfargo/transformers.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/wellsfargo.rs
This PR do amount conversion changes for Wellsfargo Connector and it accepts the amount in StringMajorUnit
Fixes https://github.com/juspay/hyperswitch/issues/6024
> refactor(connector): add amount conversion framework to Wellsfargo

- crates/router/src/core/payment_methods.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/payments/tokenization.rs
- Billing address was empty during payment request with payment_method_id
- This is due to not saving billing_address in payment_methods table while generating payment_method_id
- Create an MCA (Cybersource):
- Create a Zero Dollar Payment:
```
{
"amount": 0,
},
"accept_header": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
"language": "nl-NL",
"color_depth": 24,
"screen_height": 723, …
```
> fix(core): populate billing_address for payment with pm_id

- crates/api_models/src/payment_methods.rs
- crates/router/src/core/payment_methods/migration.rs
- crates/router/src/routes/payment_methods.rs
Introduced new fields in migrate batch api - `merchant_id` and `merchant_connector_id` 
req - 
```
curl --location 'http://localhost:8080/payment_methods/migrate-batch' \
--header 'api-key: api-key' \
--form 'file=@"path_to_csv_file"' \
--form 'merchant_id="merchant_id"' \
--form 'merchant_connector_id="merchant_connector_id"'
```
> fix(router): Update request body for migrate-batch api

- crates/router/src/core/payments/operations/payment_response.rs
Earlier, for setup mandate flows we were not populating  the Payment Method Info field, due to which for the Setup Mandate Payments the connector_mandate_details where not getting populated in the payment methods table.  This PR fixes setup mandate payments to store connector mandate details, in the payment methods table.
- Create a Off -session payment , with 0 dollar
```
Create
--header 'api-key: dev_x0Y92cBUtNSQwvW9B6xfQRtg8NxoURcyMbGh9kiqxO5EfMidDo31Ji6McelAQv9M' \
--data-raw '{
"amount": 0,
"customer_id": "CustomerX777",
"capture_on": …
```
> fix(core): fix setup mandate payments to store connector mandate details

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
remove placeholder from novalnet webhooks secret
> fix(connector): [Novalnet] Remove webhook placeholder connector config

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
> docs: Added desc. for wallets other than AP, GP

- README.md
TOC icon and reposition of the hero image in readme
Updated the icon of CI Push and repositioned the hero image
closes #6449
> docs(README): Updated the icon and repositioned the hero image

- crates/router/src/connector/wise.rs
- crates/router/src/connector/wise/transformers.rs
- crates/router/src/types/api.rs
- crates/router/tests/connectors/wise.rs
This pull request introduces significant changes to the Wise connector in the `crates/router` module, focusing on the integration of a new amount conversion utility and refactoring to utilize a new `WiseRouterData` struct. The changes enhance how amounts are handled and improve the overall structure and clarity of the code.
* **Amount Conversion Utility Integration:**
- Added `amount_converter` to the `Wise` struct and integrated it into the `new` method.
- Updated `convert_amount` usage in `WisePayoutQuoteRequest` and `WiseRecipientCreateRequest` implementations to use the new `amount_converter`. [[1]](diffhunk://#diff-a149ab1c35f89dd3b0eed2fca15df170708e81962550226b958ae6c367515043L365-R382) [[2]](diffhunk://#diff-a149ab1c35f89dd3b0eed2fca15df170708e81962550226b958ae6c367515043L444-R467) …
> refactor(connector): Added amount conversion framework to Wise.

- api-reference/api-reference/api-key/api-key--create.mdx
- api-reference/api-reference/api-key/api-key--revoke.mdx
- api-reference/api-reference/routing/routing--activate-config.mdx
- api-reference/api-reference/routing/routing--retrieve.mdx
Fixed broken API reference for the following endpoints:
- `API Key - Create`
- `API Key - Revoke`
- `Routing - Retrieve`
- `Routing - Activate Config`
> fix(docs): Fix broken pages in API reference

- crates/router/src/connector/adyen.rs
- crates/router/src/connector/adyen/transformers.rs
Integrate Wallet Paze in Adyen.
https://github.com/juspay/hyperswitch-cloud/issues/7422
We are unable to test this flow for now due to unavailability of adyen test cards via our paze wallet.
> feat(connector): [ADYEN] Integrate Paze

- crates/hyperswitch_connectors/src/connectors/worldpay/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
- cypress-tests/cypress/e2e/PaymentUtils/WorldPay.js
Described in #6316 point # 7
Helps in transforming expiry date format into a 4 digit value for card payments for worldpay connector!
<details>
<summary>1. Create a payment using 2 digit expiry year</summary>
cURL
--header 'api-key: dev_vK8vdO0cS4wec9MP0W3K8eR0GfgrVoY0oxuhJrx4rCBJm7wxoH16bOdx9fLKvYSc' \
--data-raw '{"amount":6500,"currency":"USD","confirm":true,"capture_method":"automatic","capture_on":"2022-09-10T10:11:12Z","customer_id":"cus_L8pJ8g0mnsdHmS0FPqrH_4","email":"guest@example.com","name":"John Doe","phone":"999999999","profile_id":"pro_1frLOUlLMVZWSYwOz3En","phone_country_code":"+65","description":"Its my first payment …
> fix(connector): [Worldpay] use 4 digit expiry year

- crates/router/src/utils.rs
- cypress-tests-v2/cypress/e2e/configs/Payment/Commons.js
- cypress-tests-v2/cypress/e2e/configs/Payment/Utils.js
- cypress-tests/cypress/e2e/PaymentUtils/Commons.js
- cypress-tests/cypress/e2e/PaymentUtils/Paybox.js
- cypress-tests/cypress/e2e/PaymentUtils/Utils.js
> refactor: update API response for JSON deserialization errors

- crates/router/src/connector/cybersource/transformers.rs
Change the commerce indicator for cybersource applepay payment which was failing payment in production
Note: This pr is crucial for flowbird
- Create an MCA for Cybersource:
- Create a Payment with Applepay: 
```
{
"amount": 650, …
```
> fix(connector): [Cybersource] change commerce indicator for applepay

- crates/router/src/connector/adyen/transformers.rs
Fetch email from customer email whenever billing email is not present for payment request 
Tested locally in Postman 
[Testing Doc](https://docs.google.com/document/d/1IFP36183A8gMwJz0gB8hHi2nIoTLgmppE15XM5g0yz0/edit?usp=sharing)
> feat(connector): [Adyen] Fetch email from customer email for payment request

- crates/router/src/core/user.rs
Currently we are not marking users as verified if the user comes from SSO and there is no other way to verify if SSO is the only login method that is available.
Closes #6693.
```
curl 'http://localhost:9000/api/user/oidc' \
-H 'Content-Type: application/json' \
--data-raw '{"code":"okta oidc code","state":"okta oidc state"}'
```
- The above curl when hit correctly should verify the user if the user was unverified.
> fix(users): Mark user as verified if user logins from SSO

- cypress-tests/cypress/e2e/PaymentMethodListUtils/Stripe.js
- cypress-tests/cypress/e2e/PaymentUtils/BankOfAmerica.js
- cypress-tests/cypress/e2e/PaymentUtils/Checkout.js
- cypress-tests/cypress/e2e/PaymentUtils/Commons.js
- cypress-tests/cypress/e2e/PaymentUtils/Cybersource.js
- cypress-tests/cypress/e2e/PaymentUtils/Datatrans.js
- cypress-tests/cypress/e2e/PaymentUtils/Elavon.js
- cypress-tests/cypress/e2e/PaymentUtils/Fiservemea.js
- cypress-tests/cypress/e2e/PaymentUtils/Nexixpay.js
- cypress-tests/cypress/e2e/PaymentUtils/Nmi.js
- cypress-tests/cypress/e2e/PaymentUtils/Novalnet.js
- cypress-tests/cypress/e2e/PaymentUtils/Paybox.js
- cypress-tests/cypress/e2e/PaymentUtils/Paypal.js
- cypress-tests/cypress/e2e/PaymentUtils/Stripe.js
- cypress-tests/cypress/e2e/PaymentUtils/Trustpay.js
- cypress-tests/cypress/e2e/PaymentUtils/WellsFargo.js
- cypress-tests/cypress/e2e/RoutingUtils/Stripe.js
- cypress-tests/cypress/fixtures/create-confirm-body.json
- cypress-tests/cypress/fixtures/create-mandate-cit.json
- cypress-tests/cypress/fixtures/create-ntid-mit.json
this pr increments expiry year to a later date
closes https://github.com/juspay/hyperswitch/issues/6713
4xx
ci should pass
> ci: update ntid card expiry

- .github/workflows/cypress-tests-runner.yml
Disable payouts in github ci check 
Checks are failing because  of connector error
> ci(cypress): disable payouts in PR check 

- crates/api_models/src/admin.rs
- crates/diesel_models/src/business_profile.rs
- crates/diesel_models/src/schema.rs
- crates/diesel_models/src/schema_v2.rs
- crates/hyperswitch_domain_models/src/business_profile.rs
- crates/router/src/core/admin.rs
- crates/router/src/types/api/admin.rs
- migrations/2024-12-04-072648_add_is_click_to_pay_enabled/down.sql
- migrations/2024-12-04-072648_add_is_click_to_pay_enabled/up.sql
- v2_migrations/2024-12-04-072823_add_is_click_to_pay_enabled/down.sql
- v2_migrations/2024-12-04-072823_add_is_click_to_pay_enabled/up.sql
add is_click_to_pay_enabled in business profile
Create Business Profile
Request:
```shell
curl --location 'http://localhost:8080/account/merchant_1733299712/business_profile' \
--data '{
"profile_name": "foodddijiqw",
"business_specific_configs": {
"key1": {
"theme": "#3B845E",
"logo": "https://i.pinimg.com/736x/4d/83/5c/4d835ca8aafbbb15f84d07d926fda473.jpg",
"seller_name": "sahkal",
"display_sdk_only": true
},
"key2": {
"theme": "#B202FF",
"logo": "https://i.pinimg.com/736x/4d/83/5c/4d835ca8aafbbb15f84d07d926fda473.jpg",
"seller_name": "sahkal",
"enable_saved_payment_method":true
}
}
},
"is_click_to_pay_enabled": true
}'
```
Response
```shell
{
"merchant_id": "merchant_1733299712", …
```
> feat(core): add is_click_to_pay_enabled in business profile

- crates/router/src/core/payment_link/locale.js
Add support for traditional chinese locale for payment links
SDK PR  https://github.com/juspay/hyperswitch-web/pull/822
(Need to run both hyperswitch-web and hyperswitch locally to test)
<details>
<summary>1. Update `allowed_domains` in business profile (Expand to see details)</summary>
``` 
curl --location 'http://localhost:8080/account/merchant_1733317126/business_profile/pro_I5CYJ8tVS6OHA1GMcXaW' \
--data '{
"*"
],
"enabled_saved_payment_method": true,
"hide_card_nickname_field" : true
}
}'
```
</details>
<details>
<summary>2. Create a payment link with Accept-Language header as "zh-Hant" </summary>
cURL
`curl --location --request POST …
> feat(payments): [Payment links] Add support for traditional chinese locale for payment links

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
Described in #6316 point # 8
This PR includes WASM changes for Worldpay MCA creation on dashboard.
Updates the incorrect mapping of username / password to HS `ConnectorAuthType`
> refactor(connector-configs): worldpay - update username / password mapping

- crates/diesel_models/src/payment_method.rs
- crates/hyperswitch_domain_models/src/router_flow_types/webhooks.rs
- crates/hyperswitch_interfaces/src/webhooks.rs
- crates/router/src/connector/adyen.rs
- crates/router/src/connector/adyen/transformers.rs
- crates/router/src/core/webhooks/incoming.rs
- crates/router/src/services/connector_integration_interface.rs
Hotfix for https://github.com/juspay/hyperswitch/pull/6738
> feat(webhooks): adyen - consume and update connector's network_transaction_id in payment_methods

- crates/api_models/src/analytics.rs
Currently, while generating reports on the dashboard, the current setup only supports forwarding reports to the email of the account signed in.
This PR adds support to have custom emails in the input text box on the dashboard while generating and forwarding the report, to make the reporting module slightly flexible and convenient.
- Adding the field for taking multiple emails as input in the report request body.
- Currently having it as an Option, for backwards compatibility.
To make the reporting module slightly flexible and convenient, to send the report to emails entered by the users.
Hit the curl:
```bash
curl --location 'http://localhost:8080/analytics/v1/org/report/payments' \ …
```
> feat(analytics): add support for multiple emails as input to forward reports

- CHANGELOG.md
- crates/hyperswitch_interfaces/src/events/connector_api_logs.rs
- crates/router/src/core/webhooks/incoming.rs
- crates/router/src/core/webhooks/incoming_v2.rs
- crates/router/src/core/webhooks/outgoing.rs
- crates/router/src/events/api_logs.rs
- crates/router/src/events/outgoing_webhook_logs.rs
- crates/router/src/services/api.rs
The changes are required for pushing tenant ID for API events, Connector events and Outgoing Webhook events
Attaching screenshots
> refactor(events): Tenant config in API, Connector and Outgoing Web-hook events

- crates/router/src/core/payment_link/locale.js
hotfix for https://github.com/juspay/hyperswitch/pull/6789
> feat(payments): [Payment links] Add locale case fix

- crates/api_models/src/payments.rs
- crates/hyperswitch_domain_models/src/payment_method_data.rs
- crates/router/src/core/payment_methods/vault.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/utils/verify_connector.rs
- crates/router/tests/connectors/aci.rs
- crates/router/tests/connectors/adyen.rs
- crates/router/tests/connectors/airwallex.rs
- crates/router/tests/connectors/fiserv.rs
- crates/router/tests/connectors/rapyd.rs
- crates/router/tests/connectors/utils.rs
- crates/router/tests/connectors/worldline.rs
- cypress-tests/cypress/e2e/PaymentUtils/Cybersource.js
- cypress-tests/cypress/e2e/PaymentUtils/Stripe.js
This PR contains below changes
1. Map billing's first and last name to card holder's name
2. Preserve card holder's name across different data models (API / domain / vault)
This helps in preserving the card holder name being persisted in HyperSwitch systems. And also helps populate card holder name from billing details.
Things to validate
- Card holder name in payments response when payment_method_data.card.card_holder_name is not passed should be same as billing's first and last name
- Card holder name in payments response in not mapped to card's nick_name
<details>
<summary>1. Do not pass card_holder_name but pass billing's first and last name</summary>
cURL …
> fix(core): payments - map billing first and last name to card holder name

- Cargo.lock
- crates/api_models/src/admin.rs
- crates/router/src/types/api/admin.rs
Mask custom outgoing webhook headers in profile response. This changes is required to mask the custom outgoing webhook headers in the profile dashboard. This also requires control center changes, BE changes will only be merged and 
deployed after dashboard changes.
Test Case 1 : Profile create 
```
curl --location 'http://localhost:8080/account/merchant_1733900220/business_profile' \
--header 'api-key: ••••••' \
--data-raw '{
"profile_name" : "test_profile1",
"webhook_details": {
"webhook_url": "https://webhook.site/672f0697-9e14-4a49-abef-b15769c19962",
"webhook_version": "1.0.1",
"webhook_username": "ekart_retail",
"webhook_password": "password_ekart@123",
"payment_created_enabled": true,
"payment_succeeded_enabled": true, …
```
> fix(webhooks): mask custom outgoing webhook headers in profile response

- cypress-tests/cypress/e2e/PaymentUtils/Commons.js
- cypress-tests/cypress/e2e/PaymentUtils/Paypal.js
Add mandates flow to paypal which they started handling recently 
Test cases were failing in cypress automation
(Bank redirects started throwing internal error after redirection which needs to be fixed )
> ci(cypress): Add Paypal Mandates

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/hyperswitch_domain_models/src/payments.rs
- crates/router/src/consts.rs
change click_to_pay const to snake_case and remove camel_case serde rename for clicktopay metadata
```
curl --location 'localhost:8080/payments/session_tokens' \
--header 'api-key: pk_dev_1d6e3c969ee44dc1877257462954b31e' \
--data '{
"payment_id": "pay_Xquzo6fvqyN2uWBcXBKK",
"client_secret": "pay_Xquzo6fvqyN2uWBcXBKK_secret_gXvcFn55sgVFHTOc678K",
"wallets": []
}'
```
Response
```
{
"payment_id": "pay_Xquzo6fvqyN2uWBcXBKK",
"client_secret": "pay_Xquzo6fvqyN2uWBcXBKK_secret_gXvcFn55sgVFHTOc678K",
"session_token": [
{
"wallet_name": "google_pay",
"merchant_info": {
"merchant_name": "Narayan Bhat"
},
"shipping_address_required": false,
"email_required": false,
"shipping_address_parameters": {
"phone_number_required": false
}, …
```
> fix(router): change click_to_pay const to snake_case and remove camel_case serde rename for clicktopay metadata

- crates/router/src/core/payment_methods/cards.rs
This will handel the cases for constraint_graph for PML where setup_future_usage is not passed in payments.
This can be tested in the following way:
1. Connector create (Fiuu)
```
curl --location 'http://127.0.0.1:8080/account/merchant_1733312955/connectors' \
--data '{
"connector_name": "fiuu",
"api_key": ".....",
"key1": "......",
"api_secret": "......"
},
{
{
"payment_method_type": "online_banking_fpx",
"card_networks": …
```
> refactor(constraint_graph): handle PML for cases where setup_future_usage is not passed in payments

- crates/router/src/core/payments/transformers.rs
- cypress-tests/cypress/e2e/PaymentUtils/Stripe.js
`off_session` value needs to be populated based on the value passed in the payment request instead of mapping it using `mandate_id`
[ORIGINAL PR: https://github.com/juspay/hyperswitch/pull/6855]
https://github.com/juspay/hyperswitch/issues/6856
Saved card payment flow via Stripe needs to be tested
Payments Intent:
Request:
```
--header 'api-key: dev_6xYIfowUNa5WtbnutyrwXVAoMGqGjUuhfgSksLrTFWMVhcrdDgOoGAwKMt7xIman' \
--data-raw '{
"amount": 6777,
"customer_id": "new-c77",
"email": …
```
> fix(core): Populate off_session based on payments request

- crates/diesel_models/src/dynamic_routing_stats.rs
- crates/diesel_models/src/schema.rs
- crates/diesel_models/src/schema_v2.rs
- crates/router/src/core/routing/helpers.rs
- migrations/2024-12-16-111228_add_new_col_payment_method_type_in_dynamic_routing_stats/down.sql
- migrations/2024-12-16-111228_add_new_col_payment_method_type_in_dynamic_routing_stats/up.sql
This change will add `payment_method_type` in dynamic_routing_stats.
Testing can be done in following way:
1. Enable Success based routing for a profile with feature as metrics.
2. Make a payment.
3. Search the `dynamic_routing_stats` table for the new col. `payment_method_type` for that payment.
> refactor(dynamic_routing): add col payment_method_type in dynamic_routing_stats

- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
- loadtest/config/development.toml
This PR is a hot fix for the [PR](https://github.com/juspay/hyperswitch/pull/6903/)
> fix(connector): Update mandate PMT configs for Mandate Supported Connectors

- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/core/payments/transformers.rs
- hotfix for -  https://github.com/juspay/hyperswitch/pull/6899
- Revert this [PR](https://github.com/juspay/hyperswitch/pull/6855)
- Pass `setup_future_usage = None` for ConnectorMandateId and NetworkMandateId.
1. Create Merchant
2. Create API KEY
3. Create Stripe connector
```
curl --location 'http://localhost:8080/account/postman_merchant_GHAction_1734681965/connectors' \
--data '{
"profile_id": "pro_iprJnfcIANK2ws8xnWhI",
"api_key": "__"
},
{ …
```
> fix(connector): [STRIPE] fix stripe mandate

- .github/workflows/cypress-tests-runner.yml
- cypress-tests/cypress/e2e/PayoutUtils/AdyenPlatform.js
This PR fixes the cypress payout test cases for AdyenPlatform connector.
Helps in enabling the Adyenplatform connector for payout cypress test cases as a part of Github CI checks.
Locally.
> chore(cypress): payout - fix test cases for adyenplatform bank

- crates/router/src/configs/defaults/payment_connector_required_fields.rs
https://github.com/juspay/hyperswitch/pull/6911
Fix required fileds for wallet mandate payments for cybersource and bank of america.
create payment with cybersource
request : 
```
{
"amount":1001,
"amount_to_capture": 1001,
"card": {
"card_exp_year": "2030", …
```
> fix(connector): [Cybersource] fix the required fields for wallet mandate payments

- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- crates/router/src/routes/relay.rs
disable partial auth feature for relay
> fix(router): disable partial auth feature for relay

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/router/src/core/payments/transformers.rs
Parent issue describing the feature (https://github.com/juspay/hyperswitch/issues/6841)
We need to rename `management_url` to `management_u_r_l` in the apple pay session response as our sdk converts the apple pay session request to camelCase before sending it to the apple pay team, after which  `management_url` will be sent as `managementUrl`. But apple pay expects it to be passed as `managementURL`.
Hence renaming it to `management_u_r_l` as that when it is converted to snake case it will be passed as `managementURL`.
-> create a merchant connector account with apple pay enabled
-> create a payment with recurring details passed in the `feature_metadata`
```
{
"amount": 6500,
"amount_to_capture": 6500,
"capture_method": …
```
> fix(router): rename `management_url` to `management_u_r_l` in the apple pay session response

- crates/router/src/core/payment_methods/cards.rs
Main pr - https://github.com/juspay/hyperswitch/pull/7004
> fix: consider status of payment method before filtering wallets in list pm

- .github/workflows/cypress-tests-runner.yml
Update connector creds for Novalnet
> ci: update cypress creds for Novalnet

- .github/workflows/cypress-tests-runner.yml
updates wise creds
closes #7053
ci should pass
> chore: update creds

- crates/api_models/src/admin.rs
- crates/common_enums/src/enums.rs
- crates/common_types/src/payments.rs
- crates/diesel_models/src/business_profile.rs
- crates/hyperswitch_domain_models/src/business_profile.rs
- crates/hyperswitch_domain_models/src/merchant_connector_account.rs
- crates/router/src/consts.rs
- crates/router/src/core/admin.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/unified_authentication_service.rs
- crates/router/src/core/unified_authentication_service/types.rs
- crates/router/src/core/unified_authentication_service/utils.rs
- crates/router/src/types/api/admin.rs
refactor ctp flow to fetch mca_id and get the connector creds instead of connector_name
Main PR - https://github.com/juspay/hyperswitch/pull/6859
Test cases in Main PR
> refactor(router): refactor ctp flow to fetch mca_id and get the connector creds instead of connector_name

- crates/router/src/core/payment_link/payment_link_initiate/payment_link_initiator.js
- crates/router/src/core/payment_link/payment_link_initiate/secure_payment_link_initiator.js
Hotfix for https://github.com/juspay/hyperswitch/pull/7072
> refactor(payment-link): use shouldRemoveBeforeUnloadEvents flag for handling removal of beforeunload events through SDK

- crates/router/src/core/payments.rs
During the MIT if the decided connector is same as the connector with which the mandate is created then the MIT should be processed with the connector mandate _id.
Connector mandate id based payments have better auth rates than the card details with network transaction id.
-> Create a business profile and enable connector agnostic mandate feature
```
curl --location 'http://localhost:8080/account/merchant_1737444280/business_profile/pro_h1bdGYYiQic3IHdVU1Mm' \
--data '{
"is_connector_agnostic_mit_enabled": true
}'
```
```
{
"merchant_id": "merchant_1737444280",
"profile_id": "pro_h1bdGYYiQic3IHdVU1Mm",
"profile_name": "US_default",
"return_url": "https://google.com/success", …
```
> refactor(router): prioritise `connector_mandate_id` over `network_transaction_id` during MITs

- .github/workflows/cypress-tests-runner.yml
disable sprite.
closes #7184 
...
ci should pass
> ci: disable stripe in cypress

- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
This PR enables country Malaysia for processing APay and GPay transactions via Fiuu
Helps process APay and GPay txns using MYR currency.
For valid currency - MYR
For invalid currency - ex. USD
> chore(connectors): [fiuu] update pm_filters for apple pay and google pay

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/operations/payment_status.rs
Hotfix for [7137](https://github.com/juspay/hyperswitch/pull/7137)
> fix(core): Add payment_link_data in PaymentData for Psync

- crates/hyperswitch_connectors/src/connectors/fiuu.rs
Hotfix for https://github.com/juspay/hyperswitch/pull/7189
- 
-
> chore(connector): [Fiuu] log keys in the PSync response

- crates/common_enums/src/connector_enums.rs
- crates/hyperswitch_connectors/src/connectors/datatrans.rs
- crates/hyperswitch_connectors/src/connectors/datatrans/transformers.rs
Added Support for External 3DS
Not able to test it on Local. Testing will be on integ.
> feat(connector): [DATATRANS] Add Support for External 3DS 

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
Added Wasm changes for Datatrans (acquirer_country_code,acquirer_merchant_id,acquirer_bin)
Just wasm changes
> feat(connector): [Datatrans] Add Wasm Changes 

- crates/router/src/core/payment_link/payment_link_initiate/payment_link_initiator.js
- crates/router/src/core/payment_link/payment_link_initiate/secure_payment_link_initiator.js
Integ and Sbx payment link urls have **/api/** in their path, which currently gets ignored in the url when payment reaches terminal state
-     e.g. url for integ/sbx - https://integ.hyperswitch.io/api/payment_link/merchant_1234/pay_1234?locale=en
-     e.g. url for others (does not have /api/) - https://abc.dev.com/payment_link/merchant_1234/pay_1234?locale=en
After redirection to status screen 
-     e.g. url for integ/sbx becomes - https://integ.hyperswitch.io/payment_link/status/payment_link/merchant_1234/pay_1234?locale=en (payment_link gets duplicated twice, and /api/ is gone)
-     e.g. path for others (does not have /api/) becomes - https://abc.dev.com/payment_link/status/merchant_1234/pay_1234?locale=en (as expected)
Since /api/ gets ignored currently for integ and sbx, the …
> fix(payments): [Payment links] Add fix for payment link redirection url

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
Inespay enablement in dashboard. Added the changes in connector configs.
Nothing to test, just env changes.
> feat(connector): [INESPAY] Enable Inespay In Dashboard

- crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
This PR updates connector integration for SetupMandate flow for Fiuu.
Helps fix zero amount CIT mandate flow for wallets through Fiuu
<details>
<summary>1. Zero amount mandate through GPay (CIT)</summary>
cURL (create a payment link)
--header 'api-key: dev_Z6hI0pxQyHsH240jY8lyalrGGJGyZBtjWhFrxxCmbvEdc7KywJRANdBXFzZ8XO2G' \
--data '{"customer_id":"cus_zO4rCUYOsXWOdZb4Tb8f","profile_id":"pro_9tMbnzk3iyggEiTQDwZi","customer_acceptance":{"acceptance_type":"online","accepted_at":"1963-05-03T04:07:52.723Z","online":{"ip_address":"127.0.0.1","user_agent":"amet irure esse"}},"amount":0,"currency":"EUR","payment_link":true,"setup_future_usage":"off_sess …
> fix(connectors): [fiuu] zero amount mandate flow for wallets

- .github/workflows/nix.yaml
Updates `om` CLI invocation based on this PR - https://github.com/juspay/omnix/pull/417
This fixes CI Nix workflow for GitHub actions which is run as a part of PR checks.
In this PR - CI Nix workflow should not fail.
> ci(nix): update om command invocation

- crates/hyperswitch_connectors/src/connectors/datatrans.rs
- crates/hyperswitch_connectors/src/connectors/datatrans/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
- add mandate flow (zero auth included) for datatrans connector
Create an MCA (Datatrans)
Case 1: (Zero Auth)
- Do a CIT:
```
{
"amount": 0,
"customer_id": "Sakil",
},
"billing": {
"address": {
"city": "Zurich",
"state": "asd",
"zip": "8008",
"country": "CH",
},
"email": "sk.sakil@juspay.in"
},
"accept_header": …
```
> feat(connector): [Datatrans] add mandate flow

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/admin.rs
- crates/api_models/src/payments.rs
- crates/diesel_models/src/business_profile.rs
- crates/diesel_models/src/payment_intent.rs
- crates/hyperswitch_domain_models/src/lib.rs
- crates/router/src/core/payment_link.rs
- crates/router/src/core/payment_link/payment_link_initiate/payment_link.css
- crates/router/src/core/payment_link/payment_link_initiate/payment_link.js
- crates/router/src/core/payment_link/payment_link_initiate/payment_link_initiator.js
- crates/router/src/core/payment_link/payment_link_initiate/secure_payment_link_initiator.js
- crates/router/src/core/payments/transformers.rs
- crates/router/src/macros.rs
- crates/router/src/routes/payments.rs
- crates/router/src/types/transformers.rs
Added below configs for payment link 
1. payment_button_colour: Text for customizing message for card terms
2. custom_message_for_card_terms: Custom background colour for payment link's handle confirm button https://docs.hyperswitch.io/explore-hyperswitch/merchant-controls/integration-guide/web/customization#custom-message-for-card-terms
Tested locally 
```
curl --location --request POST 'http://localhost:8080/account/merchant_1739787034/business_profile/pro_8METe0Ui8phk2DKuovKO' \
--data-raw '{
"*"
],
"payment_button_colour": "#ff69b4",
"custom_message_for_card_terms": "Lorem ipsum odor amet, consectetuer adipiscing elit."
}
}'
```
```
curl --location --request POST …
```
> feat(payments): [Payment links]  Add configs for payment link

- add_connector_updated.md
- scripts/add_connector.sh
updated add_connector.sh script, to make a entry in required places.
> fix(connector): [SCRIPT] Update template generating script and updated connector doc

- crates/hyperswitch_connectors/src/connectors/datatrans/transformers.rs
For connector Datatrans add new payment status: ChallengeOngoing and ChallengeRequired
https://github.com/juspay/hyperswitch/issues/7328
Payments Create:
Request:
```
--header 'api-key: dev_pzCQPy1Bguc8j2kV8DQeqQJHIqJQJCjF5kLyDVep1qhmsjAPfl6GUbb10RId0cr8' \
--data-raw '{
"amount_to_capture": 1000,
"card": {
"card_number": "5404000000000001",
"card_exp_month": "06", …
```
> fix(connector): [DATATRANS] Add new payment status

- crates/hyperswitch_connectors/src/connectors/datatrans/transformers.rs
For connector Datatrans add new payment status: ChallengeOngoing and ChallengeRequired
Fix Deseralization Issue on Force Sync Flow
https://github.com/juspay/hyperswitch/issues/7328
Payments Create:
Request:
```
--header 'api-key: dev_pzCQPy1Bguc8j2kV8DQeqQJHIqJQJCjF5kLyDVep1qhmsjAPfl6GUbb10RId0cr8' \
--data-raw '{
"amount_to_capture": 1000,
"card": {
"card_number": "5404000000000001",
"card_exp_month": "06", …
```
> fix(connector): [DATATRANS] Fix Force Sync Flow

- crates/connector_configs/src/common_config.rs
- crates/connector_configs/src/connector.rs
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
- crates/router/src/connector/netcetera/transformers.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
add merchant_configuration_id in netcetera metadata and make other merchant configurations optional
Main PR - https://github.com/juspay/hyperswitch/pull/7347
Clippy Successful Locally
test cases in main PR
> feat(router): add merchant_configuration_id in netcetera metadata and make other merchant configurations optional

- .github/workflows/cypress-tests-runner.yml
Required changes are made after rotating the api key for stripe
> ci: update creds

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/router/src/core/payments/flows/session_flow.rs
This pull request includes changes to enhance the handling of billing and shipping address requirements for Samsung Pay and Google Pay session tokens. The most important changes include adding new fields to the `SamsungPaySessionTokenResponse` struct, updating the `create_samsung_pay_session_token` function to include these new fields, and refactoring the code to use helper functions for determining address requirements.
Enhancements to session token handling:
* Added `billing_address_required` and `shipping_address_required` fields to the `SamsungPaySessionTokenResponse` struct.
* Updated the `create_samsung_pay_session_token` function to include the new address requirement fields and refactored the logic to use helper functions for determining if billing and shipping addresses are …
> feat(samsung_pay): collect customer address details form Samsung Pay based on business profile config and connector required fields

- crates/common_enums/src/enums.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/tokenization.rs
As we do not have a unique identifier to store when we save a wallet, we are unable to prevent payment method duplication. As a result, when a customer uses a saved wallet, we end up saving it again. During the next payment, the customer will see two buttons for the same wallet in the customer PML.
To address this issue, we check if the wallet is already saved. If the particular wallet is already saved, we simply update the 'last used' status for the same wallet, rather than creating a new entry. This payment method duplication check is already implemented for Apple Pay and Google Pay, and in this PR, I have extended it to include Samsung Pay as well.
-> Create a merchant connector account with google pay or samsung pay enabled
-> Enable the below config
``` …
```
> fix(samsung_pay): add payment_method_type duplication check

- .typos.toml
resolve spell check fail introduced by the following PR: https://github.com/juspay/hyperswitch/pull/7300
Note: No Testing Required
> fix(router): resolve spell check for state introduced for ISO representation

- crates/connector_configs/src/common_config.rs
- crates/connector_configs/src/connector.rs
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
- crates/router/src/connector/netcetera/transformers.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
add `merchant_configuration_id` in netcetera metadata and make other merchant configurations optional
Main PR - https://github.com/juspay/hyperswitch/pull/7347
Clippy successful locally
Test cases in Main PR
> feat(router): add `merchant_configuration_id` in netcetera metadata and make other merchant configurations optional

- api-reference/api-reference/payments/Introduction--to--payments.mdx
Corrected the tip content.
Corrected the content of the tip.
closes #7391
> docs(api-reference): fix the content of the tip

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/admin.rs
- crates/api_models/src/payments.rs
- crates/diesel_models/src/business_profile.rs
- crates/diesel_models/src/payment_intent.rs
- crates/hyperswitch_domain_models/src/lib.rs
- crates/router/src/core/payment_link.rs
- crates/router/src/core/payment_link/payment_link_initiate/payment_link.js
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types/transformers.rs
Hotfix for PR https://github.com/juspay/hyperswitch/pull/7340
`cargo clippy` output
> feat(payments): [Payment links] add configs for payment link

- crates/router/src/connector/adyen/transformers.rs
GooglePay fixed in Ayden 
```
--header 'api-key: dev_Coa5dQU6Vo2ezZrfgvAlgmDed2NjJmuW1hTcmI5uMevC27Tkp4F16r5Om4HEb9UU' \
--data-raw '{
"profile_id": null,
"setup_future_usage": "on_session", 
"customer": {
"id": "customer123",
"email": "customer@gmail.com",
"phone": "9999999999",
},
"customer_id": "customer123",
"routing": { 
"type": "single",
"data": "stripe"
},
"description": "Its my first payment …
```
> fix(connector): GooglePay fixed in Ayden 

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
- crates/hyperswitch_connectors/src/connectors/xendit.rs
- crates/hyperswitch_connectors/src/connectors/xendit/transformers.rs
Added payment webhooks for Xendit.
Payments Create 
```
--header 'api-key: dev_cNMaN85VYZFs73xmXrkiblB9jjN2UAuXGXl8ugAwC8VryKE7jdoFJ9ZAexezTBCl' \
--data-raw '{
"amount": 6500000,
"currency": "IDR",
"customer_id": "BamboraCustomer",
"billing": {
"address": { …
```
> feat(xendit): Add Payment Webhooks 

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/common_utils/src/errors.rs
- crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
- crates/hyperswitch_connectors/src/constants.rs
- crates/hyperswitch_connectors/src/utils.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/setup_intents/types.rs
- crates/router/src/core/payments/transformers.rs
This PR adds functionality to 
- Create QR image data URI for a given hex color
- Send back the border color and display text message along with the QR data in `NextActionData` - which is consumed by SDK to take next action
Described in #7405 
DuitNow is a realtime payment system which works by scanning QR codes. Displaying these QR codes has certain guidelines mentioned here - https://docs.developer.paynet.my/branding/duitnow/DuitNow%20Brand.pdf
This PR sends required data in the confirm API response which is consumed by SDK.
Tested locally by creating payment links and proceeding with DuitNow payment method.
<details>
<summary>Create a payment link (ensure DuitNow is enabled)</summary>
cURL …
> feat(connector): add functionality for transforming QR image color

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
Instead of merchant secret we were passing webhook_verification_token which caused the build to fail 
This PR raises the fix for this 
Fix the wasm changes for Xendit
No need of test (approved by @JeevaRamu0104 )
> fix(xendit): Fix wasm changes

- crates/analytics/src/auth_events/accumulator.rs
- crates/analytics/src/auth_events/core.rs
- crates/analytics/src/auth_events/metrics.rs
- crates/analytics/src/auth_events/metrics/authentication_attempt_count.rs
- crates/analytics/src/auth_events/metrics/authentication_count.rs
- crates/analytics/src/auth_events/metrics/authentication_success_count.rs
- crates/analytics/src/auth_events/metrics/challenge_attempt_count.rs
- crates/analytics/src/auth_events/metrics/challenge_flow_count.rs
- crates/analytics/src/auth_events/metrics/challenge_success_count.rs
- crates/analytics/src/auth_events/metrics/frictionless_flow_count.rs
- crates/analytics/src/auth_events/metrics/frictionless_success_count.rs
- crates/analytics/src/clickhouse.rs
- crates/analytics/src/lib.rs
- crates/analytics/src/query.rs
- crates/analytics/src/sqlx.rs
- crates/analytics/src/types.rs
- crates/api_models/src/analytics/auth_events.rs
- crates/router/src/analytics.rs
Hotfix PR
Original PR: [https://github.com/juspay/hyperswitch/pull/7433](https://github.com/juspay/hyperswitch/pull/7433)
> feat(analytics): refactor and rewrite authentication related analytics

- crates/analytics/src/auth_events.rs
- crates/analytics/src/auth_events/accumulator.rs
- crates/analytics/src/auth_events/core.rs
- crates/analytics/src/auth_events/filters.rs
- crates/analytics/src/auth_events/metrics.rs
- crates/analytics/src/auth_events/metrics/authentication_attempt_count.rs
- crates/analytics/src/auth_events/metrics/authentication_count.rs
- crates/analytics/src/auth_events/metrics/authentication_error_message.rs
- crates/analytics/src/auth_events/metrics/authentication_funnel.rs
- crates/analytics/src/auth_events/metrics/challenge_attempt_count.rs
- crates/analytics/src/auth_events/metrics/challenge_flow_count.rs
- crates/analytics/src/auth_events/metrics/challenge_success_count.rs
- crates/analytics/src/auth_events/metrics/frictionless_flow_count.rs
- crates/analytics/src/auth_events/metrics/frictionless_success_count.rs
- crates/analytics/src/auth_events/types.rs
- crates/analytics/src/clickhouse.rs
- crates/analytics/src/core.rs
- crates/analytics/src/lib.rs
- crates/analytics/src/query.rs
- crates/analytics/src/sqlx.rs
- crates/analytics/src/utils.rs
- crates/api_models/src/analytics.rs
- crates/api_models/src/analytics/auth_events.rs
- crates/api_models/src/events.rs
- crates/common_enums/src/enums.rs
- crates/router/src/analytics.rs
Hotfix PR
Original PR: [https://github.com/juspay/hyperswitch/pull/7451](https://github.com/juspay/hyperswitch/pull/7451)
> feat(analytics): add new filters, dimensions and metrics for authentication analytics

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/sandbox.toml
Added apikey auth for juspay threeds server in wasm file
> fix(dashboard): added apikey auth for juspay threeds server in wasm file

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
> fix(dashboard): Wasm fix for xendit connector

- .github/workflows/cypress-tests-runner.yml
Update Cypress Creds
wise connector failing
Ci should pass
> ci: update wise connector cypress creds

- postman/collection-dir/nmi/Flow Testcases/Happy Cases/Scenario12-Save card payment with manual capture/Save card payments - Confirm/event.test.js
- postman/collection-dir/nmi/Flow Testcases/Happy Cases/Scenario4-Create payment with Manual capture/Payments - Create/event.test.js
- postman/collection-dir/nmi/Flow Testcases/Happy Cases/Scenario5-Void the payment/Payments - Create/event.test.js
- postman/collection-dir/nmi/Flow Testcases/Happy Cases/Scenario9a-Update amount with manual capture/Payments - Confirm/event.test.js
- postman/collection-dir/nmi/Flow Testcases/Variation Cases/Scenario3-Capture greater amount/Payments - Create/event.test.js
The Postman Testcases for `nmi` connector was failing in case of Manual Capture
_**Before**_
<details>
<summary>Changes</summary>
- Previously the manually captured payments through `nmi` connector stayed in `processing` state after confirming the payment. But now, it goes to `requires_capture` state. So, making the necessary changes.
</details>
_**After**_
> fix(postman): update expected status from `processing` to `requires_capture` in payment confirmation tests

- crates/common_enums/src/connector_enums.rs
- crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
- crates/hyperswitch_domain_models/src/business_profile.rs
- crates/router/src/core/admin.rs
- crates/router/src/core/payments/transformers.rs
- card network fetch from db was not being populated in payment call resulting in sending the default value which failed the payment
- util function have been added to collect the card network from additional_payment_method_data
- ucaf_indicator is being populated for mastercard 
- profile generic update is made optional to not update the force_3ds_challenge if it is passed as null
- External authentication is disabled for Datatrans
- Create MCA(Cybersource):
- Create MCA(Netcetera):
- Create a payment call (enable external 3ds):
```
{
"amount": 499,
"request_external_three_ds_authentication": true,
"acceptance_type": …
```
> fix(router): pass card network for external 3DS from additional_payment_method_data

- crates/hyperswitch_connectors/src/connectors/coinbase.rs
coinbase wrongly shows the display name and description. this pr aims to fix that.
this is unintended.
```curl
curl --location 'http://Localhost:8080/feature_matrix' \
--header 'Accept: application/json'
```
> [!NOTE]
> i cannot add response due to it crossing max character length
> fix(connector): fix mapping of feature matrix for coinbase

- crates/analytics/src/auth_events/core.rs
- crates/analytics/src/auth_events/filters.rs
- crates/analytics/src/auth_events/metrics.rs
- crates/analytics/src/auth_events/metrics/authentication_attempt_count.rs
- crates/analytics/src/auth_events/metrics/authentication_count.rs
- crates/analytics/src/auth_events/metrics/authentication_error_message.rs
- crates/analytics/src/auth_events/metrics/authentication_funnel.rs
- crates/analytics/src/auth_events/metrics/authentication_success_count.rs
- crates/analytics/src/auth_events/metrics/challenge_attempt_count.rs
- crates/analytics/src/auth_events/metrics/challenge_flow_count.rs
- crates/analytics/src/auth_events/metrics/challenge_success_count.rs
- crates/analytics/src/auth_events/metrics/frictionless_flow_count.rs
- crates/analytics/src/auth_events/metrics/frictionless_success_count.rs
- crates/analytics/src/lib.rs
- crates/analytics/src/query.rs
- crates/analytics/src/sqlx.rs
- crates/api_models/src/analytics/auth_events.rs
- crates/api_models/src/analytics/sdk_events.rs
- crates/router/src/analytics.rs
Hotfix PR
Original PR: [https://github.com/juspay/hyperswitch/pull/7483](https://github.com/juspay/hyperswitch/pull/7483)
> feat(analytics): modified authentication queries and added generate report for authentications

- crates/hyperswitch_connectors/src/connectors/braintree/transformers.rs
HOTFIX: https://github.com/juspay/hyperswitch/pull/7471
Changed the Attempt Status Mapping of `SubmittedForSettlement` and `SettlementPending` to `Charged`
Issue Link: https://github.com/juspay/hyperswitch/issues/7472
**Postman Tests**
**1. Create Payment (AutoCapture)**
-Request
```
--header 'api-key: dev_ekPGg1GI2tBzBI98TAEWKy1FHsIxlwJVA7L9mNtIZPs3UpODWkCzDpUDE2dFM46T' \
--data-raw '{
"amount": 2500,
"amount_to_capture": 2500,
"customer_id": "abcdef", …
```
> fix(connector): [BRAINTREE] Changed Attempt Status Mapping for Braintree

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/admin.rs
- crates/api_models/src/payments.rs
- crates/diesel_models/src/business_profile.rs
- crates/diesel_models/src/payment_intent.rs
- crates/hyperswitch_domain_models/src/lib.rs
- crates/router/src/consts.rs
- crates/router/src/core/payment_link.rs
- crates/router/src/core/payment_link/payment_link_initiate/payment_link.css
- crates/router/src/core/payment_link/payment_link_initiate/payment_link.html
- crates/router/src/core/payment_link/payment_link_initiate/payment_link.js
- crates/router/src/core/payment_link/payment_link_initiate/payment_link_initiator.js
- crates/router/src/core/payment_link/payment_link_initiate/secure_payment_link_initiator.js
- crates/router/src/core/payments/transformers.rs
- crates/router/src/types/transformers.rs
This PR adds a payment link config for controlling the behavior or Submit button on payment links (`enable_button_only_on_form_ready`)
- If `enable_button_only_on_form_ready` is true - disallow incomplete form submission
- [DEFAULT and CURRENT] If false - allow incomplete form submission and throw validation errors
This helps add more granular control of the payment links UX.
Locally using local SDK changes
<details>
<summary>1. Update business profile to enable confirm button only when form is ready for submission</summary>
cURL
curl --location --request POST 'http://localhost:8080/account/merchant_1741692513/business_profile/pro_0pSrloAVzi0xbnpnP0mY' \
--data …
> feat(payment-link): add config for enabling form button only when form is complete

- crates/analytics/src/auth_events/core.rs
- crates/analytics/src/auth_events/filters.rs
- crates/analytics/src/auth_events/metrics.rs
- crates/analytics/src/auth_events/metrics/authentication_attempt_count.rs
- crates/analytics/src/auth_events/metrics/authentication_count.rs
- crates/analytics/src/auth_events/metrics/authentication_error_message.rs
- crates/analytics/src/auth_events/metrics/authentication_funnel.rs
- crates/analytics/src/auth_events/metrics/authentication_success_count.rs
- crates/analytics/src/auth_events/metrics/challenge_attempt_count.rs
- crates/analytics/src/auth_events/metrics/challenge_flow_count.rs
- crates/analytics/src/auth_events/metrics/challenge_success_count.rs
- crates/analytics/src/auth_events/metrics/frictionless_flow_count.rs
- crates/analytics/src/auth_events/metrics/frictionless_success_count.rs
- crates/analytics/src/auth_events/types.rs
- crates/analytics/src/sqlx.rs
- crates/analytics/src/utils.rs
- crates/api_models/src/analytics/auth_events.rs
Hotfix PR
Original PR: [https://github.com/juspay/hyperswitch/pull/7535](https://github.com/juspay/hyperswitch/pull/7535)
> feat(analytics): add issuer as filter for authentication analytics

- crates/common_utils/src/types.rs
- crates/hyperswitch_connectors/src/connectors/adyen.rs
- crates/hyperswitch_connectors/src/connectors/adyen/transformers.rs
- crates/hyperswitch_connectors/src/connectors/nexixpay.rs
- crates/hyperswitch_connectors/src/connectors/nexixpay/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
- crates/hyperswitch_domain_models/src/router_request_types.rs
- crates/router/src/core/payments/transformers.rs
- cypress-tests/cypress/e2e/configs/Payment/Nexixpay.js
Add zero auth mandate flow for nexixpay connector. It uses 3ds payments flow to create  mandates. 
We have to add support for zero amount CIT payments for nexixpay so that  merchants can do MIT payments with required value.
Cypress test:
Below curls should be used for testing zero auth mandates:
1. Payments CIT
```
curl --location 'localhost:8080/payments' \
--header 'api-key: dev_PczXRK73enU0k1JDyjEZ8u76iSUxrocg963jiEzfbY7z1ncgosfLvQFlRoHOcux4' \
--data-raw '{
"amount": 0,
"return_url": "https://abc.com",
"phone": …
```
> feat(connector): [Nexixpay] add setup mandate flow

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
WASM fixed in Getnet
Only WASM fix, hence no testing needed
> fix(connector): WASM fixed in Getnet

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/admin.rs
- crates/api_models/src/payments.rs
- crates/diesel_models/src/business_profile.rs
- crates/router/src/core/payments.rs
- crates/router/src/types/transformers.rs
Hotfix for [PR 7589](https://github.com/juspay/hyperswitch/pull/7589)
`cargo clippy` output ✅  (Ignore the warnings, they are not coming from the current commit)
https://github.com/user-attachments/assets/6667b2c9-45c7-4b42-a575-6b69260c448c
> feat(core): add three_ds_requestor_app_url in business_profile

- crates/hyperswitch_connectors/src/connectors/braintree/transformers.rs
Pass email in payment request body of Braintree as  it is mandatory field for sending receipts in braintree
https://github.com/juspay/hyperswitch/issues/7590
Payment Request:
```
{
"amount": 1233,
"customer_id": "abcdef",
"billing": {
"email": "guest@example.com"
}
"card": {
"card_number": "5200000000001096",
}
}
}
```
Payment Response:
```
{
"payment_id": "pay_o6SLsqlZ6J049AiPkHwW",
"merchant_id": "postman_merchant_GHAction_ec4bf644-13b4-420a-9747-5a91dc33c1b5",
"status": "requires_customer_action",
"amount": 100, …
```
> refactor(connector): [BRAINTREE] Pass email in payment requests

- crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs
Hotfix for [PR](https://github.com/juspay/hyperswitch/pull/7623) 
`cargo clippy output`
> fix(connector): [CYBERSOURCE]  change ucaf_collection_indicator for mastercard payments via netcetera

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
add wasm changes for coingate metadata
1. Create Merchant
2. Create API key 
3. Create MCA of coingate
```
curl --location 'http://localhost:8080/account/merchant_1742369861/connectors' \
--data '{
"connector_name": "coingate",
"api_key": "___"
},
{
{
"accepted_currencies": null,
"accepted_countries": null,
"minimum_amount": 0, …
```
> feat(connector): [Coingate] add wasm changes for coingate metadata

- cypress-tests/package-lock.json
- cypress-tests/package.json
Update cypress to latest version `14.2.0`
Cypress Tests should pass
> chore(cypress): bump cypress to `v14.2.0`

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
- crates/hyperswitch_connectors/src/connectors/trustpay/transformers.rs
- crates/router/src/configs/defaults/payment_connector_required_fields.rs
- Fix dynamic fields for SepaBankTransfer
- Handle error case Status mapping
- Fix wasm Changes for SepaBankTransfer
1. Create Merchant 
2. Create API Key
3. Create MCA for Trustpay
```
curl --location 'http://localhost:8080/account/merchant_1742994781/connectors' \
--data '{
"connector_name": "trustpay",
"api_key": "_//=",
"key1": "_",
"api_secret": "_"
},
{
{
"payment_method_type": "sepa_bank_transfer", …
```
> refactor(connector): [TrustPay] Fix status and wasm changes 

- crates/router/src/connector/stripe.rs
- crates/router/src/connector/stripe/transformers.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/flows.rs
The Sources API for Stripe Bank Transfer (Ach, Multibanco) got deprecated. They are supporting `/v1/payment_intents` now. Removed the pre processing implementations. Added new flow for Stripe Ach, and Multibanco bank transfer through payment_intents api.
Stripe Connector Create:
```
curl --location 'http://localhost:8080/account/merchant_1742504299/connectors' \
--data '{
"connector_label": "first_stripe",
"api_key": "abc"
},
{ …
```
> refactor(connector): [STRIPE] Bank Transfer Api Refactor

- crates/router/src/routes/admin.rs
- crates/router/src/routes/profiles.rs
- crates/router/src/services/authentication.rs
- cypress-tests-v2/cypress/support/commands.js
- cypress-tests/cypress/support/commands.js
Hotfix PR
Original PR: [https://github.com/juspay/hyperswitch/pull/7656](https://github.com/juspay/hyperswitch/pull/7656)
> refactor(authentication): modify auth for profiles and mca routes to `ApiKeyAuthWithMerchantIdFromRoute`

- cypress-tests/cypress/e2e/configs/Payment/Stripe.js
Mapping `status`, `error_code`, and `error_message` for `Stripe` Payment Processor `Sofort` Bank Transfer Payment Method as `Sofort` has been deprecated by `Stripe`.
`Stripe` Payment Processor has deprecated `Sofort` Bank Transfer Payment Method.
> refactor(ci): update `Stripe` response `status`, `error_code`, and `error_message` for deprecated `Sofort`

- api-reference/openapi_spec.json
- crates/openapi/src/routes/merchant_connector_account.rs
- crates/openapi/src/routes/profile.rs
Modified the authentication for profile and mca routes to use API Key instead of Admin API Key.
This PR has the corresponding OpenAPI spec changes.
Cannot test
Corresponding code changes are there in this PR: [https://github.com/juspay/hyperswitch/pull/7656](https://github.com/juspay/hyperswitch/pull/7656)
> refactor(openapi): update authentication for profiles and mca openapi

- README.md
Updated next steps after deployment setup on Readme
Updated next steps after deployment setup on Readme
closes : #7685 7685
> docs: Updated next steps after deployment setup on Readme

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/unified_authentication_service.rs
made provider field in ctp_service_details backward compatible
Add config to make the merchant eligible for authentication service
```shell
curl --location 'http://localhost:8080/configs/' \
--data '{
"key": "merchants_eligible_for_authentication_service",
"value": "[\"sahkal\", \"cewqcewc\", \"dqwdwljildwduoqwhduwqcqwjd\"]"
}'
```
Create merchant connector account for Ctp_visa
```shell
{
"connector_type": "authentication_processor",
"connector_name": "ctp_visa",
"auth_type": "NoKey"
}
}
'
```
Adyen
```shell
curl --location 'http://localhost:8080/account/dqwdwljildwduoqwhduwqcqwjd/connectors' \ …
```
> refactor(core): made provider field in ctp_service_details backward compatible

- api-reference-v2/openapi_spec.json
- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
- crates/hyperswitch_domain_models/src/payments.rs
- crates/router/src/core/payments.rs
Added dpa_client_id, , provider to click to pay session response
setup visa_ctp
Create merchant connector account for Ctp_visa
```shell
{
"connector_type": "authentication_processor",
"connector_name": "ctp_visa",
"auth_type": "NoKey"
},
"metadata": {
"dpa_id": "DPA-ID",
"dpa_name": "TestMerchant",
"locale": "en_AU",
"card_brands": [
"mastercard",
"visa"
],
"acquirer_bin": "BIN",
"acquirer_merchant_id": "MERCHANT-ID",
"merchant_category_code": "0001",
"merchant_country_code": "US",
"dpa_client_id": "TestMerchant"
}
}
'
```
update business profile
```shell
curl --location 'http://localhost:8080/account/sahkal/business_profile/pro_NlNPDiGljBSrdEUcIsND' \ …
```
> feat(session): Added dpa_client_id, provider to click to pay session response

- crates/storage_impl/src/errors.rs
Hotfix for original PR: [7712](https://github.com/juspay/hyperswitch/pull/7712)
A recent change in [this PR](https://github.com/juspay/hyperswitch/pull/7537) removed the usage of DomainStorageError in all the places and started using StorageError everywhere. 
Previously, DataStorage and RedisError were manually converted into StorageError based on few conditions which was missing in the mentioned PR resulting in resource_not_found being thrown as 5xx instead of 4xx.
```
StorageError::DatabaseError(i) => match i.current_context() {
DatabaseError::DatabaseConnectionError => DataStorageError::DatabaseConnectionError,
// TODO: Update this error type to encompass & propagate the missing type (instead of generic `db value not found`)
DatabaseError::NotFound => { …
```
> fix(errors): Entry not found error as 4xx instead of 5xx

- crates/router/src/configs/secrets_transformers.rs
- crates/router/src/configs/settings.rs
- crates/router/src/routes/admin.rs
- crates/router/src/routes/api_keys.rs
- crates/router/src/services/authentication.rs
Hotfix PR
Original PR: [https://github.com/juspay/hyperswitch/pull/7744](https://github.com/juspay/hyperswitch/pull/7744)
> feat(authentication): create authentications to fallback to ApiKeyAuth if AdminApiAuth fails

- api-reference/hyperswitch_intelligent_router_open_api_spec.yml
- api-reference/intelligent-router-api-reference/elimination/fetch-eliminated-processor-list.mdx
- api-reference/intelligent-router-api-reference/elimination/invalidate-elimination-bucket.mdx
- api-reference/intelligent-router-api-reference/elimination/update-elimination-bucket.mdx
- api-reference/intelligent-router-api-reference/overview.mdx
- api-reference/intelligent-router-api-reference/success-rate/fetch-entity-and-global-success-rates.mdx
- api-reference/intelligent-router-api-reference/success-rate/fetch-success-rate-for-an-entity.mdx
- api-reference/intelligent-router-api-reference/success-rate/invalidate-windows.mdx
- api-reference/intelligent-router-api-reference/success-rate/update-success-rate-window.mdx
- api-reference/mint.json
Open API reference for Intelligent router
> feat: Add open API reference for Intelligent router

- api-reference-v2/openapi_spec.json
- crates/api_models/src/admin.rs
- crates/common_types/src/payment_methods.rs
- crates/common_types/src/primitive_wrappers.rs
- crates/diesel_models/src/business_profile.rs
- crates/diesel_models/src/schema_v2.rs
- crates/hyperswitch_domain_models/src/business_profile.rs
- crates/router/src/core/admin.rs
- crates/router/src/db.rs
- crates/router/src/db/merchant_key_store.rs
- crates/router/src/types/payment_methods.rs
- v2_migrations/2024-08-28-081837_add_not_null_constraints_to_v2_columns/down.sql
- v2_migrations/2024-08-28-081837_add_not_null_constraints_to_v2_columns/up.sql
Moved `merchant_key_store` table to accounts schema.
Since `merchant_account` is already moved to schema. `merchant_key_store` must also be present there.
Other changes:
* introduced `ShouldCollectCvvDuringPayment` bool wrapper for `should_collect_cvv_during_payment` column in `business_profile`. And made it an optional field. 
* It is being made optional since it is an optional merchant config. Default is true.
Created Organization, MerchantAccount, BusinessProfile and MCA in v1 and fetched the same records in v2.
1. Create MerchantAccount in v1 (organization and profile will be created internally).
```
--data-raw '{ …
```
> refactor: move merchant_key_store table to accounts schema

- crates/diesel_models/src/query/merchant_account.rs
Modified the v1 merchant list query to list only v1 merchant accounts, v2 merchants cannot deserialize in v1 application code.
This change is required, since now, both v1 and v2 merchant accounts are stored in the same schema.
This will affect the following flows:
- list merchant accounts for user in org
- list merchant accounts (admin API)
- get single merchant id (during sign-in, to create JWT token)
- switch org for user
Fix the deserialization issues when listing merchant accounts using v1 routes.
Hit the following curls after creating a v1 merchant account and a v2 merchant account in the same organization.
The following APIs should only return v1 merchant accounts in the organization (and not the v2 merchant accounts).
```bash …
```
> refactor(users): modify query to list only v1 merchant_accounts for list v1 merchant accounts API

- crates/api_models/src/user/dashboard_metadata.rs
- crates/common_enums/src/enums/accounts.rs
- crates/router/src/core/user.rs
- crates/router/src/core/user/dashboard_metadata.rs
- crates/router/src/routes/app.rs
- crates/router/src/routes/user.rs
- crates/router/src/services/email/assets/bizemailprod.html
- crates/router/src/services/email/types.rs
- crates/router/src/types/domain/user.rs
- crates/router/src/utils/user/dashboard_metadata.rs
Hotfix PR
Original PR: [https://github.com/juspay/hyperswitch/pull/7638](https://github.com/juspay/hyperswitch/pull/7638)
> feat(users): refactor `ProdIntent` to support product-type context and merchant-scope

- config/config.example.toml
- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
- config/docker_compose.toml
- loadtest/config/development.toml
- add AT,DE,IT country for instant_banktransfer
1. Create  a Merchant account 
2. Create ApI key
3. Create trustpay MCA
```
curl --location 'http://localhost:8080/account/merchant_1744709039/connectors' \
--header 'api-key: dev_nQkG6G0Aa0WnoFVCyaJnTFbT44vJkiPKjSzG3vEEdVzhMEKnunJboev2sYPbFBbc' \
--data '{
"connector_name": "trustpay",
"api_key": "_",
"key1": "_",
"api_secret": "_"
},
{
{
"payment_method_type": "sepa_bank_transfer", …
```
> feat(configs): [Trustpay] add support for AT,DE,IT country for instant_banktransfer

- crates/hyperswitch_connectors/src/connectors/noon.rs
- crates/hyperswitch_connectors/src/connectors/noon/transformers.rs
previously, when making a 3ds card transaction via noon connector, we would get `next_action` as `null` which is not intended. and that is because, paypal response would override the transaction data. this pr fixes this by unifying both of them.
3ds transactions are expected to have an object in next action while at present, we are getting it as null for card payments and this is not intended.
closes #7831 
3ds card payment:
```curl
--header 'api-key: dev_dSMvDZeLPCEUIv7ZV4JQxAQIoTuE0kdlKZEhxK7gn15IY7WkcKKAgbvSEG8FEuOY' \
--data-raw '{
"amount": 390,
"currency": "AED",
"customer_id": "sammantest2722", …
```
> fix(connector): [noon] address `next_action_url` being `null` for cards in 3ds payment

- crates/hyperswitch_connectors/src/connectors/noon.rs
- crates/hyperswitch_connectors/src/connectors/noon/transformers.rs
Reverts juspay/hyperswitch#7832
> revert: fix(connector): [noon] address `next_action_url` being `null` for cards in 3ds payment

- crates/hyperswitch_connectors/src/connectors/noon/transformers.rs
ORIGINAL PR: https://github.com/juspay/hyperswitch/pull/7862
Fix Noon redirection.
1. create payments for cards
```
--header 'api-key: _' \
--data-raw '{
"amount": 390,
"currency": "AED",
"customer_id": "sammantest2722",
"description": "Its my first payment", …
```
> fix(connector): [noon] address next_action_url being null for cards in 3ds payment

- crates/hyperswitch_connectors/src/connectors/noon/transformers.rs
Reverts juspay/hyperswitch#7861
> revert: fix(connector): [noon] address next_action_url being null for cards in 3ds payment

- crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs
main pr - https://github.com/juspay/hyperswitch/pull/7828
> fix(connector): [Cybersource] send type selection indicator for co-batch cards

- crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
- crates/router/src/core/payments/transformers.rs
This PR filters the `error_code` and `error_message` in Payments API response to ensure HyperSwitch does not send back any 'invented' codes or messages. This is achieved by filtering such error codes and error messages are not sent back in the API response.
Details in ticket - https://github.com/juspay/hyperswitch/issues/7794 (point # 1)
This PR ensures HyperSwitch does not invent any new error codes or messages and send it back in the Payments API response. In case error codes and messages are not present, it will send back null in the response
<details>
<summary>1. Create card payment via Nexixpay (failed card txn)</summary>
cURL
--header …
> chore(payments): filter NO_ERROR_CODE and NO_ERROR_MESSAGE from payments API response

- crates/diesel_models/src/role.rs
- crates/diesel_models/src/schema.rs
- crates/diesel_models/src/schema_v2.rs
- crates/router/src/core/user_role/role.rs
- crates/router/src/db/role.rs
- migrations/2025-02-06-122415_udpate-roles/down.sql
- migrations/2025-02-06-122415_udpate-roles/up.sql
This pr will enable profile level custom creation from API and also enable org level custom role read
1 . Valid operation 
Request :
```
curl --location 'http://localhost:8080/user/role' \
--header 'authorization: Bearer JWT' \
--header 'cookie: login_token=JWT' \
--data '{
"role_scope": "profile",
"entity_type": "profile",
"groups": [
"operations_view",
"operations_manage"
],
"role_name": "profile-role-at-profile-scope"
}'
```
Response 
```
{
"role_id": "role_vcPMQVtjv0jblNi1tOxB",
"groups": [
"operations_view",
"operations_manage"
],
"role_name": "profile-role-at-profile-scope",
"role_scope": "profile",
"entity_type": "profile"
}
```
2. Invalid operation
Request 
```
curl --location 'http://localhost:8080/user/role' \
--header 'authorization: Bearer JWT' \
--header 'cookie: …
```
> feat(users): profile level custom role write

- crates/hyperswitch_connectors/src/connectors/worldpay.rs
- crates/hyperswitch_connectors/src/connectors/worldpay/transformers.rs
- crates/payment_methods/src/configs/payment_connector_required_fields.rs
This PR adds below changes
- Add required field for Worldpay card transactions - card holder name.
- Fix 3DS SetupMandate flows for Worldpay card transactions
Card holder name is a mandatory field which is required by WP during card transactions.
Fixing the 3DS SetupMandate flow for Worldpay allows merchants to consume the functionality.
<details>
<summary>1. [No3DS] Create zero amount off_session payment</summary>
cURL
--header 'api-key: dev_W87tjiH2egf7KXq7k4Z3Kr4b0DjNZKUqv7MgUxzaAaLa3RC2jREfBOzomE4DsAD7' \
--data-raw '{"amount":0,"currency":"SGD","confirm":true,"profile_id":"pro_5CNWfwHVvSY4jegnpzco","capture_method":"automatic","capture_on" …
> chore: add cardholder name as mandatory field for Worldpay card transactions

- crates/router/src/utils/user.rs
This PR updates the lineage context Redis caching logic to use a dedicated global Redis key prefix (`global`) instead of the default tenant-scoped prefixes (`public_`, `public_v2_`), causing inconsistencies between deployments (i.e., v1 and v2).
Introduced a new helper: `get_redis_connection_for_global_tenant`
- Fetches Redis connection with `key_prefix` set to `global`.
- Updated lineage context caching (`get_lineage_context_from_cache`, `set_lineage_context_in_cache`) to use the global Redis connection
This will enable [https://github.com/juspay/hyperswitch/pull/7871](https://github.com/juspay/hyperswitch/pull/7871) to work with both v1 and v2 merchant accounts.
The redis-key should now be in the format of global:LINEAGE_CONTEXT_<user_id>
Previously, lineage context was being cached …
> feat(user): use global redis key prefix for user lineage context

- crates/router/src/consts/user.rs
- crates/router/src/core/user.rs
- crates/router/src/types/domain/user.rs
- crates/router/src/types/domain/user/decision_manager.rs
- crates/router/src/utils/user.rs
Hotfix PR
Original PR: [https://github.com/juspay/hyperswitch/pull/7871](https://github.com/juspay/hyperswitch/pull/7871)
> feat(users): add support for caching and resolving last used lineage context

- crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
- crates/hyperswitch_domain_models/src/router_request_types.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/relay/utils.rs
- crates/router/src/core/utils.rs
- crates/router/tests/connectors/utils.rs
1)Added Refunds Flow for the Fpx payment Method
**Payments Create+ Confirm**
```curl --location 'http://localhost:8080/payments' \
--header 'api-key: dev_Wk9wyDK0awzbwasxKNY9XPLel7CLdp3IpLya22Qk1ou8sEWbK4TUvjGBsr9ZyAv8' \
--data '{
"amount_to_capture":1000,
"payment_method_type": "online_banking_fpx",
"online_banking_fpx": {
"issuer": "affin_bank"
}
}
}
}'
```
Response 
```
{
"payment_id": "pay_1zpdMfCeFGvoB1yKDQvN",
"merchant_id": "postman_merchant_GHAction_5da9f6fc-4e46-4134-97f6-02dc5ead936a",
"status": "requires_customer_action", …
```
> feat(connector): Fix FPX refunds for Fiuu

- crates/router/src/core/payments/helpers.rs
In the helper function `validate_payment_method_type_against_payment_method` added `Card` as a valid `PaymentMethodType` when `PaymentMethod` is `Card`
We need to support `card` as a `payment_method_subtype`
Request:
```
curl --location 'http://localhost:8080/v2/payment-methods-session/12345_pms_01967bcef78f75a08017231cb1264185/confirm' \
--header 'x-profile-id: pro_tvEpY9HoDhpoef5zuFhB' \
--header 'Authorization: publishable-key=pk_dev_cebd8389548b40edba3e0046680b54e8,client-secret=cs_01967bcef78f75a08017232bf96065e5' \
--header 'api-key: dev_3Je4VFrKJME1ETnyOu3TSzTSfwEz6lTef5BzJkeIWQFeZHhxzfa8KE1gZ0zDApCR' \
--data '{
"card": {
"card_number": "4000056655665556",
"card_exp_month": "06", …
```
> fix(router): Validate 'card' as a PaymentMethodType

- crates/hyperswitch_connectors/src/connectors/novalnet/transformers.rs
This PR allows debit card MITs through Novalnet.
Fixes the bug which allows debit card mandate creation, but does not allow MITs for the same payment method entry.
<details>
<summary>1. Create debit card off_session payment</summary>
cURL
--header 'api-key: dev_76MSBBu8s4TG6Y7Ojx5jOojVZveVEZJpr4vTtKAATvBqp8iWdzH5nfzfuDIIbw5Y' \
--data-raw '{"amount":6500,"currency":"EUR","confirm":true,"capture_method":"automatic","capture_on":"2022-09-10T10:11:12Z","customer_id":"cus_Wz8ND2QMGUTQCZBgO4Jx","email":"guest@example.com","name":"John Doe","phone":"999999999","profile_id":"pro_Z2e4ZhoVw0PTjZm7slwC","phone_country_code":"+65","description":"Its my …
> fix(connector): [Novalnet] allow debit card MITs

- crates/router/src/core/payment_methods/cards.rs
Context
https://github.com/juspay/hyperswitch/pull/7882 accidentally reverted changes made in https://github.com/juspay/hyperswitch/pull/7866, which was a merchant critical PR.
Reason:
- This might have occured due to incorrect resolution of merge conflicts in [this PR](https://github.com/juspay/hyperswitch/pull/7882)
- Create MA and an MCA with wallets
- Create a payment and  Save one wallet (eg: Paypal)
- Create a new payment intent
- List the Merchant PML again, Paypal would still be there
```bash
curl --location 'http://localhost:8080/account/payment_methods?client_secret={{client_secret}}' \
--header 'api-key: {{publishable_key}}'
```
```json
{
"redirect_url": null,
{ …
```
> fix(payment_methods): Re-revert changes done in `pr#7866` by `pr#7882`

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
This PR fixes Facilitapay payment method env that broke WASM.
WASM broke.
WASM shouldn't break now. 
closes #7957
> chore(env): fix Facilitapay connector config

- crates/common_utils/src/id_type/merchant.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_update.rs
Disable payment update via client config and allow using config if needed 
🔴  remove from config after some time and completely depricate update payment via client auth completely 
- Throw internal server error if some one tries to update via client auth (if config is not enabled) 
- Update using client auth when config is not allowed
request
```sh
curl --location 'http://localhost:8080/payments/pay_ImiqolwzntLifVgMh7eJ' \
--header 'api-key: pk_dev_bd649cb441c64b2495d01d9e01d2d8ce' \
--data-raw '{
"amount": 100,
"card_cvc":"fdsa",
"email": …
```
> fix(payment): disable payment update via client config

- docker-compose.yml
- scripts/poststart_hook.sh
The hyperswitch server would run even without the completion of migration runner polluting the data in the scarf dashboard.
helps close #7945 
#7963 raised to main for similar changes
> fix: fixes the docker setup to clean up the scarf data

- crates/diesel_models/src/authentication.rs
- crates/hyperswitch_domain_models/src/router_request_types/authentication.rs
- crates/hyperswitch_domain_models/src/router_request_types/unified_authentication_service.rs
- crates/hyperswitch_domain_models/src/router_response_types.rs
- crates/hyperswitch_interfaces/src/authentication.rs
- crates/router/src/connector/gpayments/gpayments_types.rs
- crates/router/src/connector/netcetera/transformers.rs
- crates/router/src/connector/threedsecureio/transformers.rs
- crates/router/src/core/authentication.rs
- crates/router/src/core/authentication/utils.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_response.rs
- crates/router/src/core/payments/operations/payment_status.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/core/payments/types.rs
- crates/router/src/core/unified_authentication_service/utils.rs
- crates/router/src/core/webhooks/incoming.rs
- crates/router/src/types/api/authentication.rs
- crates/router/src/types/domain.rs
- crates/router/src/types/transformers.rs
https://github.com/juspay/hyperswitch/pull/7978
> refactor(authentication): moved cavv storing from table to temp locker

- crates/router/src/connector/stripe/transformers.rs
this pr aims to fix the stripe bank redirect recurring mandate.
for context, `bancontact` recurring mandates happen via `sepa direct debit` and hence, stripe sends 2 connector mandate ids as shown below:
```json
{
"payment_method": "pm_somevalue_1",
"payment_method_details": {
"bancontact": {
"generated_sepa_debit": "pm_somevalue_2",
"generated_sepa_debit_mandate": "mandate_somevalue",
},
}
```
in order to do a recurring mandate, we are expected to pass the second connector mandate id. at the moment of me writing this, what is happening is that we pass the first connector mandate id that results in the recurring transaction to fail with error message provided in `motivation and context` section.
the fix is to pass second connector mandte id for the payment methods that requires it.
area …
> fix(connector): [stripe] fix bank redirect (`bancontact_card`) recurring mandate

- crates/api_models/src/admin.rs
- crates/api_models/src/payments.rs
- crates/diesel_models/src/business_profile.rs
- crates/diesel_models/src/payment_intent.rs
- crates/diesel_models/src/schema.rs
- crates/diesel_models/src/schema_v2.rs
- crates/hyperswitch_domain_models/src/business_profile.rs
- crates/hyperswitch_domain_models/src/payments.rs
- crates/hyperswitch_domain_models/src/payments/payment_intent.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/setup_intents/types.rs
- crates/router/src/core/admin.rs
- crates/router/src/core/payment_methods.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/helpers.rs
- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/operations/payment_update.rs
- crates/router/src/core/payments/operations/payment_update_intent.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/src/core/utils.rs
- crates/router/src/types/api/admin.rs
- crates/router/src/utils/user/sample_data.rs
- crates/router/tests/payments.rs
- crates/router/tests/payments2.rs
- migrations/2025-05-05-104001_is_iframe_redirection_enabled_to_business_profile/down.sql
- migrations/2025-05-05-104001_is_iframe_redirection_enabled_to_business_profile/up.sql
- migrations/2025-05-06-121325_is_iframe_redirection_enabled_to_payment_intent/down.sql
- migrations/2025-05-06-121325_is_iframe_redirection_enabled_to_payment_intent/up.sql
This pull request introduces support for **payment redirection inside an iframe**.
- **New flag added**:
- `is_iframe_redirection_enabled` has been introduced in both:
- `PaymentIntent`
- `BusinessProfile`
- **New `NextActionType`**:
- Added `RedirectInsidePopup` to `NextActionType` and `NextActionData` enums to support redirection within a popup (iframe-based).
- The flag is resolved in the following order of precedence:
1. The value provided in the **`PaymentIntent`** request (if explicitly set)
2. If not set in the request, the value from the **`BusinessProfile`** is used
3. If the flag is **not set in either place**, **iframe redirection is disabled by default**
| Case | PaymentIntent Flag | BusinessProfile Flag | Resulting Behavior              | …
> feat(core): Add Support for redirection inside Iframe 

- Cargo.lock
- crates/diesel_models/Cargo.toml
- crates/drainer/Cargo.toml
- crates/router/Cargo.toml
- crates/storage_impl/Cargo.toml
Changed `async-bb8-diesel crate from custom [fork](https://github.com/jarnura/async-bb8-diesel) to crates.io [version](https://github.com/oxidecomputer/async-bb8-diesel)
Closes #8026 
Ran clippy and tested multiple endpoints in the `router` binary
> chore: Move async-bb8-diesel crate to crates.io version

- crates/router/src/services/api.rs
This PR updates the regex used for forming the CompleteAuthorize URL for Worldpay post DDC submission.
Change made - the regex is updated to match any character except `/` for matching the query parameters. Earlier `/w` was being used which matched only the alphanumeric characters and underscore.
Defined in https://github.com/juspay/hyperswitch/issues/8025
Fixes the 3DS flows for Worldpay connector where consumers send the payment IDs (which may include non alphanumeric characters)
Steps for testing -
<details>
<summary>1. Create a payment with non alphanumeric characters in payment ID</summary>
cURL …
> fix(core): fix redirection for Worldpay for specific payment IDs

- crates/common_types/src/lib.rs
- crates/common_types/src/three_ds_decision_rule_engine.rs
- crates/euclid/src/dssa/graph.rs
- crates/euclid/src/frontend/ast/lowering.rs
- crates/euclid/src/frontend/dir.rs
- crates/euclid/src/frontend/dir/enums.rs
- crates/euclid/src/frontend/dir/lowering.rs
- crates/euclid/src/types.rs
- crates/euclid_wasm/src/lib.rs
add support for 3ds exemption rules in euclid crate
add
DirKeyKind::IssuerName - Name of the card issuing bank
DirKeyKind::IssuerCountry - Country of the card issuing bank
DirKeyKind::CustomerDevicePlatform - Platform of the customer's device (Web, Android, iOS)
DirKeyKind::CustomerDeviceType - Type of the customer's device (Mobile, Tablet, Desktop, Gaming Console)
DirKeyKind::CustomerDeviceDisplaySize - Display size of the customer's device (e.g., 500x600)
DirKeyKind::AcquirerCountry - Country of the acquiring bank
DirKeyKind::AcquirerFraudRate - Fraud rate of the acquiring bank
These keys would be required for setting up 3DS Exemption Rules
Possible outcomes for 3DS decision rules:
/// No 3DS authentication required
NoThreeDs,
/// Mandate 3DS Challenge
ChallengeRequested,
/// Prefer 3DS …
> feat: add support for 3ds exemption rules in euclid crate

- .github/workflows/cypress-tests-runner.yml
Update creds for noon and stripe
Ci is failing
cypress ci should pass
> chore(cypress): Update creds for stripe

- crates/hyperswitch_connectors/src/connectors/itaubank.rs
- crates/hyperswitch_connectors/src/connectors/nuvei.rs
Supported capture methods fix for feature matrix. This change is done for connector `Itaubank` and `Nuvei`.
1. Get feature matrix
```
curl --location 'http://localhost:8080/feature_matrix' \
--header 'api-key;'
```
Response
```
{
"connector_count": 63,
"connectors": [
{
"name": "ITAUBANK",
"display_name": "Itaubank",
"description": "Itau Bank is a leading Brazilian financial institution offering a wide range of banking services, including retail banking, loans, and investment solutions.",
"category": "payment_gateway",
"supported_payment_methods": [
{
"payment_method_type": "pix",
"payment_method_type_display_name": "Pix",
"mandates": "not_supported",
"refunds": …
```
> fix(connector): Supported capture methods fix for feature matrix

- crates/hyperswitch_connectors/src/connectors/fiuu/transformers.rs
- crates/hyperswitch_connectors/src/connectors/redsys/transformers.rs
Hotfix for https://github.com/juspay/hyperswitch/pull/8079
This change fixes the issues for Fiuu and RedSys integrations. Fiuu for refunds flow, and RedSys for 3ds card transactions.
Can only be tested in production.
> refactor(connector): [Fiuu] enable refund ORF feature [RedSys] fix the request structure

- crates/router/src/core/routing/helpers.rs
- crates/router/src/routes/routing.rs
Added api-key auth for routing APIs
Earlier, all routing endpoints were only JWT auth based for release build and (api-key + JWT) for local development build. Have removed the feature flag based distinction and refactored auth for all routing endpoints to be (api-key + JWT) for both builds.
Test all routing APIs with api-key auth
1. Create routing config (`/routing`)
2. List routing config  (`/routing`)
3. List active routing config (`/routing/active`)
4. List for profile (`/routing/list/profile`)
5. activate config (`routing/:id/activate`)
6. retrieve config (`routing/:id`)
7. deactivate (`routing/deactivate`)
8. default profile (`routing/default/profile`)
9. update default profile (`routing/default/profile/:profile_id`)
10. update default config (`/routing/default`)
``` …
```
> refactor: Added api-key auth for routing APIs

- README.md
- scripts/setup.sh
Enhanced the script to pre-configure a user and a dummy connector in the control center for the local setup.
replica of https://github.com/juspay/hyperswitch/pull/8093 on the main 
closes #8094
> fix: updated the docker setup

- crates/hyperswitch_connectors/src/connectors/adyen/transformers.rs
- crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs
- crates/hyperswitch_connectors/src/connectors/multisafepay/transformers.rs
- crates/hyperswitch_connectors/src/connectors/payeezy/transformers.rs
- crates/hyperswitch_connectors/src/connectors/payone/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
…source (#8031)
Hotfix for [8031](https://github.com/juspay/hyperswitch/pull/8031)
Clippy screenshot
> fix(connector): [CYBERSOURCE] fix CartesBancaires card_type for Cybersource

- api-reference/openapi_spec.json
- crates/api_models/src/organization.rs
- crates/openapi/src/routes/mandates.rs
- crates/openapi/src/routes/merchant_connector_account.rs
- crates/openapi/src/routes/payment_method.rs
- crates/openapi/src/routes/payments.rs
- crates/openapi/src/routes/profile.rs
- crates/openapi/src/routes/relay.rs
- crates/router/src/routes/admin.rs
This pr fixes semantic inconsistency with openapi_spec.json
> chore(openapi): resolve openapi  semantic inconsistency

- api-reference/api-reference/customer-set-default-payment-method/customers--set-default-payment-method.mdx
- api-reference/api-reference/event/events--list.mdx
- api-reference/api-reference/payment-methods/payment-method--set-default-payment-method-for-customer.mdx
- api-reference/openapi_spec.json
Fix wrong api methods for the endpoint resulting error is parsing.
No testing required.
> chore(mintlify): fix mintlify api methods for endpoint

- crates/external_services/src/email/ses.rs
- crates/kgraph_utils/src/error.rs
- crates/kgraph_utils/src/transformers.rs
- crates/masking/src/serde.rs
- crates/router/src/bin/router.rs
- crates/router/src/core/payments/helpers.rs
This PR addresses the clippy lints occurring due to new rust version 1.87.0
https://rust-lang.github.io/rust-clippy/master/index.html
CI checks should pass as this PR addresses clippy lints.
1. ran `rustc --version`
3. ran `just clippy` with new rust version (1.87.0)
4. ran `just clippy_v2` with new rust version (1.87.0)
> chore: address Rust 1.87.0 clippy lints

- cypress-tests/package-lock.json
- cypress-tests/package.json
This PR bumps Cypress and its dependencies to its latest versions.
closes https://github.com/juspay/hyperswitch/issues/8203
CI should pass.
> chore: bump cypress and its dependencies

- crates/router/src/core/payments/operations/payment_get.rs
Add `encoded_data` from `PaymentsRetrieveRequest` in `payment_attempt` inside `get_trackers` for PSync
Closes #8176 
No visible changes in API response. Verified that payment status changes to `succeeded`.
> fix(router): Handle encoded_data in PSync [V2]

- config/config.example.toml
- config/development.toml
- config/docker_compose.toml
- crates/router/src/configs/secrets_transformers.rs
- crates/router/src/configs/settings.rs
- crates/router/src/core/webhooks/incoming.rs
- crates/router/src/core/webhooks/incoming_v2.rs
- crates/router/src/events/api_logs.rs
- crates/router/src/routes/app.rs
- crates/router/src/services/api.rs
main PR
https://github.com/juspay/hyperswitch/pull/8214
Adding infra level information to `ApiEvent` based on config from deployment config under `infra_values`
```bash
[infra_values]
cluster = "CLUSTER"         # value of CLUSTER from deployment
version = "HOSTNAME"        # value of HOSTNAME from deployment which tells its version
```
This is required for comparing events generation and their status code for comparing success rate of 2 different versions of router
> feat(events): adding infra level components to api-events

- crates/common_utils/src/types/keymanager.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/services/kafka.rs
- crates/router/src/services/kafka/payment_intent.rs
- crates/router/src/services/kafka/payment_intent_event.rs
- crates/router/src/types/domain/types.rs
add infra-values in intent kafka events
cluster populating in payment_intent kafka event
Ran clippy locally
> refactor: add infra-values in intent kafka events

- config/deployments/production.toml
Apple pay payments for noon were failing due to PR#7921. Adding AED to the currency list for apple pay is a temporary fix for this failure.
Closes #8216
> chore: Update apple pay currency filter configs

- crates/hyperswitch_connectors/src/connectors/facilitapay/transformers.rs
- crates/hyperswitch_connectors/src/connectors/stripe.rs
- crates/hyperswitch_connectors/src/connectors/stripe/transformers.rs
- crates/hyperswitch_domain_models/src/router_request_types.rs
- crates/router/src/core/payment_methods.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/transformers.rs
- crates/router/tests/connectors/square.rs
- crates/router/tests/connectors/stax.rs
- crates/router/tests/connectors/utils.rs
Hotfix [PR](https://github.com/juspay/hyperswitch/pull/8248)
> feat(connector): [STRIPE] Added Connector Tokenization Flow for Cards

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
- crates/hyperswitch_connectors/src/connectors/worldpay.rs
- crates/hyperswitch_connectors/src/connectors/worldpay/transformers.rs
Reverts juspay/hyperswitch#8205
> revert(connector): [Worldpay] add root CA certificate

- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/connector_configs/src/connector.rs
- crates/hyperswitch_connectors/src/connectors/adyen/transformers.rs
- crates/router/src/compatibility/stripe/payment_intents/types.rs
- crates/router/src/compatibility/stripe/setup_intents/types.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/transformers.rs
1) Add Response Redirection URL for PopupURL Next Action
2) Accept Empty Metadata for Adyen 
3) Fix Coinbase Connector Config
Request
```
--header 'api-key:' \
--data-raw '{
"amount": 6500,
"is_iframe_redirection_enabled": true,
"order_details": [
{
"product_name": "Apple iphone 15",
"quantity": 1,
"amount": 6500
}
],
"request_external_three_ds_authentication": false,
"email": "user@gmail.com",
"description": "Hello this is description",
"shipping": {
"address": {
"city": "Banglore", …
```
> fix(connector): Add RedirectInsidePopup response redirection URL

- api-reference/openapi_spec.json
- crates/api_models/src/payments.rs
- crates/diesel_models/src/payment_intent.rs
- crates/diesel_models/src/schema.rs
- crates/hyperswitch_domain_models/src/payments/payment_intent.rs
- cypress-tests/cypress/e2e/configs/Payment/Commons.js
- cypress-tests/cypress/e2e/spec/Payment/00022-Variations.cy.js
- migrations/2025-05-25-185220_add-merchant_return_url-column-to-payment_intent/down.sql
- migrations/2025-05-25-185220_add-merchant_return_url-column-to-payment_intent/up.sql
- v2_migrations/2025-01-13-081847_drop_v1_columns/up.sql
- A new field in introduced in payment_intent table called extended_return_url
- This deprecate the existing return_url field since it can take string only upto length 255
- extended_return_url can now take length upto 2048 size
- write is done into the new field (extended_return_url)
- read is backward compatible (return_url as fallback)
Note: The hotfix is raised against https://github.com/juspay/hyperswitch/pull/8135
- Create a Payment with return url length smaller than 2048
```
curl --location '{{baseUrl}}/payments' \
--data-raw '{
"amount": 499, …
```
> refactor(core): introduce new field in payment_intent to handle longer return_url

- crates/router/src/core/payments/routing/utils.rs
- crates/router/src/core/routing.rs
This PR refactors the conversion from `ast::Program<ConnectorSelection>` to internal `Program` by introducing a fallible `TryFrom` implementation instead of an infallible `From`. This enables proper error propagation and logging during DSL conversion failures. 
Supporting conversion functions (`convert_rule`, `convert_if_stmt`, `convert_comparison`, `convert_value`) now return `RoutingResult<T>` instead of plain values, allowing fine-grained error handling throughout the conversion pipeline.
Also, the `core/routing.rs` logic has been updated to handle these errors gracefully by logging and skipping invalid programs during routing algorithm creation.
---
- Adds **robust error handling** for AST-to-internal structure conversion.
- Improves **diagnostic logging** on conversion failures.
- …
> refactor: add result type for Program

- .gitignore
- docker-compose.yml
- scripts/create_default_user.sh
- scripts/notify_scarf.sh
- scripts/poststart_hook.sh
- scripts/prestart_hook.sh
- scripts/setup.sh
The installation tracking system has been upgraded to capture more information, errors and behaviors during the installation period such as:
- User aborts
- Server failure errors
- Dependency errors
- Successful installations
Hotfix PR for #[8238](https://github.com/juspay/hyperswitch/pull/8238)
Tested locally using a mock server endpoint to verify the script captures all the errors and successes.
> fix: capture installation errors from one-click and docker compose setup

- postman/collection-dir/stripe/PaymentConnectors/.meta.json
Deleting API Key needs Merchant ID. So, deleting it after deleting the merchant itself yields a error message in the response which goes like `"API key not provided or invalid API key used"`, but, its solely because the Merchant ID used is not authenticated because the Merchant ID is already deleted.
The respective test case was failing in the Automated Tests Run.
The Remaining failures are because of outdated certificates and their keys. Once we update that it will be like the following
> fix(postman): fix `stripe` test cases failures

- crates/hyperswitch_connectors/src/connectors/archipel/transformers.rs
… implemented as required in the code to optional (#8342)
Hotfix for [8342](https://github.com/juspay/hyperswitch/pull/8342)
> fix(connector): [ARCHIPEL] Change connector fields that are currently implemented as required in the code to optional

- cypress-tests/cypress/e2e/configs/Payment/Billwerk.js
- cypress-tests/cypress/e2e/configs/Payment/Utils.js
Enhanced Billwerk Connector in cypress for Comprehensive Testing.
1.Savecard flow is not working (on_session & off_session) both throwing no eligible connector error
2.zero auth mandates not throwing an validation error
3.Payment method list is always empty
> ci(cypress): Add billwerk connector test in cypress

- cypress-tests/cypress/e2e/configs/Payment/Forte.js
- cypress-tests/cypress/e2e/configs/Payment/Utils.js
- cypress-tests/cypress/support/commands.js
Enhanced Forte Connector in cypress for Comprehensive Testing.
**Forte**
> ci(cypress): Add Forte connector test in cypress

- crates/hyperswitch_connectors/src/connectors/archipel/transformers.rs
yments
There was a typo while populating scheme for Archipel Applepay payments - this PR fixes it.
Impact - Due to this typo Applepay payments were failing using Mastercard, with this fix Applepay payments will work.
**_call /payments for Applepay using Mastercard via Archipel_**
```
--header 'api-key: dev_VXrUjYPz3bmPwhdGFpQ35Wc3LphojFSTYZHvohSqepoRfIsfrRsfmEN9qMdej9Qx' \
--data-raw '{
"amount": 600,
"amount_to_capture": 600,
"payment_type": "normal",
"wallet": { …
```
> feat(connector): [ARCHIPEL] fix Mastercard scheme string for Applepay payments

- cypress-tests/cypress/e2e/configs/Payment/PowerTranz.js
- cypress-tests/cypress/e2e/configs/Payment/Utils.js
Enhanced powertranz Connector in cypress for Comprehensive Testing.
PowerTranz
Alway 3ds payments are getting failed and there is no error code and message
> ci(cypress): Add test for powertranz connector

- crates/hyperswitch_connectors/src/connectors/hyperswitch_vault.rs
- crates/hyperswitch_connectors/src/constants.rs
add custom header to connector call for hitting sandbox custom pod
> fix(payment-method): add custom header to connector call for hitting sandbox custom pod

- crates/hyperswitch_connectors/src/connectors/adyen/transformers.rs
If full state name was provided such as `California` in the `billing`, which Adyen does not recognize as a valid value for the `ach` payment method. The request will succeed if the two-letter state code, for example CA is used.
In this PR, internally state is mapped to its 2-digit code for `ach` in `Adyen`.
```
--header 'api-key: dev_jHJyXP82dw0b91ZRpjKIAchhFIePhLsy3oArYC0rOE52iEeUG4377qToguBQjeN5' \
--data-raw '{
"description": "Its my first …
```
> fix(connector): 2 digit state code for ach fixed

- config/config.example.toml
- config/deployments/env_specific.toml
- crates/common_enums/src/enums.rs
- crates/common_types/src/callback_mapper.rs
- crates/router/src/core/payments/tokenization.rs
update env for network tokenization service with webhook source verification key
> fix(env): update env for network tokenization service

- crates/hyperswitch_connectors/src/connectors/trustpay.rs
- crates/hyperswitch_connectors/src/connectors/trustpay/transformers.rs
Hotfix for [PR](https://github.com/juspay/hyperswitch/pull/8455)
> fix(connector): [TRUSTPAY] Consuming Amount in PSync Response

- crates/hyperswitch_connectors/src/connectors/cybersource/transformers.rs
Passing a field `transaction_type` as 3 if its an MIT. For all others, we should be passing 1. 
Ref Doc : https://developer.cybersource.com/api-reference-assets/index.html#payments
https://docs.cybersource.com/content/dam/new-documentation/documentation/en/reference/api-fields/api-fields-so.pdf
Page : 1127
1. Payments Create - Cards (No3DS)
cURL: 
```
--header 'api-key: dev_0CBr33MgzjRaqH4yI6Y6DGxzptpf3M54jmkfo3lEk4hHuQ3k1QNvtqZOh7ULkhRY' \
--header 'Cookie: PHPSESSID=0b47db9d7de94c37b6b272087a9f2fa7' \
--data-raw '{
"amount": 700,
"connector": ["cybersource"], …
```
> fix(connector): [CYBERSOURCE] Passing pares_status for MasterCard & Visa and transaction_type field

- crates/hyperswitch_connectors/src/connectors/authorizedotnet/transformers.rs
- crates/hyperswitch_domain_models/src/router_request_types.rs
- crates/router/src/core/payments/transformers.rs
Previously we were not sending some customer's details (email, shipping details) in the payload while creating the customer and thus merchant was not able to see the details in connector dashboard, this PR passes the fields and thus visible in the dashboard as well.
Populated description as None, because passing email and description together was throwing error considering it an invalid field. Have raised a query with authorize.NET for same.
Previously we were not sending some customer's details (email, shipping details) in the while creating the customer and thus merchant was not able to see the details in connector dashboard, this PR passes the fields and thus visible in the dashboard as well.
``` …
```
> feat(connector): [AUTHORIZEDOTNET] Populated merchant required fields in setupmandate flow

- crates/hyperswitch_connectors/src/connectors/authorizedotnet/transformers.rs
Previously we were generating invoice_number randomly. This PR helps to populate it from `merchant_order_reference_id` if passed in payload.
```
--header 'api-key: dev_VXSrYYAUIpSs2kzGeGUYR2iQRuMwMW3KXTTNYetsa2AtH4WNILp16V2k0fQlijtG' \
--data-raw '{
"setup_future_usage": "on_session", 
"customer": {
"id": "sweta11",
"email": "sweta11_on@gmail.com",
"phone": "9999999999",
},
"routing": { 
"type": …
```
> feat(connector): [AUTHORIZEDOTNET] custom invoice number populated

- crates/router/src/core/payment_link/payment_link_status/status.js
This PR updates the behavior of final redirection to use top redirection when payment link's status page is present in the flow as well.
Explained in https://github.com/juspay/hyperswitch/issues/8639
Helps keep the behavior of payment links consistent.
<details>
<summary>1. Create a default payment link</summary>
cURL
--header 'api-key: dev_l9cbI5mKxdcSM5xnj2wiPTQGwO0lXCXDnHBeiCL9v9mbgQfYPdNcxSyEO8EHhaQN' \
--data '{"payment_id":"25c03e52-2ed0-4ca9-9841-5554f1857d8b","authentication_type":"three_ds","customer_id":"cus_UWxTZBStM3s2FzdDGGun","profile_id":"pro_gSujWAfJukk8ammz6aft","customer_acceptance":{"acceptance_type":"online","accepted_at":"1 …
> refactor(payment-links): use top redirection in status page

- api-reference/v2/openapi_spec_v2.json
- crates/api_models/src/payments.rs
- crates/hyperswitch_domain_models/src/lib.rs
- crates/router/src/core/payments/transformers.rs
Add feature_metadata in the payments response for revenue recovery in v2. Also added it in the open api spec
- Create a Org and MA and MCA in v2
- Create a payment in v2
```
curl --location 'http://localhost:8080/v2/payments/create-intent' \
--header 'api-key: dev_RvJ0UsrpfypkXccsGyytfee97LjWGSymDBIoR2K1zpxmUvaDScyXr9e4QH5cSUKc' \
--header 'x-profile-id: pro_xwf1Kn6sgcq34ih9HHPa' \
--header 'Authorization: api-key=dev_RvJ0UsrpfypkXccsGyytfee97LjWGSymDBIoR2K1zpxmUvaDScyXr9e4QH5cSUKc' \
--data-raw '{
"amount_details": {
"order_amount": 100,
"currency": "USD"
},
"billing": {
"address": {
"last_name": "Dough"
},
"email": "example@example.com"
},
"shipping": { …
```
> feat(payments): Add feature_metadata in the payments response for v2

- crates/hyperswitch_connectors/src/connectors/authorizedotnet/transformers.rs
customer_id length validated and server-too-busy error fixed
1. Setup Mandate with customer_id of length greater than max allowed length
```
--header 'api-key: dev_NArOvTgCUUPP6V2rDoKmK763cqpUdUs7F2vSbwbQbGd0VzyRnOyXJEpxALlP6W9O' \
--data-raw '
{
"amount": 0,
"customer": {
"email": "johndoe4@gmail.com",
"id": "customer_id_greater_than_length_20",
"name": "Manisha Slack",
"phone": "1234567890",
},
"payment_type": "setup_mandate",
"off_session": true,
"card": {
"card_number": …
```
> feat(connector): [AUTHORIZEDOTNET] customer_id length validated and server-too-busy error handled

- crates/router/src/core/payments.rs
Updated to check if the payment method is Wallet before proceeding with the wallet decryption operation.
main branch pr https://github.com/juspay/hyperswitch/pull/8744
-> Make a card payment without sending the payment method type
```
--header 'x-tenant-id: hyperswitch' \
--header 'api-key: dev_TkMYapm8vMYMcImjnH6Gkud5hM6jGVayHZTi3WSVU8eYUiMItzwlRYQlN3RtHIkD' \
--data-raw '{
"amount": 1000000,
"amount_to_capture": 1000000,
"phone": …
```
> fix(router): add payment method Wallet check for decrypted wallet payment method token logic

- Cargo.lock
- crates/external_services/Cargo.toml
- crates/external_services/src/grpc_client/unified_connector_service.rs
- crates/router/Cargo.toml
- crates/router/src/core/payments/flows/authorize_flow.rs
- crates/router/src/core/payments/flows/setup_mandate_flow.rs
- crates/router/src/core/unified_connector_service.rs
- crates/router/src/core/unified_connector_service/transformers.rs
This PR implements UCS(Unified Connector Service) Integration for SetupMandate and RepeatEverything (recurring payment) flows.
- Updated rust-grpc-client dependency to main branch
- Added log for Successful UCS connection
Create Intent for Zero mandate
```
--header 'api-key: _' \
--data '
{
"amount": 0,
"customer_id": "Customer123",
"setup_future_usage": "off_session"
}'
```
Confirm CIT (Authorisedotnet via UCS)
```
curl --location 'http://localhost:8080/payments/pay_YbaKZHAfIRvsnGpeuOcH/confirm' \
--header 'api-key: _' \
--data-raw '{ …
```
> feat(core): Hyperswitch <|> UCS Mandate flow integration

- crates/hyperswitch_connectors/src/connectors/wise/transformers.rs
connector_transaction_id of wise only support UUID format.
reference_id wont be required as value since we store the wise's transaction id.
We only send UUID to make the transaction without any error.
\
Create an MCA with Wise, do a payout transaction with below body:
```
{
"amount": 100,
"phone": "999999999",   
"bank": {
"bank_account_number": "40000000000",
"bank_routing_number": "064000020",
"bank_name": "Deutsche Bank",
"bank_country_code": "US",
"bank_city": "NewYork"
}
},
"billing": {
"address": {
"line2": …
```
> fix(connector): [Wise] send uuid as connector_transaction_id

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
Added GooglePay as a payment method type under wallets in config files
> fix(wasm): [FISERV] Added GooglePay Payment Method Type

- crates/euclid_macros/src/inner/knowledge.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/user.rs
This PR addresses the clippy lints occurring due to new rust version 1.89.0
1. just clippy
2. just clippy_v2
> chore: address Rust 1.89.0 clippy lints

- crates/api_models/src/admin.rs
- crates/hyperswitch_connectors/src/connectors/netcetera/transformers.rs
- crates/router/src/core/payments/routing/utils.rs
this pr fixes typos.
fix typos in the repo.
closes https://github.com/juspay/hyperswitch/issues/8919
nothing to test.
> fix: typos

- crates/hyperswitch_connectors/src/connectors/xendit.rs
- crates/hyperswitch_connectors/src/connectors/xendit/transformers.rs
1. CVV should be made an optional field for the connector Xendit.
2. Fix Capture Flow for Xendit
https://github.com/juspay/hyperswitch/issues/8920
Testing CURL's:
Payments Create:
Request:
```
--header 'api-key: dev_43StkeAliDdRysVQ1Bk58TfaGfqvDrRcQDIWNdnr9rx3WGPr7qnKR9ZQzdmf7P07' \
--data-raw '{
"amount": 6540000,
"currency": "IDR",
"email": "abc@def.com",
"amount_to_capture": 6540000,
"billing": {
"phone": {
"number": "8056594427",
"country_code": "+91"
}
},
"card": {
"card_exp_month": "11",
"card_exp_year": "29",
"card_holder_name": "John Doe",
"card_number": …
```
> chore(fix): [XENDIT] Make CVV Optional and fix Capture flow

- crates/hyperswitch_connectors/src/connectors/worldpayvantiv.rs
- crates/hyperswitch_connectors/src/connectors/worldpayvantiv/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
- crates/hyperswitch_domain_models/src/router_request_types.rs
- crates/router/src/core/payments/transformers.rs
- cypress-tests/cypress/e2e/configs/Payment/Worldpayvantiv.js
This Pr implements setup mandate flow, fixes card mandate flow and maps network_txn_id 
Hotfix for https://github.com/juspay/hyperswitch/pull/8929
1. Create a zero auth CIT
```curl
--header 'api-key: dev_XAp69f7Dfj6lQBbz5pPoxtnwadx2HAU7F7DTcFbWGB7EnGVHZakPNhkw3cGpmhoB' \
--data '{
"amount":0,
"payment_type": "setup_mandate",
"customer_id": "aaaa",
"card": {
"card_number": "4100200300011001", 
"card_exp_year": "50",
"card_cvc": "987"
}
},
"return_url": "https://www.google.com/", …
```
> fix(connectors): [worldpayvantiv] add setup mandate flow, map network txn id and fix mandate flow

- crates/hyperswitch_connectors/src/connectors/adyenplatform/transformers/payouts.rs
- crates/router/src/configs/defaults/payout_required_fields.rs
This PR removes any non mandatory fields from AdyenPlatform connector for card and SEPA payouts.
New list
- Card payouts
[payout_method_data.card.card_number](https://api-reference.hyperswitch.io/v1/payouts/payouts--create#body-payout-method-data-card-card-number)
[payout_method_data.card.expiry_month](https://api-reference.hyperswitch.io/v1/payouts/payouts--create#body-payout-method-data-card-expiry-month)
[payout_method_data.card.expiry_year](https://api-reference.hyperswitch.io/v1/payouts/payouts--create#body-payout-method-data-card-expiry-year)
[payout_method_data.card.card_holder_name](https://api-reference.hyperswitch.io/v1/payouts/payouts--create#body-payout-method-data-card-card-holder-name)
[billing.address.line1](https://api-reference.hyperswitch.io/v1/payouts/payouts--create#bod …
> refactor(connector): [AdyenPlatform] update required fields

- crates/hyperswitch_connectors/src/connectors/netcetera/transformers.rs
- crates/hyperswitch_domain_models/src/router_request_types/authentication.rs
- Handle response deserialization error
- three_ds_requestor_challenge_ind can be vector or string
Sanity flow with netcetra and cybersource
Profile update 
```
curl --location 'http://localhost:8080/account/merchant_1755510755/business_profile/pro_BwyTBsmG8NfDWCJNSozM' \
--header 'api-key: dev_QBdrxdNVk1Qi1kfHVAxfkkN4It60LAsZB1Zfb1SWaXePTncdQ8qS6v0ikHyHcXJy' \
--data '{
"authentication_connector_details": {
"authentication_connectors": ["netcetera"],
"three_ds_requestor_url": "https://google.com"
}
}'
```
Response
```
{
"merchant_id": "merchant_1755510755",
"profile_id": "pro_BwyTBsmG8NfDWCJNSozM",
"profile_name": "US_default",
"return_url": "https://google.com/success",
"enable_payment_response_hash": …
```
> refactor: [Netcetera] Handle response deserialization error 

- crates/hyperswitch_connectors/src/connectors/wise.rs
- crates/hyperswitch_connectors/src/connectors/wise/transformers.rs
change amount conversion from MInorUnit to FloatMajorUnit
hotfix raised against https://github.com/juspay/hyperswitch/pull/8991
Create an MCA through Wise:
Create a payout using below body:
```
{
"amount": 500,
"phone": "999999999",   
"bank": {
"bank_account_number": "40000000000",
"bank_routing_number": "064000020"
}
},
"billing": {
"address": {
"state": "NY",
},
"phone": {
"number": …
```
> fix(connector): [Wise] change amount conversion unit

- crates/hyperswitch_connectors/src/connectors/stripe/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
Partial capture issue related to stripe
Hotfix for : 
- https://github.com/juspay/hyperswitch/pull/8956
Issue : https://github.com/juspay/hyperswitch/issues/8953
On successful redirection on CARDS3ds Friction , eps bank redirect, even when fully captured the status is `partially_captured`
- `https://github.com/juspay/hyperswitch/pull/8833` this pr changes PSYNC flow and returns amount captured from payment_intent first
```rust
impl Capturable for PaymentsSyncData {
#[cfg(feature = "v1")]
fn get_captured_amount<F>(
&self,
_amount_captured: Option<i64>,
payment_data: &PaymentData<F>,
) -> Option<i64>
where
F: Clone,
{
payment_data
.payment_attempt
.amount_to_capture
.or(payment_data.payment_intent.amount_captured) // added for partial capture
.or_else(|| …
```
> fix(stripe): partial capture issue when fully captured on redirection flow like card3ds , eps bank redirect

- crates/redis_interface/src/commands.rs
- crates/redis_interface/src/lib.rs
- crates/redis_interface/src/types.rs
- crates/router/src/core/api_locking.rs
- crates/router/src/routes/payments.rs
Revert this PR:
https://github.com/juspay/hyperswitch/pull/8887
> revert: feat(core): add support for api locking with multiple keys for a single api (#8887)

- crates/hyperswitch_connectors/src/connectors/adyenplatform.rs
- crates/hyperswitch_connectors/src/connectors/adyenplatform/transformers/payouts.rs
This PR updates the webhooks for Adyen's BalancePlatform for payouts.
Main changes -
For status `booked` from Adyen, map it to
`success` for cards
`processing` for banks - reason being status `credited` is received from Adyen for successful credits.
Check the relevant issue for more details.
Enhances payout webhooks for Adyen's BalancePlatform.
<details>
<summary>1. Create a successful card payout</summary>
cURL
curl --location --request POST 'http://localhost:8080/payouts/create' \
--header 'api-key: dev_3ItwbKI2nwx45BPimAEaYP7QwnwKuC5a5GsG0aaow5wWefb62tXAcldZUrntn0jd' \
--data '{"amount":100,"currency":"EUR","profile_id":"pro_S5yvh1TfnZi2Gjv7uSUQ","customer_id":"cus_2bXx7dm7bRTOLOMlBAQi","connector":["adyenplatform"],"description":"Its my …
> refactor(connector): [AdyenPlatform] update incoming webhooks for payouts

- crates/hyperswitch_connectors/src/connectors/stripe.rs
- crates/router/src/core/payments/operations/payments_incremental_authorization.rs
Closes these issues - 
[Issue 1](https://github.com/juspay/hyperswitch/issues/9003)
[Issue 2](https://github.com/juspay/hyperswitch/issues/9004)
Populated Error Message in Incremental Authorization Flow. Added check for same amount in incremental authorization requests.
Postman Test
1. Payments - Create
Request:
```
--header 'api-key: dev_jVOnDLj6Q2nOHSSL8NIMQUws6P8WIRE9QNZ6toLt4gB7DqXuObIkVwPiXLJsY16n' \
--data-raw '{
"amount": 6500,
"amount_to_capture": 6500,
"phone": …
```
> fix(connector): [STRIPE] Populate Error Message in Incremental Authorization Flow

- crates/router/src/core/payments/transformers.rs
This PR adds support for propagating merchant_reference_id for PaymentsAuthorizeData v2.
> refactor(core): propagate merchant_reference_id for PaymentsAuthorizeData

- Cargo.lock
- crates/hyperswitch_connectors/Cargo.toml
- crates/hyperswitch_connectors/src/connectors/worldpayvantiv.rs
- crates/hyperswitch_connectors/src/connectors/worldpayvantiv/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
This Pr fixes the following
1.Maps cnp_txn_id to connector_transaction_id in error responses when cnp_txn_id is present.
2.Enforces maximum length validation for customer_id and connector_request_reference_id.
3.Maps merchant_order_reference to customer_reference. Since we currently don’t accept any customer-provided ID, merchant_order_reference is used as the customer_reference.
<details>
<summary> Test Payment Reference ID</summary>
</br>
<details>
<summary> Payment Create without passing payment_id </summary>
```
--header 'api-key: dev_N4Kk872pMhxmIKSazZbKqAzQfpHKxRtRKqB6JHDvd2Dy3yvBeIjvbRNfP7CMpNw0' \
--data '{
"amount":100,
"confirm": …
```
> fix(connectors): [worldpayvantiv] map cnp_txn_id to connector_txn_id and enforce max length for customer_id and connector_request_reference_id

- crates/router/src/core/refunds.rs
Before refund sync process tracker task was using pt_mapping_{connector} for sync retries (this is config name of Psync which was incorrect) 
Fixes made in this PR - 
- We are using pt_mapping_refund_sync_{connector}
- refund sync which was using retry_sync_task so made retry_refund_sync_task which will handle the refund task
- fix refund sync workflow being incorrectly scheduled for 2nd retry attempt instead of 1st retry attempt
- ConnectorPTMapping should also be read from db , previously we were always reading only from redis
Create a process tracker config for Adyen connector
```
curl --location 'http://localhost:8080/configs/pt_mapping_refund_sync_adyen' \
--header 'api-key: _____' \
--data '{
"key": "pt_mapping_refund_sync_adyen",
"value": …
```
> refactor(core): refund sync process scheduled time

- crates/router/src/routes/app.rs
- crates/router/src/routes/payment_methods.rs
Add the payment method filter route to the V2 PaymentMethods implementation which list all available countries and currencies based on connector and payment method type.
Request:
```
curl --location 'http://localhost:8080/v2/payment-methods/filter?connector=stripe&paymentMethodType=debit' \
--header 'Authorization: api-key=dev_4DIYNBJfJIQ2Tr1wLavfp48BJvXLtHmBWdkkALwWj6U91DAjP7h2RfQmhnDMATmB' \
--header 'x-profile-id: pro_9dDVfbJRfEb7o7qxBatP' \
--header 'api-key: dev_4DIYNBJfJIQ2Tr1wLavfp48BJvXLtHmBWdkkALwWj6U91DAjP7h2RfQmhnDMATmB' \
--data ''
```
Response:
```
{
"currencies": [
"QAR",
"BMD",
"ERN",
"ETB",
"ILS",
"MOP",
"STN",
"TND",
"SRD",
"TOP",
"JMD",
"BHD",
"SSP",
"BRL",
"COP",
"KMF",
"PEN",
"SLE",
"TZS",
"KZT",
"CUP",
"MDL",
"XCD",
"BGN",
"NIO",
"BTN",
"MXN",
"FKP",
"CLF",
"OMR", …
```
> feat(payment_methods): add payment-methods/filter endpoint to list countries and currencies for connector payment method in v2

- crates/api_models/src/open_router.rs
- crates/router/src/core/routing.rs
- crates/router/src/core/routing/helpers.rs
Taged Issue
https://github.com/juspay/hyperswitch-cloud/issues/10731
This PR refactors **Decision Engine dynamic routing setup** handling inside `link_routing_config` and `create_specific_dynamic_routing_setup` to improve reliability when updating dynamic routing configs.
1. **Added `enable_decision_engine_dynamic_routing_setup` import**
* Alongside `update_decision_engine_dynamic_routing_setup` in `helpers.rs`.
2. **Enhanced error handling for SuccessRate & Elimination routing configs**
* Now, we first attempt to update the DE config via `update_decision_engine_dynamic_routing_setup`.
* If the update fails, we gracefully fallback to **enabling** the config using `enable_decision_engine_dynamic_routing_setup` with parsed payloads:
* `SuccessBasedRoutingConfig`
* `EliminationRoutingConfig` …
> fix(routing): activating multiple configs in decision engine

- crates/hyperswitch_connectors/src/connectors/vgs/transformers.rs
- Change VGS auth type from BodyKey to SignatureKey
- [] This PR modifies the API contract
Closes #9067 
Request:
```
curl --location 'http://localhost:8080/v2/connector-accounts' \
--header 'x-merchant-id: cloth_seller_v2_WmQmWko8QabakxqCypsz' \
--header 'x-profile-id: pro_vnTuyThRZPNGRWjIHrIt' \
--header 'Authorization: admin-api-key=test_admin' \
--data '{
"connector_type": "vault_processor",
"connector_name": "vgs",
"api_key": "[REDACTED]",
"key1": "[REDACTED]",
"api_secret": "[REDACTED]"
},
"frm_configs": null,
"connector_webhook_details": {
"merchant_secret": ""
},
"profile_id": "pro_vnTuyThRZPNGRWjIHrIt"
}' …
```
> fix(connector): Use SignatureKey for VGS auth_type

- crates/connector_configs/src/connector.rs
- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
> fix(wasm): [dwolla] fix WASM changes

- crates/hyperswitch_connectors/src/connectors/authorizedotnet/transformers.rs
Fixed customer ID population in the Authorize flow.
- Previously, when passing customer details for normal payments, the createConnectorCustomer flow correctly created the customer.
- However, in the `Authorize` flow, we were passing the payment_id as the customer_id. If the length validation failed, a random string was being passed instead.
- This resulted in a random string always being sent as the customer_id, which caused a new customer to be created on Authorize.NET’s dashboard for every transaction.
- As a result, duplicate customers were being created.
Fix:
- Updated the flow to pass the correct customer_id in the customer details instead of payment_id.
- This prevents duplicate customer creation on Authorize.NET.
```
--header …
```
> fix(connector): [AUTHORIZEDOTNET] customer id population fixed in authorize flow

- crates/hyperswitch_connectors/src/connectors/wise.rs
Add RSA SHA 256 source verification for webhook in Wise
- Add webhook secret in MCA (Wise):
- Setup webhook Url in Wise Dashboard:
- Create a payout
- Should receive a webhook status update on merchant's end
> feat(connector): [Wise] Add webhook source verification

- crates/hyperswitch_connectors/src/connectors/payload.rs
- crates/hyperswitch_connectors/src/connectors/payload/transformers.rs
- cypress-tests/cypress/e2e/configs/Payment/Payload.js
this pr introduces 0 dollar mandate (setup mandate) for payload connector.
feature coverage. closes https://github.com/juspay/hyperswitch/issues/9109
Payment Method Id:
<details>
<summary>CIT</summary>
```sh
--header 'api-key: dev_uGs7ayYh5hoENIMQ43lMkQGC2i863OXlIg5XhqxcyfaKjNYcOtUv1YRrUTYuD1WW' \
--data-raw '{
"amount": 0,
"customer_id": "payload_connector_test", …
```
> feat(connector): introduce setup mandate flow for payload

- crates/router/src/core/admin.rs
When deleting a merchant account, the code previously included a direct call to the **Decision Engine (DE)** to remove the merchant configuration (`delete_decision_engine_merchant`). This was gated behind the `dynamic_routing` and `v1` feature flags and executed synchronously within the merchant deletion flow.
* **Removed** the in-place DE cleanup logic inside `merchant_account_delete`.
* Merchant deletion in the Decision Engine will now be handled separately instead of being triggered inline.
* Merchant deletion continues to work as expected.
* Decision Engine merchant cleanup is no longer triggered directly during merchant deletion.
* Any required DE sync/cleanup should be handled through  explicit decision engine flows.
**Curls and Responses**
merchant_create
``` …
```
> refactor(dynamic_routing): remove delete_merchant for DE

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
fixes connector metadata, again.
/crates/connector_configs/toml/sandbox.toml
/crates/connector_configs/toml/development.toml
/crates/connector_configs/toml/production.toml
some of the things that were to be working did not work as expected which is why this pr had to be raised.
should close https://github.com/juspay/hyperswitch/issues/8957
> fix(metadata): fix nordea metadata again

- crates/api_models/src/admin.rs
- crates/common_enums/src/connector_enums.rs
- crates/hyperswitch_domain_models/src/business_profile.rs
- crates/router/src/core/admin.rs
Enable configuration of extended authorization through the profile update call, and include supported payment methods and payment method types for extended authorization.
Enable extended authorization with profile update and check the DB if the value is updated 
```sh
curl --location 'http://localhost:8080/account/postman_merchant_GHAction_e8cb56a4-d7d8-4b59-b473-ea6c73407b9e/business_profile/pro_l2YKZKI9wJBFXtc00kqX' \
--header 'api-key: dev_pr8cBJl1V1iongZwdaz0MSLFtzg36x2ID74MUNxqVrk88OxaD1FCDEAcoqyhqSjB' \
--data '{
"always_request_extended_authorization": true
}'
```
Response
```
{
"merchant_id": "postman_merchant_GHAction_e8cb56a4-d7d8-4b59-b473-ea6c73407b9e",
"profile_id": "pro_l2YKZKI9wJBFXtc00kqX",
"profile_name": "US_default", …
```
> fix(core): add extended authorization to profile update and add supported payment method types 

- crates/router/src/core/payments/operations/payment_confirm.rs
- crates/router/src/core/payments/operations/payment_create.rs
- crates/router/src/core/payments/transformers.rs
This PR updates the BIN lookup override logic in payment transformers.rs to ensure payment_method_type is overridden only for Card payment methods.
This allows performing MIT wallet transactions for migrated wallet tokens.
Locally
<details>
<summary>Run wallet migration</summary>
cURL
curl --location --request POST 'http://localhost:8080/payment_methods/migrate-batch' \
--form 'merchant_id="merchant_1756795715"' \
--form 'merchant_connector_ids="mca_6wrjYYbE1zrrFSmbB0CJ"' \
--form 'file=@"wallet-migration.csv"'
Response
[
{
"line_number": 1,
"payment_method_id": "pm_edmFuErgTu8rvVwUtdTg",
"payment_method_type": "google_pay",
"customer_id": "e4c4a19c2f92c9b61a65d1b1d31bdab9",
"migration_status": "Success",
"card_number_masked": …
> fix(payments): override payment_method_type only for cards

- crates/hyperswitch_connectors/src/connectors/adyen/transformers.rs
Passing shopperReference as "Moto" if paymentChannel is being sent as Moto
1. Payments - One-off
cURL: 
```
--header 'api-key: dev_bZNtom2bqG07oqTtUo4Yj6Jj5juI2FAN7xD6DUQdM4ARrHqZMNhKwNQQuY1bet2A' \
--data-raw '{
"payment_channel": "mail_order",
"connector": ["adyen"],
"amount_to_capture": 10000, …
```
> feat(connector): [ADYEN] Add Support for MOTO Payments

- crates/router/src/core/payments/operations/external_vault_proxy_payment_intent.rs
- reference of payment_method_id was taken payment attempt but now it will be taken from payment_data
- payment attempt doesn't contain the context of payment_method_id before update tracker
- thus, this check was invalid
Testing needed with Proxy module in Postman
Create an MCA with Adyen:
Create an MCA with VGS:
Enable VGS in profile:
```
curl --location --request PUT '{{baseUrl}}/v2/profiles/{{profile_id}}' \
--header 'x-merchant-id: cloth_seller_guNbcoZfVazM1louchMU' \
--header 'Authorization: admin-api-key={{admin_api_key}}' \
--data-raw '{
"is_external_vault_enabled": true,
"external_vault_connector_details": {
"vault_connector_id": "mca_E1POF4A5tJlT6jTRBcdh",
"vault_sdk": "vgs_sdk"
}
}'
```
Create a payment (saved card flow):
```
curl …
```
> fix(core): change condition for updating payment method status

- crates/hyperswitch_connectors/src/connectors/authorizedotnet/transformers.rs
Reverts juspay/hyperswitch#9079
If a customer profile is not created during the Authorize call, the customer_profile_id and customer_payment_profile_id are not returned in the transaction response. As a result, the connector_mandate_id is populated as null, causing subsequent MIT transactions with "payment_type": "normal" to fail.
To avoid this issue, we are reverting this PR.
Impact of revert:
Reverting will ensure MIT transactions work as expected, but it will lead to two customer records being created in the Authorize.NET dashboard — one with the customer_id we pass, and another with a randomly generated ID.
> fix(connector): Revert [AUTHORIZEDOTNET] customer id population fixed in authorize flow

- crates/router/src/core/webhooks/incoming.rs
This PR fixes the state update for `payout_attempt` where latest status resides. This fixes the bug mentioned in https://github.com/juspay/hyperswitch/issues/9278
This change will allow the outgoing webhooks for payouts to receive the right status.
<details>
<summary>1. Create a successful payout</summary>
cURL
curl --location --request POST 'http://localhost:8080/payouts/create' \
--header 'api-key: dev_o0Eo3tL2RDhcX3AzI9w5G5IguQslT7UDDYHne7W6QqjdBbQboNBTbHhW2ZuHFLIJ' \
--data-raw '{"amount":100,"currency":"EUR","profile_id":"pro_BAzWgR1xTKZGtzWKCUea","customer":{"id":"cus_yvCM0YPCw76nC5Dj2Kwm","email":"new_cust@example.com","name":"John Doe","phone":"999999999","phone_country_code":"+65"},"connector":["adyen"],"description":"Its my first …
> fix(payout): send latest status in outgoing webhook notifications during IncomingWebhook flow

- crates/hyperswitch_connectors/src/connectors/nuvei/transformers.rs
Return Network transaction if from connector Response
- NOTE: we need to ask nuvei to return `external_scheme_transaction_id` during integration.
<details>
<summary> See returned NTID in the connector payment response</summary>
```json
{
"amount": 4324,
"capture_method":"automatic",
"acceptance_type": "online",
"accepted_at": "1963-05-03T04:07:52.723Z",
"online": {
"ip_address": "in sit",
"user_agent": "amet irure esse"
}
},
// "order_tax_amount": 100,
"payment_type":"setup_mandate",
"connector":["nuvei"],
"customer_id": "nidthhxxinn",
"description": "hellow …
```
> feat(nuvei): Map NTID for nuvei payment responses

- crates/router/src/core/payments/routing.rs
- crates/router/src/core/payouts.rs
- crates/router/src/core/payouts/helpers.rs
- crates/router/src/core/utils.rs
Hotfix for https://github.com/juspay/hyperswitch/pull/9277
> fix(payout): use billing address in payment_methods

- crates/router/src/core/payouts.rs
Hotfix for [PR](https://github.com/juspay/hyperswitch/pull/9262)
> feat(payouts): Mapped Default Values to  Unified Error Code and Message

- config/config.example.toml
- config/deployments/integration_test.toml
- config/deployments/production.toml
- config/deployments/sandbox.toml
- config/development.toml
- config/docker_compose.toml
- crates/hyperswitch_connectors/src/connectors/checkout.rs
- crates/hyperswitch_connectors/src/connectors/checkout/transformers.rs
- crates/hyperswitch_connectors/src/utils.rs
- crates/hyperswitch_domain_models/src/router_request_types.rs
- crates/router/src/core/payments/transformers.rs
- loadtest/config/development.toml
Integrated CIT/MIT and setup mandate flow.
Added `setup_future_usage` to `PaymentsSyncData` to support mandate payments.
For mandate flows, the source_id (connector mandate ID) must be stored in the MandateReference. To identify whether a payment is mandate-based, we need the setup_future_usage field.
CIT/MIT:
<details>
<summary>CIT </summary>
Request
```
{
"amount": 100,
// "payment_type": "setup_mandate",
"customer_id": "chec",
"all_keys_required": true,
"description": "hellow world",
"billing": {
"address": {
"zip": "560095", …
```
> feat(connector): [checkout] Add mandate flow

- crates/hyperswitch_domain_models/src/mandates.rs
- crates/router/src/core/debit_routing.rs
- crates/router/src/core/payments.rs
- crates/router/src/core/payments/retry.rs
- crates/router/src/types/api.rs
- crates/router/src/types/api/fraud_check.rs
Added action type in ConnectorRoutingData (NT with ntid, Card with ntid, Connector mandate).
We are storing all the instances of connector routing data with different action types.
During retry it will pick the top element in the list and will try to do payment with the mandate_reference_id that will be fetched from action type.
Solution doc: [link](https://docs.google.com/document/d/1SuIfFOahN8Y5bOUb_O3QUmwmpioJ26q97huAwT9bCR4/edit?usp=sharing)
```
pub struct ConnectorRoutingData {
pub connector_data: ConnectorData,
pub network: Option<common_enums::CardNetwork>,
pub action_type: Option<ActionType>,
}
pub enum ActionType {
NetworkTokenWithNetworkTransactionId(NTWithNTIRef),
CardWithNetworkTransactionId(String), // Network Transaction Id
#[cfg(feature = "v1")] …
```
> feat(core): [Retry] MIT Retries

- crates/router/src/services/email/assets/welcome_to_community.html
Updated quarterly roadmap and slack invite URL's in `welcome_to_community.html` file which is sent as the email body whenever a user signs up.
> refactor(users): update url and text in welcome email

- crates/hyperswitch_connectors/src/connectors/peachpayments/transformers.rs
- crates/payment_methods/src/configs/payment_connector_required_fields.rs
Closes this [issue](https://github.com/juspay/hyperswitch/issues/9392)
Fixed bugs and added cypress test
1. Made sensitive informations as Secret.
2. Resolved Deserialization error in Payments Response
3. Removed unnecessary structs
Postman Test
1. Previously error response from connector end was getting deserialization error but now it's getting deserialized
Payments - Create:
Request:
```
--header 'api-key: dev_4XwGvSX1WUNBozVTSoR0qBIPamQg9lArgmef44Z4m5onvvCWRQwGtm7vlkzprgCe' \
--data-raw '{
"amount": 4510,
"customer": {
"id": "customer123",
"name": "John …
```
> fix(connector): [Peachpayments] Fix Bugs

- crates/common_enums/src/connector_enums.rs
- crates/hyperswitch_connectors/src/connectors/adyenplatform/transformers/payouts.rs
Add acknowledgement in adyen for incoming webhooks by sending status 200.
We need to create two profiles having same adyen account, both the profiles should return 200 to webhooks even if it doesnt belongs to them.
here i made two profiles: 
```
pro_JcW9GqodbWptCntfDiiJ : mca_kAzlkhIkGnErSSc3L6Xr
pro_4vFskA1mTL8nf81s9Fzq : mca_4F3FOjPSWuvclkKoiG06
```
Making below payments API:
```
--header 'api-key: dev_**' \
--data-raw '{
"amount": 700,
"customer_id":"StripeCustomer",
"amount_to_capture": 700,
"email": "dg@example.com", …
```
> feat(router): Handle incoming webhooks adyen

- crates/hyperswitch_domain_models/src/payment_method_data.rs
- crates/router/src/core/payouts.rs
- crates/router/src/core/payouts/transformers.rs
This PR fixes the missing additional payout method details in the response when using stored payment methods (via PSP tokens) for processing payouts.
Sends back additional payout method details (if they exist) when using PSP tokens for processing payouts.
<details>
<summary>1. Migrate payment method</summary>
cURL
curl --location --request POST 'http://localhost:8080/payment_methods/migrate-batch' \
--form 'merchant_id="merchant_1758125250"' \
--form 'merchant_connector_id="mca_k6axPokgVgx67z9hmNkj"' \
--form 'file=@"tokens__migrate.csv"'
[tokens__migrate.csv](https://github.com/user-attachments/files/22390753/tokens__migrate.csv)
Response
[
{
"line_number": 1,
"payment_method_id": "pm_YspT9VnuMG0XecrqkhZs",
"payment_method_type": …
> fix(payouts): populate additional payout method data during recurring payouts

- crates/hyperswitch_connectors/src/connectors/nexixpay/transformers.rs
Mandatorily send cvv to nexixpay card payments.
```
--header 'api-key: **' \
--data-raw '{
"amount": 3545,
"payment_method_data": { 
"card": {
"card_number": "4349 9401 9900 4549",
"card_exp_month": "05",
"card_exp_year": "26",
"card_cvc": "396"
}
},
"setup_future_usage": "on_session", 
"customer": {
"id": "customer123",
"email": "customer@gmail.com",
"phone": "9999999999",
}, …
```
> fix(connectors): [Nexixpay] send cvv in nexixpay requests

- crates/connector_configs/toml/development.toml
- crates/connector_configs/toml/production.toml
- crates/connector_configs/toml/sandbox.toml
Add wasm field to collect merchant secret for payout webhook integration
Needs to be tested with dashboard
> feat(euclid_wasm): add wasm changes for payout webhooks

- crates/router/src/core/webhooks/incoming.rs
Hotfix for https://github.com/juspay/hyperswitch/pull/9508
> fix(webhooks): move webhook acknowledge config to cover early deserialization errors

- crates/analytics/src/sqlx.rs
- crates/hyperswitch_connectors/src/connectors/authorizedotnet/transformers.rs
- crates/hyperswitch_connectors/src/connectors/globalpay/requests.rs
- crates/hyperswitch_connectors/src/connectors/globalpay/response.rs
- crates/hyperswitch_connectors/src/connectors/nexixpay/transformers.rs
- crates/hyperswitch_connectors/src/connectors/payload/responses.rs
- crates/hyperswitch_connectors/src/connectors/signifyd/transformers/api.rs
- crates/hyperswitch_connectors/src/connectors/worldpay/requests.rs
- crates/hyperswitch_connectors/src/connectors/worldpay/response.rs
- crates/router/src/core/fraud_check/operation.rs
- crates/router/src/core/fraud_check/operation/fraud_check_post.rs
- crates/router/src/core/fraud_check/operation/fraud_check_pre.rs
- crates/router/src/db.rs
- crates/router/src/db/kafka_store.rs
- crates/router/src/routes/app.rs
- crates/router/src/services/api/client.rs
This PR addresses the clippy lints occurring due to new rust version 1.90.0
> chore: address Rust 1.90.0 clippy lints

- cypress-tests/cypress/e2e/configs/Payment/Commons.js
- cypress-tests/cypress/e2e/configs/Payment/Cybersource.js
- cypress-tests/cypress/e2e/configs/Payment/Utils.js
- cypress-tests/cypress/e2e/spec/Payment/00032-ManualRetry.cy.js
Add happy cases + variation cases for manual retry feature
> feat(cypress): add cypress test-cases for manual retry

- crates/router/src/core/payments.rs
- crates/router/src/core/payments/operations.rs
- crates/router/src/core/payments/operations/payment_confirm_intent.rs
This feature add connector-level tokenization to Hyperswitch V2, allowing secure storage of card data as tokens at payment connectors like Braintree.
Additionally Tokenization in router is not implemented, because of temp locker mechanism which is still pending.  
For connector-level tokenization:
1.When a payment comes with raw card data and the connector supports tokenization, send the card details to the connector’s tokenization API.
2. Receive the tokenized payment method ID.
3. Use the token for the subsequent payment call.
Closes #9501 
<details>
<summary>▶ Create and Confirm Request</summary>
**Request:**
```bash
curl --location 'http://localhost:8080/v2/payments' \
--header 'x-profile-id: pro_pYmCUDflXtfYghJEbwig' \
--header …
```
> feat(payments): add tokenization action handling to payment flow for braintree

- crates/router/src/core/unified_authentication_service.rs
- crates/router/src/routes/app.rs
add new api endpoint for post authentication sync in modular authentication
Once the challenge is submitted, we get POST callback from the ACS so we need to handle the post redirection with the new api endpoint in modular authentication
Can be tested only PROD, as Sandbox mock server behaviour is different from PROD
Shouldn't affect any other flows except modular authentication
> fix(router): add new api endpoint for post authentication sync in modular authentication

- crates/euclid/src/frontend/dir.rs
- crates/euclid/src/types.rs
- crates/euclid_wasm/src/lib.rs
- crates/router/src/configs/defaults/payout_required_fields.rs
This PR adds two changes
1. Updates `Sepa` to `SepaBankTransfer` for dynamic required fields for payouts
2. Adds PayoutCurrency as a rule to be set while configuring payout routing on dashboard
Two things -
1. Allows for configuring currency as a rule for payout routing
2. Sends back required fields in the response for `sepa_bank_transfer`
<details>
<summary>Create a payout link</summary>
cURL
curl --location --request POST 'http://localhost:8080/payouts/create' \
--header 'api-key: dev_ps5hUWh9tfDFtu9IO0MAaK3tbLTAWscvZlCanmGmTELIWPYCJPWVHkUXWeEGDWig' \
--data '{"merchant_order_reference_id":"ref123","amount":213,"currency":"EUR","customer_id":"cus_uEIQdrEFaB5iVfAUSTrU","description":"Its my first payout …
> feat(payouts): add payout currency in wasm crate

- crates/router/src/core/admin.rs
- crates/router/src/core/routing/helpers.rs
https://github.com/juspay/hyperswitch/pull/9629
This pull request enhances cache management for connector creation by introducing a new mechanism to invalidate related cache entries whenever a new connector is added. The main change is the addition of the `redact_cgraph_cache` function, which ensures that outdated cgraph cache data is cleared for the relevant merchant and profile, preventing stale data issues.
**Cache invalidation improvements:**
* Added the `redact_cgraph_cache` function in `crates/router/src/core/routing/helpers.rs` to invalidate both payouts and payments cgraph cache entries for a given merchant and profile. This function uses Redis and publishes cache invalidation events.
* Integrated the `redact_cgraph_cache` call into the connector creation flow in …
> refactor(core): add cache redaction for cgraph

- crates/common_utils/src/lib.rs
Currently with Postgres@18, db connection fails. Reason being space should be percent encoded as `%20`. This encoding standards are followed across all versions of Postgres as mentioned in their [docs](https://www.postgresql.org/docs/13/libpq-connect.html#LIBPQ-CONNSTRING) as well. 
Created a API Key using Hyperswitch curls:
cURL: 
```
curl --location 'http://localhost:8080/api_keys/merchant_1759751745' \
--data '{
"name": "API Key 1",
"description": null,
"expiration": "2038-01-19T03:14:08.000Z"
}'
```
Response: 
```
{
"key_id": "dev_B0IKCHN3tOmvjIA8m30P",
"merchant_id": "merchant_1759751745",
"name": "API Key 1",
"description": null,
"api_key": …
```
> fix(database): percent-encode spaces in Postgres connection URI

- crates/hyperswitch_connectors/src/connectors/nexixpay/transformers.rs
Use same order_id or max length 18 for all payment calls associated with an merchant order. 
We need to store connector_metadata in case of MIT payments also so that MIT payments can be manually captured or cancelled later.
Curls for testing with response:
Payments create:
```
--header 'api-key: dev_n5vnntb0V5gRjNMdwTnPXweumExJV6vYon3lVNzW2BoA3F4S4V0PXDHK3lW7gWHh' \
--data-raw '{
"amount": 3545,
"profile_id":"pro_QEwjCvFhpcLC2azRNZEf",
"payment_method_data": { 
"card": {
"card_number": "4111 1111 1111 1111", …
```
> fix(connectors): [Nexixpay] MIT & order_id fix

- v2_compatible_migrations/2025-10-07-131000_add_indexes_on_id_columns/down.sql
- v2_compatible_migrations/2025-10-07-131000_add_indexes_on_id_columns/up.sql
Since `id` column is introduced as varchar for a few major tracker tables in v2, index creation was missed in v2_compatible_migrations directory. This PR includes that.
To improve DB query time.
Ran diesel migrations
> chore: create indexes on required id columns for v2 application
